### ISSUE TITLE
How can I add headers to RxMoyaProvider ? 

### ISSUE THREAD

**Issue by jorgelp94** [Moya/Moya#1003]
Hi I've been using Moya with RxSwift but I need to add some http headers to the request and I've been looking through the rxswift documentation but I can't find this. Can anyone help me with this issue please?

**Comment by gperdomor** [comment]
@jorgelp94 you can use a endpoint closure. Check this `https://github.com/Moya/Moya/blob/master/docs/Endpoints.md`

> You can add parameters or HTTP header fields in this closure. For example, we may wish to set our application name in the HTTP header fields for server-side analytics.

```swift
let endpointClosure = { (target: MyTarget) -> Endpoint<MyTarget> in
    let defaultEndpoint = MoyaProvider.defaultEndpointMapping(for: target)
    return defaultEndpoint.adding(newHTTPHeaderFields: ["APP_NAME": "MY_AWESOME_APP"])
}
let provider = MoyaProvider<GitHub>(endpointClosure: endpointClosure)
```

**Comment by jorgelp94** [comment]
@gperdomor thanks! I'll look into it
