### ISSUE TITLE
Release 8.0.3

### ISSUE THREAD

**Issue by pedrovereza** [Moya/Moya#1006]
Oh hai it's me again.

So, we have a few fixes that could be released already:

- #966 fixed the Swift 3.1 compatibility, and [some people are already trying XCode 8.3 beta](https://github.com/Moya/Moya/issues/952#issuecomment-284999253).
 **This fix is not listed in the changelog**, I think it should be. (Changelog entry added in #1010)

- #979 fixed the output of `reversedPrint`

- #1002 fixed a memory leak when stubbing

cc. @Moya/contributors

**Comment by gperdomor** [comment]
also, this changes needs to be integrated in 9.0.0 branch...

**Comment by pedrovereza** [comment]
@gperdomor I think that when we decide to release 9.0, we will merge the branch with master, so 9.0 will have everything until 8.x, plus the breaking changes for 9.0. Does that make sense?

**Comment by gperdomor** [comment]
Yes... On the other hand, do that, reduce the possibility of conflicts, we don't know how many PR will merge to master or 9.0.0, but eventually this could produce more conflicts depending on how many breaking changes was introduced in 9.0.0

**Comment by soundbites** [comment]
Any ETA on the 8.0.3 release? We're currently using the Xcode beta because the 3.1 compiler is a whole-lot faster then the 3.0 one.

**Comment by pedrovereza** [comment]
@soundbites I think we just need to get #1010 merged and we should be good to go.

**Comment by BasThomas** [comment]
@pedrovereza, is it intentionally a tag and not a release?

**Comment by pedrovereza** [comment]
@BasThomas The release script first creates a tag and then a release. It takes a while and is still running 😃
