### ISSUE TITLE
nil value in JSON POST body

### ISSUE THREAD

**Issue by philipengberg** [Moya/Moya#1007]
**Version** `8.0.2`

I feel kinda stupid to be asking the seemingly simple question, but I simply can't figure it out.

I need to post some JSON to an API endpoint, where some values need to be `nil`. Here's an example:

```json
{
    "key1": "someString",
    "key2": null
}
```

However, the `parameters` property of the `TargetType` protocol only accepts `[String, Any]?` and not `[String, Any?]?`, so how do you achieve this?

**Comment by vzsg** [comment]
Use `NSNull()` to fill that entry in your dictionary.

**Comment by philipengberg** [comment]
Thanks @vzsg. But I'm curious as to why you need to use some old `NSObject` subclass in a Swift dictionary, when we have optionals?

Also, what is the easiest way of constructing the `parameters` dictionary then? Let's say I have an object
```swift
struct LineupPlayer {
    let id: Int
    let user : _User?
}
```
doing the following
```swift
extension LineupPlayer : ParameterRepresentation {
    var representation: [String : Any] {
        return ["id": id, "user": user?.representation ?? NSNull()]
    }
```
results in a compile error `Generic parameter 'T' could not be inferred`, since the nil-coalescing operator tries to operate on two different types.

How would you recommend to do this?

**Comment by jessearmand** [comment]
To provide a default value of an optional of `[String: Any]`, you could use an empty dictionary `[:]` instead of `NSNull`.

**Comment by philipengberg** [comment]
Doing

```swift
extension LineupPlayer : ParameterRepresentation {
    var representation: [String : Any] {
        return ["id": id, "user": (user?.representation as? Any`) ?? NSNull()]
    }
```

compiles, but now I get [this error](https://github.com/Alamofire/Alamofire/issues/1693#issuecomment-285937335) 🙄  I'm so confused!

**Comment by jessearmand** [comment]
Why don't you do it as the following? Also, what is the type of `representation`? Is it the same as `LineupPlayer' representation?

```swift
/// What is the expected type of user?.representation

extension LineupPlayer : ParameterRepresentation {
    var representation: [String : Any] {
        return ["id": id, "user": user?.representation as? [String: Any] ?? [:]]
    }
}
```

**Comment by philipengberg** [comment]
It's just a `protocol`

```swift
protocol ParameterRepresentation {
    var representation : [String : Any] { get }
}
```

Because the API only accepts `null` not `{ }`, when there is no value @jessearmand.

**Comment by jessearmand** [comment]
Alright, understood. It compiles, but there's an error? or a warning? 

If it's a warning I don't think that is an issue since that is what you're doing, coercing `[String: Any]` to `Any` and using `NSNull` as a default (which is a different type from `[String: Any]`.

**Comment by philipengberg** [comment]
I got it working now. Thanks everyone 🙏

**Comment by sunshinejr** [comment]
Great! Could you post your fix to the problem here as well, @philipengberg? Might be helpful for other people in the future.

**Comment by levibostian** [comment]
Leaving this here as reference in case others would find it useful. I was able to use the comments on this issue to help me with my problem of sending the value `nil` as a parameter value in my network request body. 

Moya version: 12.0.1
Swift version: 4.2

```swift
struct Contact {
    let name: String 
    let email: String?
} 

/**
 API requires body of JSON to be in format: 
  {
    "contacts": [
        {"name": "Name Here", "email": nil}
    ]
  }

It requires nil to be used if the email field does not exist locally.
*/

let contacts: [Contact] = getContacts()

var contactsRequest = [
    [String: Any]
]()
for contact in contacts {
    contactsRequest.append([
        "name": contact.name,
         "email": (contact.email as? Any) ?? NSNull()
    ])
}

let parameters = ["contacts": contactsRequest]

// Use `parameters` in `TargetType` for Moya request body. 
```
