### ISSUE TITLE
Should I share the RxMoyaProvider with multiple requests?

### ISSUE THREAD

**Issue by PMExtra** [Moya/Moya#1008]
I want to know if I storage a RxMoyaProvider and share it with multiple requests, is there any problem? (example: Can I start multiple requests with the same provider at the same time?)

In other words, if I have very intensive requests, should I init and deinit Provider for each request? Do this reduce performance?

**Comment by gperdomor** [comment]
no, you not need create a provider for each request... You need only one provider :D...
