### ISSUE TITLE
Support RxSwift's Single

### ISSUE THREAD

**Issue by andreyfel** [Moya/Moya#1011]
Since RxSwift released version 3.3 which adds support for Single observable, it would be nice if Moya supports this concept.

So, RxMoyaProvider should be able to return Single<> Instead of Observable<>, because ideologically it is more correct, because we emit only one response.

**Comment by BasThomas** [comment]
Feel free to take a stab at implementing this! Would this be a breaking change or would/should it coexist with the `Observable`-implementation?

**Comment by damienrambout** [comment]
It would probably be a breaking change since `request(_ token: Target)` would now return a `Single<Response>` (instead of `Observable<Response>`).
Otherwise, I think `Single` is pretty much the same as a regular `Observable`.

**Comment by AndrewSB** [comment]
`Single<>` sounds incredible! I brought something similar up as an issue a few months ago, I'm so excited they implemented something that solved the same problem.

I'll take a shot at this 😄

**Comment by AndrewSB** [comment]
Implemented in #1020
