### ISSUE TITLE
Can you provide retry option in your library 

### ISSUE THREAD

**Issue by iOSUser110** [Moya/Moya#1022]
if request fails then show the alert with option retry

**Comment by BasThomas** [comment]
Would you like the user of your app to retry the request? You can do that yourself when a request has failed.

**Comment by AndrewSB** [comment]
Also, if you're using ReactiveMoya/RxMoya, they both include built in ways of retry failed requests

**Comment by iOSUser110** [comment]
For Reactive/Rx Moya I have to use whole swift coding in Reactive. Right ?
Or can  I use  Reactive/Rx Moya in normal swift  ?

**Comment by BasThomas** [comment]
You should be able to use Reactive / Rx just for the retrying part, no need to use it in your app as a whole. :)
