### ISSUE TITLE
is Moya support cancel request?

### ISSUE THREAD

**Issue by nguyentrai2011** [Moya/Moya#1023]
I'm trying to find cancel request method in Moya but seem it's not support. Let me know if i missing something from document.

**Comment by BasThomas** [comment]
Yes, that's possible! Have a look at the [providers docs](https://github.com/Moya/Moya/blob/cb99411423b6e9b292f9f238bef1969f406793ff/docs/Providers.md#providers):

> That's it! The `request()` method returns a `Cancellable`, which has only one public function, `cancel()`, which you can use to cancel the request.

**Comment by nguyentrai2011** [comment]
@BasThomas thanks, i got it
In my case, i call request_1, but this not response, i continue call request_2, so i want canceled request_1 (mean only 1 request available at the same time). Do we have any property or method to do that?

**Comment by bestwnh** [comment]
@nguyentrai2011 when you cancel a request, you got a underlying error response.

**Comment by nguyentrai2011** [comment]
@bestwnh i think this way not make sense in search function. Before i call request_2, i check is there any request at this time, if have, i'll canceled all.

**Comment by bestwnh** [comment]
@nguyentrai2011 You could store the request_1 like
```swift
let request_1 = MoyaRequestXXXXX
```
then before you call request_2 call, just call `request_1.cancel()`. 
You also can add the request into an array. Then before you make new request, just use `requestArray.forEach({ $0.cancel() })`.

**Comment by nguyentrai2011** [comment]
@bestwnh i got it, thanks. I ask to make sure did Moya support or not this feature because i see we have Manager(type: Alamofire.SessionManager) in MoyaProvider.

**Comment by bestwnh** [comment]
@BasThomas Is the SessionManager can make a better solution for this situation?

**Comment by BasThomas** [comment]
Unfortunately, I don't know.

**Comment by sunshinejr** [comment]
If you need it rather universal, meaning that at any moment in the app, only 1 request can be fired up at once, you would need to implement your own logic for that, using e.g. `OperationQueue`. 

However, if you want it for only one, special case, you could make use of `requestClosure`. You could fire up `request_1` in that closure with a check that you are firing `request_2`. Now based on the response from `request_1`, you can decide whether `request_2` should be performed or not using [this closure](https://github.com/Moya/Moya/blob/master/Sources/Moya/MoyaProvider.swift#L34). Unfortunately this way you probably can't propagate the response from `request_1` easily and thus this is a workaround.

**Comment by nguyentrai2011** [comment]
i think the way of @bestwnh is good & easy for me now thanks all
