### ISSUE TITLE
Moya（8.0.0-beta.6）compiler error

### ISSUE THREAD

**Issue by jianghongyu00** [Moya/Moya#1025]
I use cocoapods install moya, after of 'pod install' ,compiler error:module file's minimum deployment targer is ios9.0 v9.0, but my iOS Deployment Target is 9.0  and Alamofire is 4.0.1

**Comment by BasThomas** [comment]
Can you please post your Podfile and its [dependency graph](https://github.com/CocoaPods/CocoaPods/issues/3611#issuecomment-106081707)?

**Comment by jianghongyu00** [comment]
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ’9.0’
use_frameworks!

target 'BeautifulApp' do
    pod 'Alamofire',    '~>4.0.0'
    pod 'Moya’,  	‘~>8.0.0-beta.1'
end

**Comment by BasThomas** [comment]
What if you only add `pod Moya`, removing Alamofire? Alamofire is included with Moya. And what is your deployment target in Xcode?

**Comment by jianghongyu00** [comment]
After removing Alamofire ，can run，thank you！
