### ISSUE TITLE
why not error, Received empty network response for  xxxxx

### ISSUE THREAD

**Issue by zhaoyunyi** [Moya/Moya#1026]
i get no error onError(), when i close network
but i get debug with moya *Received empty network response for *
how handle this error , why not return this error

**Comment by BasThomas** [comment]
Can you give us a code example?

**Comment by zhaoyunyi** [comment]
wildListViewModel.loading
            .subscribe(onNext: { [weak self] (items: ResultArray<Model>) in
                
                if let strongSelf = self {
                    if items.code == ResultAPICode.success.rawValue {
                        if let datas = items.data {
                            }
                        }
                    }
                }
            }, onError: { [weak self] (error: Error) in
                // when i close network, have no error return this
            }, onCompleted: { [weak self] in
                //when i close network, have no error return this either
            }, onDisposed: nil)
            .addDisposableTo(disposeBag)

**Comment by zhaoyunyi** [comment]
@BasThomas thank for you help

**Comment by BasThomas** [comment]
@Moya/contributors, can anyone take a look at this? Might this be a bug with our Reactive implementation?

**Comment by zhaoyunyi** [comment]
yes, you are right, it is my mistake with my Reactive implementation . but i can get error again after my onError . I have some problem for   Reactive implementation, can you help me?

    request(strongSelf.userId , strongSelf.pageSize, strongSelf.pageNo)
                        .subscribe(onNext: { (items: ResultArray<Element>) in
                            
                            if items.code == ResultAPICode.success.rawValue {
                            strongSelf.loading.onNext(items)
                        }, onError: { (error) in
                            self?.loading.onError(error) // there netError will return over agin , but can not sent this error to loading, 
                        }, onCompleted: {
                        }, onDisposed: nil)
                        .addDisposableTo(strongSelf.disposeBag)

**Comment by gmoalvarez** [comment]
I am not sure if this helps track it down but I just encountered this error as well. If I make too many simultaneous network requests they all fail. For example if I try to fetch a bunch of data at once:

provider.request(.target1).mapJSON(). map { data in 
...
}

provider.request(.target2).mapJSON(). map { data in 
...
}

provider.request(.target3).mapJSON(). map { data in 
...
}

This seems to not work for some reason. Not sure if it is related to your issue.
