### ISSUE TITLE
Scheduler issues with RxSwift

### ISSUE THREAD

**Issue by mr** [Moya/Moya#1032]
Using `Moya` 8.0.1 and `RxSwift` 3.1.0

I'm trying to make sure that `Moya` requests run on a background thread, because currently my UI gets locked up while doing requests. I've been trying to use a `ConcurrentDispatchQueueScheduler`, but invariably the `Moya` requests switch back to the main thread. Example:

```swift
MyAPI.instance.getIndex()
    .subscribeOn(ConcurrentDispatchQueueScheduler(qos: .background))
    .observeOn(MainScheduler.asyncInstance)
    .flatMap { index in /* Do some UI stuff here */ }
    .subscribe(onNext: { uiResults in /* Do something with UI results */ })
```

My `getIndex` function is just a simple

```swift
func getIndex() {
    return self.provider.request(.getIndex)
}
```

Putting a breakpoint inside the `Observable.create` part of the `RxMoyaProvider.request` function always shows `com.apple.main-thread`. This is true even if I remove the `observeOn` from above. Also any subsequent `map`s or `flatMap`s all run on `com.apple.main-thread`. Normally I would expect these to run on the `ConcurrentDispatchQueueScheduler`. This happens if I am not using `Moya`.

Any way to not lock up my UI while using `Moya`?

**Comment by AndrewSB** [comment]
So happy you've made this issue! This is a feature we were looking to implement for RxMoya. Here's the pull request: https://github.com/Moya/Moya/pull/762

Let me know if you have any other questions, or if you're interested in implementing the functionality we're missing 😄

**Comment by AndrewSB** [comment]
Let's continue discussion for this on #762, closing this for now
