### ISSUE TITLE
can not inherit MoyaError

### ISSUE THREAD

**Issue by lizhihui0215** [Moya/Moya#1033]
```swift

public enum Error: MoyaError {
    case serverError(Int, String)
}
```
this given me 2 error below
Raw type 'MoyaError' is not expressible by any literal

Type 'Error' does not conform to protocol 'RawRepresentable'

**Comment by pedrovereza** [comment]
Hey @lizhihui0215 , unfortunately Swift enums do not support inheritance. From [the docs](https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/Inheritance.html#), highlight by me:

> A class can inherit methods, properties, and other characteristics from another class. When one class inherits from another, the inheriting class is known as a subclass, and the class it inherits from is known as its superclass. **Inheritance is a fundamental behavior that differentiates classes from other types in Swift**.

[This answer on StackOverflow](http://stackoverflow.com/a/40823730) that may be helpful

**Comment by lizhihui0215** [comment]
Thx @pedrovereza if there is a way to extended the MoyaError with mine custom error

**Comment by AndrewSB** [comment]
@lizhihui0215: yes, but its not the most user friendly. Check out this issue on Result: https://github.com/antitypical/Result/issues/76, and make sure you also read the discussion they link off to in `LlamaKit`.

Come back here if you're still trying to figure out how to compose your own error type that augments `MoyaError`

**Comment by sunshinejr** [comment]
I think this should be resolved, if there are still questions about this topic, please feel free to reopen whenever.
