### ISSUE TITLE
Parameter Validation

### ISSUE THREAD

**Issue by Blackjacx** [Moya/Moya#1034]
Hey there!

what is the best place to validate input given into a target as parameter, e.g. a phone number string where the country code is missing. I think about a pre-validation in per-target basis BEFORE the request hits the network. I want to write tests for that but I couldn't find a location where I can do do the validation.

My code looks something like that:

```swift
public enum Service {
    case validatePhoneNumber(number: String)
}

extension Service: TargetType {
    public var path: String {
        switch self {
        case .validatePhoneNumber:
            return "phone"
        }
    }

    public var method: Moya.Method {
        switch self {
        case .validatePhoneNumber:
            return .post
        }
    }

    public var parameters: [String: Any]? {
        switch self {
        case .validatePhoneNumber(let number):
            return ["phone_number": number]
    }
}
```

**Comment by AndrewSB** [comment]
Hey @Blackjacx, awesome to see that you're thinking about doing some local validation before hitting the network 👌

I've used www.GitHub.com/Ben-G/Validated in the past to great effect. Basically I create a `PhoneNumber` type and I change my parameter type to be a `PhoneNumber` (`case validatePhoneNumber(number: PhoneNumber)`)

**Comment by Blackjacx** [comment]
Oh nice idea!!!! I just could create a PhoneNumberType with a failing initializer. No need for a Library - in my case at least... I think that answers my question ;-)
