### ISSUE TITLE
Carthage bootstrap failing on CI

### ISSUE THREAD

**Issue by pedrovereza** [Moya/Moya#1039]
A more descriptive error in https://circleci.com/gh/Moya/Moya/1316
> Users/distiller/Moya/carthage_test/Carthage/Checkouts/Moya/Sources/RxMoya/RxMoyaProvider.swift:2:8: **error: module compiled with Swift 3.1 cannot be imported in Swift 3.0.2**: /Users/distiller/Moya/carthage_test/Carthage/Checkouts/Moya/Carthage/Build/iOS/RxSwift.framework/Modules/RxSwift.swiftmodule/arm64.swiftmodule
A shell task (/usr/bin/xcrun xcodebuild -project /Users/distiller/Moya/carthage_test/Carthage/Checkouts/Moya/Moya.xcodeproj -scheme "RxMoya iOS" -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **

Not so verbose in https://circleci.com/gh/Moya/Moya/1319 🤔 

> A shell task (/usr/bin/xcrun xcodebuild -project /Users/distiller/Moya/carthage_test/Carthage/Checkouts/Moya/Moya.xcodeproj -scheme "ReactiveMoya iOS" -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **

I'm planing to take a deeper look on it over the weekend, but I could definitely use some help 😉

**Comment by BasThomas** [comment]
I'll see if I can help out anywhere. Exit code 65 doesn't make me happy, though. :(

**Comment by AndrewSB** [comment]
I think (after looking at this for ~20 seconds) that we need to update our circle CI to compile Moya using swift 3.1, not 3.0

**Comment by pedrovereza** [comment]
I tried a few things in branch `circle-ci-xcode-8-3`. I think bumping `Result` in `Cartfile.resolved` is enough for the original error. The status on the branch is that the compiler can't find module `Result` and I'm not sure why yet 😕

**Comment by sunshinejr** [comment]
Just a heads-up, I'm gonna look at it once my Xcode download completes 😅

**Comment by ashfurrow** [comment]
Thanks for all the help on this everyone :bow:
