### ISSUE TITLE
Moya.Response should use URLHTTPResponse class

### ISSUE THREAD

**Issue by juliengdt** [Moya/Moya#1040]
```swift
public final class Response: CustomDebugStringConvertible, Equatable {
    public let statusCode: Int
    public let data: Data
    public let request: URLRequest?
    public let response: URLResponse?
}
```

should be

```swift
public final class Response: CustomDebugStringConvertible, Equatable {
    public let statusCode: Int
    public let data: Data
    public let request: URLRequest?
    public let response: HTTPURLResponse?
}
```

[Apple HTTPURLResponse class](https://developer.apple.com/reference/foundation/httpurlresponse) is quite more interesting than simple URLResponse. 

For example we have direct access of httpHeaderFields, which can't be accessed through URLResponse class. This issue force us to forcecast (`as!`) response as a HTTPURLResponse: bad practice

## EDIT - Related Pull Request

[PR #1044 - Enhance Moya.Response by using HTTPURLResponse](https://github.com/Moya/Moya/pull/1044)

**Comment by AndrewSB** [comment]
This seems like a good idea to me @juliengdt! Do you want to try branching off `9.0.0-dev` and implementing the change? No pressure if you're not comfortable with that 😄 

The two potential hurdles I see are
1. We're currently grabbing the `URLResponse` from Alamofire, does Alamofire expose a `HTTPURLResponse` as well?
2. Some small difference b/w URLResponse and HTTPURLResponse that makes the latter unusable for some reason we haven't thought off yet

We can get a couple of reviewers on the PR to validate that its a good idea, and if they agree, we'd be more than happy to merge this in 👍

**Comment by juliengdt** [comment]
Ahoy, Ok i'll try to look at AF and if possible do the change 👍 Thanks for your reply

**Comment by BasThomas** [comment]
Seems like Alamofire does give us a `HTTPURLResponse`. 😃 https://github.com/Moya/Moya/blob/master/Sources/Moya/MoyaProvider.swift#L147

**Comment by juliengdt** [comment]
... and is "downcasted" to a simple URLResponse ... 

https://github.com/Moya/Moya/blob/master/Sources/Moya/MoyaProvider.swift#L151

The PR will be short i think 👍

**Comment by juliengdt** [comment]
I edit the issue + did the PR.

**Comment by AndrewSB** [comment]
👊
Awesome!

**Comment by juliengdt** [comment]
Ahoy everyone

This `enhancement/issue` can be close no ?

👋

**Comment by BasThomas** [comment]
As it has been implemented, yep!
