### ISSUE TITLE
Rx/ReactiveMoya does not expose queue parameter

### ISSUE THREAD

**Issue by haritowa** [Moya/Moya#1048]
Hello, i am a little confused about [this](https://github.com/Moya/Moya/blob/9.0.0-dev/Sources/RxMoya/RxMoyaProvider.swift#L20) method(and it counterpart from ReactiveMoyaProvider). I know, I can later observe on any scheduler I want, but why I can't avoid unnecessary calls on main thread(which I can do with plain Moya api)? If it is not by design, I would like to make tiny contribution 😸

**Comment by AndrewSB** [comment]
Hey @haritowa: I'm not sure I totally understand your question, but it sounds like youre looking for something similar to #1032. If that's the case, we have #762, and we'd love your help 😄

**Comment by haritowa** [comment]
@AndrewSB yeah, sorry, 2am is not best time to create issue descriptions 😅 I'll try again:
As far as i know, by default Alamofire invokes all callbacks on Main queue, but you can customize this behavior via queue parameter. Moya [expose](https://github.com/Moya/Moya/blob/9.0.0-dev/Sources/Moya/MoyaProvider.swift#L85) this parameter, but RxMoyaProvider [don't](https://github.com/Moya/Moya/blob/9.0.0-dev/Sources/RxMoya/RxMoyaProvider.swift#L20). As a result, we can't avoid Main thread.

Only `self.request` [invocation](https://github.com/Moya/Moya/blob/9.0.0-dev/Sources/RxMoya/RxMoyaProvider.swift#L24) can be customized via subscribeOn, but [completion handler](https://github.com/Moya/Moya/blob/9.0.0-dev/Sources/RxMoya/RxMoyaProvider.swift#L25-L31) will be invoked on Main thread. To avoid future computation on main thread we can observe chain on another Scheduler, but we can't bypass main thread callback and unnecessary dispatches.

I look through https://github.com/Moya/Moya/pull/762 Are you sure that pass scheduler(instead of Queue) is the best idea? I believe this is not Rx-side work, and we should just pass queue to [this](https://github.com/Moya/Moya/blob/9.0.0-dev/Sources/Moya/MoyaProvider.swift#L85) method. I don't understand why you are propose to capture queue on provider creation (`RxMoyaProvider<GitHub>(queue: DispatchQueue.global(.utility))`) instead of pass it on each observable creation(this [method](https://github.com/Moya/Moya/blob/9.0.0-dev/Sources/RxMoya/RxMoyaProvider.swift#L20))
I propose:
- Add optional queue parameter to provider creation
- Add optional queue parameter to [this](https://github.com/Moya/Moya/blob/9.0.0-dev/Sources/RxMoya/RxMoyaProvider.swift#L20) method

**Comment by AndrewSB** [comment]
That all sounds good to me @haritowa: it makes sense to be able to do that on a `provider`-basis and `request`-basis 😄 

You're right, we need to add this to both RxMoya & ReactiveMoya.

Scheduler is an Rx concept, its just an abstraction on queues and (for all intents and purposes here) can be thought as equivalent to queues.


I'd be more than happy to review a PR 👍 this is something I've wanted for a while too

**Comment by haritowa** [comment]
Ok, I'll do it tomorrow, sorry for scheduling PR on weekends :)

**Comment by BasThomas** [comment]
No worries @haritowa - take your time. 😃

**Comment by sunshinejr** [comment]
This is also done already. Closing this one as well!
