### ISSUE TITLE
BaseURL request problem.

### ISSUE THREAD

**Issue by k8mil** [Moya/Moya#1049]
Moya : 8.0.3
Language : Swift 3.1

### Let's imagine that you have a link that looks like that:

```swift
let urlString = "https://google.com/123/somepath?X-ABC-Asd=123"
```

### When I do my request using `Alamofire` :

```swift
Alamofire.upload(fileURL, to: URL(string: urlString)!, method: .put, headers: nil).response {
    response in
    print(response)
}
```

it all seems fine(don't look at status code):

![screen shot 2017-04-12 at 14 14 40](https://cloud.githubusercontent.com/assets/9297748/24957000/7984ebce-1f8a-11e7-8a6c-c62bc003f60b.png)

### but when I do the same request using Moya like that:

```swift
enum MyApi {
    case upload
}
extension MyApi : TargetType {
    var baseURL: URL {
        let urlString = "https://google.com/123/somepath?X-ABC-Asd=123"
        return URL(string: urlString)!        
    }

    var path: String {
        return ""
    }
    
    ...
}

provider.request(MyApi.upload)
```
The created request URL is different that in `Alamofire` request.

![screen shot 2017-04-12 at 14 20 49](https://cloud.githubusercontent.com/assets/9297748/24957215/4a202bea-1f8b-11e7-831f-776c84c5f555.png)

## The difference is that before `?` character moya inserts the `/` char. 

https://google.com/123/somepath?X-ABC-Asd=123
https://google.com/123/somepath/?X-ABC-Asd=123

Could you help me and tell me what I'm doing wrong?

**Comment by pedrovereza** [comment]
Hey @k8mil, can you check if it works as expected when you change your `baseURL` to be just https://google.com and `path` to return `/123/somepath?X-ABC-Asd=123`?

**Comment by k8mil** [comment]
@pedrovereza 
Thanks for your response.

I've created a sample repo with the test code. Just clone and run it.

https://github.com/k8mil/MoyaBaseURL

Below you can see, screen from Charles with 3 options:

### First
request was performed with Alamofire using 
`URL(string: "https://google.com/123/somepath?X-ABC-Asd=123")!`
### Second
request was performed using MoyaProvider with
`baseURL = "https://google.com/123/somepath?X-ABC-Asd=123"` 
### Third
request was performed using MoyaProvider with
`baseURL = "https://google.com` and `path = "/123/somepath?X-ABC-Asd=123"`

<img width="481" alt="screen shot 2017-04-13 at 22 19 42" src="https://cloud.githubusercontent.com/assets/9297748/25022746/5eb6b03a-2097-11e7-8a94-0e8b3710504b.png">


And only Alamofire produces that what I want to achieve :)

Important thing is that I'm using `Moya` in my project and the consuming my backend API with Moya is really great and works perfectly, but I have some case that I have to use the `URL`(which is not related with backedAPI) that I received from some service and I shouldn't modify that `URL`. Unfortunately, as you can see in the Second and Thrid example the URL is modified by removing/changing the `?` char.

**Comment by pedrovereza** [comment]
Hey @k8mil thanks for the detailed explanation and examples 👍 

I think I have a fix in #1053, care to take a look? 😉

**Comment by AndrewSB** [comment]
Very interesting use case. Thanks for implementing this @pedrovereza 😄

**Comment by k8mil** [comment]
Thanks @pedrovereza !
I've tested it and it works fine.
So, now I wait till it will be merged with `master` 👍  :)
