### ISSUE TITLE
Trying to declare extension and getting error.

### ISSUE THREAD

**Issue by dannymout** [Moya/Moya#1052]
I'm trying to create an `TargetType` extension, but I keep getting an error: `Use of undeclared type 'foo'`

````swift
extension GitHub: TargetType {
}
````

**Comment by bjarkehs** [comment]
Which version of Moya are you using? Could you provide the whole file? Which line produces `Use of undeclared type 'foo'`? Have you been able to reproduce in a completely new project?

**Comment by dannymout** [comment]
I ran `carthage update`. So it must be the latest version. The line is the first line from above, when I declare the extension. I'm having this issue when I try to write this in a Cocoa Touch Framework. I tried both CocoaPods and Carthage. @bjarkehs

**Comment by dannymout** [comment]
I forgot about declaring the enum.
