### ISSUE TITLE
Moya object inner mapping (with Argo)

### ISSUE THREAD

**Issue by balancin** [Moya/Moya#1054]
Moya (8.0.3)

Hello, I trying map the following object (and I can't):

`["response": {
    "groups":     (
    {
        "date": "2017-03-01T03:20:30.788Z",
        "latitude": "35.7020691",
        "longitude": "139.7753269",
        "msgs": 2,
        "name": "teste":
        "topic": "teste":
        "usernames":("john")
    }`

The question is ... How I can map that ? I need get "groups" into "response". I trying use mapObject and Map(defined function in  my helper)  but I can't use mapObject (let test = try response.mapObject(rootKey: "response")) because I get "Type String? does not conform to protocol 'ExpressibleByStringLiteral'"

Can anyone help me ?

Thanks

**Comment by AndrewSB** [comment]
Hey @balancin, this looks like more of an [`Argo`](https://github.com/thoughtbot/Argo) question, asking the people over at [`Moya-Argo`](https://github.com/wattson12/Moya-Argo) may also yield good results.
Sorry I can't be more helpful! I haven't used Argo for a while 😕
