### ISSUE TITLE
Adding headers by default in target

### ISSUE THREAD

**Issue by jayesh15111988** [Moya/Moya#1058]
I have seen an example of code where Provider can add headers to request with endpoint closure

```swift
let endpointClosure = { (target: MyTarget) -> Endpoint<MyTarget> in
    let defaultEndpoint = MoyaProvider.defaultEndpointMapping(for: target)

    // Sign all non-authenticating requests
    switch target {
    case .authenticate:
        return defaultEndpoint
    default:
        return defaultEndpoint.adding(newHTTPHeaderFields: ["AUTHENTICATION_TOKEN": GlobalAppStorage.authToken])
    }
}
let provider = MoyaProvider<GitHub>(endpointClosure: endpointClosure)
```

However, it looks to me endpoint closure is repeated if we are creating provider in multiple places. I was wondering if there is any way to add headers to request in the same way we do add parameters, request type, endpoints etc. For example, in the GitHub struct, it would look like this,

```swift
extension GitHub: TargetType {
    var headers: [String: String] {
        switch self {
            case .repositories:
                return ["auth_header": "2312dasd"]
            case .users:
                return ["user_agent": "my_user_agent"]
        }
    }
}
```

In that way any module sending a request won't explicitly have to add an endpoint closure every time.

**Comment by jayesh15111988** [comment]
I see this has already been raised in https://github.com/Moya/Moya/issues/1046. Should I just close this issue then?

**Comment by pedrovereza** [comment]
@jayesh15111988 Yes, let's continue the discussion in #1046 :wink:
