### ISSUE TITLE
Using both URLEncoding and JSONEncoding

### ISSUE THREAD

**Issue by amaurydavid** [Moya/Moya#1059]
I have to use an API that asks me to make a POST and put one parameter in the URL, others as JSON in the body.
If I had to only send the URL parameter, I would use URLEncoding.queryString
If I had to only send the body parameters, I would use JSONEncoding.default
But how can I send both with Moya? As far as I know, Moya only allow 1 parameter encoding.

As a workaround, in my implementation of TargetType I left the body params in `parameters` and 'parameterEncoding` to JSONEncoding.default, and tried to put the query parameter directly in the path, but doing so the '?' is encoded as '%3F' while it shouldn't and the API returns an error.

Using Moya 8.0.3

**Comment by amaurydavid** [comment]
Nvm, I found some inspiration from https://github.com/Moya/Moya/issues/909 and created a custom encoding.

`struct MultipleEncoding : ParameterEncoding {

	var urlParameters: [String]?
	
	init(urlParameters:[String]) {
		self.urlParameters = urlParameters
	}
	
	func encode(_ urlRequest: Alamofire.URLRequestConvertible, with parameters: Parameters?) throws -> URLRequest {
		guard let parameters = parameters else { return urlRequest as! URLRequest }
		
		//Encode URL Params
		var filteredParams: [String: Any] = [:]
		
		parameters.filter({ (key,value) in
			return urlParameters?.contains(key) ?? false
		}).forEach {
			filteredParams[$0.0] = $0.1
		}
		
		let partiallyEncodedRequest = try URLEncoding.queryString.encode(urlRequest, with: filteredParams)
		
		//Encode JSON
		filteredParams = parameters.minus(dict: filteredParams)
		return try JSONEncoding.default.encode(partiallyEncodedRequest, with: filteredParams)
	}
}`

That's not very generic but I someone has the same issue, here is something to start with :)

**Comment by hardikamal** [comment]
@amaurydavid  parameter.minus is not working. And can you help out on how to use this?
