### ISSUE TITLE
Customizing Response Handling based on endpoint

### ISSUE THREAD

**Issue by gmoalvarez** [Moya/Moya#1061]
I love how Moya allows one to customize the parameters before the network request is being made per endpoint. Are there any best practices for doing something similar with the responses? I find myself typing this often:

```swift
return self.provider
        .request(.someTarget())
        .take(1)
        .filterSuccessfulStatusCodes()
        .retry(2)
        .mapJSON()
        .map { (data) -> [Entity]  in
          guard let json = data as? JSONDictionary else { return [] }
          guard let value = json["Value"] as? [JSONDictionary] else { return [] }
          let entities = Mapper<Entity>().mapArray(JSONArray: value) ?? []
          return entities
        }
        .do(onNext: { records in
          //update record in database
          _ = repository.save(entities)
        })
```
But the specifics of parsing the JSON and saving to the database might be a little different depending on the endpoint. Any suggestions for going about this as a general guideline?

**Comment by BasThomas** [comment]
What do you find yourself typing often? 😬

**Comment by gmoalvarez** [comment]
Sorry I accidentally submitted before completing my question.

**Comment by gmoalvarez** [comment]
I did look through the closed issues and found this discussion:

https://github.com/Moya/Moya/issues/948

and this which is related

https://github.com/Moya/Moya/issues/950

I guess I am mainly looking for advice/best practices.

I am thinking for now it might be best to just create wrapper functions for each target to encapsulate the json parsing, as @scottrhoyt recommends in the first link.

So maybe something like:
```
class MyClient {
  let provider: Networking

  init(provider: Networking) {
    self.provider = provider
  }

  func getSomeTarget(parameters: SomeParams?) -> Observable< [Entity] > {
    return provider
        .request(.someTarget())
        .take(1)
        .filterSuccessfulStatusCodes()
        .retry(2)
        .mapJSON()
        .map { (data) -> [Entity]  in
          guard let json = data as? JSONDictionary else { return [] }
          guard let value = json["Value"] as? [JSONDictionary] else { return [] }
          let entities = Mapper<Entity>().mapArray(JSONArray: value) ?? []
          return entities
        }
        .do(onNext: { records in
          //update record in database
          _ = repository.save(entities)
        })
  }

  func getSomeOtherTarget() ...etc.
}
```

**Comment by sunshinejr** [comment]
Hey @gmoalvarez. That is a really interesting question. What you can do is to make also one wrapper-class around all the tasks in the pipeline before parsing response. In your case it would be:

```swift
func request(target: Target) {
    return provider
        .request(target)
        .take(1)
        .filterSuccessfulStatusCodes()
        .retry(2)
}
```

and then create multiple classes that do the request & mapping like your `MyClient` class does. It would be then useful in case you want to expand your preparation to request, or tearDown after. E.g. you can see how we can use a quite powerful wrapper with token extractor [here](https://github.com/Moya/Moya/blob/master/docs/Examples/SubclassingProvider.md).

Hope it helps!

**Comment by gmoalvarez** [comment]
Hello @sunshinejr thank you for your reply. I ended up creating a wrapper and it has been working well so far. I did also end up borrowing some of the great ideas from the Kiosk implementation and modifying it for my project. Thank you :)
