### ISSUE TITLE
command failed due to signal: segmentation fault: 11 

### ISSUE THREAD

**Issue by zhaoyunyi** [Moya/Moya#1068]
Test the moya demo
i get this error "command failed due to signal: segmentation fault: 11"  when i use 
this code. It is Apple Error ? How to solve this error?
```swift
let provider: RxMoyaProvider<GitHub> = RxMoyaProvider<GitHub>(endpointClosure: endpointClosure, requestClosure: requestClosure, stubClosure:  MoyaProvider.neverStub, manager: RxMoyaProvider<GitHub>.customAlmofireManager(), plugins: plugins)
```

xcode 8.3.2
swift 3.1

**Comment by sunshinejr** [comment]
Hey @zhaoyunyi. Is it still happening? If yes, please provide more code to us. Most valuable would be your `endpointClosure`, `requestClosure`, `plugins` and `.customAlamofireManager()`. Or if you have time, it would be awesome to have a test demo project that this behavior occurs at. I can't say what's wrong without more context, sorry.
