### ISSUE TITLE
Return nil in sampledata

### ISSUE THREAD

**Issue by dannymout** [Moya/Moya#1069]
Is there a way to return no sampledata. For some of the API calls I'm doing, the API doesn't return anything, just a status code, therefore I don't have anything for sample data.

**Comment by justinmakaila** [comment]
```
enum MyTargetType: TargetType {
   /// cases, other variables...

  var sampleData: Data {
    switch self {
    case .emptyCase:
      return Data()
    /// other cases
  }
}
```
If you return empty `Data()`, it should work
