### ISSUE TITLE
[CI RFC]: discuss danger not blocking tests on CircleCI

### ISSUE THREAD

**Issue by AndrewSB** [Moya/Moya#1070]
I wanted to continue the discussion started in https://github.com/Moya/Moya/pull/1067#issuecomment-298221375.

Right now we're having issues with contributors not being able to run tests because danger is failing, with an undescriptive error message:

<img width="1339" alt="screen shot 2017-05-03 at 5 28 05 pm" src="https://cloud.githubusercontent.com/assets/3814772/25686804/e4853590-3025-11e7-9fbf-ece8a02b298a.png">

Here's an example of a PR comment where a contributor isn't sure what's happening with tests (where the tests actually passed, but CI failed because danger required a changelog entry): https://github.com/Moya/Moya/pull/1055#issuecomment-296995830

I think we should either    
1. make `bundle exec danger` give an actionable error message (along with the comment posted in the GitHub PR thread)
2. run danger on it's own CI instance/job, so it doesn't confuse (especially new) contributors on whether tests run by `rake test && rake test:carthage && rake build_demo` passed or failed

or both

@ashfurrow: you mentioned you'd be around to help out on this, what do you think is possible?

**Comment by BasThomas** [comment]
This would be awesome, thanks for looking in to this, @AndrewSB!

**Comment by ashfurrow** [comment]
I think giving Danger more actionable error messages would be a great idea, I'll look into improving the wording this weekend. 

I'm not opposed to running Danger on a separate CI (say, Travis) but it does limit our ability to add rules that deal with build artefacts. For example, we could have a Danger rule to look for long-running Swift compile times, but only if it's run as-usual. Also, two CI services means twice the configuration, so there's a cost. I'm fine with whatever the community wants to do.

**Comment by AndrewSB** [comment]
I think just actionable error messages would be a great start. We can re-evaluate that if contributors are still getting confused about why CI crashing. 

It doesn't seem like its worth it to decouple danger's dependency on our build artifacts rn

**Comment by pedrovereza** [comment]
We can also think about loosening some danger rules. I feel that the one that causes more confusion is "missing changelog", which we could downgrade to warn instead of fail 🤔

**Comment by ashfurrow** [comment]
Sure thing 👍

**Comment by ashfurrow** [comment]
Yikes, forgot to look at this over the weekend. Will get to it ASAP.

**Comment by BasThomas** [comment]
No worries, take your time Ash :)
