### ISSUE TITLE
Adding Moya to Swift Source Compatibility Test Suite

### ISSUE THREAD

**Issue by aksswami** [Moya/Moya#1072]
I really like using Moya in daily basis.
It's probably a good idea, to add Moya to "Swift Source Compatibility Test Suite".
https://swift.org/blog/swift-source-compatibility-test-suite
https://swift.org/source-compatibility/#current-list-of-projects
Alamofire, ObjectMapper are already in the list.

**Comment by AndrewSB** [comment]
yup, that would be awesome! Do you want try to make a pull request against apple's repository?

**Comment by aksswami** [comment]
Sure, I will try to make a PR against apple's repo in a day or two.

**Comment by BasThomas** [comment]
Thanks for looking into this, @aksswami! 😀

**Comment by aksswami** [comment]
@BasThomas I have create a PR [Moya Swift compat](https://github.com/apple/swift-source-compat-suite/pull/35). But I am getting error in `./check Moya` step. Not able to get much information from the error logs also. I have added comment for asking some help from [Swift Compat](https://github.com/apple/swift-source-compat-suite) team.

**Comment by BasThomas** [comment]
This has been merged on Apple's side. @aksswami, thank you so much for picking this up!

**Comment by sunshinejr** [comment]
@BasThomas so it was, in fact, this `.git` suffix bug? Maybe we should let the world know somehow, this was found by an accident 🤔

**Comment by BasThomas** [comment]
I think so? Maybe better to ask over at https://github.com/apple/swift-source-compat-suite/pull/35; @lplarson fixed it (by updating just the hash as far as I understand, so I think the `.git` suffix did the trick.

**Comment by sunshinejr** [comment]
Huh, now where should we raise an issue, on SPM or SPM-compat? 🤔

**Comment by BasThomas** [comment]
Good question. I'd just start from the Compat PR, and go from there?

**Comment by BasThomas** [comment]
Or going straight to the mailing list is also an option.

**Comment by sunshinejr** [comment]
Right, gonna just comment on the PR what was wrong in our project then. :+1:
