### ISSUE TITLE
How to deal with case : if one of the input parameter is array of dictionary

### ISSUE THREAD

**Issue by iOSUser110** [Moya/Moya#1080]
```
{
  "id" : "101"
  "name" : "34"
  "desc" : "56"
  "FavouriteRecipe" : [
    {  "id" : "1" , "name": "recipe 1"},
    {  "id" : "2" , "name": "recipe2"},
  ]
}
```
How to deal with this kind of parameters , in MoyaProvider 
please provide sample. It very urgent. I searched a lot but not got the solution for this

**Comment by iOSUser110** [comment]
i want to construct a request with these parameters

**Comment by iOSUser110** [comment]
When I tried to make Input JSON as 

{
  "id" : "101"
  "name" : “Test”
  "desc" : “Test”
  "statusList” : [
    {  "id" : "1" , "status": “High”},
    {  "id" : "2" , "status": “low”},
    { "id" : "3" , "status": “medium”}
  ]
}


I wrote Code on swift as 
let dict1:[String,Any] =
         [
            "id":  “1”
            "status":"High"
        ] 
        
let dict2:[String,Any] =
            [
                "id”:”2”,
                "status":"Low"
                ]

let dict3:[String,Any] =
            [
                "id”:”3”,
                "status":"Medium"
                ]


let inputParam =
          [
 "id" : "101"
  "name" : “Test”
  "desc" : “Test”
  "statusList” : [ dict1,dict2,dict3]

               ]



On PHP side getting as below : 
Array => 1<br /><pre>Array
(
    [statusList] => Array
        (
            [0] => Array
                (
                    [id] => “1”
                )

            [1] => Array
                (
                    [status] =>  “High”
                )

            [2] => Array
                (
                    [id] => “2”
                )

            [3] => Array
                (
                    [status] => “Low”
                )

            [4] => Array
                (
                    [id] =>   “3”
                )

            [5] => Array
                (
                    [status] => “Medium”
                )

        )

    [id] => “101 ”
    [name] => “Test ”
    [desc] => “ Test”
  
)


BUt it should not treat dictionary element as array element , 
It should be like  as

           [0] => Array
                (
                    [id] => “1”
                    [status] =>  “High”
                )
            [1] => Array
                (
                    [id] => “2”
                    [status] =>  “Low”
                )

            [2] => Array
                (
                     [id] => “3”
                    [status] =>  “Medium”
                )

**Comment by iOSUser110** [comment]
I shared the code written in swift, And i have not written any other different thing for paramters , just use moya framework as demo shared by Moya

**Comment by mpsnp** [comment]
@iOSUser110 this is Alamofire issue (not issue actually...) but it generates such body:

```
...
statusList[][id]=1&
statusList[][status]=High&
statusList[][id]=2&
statusList[][status]= Low&
statusList[][id]=3&
statusList[][status]= Medium
``` 
In other words: it composes an array without indexes, that's why PHP or whatever cannot decode it in right way.

**Comment by iOSUser110** [comment]
so what would be the workaround ?. Workaround from app side

**Comment by alcarvalho** [comment]
@iOSUser110 what do you have set on your `parameterEncoding`? This situation described by @mpsnp only makes sense to me if you're using `URLEncoding`.

**Comment by iOSUser110** [comment]
@alcarvalho ya, I am using URLEncoding

**Comment by alcarvalho** [comment]
@iOSUser110 I don't think it's advised to use `URLEncoding` for complex data types like this one. If you're able to change it to a `POST` with `JSON` format it would be much better. I'm not sure how I would do a workaround to make it work with `URLEnconding`.
