### ISSUE TITLE
Vision document / FAQ

### ISSUE THREAD

**Issue by BasThomas** [Moya/Moya#1081]
Do you think we, @Moya/contributors, can create a Vision document? This would help us create some clear goals for the project as well as giving the community and users a better idea of what we expect of this project going forward.

What do you think? And more concrete: what should be in it?

FAQ: 
Separating subspecs into repositories
Model decoding: soon with Apple's APIs
https://github.com/Moya/Moya/issues/1126#issuecomment-312125039

**Comment by sunshinejr** [comment]
👍 

We could start with maybe using something we already have. I think the first paragraph of our Readme (till the **Sample Project**) with some changes could be a good start.

**Comment by SD10** [comment]
As an aspiring contributor, I think a Vision document would be a great move! 😃

**Comment by sunshinejr** [comment]
I think we should prioritize Vision document, as it will be really helpful in reviewing new features/ideas for contributors as well as making sure that idea someone has is a good fit for Moya. 

Pinging you, @ashfurrow, as your contribution here would be invaluable. Could any of you guys start this one and we can go from there in a PR?

**Comment by ashfurrow** [comment]
Cool cool – I've got some time this weekend, I'll see what I can do 👍

**Comment by ashfurrow** [comment]
Hey – still haven't gotten around to this. Requires some dedicated thinking time. Will do my best 👍

**Comment by sunshinejr** [comment]
No problem Ash, please take your time. And thanks for letting us know 👍

**Comment by ashfurrow** [comment]
This totally fell off my radar – going to prioritize it this weekend.
