### ISSUE TITLE
Issue when using Moya branch for handling 400 500 failures

### ISSUE THREAD

**Issue by iOSUser110** [Moya/Moya#1088]
Getting an "Invalid conversion from throwing function of type '`(_) throws -> ()`' to non-throwing function type '`Completion`' (aka '`(Result<Response, MoyaError>) -> ()`')"

**Comment by BasThomas** [comment]
Can you post your code where this error is shown?

**Comment by iOSUser110** [comment]
<img width="738" alt="screen shot 2017-05-15 at 4 39 57 pm" src="https://cloud.githubusercontent.com/assets/2657399/26055150/336126f4-398d-11e7-9ebd-449548210650.png">

as in above screenshot,
When i am trying to call service from controller

**Comment by iOSUser110** [comment]
waiting for your reply

**Comment by iOSUser110** [comment]
Sorry got the solution, It was my mistake.

**Comment by BasThomas** [comment]
What ended up solving your problem?

**Comment by KumariOS** [comment]
@iOSUser110, how did you solve this problem?

**Comment by alsingr** [comment]
I resolve it by catching any exception or error in completion closure
