### ISSUE TITLE
How can I get requestParameters from Response obj?

### ISSUE THREAD

**Issue by ZHDeveloper** [Moya/Moya#1090]

**Comment by sunshinejr** [comment]
Hey @ZHDeveloper. I'm not sure if I understood your question correctly: you want to access request parameters after getting the response? If yes, it should be possible, but not so easy. 

Our `Response` object has a `request` property that contains a `URLRequest` object in it. Now, depending on the parameter encoding, you would have to extract the parameters yourself: get parameters from the `request.url` if the request was using `URLEncoding`, maybe access the `request.httpBody` if it was using `POST` method.

However, you may try to get your parameters _just before the request_. We have a `requestClosure` that does the mapping from `Endpoint` to `URLRequest` and you can extract them from this place as well. An example of that is in our tests, [here](https://github.com/Moya/Moya/blob/dfa3568fd7727c99feeebb8156a53a915844ee72/Tests/MoyaProviderSpec.swift#L556-L575).

Hope it helps! Let us know if something wasn't clear or you need more help!

**Comment by ZHDeveloper** [comment]
@sunshinejr thanks, I think I get it
