### ISSUE TITLE
When use Moya how to write unit test? 

### ISSUE THREAD

**Issue by longshihua** [Moya/Moya#1098]
I known we can get the sampleData as response, but I don't know how to write test for request? If there have any examples about how to make unit test? Thanks

**Comment by sunshinejr** [comment]
Hey @longshihua, this is a good one. Testing is our top priority, so we should've better documentation around that. We are working on it, but in the meantime... 

If we are talking about testing with `sampleData` in unit tests, [you can see it in our tests how we do it here](https://github.com/Moya/Moya/blob/master/Tests/MoyaProviderSpec.swift#L15). Basically we use `stubbingClosure` and check the data from the response. If we are talking about testing without using any stubbing option built in in Moya, we have these as well. For that purpose we use [OHHTTPStubs](https://github.com/AliSoftware/OHHTTPStubs), you can see how we do it [here](https://github.com/Moya/Moya/blob/master/Tests/MoyaProviderSpec.swift#L711).

Hope it helps!

**Comment by rgkobashi** [comment]
As @sunshinejr mention, you can test the `.sampleData` like they do on the link that he provided. However if what you are looking is to test your `RequestManager`, `NetworkManager` or whatever you are using to encapsulate your request you can check [this](https://stackoverflow.com/a/48928906/8483739).
