### ISSUE TITLE
No iOS targets when adding Moya as submodule

### ISSUE THREAD

**Issue by mossby** [Moya/Moya#1102]
Not sure what step I may be missing, but when pulling down the latest version of Moya.git (8.0.4) I'm only seeing 3 macOS targets within the project file (Moya, RX, and Reactive)

Thanks!

**Comment by BasThomas** [comment]
What is it exactly where you encounter an error? Can you clarify what doesn't work as expected?

**Comment by petester42** [comment]
They look like Mac OS targets but they are cross platform. Just pick iPhone or simulator when running and it will just work.
