### ISSUE TITLE
Release 8.0.5

### ISSUE THREAD

**Issue by sunshinejr** [Moya/Moya#1104]
Hey guys. So this bug fixed in #1095 is actually really needed for a project that a friend of mine and his team is working on. Not only that, but this is a really big problem for people that may not know this bug even exist. Double response event in the progress might be a hard thing to debug. 

I would love to release a new version with this fix till the end of the week. Thus we might wait for any other patches/fixes that might come up and release it, or just do it immediately. Thoughts? 🤔

**Comment by BasThomas** [comment]
In this case, considering the bug, I'd say go ahead and release 8.0.5.

**Comment by sunshinejr** [comment]
Released! 🎉
