### ISSUE TITLE
Some attributes are missing on response

### ISSUE THREAD

**Issue by eliacamposilvan** [Moya/Moya#1108]
On 8.0.4 version i can't get attributes "title" and "text" on the data returned from get requests. 
Each other attribute looks perfectly fine.
Those 3 attributes appear to be presents on the response data but empty.

Thanks for the effort guys!

**Comment by sunshinejr** [comment]
Hey @eliacamposilvan. Thanks for filling in an issue.

Is this issue happening on other versions of Moya as well? Can you use our `NetworkLoggerPlugin` in your `MoyaProvider` or any other tool like `mitmproxy` to make sure it's Moya issue, not a server issue? Logs from that would be really helpful. It would be even better if you could prepare demo project where this issue exist so I can investigate more.

**Comment by eliacamposilvan** [comment]
I'm sorry but i don't have enough time atm to create a demo :(

Anyway, NetworkLoggerPlugin is logging this: 

["Moya_Logger: [30/05/2017 22:21:23] Request: http://api.supersecretendpoint.com/exhibitions", "Moya_Logger: [30/05/2017 22:21:23] Request Headers: [:]", "Moya_Logger: [30/05/2017 22:21:23] HTTP Request Method: GET"]
["Moya_Logger: [30/05/2017 22:22:07] Response: <NSHTTPURLResponse: 0x174034fa0> { URL: http://api.supersecretendpoint.com/exhibitions } { status code: 200, headers {\n    Connection = \"Keep-Alive\";\n    \"Content-Type\" = \"application/json; charset=utf-8\";\n    Date = \"Tue, 30 May 2017 20:21:50 GMT\";\n    \"Keep-Alive\" = \"timeout=5, max=100\";\n    Server = Apache;\n    \"Transfer-Encoding\" = Identity;\n    \"X-Powered-By\" = \"PHP/5.3.29, PleskLin\";\n} }"]

I have this issue also on version 8.0.3
When i perform the request with plain alamofire and postman, i get the correct response with "title" and "text" parameters.
The request is a get and the json is valid.

This is my request service
```swift
import Moya
import SwiftyJSON
import Result

class RequestsService {
    
    static let manager = RequestsService()
    
    var provider: MoyaProvider<RequestsEnum>
    
    init() {
        let endpoint = { (target: RequestsEnum) -> Endpoint<RequestsEnum> in
            return Endpoint<RequestsEnum>(
                url: target.baseURL.appendingPathComponent(target.path).absoluteString,
                sampleResponseClosure: {.networkResponse(2000, target.sampleData)},
                method: target.method,
                parameters: target.parameters
            )
        }

        self.provider = MoyaProvider(endpointClosure: endpoint, plugins: [NetworkLoggerPlugin()], trackInflights: true)
    }

    func performRequests(callback: @escaping () -> Void) {
        let requests: [RequestsEnum] = [.getExhibitions]

        for request in requests {
            RequestsService.manager.provider.request(
                request,
                completion: { result in
                    self.defaultHandler(type: request, result: result, callback: callback)
                })
        }
    }
    
    func defaultHandler(type: RequestsEnum, result: Result<Response, MoyaError>, callback: () -> Void) {
        switch result {
        case let .success(response):
            let json = JSON(data: response.data)
            switch type {
            case .getExhibitions:
                let exhibitions = json.arrayValue.map({ json in Exhibition(json: json) })
                print(exhibitions)
                break
            }
        case let .failure(error):
            print("request error: ", error)
            break
        }
    }
}

enum RequestsEnum {
    case getExhibitions
}
```

And this is my request service specification
```swift
extension RequestsEnum: TargetType {
    var baseURL: URL {
        return URL(string: ConfigService.endpoint)!
    }
    var path: String {
        switch self {
        case .getExhibitions:
            return "/exhibitions
        }
    }
    var method: Moya.Method {
        return .get
    }
    var parameters: [String: Any]? {
        return nil
    }
    var parameterEncoding: ParameterEncoding {
        return JSONEncoding.default
    }
    var sampleData: Data {
        return Data()
    }
    var task: Task {
        return .request
    }
}
```

I don't know if it's useful, but somehow, sometimes the request works correctly

Thanks again

**Comment by eliacamposilvan** [comment]
Looks like I have a problem with the responseData method of Alamofire, it doesn't return those 2 attributes... 
The responseJSON is working fine though

Sorry for the waste of time.

**Comment by sunshinejr** [comment]
Don't worry about it, glad you figured it out! 🎉  Also, from the logs it seems like there is no body in the response, might want to check that out as well. 

Please feel free to reopen if you find something that might be a Moya problem anyways.
