### ISSUE TITLE
Support app extension API only

### ISSUE THREAD

**Issue by m3rLin0WoRK** [Moya/Moya#1110]
Hi, 

I want use Moya in my framework with **Allow app extension API only** flag enabled, but I have a Xcode warning that says: **Linking against dylib not safe for use in application extension**. 
I think this is due to the fact that Moya haven't app extension flag enabled.

How can I solve? 
Thank you for your help

**Comment by m3rLin0WoRK** [comment]
Nobody can help me?

**Comment by BasThomas** [comment]
I think we should be able to add this in Moya. I'll take a look.

**Comment by BasThomas** [comment]
Thanks for bringing this to our attention! I've opened #1127.

**Comment by m3rLin0WoRK** [comment]
Thank you :)
