### ISSUE TITLE
Plugins usage?

### ISSUE THREAD

**Issue by mrfarukturgut** [Moya/Moya#1111]
Hi, I am using Moya to handle the network operations in my project and I have been here couple times. Before I have been using my own logging -which very basic prints and it was really hard to debug from it- so I decided to use NetworkLoggerPlugin and NetworkActivityPlugin. However, the print outs are very mixed up. 

<img width="581" alt="screen shot 2017-06-03 at 00 37 25" src="https://cloud.githubusercontent.com/assets/6718272/26745771/e2677d9a-47f4-11e7-874c-f1435ffbae6a.png">
 
And my code; 

```
open static func Provider() -> MoyaProvider<NetworkAPI> {
        return MoyaProvider<NetworkAPI>(endpointClosure: NetworkProvider.endpointClosure, manager: NetworkManager.manager, plugins: [NetworkLoggerPlugin(verbose: true, cURL: true)])
    }
```

 Before I was able to use it with `formatter: JSONResponseDataFormatter` but now it throws `unresolved identifier` error. Can someone please explain how to do that with some code? I examined the documentation but I couldn't figure out how to use it. If someone helps I will be very appreciated.

**Comment by pedrovereza** [comment]
Hey @mrfarukturgut , `JSONResponseDataFormatter` is not part of Moya. We have the function [implemented in our Demo app](https://github.com/Moya/Moya/blob/5678a4c66ad779b15173315b0c2e300d0e3d9ba9/Demo/Shared/GitHubAPI.swift#L6), you'd need to implement the function on yours :wink:

**Comment by mrfarukturgut** [comment]
I think I used this code piece in my code, but it was deleted somehow. anyway, thanks a lot 😃
