### ISSUE TITLE
upload progress wrong

### ISSUE THREAD

**Issue by KieSun** [Moya/Moya#1115]
```swift
provider.request(Network.uploadPic(img: data), queue: nil, progress: { (response) in
                print(CGFloat(response.progress))
                
                view.progress = CGFloat(response.progress)
                
                if response.completed {
                    view.removeFromSuperview()
                }
                
            }, completion: { (result) in
```

I can upload image success. But progress is wrong.It`s always 1.0

**Comment by sunshinejr** [comment]
Hey @KieSun. This is really strange. [We have tests around progress](https://github.com/Moya/Moya/blob/master/Tests/MoyaProviderSpec.swift#L700-L742), but if you found an edge case which our tests do not cover - please let us know with more detailed description. Even better if you could write a test for that. Right now, I can't really help you based on this information.

**Comment by petester42** [comment]
It was a bug in previous versions. What version are you using?

**Comment by phimage** [comment]
There is no test about upload progress, only download progress 

But I made an unit test on httpbin and we receive progress info
https://github.com/phimage/Moya/commit/765113a198d3058235a2197b9c5f9757cdc72aa5

**Comment by BasThomas** [comment]
Hey, thanks @phimage! Can you open a PR so we can add that test? That'd be awesome!

**Comment by phimage** [comment]
Yes I will do it
I have 3 commits, maybe 3 or 2 PR to do, and all about "progress", so potentially a lot of conflicts if I do not make it one after another.
First one is #1232, I must convert it for 9.0.0-dev
