### ISSUE TITLE
RxSwift dependency not compatible with Xcode 9 and Swift 3.2

### ISSUE THREAD

**Issue by LeonardoCardoso** [Moya/Moya#1122]
Moya Version: 8.0.5

The current version of `RxSwift` dependency is not compatible with Xcode 9 and Swift 3.2. Thus, projects can't be compiled.
```ruby
ss.dependency "RxSwift", "~> 3.0"
```

I've solved this just by changing the dependency version. I can create a PR if it's needed.
```ruby
ss.dependency "RxSwift", "~> 3.5"
```

**Comment by BasThomas** [comment]
Thanks for noticing, @LeonardoCardoso! @Moya/contributors, should we release `8.0.6` to support this for version 8 still, or do we want to hold off on this for v9? Not sure if this would break anything?

**Comment by devxoul** [comment]
How about `>= 3.0`?

**Comment by pedrovereza** [comment]
@devxoul By using `~> 3.0` we are saying we can take anything from `3.0` up until `3.9`. The problem here is that our minimal version should be `3.5` now. 

We would still want to use `~> 3.5`, as `>= 3.0` means we could take, for example, version `4.0`, which would include breaking changes that we may not be ready to take.

**Comment by BasThomas** [comment]
This confuses me every time. Why does `3.5` not work at this point, then? `3.5` is in the range of `3.0` and `4.0`, so that should work? 🤔

**Comment by BasThomas** [comment]
@LeonardoCardoso, I just set up a test project and it seems to work fine with RxSwift. Alamofire seems not to be updated yet, though, and causes an error.

Have you tried `pod update`? A fresh install uses RxSwift 3.5.

**Comment by BasThomas** [comment]
```bash
$ pod install
Analyzing dependencies
Downloading dependencies
Using Alamofire (4.4.0)
Installing Moya 8.0.5
Using Result (3.2.3)
Installing RxSwift (3.5.0)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 4 total pods installed.
```

**Comment by pedrovereza** [comment]
@BasThomas @LeonardoCardoso  Yea, just double checked that I have a dummy project that is using RxSwift 3.5 as well.

@LeonardoCardoso If `pod update` doesn't solve it for you, could you share the content of your `Podfile` and `Podfile.lock`?

**Comment by LeonardoCardoso** [comment]
That's weird. So this is my scenario: I have both Xcode and Xcode-beta on my Mac. After updating Xcode to 8.3.3, it failed to work, but after a `pod update` it worked. Sorry for this false positive and thanks for the fast response. I'm closing the issue.
