### ISSUE TITLE
Custom ParameterEncoding example

### ISSUE THREAD

**Issue by BasThomas** [Moya/Moya#1128]
We might want to add a custom ParameterEncoding example. See #1119

**Comment by Dobryninios** [comment]
Agree with Thomas!

**Comment by pedrovereza** [comment]
I think we could just point to [Alamofire docs](https://github.com/Alamofire/Alamofire#custom-encoding) instead 🤔

**Comment by BasThomas** [comment]
Yep, that'll do as well, I think. 😃

**Comment by sunshinejr** [comment]
For sure! Still, I think that `ParameterEncoding` using some specific `Moya` configuration would be awesome as well.

**Comment by jackyzh** [comment]
@pedrovereza I think `URLRequestConvertible` should be marked as open instead of internal to custom parameterEncoding.

Or if is there any other elegant way to custom parameterEncoding?

**Comment by sunshinejr** [comment]
As @bchrobot stated, this one is also resolved by #1343.
