### ISSUE TITLE
Encode url parameters in .post request

### ISSUE THREAD

**Issue by BasantAshraf** [Moya/Moya#1129]
Hello 

I have a .post request with parameters to be sent in url like following:
http://xxxxx/token?userName=Mike&password=123
but the "?" is encoded to "%3F" 
http://xxxxx/token%3FuserName=Mike&password=123

I tried putting them in the parameters, but in .post requests it is sent as body not url parameters

Any Help please?

**Comment by sunshinejr** [comment]
Hey @BasantAshraf. Use `URLEncoding(destination: .queryString)` as your `parameterEncoding` and add `userName` & `password` as your parameters. Let us know if it worked!

**Comment by BasantAshraf** [comment]
it works! Thanx a million for your fast response

**Comment by iballan** [comment]
@sunshinejr I have tested it but the url is send empty without the parameters. what can be the issue with this ?

**Comment by stevenkitter** [comment]
me too and .queryString is useless

**Comment by lforme** [comment]
cool

**Comment by shenxiewei** [comment]
@BasantAshraf Hi,I have a same question. Can you paste the code?

**Comment by shenxiewei** [comment]
@BasantAshraf yes, I solved the problem!

**Comment by sunshinejr** [comment]
Hey @shenxiewei, great to hear! Can you share your solution with us? Maybe it'll help someone else 😉

**Comment by AhmAbdallah** [comment]
I want to call this  https://www.blaalb.com/restApi/testApi/myOrders?number=1&month=24

```
enum MyWebService {
    switch self {
       case getMyOrders(number: Int, month: Int)
   }
}

var path: String {
   switch self {
      case . getMyOrders:
      return "/myOrders"
     }
  }
}

var method: Moya.Method {
     switch self {
      case .getMyOrders:
      return .get
   }
}

var task: Task {
    switch self {
      case . getMyOrders(let number, let month):
      let p = ["number" : number,
               "month": month]
    return .requestParameters(parameters:p , encoding: URLEncoding.default)
 }
}
```
