### ISSUE TITLE
Performing an URLSessionUploadTask in background?

### ISSUE THREAD

**Issue by XavierDK** [Moya/Moya#1131]
Hello,

Is it possible using Moya to perform an URLSessionUploadTask in background to send for example image even if the user return to home?

Thanks in advance!

**Comment by sunshinejr** [comment]
Hey @XavierDK. You can create your own `Manager` and pass it to the `MoyaProvider`:
```swift
let configuration = URLSessionConfiguration.background(withIdentifier: "com.example.app.background")
let manager = Manager(configuration: configuration)
```

Let us know if it helps!

**Comment by XavierDK** [comment]
Thank you @sunshinejr! It's exactly what I was searching about.

**Comment by sunshinejr** [comment]
Glad it worked! 🎉

**Comment by teameh** [comment]
It seems this is not possible any more with the latest version since it depends on Alamofire 5 which disabled background sessions: https://github.com/Alamofire/Alamofire/commit/1d5411cdde887cb9c8d282239fa4a44d42bd5e9f

Any other solutions?

**Comment by yunustek** [comment]
How can I do that? As @teameh said it is no longer available this usage?

**Comment by polurezov8** [comment]
@yunustek At the moment it looks like the way you can solve it by switching from Moya/Alamofire to native URLSession.

**Comment by yunustek** [comment]
Okay thanks @polurezov8

**Comment by frankct310** [comment]
For other people looking for a solution : a plugin can surround the requests with the start/end background tasks, like the following:

`class MoyaBackgroundPlugin : PluginType {
    var bgTask : UIBackgroundTaskIdentifier = UIBackgroundTaskIdentifier.invalid
    var numInFlight = 0

    func prepare(_ request: URLRequest, target: TargetType) -> URLRequest {
        if numInFlight == 0 {
            bgTask = UIApplication.shared.beginBackgroundTask(withName: "Moya bg plugin") {
                if self.bgTask != UIBackgroundTaskIdentifier.invalid {
                    UIApplication.shared.endBackgroundTask(self.bgTask)
                    self.bgTask = .invalid
                    self.numInFlight = 0
                }
            }
        }
        numInFlight+=1
        return request
    }

    func didReceive(_ result: Result<Response, MoyaError>, target: TargetType) {
        numInFlight -= 1
        if (numInFlight <= 0) {
            UIApplication.shared.endBackgroundTask(self.bgTask)
            self.bgTask = .invalid
        }
    }
}`
