### ISSUE TITLE
 Cannot convert value of type NSURLRequest to RequestResultClosure

### ISSUE THREAD

**Issue by bfjfm2** [Moya/Moya#1133]
We migrating our old code to Swift 2.3 and facing this issue. How to change to RequestResultClosure? 
Thanks,

```.swift
//Old Code with NSURLRequest
let requestClosure = { (endpoint: Endpoint<T>, closure: (NSURLRequest -> ())) in
        let urlRequest: NSMutableURLRequest = NSMutableURLRequest(URL: endpoint.urlRequest.URL!, cachePolicy: endpoint.urlRequest.cachePolicy, timeoutInterval: endpoint.urlRequest.timeoutInterval)
 
        closure(urlRequest)
    }
//New Code with RequestResultClosure
let requestClosure = { (endpoint: Endpoint<T>, closure: (MoyaProvider.RequestResultClosure -> ())) in
        let urlRequest: NSMutableURLRequest = NSMutableURLRequest(URL: endpoint.urlRequest.URL!, cachePolicy: endpoint.urlRequest.cachePolicy, timeoutInterval: endpoint.urlRequest.timeoutInterval)
 
       
        closure(urlRequest)// How to pass RequestResultClosure ?
    }


```

**Comment by sunshinejr** [comment]
Hey @bfjfm2. First of all, thank you for bringing that up. I think we somehow missed updating the docs regarding this matter here. 

But to help you with what we've got right now, I'd suggest taking a look at our tests that use this new closure, [here](https://github.com/Moya/Moya/blob/aa33a0466d7333516691b3e5212c5acb41990928/Tests/MoyaProviderSpec.swift#L262-L270). Basically you can now specify if you want to pursue the request using `.success` case of `Result` type, or to fail the request using `.failure` case and passing the error down.

Let us know if it's working!

**Edit:** Also, we need to update our docs around it, I've opened an issue #1134. If you resolve your problem and want to take stab at it, feel free to do so :)

**Comment by bfjfm2** [comment]
Thanks @sunshinejr . I got swift 2.3 closure [Tag 7.0.4](https://github.com/Moya/Moya/blob/7.0.4/Demo/Tests/MoyaProviderSpec.swift#L222-L227)
```.swift
//Old Code with NSURLRequest Swift 2.2
let requestClosure = { (endpoint: Endpoint<T>, closure: (NSURLRequest -> ())) in
        let urlRequest: NSMutableURLRequest = NSMutableURLRequest(URL: endpoint.urlRequest.URL!, cachePolicy: endpoint.urlRequest.cachePolicy, timeoutInterval: endpoint.urlRequest.timeoutInterval)
 
        closure(urlRequest)
    }
//New Code with RequestResultClosure Swift 2.3   Repository Tag 7.0.4
let requestClosure = { endpoint, closure in
        let urlRequest: NSMutableURLRequest = NSMutableURLRequest(URL: endpoint.urlRequest.URL!, cachePolicy: endpoint.urlRequest.cachePolicy, timeoutInterval: endpoint.urlRequest.timeoutInterval)
 
        closure(.Success(urlRequest)
    }
```

**Comment by sunshinejr** [comment]
Glad it worked! 🎉
