### ISSUE TITLE
[Documentation] Fix RequestClosure usage in the docs.

### ISSUE THREAD

**Issue by sunshinejr** [Moya/Moya#1134]
We forgot to change the documentation around new `RequestClosure` in some places. We need to double-check where we are using it, but for sure we have to update it in [Authentication.md](https://github.com/Moya/Moya/blob/master/docs/Authentication.md#oauth). Transition is rather simple, you can take a look at our tests [here](https://github.com/Moya/Moya/blob/aa33a0466d7333516691b3e5212c5acb41990928/Tests/MoyaProviderSpec.swift#L262-L270) to see how it is used now. [This](https://github.com/Moya/Moya/blob/master/docs/Endpoints.md#request-mapping) can be useful in case of explaining how the closure works nowadays.

Also, I think this might be good idea to introduce #starter-task (stolen from IGListKit 😄, thanks guys!), so I've added the label here.

**Comment by BasThomas** [comment]
I think making issues like these is a really good idea, so thanks for that! Also love the `starter-task`, but we already have the `good first step`. Should we remove that and start using `starter-task`? Also, although this is a nit, let's call it `starter task` to be in line with our other labels?

**Comment by sunshinejr** [comment]
We might want to see what "good first step" is used for, but for me it would be slithly different. E.g. I would use it for an idea that I have and that need improvements, where "starter task" would be rather concrete specification of what's needed, how to achieve that and possible caveats. 

Also, I'm in for changing "starter-task" to "starter task" to keep consistency 👍

**Comment by sunshinejr** [comment]
I'm sorry mr. stalebot, but we have to do this sometime in the future so I'm gonna reopen this. Maybe we should add `starter-task` to labels ignored by `stalebot`? 🤔

**Comment by SD10** [comment]
@sunshinejr What about adding the `documentation` tag instead?@sunshinejr What about adding the `documentation` tag instead?

**Comment by sunshinejr** [comment]
In case of documentation we use additionally `chore` tag which is ignored by `stalebot`. That leads me to a reason why this was closed by our bot 😄 I'm gonna add labels where needed, right now I think all starter tasks are docs, so we should be fine for now.

**Comment by sunshinejr** [comment]
This is covered by #1256.
