### ISSUE TITLE
Add Http Header when conforming to the TargetType protocol

### ISSUE THREAD

**Issue by ercancelik** [Moya/Moya#1138]
Hi,

I am using Moya 8.0.5 and i want to add custom http headers to the request. But still i couldn't found a way to achieve this while conforming to the TargetType protocol.

**Comment by sunshinejr** [comment]
Hey @ercancelik. You are right - you cannot do it in `TargetType` _yet_. This is in our planned 9.0.0 release. Right now you can do it in `endpointClosure` (more details [here](https://github.com/Moya/Moya/blob/9.0.0-dev/docs/Endpoints.md#from-target-to-endpoint)), and after the release you can switch to the new parameter `headers` in `TargetType`.

Let us know if it helped!

**Comment by ercancelik** [comment]
Thank you very much. It helps 👍
