### ISSUE TITLE
Update ReactiveCocoa documentation to ReactiveSwift

### ISSUE THREAD

**Issue by BasThomas** [Moya/Moya#1144]
The documentation still refers to `ReactiveSwift` as `ReactiveCocoa` in both the examples' [README](https://github.com/Moya/Moya/blob/master/docs/Examples/README.md) as well as the [documentation itself](https://github.com/Moya/Moya/blob/master/docs/Examples/ReactiveCocoa.md) (including the document's name).

This should be updated to use the `ReactiveSwift` name. Make sure to also fix all references to these documents - it seems like the only reference to it is in the README: https://github.com/Moya/Moya/search?l=Markdown&q=reactivecocoa.md&type=&utf8=✓.

**Comment by SD10** [comment]
This should be taken care of in #1153, correct?

**Comment by sunshinejr** [comment]
Not exactly @SD10, there are still places where `ReactiveCocoa` is mentioned. Look at the link by @BasThomas.

**Comment by SD10** [comment]
The changes aren't reflected in the search because they are on the `9.0.0-dev` branch. We can wait until they are merged into master to close this. I just don't want someone to get confused and think this is still available as it is a starter task 😅

**Comment by BasThomas** [comment]
Ah, yes - it's been fixed there. Let's close the issue to prevent duplicate PRs, and just wait until the `9.0.0` branch is merged into `master`.
