### ISSUE TITLE
Add Danger warning when changing something in Sources, but there are no changes in Tests

### ISSUE THREAD

**Issue by BasThomas** [Moya/Moya#1145]
When something changes in the `Sources` directory, there's a good possibility of us having to update or add a test in `Tests` as well. Giving a warning via Danger might be a good way to get a nudge in that direction if it's forgotten.

The [Dangerfile](https://github.com/Moya/Moya/blob/master/Dangerfile) should give you a good idea on how to add this.

**Comment by BasThomas** [comment]
Fixed in #1146

**Comment by Dschee** [comment]
Nice idea, just the one thing missing from my "TODOs" list in PRs like #1147 – now I would not need to add those points explicitly, they all are listed in the PR via Danger. 👍

**Comment by BasThomas** [comment]
I guess we could, but it would be a hassle that's not really worth it. Thanks for mentioning it though; I've added a check to see if a migration guide would be necessary for 9.0: https://github.com/Moya/Moya/issues/1075#issue-227035119

**Comment by Dschee** [comment]
If we happen to integrate #1147 then it definitely will, cause it removes `parameters` and `parameterEncoding` which everybody using Moya had to implement. :)

**Comment by BasThomas** [comment]
Yep :)
