### ISSUE TITLE
can't find  MultiMoyaProvider implementation.need help!!

### ISSUE THREAD

**Issue by lovesomeone** [Moya/Moya#1150]
Hi , The documentation about "Advanced usage - use MultiTarget for multiple targets using the same Provider" . where can i get MultiMoyaProvider implementation.  is there a complete implementation??

**Comment by BasThomas** [comment]
Check out the Demo, there's an example with a MultiTarget. Let us know if that helps!

**Comment by lovesomeone** [comment]
sorry  for wrong description  with the question  . what i want to know is that  "when using associated type"

**Comment by lovesomeone** [comment]
sorry for wrong description for the question  

in the documentation  i saw the code

extension MultiMoyaProvider {
    func requestDecoded<T: DecodableTargetType>
    ..........

}

let provider = MultiMoyaProvider()
provider.requestDecoded(UserApi.get(id: 1)) { result in
.......
}

i want to know  MultiMoyaProvider implementation in this case .

thank you for reply

**Comment by sunshinejr** [comment]
Hey @lovesomeone. I went through our docs and surely it could use some improvements. For now I've managed to write some really simple use-case for `MultiMoyaProvider` that compiles. Let me know what do you think!

```swift
protocol TestResultType {
    associatedtype T
    static func parse(_ object: Any) -> Self?
}

protocol DecodableTargetType: Moya.TargetType {
    associatedtype ResultType: TestResultType
}

final class MultiMoyaProvider: MoyaProvider<MultiTarget> {
    
    typealias Target = MultiTarget
    
    override init(endpointClosure: @escaping EndpointClosure = MoyaProvider.defaultEndpointMapping,
                  requestClosure: @escaping RequestClosure = MoyaProvider.defaultRequestMapping,
                  stubClosure: @escaping StubClosure = MoyaProvider.neverStub,
                  manager: Manager = MoyaProvider<Target>.defaultAlamofireManager(),
                  plugins: [PluginType] = [],
                  trackInflights: Bool = false) {
        super.init(endpointClosure: endpointClosure, requestClosure: requestClosure, stubClosure: stubClosure, manager: manager, plugins: plugins, trackInflights: trackInflights)
    }
    
    func requestDecoded<T: DecodableTargetType>(_ target: T, completion: @escaping (_ result: Result<T.ResultType, Moya.Error>) -> ()) -> Cancellable {
        return request(MultiTarget(target)) { result in
            switch result {
            case .success(let response):
                if let parsed = T.ResultType.parse(try! response.mapJSON()) {
                    completion(.success(parsed))
                } else {
                    completion(.failure(.jsonMapping(response)))
                }
            case .failure(let error):
                completion(.failure(error))
            }
        }
    }
}
```

We may want to improve existing docs, maybe creating a new example out of this - this will be a good material for a starter task imho.

**Comment by lovesomeone** [comment]
that's what i want  . thank you very much ! Thank you for your contribution！
