### ISSUE TITLE
the current request is not a multipart request

### ISSUE THREAD

**Issue by codwam** [Moya/Moya#1152]

**Comment by codwam** [comment]
`
enum Router {
    case test(account: String, image: UIImage?)
}

extension Router: TargetType {
        case .test(let account, let _):
            return ["account": account]
}

    var task: Task {
        switch self {
        case .test:
// Is this right?
            if let multipartBody = self.multipartBody, multipartBody.count > 0 {
                return .upload(UploadType.multipart(multipartBody))
            }
            return .request
        default:
            return .request
        }
    }
    
    var multipartBody: [MultipartFormData]? {
        switch self {
        case .test(_, let image):
            guard let uploadImage = image else {
                return nil
           }
            guard let cardFrontImageData = UIImageJPEGRepresentation(uploadImage, 0.5) else {
                return nil
            }
            let imageData = MultipartFormData(provider: .data(cardFrontImageData), name: "serviceImg", fileName: "photo.jpg", mimeType:"image/jpeg")
            return [imageData]
            }
`

If the image is nil, the server response 'the current request is not a multipart request'?

**Comment by sunshinejr** [comment]
@codwam to make your request multipart-friendly, you need to have a `multipartBody` that is not empty and your `method` in `TargetType` must be one of the following:
```swift
.post
.put
.patch 
.connect
```

If you specify the following correctly, there should be no issue on our side. 

From the code you posted it seems like your backend wants `multipart` request on given endpoint, but you are just doing a `request` in case of no image - thus server does not allow the request. 

One of the fixes would be to just switch from optional `UIImage?` to just `UIImage`:
```swift
enum Router {
    case test(account: String, image: UIImage)
}
```


Let us know if it helped!

**Comment by codwam** [comment]
I have an error with the 'Router test', the image is 'UIImage' optional.
And the  method is 'post'.
I use charles watch the request 'Content-type' is not 'multipartdata'(Actual it's 'formdata'?), so it's error

**Comment by sunshinejr** [comment]
Can you post the logs from Charles? Like the whole request you see? (headers, method, body)?

**Comment by codwam** [comment]
If it's no image, the request 'Content-Type' would be below
Request Headers: ["Content-Type": "application/x-www-form-urlencoded; charset=utf-8"]

And the server arise error.

What I mean is in 'MoyaProvider+Internal.swift' line 89:
`
                case .upload(.multipart(let multipartBody)):
                    guard !multipartBody.isEmpty && target.method.supportsMultipart else {
                        fatalError("\(target) is not a multipart upload target.")
                    }
`
Is this must be MultipartFormData's count > 0?

**Comment by sunshinejr** [comment]
It is not a must, @codwam, but having this check should help users when making a mistake by not specifying `multipartFormData`. If you really want to send an empty data, you could try with:
```swift
return .upload(.multipart([MultipartFormData(provider: .data(Data()), name: "serviceImg")]))
```

Let me know what you think :)

**Comment by codwam** [comment]
@sunshinejr  
I didn't think of ' Data() ', Thanks

**Comment by sunshinejr** [comment]
Glad it helped! 🎉
