### ISSUE TITLE
Repeat request in RxMoya

### ISSUE THREAD

**Issue by MrAsterisco** [Moya/Moya#1154]
I'm using the latest version of Moya with RxSwift and I've encountered a logical issue for which I can't find a solution, at the moment.

Let's say that I have a `UITableViewController` with a `ViewModel` that implements the following interface:

```swift
protocol ListViewModelType {
	
	var items: Observable<[Item]> { get }
	
}
```

The `items` property is implemented as (using _EVReflection_):

```swift
var items: Observable<[Therapy]> {
		get {
			let provider = RxMoyaProvider<ItemService>()
			return provider
				.request(.all)
				.map(toArray: Item.self)
		}
	}
```

In the `viewDidLoad` method of the `UITableViewController`, I have set up a binding between the `items` property and the `tableView` via the following code:

```swift
self.viewModel.items
			.bind(to: tableView.rx.items(cellIdentifier: cellIdentifier, cellType: cellType)) { row, element, cell in
				// cell configuration code
			}
			.disposed(by: self.disposeBag)
```

Now, I would like to refresh the content of the `UITableView` to reflect changes that the user has done through other parts of the app. Considering that the `RxMoyaProvider` returns an `Observable`, this should be easily done through another value emitted by the `Observable`, but I don't know how to communicate to the provider that it should refresh the content from the server and put it into the same `Observable`.

Am I missing something here? Is there a more recommended way to bind a `UITableView` to a list of objects coming from a `RxMoyaProvider`?

**Comment by sunshinejr** [comment]
Hey @MrAsterisco. This is a very good question. Usually, I have a `refresh` observable that would cover that for me. So my usual stack would be somewhat similar to:
```swift
final class TestViewModel {
    
    let refresh: Observable<Void>
    let items: Observable<[Item]>
    
    private let provider: RxMoyaProvider<GitHub>
    
    init(refresh: Observable<Void>, provider: RxMoyaProvider<GitHub>) {
        self.refresh = refresh
        self.provider = provider
        
        self.items = refresh
            .flatMapLatest { [unowned self] in
                self.provider.request(.zen)
            }
            .map(toArray: Item.self)
    }
}
```

This way every time `refresh` observable produces next element, my items refresh with it. This `refresh` observable might be also `Subject` or `Action`, whatever works for you. 

Let me know if it helped 👍

**Comment by MrAsterisco** [comment]
Hi @sunshinejr ,

First of all, thanks for your help.

I've also asked [this question](https://stackoverflow.com/questions/44886093/repeat-request-in-rxmoya/44889220?noredirect=1#comment76757503_44889220) on StackOverflow and they came out with a solution very similar to yours (even if, I think that yours is more elegant).

The thing that I don't like of this solution is that I have to declare an Observable (maybe a `Variable`) in each `ViewController` that I manually change and which triggers the refresh on each `ViewModel`. 

Ideally, I would expect to have some sort of _wrapper_ that joins the `RxMoyaProvider` with the resulting `Observable` and exposes a method (something like `redo()` or `request()` once again) that does exactly the same thing, but behind the scenes.

What do you think?

**Comment by sunshinejr** [comment]
Hey @MrAsterisco. Yeah, it is one of the most common usages of reactive extensions. You don't necessarily need to make a `Variable`, you want to refresh your items based on some sort of event. This event could be passed to the view model from view controller and thus could trigger the refresh. E.g. you can pass observable that on each button click it refreshes the items:

```swift
let viewModel = TestViewModel(refresh: refreshButton.rx.tap.map { _ in })
```

However your idea could work as well. You could make your own subclass of MoyaProvider that covers a function of `repeatLastRequest()`, but it would require saving state in the normal, overridden `request` function. It could be tricky (probably needs some locks), but it should work.

**Comment by MrAsterisco** [comment]
Ok, I see the challenge here. Well, let's close this for now. When I'll have some spare time I'll try to push a new branch with some ideas; then we'll be able to discuss if they works and should be merged or not.

**Comment by sunshinejr** [comment]
Of course! 👍  Let me know if I can be any help.
