### ISSUE TITLE
How to Send a delete request with parameters

### ISSUE THREAD

**Issue by zichenJack** [Moya/Moya#1166]
```swift
var method: Moya.Method {
        switch self {
        case .deleteLike:
            return .delete
        }
    }
```
but I have some parameter want to send,How should I do?

**Comment by pietrocaselani** [comment]
Hi @zichenJack 
I think you can just implement the `parameters` and `parametersEncoding` from `TargetType` protocol. See [this documentation](https://github.com/Moya/Moya/blob/master/docs/Targets.md).

**Comment by zichenJack** [comment]
sorry , I was write return nil in `parameters` , so Xcode show me code never executed
