### ISSUE TITLE
Invalid Bundle - Xcode 9 Beta 2

### ISSUE THREAD

**Issue by abeintopalo** [Moya/Moya#1167]
First, thank you for this great library. It works pretty nicely. The problem is not coding issue but configuration. It seems that Apple has added some new verification rules for submitted binaries. 
I have an app which uses Moya as a dependency using Carthage.
Carthage config: ```github "Moya/Moya``` resolved Moya version ```8.0.5```

I've built and tested my app and uploaded to iTunes Connect and the upload was successful but the binary processing failed:
```
Dear developer,

We have discovered one or more issues with your recent delivery for "<app name>". To process your delivery, the following issues must be corrected:

Invalid Bundle - Disallowed LLVM instrumentation. Do not submit apps with LLVM profiling instrumentation or coverage collection enabled. Turn off LLVM profiling or code coverage, rebuild your app and resubmit the app.

Once these issues have been corrected, you can then redeliver the corrected binary.

Regards,

The App Store team
```

Of course, it was very difficult to figure out what was the problem. I've check all Xcode settings in my app but didn't find anything suspicious. I've also posted a question in Apple forum: [Invalid Bundle - Xcode 9 Beta 2](https://forums.developer.apple.com/thread/81893?q=Xcode%209%20beta)

Luckily, I've got response from on the Apple forum that was helpful. 
I've went through all my 3rd party library dependencies and checked build settings and build scheme settings for all of them.
During this search I've found that _Moya_, _RxMoya_, _ReactiveMoya_ schemes have ```Gather coverage data``` enabled. 
I needed to disable this settings during the build for all the build schemes (_Moya_, _RxMoya_, _ReactiveMoya_) for Moya to be able to get my app's binary successfully processed by iTunes Connect.

So, I guess we need to turn this setting off otherwise people will fail their binary submission.

**Comment by sunshinejr** [comment]
Hey @abeintopalo, thank you so much for this detailed explanation! Really awesome of you.

About the problem - yeah, we got 4 schemes and each one is gathering coverage data. It _should_ work just fine with _MoyaTests_ doing that, we gotta see and test. Would you be up for doing a PR? You would have to branch from `9.0.0-dev` and target that one in the PR, though.

**Comment by abeintopalo** [comment]
@sunshinejr hi, just created a pull request: https://github.com/Moya/Moya/pull/1169
Please, verify it.

**Comment by sunshinejr** [comment]
Thank you @abeintopalo! I'll try to get to it & test it whenever I have some free time. Maybe someone else will be free to check it before me, though! Also, from the PR it seems like codecov integration didn't break (I think), so it is a good sign 😄

**Comment by sunshinejr** [comment]
I'm gonna close this one and we will focus on this matter in the PR @abeintopalo created (#1169). 👍
