### ISSUE TITLE
How to reauthenticate using Bearer HTTP Auth

### ISSUE THREAD

**Issue by ArthurAlvarez** [Moya/Moya#1174]
I am currently developing an app using Moya 8.0.5 and I have to consume an API that uses Bearer HTTP Auth with a token that expires every 8 hours.

Is there an easy way in Moya to reauthenticate (aka call an endpoint to update the token) when it expires, and then redo the request? I can't rely on a timestamp to know if the token is expired and have to do it after a request returns http status 401.

Currently I am checking in every endpoint response if the HTTP status is 401, and if it is, I call an endpoint to get a new token and then redo the original request with it.

Thank you!

**Comment by sunshinejr** [comment]
Hey @ArthurAlvarez. This is a good one!

I must say that there is no _easy_ way to do it right now. We have an [AccessTokenPlugin](https://github.com/Moya/Moya/blob/master/Sources/Moya/Plugins/AccessTokenPlugin.swift), but it doesn't allow to change the token or refresh it easily.

I really like your solution though! What I could add to that is to save token duration and if you know it expired, just send a request for token and then a normal request. This way you can avoid 1 request that shouldn't be needed.

I feel like it could even be a good CocoaPod out of it - one that handles full OAuth in Moya. I was thinking about plugin, but not sure we can do it with current plugin limitations.

**Comment by AndrewSB** [comment]
@ArthurAlvarez this conversation may help https://github.com/Moya/Moya/issues/748#issuecomment-264572164
