### ISSUE TITLE
RxMoyaProvider with TestScheduler

### ISSUE THREAD

**Issue by dindonkey** [Moya/Moya#1179]
Hi all,
I'm using Moya 8.0.

I found something similar to this:
```swift
let provider = ReactiveSwiftMoyaProvider<JokesService>(stubScheduler: scheduler, stubClosure: MoyaProvider.immediatelyStub)
```
How I can use TestScheduler with RxMoyaProvider ?

Thank you,
you're doing a great job!

**Comment by sunshinejr** [comment]
Hey @dindonkey. You can use it the same way as any other `Observable`. Below is the simple test taken from `RxSwift` repository:
```swift
func testSequenceOf_complete_immediate() {
    let scheduler = TestScheduler(initialClock: 0)
    let res = scheduler.start {
        Observable.of(3, 1, 2, 4)
    }
    
    XCTAssertEqual(res.events, [
        next(200, 3),
        next(200, 1),
        next(200, 2),
        next(200, 4),
        completed(200)
    ])
}
```

This code above is a simple test from `RxSwift ` using `TestScheduler`. What you want to do is to replace `Observable` in `scheduler.start` method and then assert whatever you like:

```swift
    let res = scheduler.start {
        provider.request(target)
    }

    XCTAssertEqual(res.events, [
        next(200, response),
        completed(200)
    ])
```

This code above might not compile since I didn't try this one out, but the idea should be precise. Also don't forget to manipulate `stubClosure` in your tests 😄 

Let me know if it helped or if you have more questions about it 🐼

**Comment by dindonkey** [comment]
Hi guys,
I'm trying to test a more complex situation with Drivers :P 
It's based on Drivers example here https://github.com/ReactiveX/RxSwift/blob/master/RxExample/RxExample-iOSTests/RxExample_iOSTests.swift 

Here's my view model:

```swift
class JokesViewModel {
    
    let jokes: Driver<[Joke]>
    
    init(
        refreshDriver: Driver<Void>,
        jokesProvider: RxMoyaProvider<JokesService>
        ) {
        
        jokes = refreshDriver
            .flatMapLatest { _ in
                return jokesProvider
                    .request(.random(numJokes: 5))
                    .mapArray(type: Joke.self, keyPath: "value")
                    .asDriver(onErrorJustReturn:[])
                    .debug("DEBUG!! random call")
        }
        .debug("DEBUG!! jokes")
    }
}

```

And here's my test:
```swift
class ChuckNorrisJokesMVVMTests: XCTestCase {
    
    override func setUp() {
        super.setUp()
    }
    
    func testJokes() {
        let scheduler = TestScheduler(initialClock: 0)
        
        driveOnScheduler(scheduler) {
    
            let refreshDriver = scheduler
                .createHotObservable([next(0, ())])
                .asDriver(onErrorJustReturn: ())
            
            let provider = RxMoyaProvider<JokesService>(stubClosure: MoyaProvider.immediatelyStub)
            let viewModel = JokesViewModel(refreshDriver: refreshDriver, jokesProvider:provider)
            
            let recordedJokes = scheduler.record(source: viewModel.jokes)
        
            scheduler.start()
            
            XCTAssertEqual(2, recordedJokes.events.count)
        }
        
    }
    
}

extension TestScheduler {
    func record<O: ObservableConvertibleType>(source: O) -> TestableObserver<O.E> {
        let observer = self.createObserver(O.E.self)
        let disposable = source.asObservable().bind(to: observer)
        self.scheduleAt(100000) {
            disposable.dispose()
        }
        return observer
    }
}

```

When I run the test, I can see in debug outputs that the driver is subscribed but no items are coming from the moya service:

> 

2017-07-24 17:28:38.784: DEBUG!! jokes -> subscribed
2017-07-24 17:28:38.791: DEBUG!! random call -> subscribed
2017-07-24 17:28:38.797: DEBUG!! jokes -> isDisposed
2017-07-24 17:28:38.797: DEBUG!! random call -> isDisposed

> 

If I run the application, everything is working and I get data from the request, so it seems something related to the test thread or test scheduler.... Help! :)

**Comment by AndrewSB** [comment]
@dindonkey I have a feeling that your Drivers are being disposed of before the subscriptions can fire and propagate next events. You may need to use one of the RxBlocking operators after you `scheduler.start()` to fix that
