### ISSUE TITLE
Update ReactiveSwift dependency to 2.0

### ISSUE THREAD

**Issue by larryonoff** [Moya/Moya#1182]
Hello Community, I just making request for update ReactiveSwift dependency to 2.0.

**Comment by sunshinejr** [comment]
Hey @larryonoff! Your proposal is just in time for our 9.0.0 version 😄 I think this one can get in as well, what do you guys think, @Moya/contributors?

**Comment by AndrewSB** [comment]
Sounds good to me!

**Comment by sunshinejr** [comment]
Cool! I think we should do it after #1181 merges onto master since there are many changes already.

Also, maybe you would be up for doing PR with the update, @larryonoff? 😉

**Comment by larryonoff** [comment]
@sunshinejr I wanted to do PR. I'm sure that it should be very easy PR. But I didn't find quickly how to configure the project dependencies for contributing. Could anyone please assist? Is it just one Carthage command?

**Comment by SD10** [comment]
@larryonoff `carthage bootstrap`

**Comment by larryonoff** [comment]
@SD10 thank you!

**Comment by larryonoff** [comment]
created PR #1185
