### ISSUE TITLE
RxMoya, how to controll whether to show a loading view while requesting?

### ISSUE THREAD

**Issue by lhalcyon** [Moya/Moya#1184]
as it's described on title,how to  controll whether to show a loading view.
i know plugin like NetworkActivityPlugin in demo support show/hide loading view, but it works for all api request . 

i want to show loading/hide view depending on the specific api type.  

for example,to get one's profile, i want to request silently but to request a list , i want user know our app is loading.

**Comment by sunshinejr** [comment]
Hey @lhalcyon. It seems like we don't have that option right now, but to allow this behavior we could just add another parameter in [NetworkActivityClosure](https://github.com/Moya/Moya/blob/master/Sources/Moya/Plugins/NetworkActivityPlugin.swift#L12), from:
```swift
(_ change: NetworkActivityChangeType) -> Void
```
to
```swift
(_ change: NetworkActivityChangeType, _ target: TargetType) -> Void
```

and this way you could make conditional statements based on `TargetType`. Also, I think this would be a valuable addition to our codebase, so maybe you would you be up for a PR? 😉
