### ISSUE TITLE
Update master readme for Swift 3.2 and Swift 4.0

### ISSUE THREAD

**Issue by Coeur** [Moya/Moya#1186]
Current Moya Readme shows:

| Swift version | Moya version  |
| ------------- | ------------- |
| 3.X           | >= 8.0.0      |

* Can you double check that Moya 8.0.0 is OK for Swift 3.2 (on Xcode 9)? Otherwise, please specify the Moya branch/version for it
* Can you document the Moya branch/version for Swift 4?

**Comment by sunshinejr** [comment]
We should do that for our 9.0.0 release, gonna make sure people will have a clear view as of which version they can use for their app. Thanks for reporting, @Coeur 👍

**Comment by BasThomas** [comment]
`8.0.5` with Xcode `8.3.3`: ✅
`8.0.5` with Xcode `9.0` (opened with the previous project): ✅
`8.0.5` with Xcode `9.0`: ❌
`8.0.5` with Xcode `8.3.3` (opened with the previous project and Deployment target reset to `10.3`: ❌

**Comment by sunshinejr** [comment]
This should be resolved in #1239.

**Comment by 3a4oT** [comment]
Hey. "8.0.5 with Xcode 9.0 (opened with the previous project)" can you please explain in more detail what does it mean? Currently I have a problem with migration to *xcode 9*. I got **Task failed with exit code 65:**. I use *Moya 8.0.5*, *RxSwift 3.6.1*.
> carthage version 0.25.0
> xcodebuild -version Xcode 9.0 Build Version 9A235

I used **carthage update Moya --platform ios**

**Comment by 3a4oT** [comment]
Ok. So after I did 
> rm -rf ~/Library/Caches/org.carthage.CarthageKit/DerivedData
AND
> carthage bootstrap --platform ios --cache-builds --toolchain com.apple.dt.toolchain.XcodeDefault 

I was able to migrate successfully. Hate the date when I assumed that Swift 3 is stable enough to start using it. Maybe Swift 6 will=)
