### ISSUE TITLE
 Xcode9  +moya(9.0.0-alpha.1)   after pod install,then display compile error

### ISSUE THREAD

**Issue by lovesomeone** [Moya/Moya#1189]
I create an new project ,named Swift4Demo . then pod install moya . that's it ,then when i open Swift4Demo.xcworkspace   . build it .  but   error appears

Environment  ： Xcode_9_beta_3 + moya (branch9.0.0-alpha.1)

Swift Complier Error 
    Static method 'reversedPrint(_:terminator:items:)' is fileprivate and cannot be referenced from a     default argument value
NetworkLoggerPlugin.swift

can anyone know  how to solve it

**Comment by BasThomas** [comment]
Hey @lovesomeone. Thanks for reporting this. Moya does not (yet) support Swift 4 in v9.

**Comment by lovesomeone** [comment]
thank you  for  replay。    oh  that’s disappointment 。can i kown  when moya support swift4   。 do you have plan，

**Comment by sunshinejr** [comment]
Hey @lovesomeone. We don't really need to do much to support Swift 4.0 in Moya core (without RxSwift/ReactiveSwift extensions). I think we can squeeze this one in alpha.2 or beta version of 9.0.0 😉 

Right now you can just use Swift 3.2 version of our pod, which should work with your 4.0 project.

**Comment by lovesomeone** [comment]
ok  I will try to use swift3.2 .  thank you for you help!
