### ISSUE TITLE
Update reactive docs.

### ISSUE THREAD

**Issue by sunshinejr** [Moya/Moya#1191]
In 9.0.0 release we deprecate both reactive providers. However, in our `Readme.md` we still encourage to use them. We need to update `Readme.md` to use classic `MoyaProvider` and both `provider.rx.request` & `provider.reactive.request` instead. 

We also forgot about updating [docs/RxSwift](https://github.com/Moya/Moya/blob/master/docs/RxSwift.md) and [docs/ReactiveSwift](https://github.com/Moya/Moya/blob/master/docs/ReactiveSwift.md). I think we don't need to remove the reactive providers usage in the docs (besides Readme), but we should label it with **DEPRECATED** sign. And add both requests usage (with and without progress) at the top of the file maybe.

When we cover all of the above, we can remove both providers docs from  examples ([docs/Examples/RxSwift](https://github.com/Moya/Moya/blob/master/docs/Examples/RxSwift.md), [docs/Examples/ReactiveSwift](https://github.com/Moya/Moya/blob/master/docs/Examples/ReactiveSwift.md)). Right now I feel they do not provide any value. We just need to make sure we got everything in the `docs` part and it should be alright.

**Comment by BasThomas** [comment]
I think these have been lost with merging somewhere? Pretty sure those were updated. 🤔

**Comment by sunshinejr** [comment]
Yup those were, but unfortunately only examples 😢
