### ISSUE TITLE
How do you use moya for HTTPS

### ISSUE THREAD

**Issue by xavierXing** [Moya/Moya#1195]
The project is a self-built certificate. How can I verify HTTPS for the moya setup?

**Comment by sunshinejr** [comment]
Hey @xavierXing. You would have to use your own `manager` in `MoyaProvider` for that one. You would then configure your certificate handling in it. You can see how we use it in our `defaultAlamofireManager`:
```swift
public final class func defaultAlamofireManager() -> Manager {
    let configuration = URLSessionConfiguration.default
    configuration.httpAdditionalHeaders = Manager.defaultHTTPHeaders
    
    let manager = Manager(configuration: configuration)
    manager.startRequestsImmediately = false
    return manager
}
```

Of course this one doesn't have certs handling in it. But you can just use the same setup as for self-signed certs in Alamofire.

Let me know if you have any more questions about it :)

**Comment by pedrovereza** [comment]
@xavierXing Hey, I have a [demo project that shows how to used self-signed certificates with Moya](https://github.com/pedrovereza/SelfSignedMoya). Let me know if you have any questions :wink:

**Comment by xavierXing** [comment]
@sunshinejr  @pedrovereza  
Thank you very much for your help. I have read the open direct mouth and tried to customize the manager and let the manager be the parameter of Moya, but it is not useful. Is my func wrong? Thank you again for helping me!!


Could you tell me the two person's instant messaging, for example, WeChat or something?

**Comment by sunshinejr** [comment]
Hey @xavierXing. Please post your code and we will try to help you :)

**Comment by xavierXing** [comment]
@sunshinejr  OK this is my code 

var baseLink: String = "http://api.news18a.com/"

enum MoyaNewsCar {
  case hotSpot,video,live,business,evaluating,shopping,newCar,useCar,calture,travel,technology,market
}

extension MoyaNewsCar: TargetType {

  var baseURL: URL {
    return URL(string: baseLink)!
    
  }
  

  var path: String {
      return "init.php"
  }
  
 
  var method: Moya.Method {
      return .get
  }
  

  var parameters: [String: Any]? {
    switch self {
    case .hotSpot:
      return [
        "m": "ina_app",
        "c": "index",
        "a": "index_new"
      ]
    case .video:
      return [
        "m": "ina_app",
        "c": "vedio",
        "a": "focus"
      ]
    case .live:
      return [
        "m": "ina_app",
        "c": "vedio",
        "a": "new_live"
      ]
    case .business: 
      return [
        "m": "ina_app",
        "c": "index",
        "a": "storylist",
        "storyType": "industry"
      ]
    case .evaluating:
      return [
        "m": "ina_app",
        "c": "index",
        "a": "storylist",
        "storyType": "evaluation"
      ]
    case .shopping:
      return [
        "m": "ina_app",
        "c": "index",
        "a": "storylist",
        "storyType": "guide"
      ]
    case .newCar:
      return [
        "m": "ina_app",
        "c": "index",
        "a": "storylist",
        "storyType": "newCar"
      ]
    case .useCar:
      return [
        "m": "ina_app",
        "c": "index",
        "a": "storylist",
        "storyType": "useCar"
      ]
    case .calture:
      return [
        "m": "ina_app",
        "c": "index",
        "a": "storylist",
        "storyType": "culture"
      ]
    case .travel:
      return [
        "m": "ina_app",
        "c": "index",
        "a": "storylist",
        "storyType": "travel"
      ]
    case .technology:
      return [
        "m": "ina_app",
        "c": "index",
        "a": "storylist",
        "storyType": "technology"
      ]
    case .market:
      return [
        "m": "ina_app",
        "c": "index",
        "a": "storylist",
        "storyType": "market"
      ]
    }
    
  }
  
  
  var parameterEncoding: ParameterEncoding {
    return URLEncoding.default
  }
  
  var sampleData: Data {
    return "{}".data(using: String.Encoding.utf8)!
  }
  
 
  var task: Task {
    return .request
  }
  
  /// 是否执行Alamofire验证。默认为"false"
  var validate: Bool {
    return true
  }
}

class NewsNetServer: NSObject {
  
 
  var netWorkDataType: MoyaNewsCar! = .hotSpot
  
  
  public func moyaGetData(type: MoyaNewsCar, success: @escaping (_ result : NSDictionary) -> (),failed: @escaping (_ error : String) -> ()) -> Void {
    MoyaNewsCarProvider.request(type) { (result) in
      do {
        let response = try result.dematerialize()
        let value = try response.mapNSDictionary()
        success(value)
      } catch {
        let errorPrint = error as CustomStringConvertible
        let errorMessage = errorPrint.description
        failed(errorMessage)
      }
    }
  }

}

//MARK: - Private Method -
extension NewsNetServer {
  
}



extension Moya.Response {
  func mapNSDictionary() throws -> NSDictionary {
    let any = try self.mapJSON()
    guard let dictionary = any as? NSDictionary else {
      throw MoyaError.jsonMapping(self)
    }
    return dictionary
  }
  
  func mapNSArray() throws -> NSArray {
    let any = try self.mapJSON()
    guard let array = any as? NSArray else {
      throw MoyaError.jsonMapping(self)
    }
    return array
  }
  
}


let MoyaNewsCarProvider = MoyaProvider<MoyaNewsCar>(endpointClosure: endpointClosure ,plugins: [NetworkLoggerPlugin(verbose: true, responseDataFormatter: JSONResponseDataFormatter)])


let endpointClosure = { (target: MoyaNewsCar) -> Endpoint<MoyaNewsCar> in
  let defaultEndpoint = MoyaProvider.defaultEndpointMapping(for: target)
  return defaultEndpoint.adding(newHTTPHeaderFields: ["VersionCode": "201"])
}


private func JSONResponseDataFormatter(_ data: Data) -> Data {
  do {
    let dataAsJSON = try JSONSerialization.jsonObject(with: data)
    let prettyData = try JSONSerialization.data(withJSONObject: dataAsJSON, options: .prettyPrinted)
    return prettyData
  } catch {
    return data
  }
}

**Comment by sunshinejr** [comment]
Hey @xavierXing. From your code I don't see any `manager` that you are creating and passing to the `MoyaProvider`. You can checkout the full demo of how would you do it - [pedrovereza/SelfSignedMoya](https://github.com/pedrovereza/SelfSignedMoya).

In short you would need to create a manager:
```swift
import Alamofire

class CustomServerTrustPoliceManager : ServerTrustPolicyManager {
    override func serverTrustPolicy(forHost host: String) -> ServerTrustPolicy? {
        return .disableEvaluation
    }
    public init() {
        super.init(policies: [:])
    }
}

let manager = Manager(
    configuration: URLSessionConfiguration.default,
    serverTrustPolicyManager: CustomServerTrustPoliceManager()
)
```

And then add it to your provider:
```swift
let MoyaNewsCarProvider = MoyaProvider<MoyaNewsCar>(endpointClosure: endpointClosure , manager: manager, plugins: [NetworkLoggerPlugin(verbose: true, responseDataFormatter: JSONResponseDataFormatter)])
```

And don't forget to set `Allow Arbitrary Loads = YES` in `Info.plist`.

Please let me know if you have further questions!
