### ISSUE TITLE
The URL in the `?` is turned into `%3F`, causes the return data exception

### ISSUE THREAD

**Issue by ONECATYU** [Moya/Moya#1198]
I have this problem: when I request arguments in URL, such as: http://www.xxxx.com/app/MobileService?action=xxxx. when the request is sent, the URL in the `?` is turned into `%3F` by the `url(for target: Target) -> URL` method, causing the request to fail.

the method: 
```swift
private final class func url(for target: Target) -> URL {
        if target.path.isEmpty {
            return target.baseURL
        }

        return target.baseURL.appendingPathComponent(target.path)
    }
 ```
The parameters in the url are added to the `[String: Any]` dictionary, and the work is normal

**Comment by panjiulong** [comment]
I have the same question ，have you fix it ?

**Comment by WeiRujian** [comment]
you can set a good success:

// MARK: - Set the request to the head
let myEndpointClosure = { (target: RequestAPI) -> Endpoint<RequestAPI> in
    
    
    print("baseURL:\(target.baseURL)\n path:\(target.path)")
    
    
    let url = target.baseURL.absoluteString + target.path
    
    print("url:\(url)")
    //http://XXXX/api/xlogin.ashx?action=xulogin
    
    
    //This method will escape special characters
    //let url = target.baseURL.appendingPathComponent(target.path).absoluteString
    //http://XXXX/api/xlogin.ashx%3Faction=xulogin
   
    
    let endpoint = Endpoint<RequestAPI>(
        url: url,
        sampleResponseClosure: { .networkResponse(200, target.sampleData) },
        method: target.method,
        parameters: target.parameters,
        parameterEncoding: target.parameterEncoding
    )
    
    //Set up your header information
    return endpoint.adding(newHTTPHeaderFields: [:])
    
}
let LoginProvider = RxMoyaProvider<RequestAPI>(endpointClosure: myEndpointClosure)

**Comment by ZhuZijun** [comment]
public extension URL 
{ 
 ...
 self = URL.init(string: target.baseURL.absoluteString + target.path)!    
}
