### ISSUE TITLE
Support one MoyaProvider instance, and mutil request?

### ISSUE THREAD

**Issue by ondev** [Moya/Moya#1199]
Does Moya support it?  create one MoyaProvider instance in my ViewController,  and more than one request it in viewDidLoad

**Comment by SD10** [comment]
@ondev Have you been able to find any useful documentation? 
I recommend reading [Targets.md](https://github.com/Moya/Moya/blob/master/docs/Targets.md) and [Basic.md](https://github.com/Moya/Moya/blob/master/docs/Examples/Basic.md). 

The `MoyaProvider` is generic over an object conforming to the `TargetType` protocol. 
Your `MoyaProvider` instance can make any number of requests to the underlying `TargetType`.

**Comment by ondev** [comment]
@SD10 I don't find any document, after my research, I think can support,  because the request returned task is a cancelable object.  like NSURLSession, can make mutil-requests on a single instance
