### ISSUE TITLE
My request responses treated as RTO error by Moya and RxMoya in iOS 8 & 9

### ISSUE THREAD

**Issue by edopelawi** [Moya/Moya#1200]
Dear Moya maintainers, I was using this library to hit an URL, which always ended up treated as an RTO.

I tried to hit a URL that returns this JSON:
```json
{
    "data": null
}
```

It's a plain GET request with Content-Type and Token header, and it returns HTTP 200 when I tried it using Postman or other platform (e.g. Android). Strangely, the similar request ended up as a RTO error:

```
Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSUnderlyingError=0x7f91593088b0 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, NSErrorFailingURLStringKey=[REDACTED], NSErrorFailingURLKey=[REDACTED], _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=The request timed out.
```

I initially used RxMoyaProvider and tried to change it with MoyaProvider, only to find the same error occurs. The code I'm using is roughly like this:

```swift

provider.request(.currentTarget)
    .subscribe(
        onNext: { [weak self] response in
            // Response code handling here
        },
        onError: {  [weak self] error in
            // Error code handling here					
        }
    )
    .addDisposableTo(disposeBag)

```

I'm currently using Moya 8.0.5, along with Alamofire 4.5.0 and RxSwift 3.4.0, all of them installed through Carthage. As the title mentioned, this only occurs in iOS 8 & 9, both in simulator and device.

Any help would be appreciated. Thanks in advance!

**Comment by edopelawi** [comment]
Wait - upon further inspection, it turns out I used `JSONEncoding` for the target's `parameterEncoding`, where it supposed to have no JSON parameter. Changing it to `URLEncoding` fixes this issue.

Apologies for the rubber-ducking, stay awesome dear Moya team!

**Comment by sunshinejr** [comment]
Hey @edopelawi. Thank you for your really well written description of the issue! Glad you figured this out. 😉
