### ISSUE TITLE
pod 'Moya/RxSwift',  can't find MoyaProvider+Rx.swift

### ISSUE THREAD

**Issue by ondev** [Moya/Moya#1202]
I have add pod 'Moya/RxSwift' to my Podfile, after pod update,  I can't find MoyaProvider+Rx.swift in my pod sub-folder.

cocospod is 1.3.0
xcode 8.3.3

**Comment by BasThomas** [comment]
What is your current Moya version? You can check in the `Podfile.lock`. And can you maybe also share the contents of your Podfile itself? I just set up a fresh projects and everything builds fine. Moya is using `8.0.5` there.

**Comment by ondev** [comment]
`target 'xxx' do

  # Pods for xxx
  pod 'SwiftProtobuf', '~> 0.9.903'
  pod 'CoreStore', '~> 4.0'           
  pod 'XCGLogger', '~> 5.0.1'         
  pod 'Moya/RxSwift'               
  pod 'CryptoSwift'                   
  pod 'SwiftyJSON'                  
  pod 'ObjectMapper'                
  pod 'KeychainAccess'              
  pod 'SwiftyUserDefaults'           
end`

**Comment by ondev** [comment]
I try to use Moya with RxSwift as the document: https://github.com/Moya/Moya/blob/master/docs/RxSwift.md

provider have no rx property,
only use the RxMoyaProvider,  the document is not update?

**Comment by ondev** [comment]
![screen shot 2017-08-09 at 09 26 27](https://user-images.githubusercontent.com/5305009/29101481-06ba748e-7ce5-11e7-8b26-2c176a68847b.png)
In the pod folder Moya/RxSwift , have no  MoyaProvider+Rx.swift

Very strange.

**Comment by ondev** [comment]
I got it,  this is Moya version 8.0.5 version. MoyaProvider+Rx.swift is in version 9.0
