### ISSUE TITLE
Use RxMoyaProvider or MoyaProvider.rx with RxSwift?

### ISSUE THREAD

**Issue by aelam** [Moya/Moya#1207]
Moya: 8.0.5

I'm using RxSwift with Moya,  the readme file uses `provider.rx` but I can't 
And there is a `RxMoyaProvider` in Moya 
Which one is the recommended method to do things ?

```swift
provider = MoyaProvider<GitHub>()
provider.rx.request(.userProfile("ashfurrow")).subscribe { event in
    switch event {
    case let .next(response):
        image = UIImage(data: response.data)
    case let .error(error):
        print(error)
    default:
        break
    }
}
```

**Comment by SD10** [comment]
Hey @aelam,
The current documentation is representing Moya [v9.0.0-alpha.1](https://github.com/Moya/Moya/releases/tag/9.0.0-alpha.1). If you want to continue using Moya `8.0.5` you will need to use the `RxMoyaProvider`. Let me know if this helps 😃

**Comment by BasThomas** [comment]
Exactly what @SD10 said. You can browse the `8.0.5` documentation here: https://github.com/Moya/Moya/tree/4512a2a4bc8019cf006434378ac6a0640f34f35f/docs

**Comment by aelam** [comment]
Thanks guys!! Will read more details

**Comment by evyasafm** [comment]
Add to Podfile: 
`pod 'Moya/RxSwift'`
