### ISSUE TITLE
Undeclared type 'DateScheduler'

### ISSUE THREAD

**Issue by riyanpratama** [Moya/Moya#1208]
Hi, I am installing Moya 8.0.5 and found this problem. I can't install Moya via Carthage, it stopped in `Building scheme "ReactiveMoya" in Moya.xcodeproj`. 

This is the error log
```
*** Building scheme "Moya" in Moya.xcodeproj
*** Building scheme "RxMoya" in Moya.xcodeproj
*** Building scheme "ReactiveMoya" in Moya.xcodeproj
Build Failed
	Task failed with exit code 65:
```

And then, I checked its log file. It says that it has undeclared `DateScheduler`
`myproject/Carthage/Checkouts/Moya/Sources/ReactiveMoya/ReactiveSwiftMoyaProvider.swift:9:32: error: use of undeclared type 'DateScheduler'`

Here is my Cartfile
```ruby for CocoaPods
github "skywinder/ActionSheetPicker-3.0" "2.2.0"
github "Alamofire/Alamofire" "4.3.0"
github "Moya/Moya"
github "Ekhoo/Device" "2.0.1"
github "hackiftekhar/IQKeyboardManager" "v4.0.8"
github "auth0/JWTDecode.swift" "2.0.0"
github "marmelroy/Localize-Swift" "1.7.1"
github "Hearst-DD/ObjectMapper" "2.2.2"
github "antitypical/Result" "3.1.0"
github "ReactiveX/RxSwift" "3.2.0"
github "rs/SDWebImage" "3.8.2"
github "SVProgressHUD/SVProgressHUD" "2.1.2"
github "SnapKit/SnapKit" "3.1.1"
github "TTTAttributedLabel/TTTAttributedLabel" "2.0.0"
github "kasketis/netfox" "01c8a05f3a376180691c7fc61e76eae49ed9ac1f"
github "RxSwiftCommunity/Action" "2.2.1"
github "ReactiveCocoa/ReactiveSwift" "1.0.0"
```

Is there anything I missed?
Thank you!

**Comment by SD10** [comment]
@riyanpratama Let me preface this by saying I don't know much about Carthage.
It looks like you're using `ReactiveSwift 1.0.0` and `DateScheduler` was added in version [1.1.0](https://github.com/ReactiveCocoa/ReactiveSwift/releases/tag/1.1.0).

I think that Moya `8.0.5` has a minimum ReactiveSwift requirement of `1.1.0`.

Let me know if this helps.

**Comment by riyanpratama** [comment]
I switched to `Moya 8.0.2` that support with `ReactiveSwift 1.0.0`, so here is my Cartfile

```
github "skywinder/ActionSheetPicker-3.0" "2.2.0"
github "Alamofire/Alamofire" "4.3.0"
github "Ekhoo/Device" "2.0.1"
github "hackiftekhar/IQKeyboardManager" "v4.0.8"
github "auth0/JWTDecode.swift" "2.0.0"
github "marmelroy/Localize-Swift" "1.7.1"
github "Hearst-DD/ObjectMapper" "2.2.2"
github "antitypical/Result" "3.1.0"
github "ReactiveX/RxSwift" "3.2.0"
github "rs/SDWebImage" "3.8.2"
github "SVProgressHUD/SVProgressHUD" "2.1.2"
github "SnapKit/SnapKit" "3.1.1"
github "TTTAttributedLabel/TTTAttributedLabel" "2.0.0"
github "kasketis/netfox" "01c8a05f3a376180691c7fc61e76eae49ed9ac1f"
github "RxSwiftCommunity/Action" "2.2.1"
github "ReactiveCocoa/ReactiveSwift" "1.0.0"
github "Moya/Moya" "8.0.2"
```

But when I install it, I got 

```
MyProject/Carthage/Checkouts/Moya/Sources/Moya/MoyaAvailability.swift:42:64: error: 'Error' has been renamed to 'MoyaError': Moya.Error has been renamed to MoyaError in version 8.0.0
```

**Comment by BasThomas** [comment]
You have a dependence on `ReactiveSwift` 1.0.0, but `Moya` needs 2.0.0. Did you add `github "ReactiveCocoa/ReactiveSwift" "1.0.0"` for a reason?

**Comment by BasThomas** [comment]
I don't know why you get the error of the renamed `MoyaError` in the availability file. What Swift version are you using? And what version of Xcode?
