### ISSUE TITLE
How to add text as MultipartFormData like postman, or I have a wrong idea?

### ISSUE THREAD

**Issue by swordjoy** [Moya/Moya#1209]
moya version: ~> 8.0.3
this is postman:
![a477e398-f2b7-4e99-b841-cd204af5fffc](https://user-images.githubusercontent.com/17894304/29165275-c5012f22-7df4-11e7-817b-3fdeafea7362.png)
I want to add text as form-data like postman
This is way i use now, only image,no text.how to do? 
```swift
public var task: Task {
        switch self {
            case let .uploadImages(imageDatas, _):
            var mutDatas = [MultipartFormData]()
            for (index, value) in imageDatas.enumerated() {
                mutDatas.append(MultipartFormData(provider: .data(value), name: "images", fileName: "files\(index).jpeg", mimeType: "image/jpeg"))
            }
            return .upload(.multipart(mutDatas))
        case let .uploadHeadIconImage(imageData):
            var mutDatas = [MultipartFormData]()
            mutDatas.append(MultipartFormData(provider: .data(imageData), name: "file", fileName: "file\(index).jpeg", mimeType: "image/jpeg"))
            return .upload(.multipart(mutDatas))
        }
    }
```
or, there is a other way to get it?

**Comment by sunshinejr** [comment]
Hey @swordjoy. The code you posted is good for multipart uploading. If you want to add text to it, you should add it to the multipart data as well. For instance, if you wanted to add `width` parameter to the request, you would do:
```swift
mutDatas.append(MultipartFormData(provider: .data("100".data(using: .utf8)!), name: "width"))
```

Let me know if it resolves your issue or if you have some more questions around this topic :)

**Comment by swordjoy** [comment]
It work well, thanks!

**Comment by khuong291** [comment]
Thanks, it works for me 👍
