### ISSUE TITLE
Add Basic Auth Plugin

### ISSUE THREAD

**Issue by SD10** [Moya/Moya#1214]
### Add Basic Auth Plugin

As discussed in #1172, `AccessTokenAuthorizable` can be updated using an enum `AuthorizationType` with the cases `none`, `basic`, and `bearer` to determine the header value.

### TO DO:
- [x] Implementation
- [x] Testing
- [x] Update Documentation

**Comment by sunshinejr** [comment]
This can be closed and move any conversation to #1215 where is the implementation of this one.
