### ISSUE TITLE
RxSwift linked to 9.0.0-dev even if not needed

### ISSUE THREAD

**Issue by Dschee** [Moya/Moya#1217]
I'm using the most current commit of the 9.0.0-dev Branch and I'm not using any reactive libraries. Since updating the dependency from my own fork (commit 4bcac8144fd438b9b93c2a9907a8581dfd899278) to commit 0c25037dcf2a4213124fe0a423656b14ee0209d4 I'm seeing the following error when building:

```
dyld: Library not loaded: @rpath/RxSwift.framework/RxSwift
  Referenced from: /Users/JamitLabs/Library/Developer/CoreSimulator/Devices/98DE006C-DE6C-45D2-9A42-4440CFD6DA9C/data/Containers/Bundle/Application/F1A76703-C1FA-4236-AD1B-7167A09B72F6/TreasuryManager.app/Frameworks/Moya.framework/Moya
  Reason: image not found
```

I have not included the RxSwift library into my project, but I don't want to since I'm not using reactive Moya. The inclusion is done via the current Carthage version. I would expect that error to not appear so I don't have to include RxSwift like it always worked before.

**Comment by BasThomas** [comment]
Are you sure it worked before? I think there's no option to get an equivalent to the "subspecs" in CocoaPods, so you'd have to download everything. That should still not show the library not loaded error, though.

**Comment by Dschee** [comment]
I've just tested again. When I put `github "Moya/Moya" "9.0.0-dev"` into my Cartfile and run `carthage update` and build the app, I get the error. Once I replace it with `github "Moya/Moya" "4bcac8144fd438b9b93c2a9907a8581dfd899278"` (which is the commit right before #1212 and #1213 were merged) it works correctly.

**Comment by Dschee** [comment]
Maybe the new file `Single+Response.swift` is part of the Moya main target?

**Comment by BasThomas** [comment]
🤔, interesting. Check the PR (#1218) that was just opened.

**Comment by Dschee** [comment]
I checked, it works. Thanks @sunshinejr! 🎉

**Comment by sunshinejr** [comment]
No problem, thanks to you for testing 9.0.0-dev on Carthage so we have a feedback and we can fix bugs faster 🙇
