### ISSUE TITLE
Add an example of multipart upload with parameters.

### ISSUE THREAD

**Issue by sunshinejr** [Moya/Moya#1219]
There were a few issues regarding multipart upload with parameters and how to do it (e.g. #1209). I feel like this is a good time to add an example to our [docs/Examples](https://github.com/Moya/Moya/tree/master/docs) directory, especially having a new release in place. What I'm thinking about is a document with one (or more) examples, but the one we need for sure is an image upload with additional parameters.

Let me know if something is not clear 👍

**Comment by nhantrivinh** [comment]
Hi @sunshinejr, I happen to need an example of this quite badly. Is there any example out there that you've seen which can help?

If yes, that would be awesome!

**Comment by sunshinejr** [comment]
Hey @nhantrivinh! I can't remember if I saw a full example out there, so I'm gonna try to give it here. Basically you need to pass parameters only in `MultipartFormData` of a `task` property (if these aren't url parameters). 

For instance, if you want to pass gif data and `description` parameter, you would combine these like:

```swift
let gifData = MultipartFormData(provider: .data(data), name: "file", fileName: "gif.gif", mimeType: "image/gif")
let description = MultipartFormData(provider: .data("description of a gif".data(using: .utf8)!), name: "description")
let multipartData = [gifData, imageWidthData]
```

Now, you would just wrap it in the `task` property, like:
```swift
extension Giphy: TargetType {
    public var task: Task {
        switch self {
        case let .upload(data):
            let gifData = MultipartFormData(provider: .data(data), name: "file", fileName: "gif.gif", mimeType: "image/gif")
            let description = MultipartFormData(provider: .data("description of a gif".data(using: .utf8)!), name: "description")
            let multipartData = [gifData, imageWidthData]
            return .upload(.multipart(multipartData))
        }
    }
}

```

For Moya 9 the return type would be a little bit different (as the API is more verbose now):
```swift
return uploadMultipart(multipartData)
```

And that new API we would like to have in our docs. 

Hope it helps!

**Comment by sunshinejr** [comment]
This is covered by #1255.
