### ISSUE TITLE
Our release numbers are incompatible with the swift package manager

### ISSUE THREAD

**Issue by AndrewSB** [Moya/Moya#1221]
Quick heads up: the alpha & beta releases we're publishing aren't compatible with spm v3.

<img width="656" alt="screen shot 2017-08-15 at 10 07 30 am" src="https://user-images.githubusercontent.com/3814772/29326828-dca7cdd8-81a1-11e7-9268-36c2942c2379.png">

I'm going to figure out the correct format, post it here, and potentially re-release our 9.0 alpha with that format

**Comment by AndrewSB** [comment]
Looks like the `.1` at the end breaks the format.
This section in their documentation talks about how to format version numbers: https://github.com/apple/swift-package-manager/blob/master/Documentation/PackageDescriptionV3.md#version
It's of the sort `"major.minor.patch[-prereleaseIdentifiers][+buildMetadata]"`.

So we should publish 
1️⃣: `9.0.0-alpha1` or
2️⃣: `9.0.0-alpha+1`

What do @Moya/contributors think?

**Comment by sunshinejr** [comment]
Thanks for the finding, @AndrewSB. This is strange, though. From what I've known, `9.0.0-alpha.1` seems like a valid [semver](http://semver.org/#spec-item-9) release number. Also, from the [docs](https://github.com/apple/swift-package-manager/blob/master/Documentation/PackageDescriptionV3.md#version):
> NOTE: prereleaseIdentifiers are separated by dot (.).

Doesn't it mean that `alpha.1` should be valid? 🤔

**Comment by pedrovereza** [comment]
As @sunshinejr mentioned `9.0.0-alpha.1` is indeed a valid semver number. A bit weird that SPM can't handle it 🤔

**Comment by BasThomas** [comment]
Let's create an issue over at SPM and go with 🎉 for now?

**Comment by freak4pc** [comment]
Agree that 9.0.0-alpha1 makes sense in general, and if it solves this - even better. Wondering on why `alpha.1` doesn't budge, seems like it should... based on SEMVER. Seems like a pretty definite SPM bug.

**Comment by BasThomas** [comment]
@AndrewSB what environment did you run this in? Making a Swift bug atm.

**Comment by BasThomas** [comment]
https://bugs.swift.org/browse/SR-5693

**Comment by AndrewSB** [comment]
Yeah, this was really strange. I thought our `9.0.0-alpha.1` release was compatible with semver

here's my swift info @BasThomas:

```
👋  swift -v                                                                   ~
Apple Swift version 3.1 (swiftlang-802.0.53 clang-802.0.42)
Target: x86_64-apple-macosx10.9
/Library/Developer/CommandLineTools/usr/bin/lldb "--repl=-enable-objc-interop -sdk /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -color-diagnostics"
Welcome to Apple Swift version 3.1 (swiftlang-802.0.53 clang-802.0.42). Type :help for assistance.
```

lldb stuff might be unrelated, I'm currently working on a project related to lldb

**Comment by sunshinejr** [comment]
Oh, I think I found it (see this [SO answer](https://stackoverflow.com/a/28205895/2340462)). Seems like a git issue? Quickfix should be to deleting `9.0.0-alpha.1` branch. What do you guys think?

**Comment by freak4pc** [comment]
You can make a tag and nuke the branch to test this I think ? If you're wrapping up this release anyways it's worth a shot IMO @sunshinejr

**Comment by AndrewSB** [comment]
really nice catch @sunshinejr 😄 let's do it

**Comment by sunshinejr** [comment]
Branch deleted @AndrewSB, can you check if it works? 😄

**Comment by AndrewSB** [comment]
It doesn't work, but it looks like a different error

<img width="296" alt="screen shot 2017-08-15 at 4 00 36 pm" src="https://user-images.githubusercontent.com/3814772/29340279-fe3dc098-81d2-11e7-9b80-3482507446fe.png">

no complaints about the refname


this should be easily repro-able. My `Package.swift` is just
```swift
import PackageDescription

let package = Package(
	name: "<NAME>",
	dependencies: [
		.Package(url: "https://github.com/Moya/Moya.git", majorVersion: 9),
	],
	exclude: [
		"thrift",
	]
)
```

**Comment by sunshinejr** [comment]
@AndrewSB I think that prerelease won't get in the `major`/`minor` range (at least that was a thing when I used SPM last). You probably need to specify a version to get it working.

**Comment by freak4pc** [comment]
Yeah you're right @sunshinejr : https://github.com/apple/swift-package-manager/blob/master/Sources/PackageDescription/Version.swift#L23

I'll confirm on my end as well a bit later if @AndrewSB isn't back by then

**Comment by freak4pc** [comment]
@sunshinejr @AndrewSB  This seems to work just fine for installation but getting a different error, not sure if it's related to my dummy project or Moya: 

```swift
import PackageDescription

let package = Package(
	name: "Moya",
	dependencies: [
		.Package(url: "https://github.com/Moya/Moya.git", Version(9, 0, 0, prereleaseIdentifiers: ["alpha", "1"])),
	]
)
```

![76a03a6e-44e0-48d1-bc84-3b16c3e13289](https://user-images.githubusercontent.com/605076/29354095-1077e458-8275-11e7-8a94-daec8ecf6497.png)

**Comment by SD10** [comment]
@freak4pc The output from @AndrewSB is showing the same warning. I'm not sure if we had this warning in previous versions but it looks like it's from the `Supporting Files` group not having any `.swift` files. @sunshinejr Did we recently refactor this folder?

**Comment by freak4pc** [comment]
@SD10 It was an Edit so didn't see it ;) 

I think the problem is it treats every folder as a Module even though in this case this is shared code. Perhaps that folder could be excluded ? I guess it would break the build as well though 🤔

**Comment by sunshinejr** [comment]
@freak4pc @SD10 I think this is just a warning and we have this for quite some time now. The module should build, though. However, we can take care of it so I've created #1224 😉

**Comment by freak4pc** [comment]
So regarding this specific ticket there is no issue with versioning so we can just close here IMO? @sunshinejr

**Comment by sunshinejr** [comment]
I believe so! If there is a way of improving/fixing the error on SPM, that's on their side now I think. We can always reopen in case something happens. Thanks everyone for helping out! 👏

**Comment by BasThomas** [comment]
Should I update the SPM bug?

**Comment by sunshinejr** [comment]
It would be awesome. TL;DR we found the issue (having `tag` and `branch` with the same name, removing branch helped). If there is something SPM could do to fix the issue or improve error handling, it would be great 😉
