### ISSUE TITLE
Please add support swift4.

### ISSUE THREAD

**Issue by danwey** [Moya/Moya#1222]

**Comment by SD10** [comment]
@danwey We're working on it. Moya `9.0.0` will support Swift 4 and should be released soon.

**Comment by sunshinejr** [comment]
Hey @danwey. As @SD10 said we are working on it, in fact it is already done and is waiting for a release. In the meantime you have 2 workarounds (until we release next version of Moya):
1. You can use Swift 3.2 in Moya but 4.0 in your project (see more about it [here](https://github.com/Moya/Moya/issues/1189))
2. You can use our `9.0.0-dev` branch which should have Swift 4.0 support already, but bear in mind that it is our development branch and it is not the safest one (I would advise against using this one in production). 

Please let us know if you have some more questions around it :)

**Comment by danwey** [comment]
pod 'Moya/RxSwift' 
![8142ed46-50f2-46b4-b758-c5a629efb9d0](https://user-images.githubusercontent.com/6631373/29357841-8ed16d48-82ab-11e7-8f20-31197c7347cd.png)

**Comment by sunshinejr** [comment]
@danwey do you use `swift4.0` branch of `RxSwift` in your `Podfile`?

**Comment by danwey** [comment]
I won't specify the 'moya/rxswift' version.

**Comment by sunshinejr** [comment]
I'm not sure I understand you correctly, @danwey, but if you still want to use Swift 4.0 version of Moya and RxSwift, you should use our `9.0.0-dev` branch and RxSwift's `swift4.0` branch:
```rb
pod 'Moya/RxSwift', :git => 'https://github.com/Moya/Moya.git', :branch => '9.0.0-dev'
pod 'RxSwift', :git => 'https://github.com/ReactiveX/RxSwift.git', :branch => 'swift4.0'
```

Please keep in mind that these are both prerelease branches and might expect difficulties/bugs.

**Comment by danwey** [comment]
pod 'Moya/Moya', :git => 'https://github.com/Moya/Moya.git', :branch => '9.0.0-dev'
pod 'RxSwift', :git => 'https://github.com/ReactiveX/RxSwift.git', :branch => 'swift4.0'
Can do it.   ：）thank you.
