### ISSUE TITLE
[Tests] Add tests for Single+Response

### ISSUE THREAD

**Issue by sunshinejr** [Moya/Moya#1227]
Lately few of the operators, that have been added to `Observable<Response>`, have also been added to `Single<Response>` (see #1213). Unfortunately, tests for them weren't added yet. We shall fix this one ASAP!

I know you were up for doing these, @freak4pc, if it's still the case, please assign yourself 😉

**Comment by freak4pc** [comment]
I already have a branch for this :) 
PR coming soon.

**Comment by freak4pc** [comment]
PR Landed at #1229

**Comment by SD10** [comment]
Closing this in favor of moving the discussion to the implementation of #1229.
