### ISSUE TITLE
Update SPM.

### ISSUE THREAD

**Issue by BasThomas** [Moya/Moya#1240]
The [`Package.swift`](https://github.com/Moya/Moya/blob/9.0.0-dev/Package.swift) will need to update its [API](https://github.com/apple/swift-package-manager/blob/swift-4.0-branch/Documentation/PackageDescriptionV4.md). Changes to the Package should also be reflected in the Readme.

**Comment by sunshinejr** [comment]
Hey @BasThomas. Not sure, but does migrating to new SPM API means that we will drop Xcode 8/Swift 3.1 support? If yes, we probably need to postpone it to 10.0 release.

**Comment by SD10** [comment]
@sunshinejr I was just looking into this because I had to familiarize myself with the new API for danger-swift. It looks like it should be backwards compatible according to [this](https://swift.org/blog/swift-package-manager-manifest-api-redesign/).

**Comment by sunshinejr** [comment]
Hmm, it seems like we would have to specify `swift-tools-version:<specifier>`, which probably will be 4.0, and someone who is working on Xcode 8 could be missing Swift 4.0 tools. Also, I wasn't sure what is this `swift-tools-version` parameters, but swift.org got me covered:

> // The swift-tools-version declares the minimum version of Swift required to build this package.

**Comment by josefdolezal** [comment]
Is this issue back in the game with Moya v10?

**Comment by sunshinejr** [comment]
Yup, I think it its, @josefdolezal! PR should be up for grabs 😉

**Comment by sunshinejr** [comment]
That's actually fixed already, so I'm closing this one.
