### ISSUE TITLE
Update ReactiveSwift to 2.0 for Moya 8.0

### ISSUE THREAD

**Issue by larryonoff** [Moya/Moya#1245]
Hello Community,

I've already did this proposal, but for 8.0. So we agreed to do it for 9.0 and we already did it.

I suggest making this change for 8.* and make new Moya 8.* release. This's because 9.0 is in beta now. 

I'll make PR if no-one against it.

**Comment by BasThomas** [comment]
If it's a non breaking change, please go ahead and open a PR. :)

**Comment by larryonoff** [comment]
@BasThomas in some way it's. ReactiveSwift 2.0 has some breaking changes. This will require some changes for `Moya/ReactiveSwift` users.

**Comment by BasThomas** [comment]
In that case, we shouldn't add it to 8.0. We'd want to do a major version update for breaking changes. Why did you want to update ReactiveSwift for 8.0 as well?

**Comment by SD10** [comment]
How were we thinking of doing this? Dowloading the `8.0.5` release and updating it? `master` already represents 9.0.x betas

**Comment by larryonoff** [comment]
I have some issues on one of my projects. That fixed by updating to ReactiveSwift 2.0 and ReactiveCocoa 6.0 (that requires  ReactiveSwift 2.0).

**Comment by larryonoff** [comment]
We can do `Moya/ReactiveSwift2`, but it looks weird.

**Comment by larryonoff** [comment]
What about updating and in case of request for ReactiveSwift <2 we'll make some kind of `Moya/ReactiveSwift_1`.

**Comment by larryonoff** [comment]
It maybe easier for me to use Moya from master for now :)

**Comment by SD10** [comment]
@larryonoff Can you migrate to `Moya 9.0.0-beta.1`?

**Comment by larryonoff** [comment]
@SD10 this's what I'm thinking about now. Do you know if it has many issues?

**Comment by SD10** [comment]
@larryonoff No, nothing that I'm aware of and we have unit tests. If you did run into something it can always be resolved

**Comment by larryonoff** [comment]
Thank you all. I'll close the issue and will use 9.0 beta.

**Comment by sunshinejr** [comment]
Thanks, @larryonoff! If you find something strange in the newest beta don't hesitate to open an issue/PR so we can fix it before official release :)

**Comment by larryonoff** [comment]
@sunshinejr  sure!

**Comment by SD10** [comment]
@larryonoff I just want to let you know there's a [migration guide](https://github.com/Moya/Moya/blob/master/docs/MigrationGuides.md#upgrade-from-8x-to-9x). Feel free to let us know if the guide can be improved or is missing something from your migration
