### ISSUE TITLE
Add default `headers` implementation `TargetType `

### ISSUE THREAD

**Issue by larryonoff** [Moya/Moya#1246]
Hi all,

```swift
public protocol TargetType {
    var headers: [String: String]? { get }
}
```

This's a very good addition to the framework. But I think that `headers` customisation can be a rare case. So I suggest adding default implementation for this.

What others think about it?

**Comment by SD10** [comment]
@larryonoff I believe one of Moya's design philosophies is to ["favour explicitly-defined behaviour over default implementations."](https://github.com/Moya/Moya/blob/master/Vision.md). Therefore, we're trying to avoid default behaviors.

**Comment by larryonoff** [comment]
@SD10 hah! thanks!

I see that `sampleData` usually `Data()`...
