### ISSUE TITLE
Moya 9 Beta breaks parameters with all requests

### ISSUE THREAD

**Issue by Legoless** [Moya/Moya#1247]
Using Moya 9.0.0 Beta 1 version and since that, Moya will ignore and discard all parameters built in `TargetType` `task`. This is a breaking change, requiring to revert back to version 8.x.x, as it is useless for any API that requires parameters:

```
enum User {
    case register([String : Any])
    case ping
}

extension User : TargetType {
    var task: Task {
        switch self {
            case .register(let parameters):
                // All parameters here are ignored.
                return .requestParameters(parameters: parameters, encoding: JSONEncoding.default)
            default:
                return .requestPlain
        }
}
```

What is the solution for this? Exploring `MoyaProvider+Internal` shows that the only time Moya will call to `Task` type is at line 96:

```
switch target.task {
    case .requestPlain, .requestData, .requestParameters, .requestCompositeData, .requestCompositeParameters:
```

Since this task is a Swift Enum returning parameters, here they are completely ignored. I was unable to find any other code that would call to `.requestParameters` task type.

How to solve this?

**Comment by SD10** [comment]
@Legoless The parameters get applied inside of the provider's `requestClosure`. 
It is set to [`MoyaProvider.defaultRequestMapping`](https://github.com/Moya/Moya/blob/master/Sources/Moya/MoyaProvider%2BDefaults.swift) by default. 
It does this by calling the [`urlRequest`](https://github.com/Moya/Moya/blob/master/Sources/Moya/Endpoint.swift) property on `Endpoint`.

**Comment by Legoless** [comment]
I created the `Endpoint` manually, and apparently with old API, this was not required, but with new, default will always be `.requestPlain`. Might be a good idea to remove default parameter, since I just wasted 3 hours figuring this out, why it doesn't work. Since task is still called again from the internal code, it can quickly be confusing where this is applied. Issue can be closed. :) Sorry.

**Comment by sunshinejr** [comment]
@Legoless this is a great idea. In fact, I think we should remove all default parameters from `Endpoint.init` as all of them might get confusing. Would you be up for a PR maybe? :)

It will be a breaking change, but I think this is for a good cause.

**Comment by SD10** [comment]
I agree, let's remove them so no one else faces this issue. @Legoless Thanks for the feedback and sorry for the confusion!

**Comment by SD10** [comment]
@sunshinejr Do you think there's any value in making the `urlRequest` property throwing and then propagating the parameter encoding errors? Since `defaultRequestMapping` just converts a `URLRequest` to a `Result<URLRequest,Error>` we can pass on this information quite easily here. Just on my mind from looking at this part of the code.

**Comment by sunshinejr** [comment]
@SD10 seems like it would be quite helpful! If you have some free time to research this one I think it would be a great update of our error handling 👍

**Comment by SD10** [comment]
Closing this in favor of #1249

**Comment by cvhong** [comment]
Hi, I think I encountered similar problem when upgrade from 8 -> 11,  task never getting call when I  trying to debug.

```
// MyAPI_TargetType.swift
 public var task: Task {
        return .requestPlain
    }
```

```
// API_Provider.swift
var endPoint = Endpoint(url: url, sampleResponseClosure: {.networkResponse(200, target.sampleData)},
                                method: target.method, task: Task.requestParameters(parameters: target.parameters!,
                                                                                    encoding: target.parameterEncoding), httpHeaderFields: httpHeader)
```
