### ISSUE TITLE
Moya cancellable request consistently triggering Exception 6, Subcode 8

### ISSUE THREAD

**Issue by zallanx** [Moya/Moya#1250]
I am using Sentry for crash reporting, and one error that I have been consistently seeing is the following:

![image](https://user-images.githubusercontent.com/1867934/29931942-c4cb70d8-8e40-11e7-978a-08ce6870ca02.png)

Specifically, it always involves a cancellable Moya request. I was wondering if it has to do with my Moya requests not being cancelled properly.

Any suggestions are welcome. Thanks!

**Comment by sunshinejr** [comment]
Hey @zallanx, thanks for the issue and sorry for the wait. It just happened for another user so we should priority this one a little more. Would you be able to report your environment for this one? Moya version, Swift version, Reactive  extensions if any. Also the Moya setup if possible - especially setting up the provider.

**Comment by zallanx** [comment]
Hey @sunshinejr, thanks for following up.

I think what occurred was that, while a Moya request was running, the app crashed due to another unrelated issue. However, when viewing the trace (specifically, this was via Sentry), it was unable to capture the crash issue further down the trace stack, and therefore only indicated it was Moya.

Let me know if this is helpful. 

Moya is working great for me 👍
