### ISSUE TITLE
Is it possible to save or capture Moya responses into stub json ala VCR?

### ISSUE THREAD

**Issue by apollow** [Moya/Moya#1251]
I was wondering if there was a way to automatically capture json responses and put them into JSON. Is there an out of box solution or is one needed to be made?

**Comment by sunshinejr** [comment]
Hey @apollow. This is a good question. There is no out-of-the-box solution yet (but there is potential for a library). However, I did a demo some time ago to show how to easily save stubs and use them using Moya (and few more), [here](https://github.com/sunshinejr/FlexibleMoya/tree/master/FlexibleMoya). This one is kinda old (both Swift/Moya), so you would have to update the syntax, but the idea is there. 

Hope it helps!

**Comment by SD10** [comment]
Kind of similar to #197. I'm not sure if Moya should have a caching layer but maybe this could be extended through a plugin

**Comment by AndrewSB** [comment]
@SD10 I'm still pretty bullish on small single purpose libraries, and I think adding caching to Moya would add a lot of complexity and make it harder to reason about the state of program.

Ideal caching in my opinion would sit above Moya, maybe like

```swift
let networkProvider = RxMoya<ATarget>()
let diskProvider = SomeDiskProvider()

let cache = ACache(firstPrioritize: diskProvider, thenPrioritize: networkProvider)
```

**Comment by pietrocaselani** [comment]
I am using [Carlos](https://github.com/WeltN24/Carlos) to cache responses. There is an example of how to add Moya support in this [issue](https://github.com/WeltN24/Carlos/issues/167)
It's similar to Andrew's idea.

**Comment by SD10** [comment]
@AndrewSB I think I had similiar thoughts:

```Swift
let moyaProvider = MoyaProvider<SomeTarget>()
let cacheProvider = CacheProvider(provider: moyaProvider)

cacheProvider.request(.zen)
```
I think a cache at any level of a program increases its complexity/the difficulty to reason about its state. Having this hidden in Moya's internals could increase that difficulty but I believe this is true for any library you don't fully understand internally. 

My main concerns are:
- The maintainability of the codebase
- The quality of a caching feature (considering there are other projected devoted to this)
- We have to consider different types of persistence

Moya does one simple thing and it does it incredibly well. If a new feature doesn't match the quality of what we do already it's more clutter than anything useful IMO.

**Comment by AndrewSB** [comment]
@SD10: Other than making it more visible, what upside do you think there would be in building this cache over using Carlos?

**Comment by SD10** [comment]
@AndrewSB The only upside is Moya users getting these capabilities by default 🤔 I don't think we can maintain something as robust as Carlos.

**Comment by AndrewSB** [comment]
I think the capabilities are robust, complicated, and variable enough that we shouldn't prescribe a one-size-fits-all solution to everyone who uses Moya. 

I think those who care about caching should configure something that works for them -- whether that be a `URLCache`, something like `PINRemoteImage` just to cache images, or `Carlos` to cache some/all requests -- and all of their caching and expiration policies

**Comment by SD10** [comment]
@AndrewSB So it seems like we both agree this wouldn't be a valuable addition to Moya's core. Better to let other libraries build Moya plugins.
