### ISSUE TITLE
Migrate SubclassingProvider example to use composition instead of subclassing.

### ISSUE THREAD

**Issue by sunshinejr** [Moya/Moya#1258]
This one should be done after #1256 is merged. Look at this [file](https://github.com/Moya/Moya/blob/cd25d627571968e9c79fbddd7e87db51b9876bba/docs/Examples/SubclassingProvider.md). This one was written before Moya 9.0.0 and before we deprecated reactive providers. It was also based on Eidolon's stack, which @ashfurrow already migrated to `9.0.0-alpha.1` version, but we changed few things in `beta.1` so it would need some work anyways. Current Eidolon's almost ready version is [here](https://github.com/artsy/eidolon/blob/de2a3f2987cc83cb213dbc7bd371c14f65660ead/Kiosk/App/Networking/Networking.swift).

**Comment by pietrocaselani** [comment]
I will work on this!

**Comment by sunshinejr** [comment]
Awesome! Keep us updated :)

**Comment by pietrocaselani** [comment]
PR is open. Let me know if there is any problems.
