### ISSUE TITLE
Formalize Changelog.

### ISSUE THREAD

**Issue by sunshinejr** [Moya/Moya#1260]
So we have few "unwritten rules" we do in our Changelog. Unfortunately, that's not always the case. Also, some of these "rules" were forgotten and, I think, were valuable enough to bring them back. So I suggest to:

1. Group changes to describe their impact on the project, as follows:
    - **Added** for new features.
    - **Changed** for changes in existing functionality.
    - **Deprecated** for once-stable features removed in upcoming releases.
    - **Removed** for deprecated features removed in this release.
    - **Fixed** for any bug fixes.
1. Add a GitHub tag to each Changelog entry.
1. Add a PR number with a change.
1. Put **Breaking change** label in breaking changes entry and put them first in the list.

Examples:
- **Breaking Change** Removed parameters & parameterEncoding in `TargetType` (#1147) - @Dschee.
- Added tests for `Single<Response>` operators (#1229) - @freak4pc.

There is also a question of what do we need in Changelog? Should this be only something visible to API users? Or maybe we should also add bigger notes of a development process like tests or refactorings?

Would love to know what do you think about it, @Moya/contributors!

**Comment by SD10** [comment]
@sunshinejr I started using GitHub tags + PR numbers at IBAnimatable and think it would be a great idea to formalize the same approach for Moya. Knowing the PR where the changes were made and who made them help a great deal with visibility and accountability. If I ship a regression (or have any questions about a change) you know where to find me 😃

Do you think we should also create a documentation file that describes our CHANGELOG process for new contributors?

**Comment by orta** [comment]
If you're thinking of adding the full process - consider using http://keepachangelog.com/ or using the standard in the JS world: https://github.com/semantic-release/semantic-release#default-commit-message-format

**Comment by sunshinejr** [comment]
Thanks for the links, @orta! Yeah, seems like we could adopt http://keepachangelog.com/ fully (I actually copied some of the rules from that website 😄). Additionally, I would really like to use both PR number and GitHub tag in the entry (which I've not seen on that website). 

I'm also thinking if/how should we document that one. Maybe in our [contributors repo](https://github.com/Moya/contributors)? 🤔

**Comment by sunshinejr** [comment]
Does anyone else have any opinion on that one, @Moya/contributors?

**Comment by ashfurrow** [comment]
More is more 😄

**Comment by sunshinejr** [comment]
Alright, I've made a PR so we can discuss the details further there - see [Moya/contributors#16](https://github.com/Moya/contributors/pull/16). Closing this one for now!
