### ISSUE TITLE
Does authorizationType require a switch self?

### ISSUE THREAD

**Issue by arjunnaha** [Moya/Moya#1261]
I'm using the brand new 9.0.0 - thanks!

Using the example code from here: 

> https://github.com/Moya/Moya/blob/master/docs/Authentication.md
> ```swift
>     var authorizationType: AuthorizationType {
>     case targetThatNeedsBearerAuth:
>         return .bearer
>     case targetThatNeedsBasicAuth:
>         return .basic
>     case targetDoesNotNeedAuth:
>         return .none   
>     }
> ```

Does the authorizationType var need a `switch self ` and a period in front of the case like so:

```swift
    var authorizationType: AuthorizationType {
        switch self {
        case .targetThatNeedsBearerAuth:
            return .bearer
        case .targetThatNeedsBasicAuth:
            return .basic
        case .targetDoesNotNeedAuth:
            return .none
        }
    }
```

As I am otherwise getting an error that a `'case' label can only appear inside a 'switch' statement`.

**Comment by BasThomas** [comment]
Yes, it does. Only if all paths have the same `AuthorizationType`, you could return immediately.

**Comment by sunshinejr** [comment]
Oh, seems like we have a missing `switch` in the documentation, nice catch @arjunnaha! Would you be up for fixing that one in a PR? 😄

**Comment by arjunnaha** [comment]
This is exactly what I am doing, as all my endpoints use .basic. Does that mean I can just use:

```swift
    var authorizationType: AuthorizationType {
        return .basic
    }
```

@sunshinejr Sure can do!

**Comment by SD10** [comment]
Doh 😅 Sorry @arjunnaha can't believe I missed that. Thank you!!

**Comment by sunshinejr** [comment]
Oh, and to answer the question, @arjunnaha: yes, you can just return `.basic` if you are using Basic everywhere, no need for a switch then 👍

**Comment by BasThomas** [comment]
@arjunnaha be aware the compiler won't warn you when adding a new endpoint that might using something other than `.basic` though!
