### ISSUE TITLE
What happened to mapArray and MapObject

### ISSUE THREAD

**Issue by YanisSOTO** [Moya/Moya#1263]
Hello, i've updated Moya to 9.0.0 today and i got some issues with mapArray() and mapObject() who doesn't exist anymore. I found nowhere some replacement of it.

     public static func getBattleRanking(userID: String, companyID: String) -> Observable<[RBattleResult]> {
        return RNetwork.provider
            .request(RService.getLeagueRankings(user_id: userID, company_id: companyID))
            .mapObjet(RBattleResult.self)
    }

Thank's for you help !

**Comment by SD10** [comment]
Hey @YanisSOTO,
This isn't a part of the Moya core library. You're using **Moya-ModelMapper**, correct?
You can check the [CHANGELOG](https://github.com/sunshinejr/Moya-ModelMapper/blob/master/Changelog.md#500-beta1) for the library. 

It looks like `mapObject` and `mapArray` have been renamed to `map(to:keyPath:)`

**Comment by YanisSOTO** [comment]
Hello @SD10 , thank's for your answer ! I'm not using ModelMapper, but this is coming from **Freddy**. So i'll refer to it. Sorry and thank's again. :)
