### ISSUE TITLE
[Question] How can one cancel a RxMoya request

### ISSUE THREAD

**Issue by alfian0** [Moya/Moya#1268]
Hi, I am new in moya. I am still dont understand about disposable. I heard to cancel RXMoya request we need to dispose but I still confusing how to dispose the observable. Can anyone give me a sample to handle this proble ??

**Comment by AndrewSB** [comment]
```swift
var disposeBag = DisposeBag()
provider.rx.request(.zen).mapString().subscribe(onSuccess: { json in
    print(zen) // this will never get called because we dispose
}) { error in
    print(error)
}.disposed(by: disposeBag)

disposeBag = nil
```

so here, the request will be started, but the subscription will never print, since we dispose (set to nil) the disposeBag before the request can return.

If you're interested in the implementation, when the disposeBag is set to nil, [code here in RxMoya](https://github.com/Moya/Moya/blob/master/Sources/RxMoya/MoyaProvider%2BRx.swift#L41) gets called that cancels the request using Alamofire.

Is there anything else we can shine the light on for you

**Comment by alfian0** [comment]
@AndrewSB thanks for solution, but when I set disposeBag to nil, I got error 

> Nil cannot be assigned to type 'DisposeBag'

I change
`disposeBag = nil`
to
`disposeBag = DisposeBag()`

and now it working, thanks

**Comment by AndrewSB** [comment]
Ahh, my fault. The swift type system probably inferred `disposeBag` to not be an optional. Change the first line to 

```swift
var disposeBag: DisposeBag? = DisposeBag()
```

and you should be fine

**Comment by alfian0** [comment]
**UPDATE**
we can use `.takeUntil(rx.methodInvoked(#selector(viewWillDisappear(_:))))` to handle disposable :)

**Comment by RowanG1** [comment]
> Ahh, my fault. The swift type system probably inferred `disposeBag` to not be an optional. Change the first line to
> 
> ```swift
> var disposeBag: DisposeBag? = DisposeBag()
> ```
> 
> and you should be fine
> 
> Happy you got it to work 😄

But if optional, you can't say .disposed(by: disposeBag), because it requires an unwrapped variable. If you force unwrap, and set disposebag nil later before request ends, the code crashes at point of .disposed(by: disposeBag!)

**Comment by RowanG1** [comment]
> .takeUntil(rx.methodInvoked(#selector(viewWillDisappear(_:))))

I can't add a takeuntil anywhere? Please show specific basic code in place with MoyaRequest?

**Comment by AndrewSB** [comment]
I believe it's unrelated to a `DisposeBag`. instead of adding the disposable from the request to a dispose bag, you can `.request(...).subscribe(...).takeUntil(rx.methodInvoked(#selector(viewWillDisappear(_:)))` and it sounds like @alfian0 has tested to see that it works
