### ISSUE TITLE
How to chain two network calls in Moya?

### ISSUE THREAD

**Issue by AAAstorga** [Moya/Moya#1270]
I am using Moya with good ol swift. How does one properly chain two network calls in Moya with different URLs? Say I go to url A and fetch a json. In the json there is a pictureURL, and I want to fetch that picture. so I need to make the call to the pictureURL. How does one accomplish this?

I followed this [guide](https://medium.com/@vsemenchenko/writing-network-layer-with-moya-for-swift-3aa039a6e693) when setting up my networking layers in my app.

I'd appreciate the help!

**Comment by AndrewSB** [comment]
I'd recommend creating a second MoyaProvider which provides photos, and then calling the passing in the ID of the photo (needed to make the URL) into a call after you get it from the first request.

That is assuming some knowledge of the pictureURL though. If you don't have that we'd have to go another route.


Also, I use a library called PINRemoteImage so I don't need to worry about the request of the image. If you're just planning to display it in a view, I'd recommend not worrying about the second request by giving that responsibility to another library
