### ISSUE TITLE
MoyaError Code=4 "The network connection was lost."

### ISSUE THREAD

**Issue by ICCanche** [Moya/Moya#1271]
I have an Moya configuration like this:

```swift
enum PromotionAPI {
    case fetchDailyPromos(param:String, param2: Double)
}

extension PromotionAPI : TargetType {
    var baseURL: URL { return URL(string: "https://myurlapi.com"}
    
    var path: String {
        switch self {
        case .fetchDailyPromos:
            return "api/promos"
        }
    }
    
    var method: Moya.Method {
        switch self {
            case .fetchDailyPromos: return .get
        }
    }
    
    var parameters: [String : Any]? {
        switch self {
        case .fetchDailyPromos(param: let param, param2: let param2) :
            
           return  ["param1":param, "param2": param2]
   
        }
    }
    
    var parameterEncoding: ParameterEncoding {
        switch self {
        case .fetchDailyPromos: return JSONEncoding.default
        }
    }
    
    var sampleData: Data {
        switch self {
        case .fetchDailyPromos: return Data()
        }
    }
    
    var task: Task {
        return .request
    }
    
    
}


```

When I call the request like this:

```swift
 provider.request(.fetchDailyPromos(param: let param, param2: let param2)) { result in 
       print(result)
})
```

I get this error:

> Error Domain=Moya.MoyaError Code=4 "The network connection was lost."

Result print:

> .failure(underlying(Error Domain=NSURLErrorDomain Code=-1005 "The network connection was lost." UserInfo={NSUnderlyingError=0x170240cc0 {Error Domain=kCFErrorDomainCFNetwork Code=-1005 "(null)" UserInfo={_kCFStreamErrorCodeKey=-4, _kCFStreamErrorDomainKey=4}}, NSErrorFailingURLStringKey=https://myurlapi.com/api/promos, NSErrorFailingURLKey=https://myurlapi.com/api/promos, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-4, NSLocalizedDescription=The network connection was lost.}))

I've test the API resource with Postman everything works fine, I'm not sure where the issue comes from.

**Comment by linbx08** [comment]
hi, This is a breaking change Moya 9.0.0 default parameters from Endpoint will be removed. 

`https://github.com/Moya/Moya/issues/1247`hope can help you

**Comment by ICCanche** [comment]
Thanks for answering, I'm using version 8.0.3

**Comment by sunshinejr** [comment]
I think this can be closed, but if you still have any questions about this one @ICCanche, let us know!
