### ISSUE TITLE
Moya error domain in docs

### ISSUE THREAD

**Issue by arjunnaha** [Moya/Moya#1272]
Just wanted to check something before making a PR. In the docs at the bottom of this page: https://github.com/Moya/Moya/blob/master/docs/RxSwift.md, it states that the Moya error domain is `MoyaErrorDomain` however when you trigger an error the actual domain is `Moya.MoyaError`.

**Comment by pedrovereza** [comment]
You're correct. Seems like we forgot to update the docs after #508 😅

**Comment by SD10** [comment]
@arjunnaha Thanks for the report! Do you want to submit a PR to take care of this? 😃

**Comment by arjunnaha** [comment]
Sure! I'll try and get that PR done today.

**Comment by arjunnaha** [comment]
Would someone be able to merge at #1274.

Cheers.
