### ISSUE TITLE
How to use Moya with access token as url parameter?

### ISSUE THREAD

**Issue by dotprox** [Moya/Moya#1273]
Hello

I have the following format for a url to access data: 
```
https://api.sitename.com/method.name/?someparameter=somedata&access_token=token
```

How to use Moya with this token type?

**Comment by BasThomas** [comment]
You can just add the `access_token` in the parameters.

**Comment by dotprox** [comment]
Hello @BasThomas, thank you for your answer. Is it good idea pass token each service method? I mean, here is authentication plugin, can we modernise it for different token types?

**Comment by BasThomas** [comment]
With the access token being a parameter, I think the best solution would be to add it via `parameters`; in this case the access token is not really different from any other parameter.

But it *is* a parameter that needs to be added to every request, so you might want to look into adding it to the Authentication Plugin, yes. Do you want to take a stab at implementing that?

**Comment by dotprox** [comment]
@BasThomas thanks for the suggestion, I will try! 🙂

**Comment by sunshinejr** [comment]
I'm closing this one in favor of #1283 as we discuss the issue further there.
