### ISSUE TITLE
How exactly do parameters and tasks work in Moya 9?

### ISSUE THREAD

**Issue by damianesteban** [Moya/Moya#1276]
Hello. I've been using Moya since early on and really love the project. I started to upgrade our application to Moya 9.0 yesterday and the configuration of parameters and tasks is confusing.

Example (other boilerplate omitted for brevity):

```
enum MyApi {
    case createUser(id: Int, name: String, email: String)
    //......
}

extension MyApi: TargetType {
    //.....
    var parameters: [String : Any]? {
        switch self {
        case .createUser(let id, let name, let email):
            return ["id": id, "name": name, "email": email]
        }
     // .....
    }

    var method: Moya.Method {
        return .post
   }
  // ....
```
With Moya 8.0, as long as `MyApi` conformed to `TargetType` and was properly configured I would be able to make a `POST` request to the `createUser` target. Under Moya 9.0, I must add the following, otherwise the parameters are sent along with the request:

```
var task: Task {
  switch self {
    case .createUser(let id, let name, let email):
      return .requestParameters(parameters:  ["id": id, "name": name, "email": email], encoding: URLEncoding.default)
     //....
     }
}
```

Surely I do not need to add the parameters twice in the `TargetType`, do I?

Thank you.

**Comment by SD10** [comment]
@damianesteban No, you do not need to add the parameters using the `parameters` property of `TargetType` in Moya `9.0`. Basically, `parameters` and `task` has been combined into a single property. You might want to check the [Migration Guide](https://github.com/Moya/Moya/blob/master/docs/MigrationGuides.md) (sorry if you've done so already)

**Comment by damianesteban** [comment]
Not quite sure how I missed this :). Thanks!

**Comment by SD10** [comment]
Maybe it would be useful to provide a deprecated warning for the `parameters` property. @BasThomas What do you think? Currently, if a Moya user doesn't remove the old `parameters` property it just results in it being unused. Thank you @damianesteban

**Comment by damianesteban** [comment]
I think that's a good idea. In fact, I would be happy to work on that.

**Comment by BasThomas** [comment]
Yes - that'd be awesome. Want to open a PR, @damianesteban? Let me know if you need any help.

**Comment by damianesteban** [comment]
Yes I will. Thanks.

**Comment by pccole** [comment]
@SD10 Was the Migration Guide removed? I just inherited a project that was using Moya 8.0, I've updated to 11 and I do not see the parameters computed property being hit.

Any help?

Thanks!

**Comment by SD10** [comment]
@pccole You can find all our migration guides under `docs/MigrationGuides`. I would recommend going through each one from your previous Moya version to the latest to get a feel for all the changes.  As mentioned above, we removed the `parameters` property in Moya 9.0 in favor of combining it with the `Task` enum.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
