### ISSUE TITLE
Stub Responses and Validation

### ISSUE THREAD

**Issue by xaverlohmueller** [Moya/Moya#1277]
I'm trying to stub requests as described in https://github.com/Moya/Moya/blob/master/docs/Endpoints.md:

```swift
let endpointClosure = { (target: MyTarget) -> Endpoint<MyTarget> in
    let url = URL(target: target).absoluteString
    return Endpoint(url: url, sampleResponseClosure: {.networkResponse(200, target.sampleData)}, method: target.method, task: target.task)
}
```

This works fine for stubbing response status codes and sample data. All of my `TargetType`s, however, take advantage of the `validate` feature and don't check status codes when making requests.
As a result, if I stub a response using status code `500`, my request will be considered a success.

Is there any way to run the built-in Moya validation against stubbed responses?

I'm using Moya `9.0.0`.

**Comment by damianesteban** [comment]
I usually make a separate endpointClosure for testing errors, i.e.:

```
let failingEndpointClosure = { (target: MyTarget) -> Endpoint<MyTarget> in
    let url = URL(target: target).absoluteString
    return Endpoint(url: url, sampleResponseClosure: {.networkResponse(500, sampleErrorData)}, 
    method: target.method, task: target.task)
}
```

**Comment by xaverlohmueller** [comment]
Yes, but it'll still be presented as a `.success` case in the `MoyaProvider.request()` completion handler.
If my `TargetType` has validation enabled, a real network request with status code `500` will hit the `failure` case.

I guess I'll just duplicate the status code validation in my `endpointClosure`...
