### ISSUE TITLE
How to run Moya Demo

### ISSUE THREAD

**Issue by mac10688** [Moya/Moya#1278]
I just cloned the project.

I cd'd into Demo folder.

ran the command
```
pod repo update
````

It updated some things.

I typed in

```
pod install
```

It seemed to install with no issues.

I go to build the project and I get the error.

No such module 'Moya' GitHubUserContentAPI.swift

I go to that file and see there is a red flag on line #2

```swift
import Moya
```

I'm new to swift so maybe there's something obvious I'm missing. But how do I get rid of this error so I can run the Demo project?

**Comment by mac10688** [comment]
I saw in the podfile that Moya is targeted with path to the parent directory. I opened that project and got it to build but still no luck with the Demo project.

**Comment by BasThomas** [comment]
Hey @mac10688. What did you change? What version of Moya and Xcode are you using? I've just tried installing Moya 9.0.0 with Xcode 8.3.3, and doing a `pod repo update` and `pod install` in the Demo directory worked fine.

**Comment by mac10688** [comment]
i'm using master version of Moya and xcode 8.3.3. I'll blow away the solution and try again

**Comment by mac10688** [comment]
I think I know. I opened xcodeproj, instead of xcworkspace. I remember going over that learning pods but I switched to carthage. I'm still new and I overlooked that. Thanks for replying!

**Comment by maross** [comment]
I still have problems to run Moya examples, now Demo folder is changed to Examples, but there is no Podifile. Can someone help me? Thanks

**Comment by sunshinejr** [comment]
Hey @maross. You'll need to build Carthage modules now. Basically you can go into the directory in terminal and run:
```
carthage update --platform iOS
```

We will need to update our docs to reflect the changes we did in latest version, though. Would you be up for the PR, @maross?

**Comment by BasThomas** [comment]
@sunshinejr would it be possible to enable the `Demo`s to be run with a Podfile too?

**Comment by sunshinejr** [comment]
Not sure because CocoaPods creates its own workspace etc. Right now we are doing it with Carthage, but we might want to switch to SPM once we get `swift test` done (also Harvey working copy).
