### ISSUE TITLE
Send only a String value as a parameter

### ISSUE THREAD

**Issue by uditha2233** [Moya/Moya#1281]
I have an API function which accepts only a string as a parameter. So I can't send parameters as `[String: Any]?` dictionary. Currently I am using Alamofire as below to  send only a string to the API.

```swift
        Alamofire.request(endPoint, method: .post, parameters: [:], encoding: param, headers: headers).response { response in
   
            print("Request: \(String(describing: response.request))")
            print("Response: \(String(describing: response.response))")
            print("Error: \(String(describing: response.error))")
            
            if let nonce = response.response?.allHeaderFields["nonce"] as? String {
                
                self.nonce = nonce
            }
            
            if let data = response.data, let utf8Text = String(data: data, encoding: .utf8) {
                
                let data = ("\(utf8Text)")
                completion(data)
            }
        }
```
 I have to do this using Moya now. But I can't figure out how to do this. I've tried it like below 

```swift
let endpointClosure = { (target: NetworkService) -> Endpoint<NetworkService> in
            return Endpoint<NetworkService>(url: "sampleUrl", sampleResponseClosure: {.networkResponse(200, target.sampleData)}, method: target.method, parameters: [:], parameterEncoding: param, httpHeaderFields: headers)
        }
```

But this is not working. Could I know how to pass only a string value using Moya.

**Comment by BasThomas** [comment]
Hi @uditha2233! Can you show some more of your code? For example your `endPoint`, `param` and `headers` parameters.

Other than that, a parameter should **always** be a key-value pair. Can you give us an example URL of what you are trying to achieve?

**Comment by uditha2233** [comment]
Hi @BasThomas The `endpoint` is the url of the API function and the `param` is just a string value.
`param =  encriptedKey + "." + encriptedData`. And the headers are like below 

```
  let headers: HTTPHeaders = [
            "nonce": iv,
            "alg": "2"
        ]
```

I need to send this `param` string to the API. But I can't send this `param` as a key-value pair because the API function doesn't accept any key-value pairs. It needs only a single string value. 
So my requirement is to send a value to the API without a key. Sorry for my bad English. But I hope you understand my question.

**Comment by AndrewSB** [comment]
Hey @uditha2233, apologies for the inactivity here. If you're still using that design on your server, you'll probably want to implement an [`endpointClosure`](https://github.com/Moya/Moya/blob/master/docs/Endpoints.md#from-target-to-endpoint) and add your string in there

Let us know if we can help in any other way 😄

**Comment by uditha2233** [comment]
Hi @AndrewSB , I have solved my issue. Thanks for your support. :)
