### ISSUE TITLE
Question about the Moya Pattern with Large API

### ISSUE THREAD

**Issue by matthewweldon** [Moya/Moya#1282]
I was wondering how a Moya TargetType should be structured to support a large list (30+) of endpoint cases. On my current project there are many API calls in the TargetType related to Registration, Login, get[Data], set[Data].  It it seems like it makes sense to put them in the single TargetType enum because many of the params are shared such as sessionToken, location, locale, which are required by the API.

When the TargetType has this many cases to handle it starts to feel unwieldy; keeping track of all the enums, making sure that the var/cases are exhaustive, keeping them alphabetical/consistent with the order in the original Enum declaration.

Admittedly these are minor headaches, but I thought maybe I'm misunderstanding the pattern. 

Should I be using more TagetType enums and separating them by type? Like RegisterProvider, LoginProvider, Data1Provider, etc., even if they share the same baseURL, encodings, session and other characteristics ?

**Comment by SD10** [comment]
@matthewweldon I would encourage you to separate your `TargetType`s as much as possible while still maximizing code reuse. Can I ask is all of this shared info across the targets stored in `associated values` of the enum? If it's not you could consider creating a `protocol` that sits a level above your individual `TargetType`s and provides this information.

**Comment by matthewweldon** [comment]
@SD10 Yes, I added associated values for things like session, location, locale. So when I'm building a parameter dictionary I can grab them as needed.

A protocol would still have tons of code reuse, no? Implementing that protocol on each targetType means I will be putting some get code in each targetType that could be stored in a single place instead. 

I currently have a sessionManager instance and a location manager instance outside of the targetType, the associated values call those singletons to get things like sessionToken or currentLocation. This is so that I can avoid having things like NSLocation, and NSUserDefaults code in my TargetType, which is a relatively a clean API reference.

I could make a struct for the parameters and shared associated values. My TargetTypes will then use that SharedParameter struct. Seemed like an extra layer.

I've attached a reduced version of my targetType definition so you can see what my current structure is.

![screen shot 2017-09-13 at 2 57 39 pm](https://user-images.githubusercontent.com/1388193/30395376-f0d0f7e0-9893-11e7-8481-f023db7b2fd4.png)

**Comment by SD10** [comment]
@matthewweldon I was asking about the associated values is that those can't be shared via a protocol, but your "Parameter vars" section looks like something that could be nicely extracted into a protocol that sits above your `TargetType`.

**Comment by matthewweldon** [comment]
Gotcha, thanks, I will tinker.
