### ISSUE TITLE
Switching on a RxSwift Moya error

### ISSUE THREAD

**Issue by arjunnaha** [Moya/Moya#1284]
Hey!

I've passed down a Moya error from the view model to the view controller below. When I try to switch on the error using the example code from here, https://github.com/Moya/Moya/blob/master/docs/Examples/ErrorTypes.md, I get the error:

> Pattern cannot match values of type 'Error'

```swift
viewModel.authStatus
    .debug("VC")
    .subscribe(onError: { error in
        
        switch error {
        case .statusCode: // Error occurs on this line
            print("statusCode")
        }
    
    }, onCompleted: {
        // Completed
    })
    .addDisposableTo(disposeBag)
```

It seems that the compiler is not interpreting that this is a MoyaError rather than a regular Error. Any ideas on how I can solve this? 😄

Thanks.

**Comment by SD10** [comment]
@arjunnaha Can you cast the `error` to a `MoyaError`?

**Comment by arjunnaha** [comment]
I've done this:

```swift
switch error as! MoyaError {
 case .statusCode:
    print("statusCode")
}
```
 but getting the error `Use of undeclared type 'MoyaError'`. Am I casting it correctly?

**Comment by SD10** [comment]
Do you have `Moya` imported? 😅 I'm rusty on my RxSwift

**Comment by arjunnaha** [comment]
That might have been why!! Thanks.
