### ISSUE TITLE
[CI] Don't run for documentation-only changes.

### ISSUE THREAD

**Issue by sunshinejr** [Moya/Moya#1286]
I found [an example](https://github.com/facebook/react/pull/2000/files#diff-354f30a63fb0907d4ad57269548329e3), but unfortunately it's for Travis so this is in `.travis.yml` config. We would have to migrate it to either Rakefile/Circle config or maybe even a new script.

As always, please assign yourself if you are working on it so we won't duplicate our work ✌️

**Comment by Sherlouk** [comment]
Assign this one to me, gives me an excuse to look into Circle 😅

**Comment by sunshinejr** [comment]
Sure thing, thanks @Sherlouk!

**Comment by SD10** [comment]
Yeah, there's an issue requesting that feature [here](https://github.com/isaacs/github/issues/100). It's been 4 years already so I don't think it's coming anytime soon 😭 I really want it though

**Comment by yeskunall** [comment]
I found [this](https://circleci.com/blog/circleci-hacks-automate-the-decision-to-skip-builds-using-a-git-hook/) article that shows how to skip CI builds if changes are in a certain directory by combining git hooks with a `.ciignore` (or any name) file. The only problem is that git hooks are local and are not copied over when a repo is cloned or forked, so I've hit a dead-end there 😓

I'm still looking for a way to achieve this in CircleCI tho 😅

**Comment by sunshinejr** [comment]
@yeskunall you can check #1339 as there should be a working script that does that.
