### ISSUE TITLE
Way to get some metrics for network requests to realize Circuit Breaker pattern

### ISSUE THREAD

**Issue by mrsnow-git** [Moya/Moya#1288]
I need a way to get some interesting network metrics while using Moya. Something like in URLSessionTaskMetrics or Alamofire response.timeline. 

Simple needs is to get Network Reachability status. More interesting to make some realization of Circuit Breaker pattern. Get information about latency, request timeline, redirect hops, network response time, errors.

I know some of it can be done using Moya Plugin. Is where any other useful ways I  didn't see?

**Comment by AndrewSB** [comment]
Moya is probably a level of abstraction too high to get metrics like that. Can you explain how you want to use the circuit breaker pattern? Is it with all of your requests, or just one endpoint?

**Comment by shannonchou** [comment]
@mrsnow-git  You can get URLSessionTaskMetrics like this:  https://github.com/Moya/Moya/issues/2073#issuecomment-737126499
