### ISSUE TITLE
Omit Target parameters

### ISSUE THREAD

**Issue by armandsLa** [Moya/Moya#1297]
Is there a way to omit Target parameters? Default arguments are not permitted in tuple types, which allows this type of functionality with functions.
This would become extremely handy when used with PATCH requests.

If default arguments would be permitted, it would look something like this:
```swift
public enum SomeAPI {
    case userEdit(name: String? = nil, surname: String? = nil, email: String? = nil)
}
```

This would allow to update(PATH) only changed values:
```swift
Provider.request(. userEdit(surname: "Smith")) { result in
    ...
}
```

Is there a way to achieve this?

**Comment by BasThomas** [comment]
That's not supported by Swift, unfortunately. It seems you *can* do it by adding an `init` to your enum, maybe that's an option? https://stackoverflow.com/questions/34456531/optional-parameter-in-enum-case-in-swift

**Comment by BasThomas** [comment]
That would enable something like this, but I feel it will make readability worse.

```swift
enum Network {
    case userEdit(name: String?, surname: String?, email: String?)
    case search(query: String)
}

extension Network {
    init?(name: String? = nil, surname: String? = nil, email: String? = nil) {
        guard name != nil || surname != nil || email != nil else { return nil }
        self = .userEdit(name: name, surname: surname, email: email)
    }
}

Network.userEdit(name: nil, surname: nil, email: nil) // userEdit(name: nil, surname: nil, email: nil)
Network.search(query: "test") // search("test")
Network(name: "test") // userEdit(name: Optional("test"), surname: nil, email: nil)
```
