### ISSUE TITLE
How to use CredentialsPlugin for specific target endpoint ?

### ISSUE THREAD

**Issue by dehlen** [Moya/Moya#1298]
**Moya Version:** 9.0.0

Hello,

i saw the example in the Authentication docs to use the CredentialsPlugin in order to authenticate a specific request with a basic auth header.

I have an enum conforming to TargetType with a case:
```swift
public enum APIService: TargetType {
    case createUser(user: User)
    case loginUser(user: User)
```

Now i want to add a CredentialsPlugin to my provider, but the provider should only send the authentication header when requesting the .loginUser endpoint. Thats why i was trying to switch over the target the credentialsPlugin is providing in the closure. Unfortunately i am getting this error message: 
```
Pattern cannot match values of type 'TargetType'
```

Here is my setup for the CredentialsPlugin:
```swift
CredentialsPlugin { target -> URLCredential? in
    switch target {
    case .loginUser(let user):
        return URLCredential(user: user.email, password: user.password, persistence: .none)
    default:
        return nil
    }
}
```

I am not quite sure what I am doing wrong. Any hint for me would be much appreciated.

Thanks,
David

**Comment by dehlen** [comment]
Nevermind i just got it working ...

```swift
CredentialsPlugin {
            switch $0 {
            case APIService.loginUser(let user):
                return URLCredential(user: user.username, password: user.password, persistence: .none)
            default:
                return nil
            }
        }
```

**Comment by dehlen** [comment]
Need to reopen this issue. I just discovered that the authorization header is not sended. Any idea why this is the case ? NetworkLoggingPlugin reveals the following:

```
Moya_Logger: [20/09/2017 15:12:20] Request: http://localhost:9000/auth
Moya_Logger: [20/09/2017 15:12:20] Request Headers: ["Content-Type": "application/json"]
Moya_Logger: [20/09/2017 15:12:20] HTTP Request Method: POST
```

**Comment by nmccann** [comment]
@dehlen I ran into a similar issue. The problem is that the URLCredential is only used for authentication challenges, not for preauthorizing the request. So if your API requires an `Authorization` header in the request this won't work. There seems to be a lot of confusion around how this works, see [this issue](https://github.com/Alamofire/Alamofire/issues/32) on Alamofire.

I worked around this with the following:

```swift
lazy var provider: MoyaProvider<LoginService> = {
    let endpointClosure = { (target: LoginService) -> Endpoint<LoginService> in
      let defaultEndpoint = MoyaProvider.defaultEndpointMapping(for: target)

      switch target {
      case .login(let username, let password):
        return defaultEndpoint.adding(newHTTPHeaderFields: ["Authorization": "\(username):\(password)".base64Encoded])
      }
    }
    
    return MoyaProvider(endpointClosure: endpointClosure)
  }()
```

You could likely extract this to a plugin by using the `AccessTokenPlugin` as a guide. One reason I went this route instead of using the `AccessTokenPlugin` is that I wanted the ability to create requests with different credentials without having to create a new provider instance. `CredentialsPlugin` seemed like it would allow that, but lacked the pre-auth my API required.

If anyone has any better solutions, I'd be very interested to see them.

**Comment by nmccann** [comment]
I ended up improving this by introducing my own plugin as well as my own protocol that targets could conform to:

```swift
struct SessionCredentials {
  let username: String
  let password: String
}

protocol SessionAuthorizable: AccessTokenAuthorizable {
  var credentials: SessionCredentials? { get } //If you never mix authenticated and non-authenticated endpoints in your targets, you could make credentials non-nullable
}

private extension SessionAuthorizable {
  func authorization() -> String? {
//Convert credentials to a Base64 encoded string, prefixed with "Basic"
  }
}

class SessionPlugin: PluginType {
  public func prepare(_ request: URLRequest, target: TargetType) -> URLRequest {
    guard let authorizable = target as? SessionAuthorizable, let value = authorizable.authorization() else {
        return request
    }

    var request = request
    request.addValue(value, forHTTPHeaderField: "Authorization")
    return request
  }
}
```

I chose to build on `AccessTokenAuthorizable` and it's `AuthorizationType` enum - alternately you could introduce your own or get rid of it entirely if you only have one supported authentication type.

**Comment by dehlen** [comment]
Thank you very much. Your effort is much appreciated on my side :) I'll close this issue since my problem is solved this way.

**Comment by yutaoming** [comment]
I meet both issues when I  want to use CredentialsPlugin :)
