### ISSUE TITLE
Multitarget with from data parameter

### ISSUE THREAD

**Issue by Sadmansamee** [Moya/Moya#1299]
I'm using Moya version 9.0.0. 

I have an API where it takes an image and a parametre both are in Form data. so how can I do it? on previous version It was working now it's not.

**Comment by sunshinejr** [comment]
Hey @Sadmansamee. Please take a look at [this example](https://github.com/Moya/Moya/blob/master/docs/Examples/MultipartUpload.md#parameters-in-body). It covers multipart upload - image and description. If this is not what you wanted/you have more questions about it, please let me know!

**Comment by BasThomas** [comment]
Hey @Sadmansamee - were you able to fix your problem? If so, can you let us know how you were able to do so? 😃

**Comment by Sadmansamee** [comment]
@BasThomas  yes, I was able to fix it, thank you very much 😃
