### ISSUE TITLE
Weird issues calling dematerialize() running tests target

### ISSUE THREAD

**Issue by adimango** [Moya/Moya#1300]
Running tests with Moya 9.0, the compiler returns weirds issues (attached) this **only** running test targets, any idea? 
note: If i remove the `result.dematerialize()` everything works.

```
    func performFetchMedia (request: FetchMediaRequest) {
        InstagramProvider.request(.userMedia(request.accountName!,request.offset)){ result in
            do {
                let response = try result.dematerialize()
                let value:[String: Any] = try response.mapNSArray()
            } catch {
                self.loadFetchMediaFailureAlert(error: error)
            }
        }
    }
```

project link: https://github.com/adimango/insights-for-instagram

![screen shot 2017-09-21 at 11 02 34](https://user-images.githubusercontent.com/5462772/30687725-70e4357c-9ebc-11e7-9f23-6b0ef18254dd.png)
![screen shot 2017-09-21 at 11 02 24](https://user-images.githubusercontent.com/5462772/30687726-70e97d2a-9ebc-11e7-85f4-61616697cd04.png)

**Comment by sunshinejr** [comment]
Hey @adimango. Can you try if importing `Result` resolves the issue?

**Comment by adimango** [comment]
Hey @sunshinejr, yes it works!
Thank You.
