### ISSUE TITLE
TargetType default value for sampleData

### ISSUE THREAD

**Issue by armandsLa** [Moya/Moya#1301]
Is there a reason why `sampleData`  in `TargetType` protocol does not have a default value? It's a great feature but would love to get rid of `return "".data(using: String.Encoding.utf8)!` when not testing.

**Comment by BasThomas** [comment]
You can `return Data()` too. We don’t offer defaults so the implementation is always clear (see the Vision document)

**Comment by armandsLa** [comment]
Thanks
