### ISSUE TITLE
Swift 4 and RxMoya

### ISSUE THREAD

**Issue by devxoul** [Moya/Moya#1303]
Hey guys,

RxMoya currently doesn't support Swift 4 because there was no RxSwift release for Swift 4. However, RxSwift recently released [4.0.0 beta](https://github.com/ReactiveX/RxSwift/releases/tag/4.0.0-beta.0) and I think we can start using this version to support Swift 4.0 in RxMoya. How do you think?

**Comment by BasThomas** [comment]
Definitely! It’s planned for the 10.0 release. Would you be up for a PR to add support for RxSwift 4? :)

**Comment by devxoul** [comment]
Sure! #1306

**Comment by SD10** [comment]
This is merged into `10.0.0-dev` so closing this. Thank you @devxoul 👍!!
