### ISSUE TITLE
Pods written in Swift can only be integrated as frameworks

### ISSUE THREAD

**Issue by msalmanST** [Moya/Moya#1307]
"[!] Pods written in Swift can only be integrated as frameworks; add `use_frameworks!` to your Podfile or target to opt into using it."

This is the error I get when using Moya pod where my pod file does not contain "use_framework!"

Any workaround for the above issue ?

**Comment by BasThomas** [comment]
If you add Moya as a pod, you’ll need to add the `use_frameworks!` line in your Podfile. It’s required for all Swift frameworks.

**Comment by msalmanST** [comment]
Thanks for your quick response.
As per https://github.com/CocoaPods/CocoaPods/pull/6811 are you guys thinking to give any such support in coming future ?

**Comment by BasThomas** [comment]
Yes, probably. For now you’d have to stick with adding the `use_frameworks!` though.

**Comment by msalman** [comment]
@BasThomas Any guidelines for me after the release of [cocoapod version 1.5 beta ](https://github.com/CocoaPods/CocoaPods/releases/tag/1.5.0.beta.1)

**Comment by sunshinejr** [comment]
@msalman I didn't try the feature yet, but Artsy's eigen is already moved to static libraries, see [artsy/eigen#2561](https://github.com/artsy/eigen/pull/2561/files#diff-4a25b996826623c4a3a4910f47f10c30), maybe it will help.
