### ISSUE TITLE
Add pull request template

### ISSUE THREAD

**Issue by BasThomas** [Moya/Moya#1313]
I’ve seen numerous issues that had to be closed manually because the PR didn’t include something like “fixes #9001”, which would in turn automatically close the referenced issue.

I propose to add a super simple pull request template that encourages the user to add a “fixes #” at the top of their PR.

**Comment by sunshinejr** [comment]
Good idea, maybe we can link to the [Changelog guide](https://github.com/Moya/contributors/blob/master/Changelog%20Guidelines.md) in there as well?
