### ISSUE TITLE
Use reduce(into:_:) in favor of reduce(_:_:)

### ISSUE THREAD

**Issue by SD10** [Moya/Moya#1316]
Been bugging me for awhile but refactoring to a `for loop` decreased readability 😅.

It's better to use `reduce(into:_:)` when working with copy-on-write types because currently the reduce method we use makes a copy of the plugin array with every iteration of the closure. It's cheaper to not make all these needless copies.

We do this [here](https://github.com/Moya/Moya/blob/master/Sources/Moya/MoyaProvider%2BInternal.swift#L32) and [here](https://github.com/Moya/Moya/blob/aedd30604d78ac231b9aa295f021681ea62fd4da/Sources/Moya/MoyaProvider%2BInternal.swift#L69).

**Comment by SD10** [comment]
May not want to bother with this one for now. Would require [PluginType methods](https://github.com/Moya/Moya/blob/master/Sources/Moya/Plugin.swift#L10) have discardable results because the `reduce(into:_:)` doesn't use the return value.

Also, I had it in my mind that the result is a `Collection` type when it's in fact a `Result<Response, MoyaError>`. Still likely a copy-on-write type but pales in comparison to the costs of copying if it were a collection. 

Looks like I don't get to use this new toy in Swift 4 :(

**Comment by sunshinejr** [comment]
I feel ya. Although with your recent findings I believe we can close this one for now? Might be cool to revisit it once we get to plugins revamp :)

**Comment by SD10** [comment]
Yes closing this for now 👍
