### ISSUE TITLE
Add Code of Conduct & Contributing.md to Moya/Moya

### ISSUE THREAD

**Issue by BasThomas** [Moya/Moya#1318]
We should add (a copy of) the CoC in the main repo for transparency.

The CoC is currently found [here](https://github.com/Moya/contributors/blob/master/Code%20of%20Conduct.md).
We should then also add a link to the local CoC in the Readme.

**Comment by SD10** [comment]
To be honest I never liked that a lot of the important documentation was in the `contributors` repo. I always saw that as a guide for other projects to apply Moya's approach to open source. I feel like more of those files should be in the main repo or the README should be very explicit in where to find those documents.

**Comment by sunshinejr** [comment]
Good idea! Also `Contributing.md` could be transported here, as it gives us visibility in GitHub Community metrics.

**Comment by BasThomas** [comment]
> as it gives us visibility in GitHub Community metrics.

I should've clarified - that's exactly why I wanted to do this.

**Comment by SD10** [comment]
I think linking the `Changelog Guidelines` to Danger was the best move. We also have to consider maintaining these docs if they're in two places. But most of them are pretty static

**Comment by BasThomas** [comment]
Was that comment meant to be on #1317 @SD10?

**Comment by SD10** [comment]
No, I was just very unclear. I was worried about having to maintain `Changelog Guidelines` in the `contributors` repo and in the main repo. It would be the most dynamic of our documents -- not a big issue though.

The Danger comment was probably better stated in the open PR 😅 Thanks for doing that!

**Comment by BasThomas** [comment]
Haha. Yeah - if we'd have to maintain a Changelog in two repos... ugh

**Comment by SD10** [comment]
Do we even have a `Contributing.md`? I can't find a file by that name in either repo. We link to `Community.md` when talking about contributing and this file is present in the Moya main repo.

**Comment by sunshinejr** [comment]
Hmm, you are right we don't have `Contributing.md`. But I think that `Community.md` is really close to it. Should we rename it, though? What do you think @ashfurrow?

**Comment by ashfurrow** [comment]
Yeah yeah, let's rename 👍

**Comment by sunshinejr** [comment]
Should we rename it only in Moya repo, or in contributors repo as well? @ashfurrow

**Comment by ashfurrow** [comment]
Let's do both – we'll have to update some links in the contributors readme.

**Comment by sunshinejr** [comment]
Cool! Will take care of that.
