### ISSUE TITLE
Hacktoberfest!

### ISSUE THREAD

**Issue by sunshinejr** [Moya/Moya#1323]
Hey guys! In October we are celebrating [Hacktoberfest](https://hacktoberfest.digitalocean.com). TL;DR A month-long celebration of open-source. On that website you can find a list of projects that have already some task/issues with [**hacktoberfest**](https://github.com/Moya/Moya/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest) label, so people can chime in. We still have few days left till it starts, so I'm thinking about first labeling all our starter tasks and then maybe we can add some more to encourage people. Currently, [list of Swift tasks](https://github.com/search?l=Swift&q=label%3Ahacktoberfest+state%3Aopen+type%3Aissue&type=Issues) is small, but we can help and make it bigger! :)

And as always, let me know what do you guys think!

**Comment by AndrewSB** [comment]
We're now deep in hacktoberfest. Does anyone have any issues we can create as good starter tasks? Something we've wanted to add/change/remove for a while?

**Comment by sunshinejr** [comment]
Hm, I don't have anything like that in my list anymore apart from SPM testing that I'm taking care off. There are also tasks like website, playgrounds etc that are almost stale now, but not sure if these are easy starter tasks 😞

**Comment by SD10** [comment]
We could possibly add a task for someone to rewrite the CHANGELOG using our new guidelines?

**Comment by sunshinejr** [comment]
Great idea @SD10, added the issue (#1395).

**Comment by AndrewSB** [comment]
awesome! I'm happy we could get one more thing added before the month ended
