### ISSUE TITLE
Missing Content-Type when using .requestData(Data)

### ISSUE THREAD

**Issue by wieweb** [Moya/Moya#1329]
Moya 9.0

When using `.request(Data)` Moya do not add a Content-Type to httpHeaders. 
For `requestParameters(parameters: [String : Any], encoding: Moya.ParameterEncoding)` headers get set by Alamofire.

It's easy to fix by manually set `headers` in TargetType. 
```swift
var headers: [String: String]? {
            return ["Content-Type": "application/json"]
        }
    }
```

But it would be nice to pass it directly in `task`.
e.g.:
```swift
return . requestData(myData, contentType: .jsonData)
```

**Comment by SD10** [comment]
@wieweb You're responsible for adding your own headers. This is why the `headers` property is declared on `TargetType` without any default implementation. 

I'm not sure that passing the headers inside of `Task` is a good idea. I think it's far more flexible to be able to set this through the headers property.

**Comment by wieweb** [comment]
@SD10 I see your point. But when using `requestParameters` ContentType get set correctly.
I did expect the same behaviour on `requestData`.
Maybe we can combine this issue with #1325. Something like `requestEncodable(data:encoding:)` with correct ContentType headers ;-)

**Comment by ykws** [comment]
> requestEncodable(encodable:jsonEncoder:) with correct ContentType headers ;-)

replace `requestJsonEncodable`
