### ISSUE TITLE
Paw Moya Generator

### ISSUE THREAD

**Issue by narlei** [Moya/Moya#1330]
Here is a extension to Paw (https://paw.cloud) to generate Moya files based in requests.

https://github.com/narlei/SwiftMoyaCodeGenerator

**Comment by sunshinejr** [comment]
Hey @narlei. Thanks for doing that! Would you be up for making a PR that adds this one to the [CommunityProjects.md](https://github.com/Moya/Moya/blob/master/docs/CommunityProjects.md)? [Here](https://github.com/Moya/Moya/pull/1310) is an example of how could it look like.

**Comment by narlei** [comment]
@sunshinejr  I created a PR here https://github.com/Moya/Moya/pull/1332
Thank you!

**Comment by sunshinejr** [comment]
Closed by #1332.
