### ISSUE TITLE
How does support swift 4

### ISSUE THREAD

**Issue by ondev** [Moya/Moya#1333]
I try to upgrade my xcode to 9.0,  and Moya not work on swift 4.

**Comment by ondev** [comment]
Moya v9.0.0 is support the swift4, but its dependence RxSwift is v3.3,  not support swift4,  I to fix this problem?

**Comment by sunshinejr** [comment]
Hey @ondev. We have a branch `10.0.0-dev` that works with newest RxSwift. You just need to keep in mind that this is our development branch and you shouldn't rely on it in the production code. We plan to release `10.0.0-beta` in a near future, just few things left. You can track the progress at #1253.

If you use CocoaPods you can use these lines to use `RxSwift` & `Moya` with Swift 4:
```ruby
pod 'RxSwift', '4.0.0-beta.0'
pod 'Moya/RxSwift', :git => 'https://github.com/Moya/Moya.git', :branch => '10.0.0-dev'
```

If you want a stable production version, you can use Moya in Swift 3.2 with your codebase being 4.0 - see [this tweet](https://twitter.com/johnsundell/status/910538432451170305) for instructions.

Let me know if you have more questions around this topic!

**Comment by sunshinejr** [comment]
Just updating the issue: you can now use Moya with Swift 4.0 and RxSwift 4.0! With `RxSwift` you can use Moya 9.0.0, but with `RxSwift` you need Moya 10.0.0 (which is right now in beta.1 stage). You need `RxSwift` 4.0.0-rc.0, so for example when you use CocoaPods, you would need lines below to use newest Moya:
```ruby
pod 'RxSwift', '4.0.0-rc.0'
pod 'Moya/RxSwift', '10.0.0-beta.1'
```
