### ISSUE TITLE
Moya + AlamofireImage

### ISSUE THREAD

**Issue by SeRG1k17** [Moya/Moya#1342]
Is it possible to use AlamofireImage to download images with Moya?

```swift
public enum EndPoints {
    case weather(in: String)
    case download(icon: String)
}

//...
public var task: Task {
        
        switch self {
        case .weather: return .requestParameters(parameters: parameters, encoding: URLEncoding.queryString)
        case .download: return .requestPlain
        }
    }

//Another file:
//...
    func downloadImage(name: String) {
        
        provider.request(.download(icon: name)) { [weak self] response in
            
            switch response {
            case let .success(moyaResponse):
                self?.delegate?.weatherImage(moyaResponse.data)
                
            case let .failure(error):
                self?.delegate?.failure(error)
                print("error: \(error)")
            }
        }
    }
```
I understand that i can write: 

```swift
Alamofire.request(url).responseImage { response in //...
```
But this is not quite elegant and violates the principle that the entire network layer uses Moya
Apparently, to use any available closures to do this, it does not work out

**Comment by sunshinejr** [comment]
Hey @SeRG1k17. You can download images with Moya, both to a disk (`Task.downloadDestination` or `Task.downloadParameters` if you need parameters in the `Task`) and not (using all `Task.request*` cases). If you just want to fetch the image without downloading... we provide mappers! `Response.mapImage()` function should be helpful in this one:
```swift
provider.request(.downloadImage) { result in
    switch result {
        case let .success(response):
            let image = try? response.mapImage()
        ...
    }
}
```

Let me know if this resolves your issue 😉

**Comment by SeRG1k17** [comment]
@sunshinejr Thanks for the answer, but I think it's a little different from what I'd like. That is, you propose to manually process all pictures (manually cache them).
The version with the mapping is convenient, but it's just an asynchronous download.

It seems this is the simplest option:
```swift
Alamofire.request(url).responseImage { response in //...
//Set imageView.image = responseImage
```

**Comment by AndrewSB** [comment]
@SeRG1k17 to my knowledge using AlamofireImage through Moya currently isn't possible. We may be open to a Pull Request that adds support, but I don't speak for the entire org, if you're interested in that, I'd recommend creating a new issue with a proposal, rationale, etc.

I personally use [PINRemoteImage](https://github.com/pinterest/PINRemoteImage) and love it. I think it's ok to leave the Moya ecosystem for image downloading and caching. I saw no upside from limiting myself to just Moya (other than first class testing support, for which I wrapped PINRemoteImage with a class that could used stubbed images instead)

**Comment by IgorNiko83** [comment]
mapImage() failed parse image request which have destination, so - may be can help.

```
public extension Response {

    func mapImage(token: Moya.TargetType) throws -> UIImage {
        var image: UIImage?
        switch token.task {
        case let .downloadDestination(downloadDestination):
            if let httpResponse = response, let url = httpResponse.url {
                let fileUrl = downloadDestination(url, httpResponse).destinationURL
                if let data = try? Data(contentsOf: fileUrl) {
                    image = UIImage(data: data)
                }
            }
        case let .downloadParameters(_, _, downloadDestination):
            if let httpResponse = response, let url = httpResponse.url {
                let fileUrl = downloadDestination(url, httpResponse).destinationURL
                if let data = try? Data(contentsOf: fileUrl) {
                    image = UIImage(data: data)
                }
            }
        default:
            image = try? mapImage()
        }
        
        guard let result = image else {
            throw MoyaError.imageMapping(self)
        }
        
        return result
    }
}
```

usage

```
    func requestOptionalImage(_ token: Target) -> Observable<UIImage?> {
        return self.rx.request(token)
            .asObservable()
            .filterSuccessfulStatusCodes()
            .map({ try $0.mapImage(token: token) })
            .catchError { error in
                return Observable.error(self.mapError(error))
        }
    }
```
