### ISSUE TITLE
Failed convert to current syntax 

### ISSUE THREAD

**Issue by ninasaveljeva** [Moya/Moya#1345]
Hello, 
I've tried to setup Moya via cocoa pods. Xcode version 8.3.3, swift 3.1

My Podfile is 

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!
target 'testForms' do 
    pod 'Moya'
end

```
Pod install working good:
```
Installing Alamofire (4.5.1)
Installing Moya (9.0.0)
Installing Result (3.2.4)
```
After that Xcode ask to convert to current swift syntax which failed for Moya. It suggest to make changes in Moya Core classes. Can you help me to fix it?

Thanks.

**Comment by BasThomas** [comment]
Hey @ninasaveljeva! Moya 9.0 [doesn’t support Swift 3.1](https://github.com/Moya/Moya#moya-version-vs-swift-version). Try to change the `pod 'Moya'` to `pod 'Moya', '~> 8.0.5'` and see if that helps? :)

**Comment by ninasaveljeva** [comment]
Thanks for quick response.
I've tried that before and once again now. Same thing. Installed 8.0.5 but could not convert to current swift syntax :( Ask to change e.g 
```
public struct AccessTokenPlugin: PluginType {

    /// The access token to be applied in the header.
    public let token: String

    private var authVal: String {
        return "Bearer " + token
    }
```


to 

```
public struct AccessTokenPlugin: PluginType {

    /// The access token to be applied in the header.
    public let token: String

   fileprivate var authVal: String {
        return "Bearer " + token
    }

```

**Comment by ninasaveljeva** [comment]
Ended up by renewing Xcode to 9.0 and install Moya 9.0

**Comment by SD10** [comment]
Sorry, computer experienced a major lag (yes on GitHub 😅) and I accidentally closed this.
It looks like it can be closed anyways though. Sorry, you had to resolve this by upgrading to Moya 9.0 @ninasaveljeva but we hope you like the new version!
