### ISSUE TITLE
Moya 9: Type Task has no member 'request'

### ISSUE THREAD

**Issue by mazz** [Moya/Moya#1353]
Hi all, after upgrading to Moya 9, my TargetType extension will no longer compile. What do I return now?

```swift
    var task: Task {
        switch self {
        case  .zen, .showUser, .createUser, .updateUser, .showAccounts:
            return .request // compile error
        }
    }
```

**Comment by BasThomas** [comment]
What is the compiler error you are seeing?

**Comment by SD10** [comment]
Hey @mazz, in Moya 9.0 we condensed `task` and `parameters` into a single property.
Can you take a look at [Moya 9.0 Migration Guide](https://github.com/Moya/Moya/blob/master/docs/MigrationGuides.md) and let me know if you have any questions after this?

**Comment by mazz** [comment]
Hi @SD10 thanks for the prompt response. I changed the `.request` to `.requestPlain` and that fixed my compile error but at runtime now I'm getting back 400 and 500 errors from the server calls that would return 200 before.

**Comment by SD10** [comment]
@mazz Do your requests have parameters? If they do you need to use:
`.requestParameters` and provide the parameters and parameter encoding as associated values.

**Comment by mazz** [comment]
@SD10  yeah I understand what is going on. I'll have to refactor `task` a bit to segment between the various calls that have parameters and the ones that do not. I was lazily bunching them all together with a catch-all `.request` Thanks for the help!

**Comment by SD10** [comment]
@mazz Glad we could resolve this for you. You might want to check out [Targets.md](https://github.com/Moya/Moya/blob/master/docs/Targets.md) and [Basic.md](https://github.com/Moya/Moya/blob/master/docs/Examples/Basic.md) for examples on using `.requestParameters`.
