### ISSUE TITLE
Create a Moya 9.0 -> 10.0 Migration Guide

### ISSUE THREAD

**Issue by SD10** [Moya/Moya#1354]
Moya `10.0` will have significantly less breaking changes as compared to the `8.0` -> `9.0` migration. However, this is relatively easy to write up and nice to have. I'm going to start working on this later this evening, just creating an issue in case anyone had similar plans.

**Comment by sunshinejr** [comment]
Great idea @SD10, thank you for covering that one!

**Comment by sunshinejr** [comment]
Hm, this one didn't close itself as well, seems like `resolved #NNNN` doesn't work even though it is highlighted as if it would. ¯\_(ツ)_/¯
