### ISSUE TITLE
How to avoid duplicate HTTP request?

### ISSUE THREAD

**Issue by swordjoy** [Moya/Moya#1361]
In Some request, I hope that there is only one same request at the same time.
For example
- If the request is in progress, retrun and not to perform a new and same request.Such as tap a button to submit an order.If I duplicate tap the button, I don't want to duplicate request and get some same order.
Now, I use one global dictionary to cache request in progress. Function name as key, Cancellable as value.
```swift
func requestData() -> Cancellable {
    if let cacheCancle = globalDictionary[function name] {
        // request is in progress. return
        return cacheCancle
    }
    
    let cancle =  MoyaProvider.request....{
        // in respose
        globalDictionary.removeValue(forKey: function name)
    }
    
    globalDictionary[function name] = cancle
    return cancle
}
```
but the problem is in each request function, I must to write code like above.
- judge request is in progress or not
- in respose, remove it
- cache request to globalDictionary

Is there a way that can implement this in one place?

**Comment by AndrewSB** [comment]
Let me know if this is too high level, but Carlos, a swift caching library supports this https://github.com/WeltN24/Carlos#pooling-requests

Also, if you're so inclined, I always recommend a swift caching talk given by a friend of mine: https://www.youtube.com/watch?v=8uqXuEZLyUU
