### ISSUE TITLE
How to add parameters to body when upload multipart data in 10.0.0_beta1

### ISSUE THREAD

**Issue by RockyAo** [Moya/Moya#1362]
I only find one method to add parameters ,  but it add the parameters to url.. I want to add parameters to body. How could I do it
```swift
public var task: Task {
        switch self {
        case .createAvatar(let imageData,let both,let noBody):
            let data = MultipartFormData(provider: .data(imageData), name: "input", fileName: "imageName", mimeType: "image/jpeg")
            
            let parameters = [
                "mode":"final",
                "no_body": noBody ? 1 : 0,
                "both": both ? 1 : 0
                ] as [String : Any]
            
            return .uploadCompositeMultipart([data], urlParameters: parameters)
        }
    }
```

**Comment by sunshinejr** [comment]
Hey @RockyAo! Please take a look at our [example for `MultipartUpload`](https://github.com/Moya/Moya/blob/master/docs/Examples/MultipartUpload.md). There you can find how to add parameters in body and in url. Also, please let me know if there is something missing or something we can improve. Cheers!

**Comment by RockyAo** [comment]
@sunshinejr Thanks for answer,
