### ISSUE TITLE
Error installing Moya

### ISSUE THREAD

**Issue by lubieapki** [Moya/Moya#1363]
[!] Error installing Moya
[!] /Applications/CocoaPods.app/Contents/Resources/bundle/bin/git -C /var/folders/lb/cp793sm10k54t_cm2r672ghc0000gn/T/d20171010-4551-1pcrx3r checkout --quiet 7c74420a86b0b492ffa989aadb2c542a3d3c6c23

fatal: reference is not a tree: 7c74420a86b0b492ffa989aadb2c542a3d3c6c23

7 c74420a86b0b492ffa989aadb2c542a3d3c6c23

**Comment by sunshinejr** [comment]
Hey @lubieapki, please let me know your environment better: `CocoaPods` version, `Podfile`, `Podfile.lock` all would be greatly appreciated to inspect the problem. Thanks!

**Comment by lubieapki** [comment]
Hey sunshinejr

cocoapods-1.3.1

Podfile:
platform :ios, '9.0'
inhibit_all_warnings!

target 'Zero' do
  use_frameworks!

  # Architecture
  pod 'ReactorKit'

  # Networking
  pod 'Moya/RxSwift', :git => 'https://github.com/Moya/Moya.git', :branch => '10.0.0-dev'
  pod 'MoyaSugar/RxSwift', :git => 'https://github.com/devxoul/MoyaSugar.git', :branch => 'master'

  # Rx
  pod 'RxSwift', '4.0.0-beta.0'
  pod 'RxCocoa', '4.0.0-beta.0'
  pod 'RxDataSources', :git => 'https://github.com/RxSwiftCommunity/RxDataSources.git', :branch => 'swift4.0'
  pod 'Differentiator', :git => 'https://github.com/RxSwiftCommunity/RxDataSources.git', :branch => 'swift4.0'
  pod 'RxOptional'
  pod 'RxKeyboard'
  pod 'RxGesture', :git => 'https://github.com/sidmani/RxGesture.git', :branch => 'swift-4'

  # UI
  pod 'SnapKit', '~> 4.0.0'
  pod 'ManualLayout'

  # Logging
  pod 'CocoaLumberjack/Swift'

  # Misc.
  pod 'ReusableKit'
  pod 'SwipeCellKit', :git => 'https://github.com/SwipeCellKit/SwipeCellKit.git', :branch => 'swift4'
  pod 'UITextView+Placeholder'

  # Testing
  target 'ZeroTests' do
    pod 'RxTest', '4.0.0-beta.0'
    pod 'RxExpect'
    pod 'RxOptional'
  end

end

post_install do |installer|
  pods_dir = File.dirname(installer.pods_project.path)
end

**Comment by sunshinejr** [comment]
Hey @lubieapki, our current branch `10.0.0-dev` shouldn't be used anymore as we have a version `10.0.0-beta.1` already released. Please use the following lines instead:
```ruby
pod 'RxSwift', '4.0.0-rc.0'
pod 'RxCocoa', '4.0.0-rc.0'
pod 'Moya/RxSwift', '10.0.0-beta.1'
```

You'll probably need to see if other Rx dependencies like `RxOptional` etc. support `RxSwift` version 4.0.0-rc.0.

**Comment by lubieapki** [comment]
@sunshinejr dzięki ;P
