### ISSUE TITLE
Require pull request reviews and status checks

### ISSUE THREAD

**Issue by BasThomas** [Moya/Moya#1368]
Re: https://github.com/Moya/Moya/pull/1365#issuecomment-335738959, do we want to look into requiring reviews and / or status checks before we can merge things? I think the advantages of these far outweigh the disadvantages, and we can maybe make the Core Team be able to ignore these?

**Comment by SD10** [comment]
I completely agree with having both required code reviews and passing CI builds. At the very minimum code reviews. 

You can add specific individuals who are able to override these requirements in the case of it becoming a nuisance. If CI starts acting up then we can just temporarily disable it as a requirement.

**Comment by sunshinejr** [comment]
👍 Good idea. Core team members have Admin access to Moya so they should be able to override the settings in case of failable CI or whatever other reasons. Would you be up for setting this one up, @BasThomas?

**Comment by BasThomas** [comment]
Done!

![screen shot 2017-10-11 at 13 18 55](https://user-images.githubusercontent.com/4190298/31437799-cb01bc62-ae86-11e7-83c5-b1d8370e32ea.png)

**Comment by BasThomas** [comment]
Did the same for the `10.0.0-dev` branch.
