### ISSUE TITLE
Add/rename one of the labels to "help wanted" or "good first issue".

### ISSUE THREAD

**Issue by sunshinejr** [Moya/Moya#1371]
See this info:
<img width="329" alt="zrzut ekranu 2017-10-11 o 21 22 12" src="https://user-images.githubusercontent.com/5232779/31461609-5acc240c-aeca-11e7-8fa7-4368ce760382.png">

Shall we rename `starter task` to `help wanted` or `good first issue`? Because that is our equivalent of some sort. Interested in your opinion, guys! @Moya/contributors

**Comment by devxoul** [comment]
+1 for `good first issue`. `help wanted` doesn't seem to be a starter task.

**Comment by BasThomas** [comment]
Let's go with `good first issue` indeed.

**Comment by sunshinejr** [comment]
I also liked it more. Cool then, renamed already! Thanks for a quick feedback guys! 💯

**Comment by SD10** [comment]
I really wish GitHub had decided to use `Starter Task` 😢

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sunshinejr** [comment]
Same @SD10, when it happens, we will adjust accordingly of course 😉
