### ISSUE TITLE
Remove redundant RxSwift & ReactiveSwift request methods.

### ISSUE THREAD

**Issue by AndrewSB** [Moya/Moya#1372]
I saw this https://github.com/Moya/Moya/pull/1320#issuecomment-332476303 and thought it would be a good idea to create an issue so we don't forget to do this

**Comment by sunshinejr** [comment]
Oh, thank you for catching it! Totally forgot about it. 😓

**Comment by SD10** [comment]
I don't think this made it in the release. To be honest, I was having trouble removing the abstraction while keeping the same API. My RxSwift skills have grown a bit rusty.

**Comment by sunshinejr** [comment]
Taking care of this as we speak. In hindsight, it might not be the best issue for `hacktoberfest` 😅

**Comment by SD10** [comment]
This has been closed in #1399
