### ISSUE TITLE
how to pod target to >= (9.0.0)

### ISSUE THREAD

**Issue by mwapptest** [Moya/Moya#1376]
<!--
I am using Xcode 9.0 & cocoapod. My project pod file mentioned : pod 'Moya'
but when I start with pod install it always install pod with Using Moya (8.0.3)
when I am trying to pod 'Moya', '~ 9.0.0' it gives me error like - `Moya (~> 9.0.0)` required by `Podfile` How to get latest pod 9.0 from pod install commands?

**Comment by mwapptest** [comment]
I am using Xcode 9.0, swift 4.0. and cocoapod. My pod file mentioned pod 'Moya' but when I start with pod install it always downloaded 'Using Moya (8.0.3)', how can I update to latest moya 9.0?

**Comment by SD10** [comment]
Hey @mwapptest,
Can you do `pod update` and then try `pod install` again?

**Comment by Lixyss** [comment]
1.pod repo update;
2.pod install,
work well for me

**Comment by mwapptest** [comment]
it works now, thanks @Lixyss  & @SD10
