### ISSUE TITLE
RxSwift4.0

### ISSUE THREAD

**Issue by Z-JaDe** [Moya/Moya#1379]
RxSwift latest version is 4.0, but Moya->RxSwift is 3.3

**Comment by SD10** [comment]
Hey @Z-JaDe,
We will be using the latest version of RxSwift in `Moya 10.0`. 
You can use the beta release, [10.0.0-beta.1](https://github.com/Moya/Moya/releases/tag/10.0.0-beta.1) which uses `RxSwift, 4.0.0-rc.0`

**Comment by sunshinejr** [comment]
RxSwift 4.0.0 was released at night today, we are gonna prepare for 10.0.0 release today as well :)

**Comment by Z-JaDe** [comment]
I know. Thanks

**Comment by bryant-wang** [comment]
hope it

**Comment by AndrewSB** [comment]
It makes me so happy that our releases sync with Rx. I love that we treat `RxMoya` so well

**Comment by sunshinejr** [comment]
Hey guys, just a heads-up that we found a confirmed bug (#1382) and we will be delaying the 10.0.0 release for a short amount of time to make sure we fixed it correctly. Sorry for the trouble!

**Comment by sunshinejr** [comment]
I'm gonna close this issue as the only problem right now is when the 10.0.0 version is out. For this we have #1253, so please head out there as we are planning the release for today 😉
