### ISSUE TITLE
Weak self in Rx extension causes dispose of the request

### ISSUE THREAD

**Issue by MrAsterisco** [Moya/Moya#1380]
I'm using _Moya 10.0.0-beta.1_ together with _RxSwift 4.0.0-rc.0_ and I've found a weird issue when making a request.

I have the following code:

```swift
MoyaProvider<SomeService>().rx.request(.all)
                .subscribe({ (event) in
                    switch event {
                    case let .success(response):
                        print(response)
                        
                    case let .error(response):
                        print(response)
                    }
                })
                .disposed(by: self.disposable)
```

Using the _out-of-the-box_ install with CocoaPods, this request is never fulfilled. The subscribe event is logged (with RxSwift `debug()` method), but no response is received… ever.

I have managed to identify the issue in `MoyaProvider+Rx.swift` in the following function:

```swift
internal func rxRequest(_ token: Target, callbackQueue: DispatchQueue? = nil) -> Single<Response> {
        return Single.create { [weak self] single in
            let cancellableToken = self?.request(token, callbackQueue: callbackQueue, progress: nil) { result in
                switch result {
                case let .success(response):
                    single(.success(response))
                case let .failure(error):
                    single(.error(error))
                }
            }

            return Disposables.create {
                cancellableToken?.cancel()
            }
        }
    }
```

The issue is solved by just removing the `weak self` reference, hence making `self` a strong reference to the object.

```swift
internal func rxRequest(_ token: Target, callbackQueue: DispatchQueue? = nil) -> Single<Response> {
        return Single.create { single in
            let cancellableToken = self.request(token, callbackQueue: callbackQueue, progress: nil) { result in
                switch result {
                case let .success(response):
                    single(.success(response))
                case let .failure(error):
                    single(.error(error))
                }
            }

            return Disposables.create {
                cancellableToken.cancel()
            }
        }
    }
```

I don't know if this is an actual issue with Moya itself or it depends on something from RxSwift, but I couldn't find any way to reproduce the same behaviour with just RxSwift.

Can someone explain me why?

**Comment by sunshinejr** [comment]
Hey @MrAsterisco. This is kind of a duplicate of #1294. TL;DR is that we don't support this way of executing the request - you need to retain your provider.

**Comment by MrAsterisco** [comment]
I'm really sorry for the duplicate: I didn't see that issue. Ok, closing this one.

**Comment by sunshinejr** [comment]
@MrAsterisco don't worry, we probably need to document it better. Would you be interested in improving our existing documentation? :)

**Comment by MrAsterisco** [comment]
Yeah, sure. But I would need to understand why you changed this… :-)

**Comment by sunshinejr** [comment]
@MrAsterisco There was a bug in `RxSwift` extensions - in `ReactiveSwift` and without any reactive extensions it was working fine (meaning it needed retained provider), only in`RxSwift` it was retained for you.

**Comment by MrAsterisco** [comment]
Uhm, all right. I'm still thinking of it as a bug, just on the RxSwift's side. Anyway, I'm going to update the documentation asap. Thanks for the explanation!
