### ISSUE TITLE
The response map to decodable array always failed.

### ISSUE THREAD

**Issue by ufosky** [Moya/Moya#1381]
See this line of code from branch 10.0.0-dev:
https://github.com/Moya/Moya/blob/a951eeab47ad7f4ef780b63e085704b576bbc3be/Sources/Moya/Response.swift#L127
If the response data at given key path is an array, the type cast to `Dictionary<String, Any>` will always fail, and the result is throw an error.

**Comment by ufosky** [comment]
See this https://github.com/Moya/Moya/pull/1335

**Comment by devxoul** [comment]
I made a mistake and #1382 is a patch for this issue. Thanks for reporting @ufosky!

**Comment by sunshinejr** [comment]
Thank you so much @ufosky for finding this one! So many cases in decodable extension so it was easy to miss one. Thankfully you spotted it just before the release 😉

**Comment by AndrewSB** [comment]
@devxoul: you wrote this, can you confirm this bug?

**Comment by sunshinejr** [comment]
Huh, the PR didn't close this issue even though there was a "Fixes #1381" keyword in it. Really strange, but ¯\_(ツ)_/¯. Closing this one!
