### ISSUE TITLE
How to use RxMoyaProvider 

### ISSUE THREAD

**Issue by zhaoyunyi** [Moya/Moya#1384]
Value of type 'MoyaProvider<UserAPI>' has no member 'rxRequest'
```swift
have thie error userProvider.rxRequest(UserAPI.userApi(request: identifyRequest))
```

**Comment by zhaoyunyi** [comment]
'RxSwift', '~> 4.0.0-rc.0'
'Moya/RxSwift', '~> 10.0.0-beta.1'

**Comment by SD10** [comment]
Hey @zhaoyunyi,

With `Moya 9.0` we deprecated the reactive providers. You need to use the `rx` namespace to access the underlying `request` method.

```Swift
userProvider.rx.request(UserAPI.userApi(request: identifyRequest))
```

Check out the [migration guide](https://github.com/Moya/Moya/blob/master/docs/MigrationGuides.md)
And here is the [RxSwift documentation](https://github.com/Moya/Moya/blob/master/docs/RxSwift.md)

**Comment by zhaoyunyi** [comment]
i slove it, it looks like that project cannot  cocopods code. I drag MoyaProvider+Rx.swift file in main project

**Comment by SD10** [comment]
@zhaoyunyi Please use the method I described above 😅 The file you re-added has been removed for a reason. It wouldn't be a good idea to rely on this because it will no longer be supported in the upcoming version of Moya.

**Comment by zhaoyunyi** [comment]
![image](https://user-images.githubusercontent.com/8953791/31751497-3e8234ae-b44b-11e7-9916-5d803eb26e7a.png)

you are right, but I can not  vist those source file in my main project.
So I use this method to fix it temporarily

**Comment by zhaoyunyi** [comment]
Do you have the same problem?

**Comment by AndrewSB** [comment]
@zhaoyunyi can you share your `Podfile` and `Podfile.lock` please?

**Comment by zhaoyunyi** [comment]
![image](https://user-images.githubusercontent.com/8953791/31752064-a5b3664a-b44e-11e7-9ccf-1de00eacfd5b.png)
![image](https://user-images.githubusercontent.com/8953791/31752090-c4aca408-b44e-11e7-89d8-6bfc33c66b6e.png)
![image](https://user-images.githubusercontent.com/8953791/31752102-d65e4792-b44e-11e7-8163-b2d52ef92721.png)

**Comment by AndrewSB** [comment]
and the code that isn't working for you

**Comment by nsuxin** [comment]
![image](https://user-images.githubusercontent.com/16434431/31859144-4b6cf80a-b6cd-11e7-807e-ccb7c24d06ee.png)
I think that's probably the case

**Comment by evyasafm** [comment]
Add to the Podfile:
`pod 'Moya/RxSwift'`
