### ISSUE TITLE
How to submit a params like json array

### ISSUE THREAD

**Issue by xuech** [Moya/Moya#1387]
here is my Moya's version: 8.0.3 
my paramters like this: [{"A":"1","B":"2"...},{"A":"1","B":"2"...},{"A":"1","B":"2"...}...]

```Swift
enum InventoryService{
    case queryInventory(paramters: [String:Any])
}
var path: String {
        switch self {
        case .queryInventory:
            return  "api/queryInventory"
        }
    }

var parameters: [String: Any]? {
        switch self {
        case .queryInventory(let paramters):
            return ["jsonArray":paramters]
        }
 }


let InventoryRequestClosure = { (endpoint: Endpoint<InventoryService>, done: MoyaProvider.RequestResultClosure) in
    var request = endpoint.urlRequest!
    request.httpMethod = endpoint.method.rawValue
    do {
        request.httpBody = Array(endpoint.parameters!.values.map { $0 })
    } catch {
    }
    request.setValue("application/json", forHTTPHeaderField: "Content-Type")
    done(.success(request))
}
let moyaNetWork = MoyaProvider(endpointClosure: endpointClosure,requestClosure:requestClosure)

```
How do I set it up？
BTY,when i use 'request.httpBody = Array(endpoint.parameters!.values.map { $0 })',
Xcode Prompt error：“Cannot assign value of type 'Array<Any>' to type 'Data?'”

**Comment by SD10** [comment]
Hey @xuech,

You're receiving the Xcode error because `Array(endpoint.parameters!.values.map { $0 })` results in an array and the `httpBody` property accepts `Data?`.

Can you achieve what you want to do without creating a requestClosure and using the other properties of the `TargetType` protocol? You can check the docs for `TargetType` in `Moya 8.0` [here](https://github.com/Moya/Moya/blob/685a6db9aa3a3b3404792366eec38b842cef5f27/docs/Targets.md).

**Comment by lovesomeone** [comment]
hi      
class TestObject:NSObject {
    var id = 0
    var name = ""
    
    func toDictionary() -> [String:Any] {
        return ["id":id,"name":name]
    }
}

**Comment by lovesomeone** [comment]
hi   
this is an example .hope this will help you
``
class TestObject:NSObject {
    var id = 0
    var name = ""
    
    func toDictionary() -> [String:Any] {
        return ["id":id,"name":name]
    }
}


func test()  {
        var objArr = [TestObject]()
        for i in 0...3 {
            var ob = TestObject()
            ob.id = i
            ob.name = "test\(i)"
            objArr.append(ob)
        }
        var resulst = objArr.map { $0.toDictionary() }
        let data = try! JSONSerialization.data(withJSONObject: resulst, options: [])
        // apply this data to request.httpBody
        // request.httpBody = data
        let string = String(data: data, encoding: String.Encoding.utf8)
        print(string)
      
    }
``
