### ISSUE TITLE
Update Changelog.md to our newest standards.

### ISSUE THREAD

**Issue by sunshinejr** [Moya/Moya#1395]
We've updated our guidelines for a Changelog, [here](https://github.com/Moya/contributors/blob/master/Changelog%20Guidelines.md). As you can see in our [Changelog](https://github.com/Moya/Moya/blob/master/Changelog.md), we started using the newest guidelines as of Moya version 10. We need to update the older entries of the Changelog to the newest standards as well.

If you want to claim this issue, please comment here or assign yourself if you are part of Moya organization already.

If there are any questions, we are happy to assist!

**Comment by dannymout** [comment]
I'll work on this

**Comment by sunshinejr** [comment]
Hey @dannymout, how is the task going?
