### ISSUE TITLE
Using Moya as a Facade a certain SDK

### ISSUE THREAD

**Issue by wassimseif** [Moya/Moya#1396]
Is it possible to use Moya to wrap a certain SDK & provide a consistent API for all web services?
For example, i want to hide `FacebookLoginManager.login` API that relies on `FacebookLoginSDK` to do its job. However, in my App, i don't want to expose the `FacebookSDK` APIs. All the network APIs should happen through Moya.
When i tried to do this  i got stuck while confirming to `TargetType`
can someone help me with filling these fields 
```swift
extension APIService : TargetType {
    var baseURL: URL {
        
    }
    
    var path: String {
        
    }
    
    var method: Method {
       
    }
    
    var sampleData: Data {
        
    }
    
    var task: Task {
        
    }
    
    var headers: [String : String]? {
        
    }
    
    
}

```

**Comment by sunshinejr** [comment]
Hey @wassimseif. I'd say that you would need another abstraction layer that decides whether to use Moya or certain SDK to process the request. Without needed information about the target, it would be really painful to integrate FacebookSDK into it, unfortunately.

**Comment by AndrewSB** [comment]
yup
```swift
protocol NetworkTarget {} // an empty marker protocol to use

enum FacebookTarget {
    case login
}
```

```swift
class TheNetwork {
    func request(target: NetworkTarget) -> Observable<Response> {
        switch target {
        case target as FacebookTarget: return facebookRequestLogin()
        case target as MoyaTargetTypeEnum: return moyaProvider.request(target)
        default: fatalError("not yet implemented")
        }
    }
}
```
