### ISSUE TITLE
Using GitHub project management

### ISSUE THREAD

**Issue by SD10** [Moya/Moya#1398]
~Nothing set in stone here. Just want to generate some discussion around what the community wants to see in the next major version.~
~Current list of tasks:~
~- [ ] Improving `AccessTokenPlugin` / plugins in general #1283~
~- [ ] Remove redundant RxSwift & ReactiveSwift methods #137~
~- [ ] Support for stable release of ReactiveSwift that supports Swift 4.0~
~- [ ] Sample data refractor (see issue #1126 and discussion #1285)~

**EDIT: I've changed the subject here to discuss managing Moya with GitHub projects**

Do we have any specific setup/workflow we'd like to adopt?

**Comment by AndrewSB** [comment]
Looks good @SD10 

I thought it might be interesting for us to give GitHub projects a try. https://github.com/Moya/Moya/projects/1, what do you think?

**Comment by BasThomas** [comment]
Would love to try out GitHub Projects.

Initial list of tasks looks solid, too. Thanks for taking the initiative here, @SD10.

**Comment by sunshinejr** [comment]
Thanks for doing this, @SD10! I'm also up for trying the projects out, at least for one version to test the waters. 

Also, do we want to keep this issue anyways? I feel like it is not necessary and whenever we want to publish a new version (alpha/beta/release), we can make a new issue about it. From the last issues that covered the release I feel like these are going stale really fast and are hard to find.

Huh, I just noticed that `ReactiveSwift` didn't release 2.1.0 😮 Now they have alpha for 3.*, that is really interesting.

**Comment by SD10** [comment]
Yeah, we can close this if you'd like 👍. I was just trying to get a vision/start some discussion of what 11.0 would look like. I'm fine with testing out the GitHub projects too. 

I see @AndrewSB set us up with an initial structure. I think this is good but mainly represents the concept of a backlog. Do we also want to track the states of these tasks?
- In Progress
- In Testing
- Merged (Next Release)
- Merged (Master)

We could also add a column for all documentation related tasks?

**Comment by BasThomas** [comment]
> Also, do we want to keep this issue anyways? I feel like it is not necessary and whenever we want to publish a new version (alpha/beta/release), we can make a new issue about it. From the last issues that covered the release I feel like these are going stale really fast and are hard to find.

I agree on all of these points, but I must say that I really like having that one issue where we can share updates regarding the release; eg. when a new version is ((almost) ready to be) released.

**Comment by BasThomas** [comment]
Also, I think it would be nice to create a separate issue for the ReactiveSwift 4.0 support.

**Comment by SD10** [comment]
So sorry @BasThomas, I prematurely changed the discussion here without your feedback 😭 My apologies

**Comment by BasThomas** [comment]
No problem!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
Just a bit of record keeping. The GitHub project management wasn't that helpful for the latest release.

**Comment by BasThomas** [comment]
Yeah, I don’t feel like we have any need / that it would improve managing releases for us at this point. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
Does anyone mind if I close the existing GitHub project? We haven't been using it and I don't find it helpful personally. I'd like to continue with project management via milestones.

**Comment by sunshinejr** [comment]
As I think we agree that we don't really use it, I went ahead and closed the project and gonna close this issue too 👍
