### ISSUE TITLE
How to add extension to retry with OAuth?

### ISSUE THREAD

**Issue by tosbaha** [Moya/Moya#1402]
I am trying to add retry logic with OAuth. I have found following [article](http://sapandiwakar.in/refresh-oauth-tokens-using-moya-rxswift/) for it. However it is for old version of Moya. AFAIK, Moya now returns `Single<Response>`  I tried to port it to new version but it is not working.I get Type of expression is ambiguous without more context. Could you help me to find my error? I am using Moya 10 Thanks

```swift
extension PrimitiveSequence where TraitType == SingleTrait, ElementType == Response {
    /// Tries to refresh auth token on 401 errors and retry the request.
    /// If the refresh fails, the signal errors.
    public func retryWithAuthIfNeeded() ->  Single<Response> {
        return self.retryWhen{e -> Observable<Error> in
            Observable.zip(e, Observable.range(start: 1, count: 3), resultSelector: { $1 })
            .flatMap { i in
                return provider.rx.request(.refresh(token: "abc"))
                .filterSuccessfulStatusAndRedirectCodes()
                .map(Token.self)
                .catchError {  error  in
                    if case MoyaError.statusCode(let response) = error  {
                        if response.statusCode == 401 {
                            // Logout
                            do {
                                try User.logOut()
                               // AlertHelper.show(title: "Error", subTitle: "Please login to continue", actionButton: AlertButton(title: "OK",
                              //                                                                                                   backgroundColor: Constants.Colors.Blue.regular))
                            } catch _ {
                                log.warning("Failed to logout")
                            }
                        }
                    }
                    return Observable.error(error)
                    }.flatMap { token -> Observable<Token> in
                        do {
                            try token.saveInRealm()
                        } catch let e {
                            log.warning("Failed to save access token")
                            return Observable.error(e)
                        }
                        return Observable.just(token)
                }
            }
        }
    }
}
```

**Comment by SD10** [comment]
@tosbaha Can you give us the line where the error occurs?

**Comment by sunshinejr** [comment]
@toshaba I would add return types to every closure (you have missing ones in your first `flatMap` and `catchError`). Compiler with RxSwift gets confused so general rule of thumb is to specifically add return types in each operator.

**Comment by BasThomas** [comment]
@sunshinejr seems like there are actually returns? The first `flatmap` returns immediately, the `catchError` returns after the `if`.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tosbaha** [comment]
@SD10 on line `}.flatMap { token -> Observable<Token> in`

@sunshinejr I added  ` .flatMap { i -> Single<Token> in` and ` .catchError {  error  -> Single<Token> in` didn't make any difference. I think there is a typo somewhere that I can't see.

**Comment by Mazorati** [comment]
For me Single does not have retryWhen... Why?

**Comment by Mazorati** [comment]
this works for me:
import Foundation
import RxSwift
import Moya
import XCGLogger

```
extension PrimitiveSequence where TraitType == SingleTrait, ElementType == Response {
    public func retryWithAuthIfNeeded() -> Single<ElementType> {
        return retryWhen { e in
            Observable.zip(e, Observable.range(start: 1, count: 3),
                           resultSelector: { $1 })
                .flatMap { i -> PrimitiveSequence<SingleTrait, Access> in
                    var _xAppToken = XAppToken()
                    return DataProvider.rx
                        .request(.refreshToken(token: _xAppToken.refreshToken!))
                        .filterSuccessfulStatusCodes()
                        .mapObject(Access.self)
                        .catchError { error in
                            if case MoyaError.statusCode(let response) = error  {
                                if response.statusCode == 401 {
                                    // Logout
                                }
                            }
                            return Single.error(error)
                        }.flatMap({ access -> PrimitiveSequence<SingleTrait, Access> in
                            XCGLogger.default.debug(access.accessToken)
                            XCGLogger.default.debug(access.refreshToken)
                            
                            return Single.just(access)
                        })
            }
        }
    }
}
```

**Comment by tosbaha** [comment]
Thanks @Mazorati for trying to help. I have solved this issue couple of days ago and your issue notification helped to remember this issue again. For anyone interested, I have managed to solve the issue both with `Single` and `Observable` My error was the parameter of `retryWhen` which nobody caught the error :\  

PS: I believe that just like [NetworkStack](https://github.com/NijiDigital/NetworkStack), this project may also benefit from authentication and authorization handler. 

```swift
// With Single
extension PrimitiveSequence where TraitType == SingleTrait, ElementType == Response {
    /// Tries to refresh auth token on 401 errors and retry the request.
    /// If the refresh fails, the signal errors.
    public func retryWithAuthIfNeeded() ->  Single<Response> {
        return self.retryWhen{ (e: Observable<Error>) in
            Observable.zip(e, Observable.range(start: 1, count: 3), resultSelector: { $1 })
                .flatMap { i in
                    return provider.rx.request(.refresh(token: "abc"))
                        .filterSuccessfulStatusAndRedirectCodes()
                        .map(Token.self)
                        .catchError {  error  in
                            if case MoyaError.statusCode(let response) = error  {
                                if response.statusCode == 401 {
                                    // Logout
                                    do {
                                        try User.logOut()
                                    } catch _ {
                                        logger.warning("Failed to logout")
                                    }
                                }
                            }
                            return Single.error(error)
                        }.flatMap { token -> Single<Token> in
                            do {
                                try token.saveInRealm()
                            } catch let e {
                                logger.warning("Failed to save access token")
                                return Single.error(e)
                            }
                            return Single.just(token)
                    }
            }
        }
    }
}

// With Observable just like linked example.
public extension ObservableType where E == Response {
    /// Tries to refresh auth token on 401 errors and retry the request.
    /// If the refresh fails, the signal errors.
    public func retryWithAuthIfNeeded() ->  Observable<Response> {
        return self.retryWhen{ (e: Observable<Error>) in
            Observable.zip(e, Observable.range(start: 1, count: 3), resultSelector: { $1 })
                .flatMap { i in
                    return provider.rx.request(.refresh(token: "abc"))
                        .filterSuccessfulStatusAndRedirectCodes()
                        .asObservable()
                        .map(Token.self)
                        .catchError {  error  in
                            if case MoyaError.statusCode(let response) = error  {
                                if response.statusCode == 401 {
                                    // Logout
                                    do {
                                        try User.logOut()
                                    } catch _ {
                                        logger.warning("Failed to logout")
                                    }
                                }
                            }
                            return Observable.error(error)
                        }.flatMap { token -> Observable<Token> in
                            do {
                                try token.saveInRealm()
                            } catch let e {
                                logger.warning("Failed to save access token")
                                return Observable.error(e)
                            }
                            return Observable.just(token)
                    }
            }
        }
    }
}
```

**Comment by SD10** [comment]
Hey @tosbaha, I'm going to close this now that it's been resolved. Thanks for sharing how you remedied the issue so that others facing similar struggle can resolve theirs 👍

**Comment by Mazorati** [comment]
@tosbaha but i don't understand why do we use Observable.zip(e, Observable.range(start: 1, count: 3) here? Method .retry(3) is the same?

**Comment by tosbaha** [comment]
@Mazorati I am not super confident about RxSwift. However according to my understanding, it gives us better control for each try. For example you can check `i` and act differently. For first try do this, second try do that etc. I think at the end of the day, you prefer whatever works for you.

**Comment by rlam3** [comment]
@tosbaha 

I'm getting an error on the following line: 

<img width="657" alt="screen shot 2017-11-08 at 12 56 48 pm" src="https://user-images.githubusercontent.com/1154044/32568578-50d22558-c484-11e7-9578-0c6e8d485873.png">

```swift

        return self.retryWhen{ (e: Observable<Error>) in
```

Was wondering if you had a demo on github for this retry loop. Thanks!

**Comment by Mazorati** [comment]
@rlam3 use my code above

**Comment by rlam3** [comment]
@Mazorati 

<img width="931" alt="screen shot 2017-11-08 at 3 25 06 pm" src="https://user-images.githubusercontent.com/1154044/32575219-0b7b721a-c499-11e7-9b33-4c4e4b41feb6.png">

I don't believe I should be using a single right? This is what my token map looks like. It takes a refresh_token and gives back a new access_token and a new refresh_token. the old one is scrapped in the backend.

<img width="378" alt="screen shot 2017-11-08 at 3 26 22 pm" src="https://user-images.githubusercontent.com/1154044/32575299-39c52cce-c499-11e7-94db-92552e57628c.png">

**Comment by tosbaha** [comment]
@rlam3 I just hacked a quick repo for you. Open MoyaDemoTests and run the tests. First test goes directly to Internet. Second test uses stubbing to emulate failed response. You can play with it and see what is going on. 

Repo: [MoyaDemo](https://github.com/tosbaha/MoyaDemo)

**Comment by AndrewSB** [comment]
### Heads up to future readers of this issue
This solution is a little hacky and I wouldn't recommend copying it. Using `.zip` as a hack instead of `retrying` is less than ideal.

If you're looking for latest best practices, please give them a shot yourself and open a new issue if you need help with your implementation

**Comment by Mazorati** [comment]
@rlam3 wrong return type after mapping. Use https://github.com/ivanbruel/Moya-ObjectMapper

**Comment by tosbaha** [comment]
@AndrewSB I am sorry to say this, but I don't think opening a new issue will help. I am sure I will sound like ungrateful by writing this. I opened this issue 16 days ago. I am not so much familiar with RxSwift and Moya. I tried to make it work but couldn't. However none of the contributors of this repo looked at it thoroughly. It took me 4 days to solve by myself. I am sure they would find out my error or suggest best practices if they did. Again I sound ungrateful for by complaining on OSS repo. I know everybody is busy with their job and other daily stuff but I don't think that opening a new issue on the same subject will result in different output. It looks like you are focusing more on trivial things like fixing typo on a README, or decreasing amount of days for stale-bot. I don't see the point of decreasing days of stale-bot. I follow most of the contributors and their projects. I am really grateful for what you all share. I love for example Ash Furrow's contributions and his positive attitude. However, not everything works as in theory. I opened two issues on similar subject and I really don't believe that I will get a solution on third.

**Comment by SD10** [comment]
Hey @tosbaha,

I'm really sorry that you feel like the Moya contributors haven't given you the help you need. I can assure you that we all do our best to answer any question that's asked, but it takes a large effort to answer several new questions daily while maintaining the core library. I believe if a Moya contributor is focusing on a seemingly "trivial" task while you have an outstanding question, it is likely that the contributor only has enough time to resolve that simple issue.

That being said, I feel like your question is more related to the use of RxSwift and the Swift compiler than it is directly related to Moya.
