### ISSUE TITLE
How to restart the request

### ISSUE THREAD

**Issue by asasdasasd** [Moya/Moya#1404]
I want to handle each response and if the response not match the condition then retry the request ,
Could you help me ?

**Comment by sunshinejr** [comment]
Hey @asasdasasd. Please take a look at [Wrapping in Adapter example](https://github.com/Moya/Moya/blob/master/docs/Examples/WrappingInAdapter.md) and let me know if it is understandable for you.

**Comment by asasdasasd** [comment]
thanks for your response 
actually I have a scenary that I have an accesstoken and I don't know when it expired, backend will tell me that, and at that time I should refresh accesstoken and retry the request
now I know how to handle each response , 
  like this  [https://github.com/artsy/eidolon/blob/1c746f9a9c6420cda9f691468783fee67376e8b1/Kiosk/App/Networking/Networking.swift#L22-L31](url)
but how to retry the request 
here is my code 
  

```
static func request(target: API) -> Observable<Response> {
        let actualRequest = provider.request(target)
        return self.provider.request(target).flatMapLatest { (response) -> Observable<Response> in
            let responseModel = ResponseModel(data:response.data)
           
            if responseModel.code == -405 {
                let refreshToken = User.shared?.refreshToken
                self.provider.request(.refreshToken(refresh: refreshToken!)).flatMap({ response -> Observable<String> in
                   return Observable.just("")
                   
                }).shareReplay(1).subscribe(onNext: { refreshToken in
                   User.shared?._refresh_token = refreshToken
                 self.provider.request(target)
                }, onError: { (error) in
                    
                },onCompleted: { _ in
                    
                })
                
            }
            
                return Observable.just(response)
        }
    }
```

**Comment by sunshinejr** [comment]
@asasdasasd you would need to check out `retryWhen` operator in RxSwift.

**Comment by asasdasasd** [comment]
@sunshinejr  any examples or Demoes?

**Comment by asasdasasd** [comment]
@sunshinejr  retryWhen is only called when an error occurs, but I just want to retry when the responseModel.code == -405.

**Comment by asasdasasd** [comment]
`retrywhen `operator can handle this scenario

**Comment by AndrewSB** [comment]
@asasdasasd There are a couple of open source apps using Moya, they're interesting to check out https://github.com/Moya/Moya/blob/master/docs/CommunityProjects.md#applications, I'm pretty sure Eidolon retries using `RxSwift`.

If you're having issues retrying the request when the HTTP response code is 405, and want us to help, please share an example app that shows your approach.

**Comment by rsardek** [comment]
The above settings presumes that the app uses Moya and RxSwift. 
What if a project:
- has the same use-case as @asasdasasd  ( make an authenticated call with a token -> server responds token has expired -> refresh the token making an intermediate call -> and only after that make the original request )
- but doesn't use RxSwift

How can I handle such case?

**Comment by AndrewSB** [comment]
hmm, great question!

You can probably handle it by doing subclassing MoyaProvider and overriding `request`, maybe something like 

```swift
func request(token: ..., callback: (Response) -> ()) {
  super.request(token) { (response)
    // heres where the magic happens, you can do anything you want. Check if the token expired, re-request, etc.

    // finally, call the callback in the params once you're happy with the response
    callback(response)
  }
}
```
