### ISSUE TITLE
Content type for requestJSONEncodable

### ISSUE THREAD

**Issue by Vict0rS** [Moya/Moya#1406]
When using requestJSONEncodable task there is no "Content-Type": "application/json" header in result request. Is it intended behavior? Now it is necessary to add this header manually via headers method on TargetType.

Version of Moya: 10.0.0

**Comment by sunshinejr** [comment]
Oh it seems like a bug. Thank you very much @Vict0rS for reporting it. Would you be up for fixing it by making a Pull Request? We would have to add it manually somewhere around [here](https://github.com/Moya/Moya/commit/f2f034b7b668f8b66e1f270aa73f0a0ccee3bbb8#diff-6ad6acf1f7ede09a355e056d27a08965R5), similar as [Alamofire does it](https://github.com/Alamofire/Alamofire/blob/master/Source/ParameterEncoding.swift#L312-L314).

I can help to guide you through, but if you don't have time or just can't do it, I can take it from here.

**Comment by Vict0rS** [comment]
Pull Request is here #1410.
