### ISSUE TITLE
Please close This problem

### ISSUE THREAD

**Issue by zichenJack** [Moya/Moya#1413]
`Moya <= 8.0.5` I use param `parameters` , but in `10.0.0 `  `parameters` was disappear, What should I do?

**Comment by SD10** [comment]
Hey @zichenJack,
Please check out the [Moya 8.0 -> 9.0 migration guide](https://github.com/Moya/Moya/blob/master/docs/MigrationGuides/migration_8_to_9.md) and let me know if you have any questions after that 😃

**Comment by zichenJack** [comment]
I saw doc say the param write in task ,

**Comment by SD10** [comment]
@zichenJack I'm going to close this issue. Let me know if you have any other questions 👍
