### ISSUE TITLE
[Question] Get absolute url from TargetType instance value?

### ISSUE THREAD

**Issue by ufosky** [Moya/Moya#1419]
I want to cache some response data for urls, and get cached data by url. But I use a TargetType value to make a request, and I don't find an easy way to get absolute url from this value.

**Comment by SD10** [comment]
@ufosky Can you use `TargetType`'s two properties`baseURL` & `path` to form the absolute URL? You could add an extension to `TargetType` to make this easier for you across all of your targets.

**Comment by SD10** [comment]
I just remembered that Moya also has a `URL` extension to initlaize a `URL` with a `TargetType`. You can check out the [source file](https://github.com/Moya/Moya/blob/master/Sources/Moya/URL%2BMoya.swift) for this. It could help 😃

**Comment by ufosky** [comment]
But this way only get url from `baseURL` & `path`, if some parameters in the url, like http://www.example.com/path?param1=test, only get result http://www.example.com/path

**Comment by SD10** [comment]
Sorry @ufosky you're right. I'm not sure of any easy way of doing this at the moment. The final `URLRequest` is constructed through the `Endpoint` class 🤔

**Comment by ufosky** [comment]
I use this code currently:
```
if let request = try? MoyaProvider.defaultEndpointMapping(for: target).urlRequest(),
  let url = request.url {
  let key = url.absoluteString
  return key
}
```

**Comment by BasThomas** [comment]
And you could extend your TargetType maybe to wrap this in a variable 👍 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by AndrewSB** [comment]
happy we could help @ufosky!
