### ISSUE TITLE
I want to integrate Moya with Carthage but I can't find the RxMoya file.

### ISSUE THREAD

**Issue by GG526** [Moya/Moya#1422]
I use "github" Moya/Moya in Carthage to add Moya.
```
github "Moya/Moya" ~> 10.0.0
```

**Comment by GG526** [comment]
I can't find Moya in the Checkouts folder

**Comment by AndrewSB** [comment]
I believe that through Carthage, Moya Vends precompiled frameworks

They’re on the release page

**Comment by edulpn** [comment]
```carthage update --no-use-binaries``` will generate RxMoya.framework, but I'm not being able to use ```RxMoyaProvider```, Xcode gives me:

![image](https://user-images.githubusercontent.com/4682317/32246767-3b93be22-be67-11e7-8a1b-29793efeecdd.png)

**Comment by edulpn** [comment]
My bad, I wasn't aware that Moya  10.0.0 extinguishes ```RxMoyaProvider``` and goes the ```MoyaProvider.rx``` way (see [here](https://github.com/Moya/Moya#rxswift))
