### ISSUE TITLE
How to send Synchronous Request 

### ISSUE THREAD

**Issue by hamada147** [Moya/Moya#1426]
Moya v9
Swift 4
Xcode v9

Once I create the provider I'm able to send request but only Asynchronous request. Is there is a specific way that through it I would be able to send Synchronous request where the code will have to wait until the response of the request is received in order to processed.

I read your documentation regarding the "Threading" and found this part of code.

```swift
provider = MoyaProvider<GitHub>(callbackQueue: DispatchQueue.global(.utility))
```

What values other than ".utility" can I use and what dose they represent and how can I override the Alamofire which put the request in the background. I would like both to work on the same thread (main) so they would work in sequence.

**Comment by SD10** [comment]
Hey @hamda147,

Why do you need a synchronous request? It's not recommended to do network requests synchronously. I guess you could use `DispatchQueue.main`? I'm not sure, to be honest :neutral_face:

**Comment by hamada147** [comment]
I know, it's a really bad practice specially if the request take a long period of time. But, I have to use it. Anyway I'm trying it write now.

**Comment by hamada147** [comment]
Unfortunately that didn't work.

**Comment by SD10** [comment]
@hamada147 Can you give me more context as to why you need to perform the request synchronously?

**Comment by hamada147** [comment]
because of API bad design. I need to get some data from request#1 then use these data for request#2 then use that data for the final request#3.

**Comment by SD10** [comment]
@hamada147 You can nest your requests so that you can still perform everything asynchronously.
```Swift
provider.request(.zen) { result in
    switch result {
    case .success(let response):
         // launch next request
        provider.request(.zen) { result in
            switch result {
            case .success(let response):
                // add 3rd request here
            case .failure(let error):
                // failure code
            }
        }
    case .failure(let error):
        // failure code
    }
}
```
The code gets a bit messy but you can look into using some sort of abstraction like a `Promise` to make it more readable.

https://github.com/mxcl/PromiseKit

**Comment by hamada147** [comment]
@SD10 I was doing it this way and became way too messy. I will look into **Promise** and get back to you.

**Comment by hamada147** [comment]
@SD10  I looked into it and I did a small test and this will work really good but since I'm using the Notification Center a lot in my project. I decided to go with that. So the request would work in Asynchronies manner but only send the request after it receives the response from the previous request and so on.

**Comment by hamada147** [comment]
@SD10 you can mark it as closed ;)
