### ISSUE TITLE
Is it possible to install Moya/ReactiveMoya via Carthage without installing RxSwift?

### ISSUE THREAD

**Issue by JohnTheBastard** [Moya/Moya#1427]
Moya 10.0.0
ReactiveSwift 2.0.1

It does not seem possible to install `ReactiveMoya` via carthage without also installing `RxMoya` and `RxSwift` (and probably also `RxBlocking`, `RxCocoa`, and `RxTests`).

Adding ReactiveMoya to Carthage

```ruby
github "Moya/ReactiveMoya" 
```

and running `carthage update ReactiveMoya --platform iOS` produces this error:

```bash
A shell task (/usr/bin/env git checkout --quiet 7ec3c37331e939c1fa07cc3445fa4c0cb47f524f (launched in /path/to/Carthage/Checkouts/ReactiveMoya/External/Moya)) failed with exit code 128:
fatal: reference is not a tree: 7ec3c37331e939c1fa07cc3445fa4c0cb47f524f
```

If I add the following instead:
```ruby
github "Moya/Moya" ~> 10.0 
```
but don't copy the `Rx*` frameworks to my build phases, I get the following error at runtime:

```bash
dyld: Library not loaded: @rpath/RxSwift.framework/RxSwift
  Referenced from: /path/to/Frameworks/Moya_ObjectMapper.framework/Moya_ObjectMapper
  Reason: image not found
```

The runtime issue may be a problem with `Moya-ObjectMapper` specifically, but regardless, I don't see a way to build `ReactiveMoya` without all the `Rx*` dependencies.

**Comment by JohnTheBastard** [comment]
`Moya-ObjectMapper` only has two source files that I needed, so I just moved them into my project and removed the framework. That did fix the runtime issue and allow me to removed the `Rx` frameworks from the project, but I still don't know a way to build `ReactiveMoya` without also building `Rx`.

**Comment by BasThomas** [comment]
With Carthage, this is unfortunately not a possibility at this point. :(

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by JohnTheBastard** [comment]
Okay, good to know. Thanks. (It may be worth mentioning in the documentation.)

**Comment by BasThomas** [comment]
That's a good one. Would you be up for opening a pull request adding it? :)

**Comment by JohnTheBastard** [comment]
Sure, I'll try to put up a PR in the next few days.
