### ISSUE TITLE
Can I re-throw Moya error  or how to process errors of several async requests?

### ISSUE THREAD

**Issue by ninasaveljeva** [Moya/Moya#1429]
Hello, 
I am using Moya 9.0 
I have two requests to be done, but if i've got auth error i should display only one error alert. 
I thought that i could re-throw errors from Moya but i don know how to do this. Can you help? Or there is a better way?

```swift
provider.request(.getChildren(client_id: clientprofile_id)) { result in
    switch result {
    case let .success(moyaResponse):
        do {  //...
            
        }  catch {
            let printableError = error as CustomStringConvertible
            let errorMessage = printableError.description
            SCLAlertView().showError("Network error", subTitle: errorMessage)
        }
    case let .failure(error):
        //got 401 error here. Can I re-throw ?
        switch moyaError {           
        case .underlying(let err, let response):
           {   //...
                if statusCode == 401 || statusCode == 403 {
                    //redirect unauth
                   self.performSegue(withIdentifier: backSegueName, sender: self)
                }
                message = errorData["message"] as! String
            }
            SCLAlertView().showError("Error", subTitle: message)
            
        default :
            print(moyaError)
            SCLAlertView().showError("Error", subTitle: moyaError.errorDescription ?? "")
        }
    }
    
provider.request(.getFamilyDetails(user_id: userid)) {
        // the same as above
}
    
    
```
 Or may be there is another way to process errors of several async request without reactiveX extensions?
Thanks.

**Comment by SD10** [comment]
@ninasaveljeva Can you wrap the call to the `MoyaProvider` in a throwing function then propagate the errors in the failure case? You can then handle them at the call site of the wrapper method. Sorry if this isn't what you wanted to accomplish 😞

**Comment by ninasaveljeva** [comment]
@SD10  If i add throw inside .request handling i've got a complaint about using throw in non-throwing function: 
`Invalid conversion from throwing function of type '(_) throws -> ()' to non-throwing function type 'Completion' (aka '(Result<Response, MoyaError>) -> ()')`

**Comment by SD10** [comment]
@ninasaveljeva I'm not sure if this compiles but maybe its a step in the right direction?
```Swift
func someRequest(completion: () throws -> Result<MoyaError, Moya.Response>) {
    provider.request(.zen) { result in
        completion(result)
    }
}
```

**Comment by lovesomeone** [comment]
@ninasaveljeva    Hi   I think you can wrapper or extension  SCLAlertView . 

 First  Just add a static var  ,such as ```static var isReadyShowAlert = false```   .

Second  When you call  ```  SCLAlertView().showError("Error", subTitle: message)```    you should replace it with   ```  if !SCLAlertView.isReadyShowAlert {
       SCLAlertView().showError("Error", subTitle: message)
       SCLAlertView.isReadyShowAlert = true
    }```   . 

The last   you should set "isReadyShowAlert" to false  when you cancell your Alert View. So you can extension SCLAlertView to achieve it.

**Comment by ninasaveljeva** [comment]
Thanks, guys. Sounds good. I'll try you decisions :)
