### ISSUE TITLE
Need a different header configuration than the default Multipart Upload configuration? 400 Status Code

### ISSUE THREAD

**Issue by jayvenavetics** [Moya/Moya#1430]
So the following works on Alamofire:

```swift
Alamofire.upload(multipartFormData: { multipartFormData in

    for (key, value) in fields {
        multipartFormData.append(value.stringValue.data(using: String.Encoding.utf8)!, withName: key)
    }
    
    multipartFormData.append(imageData, withName: "file", fileName: s3Filename, mimeType: "image/jpeg")
    
}, to: "https://avetics-tango.s3-ap-southeast-1.amazonaws.com", encodingCompletion: {
    encodingResult in
    }
```
However, when I try to replicate the same multipart upload on Moya I receive a 400 error with the following code:

```swift
case let .uploadPhoto(data, s3Filename, fields):
	let photoData = MultipartFormData(provider: .data(data), name: "file", fileName: s3Filename, mimeType: "image/jpeg")
	var multipartFormData = [photoData]
	for (key, value) in fields {
	    let keyAndValueData = MultipartFormData(provider: .data(value.stringValue.data(using: .utf8)!), name: key)
	    multipartFormData.append(keyAndValueData)
	}
	return .uploadMultipart(multipartFormData)
```

This is a successful request from using Postman:

![](https://i.imgur.com/mtqJMxO.png)

This is what I see in Xcode's console log:

![](https://i.imgur.com/6OLRyg8.png)

I think the wrong header configuration is the problem.

**Comment by sunshinejr** [comment]
Hey @jayvenavetics, are you sure that headers from Alamofire are different than in Moya? We don't really change anything from the request-side, because we actually leverage `Alamofire`'s `upload(multipartFormData:)`. Additionally, it's Alamofire that appends the `multipart/form-data` header, as it's enables multipart encoding of the data on both ends.
