### ISSUE TITLE
Optional request parameters 

### ISSUE THREAD

**Issue by asasdasasd** [Moya/Moya#1431]
I have read the example, but it seems that `.requestPlain` .`requestParameters(parameters: params, encoding: URLEncoding.default)` not exist
the moya version is 8.0.5

**Comment by SD10** [comment]
Hey @asasdasasd,
Those types are available in Moya 9.0. We're on Moya 10.0 now so I recommend you upgrade to the latest version 👍

**Comment by asasdasasd** [comment]
@SD10 
I use swift 3.0, can I use the latest version?

**Comment by SD10** [comment]
@asasdasasd You're using 3.0 or 3.2? I think you should be able to use Moya 9.0 but I'm not entirely certain.

**Comment by asasdasasd** [comment]
OK I will have a try

**Comment by SD10** [comment]
Hey @asasdasasd,
These are the [docs for Moya `8.0.5`](https://github.com/Moya/Moya/tree/8.0.5/docs) if you're unable to convert

**Comment by asasdasasd** [comment]
@SD10  upgrade failed, thanks for your docs
