### ISSUE TITLE
Carthage update hangs when fetching ReactiveSwift submodule

### ISSUE THREAD

**Issue by edulpn** [Moya/Moya#1433]
macOS High Sierra 10.13
Carthage version: 0.26.2
Cartfile:
```
github "Moya/Moya"
github "mac-cain13/R.swift.Library"
github "ReactiveX/RxSwift" ~> 3.0
github "Swinject/Swinject"
github "Swinject/SwinjectStoryboard" ~> 1.0.0
github "onevcat/Kingfisher" ~> 3.0
github "SnapKit/SnapKit" ~> 3.2.0
```

When trying to run ```carthage update --platform iOS``` it hangs (CPU spikes to 100%, coolers speed up. Left alone for enough time, will freeze up the entire UI) fetching ReactiveSwift submodule everytime:

```
*** Fetching R.swift.Library
*** Fetching Swinject
*** Fetching SnapKit
*** Fetching SwinjectStoryboard
*** Fetching Moya
*** Fetching RxSwift
*** Fetching Kingfisher
*** Fetching Result
*** Fetching Alamofire
*** Fetching ReactiveSwift
``` 

Commenting Moya on the Cartfile will result in SUCCESSFUL build, but will leave me network-less. Trying to ```carthage update Moya --platform iOS``` will result in the same behavior.

Is there any way to skip ReactiveSwift submodule fetch/checkout/build? I use RxSwift only, so it would result in quicker builds, too.
If not, is there any trick to make it pass through ReactiveSwift without hanging?

Thanks!

**Comment by edulpn** [comment]
Kind of found a way around...

I created a new folder somewhere else on my computer, created a new Cartfile, and added only ```github "Moya/Moya"```. Ran ```carthage update --platform iOS``` and it built with SUCCESS. I will try to just drag the generated frameworks from the new test folder to my project and see if it works.

I know this might have to be something weird with Carthage and not Moya (or it's submodules), so I'll probably try to ask there, but I'm pretty sure this shouldn't happen, as Carthage just checks code out from git repos and build them and is not aware of the "surrounding environment". Maybe I bumped into some weird cache issue?

Anyways, hope this, at least can help someone else.

**Comment by BasThomas** [comment]
Good to hear your issue is resolved and thanks for sharing your findings. 👍

**Comment by edulpn** [comment]
More details:
It all looks to gravitate around both Moya and RxSwift, not ReactiveSwift, being installed through Carthage. Suppressing either one from the Cartfile will result in successful build (which I think happens because Moya already has RxSwift as a submodule to make RxMoya work).

I'm good as long as both are already installed and working as intended, but this might impact someone else in some weird way.
