### ISSUE TITLE
Work thought proxy server

### ISSUE THREAD

**Issue by NBibikov** [Moya/Moya#1435]
Hello! Thank for great library! I have a question.
I using _RxMoya 10.0_. Can i sent request by custom proxy using _RxMoya_?

**Comment by AndrewSB** [comment]
try `Moya.rx.request`

**Comment by pedrovereza** [comment]
More details in [the docs](https://github.com/Moya/Moya/blob/master/docs/RxSwift.md).
Let us know if you still have questions 😉
