### ISSUE TITLE
Endpoint closure not adding http header fields anymore.

### ISSUE THREAD

**Issue by ivanmkc** [Moya/Moya#1440]
I was using endpoint closures to sign non-authenticating requests as described in the docs. It used to work in Moya 8.0.5, but since migrating to 10.0, it has stopped working. Everything else is working fine.

Mentioned here: https://github.com/Moya/Moya/blob/master/docs/Endpoints.md#from-target-to-endpoint
```swift
let endpointClosure = { (target: MyTarget) -> Endpoint<MyTarget> in
    let defaultEndpoint = MoyaProvider.defaultEndpointMapping(for: target)

    // Sign all non-authenticating requests
    switch target {
    case .authenticate:
        return defaultEndpoint
    default:
        return defaultEndpoint.adding(newHTTPHeaderFields: ["AUTHENTICATION_TOKEN": GlobalAppStorage.authToken])
    }
}
let provider = MoyaProvider<GitHub>(endpointClosure: endpointClosure)
```

My Cocoapod entry is:
```ruby
  pod 'Moya',   '~> 10.0'
```

I verified that it didn't work by using Charles to trace the network calls.

**Comment by ivanmkc** [comment]
Actually it seems it used to add it in the body but now it adds it into the HTTP header fields (as expected). Now the question is, how do I add body parameters using an endpointClosure?

**Comment by SD10** [comment]
Hey @ivanmkc, can you share your `TargetType` code please? I vaguely remembered what changed here but it's hard to keep track of all the different Moya versions in my head.

**Comment by ivanmkc** [comment]
I think I got it working now, by just modifying the task parameter for the TargetType to refer to a singleton. However, I was trying to avoid having the TargetType have a global reference like that, hence I was using a endpointClosure.

**Comment by heyjas0n** [comment]
I think we are running into the same issue except we are using a MultiTarget provider. Running out of ideas, it seems like the Authorization header never gets added. Any ideas?

```
let requestClosure = { (endpoint: Endpoint<MultiTarget>, done: @escaping MoyaProvider<MultiTarget>.RequestResultClosure) in
            var request: URLRequest?

            var accessToken: String
            accessToken = persistentData.getAccessToken()!

            do {
                request = try endpoint.urlRequest()
            } catch {
            }

            accessTokenProvider.getToken().subscribe(onNext: {accessToken in
                endpoint.adding(newHTTPHeaderFields: ["Authorization": "Bearer \(accessToken)"])
            }, onDisposed: {
                    done(.success(request!))
            }).disposed(by: disposeBag)

        }
```

**Comment by AndrewSB** [comment]
@heyjas0n you have a separate issue. You're using an async function inside the `requestClosure`. That isn't supported, you'll need to assign your accessToken synchronously inside the requestClosure. Let's not pollute this issue with your separate issue. If you still need help, please open a separate issue.

**Comment by AndrewSB** [comment]
@ivanmkc your issue sounds pretty serious. Can you show us the diff you applied to get the header to work?

**Comment by ivanmkc** [comment]
Sorry for the delayed reply. I had to add this hack at the end of the TargetType.parameters code:

`
//Sign endpoints
        if let currentSession = AuthenticationService.sharedInstance.session.value
        {
            switch self {
            case .LoginByEmail:
                break
            default:
                optionalParameters["u"] = currentSession.id
                optionalParameters["t"] = currentSession.token
            }
        }
`

**Comment by ivanmkc** [comment]
I think I see what happened. It used to add this to the body, but now it adds it to the headers (which seems to be the correct way). You can keep the issue closed.

**Comment by AndrewSB** [comment]
Ahh, I see.

Thanks for following up @ivanmkc!
