### ISSUE TITLE
Carthage : Moya requires at least osx 10.11

### ISSUE THREAD

**Issue by lucas34** [Moya/Moya#1441]
Hi,

As defined in podspec, the minimal deployment target is 10.10. But when using carthage the lib requires 10.11.

**Comment by sunshinejr** [comment]
Hey @lucas34, thanks for reporting the issue. You are right, our CocoaPods config requires 10.10, but from the quick look at our [xcodeproj](https://github.com/Moya/Moya/blob/master/Moya.xcodeproj/project.pbxproj#L968), it seems like we have deployment target for macOS on 10.11. Not sure why, but it _seems_ like a bug. Would you be up for changing this one? I think that it would require changes only in the xcodeproj, wherever we have `MACOSX_DEPLOYMENT_TARGET = 10.11`.

**Comment by BasThomas** [comment]
Do we need to target `10.11` for a reason though, or can we change the podspec to `10.10`?

**Comment by sunshinejr** [comment]
@BasThomas our podspec [already use 10.10](https://github.com/Moya/Moya/blob/master/Moya.podspec#L17), thus I believe that this is a bug that our Moya.xcodeproj uses 10.11 as a deployment target and it should be safe to fix.
