### ISSUE TITLE
How to customize JSONEncoder for Task.requestJSONEncodable?

### ISSUE THREAD

**Issue by evgeny-sureev** [Moya/Moya#1442]
I need a way to pass custom DateFormatter to dateEncodingStrategy, but it seems now it is impossible.

Moya version is 10.0.0.

**Comment by sunshinejr** [comment]
Hey @evgeny-sureev! You're right, right now you need to encode it yourself and pass as a data. But this could be a good addition to Moya: we could extend `Task` type to have an option with custom `JSONEncoder`. Would you be up for implementing the feature? [This PR](https://github.com/Moya/Moya/pull/1349/files) might be helpful as a reference, but I'm happy to answer all the questions you would have.

**Comment by sunshinejr** [comment]
That is merged and will be available in Moya 11.
