### ISSUE TITLE
Custom status code validation

### ISSUE THREAD

**Issue by amaurydavid** [Moya/Moya#1447]
I want to configure my `MoyaProvider` to treat status codes specifically  according to the target I'm requesting.
Ex: a target T1 is expected to return a 404 sometimes, it's catched by the app and treated like a 200 with an empty response.
Another target T2 is not expected to return 404.

So here is my problem: How can I configure my `MoyaProvider` to treat 404 from T1 as valid, and 404 from T2 as invalid?
Short answer: I have not found a way
Long answer: It's possible, but by changing a bit Moya

1. Using the Alamofire's validation
So far, the `Target`'s `validate` property only allows us to use the default Alamofire's validation, i.e validating codes in 200..<300
With Alamofire's `validate(statusCode:)` function, it's possible to customize the validation, but this function is not used by Moya. This issue could be easily addressed by replacing the `Target`'s boolean `validate` property with an enum allowing to use the default 200..<300 range or any custom array and then pass it back to Alamofire.

2. Not using the Alamofire's validation
The Moya's `Response` already contains some `filter()` functions but none allows us to provide an array of status code. In my case, to allow the 404 for T2 would mean to use a 200...404 range, allowing 401 402 and 403 codes which I don't want. A new `Response`'s `filter()` function taking an array as parameter would be needed.

Is all this reasoning correct, or am I missing something that allows me to solve my issue without modifying Moya?

**Comment by pedrovereza** [comment]
Hey @amaurydavid.

> A new Response's filter() function taking an array as parameter would be needed.

The issue seems very specific to your domain. Do you think you would be able to implement this function yourself as an extension on `Response`? Something like:

```swift
extension Response {
    public func filter(statusCodes: [Int]) throws -> Response {
        guard statusCodes.contains(statusCode) else {
            throw MoyaError.statusCode(self)
        }
        return self
    }
}
```

**Comment by SD10** [comment]
Hey @amaurydavid,

I have to agree with @pedrovereza on this one, it seems like a very domain specific issue. Moya already provides you with a way to filter an individual status code and a range of status codes.

A more complex approach that doesn't require having an array of passing codes:

```Swift
extension Response {
    public func filterStatusCodes(failureCodes: [Int], in range: ClosedRange<Int>) throws -> Response {
        guard !failureCodes.contains(statusCode) && range.contains(statusCode) else {
            throw MoyaError.statusCode(self)
        }
        return self
    }
}

let response = MoyaResponse()

response.filterStatusCodes(failureCodes: [401, 402, 403], in range: 200...404)


```

**Comment by amaurydavid** [comment]
Yep it does the job. But what about using all of the validation functions of Alamofire instead of restricting it to `validate()` (my first case) ? Is this something you're willing to do, or is it restricted on purpose ?

**Comment by AndrewSB** [comment]
what additional validate functions do you think would be useful in Moya?
