### ISSUE TITLE
Moya not catching network response after 8.0.x -> 10.0 migration

### ISSUE THREAD

**Issue by JohnTheBastard** [Moya/Moya#1450]
Moya version: 8.0.5 -> 10.0.0
ReactiveCocoa: 5.0.3 -> 6.0.2
P2.OAuth2: 3.0.3

We've upgraded Moya from version 8 and are having a hard time diagnosing a networking issue. Our authentication calls are handled with P2.OAuth2 and complete without error, but the rest of the traffic is routed through Moya. The calls that are routed through Moya hit the API server, have a response generated and returned there. We've verified the data is being returned through the networking tool Charles but Moya eventually just returns an error, typically -999 or -1001 (timeout). We've spent some time looking through issues here including #844, #1436 and #1440 but they don't seem to be the problem in our case. Any suggestions for further debugging? I'm running out of ideas.

**Comment by JohnTheBastard** [comment]
Okay, never mind. I found the problem. I missed a detail from the migration guides. I changed `.request` to `.requestPlain` when I needed `.requestParameters(parameters:encoding:)`.

**Comment by SD10** [comment]
Thank you for sharing how you resolved the problem 👍 I'm going to close this now
