### ISSUE TITLE
Unarchive response, which is archived with RLE

### ISSUE THREAD

**Issue by vuvkar** [Moya/Moya#1451]
Moya version - 9.0.0
Backend is Express (NodeJs) and sends responds archived with RLE.  Is there any implementation of unarchivation for this case.

**Comment by AndrewSB** [comment]
This would be a good question for Alamofire, I'm not sure

**Comment by AndrewSB** [comment]
This is out of scope for Moya, so I'm going to mark this is wontfix and close the issue. If you'd like to help other people who run into the same issue, you should post your findings here once you've solved the issue
