### ISSUE TITLE
How to print curl request in moya 10.0.0

### ISSUE THREAD

**Issue by lengocgiang** [Moya/Moya#1453]
Hi guys, I'm using moya 10.0.0, how can i print log to curl request

Please wrap code blocks in backticks, like so:
this's provider defaut init
```swift
       provider = MoyaProvider<FacilitiesTarget>(endpointClosure: endpointClosure)
```

**Comment by AndrewSB** [comment]
Add a NetworkLoggerPlugin to the plugins in your MoyaProvider initializer?

**Comment by lengocgiang** [comment]
@AndrewSB : could you show me your code?

**Comment by AndrewSB** [comment]
Take a look at the docs. [The plugin docs](https://github.com/Moya/Moya/blob/master/docs/Plugins.md) have what you need

**Comment by lengocgiang** [comment]
No your doc support moya < 10.0, this's 
```swift
provider = MoyaProvider<FacilitiesTarget>(endpointClosure: <#T##(FacilitiesTarget) -> Endpoint<FacilitiesTarget>#>, requestClosure: <#T##(Endpoint<FacilitiesTarget>, @escaping MoyaProvider.RequestResultClosure) -> Void#>, stubClosure: <#T##(FacilitiesTarget) -> StubBehavior#>, callbackQueue: <#T##DispatchQueue?#>, manager: <#T##Manager#>, plugins: <#T##[PluginType]#>, trackInflights: <#T##Bool#>)
```
How can i fill stubClosure,  requestClosure, callbackQueue, manager ?

**Comment by AndrewSB** [comment]
The documentation is current, and valid in 10.0. You can omit the other parameters, since they have default values

**Comment by lengocgiang** [comment]
@AndrewSB 👍  thanks you
