### ISSUE TITLE
Update Cocoapods Installation to include the current version

### ISSUE THREAD

**Issue by BasThomas** [Moya/Moya#1459]
Without this, a previous version could by installed when the specs repository is out of date locally.

See [here](https://github.com/Moya/Moya/issues/1456#issuecomment-343477875).

Ref #1456

**Comment by BasThomas** [comment]
In this case, we wanted to fix a silent install of an outdated version; you can read all the information on it [here](https://github.com/Moya/Moya/issues/1456). I think what you are trying to achieve is something different. :)

**Comment by alliamin** [comment]
@BasThomas Yes read it. Actually [this](https://github.com/Moya/Moya/issues/1456#issuecomment-343680257) is the part I was talking about specifically 😄 
I mean instead of updating Readme manually.

**Comment by BasThomas** [comment]
That’s interesting! Feel free to open a pull request, and we discuss it further there? :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by alliamin** [comment]
Sure, Will open the PR once the script is more ready.
Thanks BasThomas.
