### ISSUE TITLE
Does Moya support Https? So how do we do that?

### ISSUE THREAD

**Issue by ETmanwenhan** [Moya/Moya#1463]
Does Moya support Https? So how do we do that?

**Comment by pietrocaselani** [comment]
Yes, Moya and Alamofire supports HTTPS requests.
Are you facing any issues doing HTTPS request?
If you have problems with certificates you can look at [this example](https://github.com/Moya/Moya/issues/992#issuecomment-283331979)
Let us know if you need any help.
