### ISSUE TITLE
Response objct mapString() got nil

### ISSUE THREAD

**Issue by ZHDeveloper** [Moya/Moya#1466]
when i send a request i got here response:

```json
{
	"res": "1",
	"data": [{
		"mod_type": "1",
		"mod_name": "实物发货",
		"remind_count": "0"
	}, {
		"mod_type": "2",
		"mod_name": "审核订单",
		"remind_count": "0"
	}, {
		"mod_type": "4",
		"mod_name": "审核批准",
		"remind_count": "1"
	}, {
		"mod_type": "5",
		"mod_name": "签收货品",
		"remind_count": "0"
	}, {
		"mod_type": "6",
		"mod_name": "公司发货",
		"remind_count": "0"
	}, {
		"mod_type": "3",
		"mod_name": "我的提醒",
		"remind_count": "1"
	}],
	"msg": "获取数据成功"
}
```
i call the reponse obj' mapString(),however i got nil

**Comment by SD10** [comment]
Hey @ZHDeveloper, thanks for opening this issue. 
Can you try providing a `keyPath` to do the mapping or use `try` with a `do/catch` block to see where the error occurs?

It looks like Moya does the mapping without a specified keyPath like this:
```Swift
            // Key path was not provided, parse entire response as string
            guard let string = String(data: data, encoding: .utf8) else {
                throw MoyaError.stringMapping(self)
            }
            return string
```
I'd have to test but I wonder if that fails for JSON objects.

**Comment by ufosky** [comment]
Hi, @ZHDeveloper, are you ensure the response data is utf8 encoded.

**Comment by ZHDeveloper** [comment]
i change encoded,then resolve it~
