### ISSUE TITLE
Using Moya some questions

### ISSUE THREAD

**Issue by ETmanwenhan** [Moya/Moya#1467]
Using Moya some questions:
The task instance will be called twice? How to avoid multiple calls?

![e85ac832-07e9-4b31-975f-1c1caedf1139](https://user-images.githubusercontent.com/5837888/32935197-faa1f578-cba9-11e7-8fa8-d59d025c25d7.png)

**Comment by SD10** [comment]
Hey @ETmanwenhan,
Are there two requests or is task just being called twice? `TargetType` serves as a representation of the requests, therefore, Moya may need to access some of this information multiple times internally when creating a request.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ETmanwenhan** [comment]
@SD10 
Will that request the web multiple times? Is there a way to avoid it?

**Comment by SD10** [comment]
@ETmanwenhan No it will not, it looks to me like only one request is being logged in your debug output. Sometimes Moya just needs to access this information multiple times, it doesn't create multiple requests every time it is accessed, there are no side effects
