### ISSUE TITLE
Update ReactiveSwift dependency

### ISSUE THREAD

**Issue by eastsss** [Moya/Moya#1468]
there is 3.0.0 version released, how about updating Moya dependency to 3.0.0 as well? (this is the only thing which stops me from updating my project to new pod versions)

**Comment by SD10** [comment]
Hey @eastsss, this is definitely something we need to do. Do you know if 3.0.0 has any breaking changes that affect Moya? We would be open to a PR with the upgrade

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by larryonoff** [comment]
Sorry! Someone was quicker than I.

**Comment by larryonoff** [comment]
Will try to do PR tomorrow

**Comment by larryonoff** [comment]
done in #1470
