### ISSUE TITLE
Instances of Moya provider

### ISSUE THREAD

**Issue by arjunnaha** [Moya/Moya#1472]
Using RxSwift, I'm using this line on every ViewModel I create:
```swift
let provider = MoyaProvider<MyService>(plugins: [authPlugin])
```
I wondered if this was the best way to create a provider or there is a way to create a 'global' instance (or any better way!).

Cheers!

**Comment by SD10** [comment]
Hey @arjunnaha,
I don't think there is a right or wrong way to use a provider. It ultimately depends on the behavior you'd like to have. If you create a 'global' instance or something like a singleton then that provider will have an infinite lifetime. Personally, I prefer to tie the lifetime of the provider to the object using it

**Comment by arjunnaha** [comment]
Perfect! Thanks for your help.
