### ISSUE TITLE
set requestTimeoutClosure in Moya

### ISSUE THREAD

**Issue by starkite** [Moya/Moya#1478]
I'm using Moya 9.0.0 before.
when i update Moya 10.0, the code is not work.
error: Initializer for conditional binding must have Optional type, not '() throws -> URLRequest'

How can I fix it in Moya 10.0?
thanks

```swift
let timeoutInterval = 5
// MARK: - set request timeout
let requestTimeoutClosure = { (endpoint: Endpoint<NetworkClient>, done: @escaping MoyaProvider<NetworkClient>.RequestResultClosure) in
    
    guard let request = endpoint.urlRequest else { return }
    
    request.timeoutInterval = TimeInterval(timeoutInterval)
    done(.success(request))
}
```

**Comment by pietrocaselani** [comment]
Now `urlRequest` throws an error, so you have to handle error with the `try` keyword, something like that:
`guard let request = try? endpoint.urlRequest() else { return }`

or

```swift
do {
  let request = try endpoint.urlRequest()
} catch {
  done(Result.failure(error))
}
```

Let me know if you need any help.

**Comment by starkite** [comment]
@pietrocaselani 
thanks for your suggestion.
it's works for me now!

**Comment by umairalisyn** [comment]
Where do you add this closure to Moya provider?

**Comment by sunshinejr** [comment]
Hey @umairalisyn, this is a `requestClosure` parameter passed to `MoyaProvider` on initialization. Bear in mind that the code posted here is from few versions ago so it might need adjustments (e.g. the `Endpoint` is not generic anymore).

**Comment by BNazh** [comment]
static func defaultRequestMapping(for endpoint: Endpoint, closure: MoyaProvider.RequestResultClosure) {
        do {
            var urlRequest = try endpoint.urlRequest()
            urlRequest.timeoutInterval = 120
            closure(.success(urlRequest))
        } catch MoyaError.requestMapping(let url) {
            closure(.failure(MoyaError.requestMapping(url)))
        } catch MoyaError.parameterEncoding(let error) {
            closure(.failure(MoyaError.parameterEncoding(error)))
        } catch {
            closure(.failure(MoyaError.underlying(error, nil)))
        }
    }

**Comment by BNazh** [comment]
```
 static func defaultRequestMapping(for endpoint: Endpoint, closure: MoyaProvider.RequestResultClosure) {
        do {
            var urlRequest = try endpoint.urlRequest()
            urlRequest.timeoutInterval = 120
            closure(.success(urlRequest))
        } catch MoyaError.requestMapping(let url) {
            closure(.failure(MoyaError.requestMapping(url)))
        } catch MoyaError.parameterEncoding(let error) {
            closure(.failure(MoyaError.parameterEncoding(error)))
        } catch {
            closure(.failure(MoyaError.underlying(error, nil)))
        }
    }

```
