### ISSUE TITLE
How to perform request prior executing actual request

### ISSUE THREAD

**Issue by Blackjacx** [Moya/Moya#1484]
Hey there,

this is just a general question. For requests with the method post or put, i.e. these that change an object I need to read the respective object prior making the changing request. I want to implement this centrally by switching on the target and do the respective read request in advance and then do the changing request. For normal get requests I want to just pass through the original request.

How is that possible using Moya? My first guess is the endpoint closure, but isn't there another point in the pipeline where I can do this? In general I need a closure that provides me with the target and has a completion handler that executes the original request when called with a success parameter or  executes the failure closure of the original request in case of an error.

If I use the endpoint closure I need to identify the target the endpoint belongs to. How can I do this?

Thanks in advance :-)

**Comment by Blackjacx** [comment]
Hey @sunshinejr ,

I tried the request closure but couldn't figure out how to get back to the target from an endpoint. I also realised that my approach isn't that optimal. What I really need is to react on a certain error code (409 - Conflict), perform a refresh request to get the newest object I try to change and then retry the original changing request. I'll try to do that centrally for every request in the network layer where I do my error handling.

So you may close this issue.

PS: Cool would be to explain how to extract the target from an endpoint before closing this issue.

**Comment by tosbaha** [comment]
@Blackjacx 
> PS: Cool would be to explain how to extract the target from an endpoint (since this was my initial question) before closing this issue. This would be important when using the request closure and you need to switch on your TargetType there.

AFAIK, you can't extract target from Endpoint in requestClosure. Since requestClosure is called with
```swift
 requestClosure(endpoint, performNetworking)
```
Only thing you can do is try to identify `Target` by checking url, method, parameters etc of Endpoint which may lead to code smell. I think better solution is adding `Target` as parameter to  `requestClosure` You can also try to use EndpointClosure in which you have access to `Target`

**Comment by sunshinejr** [comment]
@Blackjacx @tosbaha is correct, you can't really get `Target` from `Endpoint` (I mean you can try to guess using properties, but that's not really reliable as it depends on `endpointClosure` and trying not to duplicate things). You would use `endpointClosure` for that one.
