### ISSUE TITLE
Handling of null values of respones?

### ISSUE THREAD

**Issue by realcarlos** [Moya/Moya#1486]
I'm mapping this JSON object:
```JSON
{
...
"completedDate": null,
...
}
```

```Swift
struct TaskResult : Mappable{
.....
let completedDate : Int?
}
return MyProvider.rx.request(.request005())
.debug()
.mapOptional(to: [TaskResult].self, keyPath: "data")
```
I got a nil mapping result ,any idea?

**Comment by BasThomas** [comment]
Hey @realcarlos. It seems like your issue is related to decoding your JSON; that being said, it’s hard to debug as you only provide a part of that JSON.
