### ISSUE TITLE
cancel Observable<ProgressResponse>

### ISSUE THREAD

**Issue by MartinPape** [Moya/Moya#1487]
Hi,

I'm using Moya 8.0.5 with RxSwift.
I need to be able to cancel a running network request created by an RxMoyaProvider and
I have not been able to find the request/object which provides an cancel() method.
My code to download files works well and I inform a display element through a delegate
about the progress.

This is my code (shortened):
```swift
//model (called mirrorModel)
let provider: RxMoyaProvider<MirrorAPI>
    
func media(url: String) -> Observable<ProgressResponse> {
   return self.provider.requestWithProgress(MirrorAPI(urlString: url))
}

//observing the download
let progress: Observable<ProgressResponse> = self.mirrorModel.media(url: "http://www.test.com/file1.txt")
_ = progress.subscribe { event in
  switch event {
    case .next(let progressResponse):
       //inform delegate about progress
    case .completed:
       // do something with download
    case .error(let error):
       print("Download media failed. Error: \(error)")
    }
```

I simple can't find the hook to cancel the call once it is running.
Many thanks for any advice here.

**Comment by evgeny-sureev** [comment]
Store subscription and dispose it:

```
let download = progress.subscribe(...)
// later
download.dispose()
```

**Comment by MartinPape** [comment]
Many thanks!
