### ISSUE TITLE
[stupid question]Hi, i'm wondering how you feel about my friend's project MoyaX(https://github.com/jasl/MoyaX)

### ISSUE THREAD

**Issue by zzz6519003** [Moya/Moya#1490]
https://github.com/jasl/MoyaX

**Comment by BasThomas** [comment]
Awesome! Feel free to add it to our list of [Community Projects](https://github.com/Moya/Moya/blob/master/docs/CommunityProjects.md).

**Comment by AndrewSB** [comment]
Not stupid at all 🙃

**Comment by zzz6519003** [comment]
still figuring out how that code work, by then i can proundly do my friend's a favor XD

**Comment by zzz6519003** [comment]
good job bot! @stale

**Comment by yalvinz** [comment]
i love you
