### ISSUE TITLE
Question about Moya response logging (log request too)

### ISSUE THREAD

**Issue by dtomicAZ** [Moya/Moya#1491]
Hi, I am using Moya 10.0.1

I have a question when logging failed requests.

Here is my code:

```
struct MyMoyaPlugin: PluginType {
  
  func prepare(_ request: URLRequest, target: TargetType) -> URLRequest {
    if (target as! AccessTokenAuthorizable).authorizationType == .none {
      return request
    }
    
    var request = request
    request.addValue(App.user.authToken ?? "", forHTTPHeaderField: "Authorization")
    return request
  }
  
  func didReceive(_ result: Result<Response, MoyaError>, target: TargetType) {
    SVProgressHUD.dismiss()
    
    switch result {
      case .success(let response):
        if response.statusCode != 200 {
          let info = ["Response": response.debugDescription, "Data": String(data: response.data, encoding: .utf8) ?? ""]
          Logger.logError(type: .responseError(nil), info: info , code: response.statusCode)
        }
      break
      case .failure(let error):
        let info = ["Response": result.debugDescription, "Error":error.errorDescription ?? ""]
        Logger.logError(type: .networkFailure, info: info, code: error.response?.statusCode ?? 0)
      break
    }
    
    if let response = result.value {
      if response.statusCode == 403 {
        App.delegate.logOut()
      }
    }
  }
}
```

The question is, is there any way when logging response (in didReceive func), to log fired request too ?

**Comment by sunshinejr** [comment]
Hey @dtomicAZ. You can take a look at our [NetworkLoggerPlugin](https://github.com/Moya/Moya/blob/master/Sources/Moya/Plugins/NetworkLoggerPlugin.swift#L28-L34), which basically logs both requests/responses - maybe it has all the functionalities you need 😉  

This plugin logs the request in `willSend` method. You could log it in the `didReceive` as well, then you would use `response.request` to get underlying request of a response (see our [Response model](https://github.com/Moya/Moya/blob/master/Sources/Moya/Response.swift#L7)). 

Please let me know if any of these is helpful to you!

**Comment by dtomicAZ** [comment]
@sunshinejr awesome, `response.request` did the trick, thank you.
