### ISSUE TITLE
AccessTokenPlugin hidden coupling

### ISSUE THREAD

**Issue by biboran** [Moya/Moya#1492]
I am using `AccessTokenPlugin` to implement authorization in our app, and I just updated Moya from **8.0.2** to **10.0.1** and was surprised to see authorization stop working. 

After looking at the changelogs and Moya source files I found that decision to append an authorization header is now decided by [optionally type casting target](https://github.com/Moya/Moya/blob/c29fb183ed917c5fb53e71260abe02ee32668a66/Sources/Moya/Plugins/AccessTokenPlugin.swift) (line 57) to `AccessTokenAuthorizable`. This is surprising because subtype casting is not something Moya uses actively as a pattern and is not something I think Moya should adopt. It introduces unnecessary hidden coupling, breaks encapsulation, and makes it impossible to understand the behavior of `AccessTokenPlugin` without looking at the documentation (which I didn't find) or the source code.

I think at the very least Moya should use an `assert()` to warn its users in non-production mode that they are using `AccessTokenPlugin` and their `Target` doesn't conform to `AccessTokenAuthorizable`. However, I believe a better solution would be to pass a `AccessTokenAuthorizationSource` in the `AccessTokenPlugin` ctor, so that `AccessTokenPlugin` will be able to ask source wether it's supposed to append an authorization header for this particular target. This way the decision will be delegated to the source which can be proxy, target, or anything else. If users of the plugin choose to break encapsulation and cast their target to some marker interface, they can do it in the source.

**Comment by SD10** [comment]
Hey @biboran, thanks for submitting this issue 😃

A few of my thoughts:
- The casting behavior was present in [Moya 8.0.2](https://github.com/Moya/Moya/blob/f398a5a468e78bb7cceb74685b687520159e06b1/Sources/Moya/Plugins/AccessTokenPlugin.swift#L54).
- An `assert()` could work, but plugins are applied through the Moya provider, which can accept multi targets and not all targets are `AccessTokenAuthorizable`.

> It introduces unnecessary hidden coupling, breaks encapsulation, and makes it impossible to understand the behavior of AccessTokenPlugin without looking at the documentation (which I didn't find) or the source code.

I do agree it would be quite difficult to infer this behavior without looking at the documentation. You can find the documentation for the `AccessTokenPlugin` [here](https://github.com/Moya/Moya/blob/master/docs/Authentication.md).

Could you help me better understand what kind of problem you ran into before we discuss adding an `AccessTokenAuthorizationSource`? 

The plugin is already getting quite complex, due for a refactor in #1283, and this introduces some coupling I'm not fond of 😕

**Comment by biboran** [comment]
Hi @SD10! Thanks for a quick response!

Basically the problem that I ran into was that requests authorization stopped working (the header was not appended). I didn't even know about the existence of casting behavior but in **8.0.2** it didn't interfere with designated business logic of `AccessTokenPlugin` in my case because I never adopted `AccessTokenAuthorizable`. Isn't it logical to assume that `AccessTokenPlugin` will authorize your requests by default if it doesn't declare an authorization strategy mechanism in the ctor?

> plugins are applied through the Moya provider, which can accept multi targets and not all targets are AccessTokenAuthorizable.

Could you please elaborate on that? Do you mean that one `TargetType` supplied for `MoyaProvider` can address different resources which may or may not require different type of authorization heading?

**Comment by SD10** [comment]
@biboran After comparing the **8.0.2** and **10.0** sources I can see the issue clearly. 

- In Moya **10.0** we return early using a `guard` statement so the "Authorization" header is never applied. 
- In Moya **8.0.2** we use an `if let` statement which continues to execute the scope after the failed cast.

I now remember I made these changes because I didn't think we should opt into any default behavior. 

I wanted users to explicitly have to conform to `AccessTokenAuthorizable` when using the `AccessTokenPlugin`.

**Comment by biboran** [comment]
@SD10 right, so users of the plugin **must** declare their intention through `AccessTokenAuthorizable` somewhere if they choose to use `AccessTokenPlugin`. It seems that class casting is not a good solution in this case (imho in any case).

Going back to my original suggestion: if changing `AccessTokenPlugin` is not something potent for the upcoming Moya release, I think `assert()` will suffice but there are definitely better ways to implement `AccessTokenPlugin` without hiddenly breaking `TargetType` contract.
