### ISSUE TITLE
Http Method Post parameters are empty so getting false response from server

### ISSUE THREAD

**Issue by swabzz** [Moya/Moya#1493]
Hi,

I might be asking basic question here but i am stuck in post parameterised http request.

Moya (9.0.0)
Moya-ObjectMapper (2.4.2)

1. ParameterEncoding method is not getting called.
2. Always getting false response (Parameters might not be adding into body?)
3. tried adding header as below but nothing helps

```swift
let HEADER_API_VERSION = "Content-Type: application/x-www-form-urlencoded" 
 // The headers to be used in the request.
    public  var headers: [String: String]? {
        return ["HEADER_API_VERSION": HEADER_API_VERSION]
    }

```

```swift
 public var parameterEncoding: ParameterEncoding {
        return URLEncoding.default
    }

// MARK: - Endpoint Closure
let endpointClosure = { (target: MoyaEndpoints) -> Endpoint<MoyaEndpoints> in
    let endpoint: Endpoint<MoyaEndpoints> = Endpoint<MoyaEndpoints>(url: url(target), sampleResponseClosure: {.networkResponse(200, target.sampleData)}, method: target.method, task: target.task, httpHeaderFields: target.parameters as? [String : String])
    // Sign all non-authenticating requests
    
    // Headers
    return endpoint.adding(newHTTPHeaderFields: target.headers!)    
}

```

I gone through many issues related to encoding but did not get any solution for my case.

Please suggest what change in my code should be made to get it running?

Thanks!
<img width="1018" alt="screenshot at dec 07 11-21-00" src="https://user-images.githubusercontent.com/15198865/33700754-1801dfe2-db41-11e7-95e3-94462ecc8f77.png">

**Comment by filograno** [comment]
In Moya 9.0 `parameterEncoding` property is not used but you have to use `task` property.
For headers use `headers` property.
For more information refer to the migration guide:

[https://github.com/Moya/Moya/blob/master/docs/MigrationGuides/migration_8_to_9.md](url) 

and:

[https://github.com/Moya/Moya/blob/1d4700baca59c766d1c3f8f3ab520633442f0e09/docs/Examples/Basic.md](url)
