### ISSUE TITLE
Incorrect retainment model in RxSwift extension for MoyaProvider. 

### ISSUE THREAD

**Issue by biboran** [Moya/Moya#1496]
Starting with Moya **9.0.0** 2efc441c0 `RxSwift` extension for `MoyaProvider` no longer retains self when converting to an observable by `Reactive<MoyaProvider>.request`. Such retainment

- is inconsistent with standard `MoyaProvider.request` behavior which doesn't oblige you to retain the provider object and guarantees that the completion handles will be executed even if the provider is deallocated.
- is inconsistent with previous behavior of `RxMoyaProvider` which you also didn't have to retain
- is inconsistent with RxSwift general retainment model which implies that all resources must be help by the chain until `DisposeBase` relieves them. For example `URLSession` extension in `RxCocoa` [line 37](https://github.com/ReactiveX/RxSwift/blob/f043778214c8f182018ccdfbf7f440edbe0aecc8/RxCocoa/Foundation/URLSession%2BRx.swift)

The major problem we had with this is that we use decoration for nearly all of the observable chains inside the project and since Swift doesn't support true generic protocols and they have to be type erased, so the only solution is to retain `MoyaProvider` and to retain whoever holds the provider (which in our case is not a controller). <s>`rxRequest` doesn't necessarily have to retain self, I think capturing `request` instead of `[weak self]` should be enough. </s> (there is no difference)

**Comment by SD10** [comment]
@biboran I believe this has already been discussed and is behaving as intended. 
See #1267 #1380 #1311 #905
