### ISSUE TITLE
Anyway cancel all requests?

### ISSUE THREAD

**Issue by Natai** [Moya/Moya#1497]
How can i cancel all my moya requests?

**Comment by juliengdt** [comment]
Hey @Natai ,

I doubt it's possible with Moya directly (need investigation). But as Moya is a layer of AF, you can do something like:

```
let sessionManager = Alamofire.SessionManager.default sessionManager.session.getTasksWithCompletionHandler { dataTasks, uploadTasks, downloadTasks in      
    dataTasks.forEach { 
        $0.cancel() 
    } 
    uploadTasks.forEach { 
        $0.cancel() 
    } 
    downloadTasks.forEach { 
       $0.cancel() 
    } 
}
```

This works only if you didn't override the AF manager used by your Moya instance, obviously.

But cancelling request by using Moya can be a good feature I think

Cheers
