### ISSUE TITLE
Step by step sample how to run the examples?

### ISSUE THREAD

**Issue by glennposadas** [Moya/Moya#1499]
Hi there, I've never used carthage before, and I believe in your documentation on how to use the examples, just run `pod install`. Carthage is giving me errors.  Thanks.

**Comment by SD10** [comment]
@glennposadas Try running `carthage bootstrap`

**Comment by glennposadas** [comment]
Thanks a lot! I had no choice but to try out Carthage. It's okay now.

**Comment by glennposadas** [comment]
Ooh, now it says Image not found :/

**Comment by BasThomas** [comment]
Can you post the whole console log?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by glennposadas** [comment]
It's not a big deal though. :) The error or rather crash happens both on my iPhone 5S with iOS 10+ and on my iPhone 7plus iOS 11+.

When I made my own sample and integrated Moya with Cocoapods, I didn't experience such crash. So I think it's okay and not a big deal. Thank you!
