### ISSUE TITLE
Failure request when put app in foreground.

### ISSUE THREAD

**Issue by dtomicAZ** [Moya/Moya#1501]
In my app I show message to user when request fails.

Request can fail (in my case) for 3 reasons.
1) response status code is different from 200,
2) json parsing can fail,
3) request can timeout (Moya failure case gets executed)

I have problem with 3, when request timeouts.

Problem shows up when I open app (some requests gets fired) and immediately(before requests got finished) put app in background. And then after 30s( I set request timeout to be 30s) I open app again, and I see message in my app showing that request has failed.

I don't know how to solve this, maybe there is some way to cancel all requests when putting app in background ?

**Comment by AndrewSB** [comment]
Hey @dtomicAZ, great question! I want to make sure I understand exactly what you're trying to do before answering. Are you saying you *want* to cancel all requests as soon as your app is backgrounded, or you want to try to have requests succeed after the app has been backgrounded?

**Comment by dtomicAZ** [comment]
Hi, @AndrewSB 

For me better would be 1. solution, to cancel all requests as soon as my app is backgrounded, thank you.

**Comment by AndrewSB** [comment]
I'd do this by
1. storing a list of all the in flight requests
2. Iterating through and cancelling each of those requests in my `AppDelegate`, in the `appWIllBackground` delegate method or something similar

**Comment by dtomicAZ** [comment]
@AndrewSB Thank you for info.

I found another solution, to dismiss error messages in applicationWillEnterForeground.
I am using RMessage lib for showing message alert, so this was one line of code:
`RMessage.dismissActiveNotification()`

**Comment by vbicer** [comment]
@AndrewSB I have same problem and I wanna  have requests succeed after the app has been backgrounded. Do you have any idea how to accomplish this.
