### ISSUE TITLE
Cannot convert value of type '(MoyaTest) -> Endpoint<MoyaTest>' to expected argument type '(_) -> Endpoint<_>'

### ISSUE THREAD

**Issue by rainedAllNight** [Moya/Moya#1512]
with the latest version 10.0.0

![c687bec2-dad7-44aa-a740-8c1b8c26a78a](https://user-images.githubusercontent.com/16357931/34251369-d36bc4e8-e67a-11e7-82b6-75201b7f8b78.png)

**Comment by AndrewSB** [comment]
@rainedAllNight it's hard to tell exactly what's wrong, but can you add a type annotation to the line where you declare `endpointClosure`? So something like

```swift
let endpointClosure: Moya.EndpointClosure<MoyaTest> = ...
```

that might lead to swift giving a more helpful error message
