### ISSUE TITLE
FOr status code 400 returning 200 status code

### ISSUE THREAD

**Issue by iOSUser110** [Moya/Moya#1515]
even for responce from server is 400 , it if enter into the success and status code responce as 400.
PLease any one can reply on this  ASAP.??
and giving as recived empty responcse

**Comment by SD10** [comment]
Hey @iOSUser110,
Are you using `validate` on your `TargetType`? You should try filtering the response codes using one of Moya’s methods on `Moya.Response`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
