### ISSUE TITLE
Using Moya.Method face " __T09Alamofire10HTTPMethodON"

### ISSUE THREAD

**Issue by gb-6k-house** [Moya/Moya#1517]
I'm facing an Compile error within **Swift 4.0 and Moya 9.0.0** 。when I declare an property for a **class** or **enum** as **Moya.Method** type  in this way

```swift
public class MyTest {
    public var method: Moya.Method = .get
}
```
i got an compile error like this:
"Undefined symbols for architecture x86_64:
  "__T09Alamofire10HTTPMethodON", referenced from:
      l_get_field_types_MyTest in YSTargetRequestable.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)"
How can I use？

**Comment by AndrewSB** [comment]
Have you used Moya successfully before? Can you share now you've imported Moya into your project and any relevant lock files?

**Comment by gb-6k-house** [comment]
I didn't face this issue in Swift 3.2 and  Moya 8.0.5 , just when i update to Swift 4.0, i have this problem.
@AndrewSB

**Comment by SD10** [comment]
@gb-6k-house How are you installing Moya?

**Comment by gb-6k-house** [comment]
I used CocoaPods.  It was seems building successful with Moya 10.0.1 now, and  well  done when  i change to use Moya 9.0 again .  Something wrong  with CocoaPods installing  I guess . However, thanks all @AndrewSB @SD10

**Comment by SD10** [comment]
Thanks for sharing how you resolved this @gb-6k-house 👍
