### ISSUE TITLE
uploadMultipart([MultipartFormData])

### ISSUE THREAD

**Issue by ETmanwenhan** [Moya/Moya#1519]
Upload the avatar and submit the parameters, but the avatar is optional. How can I deal with this situation with Moya. 

When the avatar is nil, the server requests the method to be 
> multipart/form-data

```swift
 case .regAdd(_ , let avatar):
            
            if let avatarData = avatar {
                let data = MultipartFormData(provider: .data(avatarData), name: "img", fileName: "img.jpg", mimeType: "image/jpeg")
                let multipartData = [data]
                return .uploadCompositeMultipart(multipartData, urlParameters: self.parameters!)
            } else {
                return .requestParameters(parameters: self.parameters!, encoding: URLEncoding.default)
            }
```

```swift
public var headers: [String : String]? {
    
        switch self {
        case .regAdd:
            return ["Content-type": "multipart/form-data"];
        default:
            return nil
        }
    }
```

**Comment by ETmanwenhan** [comment]
When using the following method to request a network, appears in the code, how do you set the encoding format for the request parameters.

> uploadCompositeMultipart

**Comment by ETmanwenhan** [comment]
@BasThomas 
Does MultipartFormData create a default object to solve the problem?

**Comment by sunshinejr** [comment]
Hey @ETmanwenhan, sorry for the late response. If you really need the `multipart/form-data`, you can just use a normal `uploadMultipart` with empty data. There was a similar use-case to yours in #1152.

Let me know if it helped!
