### ISSUE TITLE
Remove generics of Endpoint

### ISSUE THREAD

**Issue by zhongwuzw** [Moya/Moya#1524]
I want to make a `PR` to remove generics of `Endpoint`. The reason based on:

`Endpoint` is a concrete class, and store some basic info about request. I cannot found any reason that `Endpoint` need uses generics.

Maybe my thoughts is one-sided, please let me know if it is.:beers::beers:

**Comment by AndrewSB** [comment]
It doesn't seem like a bad idea to me, but I can't imagine why the person who implemented the generics in Endpoint would do so for no reason. I think the easiest way to see why it's required is by attempting the PR. Maybe you'll find out if/why it can't be removed while attempting the change

**Comment by SD10** [comment]
@zhongwuzw I think @AndrewSB makes a good suggestion here. You can try and remove it by submitting a PR for this change. However, I can't guarantee it will be accepted.

**Comment by SD10** [comment]
#434 Is related

**Comment by sunshinejr** [comment]
Closing, this one is already ⛵️in Moya 11.0.0-beta.2 🎉
