### ISSUE TITLE
Parameter

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [Moya/Moya#1526]
Version : 10.0.1

```
var parameters : [String:Any]? {
        switch self {
        case .register(let firstName, let email, let password, let mobileNumber):
            return ["user_fname":firstName,
             "user_email":email,
             "user_password":password,
             "user_mobile_no":mobileNumber]
        }
    }
```
currently parameter is going as [String:Any]  but my requirement is to send parameter in JSON format. 
Like Following.

```swift

{
  "user_fname": "TestFirstName",
  "user_email": "test@email.com",
  "user_password": "Test@123",
  "user_mobile_no": "9876543210"
}

```

I am not getting correct response by sending parameters as `[String:Any]`.

When testing in `Postman`, sending parameter as `raw` in Postman, It is working fine.

I want to implement same thing using `Moya`.

How do I achieve?

**Comment by BasThomas** [comment]
But it is in JSON format - your JSON is simply a Dictionary, which is what `[String: Any]` is, too. What does not work? What error do you get?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
@Rashesh-Bosamiya is the `mobileNumber` associated value a `String`?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Rashesh-Bosamiya** [comment]
@SD10 , Yet `mobileNumber` is a `String` type.

**Comment by Rashesh-Bosamiya** [comment]
@BasThomas, Error is coming from server. Server is not able to get parameters, that I am sending.

I tested the same thing in `Postman`.

The need is sending `Parameter` is `raw`.

See the `Postman` screenshot.

In short, I want to send `Parameter` as `raw`.

![screen shot 2018-01-05 at 9 32 43 am](https://user-images.githubusercontent.com/19154948/34595128-77d12948-f1fb-11e7-9af4-e6dcd30d2d15.png)

**Comment by SD10** [comment]
I think I know what’s happening. @Rashesh-Bosamiya can I see your `TargetType` code? We don’t use the `parameters` property in Moya 9+. We flattened this into the `Task` property. Check the migration guide for more information if my hypothesis is correct.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Rashesh-Bosamiya** [comment]
Following is my `TargetType` code.

```
enum MyServerAPI {
    case login(email:String,password:String)
    case register(firstName:String,email:String,password:String,mobileNumber:String)
    case forgotPassword(email:String)
    case checkUniqueEmail(email:String)
}

extension MyServerAPI : TargetType {
    
    var parameters : [String:Any]? {
        switch self {
        case .login(let email, let password):
            return ["user_email":email,
                    "user_password":password]
        case .register(let firstName, let email, let password, let mobileNumber):
            return ["user_fname":firstName,
             "user_email":email,
             "user_password":password,
             "user_mobile_no":mobileNumber]
        case .forgotPassword(let email):
            return ["user_email":email]
        case .checkUniqueEmail(let email):
            return ["user_email":email]
        }
    }
    
    var parameterEncoding : Moya.ParameterEncoding {
        return URLEncoding.httpBody
    }
    
    var baseURL: URL {
        return URL(string: "http://someURL.com/page/")!
    }
    
    var path: String {
        switch self {
        case .login:
            return "web_user_login"
        case .register:
            return "web_add_user"
        case .forgotPassword:
            return "web_user_forgot_password"
        case .checkUniqueEmail:
            return "web_check_user_email"
        }
    }
    
    var method: Moya.Method {
        return .get
    }
    
    var sampleData: Data {
        return Data()
    }
    
    var task: Task {
        return .requestPlain
    }
    
    var headers: [String : String]? {
        return ["Content-Type":"application/json"]
    }
}
``` 

Please correct, If anything seems wrong.

**Comment by SD10** [comment]
@Rashesh-Bosamiya Here is the [migration guide](https://github.com/Moya/Moya/blob/master/docs/MigrationGuides/migration_8_to_9.md).

You need to change `.requestPlain` to `.requestParameters(parameters:encoding)`
You can check out the docs for [TargetType here](https://github.com/Moya/Moya/blob/master/docs/Targets.md).

**Comment by Rashesh-Bosamiya** [comment]
Thank you very much 😃
