### ISSUE TITLE
URL to Demo is incorrect. 

### ISSUE THREAD

**Issue by LipYoung** [Moya/Moya#1528]
This doc's `Demo` url is failure.Doc's address is https://github.com/Moya/Moya/blob/master/docs/Examples/MultiTarget.md and https://github.com/Moya/Moya/blob/master/docs_CN/Examples/MultiTarget.md

**Comment by BasThomas** [comment]
Thanks for reporting @LipYoung. Would you be interested in fixing this and opening a pull request?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by LipYoung** [comment]
@BasThomas Thanks your invite.but i dnot konw how to fix it.so sorry.

**Comment by BasThomas** [comment]
Hey @LipYoung - I've already opened a pull request for this - #1551. 👍

**Comment by LipYoung** [comment]
@BasThomas I see it, and read sunshinejr's content.Thank you again.Good job.
