### ISSUE TITLE
Update to RxSwift 4.1

### ISSUE THREAD

**Issue by lucas34** [Moya/Moya#1530]
Hi,

RxSwift just recently released a new version aka 4.1. Current dependency is pointing to 4.0.
I think we can considerer upgrading the dependency to 4.1 for the next release (11.0). If it's not too late.

I upgraded my project and base on the release note we should not have any breaking changes.

I can make a PR by updating both podfile and cartfile. Should I target the PR to branch 'master' or 'development' ?
  

Need to update:
- [x] Podfile
- [x] Cartfile and Cartfile.resolved
- [x] Package.Swift and Package.resolved

**Comment by SD10** [comment]
Hey @lucas34, I think `development` is the best place to submit this change.
