### ISSUE TITLE
how to call previous api on authentication failure?

### ISSUE THREAD

**Issue by Mridul56** [Moya/Moya#1536]
I am using Moya 8.0.0.

How do i call back previous api?

**Scenario** : I have to call generate token api if any api gives token expiry code for token and after that i have to call the previously called api again which has responded me token expiry code. 

Is there any way to handle this scenario in Moya or do i have to write my custom logic for it ?

Thanks in advance

**Comment by pietrocaselani** [comment]
Hi @Mridul56 
There is some other issues about retrying requests when auth fails. Please, take a look at
[How to add extension to retry with OAuth?](https://github.com/Moya/Moya/issues/1402)
[Suclass MoyaProvider for token refreshing](https://github.com/Moya/Moya/issues/1510)
[Creating a PluginType to handle request reauthentication](https://github.com/Moya/Moya/issues/744)
[Can I re-throw Moya error or how to process errors of several async requests](https://github.com/Moya/Moya/issues/1429)
[[Help] OAuth2 Authentication using Moya](https://github.com/Moya/Moya/issues/1436)

Let us know if you need any help.

**Comment by AndrewSB** [comment]
@pietrocaselani that was a great answer. We should investigate if we can start sorting our knowledge base better to add a note to the ISSUE_TEMPLATE to check some sort of frequently asked issue section.
