### ISSUE TITLE
How to provide SSL Pinned certificates for NSURLSession in Moya?

### ISSUE THREAD

**Issue by inforeqd512** [Moya/Moya#1538]
Hi, 
How to provide SSL Pinned certificates for NSURLSession in Moya?

**Comment by NarenLK** [comment]
Get the certificate by  **SecCertificateCreateWithData**. Then use  **ServerTrustPolicy.pinCertificates** to validate the server trust. The server trust is considered valid if one of the pinned certificates match one of the server certificates. Finally return the **Manager** object
