### ISSUE TITLE
Provide mock data for success and error response for the same request

### ISSUE THREAD

**Issue by inforeqd512** [Moya/Moya#1539]
Hi, 

This is a general question as to when providing sampleData how do we provide samples for success and error cases?

**Comment by SD10** [comment]
Hey @inforeqd512,
Your `MoyaProvider` can be initialized with an [`endpointClosure`](https://github.com/Moya/Moya/blob/master/docs/Providers.md#endpointclosure) which is responsible for mapping the `TargetType` to a concrete `Endpoint`. 

One of the properties of `Endpoint` is `sampleResponseClosure` which is responsible for returning a `EndpointSampleResponse`, which is an enum consisting of the cases:

- `case networkResponse(Int, Data)`
- `case response(HTTPURLResponse, Data)`
- `case networkError(NSError)`

You have access to the `TargetType` inside of the `endpointClosure`, so you can use this as an access point to return different `sampleResponseClosures`.
