### ISSUE TITLE
Modifying Task.uploadMultipart through endpointClosure has no effect

### ISSUE THREAD

**Issue by seasox** [Moya/Moya#1546]
I'm trying to add authentication data (username/password) to an uploadMultipart task. First thing I tried was modifying `URLRequest.httpBody` in my authenticator plugin in `PluginType.prepare(_:target:)`, but this doesn't work for uploadMultipart tasks. Next, I tried modifying target.task in an endpointClosure like this:
```swift
        let endpointClosure: ((T) -> Endpoint<T>) = { target in
            var outtask = target.task
            if case .uploadMultipart(let multipart) = outtask {
              outtask = .uploadMultipart(multipart + [ /* Add authentication multipartData here */ ]
            }
            return Endpoint(url: target.path.absoluteString,
                            sampleResponseClosure: { .networkResponse(200, target.sampleData) },
                            method: target.method,
                            task: outtask,
                            httpHeaderFields: target.headers)
        }
```
This doesn't work either, since, if I understand MoyaProvider+Internal correctly, the original target gets passed to `performRequest(_:request:callbackQueue:progress:completion:endpoint:stubBehavior:)` alongside `endpoint`. Is there a way to modify multipart data outside of `TargetType` in Moya 10.0.1? Thanks in advance!

**Comment by SD10** [comment]
> Is there a way to modify multipart data outside of `TargetType` in Moya 10.0.1?

@seasox Why are you looking to modify the request outside of `TargetType`? Is it because you are trying to reuse authentication on every request? 

Have you considered creating a [plugin](https://github.com/Moya/Moya/blob/master/docs/Plugins.md)?

> Moya plugins are used to modify requests and responses or perform side-effects. A plugin is called: 

> - (prepare) after Moya has resolved the TargetType to a URLRequest. This is an opportunity to modify the request before it is sent (e.g. add headers).

**Comment by sunshinejr** [comment]
Hmm, it's strange, appending it in `endpointClosure` should just work. Can you confirm for sure that it doesn't, @seasox?

**Comment by SD10** [comment]
> This doesn't work either, since, if I understand MoyaProvider+Internal correctly, the original target gets passed to:
performRequest(_:request:callbackQueue:progress:completion:endpoint:stubBehavior:) 
alongside endpoint

https://github.com/Moya/Moya/blob/e212f6e638fa6383f19537a89a8a647b7120c0b1/Sources/Moya/MoyaProvider%2BInternal.swift#L93

@sunshinejr He could be correct. It looks like the request is being sent with the original `target.task`. I think switching on `endpoint.task` would be better?
