### ISSUE TITLE
Upgrading from Moya 8.0 to 10.0 causes tests to no longer run properly.

### ISSUE THREAD

**Issue by minuscorp** [Moya/Moya#1554]
I'm using Moya 10.0.1 installed through CocoaPods. I'm upgrading my Network layer to Moya 10.0 from 8.0. I've read all the migration documentation regarding the migration between versions.

The problem is the following. I had a test suite that relies on protocol extensions to load the desired `Provider` in function of the kind of build settings as the following: 

```swift
public var provider: MoyaProvider<Service> {
        let endpointClosure = { (target: Service) -> Endpoint<Service> in
            let defaultEndpoint = MoyaProvider.defaultEndpointMapping(for: target)
            if let userTarget = target as? UserTarget {
                switch userTarget {
                case .login(_, _, _), .register(_), .lostPassword(_):
                    return defaultEndpoint
                default:
                    guard let token = UserDefaults.standard.string(forKey: SessionManager.shared.configuration.userDefaultsTokenKey) else {
                        return defaultEndpoint
                    }
                    return defaultEndpoint.adding(newHTTPHeaderFields: ["token": token])
                }
            }
            guard let token = UserDefaults.standard.string(forKey: SessionManager.shared.configuration.userDefaultsTokenKey) else {
                return defaultEndpoint
            }
            return defaultEndpoint.adding(newHTTPHeaderFields: ["token": token])
        }
        #if DEBUG
            if (NSClassFromString("XCTest") != nil) {
                return MoyaProvider<Service>(stubClosure: { _ -> StubBehavior in return .delayed(seconds: 1) }, plugins: [NetworkLoggerPlugin(verbose: true, responseDataFormatter: JSONResponseDataFormatter)])
            }
            else {
                return MoyaProvider<Service>(endpointClosure: endpointClosure, plugins: [NetworkLoggerPlugin(verbose: true, responseDataFormatter: JSONResponseDataFormatter)])
            }
        #else
            return MoyaProvider<Service>(endpointClosure: endpointClosure)
        #endif
    }
```

This code was working on Moya 8.0, I've debugged with the new 10.0 version, the desired `Provider` is loaded (the one which produces the `.delayed(1)` stubbing behavior) but when the request is made no calls are made to `sampleData` in the `TargetType`.
Am I missing something in the configuration that has been changed about the testing behavior in the library or is this a real bug?

Thank you:)

BTW, this is the actual test using RxSwift extensions.

```swift
SessionManager.shared.service.activity.activity(withId: 1449319201383, source: .internet)
                    .observeOn(MainScheduler.instance)
                    .asObservable()
                    .subscribe(onNext: {
                        _activity in
                        activity = _activity
                    })
                    .disposed(by: self.disposeBag)
                
                expect(activity).toEventuallyNot(beNil(), timeout: 5)
                expect(activity.id) == 1449319201383
```
Which is using an underlying function who calls to `return self.provider.rx.request(.detail(id: id))` 

It's curious that debugging this, the `request` function, [here](https://github.com/Moya/Moya/blob/7b799cea2dfd1cbaafca308cd6f96bcfd12da894/Sources/Moya/MoyaProvider.swift#L110), is never being called.

**Comment by sunshinejr** [comment]
Hey @minuscorp, thanks for the issue.

Please take a look at #1267, seems like a similar issue. If it's not the case, let me know.

**Comment by minuscorp** [comment]
So... If I understand correctly from that issue, the problem was that the provider was not getting deallocated in 8.X but now in 10.X it is. But I think that in my case is actually impossible that the provider is getting deallocated, as you can see, `activity` in my example above, is part of a singleton that instantiates the corresponding service at the first moment it is called. How can it be released and how's this the expected behavior, if this is the case, we cannot rely on Protocol Extensions that instantiate the services under-demand. I can understand that the Provider gets deallocated after a request is finished and no more references are linked to it, but *during* a request, that the resource itself gets deallocated... I don't think it is a proper management... there're no risks in retain cycles because requests from Moya don't perform side-effects as they're defined.

**Comment by SD10** [comment]
@minuscorp It could be that the provider is a computed property? Maybe make it a closure that is called immediately so that a value is stored in the property.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by minuscorp** [comment]
I will test making the computed property a computed closure that generates the provider, but I don't know if this is the desired behavior... Now it would be necessary to call it as follows:

```swift
SessionManager.shared.service.activity().activity(withId: 1449319201383, source: .internet)
```
which in my opinion is an anti-Swift pattern, cannot understand how the Provider is being released during a network call...

**Comment by SD10** [comment]
@minuscorp what I meant was something like
```Swift
let provider: MoyaProvider<Service> = { return ... }()
```
It’s impossible to tell without your full service class, but this property has to have a value for the lifetime of the request. It can’t be a factory spitting out new ones. It has to be retained somewhere in the singleton

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by minuscorp** [comment]
But with that approach, protocol extensions are no longer usable, which comes handy when having 10 different targets in the application...

**Comment by sunshinejr** [comment]
You can still [store variables in protocol extensions](https://marcosantadev.com/stored-properties-swift-extensions/) (even though it's not that simple to do). 

Additionally, Moya always warned users that they _**need**_ to retain the provider as long as you need the callback from it. In the recent versions we just fixed the inconsistency around this topic (especially in reactive plugins) and documented it a bit more. 

The main advantage (at leas for me) with having it deallocated is that I don't waste my resources whenever I don't want it. Simple use-case: we have a provider created for a user. In the app there are many requests for fetching data and displaying it. Whenever user logs out we don't want the requests to go through and give us back the responses, because these are not needed anymore - the object responsible for it is not there.

If you feel like we could discuss it further, we can close this issue and create a new one for this specific case.

**Comment by SD10** [comment]
@minuscorp Can you generate the providers in a protocol extension but then assign them to a stored property in the Singleton? Sorry for the inconvenience but I believe this is the correct behavior

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by minuscorp** [comment]
I understand the approach, not so pretty to use that _hacky_ way, but I suppose I have not choice. Now is late night in Europe so I'll try this tomorrow.

About the behavior, I think that I do not agree on your use case... Normally the user is responsible of disposing any resources that might be running, this is an standard approach that is defined by the promises. You can either reject or resolve it. ReactiveX adds another tool for controlling all the resources by the disposable management, in that case, logging out as you pointed, will be enough to dispose any ongoing network request.

What do you think?

**Comment by sunshinejr** [comment]
@minuscorp I'm not talking about any library specifically, just saying that when the object is released (in this case MoyaProvider), I don't expect anything anymore from this object, because it doesn't exist. But I guess this is just a personal matter and if we want to discuss this behavior in Moya further, let's create another issue 👍

**Comment by minuscorp** [comment]
I opened #1558 for the discussion.

About the issue itself, I wasn't able to change my Provider yet, so if you want, we can keep this open until I get it fixed by my side and can confirm that is actually the root of the issue. 😄

**Comment by sunshinejr** [comment]
Yeah, let's keep it open then 👍

**Comment by minuscorp** [comment]
I confirm that this is due the behavior being implemented in later versions of Moya. I close this but I'd like to continue the discussion in the other issue, about the behavior itself.

Thank you all!!
