### ISSUE TITLE
Swift 2.0 branch?

### ISSUE THREAD

**Issue by ericreid** [Moya/Moya#156]
I want to integrate Moya into an Xcode 7/Swift 2.0 project. Any chance of an official branch to support this to go along with the Alamofire swift-2.0 branch?

**Comment by ashfurrow** [comment]
Hey, totally! Great idea! I've pushed a `swift-2.0` branch so we can follow that there. If you're able to, a PR into that branch would be very much appreciated :)

**Comment by justinmakaila** [comment]
I'm in the midst of cleaning up the dependencies on the `swift-2.0` branch, and I wanted to make some changes to how the demo project is set up and whatnot (having it in the `Pods.xcodeproj` is kind of bulky and confusing). How attached are you to keeping CocoaPods in the directory? If I can achieve the same thing using `Carthage` and pushing the frameworks to the repo, would that be cool?

**Comment by ashfurrow** [comment]
I'm not attached at all – @neonichu asked to add the `Pods/` directory and its friends for Carthage support. If we don't need that, that's cool with me. 

![](https://s-media-cache-ak0.pinimg.com/originals/d9/be/72/d9be72f4ac11c7da286fa98e99c929f3.jpg)

**Comment by ashfurrow** [comment]
Hmm, sorry, I'm re-reading this and I thought you meant to pods _directory_. I'd feel more comfortable keeping the demo project built with CocoaPods.

**Comment by esttorhe** [comment]
Can this be closed with #194 ?

**Comment by ashfurrow** [comment]
Sounds good.
