### ISSUE TITLE
If my project have two baseUrl, but with same endpointClosure and requestClosure。How to package targettype more elegant

### ISSUE THREAD

**Issue by blackchena** [Moya/Moya#1561]
If my project have two baseUrl, but with same endpointClosure and requestClosure。How to package targettype more elegant

**Comment by sunshinejr** [comment]
Hey @blackchena. There are few ways to do this, but I'd use `MultiTarget` and split your API into two `TargetType`s.  You can take a look at our MultiTarget examples [here](https://github.com/Moya/Moya/blob/master/docs/Examples/MultiTarget.md). 

Let me know if I can be any more helpful with that matter!
