### ISSUE TITLE
Does Moya support last release of ReactiveSwift 3.1?

### ISSUE THREAD

**Issue by chapayGhub** [Moya/Moya#1564]
I can't create project with pods:
- ReactiveSwift 3.1
- Last Moya
- And json serializer like ObjectMapper that support  ReactiveSwift 3.1

Do you have plans to support  ReactiveSwift?

**Comment by sunshinejr** [comment]
Hey @chapayGhub. We support `ReactiveSwift` >= 3.0 in the newest beta of `Moya 11` (11.0.0-beta.2). We strive to release it in the next days when we feel like it's stable enough. Would love it if you could use it and give any feedback on the changes if you have time to do it.

**Comment by SD10** [comment]
[Moya 11.0](https://github.com/Moya/Moya/releases/tag/11.0.0) has been released and ReactiveSwift 3.0 support is now available on `master`. I'm going to close this, thank you @chapayGhub 👍
