### ISSUE TITLE
Moya 11 Default Request Mapping?

### ISSUE THREAD

**Issue by jhrasco** [Moya/Moya#1569]
Migrating to Moya 11 generates error (see below) when overriding the MoyaProvider initializer with default values.

Error:

Default argument value of type '(Endpoint, (Result<URLRequest, MoyaError>) -> Void) -> ()' cannot be converted to type 'MoyaProvider.RequestClosure' (aka '(Endpoint, @escaping (Result<URLRequest, MoyaError>) -> ()) -> ()')

Code:

```swift
override init(endpointClosure: @escaping EndpointClosure = MoyaProvider.defaultEndpointMapping,
                  requestClosure: @escaping RequestClosure = MoyaProvider.defaultRequestMapping,
                  stubClosure: @escaping StubClosure = MoyaProvider.neverStub,
                  callbackQueue: DispatchQueue? = nil,
                  manager: Manager = MoyaProvider<MultiTarget>.defaultAlamofireManager(),
                  plugins: [PluginType] = [AuthPlugin()],
                  trackInflights: Bool = false) {
        
        super.init(endpointClosure: endpointClosure,
                   requestClosure: requestClosure,
                   stubClosure: stubClosure,
                   callbackQueue: callbackQueue,
                   manager: manager,
                   plugins: plugins,
                   trackInflights: trackInflights)
    }
```

How to assign a defaultRequestMapping?

**Comment by SD10** [comment]
Hey @jhrasco, thanks for reporting this. I'm thinking that [MoyaProvider.defaultRequestMapping](https://github.com/Moya/Moya/blob/0b90f7ee8dcc378fe48db18c8b281e8792244de9/Sources/Moya/MoyaProvider%2BDefaults.swift#L15) needs to have its `RequestResultClosure` argument marked as `@escaping`. What version of Moya are you migrating from?

**Comment by jhrasco** [comment]
Hi @SD10 Thank you for a quick response. I'm migrating from version 10.0.2 to 11.

**Comment by SD10** [comment]
@jhrasco Are you subclassing? This is an odd error message. 
The real fix is you need to reference `YourProviderSubclass.defaultRequestMapping` or resolve `MoyaProvider`'s generic.

**Comment by jhrasco** [comment]
@SD10 Thanks. Yes, I'm subclassing and your proposed solution,`ProviderSubclass.defaultRequestMapping`, works. Thank you.

**Comment by SD10** [comment]
Looks like a type alias for a function is `@escaping` by default in Swift. So we don't need to mark `RequestResultClosure`. 

But we need the `@escaping` attribute on `RequestClosure` because it looks like the `@escaping` attribute is not inferred by default on a `typealias` 🤔 

Bad error message I guess.

**Comment by SD10** [comment]
It looks like when `Endpoint` was generic, `MoyaProvider` was able to resolve the type. 
You could use `MoyaProvider.defaultRequestMapping` in `10.0.2` but now you cannot. You must pass on the generic from the subclass or refer to the subclass itself.

**Comment by sunshinejr** [comment]
💯 I've added a line to Migration Guide in #1570.
