### ISSUE TITLE
[Ask] Cannot invoke 'map' with an argument list of type

### ISSUE THREAD

**Issue by alfian0** [Moya/Moya#1574]
Hi ...is everyone here create NetworkService wrapper for transform response in to Decodable object, when I create function with generic type of Decodable.protocol I got this `Cannot invoke 'map' with an argument list of type`

<img width="585" alt="screen shot 2018-02-08 at 7 56 25 pm" src="https://user-images.githubusercontent.com/21122436/35974055-2d52c866-0d0a-11e8-9107-8635211b211a.png">

1. Moya/RxSwift (10.0.1)
1. ObjectMapper (3.1.0)

**Comment by sunshinejr** [comment]
Hi @alfian0. You could try making the function generic, as our function expects any type that _implements_ `Decodable` and AFAIK `Decodable` does not implement `Decodable`, which shouldn't be the case and I'm not sure if it's fixed in the newest Swift.

Something like:
```swift
internal func requestObject<T: Decodable>(token, decodableClass: T.Type) {}
```

Let me know if it helps.

**Comment by alfian0** [comment]
Ha ha, yes it's dumb question. I just forgot to use `T`, my existing code use ObjectMapper and I need change to Decodable. Its working now

<img width="741" alt="screen shot 2018-02-08 at 8 20 59 pm" src="https://user-images.githubusercontent.com/21122436/35974965-adf864e6-0d0d-11e8-8427-a339edd734ca.png">

this is my old implementation

<img width="675" alt="screen shot 2018-02-08 at 8 21 05 pm" src="https://user-images.githubusercontent.com/21122436/35975494-8c321454-0d0f-11e8-906f-4b4d9a845e0b.png">

thanks @sunshinejr

**Comment by sunshinejr** [comment]
Nah, not dumb at all @alfian0. In fact this shouldn't be a problem and you should be able to just run the code you posted without any changes. But yeah, it's not there yet.

I'm closing this one but if there is anything else we can help you with, let us know!
