### ISSUE TITLE
Parameter encoding - linker error

### ISSUE THREAD

**Issue by mkkroliks** [Moya/Moya#1576]
I'm using "Moya/Moya" "10.0.2" and "Alamofire/Alamofire" "4.6.0"

Once I add parameter encoding to TargetType enum declaration I'm getting linker error

```swift
public var parameterEncoding: ParameterEncoding {
        return URLEncoding.httpBody
    }
```

![image](https://user-images.githubusercontent.com/2151961/36021921-92e43264-0d87-11e8-85a6-fc77953ee5b5.png)

Look's like problem is related with Alamofire, but I can't find any solutions.

I'm using Carthage 0.27.0

**Comment by sunshinejr** [comment]
Hey @mkkroliks. Try to import Alamofire and see if it helps.

**Comment by mkkroliks** [comment]
Yes! It works, thanks a lot @sunshinejr.

**Comment by SD10** [comment]
Thanks for letting us know this worked for you @mkkroliks 👍

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
