### ISSUE TITLE
Upgrade RxMoya antitypical/Result version to 3.1+

### ISSUE THREAD

**Issue by hherman1** [Moya/Moya#1583]
I'm breaking the format because it doesn't really apply (or so it seems).

Currently RxMoya requires Result ~> 3.0.0 (idk if this is a code requirement or just coming from the Result installation instructions)... version 3.0.0 doesn't include AnyError which I would like to use. If you can, please upgrade RxMoya's Result to 3.1+! (latest version is 3.2.4)

**Comment by lucas34** [comment]
Issue only applicable if you fetch the project with `pod`
```
Podspec
"Result", "~> 3.0"
````
```
Cartfile
github "antitypical/Result" ~> 3.1
```

Both should point to the same version.
Updating Results should not bring any issue since it's already working if you fetch the project with Carthage. Will resolve Results with  for 3.2.4. Same if you are using SPM.

**Comment by sunshinejr** [comment]
I think this one should be resolved thanks to @lucas34, but if there are still questions about it, don't hesitate to reopen it @hherman1.
