### ISSUE TITLE
Upload image with parameters.

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [Moya/Moya#1584]
I am using latest version of Moya. 

How can I upload image with parameters, according to migration guide.

**Comment by sunshinejr** [comment]
Hey @Rashesh-Bosamiya. Please take a look at our [Multipart Upload example](https://github.com/Moya/Moya/blob/master/docs/Examples/MultipartUpload.md). It covers sending image with parameters in body or in URL.

**Comment by Rashesh-Bosamiya** [comment]
Thanks!
