### ISSUE TITLE
Repeating requests when server return 401

### ISSUE THREAD

**Issue by dtomicAZ** [Moya/Moya#1588]
Hi,

I am using Moya (10.0.1)

Post request repeats himself when getting 401 from server.
I sent one request, but when I inspect it with Burp, I see same request is fired 3 times.
Server also registers it 3 times and lock user login.

Is there any way to prevent this ?

Here are links on this subject, but without solution.
https://stackoverflow.com/questions/25647755/return-http-401-and-say-client-do-not-repeat-request
https://stackoverflow.com/questions/13944527/nsurlconnection-retry-on-401-status

**Comment by BasThomas** [comment]
Hey @dtomicAZ, can you share the code where you’re experiencing the issue?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dtomicAZ** [comment]
@BasThomas It is little complicated to share this code.

This is my login method:

```
  func signIn(email: String, password: String, success: @escaping (Token) -> (), failure: @escaping (AppError) -> ())
  {
    App.rest.request(.signIn(email: email, password: password)) { (result) in
      self.jsonWorker.handleJsonObject(result: result, success: success, failure: failure)
    }
  }
```

App.rest is Moya provider:
case signIn(email: String, password: String).. etc.

It's just POST request on server API for login, which requires email and password.
Server returns me this:

HTTP/1.1 401 Unauthorized
Cache-Control: no-cache
Pragma: no-cache
Content-Type: application/json; charset=utf-8
Expires: -1
WWW-Authenticate: Negotiate
WWW-Authenticate: NTLM
Date: Thu, 15 Feb 2018 07:43:55 GMT
Connection: close
Content-Length: 51

After that iOS fires two more same requests.

I tried same request using "native" URLRequest and URLSession, without Moya, and same thing happens. So it is something on iOS level, not Moya.

But I am using Moya and I am interested is there some way to prevent multiple request without changing status code on server side different than 401.

Android and Postman don't have this issue/feature, no repeating requests on same server.

btw. If I change status code on server to e.g. 403, than requests is not repeating.
I came to this issue first time in my 5 years of development of iOS mobile apps.

**Comment by sunshinejr** [comment]
@dtomicAZ seems like [this response from SO](https://stackoverflow.com/a/25319418/2340462) says it all - when you have `www-authenticate` header, authentication challenges are triggered. [This issue from RN](https://github.com/facebook/react-native/issues/2266) is also similar. Really interesting, didn't know about it either!

I'm gonna close this one, but if you have any more questions for Moya itself, please don't hesitate to create new issue.
