### ISSUE TITLE
ValidationType not working with uploadMultipart

### ISSUE THREAD

**Issue by HadiYaac** [Moya/Moya#1590]
Moya 11.0 using CocoaPods

- The new ValidationType has something with the uploadMultipart, why there is no validation on the multipart upload?
- The below is the debugger output when printing down the **result** from the *requestNormal* function in the **MoyaProvider+Internal.swift**

```lldb
(lldb) po result
▿ .success(Status Code: 400, Data Length: 104)
  ▿ success : Status Code: 400, Data Length: 104
```

**Comment by SD10** [comment]
@HadiYaac What validation type are you using?

**Comment by SD10** [comment]
Thank you for reporting this @HadiYaac. I'm working on the patch 😃
