### ISSUE TITLE
How to post json parameters and UIImage both

### ISSUE THREAD

**Issue by kou0117** [Moya/Moya#1594]
Using Moya 9.0.0

I would like to post json parameters and UIImage both, but I do not know how to do that.

In the case below, Data is UIImage and a, b and c is String.
I would like to create json parameters which contains a, b and c like 
```swift
parameters: ["a": a, "b": b, "c": c], encoding: JSONEncoding.default)
```

```swift
import UIKit
import Moya
import SwiftyJSON

    public var task: Task {
        switch self {
        case .uploadImage(let image, let a, let b, let c):
            let data = UIImageJPEGRepresentation(image, 0.5)!
            let Data = MultipartFormData(provider: .data(data), name: "files", fileName: "txImage.jpg", mimeType: "image/jpeg")
            let a = MultipartFormData(provider: .data(a.data(using: .utf8)!), name: "a")
            let b = MultipartFormData(provider: .data(b.data(using: .utf8)!), name: "b")
            let c = MultipartFormData(provider: .data(c.data(using: .utf8)!), name: "c")
//            let jsonParameter = JSON([a, b, c])

            let multipartData = [Data, a, b, c]
            return .uploadMultipart(multipartData)
        }
    }
```

**Comment by sunshinejr** [comment]
Hey @kou0117. Unfortunately, you can't really send all of it as a `JSON` body, because `JSONEncoding` sends 
```
Content-Type: application/json
```

where uploading multipart needs a different header:
```
Content-Type: multipart/form-data
```

and this is needed because server needs to resolve the request correctly in case of a multipart one.

Now the question is: what is really wrong with the code you posted, because from the server perspective it would seem similar to what you want to achieve (meaning it would get 3 parameters and a data). If it's different serialization, you can use `JSONSerialization` instead of `"".data(using: .utf8)` to get the data:
```swift
JSONSerialization.data(withJSONObject: parameters, options: options)
```

If it's still not what you really want, let me know please.

**Comment by kou0117** [comment]
Thank you so much for your reply.

So when I want to send image as ```jpeg``` and a, b, c as ```JSON```, the code below is fine?

```swift
import UIKit
import Moya
import SwiftyJSON

    public var task: Task {
        switch self {
        case .uploadImage(let image, let a, let b, let c):
            let data = UIImageJPEGRepresentation(image, 0.5)!
            let Data = MultipartFormData(provider: .data(data), name: "files", fileName: "txImage.jpg", mimeType: "image/jpeg")
            let parameters: [String: Any] = ["a": a, "b": b, "c": c]
            let json = JSONSerialization.data(withJSONObject: parameters, options: options)

            let multipartData = [Data, json]
            return .uploadMultipart(multipartData)
        }
    }
```
I would appreciate if you may reply.

**Comment by sunshinejr** [comment]
@kou0117 you won't really send it as JSON; it will be sent as a `form-data`. However, if your server accepts both image and parameters in the body, your code is fine. If you want your parameters in the url instead, please take a look at our [Multipart upload example](https://github.com/Moya/Moya/blob/master/docs/Examples/MultipartUpload.md).

**Comment by kou0117** [comment]
@sunshinejr 
I understand it.
Thank you for your help!
