### ISSUE TITLE
Having issues with Cocoapods 

### ISSUE THREAD

**Issue by vishal91** [Moya/Moya#1595]
While installing Firebase in pod, i am facing this issue. 

`Undefined symbols for architecture x86_64: "__T09Alamofire11URLEncodingVAA17ParameterEncodingAAWP", referenced from: __T09App0A3ApiO4task4Moya4TaskOfg in App.o "__T09Alamofire12JSONEncodingVN", referenced from: __T09App0A3ApiO4task4Moya4TaskOfg in App.o "__T09Alamofire11URLEncodingVN", referenced from: __T09App0A3ApiO4task4Moya4TaskOfg in App.o "__T09Alamofire12JSONEncodingVAA17ParameterEncodingAAWP", referenced from: __T09App0A3ApiO4task4Moya4TaskOfg in App.o "__T09Alamofire11URLEncodingV7defaultACfgZ", referenced from: __T09App0A3ApiO4task4Moya4TaskOfg in App.o "__T09Alamofire12JSONEncodingV7defaultACfgZ", referenced from: __T09App0A3ApiO4task4Moya4TaskOfg in App.o ld: symbol(s) not found for architecture x86_64 clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by sunshinejr** [comment]
Hey @vishal91. Please try to `import Alamofire` wherever you are using the `ParameterEncoding`. 

This seemed like an issue with Carthage though, so it's odd that it happens to you with CocoaPods. 🤔

**Comment by vishal91** [comment]
@sunshinejr : Its weird. It works fine if i don't add Firebase/Core and Firebase/Messaging pods to the project.

**Comment by vishal91** [comment]
@sunshinejr Thanks a lot.
