### ISSUE TITLE
Update Swift Compatibility

### ISSUE THREAD

**Issue by ashfurrow** [Moya/Moya#1600]
Apple maintains a list of Swift projects and their Swift version compatibilities [here](https://github.com/ashfurrow/swift-source-compat-suite), which is used as a test suite to guard against regressions in the Swift language. Now that Moya supports Swift 4, we should add that compatibility to our specification:

https://github.com/ashfurrow/swift-source-compat-suite/blob/e51c38ddf03928b2c089fe5dd19fcdc815faf565/projects.json#L1013-L1037

Instructions are in the readme. Once added, the `./project_precommit_check` script can be run to verify everything works, and a pull request can be submitted to Apple's repo.

This should be a straightforward task and an ideal one for anyone who wants to get more involved in the Swift community.

**Comment by kimdv** [comment]
https://github.com/apple/swift-source-compat-suite/pull/148

**Comment by ashfurrow** [comment]
Nice work!

**Comment by kimdv** [comment]
It seems that the build failed
https://ci.swift.org/view/Source%20Compatibility/job/swift-master-source-compat-suite/1339/console

But what I can read, it is Moya passes, right?

**Comment by SD10** [comment]
Yep, it's all good @kimdv. Thank you for taking care of this issue so Swiftly 😆 ❤️
