### ISSUE TITLE
Not getting data

### ISSUE THREAD

**Issue by fragilehm** [Moya/Moya#1608]
I am using last version of moya and 
when i'am trying to get data from specific host with port :8000 it works fine but when i changed to 
:8081 it loads too long then failure with "timeout", same thing works fine in Alamofire

**Comment by BasThomas** [comment]
Can you post your code?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fragilehm** [comment]
Hello, I have basic structure to get data, the thing if i use

URL(string: "http://46.101.146.101:8000")! as baseUrl everything work fine,
but we

this is production host and for developing host we have

URL(string: "http://46.101.146.101:8081")!, so everything is the same but
just 8081

you can try yourself, it you still need code I can send


2018-03-20 19:39 GMT+06:00 Bas Broek <notifications@github.com>:

**Comment by SD10** [comment]
@fragilehm I see that you resolved this issue, do you have any insight for future Moya users who may have a similar problem?
