### ISSUE TITLE
Question: How to merge multiple requests using zip? I am using Moya with RxSwift.

### ISSUE THREAD

**Issue by hemant3370** [Moya/Moya#1609]
This isn't working
```swift
let r2 = APIProvider.rx.request(Quizzler.FORECASTING())
let r3 = APIProvider.rx.request(Quizzler.HOURLYDATA())
let r4 = APIProvider.rx.request(Quizzler.SUNTIMING())
let comb = Observable.zip(r1.asObservable(), r2.asObservable(),r3.asObservable(),r4.asObservable()) {
    return ($0, $1, $2, $3)
}
comb.subscribe { (event) in
    switch event {
   case .completed:
       print("parsing done")
   case .error(let err):
       print(err.localizedDescription)
   case .next(let element):
       print(element.0)
       print(element.1)
       print(element.2)
       print(element.3)
   }
}.disposed(by: disposeBag)
```

**Comment by BasThomas** [comment]
Can you give a better explanation of what’s not working / what you expect?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hemant3370** [comment]
@BasThomas I want to hit 4 different API endpoints and get a callback only when all 4 are completed.

**Comment by BasThomas** [comment]
OK. What is not working exactly? What is the output?

**Comment by hemant3370** [comment]
@BasThomas  case .next(let element) never gets called.

**Comment by jdisho** [comment]
@hemant3370 This shouldn’t be an RxMoya problem. 
But, what do you get when you do this?
```swift
comb.subscribe { event in 
  print(event)
}
```

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jimijon** [comment]
@hemant3370 I am having the same problem. What was your solution?

**Comment by xseec** [comment]
You must define provider in class, prevent to be recycled right now.

> class XXX {
>     let provider = MyService.getProvider()

>     func  request() {
>         let r2 = provider.rx.request(Quizzler.FORECASTING())
>         let r3 = provider.rx.request(Quizzler.HOURLYDATA())
>         let r4 = provider.rx.request(Quizzler.SUNTIMING())
>         let comb = Observable.zip(r1.asObservable(), r2.asObservable(),r3.asObservable(),r4.asObservable()) 
>         comb.subscribe { (event) in
>         ......
>     }

>}
