### ISSUE TITLE
Upload image using .uploadMultipart get error status code 500

### ISSUE THREAD

**Issue by anhpt681995** [Moya/Moya#1610]
`Moya Version: 10.0.1`

I did follow the [Multipart Upload example](https://github.com/Moya/Moya/blob/master/docs/Examples/MultipartUpload.md) and this is my code:

```swift
import Moya

typealias UpdateUserAvatarParameters = (userId: UserId, image: UIImage)

enum APITarget {
    case updateUserAvatar(parameters: UpdateUserAvatarParameters)
}

extension APITarget: TargetType {

    public var method: Moya.Method {
        switch self {
        default: return .post
        }
    }

    public var task: Task {
        switch self {
        case .updateUserAvatar(let parameters):
            let imageData = UIImagePNGRepresentation(parameters.image) ?? Data()
            let userIdData = parameters.userId.string.data(using: String.Encoding.utf8) ?? Data()
            
            let imageMultipartFormData = MultipartFormData(provider: .data(imageData), name: "img", fileName: "user_avatar.jpeg", mimeType: "image/jpeg")
            let userIdMultipartFormData = MultipartFormData(provider: .data(userIdData), name: "cusId")
            
            return .uploadMultipart([imageMultipartFormData, userIdMultipartFormData])
        }
    }

    public var headers: [String : String]? {
        switch self {
        case .updateUserAvatar:
            return ["Content-type" : "multipart/form-data"]
        default:
            return ["Content-type" : "application/json"]
        }
    }
}
```

However, when I make a request, I get an MoyaError:
<img width="282" alt="screen shot 2018-03-23 at 10 00 33 pm" src="https://user-images.githubusercontent.com/15669551/37836704-b8cbaa78-2ee5-11e8-8841-ae69be303de6.png">

I have no idea about what I did wrong. Any suggestion?

Addition, when I make a request with Alamofire with the same setup (url, parameters...), everything works normally:

```swift
Alamofire.upload(multipartFormData: { multipartFormData in
    let imageData = UIImagePNGRepresentation(pickedImage) ?? Data()
    let userIdData = userId.string.data(using: String.Encoding.utf8) ?? Data()

    multipartFormData.append(imageData, withName: "img", fileName: "user_avatar.jpeg", mimeType: "image/jpeg")
    multipartFormData.append(userIdData, withName: "cusId")
}, to: "http://domain/api/postuserimage", encodingCompletion: { result in
    switch result {
    case .success(let upload, _, _):
        upload.uploadProgress(closure: { progress in
            print("Upload Progress: \(progress.fractionCompleted)")
        })

        upload.responseJSON(completionHandler: { response in
            print(response.result.value)
        })

    case .failure(let encodingError):
        print(encodingError)
    }
})
```

**Comment by jdisho** [comment]
@anhpt681995 `500` indicates that the server encountered something unexpected. Probably the data  in `httpBody` is not as the server expects.

**Comment by anhpt681995** [comment]
@jdisho Thanks for your respond. Yes, as you pointed out, `500` indicates that the server encountered an unexpected condition which prevented it from fulfilling the request. However, with the same url, parameters, HTTP method ... when I make a request with Alamofire it worked. So I think the problem is not at the server. Maybe I did something wrong with Moya but I didn't know where I was wrong.

**Comment by jdisho** [comment]
You use this in `Moya`
```swift 
let userIdData = Data(bytes: &userId, count: MemoryLayout.size(ofValue: userId))
```

and this in `Alamofire`, which means that you are creating `utf8` encoded `Data` from `String`

```swift 
let userIdData = userId.string.data(using: String.Encoding.utf8) ?? Data()
```

Try using the same thing in `Moya` @anhpt681995 .

**Comment by anhpt681995** [comment]
@jdisho Well spotted, however, I tried it, but it still doesn't work. It's still `500` :(

Thanks for have a look at it.

**Comment by dangthaison91** [comment]
Did you resolve this @anhpt681995 ?
