### ISSUE TITLE
Not working with AlamofireNetworkActivityIndicator

### ISSUE THREAD

**Issue by SeRG1k17** [Moya/Moya#1612]
Moya using Alamofire.
[AlamofireNetworkActivityIndicator](https://github.com/Alamofire/AlamofireNetworkActivityIndicator) using Alamofire.
If I set
```swift
NetworkActivityIndicatorManager.shared.isEnabled = true
```
And execute the request using Moya. The indicator will be displayed indefinitely.
I know about the existence of a built-in plugin - NetworkActivityPlugin.
But it requires manual control of the indicator in the closure, which I do not need.

**Comment by SD10** [comment]
@SeRG1k17 I looked into this today and I can't reproduce. Can you put together an example project demonstrating the issue?

**Comment by SeRG1k17** [comment]
@SD10 I created a test project, but everything works correctly there. Can there be a problem in a specific request?

**Comment by sunshinejr** [comment]
@SeRG1k17 really strange, are you sure it's there indefinitely? Maybe there is a request that gets a timeout?

**Comment by SD10** [comment]
At first, I thought it was related to #1503 because the `defaultAlamofireManager()` isn't a shared instance. I tried a lot of things in an example project and just like @SeRG1k17 I couldn't reproduce

**Comment by SeRG1k17** [comment]
See the guys @SD10, @sunshinejr 
I noticed that for some reason the increment of the counter inside the library is called twice.
Here is the call stack at the normal move, that is, the user pressed the button-started request ...
![normal](https://user-images.githubusercontent.com/13317173/39041091-e531abba-4490-11e8-94d9-784292ee81ae.png)

Then we hit the increment method again, here's the stack:
![twice](https://user-images.githubusercontent.com/13317173/39041185-faca709c-4490-11e8-8203-6f56777752d4.png)

Offtopic:
I have some more ideas for improving the library, where I could discuss some details. Or just make pull requests?

**Comment by SD10** [comment]
@SeRG1k17 Can you provide an example project that reproduces it? I could play with it when I have some free time.

About improving Moya, if you have any ideas the best thing to do is to open issues for the community to discuss them 👍

**Comment by SeRG1k17** [comment]
@SD10 The problem is observed on a large working project. On a test project, with the same request, everything is fine :(

**Comment by SeRG1k17** [comment]
@SD10 
Typical creation of own manager is described in #743 
If dont use manager.startRequestsImmediately = false
This causes the problems described above. We increment the counter twice.
Is this a bug?

**Comment by SeRG1k17** [comment]
@SD10 I think, now I know how reproduce it in example project:)

**Comment by larsschwegmann** [comment]
@SeRG1k17 How did you resolve this? I am experiencing the same issue...
