### ISSUE TITLE
Add Carthage-friendly SwiftLint build phase.

### ISSUE THREAD

**Issue by sunshinejr** [Moya/Moya#1616]
So we had a SwiftLint build phase for quite some time. Unfortunately, this build phase was a problem for Carthage users, so there is a PR to remove it (#1615) to fix some of the problems like #1458 and #1542.

The main problem is that the build phase is ran by Carthage as well. [Quick](https://github.com/Quick/Quick) had a similar issue and it seems to be resolved now. Relevant links: [Quick#693](https://github.com/Quick/Quick/issues/693), [Quick#694](https://github.com/Quick/Quick/pull/694) and [Nimble#409](https://github.com/Quick/Nimble/pull/409).

Oh, and it would be awesome to update our [CI workflow](https://github.com/Moya/Moya/blob/master/.circleci/config.yml) to separate testing Carthage integration without SwiftLint, so we can avoid similar situation in the future.

If there are any questions about this one let me know!

**Comment by SD10** [comment]
Going to close this as it has been patched in Moya 11.0.2. Thanks for taking the time to investigate and write a detailed outline of the problem @sunshinejr 👍
