### ISSUE TITLE
Best way to handle pagination

### ISSUE THREAD

**Issue by filograno** [Moya/Moya#1618]
Public third party API (like Instagram API or GitHub API) paginate data using a specific url to indicate the next page.
Using Moya (11.0.1), in the request I need to pass the entire url of the next page.
To avoid encoding issues (as mentioned in the issue #1119) I need to extract the path and query string from this url, so that my TargetType is:

```swift
enum InstagramService {
    /// gets the first page of the recent media 
    case media(accessToken: AccessToken)
    /// gets the next pages of the recent media 
    case nextMedia(path: String, params: [String : Any])
}


extension InstagramService: TargetType {
    var baseURL: URL {
        return Constant.InstagramValue.apiBaseUrl
    }
    
    var path: String {
        switch self {
        case .media:
            return "/users/self/media/recent"
        case .nextMedia(let path, _):
            return path
        }
    }
    
    var method: Method {
        return .get
    }
    
    var sampleData: Data {
        return "".data(using: .utf8)!
    }
    
    var task: Task {
        switch self {
        case .media(let accessToken):
            let parameters = ...
            return .requestParameters(parameters: parameters,
                                      encoding: URLEncoding.queryString)
        case .nextMedia(_ , let params):
            return .requestParameters(parameters: params, encoding: URLEncoding.queryString)
        }
        
    }
    
    var headers: [String : String]? {
        return nil
    }
}
```

is this the right approach to handle the pagination with Moya? Is there a better approach?

**Comment by sunshinejr** [comment]
Hey @filograno. I usually have an optional `pagination` object that holds a `page` and number of items per page that I want to fetch. Then, from the response, either I got an object that returns a current `Pagination` object as well, or if I can't get it out of an API, I'd just bump the `page` in my current `Pagination` object.

I think that there are many approaches and it's just a matter of what do you like the most. Nothing's wrong with your as well. Maybe there is even a room for a simple library for Moya 😉
