### ISSUE TITLE
Why is my character converted?

### ISSUE THREAD

**Issue by PlutusCat** [Moya/Moya#1625]
I'm using the 11.0.1 version
My code 
``` swift

extension MainMoyaAPI: TargetType {
    public var baseURL: URL {
        return URL(string: "http://www.mainmoya.com")!
    }

    public var path: String {
        switch self {
        case .login(_):
            return "/login.do?key=\(iOS_Key)"
        case .cityList(_):
            return "/getCity"
        }
    }
// More ....
}

```

The string "/login.do?key=\(iOS_Key)"  is converted to "/login.do%3Fkey=\(iOS_Key)"
Right is "http://www.mainmoya.com/login.do?key=\(iOS_Key)"

Thinks

**Comment by SD10** [comment]
@PlutusCat It's because `?` is not meant to be used in `path` and this is what causes it to get encoded this way. You could move the `?` into `baseURL` and it should fix your issue.

**Comment by SD10** [comment]
@jdisho Thanks for helping us clean up! But we actually have a bot that automatically closes an issue after 2 weeks of inactivity 😇

**Comment by SD10** [comment]
@PlutusCat We're glad you were able to resolve your issue. Mind letting us know how you managed to fix this? It could help a future Moya user

**Comment by AhmAbdallah** [comment]
I want to call this  https://www.blaalb.com/restApi/testApi/myOrders?number=1&month=24

```
enum MyWebService {
    switch self {
       case getMyOrders(number: Int, month: Int)
   }
}

var path: String {
   switch self {
      case . getMyOrders:
      return "/myOrders"
     }
  }
}

var method: Moya.Method {
     switch self {
      case .getMyOrders:
      return .get
   }
}

var task: Task {
    switch self {
      case . getMyOrders(let number, let month):
      let p = ["number" : number,
               "month": month]
    return .requestParameters(parameters:p , encoding: URLEncoding.default)
 }
}
```
