### ISSUE TITLE
Escaping / in path

### ISSUE THREAD

**Issue by maciejburda** [Moya/Moya#1629]
I use the newest moya.

And I've got we weird problem setting up the proper path.
The problem is that id you the object has `/` inside which has to be escaped.
But it can't really be passed as param because it's in the middle of the path:

Typical object id: `lci80MzY2NDQwODU4NDI/a2V5PTE0MjNmMmN`

```swift
var path: String {
        switch self {
        case let .trackObject(objectId):
            return "/objects/\(objectId)/track"
        }
    }
```

Slash is a valid sign so it won't be escaped.
But when I do this:
```
return "/objects/\(objectId.addingPercentEncoding(withAllowedCharacters: .urlHostAllowed) ?? "")/track"
```

The `%` sign will be escaped afterwards.

I tried playing with parameter encoding, no luck.
Any suggestions?

**Comment by SeRG1k17** [comment]
@maciejburda You can use the parameters in task like this:
swift```
public var task: Task {
        switch self {
        case .youCase, return .requestParameters(parameters: parameters, encoding: URLEncoding.queryString)
}
```
where parameters manually created property(or create dictionary here):

typealias Parameters = [String: Any]
    var parameters: Parameters {
        switch self {
        case let .login(username: name, password: pass): return ["username": name, "password": pass]
        }
    }
