### ISSUE TITLE
Example project for RxMoya with version 11.0

### ISSUE THREAD

**Issue by goktugaral** [Moya/Moya#1636]
Hi,

I am very disappointed with your example project. I want to use RxMoya on my project and I'm new on RxSwift. I found a couple of tutorials which includes RxMoya but they all have an old version of Moya. Could you update your example project, please? I tried to migrate from v.8.0 to v.11.0 but it is really confusing for me.

**Comment by jdisho** [comment]
Have a look at my OSS https://github.com/jdisho/Papr/tree/papr-moya-version, I am using RxMoya v.11 there. 
Btw, you have also check [Community projects](https://github.com/Moya/Moya/blob/master/docs/CommunityProjects.md)

**Comment by BasThomas** [comment]
Hi @goktugaral, thanks for letting us know. Unfortunately, even though we try our very best, some things might slip through the cracks and aren't update alongside the library itself. Please bear with us!

**Comment by goktugaral** [comment]
@jdisho I have just started to explore your project and puooww what the heck!! Thank you very much for widening my world. :)

@BasThomas thank you for your consideration and kind response. Of course, I bear :) I just wanted to mention about my suffering.

**Comment by SD10** [comment]
Thank you @pedrovereza 👍
