### ISSUE TITLE
How do I get the complete request URL in token?

### ISSUE THREAD

**Issue by honbolau** [Moya/Moya#1637]
//  I want to use the URL as the key in the database.
 // 1 ? How do I get the complete request URL in token?
 // 2 ?I tried to use splicing, but I couldn't get the Token parameter.

```swift
import Foundation
import RxSwift
import Moya
import WCDBSwift
import CryptoSwift

public extension Reactive where Base: MoyaProviderType {

    
    public func tryUseOfflineCacheThenRequest(_ token: Base.Target, callbackQueue: DispatchQueue? = nil) -> Observable<Response> {

        return Observable.create { [weak base] observer in
                let database = Database(withPath: dbPath);
                
//  I want to use the URL as the key in the database.
 // 1 ? How do I get the complete request URL in token?
 // 2 ?I tried to use splicing, but I couldn't get the Token parameter.
            
            do {
                // let object: Cache? = try database.getObject(fromTable: URLCacheTable, where: Cache.Properties.key == token.path.md5())
                if let obj = object{
                    let response = Response(statusCode: obj.statusCode, data: obj.data)
                    observer.onNext(response)
                }
            } catch {
                
            }
            let cancellableToken = base?.request(token, callbackQueue: callbackQueue, progress: nil) { result in
                switch result {
                case let .success(response):
                    if response.response!.statusCode == 200 {
                        let object = Cache()
                        object.key = token.path.md5()
                        object.statusCode = response.response!.statusCode
                        object.data = response.data
                        let database = Database(withPath: dbPath);
                        try! database.insertOrReplace(objects: object, intoTable: URLCacheTable)
                    }


                    observer.onNext(response)
                case let .failure(error):
                    observer.onError(error)
                }
            }
            return Disposables.create {
                cancellableToken?.cancel()
            }

        }

    }
}

```

**Comment by sunshinejr** [comment]
Hey @honbolau. To get the complete `URL` you would have to get the url + parameters. `URL` you can get using Moya's initializer for `URL`, `URL(target:)`. Parameters are harder because you would need to know if these parameters are gonna be encoded in the `URL` or not. You basically would need to implement all the logic Moya has to do it.

The other way would be to implement a `Plugin`. There is a function, [`willSend(_:target:)`](https://github.com/Moya/Moya/blob/master/Sources/Moya/Plugin.swift#L15), that should contain all the data you need.

We could also think about a way that helps you achieve all you need without using a Plugin, but I don't have any specific idea in mind, maybe you have one?

**Comment by honbolau** [comment]
@sunshinejr  I just want to save the full URL to the database in the following way.
`http://xxxx.com/view/cg/cargo/cargoAreaAvgPriceDate?areaId=0&releaseDate=2018-04-12`
But I can't get the parameters in this method.

**Comment by honbolau** [comment]
@sunshinejr  I just want to save the full URL to the database in the following way.
`http://xxxx.com/view/cg/cargo/cargoAreaAvgPriceDate?areaId=0&releaseDate=2018-04-12`
But I can't get the parameters in this method.

**Comment by pedrovereza** [comment]
@honbolau As mentioned by @sunshinejr, you can create a custom `Plugin` to get the full URL. So for an example target:

```swift
enum ExampleTarget {
    case example
}

extension ExampleTarget : TargetType {

    var baseURL: URL { return URL(string:"https://httpbin.org")! }
    var path: String { return "/get" }
    var method: Moya.Method { return .get }
    var sampleData: Data { return Data() }
    var task: Task { return .requestParameters(parameters: ["param1" : "value1",
                                                            "param2" : "value2"],
                                               encoding: URLEncoding.default) }

    var validate: Bool { return true }
    var headers: [String: String]? { return nil }
}
```

A custom plugin that is able to get the full URL would look like this:

```swift
class CompleteUrlLoggerPlugin : PluginType {
    func willSend(_ request: RequestType, target: TargetType) {
        print(request.request?.url?.absoluteString ?? "Something is wrong")
    }
}
```
This plugin is printing the url of every request (you may want to add some logic to only handle requests you want to save). Example output:

```
https://httpbin.org/get?param1=value1&param2=value2
```

Usage on your provider:

```swift
let provider = MoyaProvider<ExampleTarget>(plugins: [CompleteUrlLoggerPlugin()])
```

**Comment by honbolau** [comment]
@pedrovereza Thank you, but I can't get the cache data from the database immediately when I send the network request.
