### ISSUE TITLE
Moya reactive extensions concern

### ISSUE THREAD

**Issue by kzaher** [Moya/Moya#164]
Hi Ash,

I've been checking out reactive integration code (RX and RAC), and have some questions :)

It looks like the idea is to try to share results of in flight requests. That would make sense for idempotent query requests, but not sure that is correct in case of mutating command requests.

What do you think?

**Comment by ashfurrow** [comment]
Yeah, that's a fair point. We use comparisons based on the URL, the HTTP method, all the parameters, and the body. I would think that sending the same request twice would be different, but I suppose this is an assumption. 

Any suggestions? We could extend behaviour in the `MoyaProvider` class – maybe a closure like this?

```
typealias ShouldCheckInflightRequests = (Endpoint) -> (Bool)
```

That way people _can_ opt-out on a per-endpoint bases if they want? Open to suggestions on this.

**Comment by kzaher** [comment]
Yeah, you could do that. I would suggest that default behavior should be `false` :)

It would also be cool if you could do something like 
```
internalRequest(token)
    >- cacheInFlightRequests
```

`cacheInFlightRequests` should probably be internal method so you could write the code like

```
func request(token: T) -> Observable<MoyaResponse>
    if shouldCheckInflightRequests(target) {
        return internalRequest(token)
    }
   else {
        return internalRequest(token)
                   >- cacheInFlightRequests
    }
}
```

It would maybe also make sense to add functionality that would enable you to get typed object for endpoint instead of MoyaResponse (Observable<MyObject>).

**Comment by ashfurrow** [comment]
Hmm. Maybe a good default implementation would specify that GET and HEAD requests are coalesced, but POST PUT PATCH and DELETE ones are not. That seems like a sane default to me. Thoughts?

As for the inflight caching – using a token makes sense to me.

**Comment by kzaher** [comment]
That's probably a reasonable tradeoff. If somebody has command GET and HEAD requests he probably has bigger problems on his hands anyway :)

**Comment by aschuch** [comment]
We just discovered a case where in-flight GET requests would lead to a bug in one of our apps.

We continuously check for user settings whenever the app is opened. 
In case the user is no longer authorized, an automatic "relogin" attempt is made, which also tries to download the user settings.
In case the user settings call is not finished by the time of the "relogin", the "relogin" waits for the current _unauthorized_ user settings request to return and gets a 401 from the API.
This was easy enough to fix, but shows that GET requests might also lead to some unexpected behaviour.

I think I'd like in-flight caching to be opt-in, which would also make it less "magic" for everyone new to reactive programming concepts.

**Comment by ashfurrow** [comment]
Yeah, I dunno. Seems like this might be more trouble than it's worth, but @aschuch and @kzaher are right – this should definitely be opt-in.

**Comment by ashfurrow** [comment]
Fixed in https://github.com/Moya/Moya/pull/232 – currently in 3.0.0-develop branch.
