### ISSUE TITLE
Reference to member cannot be resolved without a contextual type

### ISSUE THREAD

**Issue by bnussey** [Moya/Moya#1641]
I'm using Moya 11 and have been working on adding in the ability to refresh an auth token if a `401` is detected. I'm doing this by subclassing the provider.

All was looking good, but very strangely, when I try and build the code, I get an error:

`Reference to member 'authorizeRefresh' cannot be resolved without a contextual type`

Which relates to:

`return self.provider.rx.request(.authorizeRefresh(token: refreshToken))`

I've also tried prefixing it with StageAPI (the enum where all our endpoints are defined) and this results in the following error:

`Cannot invoke 'request' with an argument list of type '(StageAPI)'`

I am able to make this call in other parts of my project.

Does anyone have any ideas as to why such an error would occur? Its really got me stumped. 

Here is the code:

```swift
class StageProvider<Target>: MoyaProvider<Target> where Target: TargetType {

    fileprivate let provider: MoyaProvider<Target>

    init(endpointClosure: @escaping MoyaProvider<Target>.EndpointClosure = MoyaProvider<Target>.defaultEndpointMapping,
        requestClosure: @escaping MoyaProvider<Target>.RequestClosure = MoyaProvider<Target>.defaultRequestMapping,
        stubClosure: @escaping MoyaProvider<Target>.StubClosure = MoyaProvider.neverStub,
        manager: Manager = MoyaProvider<Target>.defaultAlamofireManager(),
        plugins: [PluginType] = [],
        trackInflights: Bool = false
    ) {
        self.provider = MoyaProvider(endpointClosure: endpointClosure, requestClosure: requestClosure, stubClosure: stubClosure, manager: manager, plugins: plugins, trackInflights: trackInflights)
    }

    func authRequest(_ token: Target) -> Single<Response> {
        return provider.rx.request(token)
            .flatMap({ (response) -> PrimitiveSequence<SingleTrait, Response> in
                if response.statusCode == 401 {
                    if let refreshToken = AuthorizationConfiguration.refreshToken {
                        return provider.rx.request(.authorizeRefresh(token: refreshToken))
                            .map(AuthorizationStageResponse.self, atKeyPath: "result")
                            .map({
                                AuthorizationConfiguration.storeAuthorizationConfiguration($0.tokens)
                            })
                            .flatMap({ _ in
                                return self.authRequest(token)
                            })
                    }
                    else {
                        return Single.just(response)
                    }
                }
                else {
                    return Single.just(response)
                }
            })
    }


}
```

**Comment by sunshinejr** [comment]
Hey @bnussey. So you are able to use `self.provider.rx.request(.authorizeRefresh(token: refreshToken))` in one part of the app and you can't in the other? If yes, please copy parts of the code surrounding the request - one that works and one that doesn't work. Also, please copy the code for `TargetType` that you use (with `. authorizeRefresh(token:)` case).
