### ISSUE TITLE
.success Status Code: 405 . Urgent need your help！

### ISSUE THREAD

**Issue by GTMYang** [Moya/Moya#1645]
For continuous launched the same request，I've got the following result:

result is .success(Status Code: 405, Data Length: 70)

Message is:
The requested resource does not support http method 'T'.

Urgent need your help！

**Comment by sunshinejr** [comment]
Hey @GTMYang, thanks for the issue. It seems like it's a similar one to the https://github.com/Moya/Moya/issues/1533. Could you check if your backend is using `Spring`? It seems like this might be the issue here.

**Comment by GTMYang** [comment]
@sunshinejr No. I have not using Spring.

**Comment by SD10** [comment]
@GTMYang Can you use the `NetworkLogger` plugin to get more information about the HTTP request and response?

**Comment by GTMYang** [comment]
@sunshinejr @SD10 Is not moya's bug. it's my backend's issue!  Thank you very much!

**Comment by GTMYang** [comment]
@sunshinejr @SD10 Maybe is Moya's issue. Because when i use Alamofire to do the same request, worked well!

**Comment by GTMYang** [comment]
I found that when i use following code the problem appear：
.requestCompositeParameters(bodyParameters: [:], bodyEncoding: JSONEncoding.default, urlParameters: self.parameters)

when i use  .requestParameters(parameters: self.parameters, encoding: URLEncoding.default)
the problem not appear.

the real is that  when i set   
    Content-Type: application/json
problem appear.

**Comment by wongwenlei** [comment]
The same problem I encountered, how do you solve it?
