### ISSUE TITLE
Can Path and JSON Body work together?

### ISSUE THREAD

**Issue by sunnyleeyun** [Moya/Moya#1649]
I'm new to moya. I've got a case as below. I need to use both path and JSON Encoding.

```swift
case updateCart(memberid: String, Cartidx: String, Num: Int)
```

As memberid goes to the path.

```swift
case .updateCart(let memberid):
  return "Cart/\(memberid)"
```
and Cartidx & Num goes as JSON

```swift
case let .updateCart(_, Cartidx: Cartidx, Num: Num):
  return .requestParameters(parameters: ["Cartidx": Cartidx, "Num" : Num], encoding: JSONEncoding.default)
```

However, it doesn't seem to work. I tested it by removing 'memberid' and embed a fake one, such as cxxxx-xxxx-xxxxxxxx, temporarily. As it turned to be like

```swift
case updateCart(Cartidx: String, Num: Int)

case .updateCart:
  return "Cart/cxxxx-xxxx-xxxxxxxx"

case let .updateCart(Cartidx: Cartidx, Num: Num):
  return .requestParameters(parameters: ["Cartidx": Cartidx, "Num" : Num], encoding: JSONEncoding.default)
```

It worked in that way, but I'm still not able to solve the problem. I supposed the two things somehow conflict. My question is that how can I make Path and JSON both work in this case?

**Comment by sunshinejr** [comment]
Hey @sunnyleeyun. Have you maybe tried using `requestCompositeParameters`? It should allow you using parameters both in URL (with `URLEncoding`) and in body (`JSONEncoding` in that case).

**Comment by sunnyleeyun** [comment]
@sunshinejr As a matter of fact, I did. Maybe I misunderstood. Before answering this, I tried:
```swift
case let .updateCart(memberid: memberid, Cartidx: Cartidx, Num: Num):
  return .requestCompositeParameters(bodyParameters: ["Cartidx": Cartidx, "Num" : Num], bodyEncoding: JSONEncoding.default, urlParameters: ["memberid": memberid])
```
Clear error. (status code: 400)

However, after reviewing your answer, I tried again.
```swift
case let .updateCart(memberid: memberid, Cartidx: Cartidx, Num: Num):
  return .requestCompositeParameters(bodyParameters: ["Cartidx": Cartidx, "Num" : Num], bodyEncoding: JSONEncoding.default, urlParameters: ["memberid": memberid])
```
Still an error. (status code: 405 -> wrong method or wrong parameter. In this case, probably wrong parameter).
I supposed it referred to two completely different result. I'm not so sure how exactly requestCompositeParameters worked, but it seems kind of strange putting ["memberid": memberid] in the urlParameters. How can I adjust above request to the "path" of like solution? Thanks a lot!

**Comment by sunshinejr** [comment]
Okay it seems like you want url like `https://url.to/path/MEMBER_ID` instead of `https://url.to/path?memberId=MEMBER_ID` so it's really a custom situation.

Then you should probably use `.requestParameters(parameters: ["Cartidx": Cartidx, "Num" : Num], encoding: JSONEncoding.default)` and have `memberId` in the `path` as you had before. Probably though you would need to make an encoding on your `path` by yourself.

One thing that could help you with debugging your requests/responses is our `NetworkLoggerPlugin`. In your `MoyaProvider` instance add `plugins` parameter:
```
let provider = MoyaProvider<Endpoint>(plugins: [NetworkLoggerPlugin(verbose: true)])
```

This way you will get logs in the console every time there is a request/response. You could then copy/paste your request and tell us exactly what are you sending in URL and what is the expected behavior.

**Comment by SeRG1k17** [comment]
@sunshinejr Hello, I think. It's like my question #1647

**Comment by kaleemozitech** [comment]
Yes Path and JSON Body work together

**Comment by sunnyleeyun** [comment]
@SeRG1k17 I don't think it's the same. The path I meant was not "query string".
@kaleemozitech How exactly?

**Comment by sunnyleeyun** [comment]
@sunshinejr Yes, I'd like url as `https://url.to/path/MEMBER_ID` , but what do you mean "Probably, though, you would need to make an encoding of your path by yourself." I supposed I'm doing things half right. Is there any example I could take as an example.

**Comment by SeRG1k17** [comment]
@sunnyleeyun You can’t use dynamic formatting in path variable.

**Comment by sunnyleeyun** [comment]
@SeRG1k17 It's possible to use `return "Cart/\(memberid)"` at the path target, so I supposed this means we can use dynamic formatting in path variable, but perhaps not combining with dynamic task target.

**Comment by SD10** [comment]
@sunnyleeyun Can you configure the path in the `baseUrl` instead?

**Comment by kaleemozitech** [comment]
@sunnyleeyun this is how exactly 

var path: String {
        switch self {
        case let .cities(str:str):
            return "/home/cities/\(str)"
        default:
           return "/home"
}
}

**Comment by kaleemozitech** [comment]
@sunnyleeyun did you get success

**Comment by kaleemozitech** [comment]
here is one more answer 
https://github.com/Moya/Moya/issues/909

**Comment by kaleemozitech** [comment]
here is one more Answer if you want to use Both JSON and URL Encoding
https://github.com/Moya/Moya/issues/1059

**Comment by sunnyleeyun** [comment]
@kaleemozitech  Thanks for your reply. Can you take a look at my question above? Cause it seems that I did exactly as you said at the very beginning. However, it wasn't working. Perhaps there's something I missed or went wrong which I didn't recognized.
