### ISSUE TITLE
How to use delayed stub with RxTest.TestScheduler?

### ISSUE THREAD

**Issue by gobetti** [Moya/Moya#1650]
Moya version: 11.0.1

**Context:**
Hi! I'm reasonably new to Moya so I may be overlooking this, hence this is just a question. I've recently migrated to RxTest and all tests using `immediatelyStub` worked perfectly, but I'm having trouble with the cases where I need `delayedStub`. I'd really like to simulate network work in my unit test (while still using stubs) and count on the perfect precision of RxTest when it comes to comparing events timestamps, however the `delayedStub` seems (in a first look) stuck to real world time units instead of being able to use `TestScheduler`'s virtual time.

So when I noticed that the following code is inside an `open`-declared method, my first thought was to subclass `MoyaProvider`:
```swift
case .delayed(let delay):
    let killTimeOffset = Int64(CDouble(delay) * CDouble(NSEC_PER_SEC))
    let killTime = DispatchTime.now() + Double(killTimeOffset) / Double(NSEC_PER_SEC)
    (callbackQueue ?? DispatchQueue.main).asyncAfter(deadline: killTime) {
        stub()
    }
```

But subclassing doesn't _feel_ right, given that Moya 9.0 deprecated the old `RxMoyaProvider` in favor of extension methods, so maybe I should be only extending as well. Also I have problems even for getting to a compilable version when subclassing `MoyaProvider` without having to add more code than just the only method I'd like to override, but that's a side subject that we can move to a whole new issue if desired 😃 

▶️ **Question:**
So is there a way to use `TestScheduler` to delay (in virtual time) responses when using stubs?

If not, then I'm willing to help with this because RxTest is a must to me, just please let me know your constraints for this implementation so I can start thinking about an architecture that doesn't break your purposes. For example, possibly #1502 would change how to address this (for better or for worse, I don't know right now).

Thank you very much!

**Comment by sunshinejr** [comment]
Hey @gobetti. That's a great question. So I didn't really use delayed stubs in combination with `TestScheduler` in RxSwift, but I know that people who did, subclassed `MoyaProvider`. 

If there is a way of introducing this to Moya without creating additional subclasses it would be awesome. If not, maybe just adding an example of subclassing to our docs would be sufficient? What do you think?

**Comment by gobetti** [comment]
Hi @sunshinejr , thanks for the fast and kind answer!
If subclassing is still considered a good practice after `RxMoyaProvider` got deprecated, then I'm all for it. An example may help, but I can anticipate that currently there is a single method in `MoyaProvider` handling all `StubBehavior` cases and I'd like to override only the `delayed` one (the one where a scheduler will make sense since there's timing embedded). This method has the following signature:
```swift
open override func stubRequest(_ target: Target, request: URLRequest, callbackQueue: DispatchQueue?, completion: @escaping Moya.Completion, endpoint: Endpoint, stubBehavior: Moya.StubBehavior) -> CancellableToken
```
Internally, it does this:
`let callbackQueue = callbackQueue ?? self.callbackQueue`
However notice that `callbackQueue` is internal in MoyaProvider, so given that I want to keep this code, I need to create another of that property in my subclass.

Also, my `TestScheduler` needs to be injected in my `MoyaProvider` subclass via its initializer, so that I don't modify the signature of the overridden method. But here again I had problems because I wanted to keep all the same parameter default values, and some won't work at least not in a first naive attempt.

So in brief, an example that:

1. Overrides `stubRequest` by replacing the code for one of the stub behaviors
2. Exposes a new initializer with an additional parameter, while keeping all the same parameter default values from the `MoyaProvider` subclass

will definitely be all I need! 😄 

Thank you again!

**Comment by sunshinejr** [comment]
Oh, I thought that you wanted to take a stab at it and create a PR with the example, @gobetti 😄 My time is limited right now so maybe you could try to do it and I could help you with your questions in a PR?

**Comment by gobetti** [comment]
Hi guys! I'm sorry, but for my purposes, it ended up being a simpler approach to write a new network layer on top of RxCocoa, whereas Moya does it from scratch and provides reactified versions via extensions, making it fully decoupled from RxSwift/RxCocoa - which is a great point, but not something I'm taking benefit from given that I don't want to decouple my project anyway :)

Thanks for your time and attention, and feel free to close this discussion as stale or however fits best for you. If I ever need to dig into this again, I'll surely dedicate some time and contribute!

**Comment by SD10** [comment]
@gobetti No problem 👍 Glad you found a solution

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
