### ISSUE TITLE
i did not find any way to pass JSON instead of Sending parameters 

### ISSUE THREAD

**Issue by kaleemozitech** [Moya/Moya#1651]
i was going to call a API that takes more then 15 parameters in Body and it doesn't looks good to send such number of parameters in function call /Moya Api Call
and I think Passing Full JSON Will be a Good option for such type of problems

**Comment by SeRG1k17** [comment]
@kaleemozitech  Please take a look at my answer #1629
This is what you need? If yes, I think it can be closed.

**Comment by kaleemozitech** [comment]
@SeRG1k17 #1629 did not solved the issue of passing JSON (Created from Some Model)
i am talking about 
case .youCase, return .requestParameters(parameters: myJSONobject, encoding: URLEncoding.queryString)

**Comment by kaleemozitech** [comment]
@SD10  thanks
