### ISSUE TITLE
Html code in response object 

### ISSUE THREAD

**Issue by Pawlo1501** [Moya/Moya#1652]
pod 'Moya/RxSwift', '~> 11.0'

Hi im' getting from server strings like in an example. Is there any tool in Moya to decode these html characters in response to normal string which I could use in labels? 

```swift
example "Who wrote &quot;Harry Potter&quot;?"	
```

**Comment by kaleemozitech** [comment]
use   case let .success(moyaResponse):
                moyaResponse.mapString()

**Comment by SeRG1k17** [comment]
Don’t forgot handle do/catch here

**Comment by SeRG1k17** [comment]
And statuscode filtering before mapping

**Comment by kaleemasad** [comment]
Yes exactly right https://github.com/SeRG1k17

**Comment by Pawlo1501** [comment]
thanks for response but when i have code like this
`  self.provider.rx.request(.getObjects).debug().map(ObjectsList.self).asObservable().subscribe(
                onNext: { [weak self] model in
                    guard let objects = model.list, let firstObject = objects.first else {return}
                    self?.firstObject.value = firstObject
                    onNext(objects)
                },
                onError: { error in
                    print(error.localizedDescription)
            }).disposed(by: self.disposeBag)
        }`

And this "firstObject" is a class object with property "text" and in this "text" sometimes i'm getting this html code

**Comment by jdisho** [comment]
@Pawlo1501  I don't think that Moya has any function to parse the `HTML strings` (@SD10 correct me if I am wrong).

Btw, with the suggestion from @kaleemozitech you can only map the entire `response` as `string`.

**Comment by Pawlo1501** [comment]
Ok thanks all for your help!
