### ISSUE TITLE
requestCompositeParameters is not working 

### ISSUE THREAD

**Issue by kaleemozitech** [Moya/Moya#1653]
i want to send bodyParameters in Composite request and i am using .post method but its not working fine and not passing body parameters and i am getting error from server

`return .requestCompositeParameters(bodyParameters: ["city" : 1], bodyEncoding: JSONEncoding.default , urlParameters: ["_method" : "put"])`

**Comment by kaleemozitech** [comment]
and i got succeeded using Multipart With Parameters 

`  let multipartData = [ name, gender, date_of_birth, city, address, servicesObj]
            return .uploadCompositeMultipart(multipartData, urlParameters: ["_method" : "put"])`

**Comment by sunshinejr** [comment]
Hey @kaleemozitech. Please use `NetworkLoggerPlugin(verbose: true)` and post the logs here.
