### ISSUE TITLE
How to pass a semicolon in url with POST method?

### ISSUE THREAD

**Issue by andy1247008998** [Moya/Moya#1661]
I know it's kind of wired to have parameters in url and body at the same time, but www.example.com is out of my control, so please help me.

target url:
`https://www.example.com/example/login.do;jsessionid=\(jsessionid)"`

method:
POST

body:
`param1=abc&param2=def&param3=ghi`

Here's the problem:
That `;` in the url is always escaped to `%3B`.

Is there anything in the PATH section like this ?
`return "/example/login.do;jsessionid=\(jsessionid)".doNotEscapeMe()`

**Comment by SD10** [comment]
@andy1247008998 You probably have to make a custom URLEncoding for this. The easier, more hacky way would be for you to not use the `path` variable but rather declare the path as part of the `baseUrl`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by andy1247008998** [comment]
I figured it out myself.

In TASK section, 
change
```
return .requestParameters(parameters: [
                "org.apache.struts.taglib.html.TOKEN": token,
                "userid": userid,
                "password": password
                ], encoding: URLEncoding.queryString)
```
to
```
return .requestParameters(parameters: [
                "org.apache.struts.taglib.html.TOKEN": token,
                "userid": userid,
                "password": password
                ], encoding: URLEncoding.default)
```

**Why is the encoding here also affects the encoding for baseURL and path?**

Anyway, I will close this issue.
