### ISSUE TITLE
Can I not set the baseURL?

### ISSUE THREAD

**Issue by panjiulong** [Moya/Moya#1664]
The baseURL of our project is changed. There are several baseURLs, so we can not specify baseURL?

**Comment by jdisho** [comment]
All baseURLs have the same endpoints? @panjiulong

**Comment by SD10** [comment]
@panjiulong I would make a protocol `BaseUrlRepresentable` with the baseURL property and then conform all your targets to that. Alternatively you could just provide a default implementation via protocol extension on `TargetType` if all base URLs are the same

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jdisho** [comment]
Like this? @SD10 

```swift 
protocol BaseUrlRepresentable {
      var baseULR1: URL {get}
      var baseULR2: URL {get}
      ...
}
```
and then 

```swift
extension GithubAPI: TargetType, BaseUrlRepresentable {
      ....
}
```

**Comment by SD10** [comment]
@jdisho if there are two different urls than that works

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by panjiulong** [comment]
@ SD10  @jdisho  Thanks!
