### ISSUE TITLE
Pod Moya/RxSwift broke Xcode autocompletion for Rx-pods

### ISSUE THREAD

**Issue by snowtema** [Moya/Moya#1665]
If I connect Moya/RxSwift pod to my project I had an unexpected trouble with autocompletion in Xcode and AppCode, it doesn't work. If I disconnect it works fine.

RxSwift v.4
Moya v.11

**Comment by BasThomas** [comment]
That's interesting. Can you share your whole Podfile?

**Comment by snowtema** [comment]
Podfile

    platform :ios, '11.0'
    use_frameworks!

    target 'Workout' do
      # Analytics
      pod 'Fabric', '~> 1.7.3'
      pod 'Firebase/Core', '~> 4.9'
      pod 'Firebase/Messaging', '~> 4.9'
      pod 'Crashlytics', '~> 3.10.0'
  
      # Reactive
      pod 'RxSwift', '~> 4.1.2'
      pod 'RxCocoa', '~> 4.1.2'
      pod 'RxDataSources', '~> 3.0.2'
      pod 'Action'
      pod 'RxFlow', '~> 1.2.0'
      pod 'RealmSwift', '~> 3.0.2'
      # pod 'Moya/RxSwift'

      # Network & parsing
      pod 'Moya', '~> 11.0'
      pod 'Unbox', '~> 2.5.0'
      pod 'Kingfisher'

      # UI
      pod 'Reusable', '~> 4.0.0'
      pod 'Hero', '~> 1.1.0'

      # Colors
      pod 'DynamicColor', '~> 4.0.1'
      pod 'UIImageColors', '~> 2.0.0'
    end

**Comment by BasThomas** [comment]
🤔, not sure if there are some clashes with `RxSwift` possibly. Moya [now depends on 4.0](https://github.com/Moya/Moya/blob/0b90f7ee8dcc378fe48db18c8b281e8792244de9/Moya.podspec#L39), while you specified 4.1.2.

Can you try to remove the `RxSwift` dependency and check if the problem persists?

If so, can you post your `Podfile.lock`?
