### ISSUE TITLE
Lazy subscription after rx provider release

### ISSUE THREAD

**Issue by kjisoo** [Moya/Moya#1667]
I found a problem when using the RxProvider.

You can create a Single through a request from an RxProvider, but you can not subscribe to it immediately.
If I create a request through the RxProvider and the RxProvider is released from memory before subscribing to the Single, Single will not happen.
(Maybe This is bad code.)
like this
``` swift
class Foo {
  let single: Single<Some>
  init() {
    self.single = Provider<SomeTarget>().rx.request(.foo)
  }
  func subscribe() {
    self.single.subscribe() // single never success or fail
  }
}
let foo = Foo()
foo.subscribe()
```

`MoyaProvider+Rx.swift` will use `base?.request`, but nothing happens because base is nil.

What about giving an error in this situation?

**Comment by SD10** [comment]
@kjisoo I believe this is the intended behavior, you need to retain your provider.
See the folliwng issues:
#1496 Incorrect Retainment Model for RxSwift extension in MoyaProvider
#905 Providers that are deallocated never completes
#1267 Objects with RxMoyaProvider are no longer retained in 9.0
#1294 Fixing potential issue with RxSwift request method
#1311 Stop retaining self in rxReuestWithProgress
