### ISSUE TITLE
utf-8

### ISSUE THREAD

**Issue by marshallee** [Moya/Moya#1676]
My server dose not support unicode， so how can I transfer all paramaters to utf-8?

**Comment by sunshinejr** [comment]
Hey @marshallee, sorry but this is not really a question to Moya, rather to Swift - you could try using [StackOverflow](https://stackoverflow.com/questions/44702613/remove-occurrence-of-unicode-character-uef-from-string-in-swift-3). Generally you would need a function that finds any unicode character in your params and replace/remove it.  

Sorry, but I have to close this one - hope you understand! 🐼
