### ISSUE TITLE
Directly crash in Release

### ISSUE THREAD

**Issue by R-U-N** [Moya/Moya#1678]
![image](https://user-images.githubusercontent.com/22491697/40955187-19255298-68bb-11e8-98fd-6c62617e6ea6.png)
When I change my build configuration to Release。It directly crash like this。What should i do？

**Comment by R-U-N** [comment]
I fix this by setting optimization to None in Release Tempoary。I hope I can find out what's the problem by my abilty limited me。So wish you can fix it

**Comment by SD10** [comment]
@R-U-N This is a bug in the Swift compiler 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by glennposadas** [comment]
@SD10 , does that mean users in prod would experience such crash? I experienced that tonight so I went here. Thank you.

**Comment by LeoQingit** [comment]
I meet this issue too. How can I fixed it?

**Comment by LeoQingit** [comment]
excuse me, Its my code issue . sorry

**Comment by ReflectionMzy** [comment]
> 对不起，这是我的代码问题。抱歉

how to solve this problem？ thx

**Comment by fl034** [comment]
@SD10 got this problem with Moya 13.0.1 via SPM when in Release mode.
I guess since updating to Xcode 11.2.1.
Any suggestions?

**Comment by gerchicov-vg** [comment]
I have the same problem:
https://github.com/Moya/Moya/issues/2351
but Moya 15.0.0 and installed with cocoapods

**Comment by gerchicov-vg** [comment]
@R-U-N @LeoQingit @fl034 @SD10 are you at least able to reproduce it in debug or release mode? In my case it appears in App Store build only and not always.
