### ISSUE TITLE
Consider moving Moya to an organization

### ISSUE THREAD

**Issue by ashfurrow** [Moya/Moya#168]
I've never had an open source project reach this level of popularity – I think it's time we consider whether or not it makes sense to move Moya off of my own personal GitHub account. I've not run an organization before, either. 

Benefits:

- Easier to mention all contributors in important issues/PRs.
- Emphasizes that this is a community project and not a personal one.
- We could separate Moya into distinct repositories, one for the core, one for ReactiveCocoa, and one for RxSwift.
- Adding new, related libraries would be easy and be on the same organization.

Drawbacks:

- Existing podspecs, cartfiles, submodules will need to move over to the new URL (redirects seem to stop working after a month in my experience).
- I don't get my name all over the project anymore.

Is anyone else aware of other tradeoffs? @orta?

**Comment by orta** [comment]
If you're thinking about it, then it should probably be done. Given that `/moya` isn't free, you might want to consider if you can think of other sibling projects that could go with it.

The distinct repos sounds like a bunch of faffing though to me FWIW.

**Comment by ashfurrow** [comment]
Good points. 

Distinct repos would solve our Carthage problem; they refuse to implement subspec-style libraries because it "encourages large libraries." Could be something CocoaPods could do – it crease a project now, maybe one with separate framework targets for different subspecs?

**Comment by orta** [comment]
Would probably be a pretty reasonable CP plugin for lib authors wanting to make binary releases.

**Comment by ashfurrow** [comment]
Leaning more in favour of this. We should probably add a [CoC](http://contributor-covenant.org) while we're at it.

**Comment by ashfurrow** [comment]
So, since no one has any objections, I've decided to go ahead with this. Here are the steps we'll need to take:

- [ ] Think of an organization name (this is the hardest part).
- [ ] Create a new org.
- [ ] Add Moya contributors as admins to the org.
- [ ] [Transfer the repo](https://help.github.com/articles/transferring-a-repository/) to the org.
- [ ] Create an org code of conduct.
- [ ] Send a PR to CocoaPods/Specs to change the git URLs to the new endpoint. (Right?)

Any other steps? Any suggestions on a name?

**Comment by colinta** [comment]
What other projects will be in this org?  We can ask github to make github.com/Moya available.

**Comment by orta** [comment]
>  Send a PR to CocoaPods/Specs to change the git URLs to the new endpoint. (Right?)

Yep, the default redirects will work, but not forever.

> Any suggestions on a name?

MoyaAPI, MoyaNetworking, nothing strikes me as awesome. Will ask @moya if it can be transferred.

**Comment by ashfurrow** [comment]
Cool, yeah. 

@colinta Initially, it'd just be this repo and probably a demo or two showing how to use Moya. In the long run, I'd love to see the org grow to include new functional-ish ways to use Swift to solve problems on iOS and OS X. It would be awesome to have a sort of meta repo where we could keep a list of ideas for projects. That way if someone had an idea, or needs an idea, they have a space they can get more help than on their own.

**Comment by ashfurrow** [comment]
@orta Thanks for asking :)

**Comment by orta** [comment]
Given the lack of a reply from @moya I think it might make sense to go with MoyaAPI ?

**Comment by ashfurrow** [comment]
Or MoyAwesome :stuck_out_tongue: 

MoyaAPI just seems so... _pedestrian_.

**Comment by Palleas** [comment]
Is there any chance the @github support could intervene, a bit like the twitter one does when you request an unused account (for good reason)?

**Comment by ashfurrow** [comment]
It's possible, but the user could have private activity that we just can't see. I don't want to write them off :)

Moya is named after [a living spaceship](https://en.wikipedia.org/wiki/List_of_Farscape_characters#Moya). **puts on nerd glasses** Moya doesn't speak, so she doesn't have a voice actor, but she's biologically bonded to a pilot, voiced by Lani Tupu. It's [been suggested](https://twitter.com/twannl/status/628670104667070464) that using some variation of that name might work, though those names are taken. I'd be pretty cool with using another homage to Farscape, too, but everything I found was too on the nose.

**Comment by colinta** [comment]
github.com/Leviathon/Moya

**Comment by ashfurrow** [comment]
Nah, https://github.com/Leviathan/ is taken.

**Comment by colinta** [comment]
Dang it, I spelled "Leviathan" incorrectly.  github.com/Leviathan is taken.

**Comment by ashfurrow** [comment]
I've been in contact with GitHub support, and https://github.com/Moya is now an organization I control. I'll be adding contributors as team members there, then transferring and doing related chores hopefully today, maybe tomorrow. 

:tada:

**Comment by colinta** [comment]
Awww I JUST got the same email from github, and I was hoping to bring a present to the discussion today!

Well, “HUZZAH” nonetheless.  These other names were… less good. ;-)

**Comment by SRandazzo** [comment]
:tada:

**Comment by esttorhe** [comment]
Awesome sauce! :tada: 

:clap:

**Comment by ashfurrow** [comment]
OK, so I've submitted a PR to update the Moya podspecs: https://github.com/CocoaPods/Specs/pull/13370

Circle CI needs to enabled the iOS beta on the Moya organization, so our CI will be broken until they flip that switch. 

I've also submitted this PR on Moya to update docs, CI, etc: https://github.com/Moya/Moya/pull/175 If one of @Moya/contributors could take a look, that'd be awesome!
