### ISSUE TITLE
Moya/RxSwift - stubs and multiple sample data per endpoint

### ISSUE THREAD

**Issue by pgawlowski** [Moya/Moya#1682]
Version - Moya/RxSwift
UnitTests case scenario.

Hey guys. I am trying to figure out how to use sample data and stubs/stubClosure for unit tests.

The case is to be able to provide multiple, different sample data according to test.
Exmaple 

```swift
    var sampleData: Data {
        var response: String = ""

        switch self {
        case .getNeedsApproval:
            response = "{ needsApproval: true }"
         }
         return response.data(using: .utf8)!
       }
```
In that case. I would like to be able to provide response with true/false as well as different statusCodes from 200 to 404, 401, 400 etc. 
The solution I am looking for supposed to be as much generic as possible. 

Am I supposed to prepare separate stubs for different response codes? If yes how to differentiate sampleData per stub?

The main problem is I am actually not sure how to mix sample data and stub closures for my case. Any hints and ready to use code samples are welcome.

**Comment by SD10** [comment]
@pgawlowski You're going to need to create some boolean properties or another enum and then switch on them inside of your `TargetType` to determine which `sampleData` or which `stubClosure` you'd like to use.
