### ISSUE TITLE
Different timeout for upload APIs

### ISSUE THREAD

**Issue by DavidTomic** [Moya/Moya#1683]
Hi,

I am using Moya 10.0.2

Is there any way to set a timeout for upload APIs e.g. 120s, and for the rest APIs to be e.g. 10s.

**Comment by WeiRujian** [comment]
```
//MARK: - 设置请求超时时间
fileprivate var requestTimeOut: Double = 15
//MARK: - endpointClosure
fileprivate let myEndpointClosure = { (target: NetworkApi) -> Endpoint in
    let url = target.baseURL.absoluteString + target.path
    
    let endpoint = Endpoint(url: url,
                            sampleResponseClosure: { .networkResponse(200, target.sampleData) },
                            method: target.method,
                            task: target.task,
                            httpHeaderFields: target.headers)
    
    
    // 修改请求超时时间
    switch target {
    
        /// 上传60s超时
    case .DocTransCoding,
         .ImgTransCoding:
        
        requestTimeOut = 60.0
        
    default:
        requestTimeOut = 15
    }
    
    return endpoint
}
//MARK: - requestClosure
fileprivate let myRequestClosure = { (endpoint: Endpoint, done: @escaping MoyaProvider<NetworkApi>.RequestResultClosure) in
    
    do {
        var request = try endpoint.urlRequest()
        request.httpShouldHandleCookies = false
        request.timeoutInterval = requestTimeOut
        
        
        done(.success(request))
    } catch {
        
        done(.failure(MoyaError.underlying(error, nil)))
    }
}
```

**Comment by WeiRujian** [comment]
OK，Can achieve the desired effect？

**Comment by DavidTomic** [comment]
@WeiRujian I tried above but without success.

I end up with a solution to initialize two providers with different SessionManagers. One SessionManager has timeout 10s and the second one 120s.

The second provider I am using for uploading media files, and the first one for rest.

**Comment by SuiFengLiuNian** [comment]
> ```
> //MARK: - 设置请求超时时间
> fileprivate var requestTimeOut: Double = 15
> //MARK: - endpointClosure
> fileprivate let myEndpointClosure = { (target: NetworkApi) -> Endpoint in
>     let url = target.baseURL.absoluteString + target.path
>     
>     let endpoint = Endpoint(url: url,
>                             sampleResponseClosure: { .networkResponse(200, target.sampleData) },
>                             method: target.method,
>                             task: target.task,
>                             httpHeaderFields: target.headers)
>     
>     
>     // 修改请求超时时间
>     switch target {
>     
>         /// 上传60s超时
>     case .DocTransCoding,
>          .ImgTransCoding:
>         
>         requestTimeOut = 60.0
>         
>     default:
>         requestTimeOut = 15
>     }
>     
>     return endpoint
> }
> //MARK: - requestClosure
> fileprivate let myRequestClosure = { (endpoint: Endpoint, done: @escaping MoyaProvider<NetworkApi>.RequestResultClosure) in
>     
>     do {
>         var request = try endpoint.urlRequest()
>         request.httpShouldHandleCookies = false
>         request.timeoutInterval = requestTimeOut
>         
>         
>         done(.success(request))
>     } catch {
>         
>         done(.failure(MoyaError.underlying(error, nil)))
>     }
> }
> ```
myEndpointClosure 这个闭包哪里用到了？？？
