### ISSUE TITLE
How to send string as a url query with encoding?

### ISSUE THREAD

**Issue by vishal91** [Moya/Moya#1685]
How to send this { \"where\":{\"isApproved\":true, \"categoryId\":" + categoryId + "} }
as url query with encoding?

**Comment by vishal91** [comment]
is encoded as : **%3ForderBy=priority+asc%3F%7B%5Cwhere%5C:%7B%5CisApproved%5C:true,%5CcategoryId%5C:2%7D%7D**

**Comment by hamdshah** [comment]
In the `Task` you can mention the type of encoding
https://github.com/Moya/Moya/blob/master/Sources/Moya/Task.swift#L19
