### ISSUE TITLE
How to work rxMoya Single<Model>

### ISSUE THREAD

**Issue by ZZHHAANNGG** [Moya/Moya#1689]
I'm using Moya 11.0.2

I tried to return a Single<Response> from a ViewModel to a ViewController, and then bind to a UITableView.

How should I return a Single to subscribe later?

**_The error is:_**

Cannot convert return expression of type 'PrimitiveSequence<SingleTrait, Response>' to return type 'SharedSequence<SignalSharingStrategy, Response>''

```swift
import Foundation
import Moya
import RxCocoa
import RxSwift

struct ProductsViewModel {
    let provider:MoyaProvider<SSX>
    
    func fetchProducts() -> Signal<[ProductModel]> {
        return provider.rx.request(.fetchProducts())
    }
}

extension ProductsViewModel {

}
```

**Comment by hamdshah** [comment]
@ZZHHAANNGG 
If you can share some more code then it would be helpfull to understand the problem, but from the current sample looks like that 
`provider.rx.request` returns `Single<Request>` while your function return type is `Single<[ProductModel]>` so you have to map it to the model first.

**Comment by ZZHHAANNGG** [comment]
Thanks for pointing out the wrong general type issue.
