### ISSUE TITLE
How to configure the specified encoding?

### ISSUE THREAD

**Issue by AndRickyChan** [Moya/Moya#1691]
The version number I used is Moya ~>11.0,  But when I submitted Chinese request, there was a garbled phenomenon. so,  I want to know how to configure th specified encoding so that I can save this problem

**Comment by hamdshah** [comment]
Source:
https://github.com/Moya/Moya/blob/master/Sources/Moya/Task.swift#L19
Example 
https://github.com/Moya/Moya/blob/master/docs/Examples/ParameterEncoding.md

**Comment by AndRickyChan** [comment]
Could you please tell me what's the default encoding in this framework?
