### ISSUE TITLE
How do I get parameters to cache the requested data？

### ISSUE THREAD

**Issue by Ethan561** [Moya/Moya#1694]
I wanted to use url + parameters to cache the requested data, but in the latest version I couldn't get the parameters I requested

let key = cacheKey
// cache Key, using BaseURL + Path + Parameter to convert to JSON string

**Comment by SD10** [comment]
Hey @Ethan561, I'm having a little bit of trouble understanding what you're asking here. Can you provide some more info and maybe someone can assist you?

**Comment by Ethan561** [comment]
[Network.zip](https://github.com/Moya/Moya/files/2212094/Network.zip)

HD_LY_NetHelper.swift and HDCache.swift 

                    //请求成功
                    case Status_Code_Success :
                        success(response.data)
                        if cache == true {
                        
                            let url = target.baseURL.appendingPathComponent(target.path).absoluteString
                            let key = HDCache.default.cacheKey(url, nil)
                            HDCache.default.setObject(response.data, forKey: key)
                            LOG("缓存成功：\(url)")
 
                        }

I wanted to get the request parameter for  cacheKey，but I don't know how to get it？
