### ISSUE TITLE
How do I manually escape a character in the path?

### ISSUE THREAD

**Issue by staz1000** [Moya/Moya#1696]
Version: 11.0
Dependancy manager: CocoaPods

I'm working on a forgot password task and need to be able to send emails with a + e.g. _test+test1@example.com_.

If I manually escape the + with a @2B in the TargetType the % gets escaped again into %252B.

How can I fix this? Or do I need to implement my own Endpoint Mapping function?

**Comment by SD10** [comment]
@staz1000 I'm just passing by but maybe one of these issues would help you. You may need to create your own `ParameterEncoding` or like you said, handle this in your own endpoint mapping function.

Related:
#1198 
#1129 
#1030 
#1119 
#1121 
#1059 
#969
