### ISSUE TITLE
How can i send url parameters with .requestCustomJSONEncodable?

### ISSUE THREAD

**Issue by Lang-le** [Moya/Moya#1698]
I want to send request with JSON and url parameter.
But `.requestCustomJSONEncodable` send without url parameters.
So how can i do that? Please help! Thank you!

**Comment by SD10** [comment]
Hey @Lang-le, this doesn't seem to be possible through Moya's `Task` object. It seems to be related to #1647. My solution for you would be to create a [PluginType](https://github.com/Moya/Moya/blob/master/docs/Plugins.md) to add the parameters.

**Comment by Lang-le** [comment]
@SD10 Thanks! I try to custom .requestCustomJSONEncodable and it worked.
Can i submit my code?

**Comment by SD10** [comment]
@Lang-le This has been requested a couple times now so we'll consider adding first class support for this. I was the one who was originally against it because I thought it was an uncommon use case
