### ISSUE TITLE
Stubbed MoyaProvider still invoking network endpoint

### ISSUE THREAD

**Issue by ivanmah** [Moya/Moya#1699]
Hi all, I'm currently on v11.0.2 of Moya, and I'm encountering a similar issue to https://github.com/Moya/Moya/issues/350 where my stubbed MoyaProvider is still invoking the network endpoint.

My code is fairly straightforward, and looks like this:

`var testProvider = MoyaProvider<TestTarget>(stubClosure: MoyaProvider.immediatelyStub)`

Is there something I'm missing out somewhere?

**Comment by SD10** [comment]
Hey @ivanmah, can you show me the configuration for your `TestTarget` type? Thanks
