### ISSUE TITLE
Better image in README

### ISSUE THREAD

**Issue by ashfurrow** [Moya/Moya#170]
This image is misleading:

![](https://raw.githubusercontent.com/ashfurrow/Moya/master/web/bad.png)

It's the first image in the README and is in the "on-brand" Moya colours. A casual reader might infer that this is the Moya solution. 

We should make it clear that this is _not_ how Moya works, but is an example of the problem that Moya solves. Possible solutions:

- Desaturate the image to make it look sad.
- Add sad faces or sad face emojis :cry: 
- Add a rage-comic style "wtf" person – [Jackie Chan](http://wallpaper.ultradownloads.com.br/276253_Papel-de-Parede-Meme-Jackie-Chan_1920x1440.jpg)? 
- Something else.

Suggestions? Thoughts?

**Comment by esttorhe** [comment]
Perhaps leave the introduction paragraph and then a section of

## Current state of apps
![](https://raw.githubusercontent.com/ashfurrow/Moya/master/web/bad.png)

<Rest of that section>

## How `Moya` solves this
![](https://github.com/ashfurrow/Moya/raw/master/web/good.png)
<Next paragraph explaining how Moya works>

**Comment by esttorhe** [comment]
Honestly I like that the image uses `Moya` colors to keep it in sync and consistent with the rest of the README; looks «prettier» IMHO

**Comment by ashfurrow** [comment]
Yeah, that's a good point. Maybe desaturate them a little bit? 

![bad](https://cloud.githubusercontent.com/assets/498212/9091634/49359e7e-3b6f-11e5-8f06-4928713098d3.png)

Meh, that kind of sucks too.

**Comment by esttorhe** [comment]
hahahahaha; it makes me think of infomercials when people are terribly using a normal product product.

Put a filter to make it look «old and archaic»? ¯\\\_(ツ)\_/¯

**Comment by ashfurrow** [comment]
![bad-2](https://cloud.githubusercontent.com/assets/498212/9091876/b2a51e92-3b70-11e5-807f-e65de781836e.png)

**Comment by ashfurrow** [comment]
Hmm.

**Comment by ashfurrow** [comment]
Nah, I think maybe a label saying "BAD" or something would be illustrative.

**Comment by esttorhe** [comment]
Perhaps the «biggest» issue is that the image is the first in the README and as you pointed out could be potentially confusing.

What about putting them both side by side with `current / Moya` as a footnote to the images?

PS. I think the label could work as well but I'm throwing ideas just in case

**Comment by skywinder** [comment]
As option:
As @esttorhe suggested, but this 2 images in a row and add arrow between:
:city_sunset:  :arrow_right:  :rocket:

**Comment by orta** [comment]
might be better to try have both in one image (roughly chucked together)

![screen shot 2015-08-27 at 10 07 21 am](https://cloud.githubusercontent.com/assets/49038/9522553/788e7656-4ca3-11e5-8c1e-df89ff449553.png)

http://cl.ly/0E0u3H422C3F/moya-front.sketch

**Comment by ashfurrow** [comment]
@orta it's a good start, but I think it needs more character. Suggestion: 

![artboard 1](https://cloud.githubusercontent.com/assets/498212/9523674/38babc28-4ca9-11e5-8937-0200a6c753a6.png)

**Comment by esttorhe** [comment]
:shipit:

**Comment by skywinder** [comment]
@ashfurrow  :1

**Comment by orta** [comment]
this this is the direction we're after, I can spruce it up and give it some good arrows etc. I prefer the emoji.

**Comment by ashfurrow** [comment]
Sounds good to me!
