### ISSUE TITLE
What shall I do

### ISSUE THREAD

**Issue by feixue299** [Moya/Moya#1700]
version of Moya
    Moya (11.0.2):
    - Moya/Core (= 11.0.2)
  - Moya/Core (11.0.2):
    - Alamofire (~> 4.1)
    - Result (~> 3.0)
  - Moya/RxSwift (11.0.2):
    - Moya/Core
    - RxSwift (~> 4.0)

![5d3cf8fa-2d12-43a1-bf69-74842668184f](https://user-images.githubusercontent.com/12168109/43177599-981bd538-8ffb-11e8-8ad8-c1aa21c0d967.png)

**Comment by feixue299** [comment]
It doesn't look synchronous
![b84b8578-6b19-40ce-b2d8-68a8c3e65f38](https://user-images.githubusercontent.com/12168109/43178190-a92974ea-8ffe-11e8-951f-c8f8c756ff35.png)

**Comment by SD10** [comment]
@feixue299  It is because you are not retaining your provider. It needs to be at a scope outside of the function definition in order for it to be retained. 

[Providers.md](https://github.com/Moya/Moya/blob/master/docs/Providers.md)

> Always remember to retain your providers, as they will get deallocated if you fail to do so. Deallocation will return a -999 "canceled" error on response.

**Comment by feixue299** [comment]
@SD10 thank you. it work for me.
