### ISSUE TITLE
Moya request call issue

### ISSUE THREAD

**Issue by QiProject** [Moya/Moya#1701]
Moya Version: 11.0.2 by cocoa pods

Hi, I am using RxSwift with Moya/RxMoya,  I found a thing that I can't decide if this is bug :
I have a networking wrapper :

```swift
final class NetService {
    fileprivate let networking = Networking<DeiAPI>()
    func req(name:String)->Single<Response> {
        return networking
            .request(.checkUseName(name: name))
            .do(onSuccess: { (r) in
                "1: \(r)".dd()
            }, onError: { (e) in
                "2 \(e)".dd()
            }, onSubscribe: {
                "3".dd()
            }, onSubscribed: {
                "4".dd()
            }).subscribe(onSuccess: { (r) in
                "subscribe r:\(r)".dd()
            })
    }
  }

//the dd() is a String extension method for printing thing in console.

// so if I do this is viewDidLoad:

NetService().req("Jim") // this doesn't send network request.

// but if I do this :

let netService = NetService()
netService.req("Jim") // this shows up the , 3,4,1,2 in the console, means the network request has sent.
```

I really wonder this behavior and would like to ask the help if
someone could point me out of this, what I think with 'let' it can keep alive the variable,
but in fact, once the scope exits viewDidLoad, neither those variables keep alive anymore.

or this is some bug that I am noticing it ?

**Comment by SD10** [comment]
@QiProject This looks like expected behavior to me, you need to retain your `NetService` object which causes your `MoyaProvider` to be retained as well. 

By using `NetService().req("Jim")` your provider is deallocated immediately

**Comment by QiProject** [comment]
This is what lack of my knowledge, thanks to point it me out !
