### ISSUE TITLE
Downloading image

### ISSUE THREAD

**Issue by KompoD** [Moya/Moya#1702]
Hello! :)
I have a question. Can I download and paste downloaded image in image view using Moya?
P.S. Thanks for your awesome library! 👍

**Comment by BasThomas** [comment]
Hi @KompoD — you can! In the README there is an example of [an endpoint that returns `Data` for an image](https://github.com/Moya/Moya#reactiveswift) which you can then use to initialize a `UIImage`.

**Comment by pedrovereza** [comment]
Hey @KompoD I have an example project that downloads and displays images, it may be helpful: https://github.com/pedrovereza/quote

**Comment by KompoD** [comment]
@BasThomas and @pedrovereza, thanks for your answers! :)
