### ISSUE TITLE
How to refresh the accesstoken in Moya 

### ISSUE THREAD

**Issue by sathishvgs** [Moya/Moya#1705]
I'm using CocoaPod Moya 11.0 which is the latest version

Here, I need to refresh my accesstoken like doing in Alamofire's RequestRetrier and RequestAdapter. After the token got refreshed I need to restart the request. Can anyone explain how should we achieve this in Moya.

Language: Swift 4.3

**Comment by pietrocaselani** [comment]
Hi @sathishvgs 

This is a pretty common issue here, so please, take a look at this [answer](https://github.com/Moya/Moya/issues/1536#issuecomment-356273395).

Let us know if this solves your problem or if you need more help.
