### ISSUE TITLE
Update to ReactiveSwift 4.0.0

### ISSUE THREAD

**Issue by soxjke** [Moya/Moya#1707]
Hi guys, we're using Moya 11.0.2 on several projects. Now we can't update to latest ReactiveCocoa / ReactiveSwift because Moya spec requires ReactiveSwift ~> 3.0.

Would you like my team or me to make a PR updating to ReactiveSwift ~> 4.0 ?

**Comment by pedrovereza** [comment]
Hey @soxjke, we recently updated the dependency in #1668, you can expect a beta release of Moya 12.0 soon 😄

**Comment by soxjke** [comment]
That's great, thank you!
