### ISSUE TITLE
Concurrent independent requests

### ISSUE THREAD

**Issue by HardikDG** [Moya/Moya#1715]
I am using Moya version: 11.0.2. 

I want to call multiple APIs which are independent of each other. Can I do that with Moya? Is Moya providing this type of facility like i can call multiple API and it will notify me once all the API response is received. 

The APIs are independent of each so the order of the API don't matter for me. 

I want similar functionality like Promiss.all... then in the Javascript. Where I add multiple promises and in single then I get final callback once all APIs are completed.

**Comment by slavasemeniuk** [comment]
I'm not sure that Moya provides such a functionality. But you still can use Moya together with PromiseKit to achieve the behaviour described above.

**Comment by slavasemeniuk** [comment]
```swift   
func request(_ target: Target) -> Promise<Response> {
        return Promise<Response> { seal in
            self.request(target, callbackQueue: .main, progress: nil, completion: { result in
                switch result {
                case let .success(response):
                    do {
                        _ = try response.filterSuccessfulStatusCodes()
                        seal.fulfill(response)
                    } catch {
                        seal.reject(error)
                    }
                case let .failure(error):
                    seal.reject(error)
                }
            })
        }
    }
```

And now you can use it: 
```swift 
when(fulfilled: userProvider.request(.get), postsProvider.request(.get))
```
