### ISSUE TITLE
Moya .uploadMultipart Task sending empty/no request body

### ISSUE THREAD

**Issue by wfcastaneda** [Moya/Moya#1717]
Environment: Using Moya (11.0.2), Xcode 9.4.1, iOS 11.4

Hi guys, 

I'm currently converting all of the networking for our app to Moya from plain alamofire. It's been incredible for all of the standard requests; however, this multipart upload is giving me trouble. I simply translated the old implementation to Moya by looking at your documentation on the subject. 

The task is below (ignore force unwraps, a product of debugging this issue :)): 

```swift
case .uploadAttachment(let attachment, _):
            let description = attachment.attachmentDescriptionString.data(using: String.Encoding.utf8)
            let image = UIImageJPEGRepresentation(attachment.imgUIImg, 0.20)
            
            let attachmentDescription = MultipartFormData(provider: .data(description!), name: "attach_type")
            let attachmentImage = MultipartFormData(provider: .data(image!), name: "attach_img", fileName: "image.jpg", mimeType: "image/jpeg")
            
            let multipartData = [attachmentDescription, attachmentImage]
            
            return .uploadMultipart(multipartData) 
```

And the request/response: 
```
---------------------
POST 'http://our_url':
Headers: [
  Content-Type : multipart/form-data; boundary=alamofire.boundary.d9a08dcf4bd0fe8d
  Authorization : Token "Some Auth Token"
]
---------------------
400 'http://our_url' [0.1520 s]:
Headers: [
  Content-Type : application/json
  Connection : keep-alive
  Content-Length : 42
  Allow : POST, OPTIONS
  Server : nginx
  Date : Fri, 24 Aug 2018 18:22:05 GMT
  Vary : Accept, Cookie
]
{
  "attach_file" : [
    "No file was submitted."
  ]
}
```

I'm wondering if there's something I'm missing or if this is a moya issue. Please let me know if you need more detail. 

Thank you.

**Comment by rivera-ernesto** [comment]
Having the exact same issues when trying to upload `UIImage`'s data.

**Comment by rivera-ernesto** [comment]
I found that it is required to create the `MultipartFormData` with both a valid `fileName` and a valid `mimeType`.
