### ISSUE TITLE
Response: Received empty network response

### ISSUE THREAD

**Issue by SupranJowti** [Moya/Moya#1718]
'Moya', '‾> 11.0'

First of all, I already saw some similar response but did not get any proper answer. most of them facing rx subscription problem

status code 200

**Request: baseurl?grant_type=password&password=pass&username=email
Moya_Logger: Request Headers: ["Content-Type": "application/x-www-form-urlencoded", "Authorization": "Basic ZGhha2FAbTJzeXMuY29tOm0yc3lzMTIz"]
Moya_Logger:  HTTP Request Method: POST
Moya_Logger:  Response: Received empty network response for .....**

`
class Network {

    static let manager: Manager = MoyaProvider<MyService>.defaultAlamofireManager()
    
    static let mprovider = MoyaProvider(endpointClosure: Network.endpointClosure, requestClosure: Network.endpointResolver(), stubClosure: MoyaProvider.immediatelyStub, manager: Network.manager, plugins: Network.plugins, trackInflights: true)
    
    
    static let endpointClosure = { (target: MyService) -> Endpoint in
        var headers = ["":""] // change this as you need
        
        let defaultEndpoint = MoyaProvider<MyService>.defaultEndpointMapping(for: target)
        switch target{
        case .createUser(let userName, let password):
            headers = ["Authorization": ("Basic " + ("\(userName):\(password)".toBase64() ?? "")),
            ]
        }
        
        return defaultEndpoint.adding(newHTTPHeaderFields: headers)
    }
    
    static func endpointResolver() -> MoyaProvider<MyService>.RequestClosure {
        return { (endpoint, closure) in
            do {
                var request = try endpoint.urlRequest()
                request.httpShouldHandleCookies = true
                
                closure(.success(request))
            } catch let error {
                closure(.failure(MoyaError.underlying(error, nil)))
            }
        }
    }

    static var plugins: [PluginType] {
        return [
            NetworkLoggerPlugin(verbose: true, responseDataFormatter: JSONResponseDataFormatter)
        ]
    }
}

`

**Comment by SSHuiqin** [comment]
Can I ask how you solve this issue? 
I have this problem occasionally. once it happens, i keep receiving empty response until I uninstall my application...

**Comment by ShahzaibInvision** [comment]
I have the same issue, what is the solution to this ?

**Comment by amaurydavid** [comment]
You might be interested in https://github.com/Moya/Moya/issues/1967 ;)
