### ISSUE TITLE
Module compiled with Swift 4.1 cannot be imported by the Swift 4.2 compiler

### ISSUE THREAD

**Issue by mcichecki** [Moya/Moya#1725]
Moya 11.0.2, built with Carthage. I set `xcode-select` to Xcode 10 and ran `carthage build Moya` but error still occurs. Is there going to be release of Moya with support of Xcode 10 and Swift 4.2?

**Comment by jdisho** [comment]
Are you installing `Moya/ReactiveSwift` ?

**Comment by BasThomas** [comment]
Yeah; can you share your `Cartfile.resolved` by chance, @stfnhdr?

**Comment by SD10** [comment]
I have yet to try running Moya, RxMoya, or ReactiveMoya on Swift 4.2. I'm guessing we need to update the minimum version of RxSwift to 4.2 and ReactiveSwift to 4.0?

We're ready to do a Moya 12 release once we're certain things work on Swift 4.2

**Comment by stfnhdr** [comment]
@BasThomas 
`github "AFNetworking/AFNetworking" "3.2.1"
github "Alamofire/Alamofire" "4.7.3"
github "ReactiveCocoa/ReactiveCocoa" "7.2.0"
github "ReactiveCocoa/ReactiveSwift" "3.1.0"
github "ReactiveX/RxSwift" "4.2.0"
github "SVProgressHUD/SVProgressHUD" "2.2.5"
github "aloco/SimpleButton" "3.0.1"
github "antitypical/Result" "3.2.4"
github "aschuch/StatefulViewController" "3.0.1"
github "gunterhager/ReactiveCodable" "1.1.1"
github "jdg/MBProgressHUD" "1.1.0"
github "jonkykong/SideMenu" "83f8e461e103d2caacb328c3050fcbb4980cbc83"
github "kishikawakatsumi/KeychainAccess" "v3.1.1"
github "mbuchetics/DataSource" "5.2.0"
github "moya/Moya" "11.0.2"
github "oliverkrakora/DataSource" "25535d5adef53a7a476f82e37b332add7993c65b"
github "scinfu/SwiftSoup" "1.7.2"
github "weichsel/ZIPFoundation" "0.9.6"
github "wokalski/Diff.swift" "0.5.3"
`

**Comment by nmtitov** [comment]
Any solution to this problem?

**Comment by SD10** [comment]
We'll be releasing a Moya 12.0.0-beta.1 shortly which will resolve the issues with your Carthage dependency

**Comment by kamranpirwani** [comment]
@SD10 Any thoughts on exact date? I'm awaiting this as well, wondering where to hold off on Swift 4.2 Upgrade

**Comment by SD10** [comment]
#1753 👍
