### ISSUE TITLE
Does Moya support convertFromSnakeCase decoding strategy?

### ISSUE THREAD

**Issue by felixsolorzano** [Moya/Moya#1737]
I use RxMoya, and I'd like to know if you're supporting [JSONDecoder.KeyDecodingStrategy.convertFromSnakeCase](https://developer.apple.com/documentation/foundation/jsondecoder/keydecodingstrategy/convertfromsnakecase)?

**Comment by pietrocaselani** [comment]
Yes!
You can use your own JSON Encoder, just use the Task `.requestCustomJSONEncodable`.

Let us know if need any more help.

**Comment by felixsolorzano** [comment]
Do you have an example of how to use it? @pietrocaselani

**Comment by pietrocaselani** [comment]
@felixsolorzano Sorry, I thought you would like to encode, but you want to decode a JSON, my bad!
For that, you can use the map function like this:

```swift
let decoder = JSONDecoder()
decoder.keyDecodingStrategy = .convertFromSnakeCase
moyaProvider.rx.request(.target).map(SomeDecodableStruct.self, using: decoder)
```

**Comment by felixsolorzano** [comment]
I see, thanks @pietrocaselani
