### ISSUE TITLE
Can a Provider be used without RxSwift?

### ISSUE THREAD

**Issue by multinerd** [Moya/Moya#1747]
Moya 11.0.2

How can i create a provider without using RxSwift?

the [docs](https://github.com/Moya/Moya/blob/master/docs/Examples/ComposingProvider.md) is using rxswift and i cant figure out how to return a `Moya.Response` without using closures

**Comment by SD10** [comment]
Hey @multinerd,

You may want to check out the [getting started guide](https://github.com/Moya/Moya/blob/master/docs/Examples/Basic.md) for the non-Rx version of Moya. You can also see the non-Rx MoyaProvider documentation [here](https://github.com/Moya/Moya/blob/master/docs/Providers.md). Hope this helps 😄

**Comment by multinerd** [comment]
Im trying to mimic the kiosk app implementation of `OnlineProvider<Target>`, im wondering if that can be done without RxSwift. If so, how would i implement `request(_ token: Taget) -> Single<Moya.Response> `

**Comment by multinerd** [comment]
Im waiting for a response

**Comment by multinerd** [comment]
I guess im not getting a response...

**Comment by pietrocaselani** [comment]
Hi @multinerd 
So... I think that is easier to implement this using Rx, but I made a "pseudo/fake" code trying to reproduce the same behavior without Rx.

```swift
enum ConnectionType {
    case wifi
    case mobile
}

enum ConnectionStatus {
    case offline
    case online(type: ConnectionType)
}

protocol ConnectivityObserver {
    func connectionChanged(status: ConnectionStatus)
}

class FakeCancellable: Cancellable {
    var isCancelled: Bool = false
    
    func cancel() {}
}

final class OnlineProvider<Target> where Target: Moya.TargetType : ConnectivityObserver {
    private let provider: MoyaProvider<Target>

    private var lastRequestTarget: Target?
    private var lastRequestCompletion: Moya.Completion?
    private var lastRequestCancellable: Cancellable?

    private var connectionStatus: ConnectionStatus
    
    init(endpointClosure: @escaping MoyaProvider<Target>.EndpointClosure = MoyaProvider.defaultEndpointMapping,
         requestClosure: @escaping MoyaProvider<Target>.RequestClosure = MoyaProvider.defaultRequestMapping,
         stubClosure: @escaping MoyaProvider<Target>.StubClosure = MoyaProvider.neverStub,
         manager: Manager = MoyaProvider<Target>.defaultAlamofireManager(),
         plugins: [PluginType] = [],
         trackInflights: Bool = false) {
             self.connectionStatus = .offline
             self.provider = MoyaProvider(endpointClosure: endpointClosure, requestClosure: requestClosure, stubClosure: stubClosure, manager: manager, plugins: plugins, trackInflights: trackInflights)
         }

    func request(_ target: Target, completion: @escaping Moya.Completion) -> Cancellable {
        if connectionStatus == .online {
            //We are online! So lets perform the request
            return provider.request(target, completion)
        }

        //We are offline :( Lets keep the references to perform the request after...
        self.lastRequestTarget = target
        self.lastRequestCompletion = completion

        //Returns a cancellable that does nothing!
        return FakeCancellable()
    }

    func connectionChanged(status: ConnectionStatus) {
        self.connectionStatus = status
        
        //You should handle those optionals!
        lastRequestCancellable = provider.request(lastRequestTarget!, lastRequestCompletion!)
    }

    //If you want to cancel the request, you should call this method, or expose the `lastRequestCancellable` to the outside world!
    func cancel() {
        lastRequestCancellable?.cancel()
    }
}
```
You need to implement the protocol `ConnectivityObserver` using a reachability, I think alamofire has something to do this.

Again... this is a pseudo code, I didn't test it, is just to give you an idea about the implementation. But I really think that using Rx is a better approach.

**Comment by irilattada** [comment]
hi @pietrocaselani what is trackInflights?
when should I pass true or false
can't find documentation about it yet.

**Comment by pietrocaselani** [comment]
Hi @irilattada 
I don't actually know what the `trackInflights`. This code is just a example and you can find more info about it in [here](https://github.com/Moya/Moya/blob/master/docs/Examples/ComposingProvider.md)
