### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by WenzheFan** [Moya/Moya#1749]

**Comment by WenzheFan** [comment]
how to use ！
old code  no use ,new code how to use

**Comment by SD10** [comment]
Hey @WenzheFan, you can find the documentation for Moya [here](https://github.com/Moya/Moya/tree/master/docs). I recommend starting with [basic usage](https://github.com/Moya/Moya/blob/master/docs/Examples/Basic.md). Hope this helps 😄
