### ISSUE TITLE
How to check if there is internet connection?

### ISSUE THREAD

**Issue by mxp7064** [Moya/Moya#1751]
Hi. I am new to Moya. Can you please tell me how can I check if there is network connection before I send the request so I can do proper handling like showing user a message that there is no internet connection?

Thanks in advance!

**Comment by suhitp** [comment]
Do read [Designing for the real-world network document] guidelines by Apple (https://developer.apple.com/library/archive/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/WhyNetworkingIsHard/WhyNetworkingIsHard.html#//apple_ref/doc/uid/TP40010220-CH13-SW1)

For **Reachability** you can use [NetworkReachabilityManager](https://github.com/Alamofire/Alamofire/blob/master/Source/NetworkReachabilityManager.swift) from Alamofire to listen for the reachability changes and handle the status. Do follow best practices highlighted in the document as well.

**Comment by mxp7064** [comment]
Thank you so much! Could you also please tell me what's the best way to cancel requests? I've been looking at different question threads about that but they are all for RxMoya or ReactiveMoya. I am using the usual Moya.

**Comment by suhitp** [comment]
MoyaProvider request method returns a Cancellable protocol type which has a cancel method. 

```
func request(_ target: Target,
                  callbackQueue: DispatchQueue? = .none,
                  progress: ProgressBlock? = .none,
                  completion: @escaping Completion) -> Cancellable
```

So you return this Cancellable type from your Network Layer method and call cancel when required.

**Comment by mxp7064** [comment]
Thank you!
