### ISSUE TITLE
[Help] Encode

### ISSUE THREAD

**Issue by anh-ht** [Moya/Moya#1752]
I have a question.

I have used moya code as follows:

`var parameterEncoding:ParameterEncoding { return URLEncoding.default }`
and
`params["filter"] = ["where": ["or": [["source": 1], ["source": 2]]], "offset": offset ?? 0]`

=> and the url returned from the server is

`[filter][where][or][][source]=1&[filter][where][or][][source]=2`

But server need :

`[filter][where][or][0][source]=1&[filter][where][or][1][source]=2`

How do I get it?

**Help !!**

**Comment by anh-ht** [comment]
Has anyone solved the same problem like this ?

**Comment by pedrovereza** [comment]
Hey @anh-ht, I think you'll have to create your own `ParameterEncoding`. Here is the [Alamofire documentation on how to build a custom `ParameterEncoding`](https://github.com/Alamofire/Alamofire/blob/master/Documentation/Usage.md#custom-encoding), hope it helps.

**Comment by anh-ht** [comment]
@pedrovereza thanks. :)
