### ISSUE TITLE
An easier way to use stub requests and sampleData

### ISSUE THREAD

**Issue by amaurydavid** [Moya/Moya#1754]
One of the things that make me love Moya is the stubRequest / sampleData feature. It's so easy to use mocks! But I think it could be even more easier.

Every time I create a new endpoint without the need to use mock data, I still need to return a Data object for `sampleData`, and always end up using something like ```var sampleData: Data { 
return Data() 
}```. Even if it's never used (because somehow the , it frustrates me to actually be forced to return a data.

Additionally, I also like to add a property `stubBehavior` to each one of my targets. You guessed it, it just checks `sampleData` and return a behavior accordingly:
``` 
extension MyTarget {
  var stubBehavior: StubBehavior {
    return sampleData == Data() ? .never : .delayed(seconds:1)
  }
}
```

Finally, I use a `MoyaProvider` subclass with a custom `stubClosure`
```
class DemoMoyaProvider: MoyaProvider<MyTarget> {

  init() {
    let customStub: DemoMoyaProvider.StubClosure = { $0.stubBehavior }
    super.init(stubClosure: customStub)
  }
}
```

Having the `sampleData` and the `stubBehavior` properties at the same location (i.e in the target enum) is to me way more easier to activate/deactivate mocks on the fly. But again, it doesn't change the `sampleData` and i'm still frustrated of this `return Data()`.

So here is a proposal: what about merging those `sampleData`and `stubBehavior` properties into a simple `stubBehavior`property, and updating the `StubBehavior` cases to add a `Data` associated value:
```
public enum StubBehavior {

    /// Do not stub.
    case never

    /// Return a response immediately.
    case immediate(stubData: Data)

    /// Return a response after a delay.
    case delayed(seconds: TimeInterval, stubData: Data)
}
```
Not only we now have at the same place both the stub behavior and the stub data, but it could also saves the use of a custom `stubClosure` in the `MoyaProvider`.

For the record, I don't use mocks for tests, but mainly as placeholders while waiting for the API to be available. So I would understand if this approach would not fit right into unit tests.

**Comment by SD10** [comment]
Hey @amaurydavid, we've talked about changing the stubbing API, check out #1502 and let me know what you think
