### ISSUE TITLE
Why Watch os has no MoyaProvider<>().rx???

### ISSUE THREAD

**Issue by gityubj** [Moya/Moya#1761]
Platform: Clock, '4.0'
pod 'RxSwift', '~ 4.3'
pod 'RxCocoa', '~ 4.3'
pod 'Moya', '~ 11.0'
End

I am using cocoapods.

The cocoapods version uses 1.5.3.

Static Let provider = MoyaProvider <watchAPI> (). rx

I use an iOS target and an .rx error occurs on the watch target.

There is no 'rx' member in the value of type 'MoyaProvider <watchAPI>'.

The above error. Thank you for your help.

**Comment by SD10** [comment]
@gityubj Could be related to #1758

**Comment by SD10** [comment]
This should be fixed by Moya version 12.0. Please upgrade and feel free to re-open if the problem persists. Thank you for your patience 🙏
