### ISSUE TITLE
RxSwift example in README

### ISSUE THREAD

**Issue by ashfurrow** [Moya/Moya#177]
To match the ReactiveCocoa one.

**Comment by retsohuang** [comment]
I'm using RxSwift + Moya in my project, Is the sample code like this  would help?
```
      provider.request(.UserProfile("ashfurrow")).subscribe(next: {
          image = UIImage(data: $0)
        }, error: {
          println($0)
      })
```

**Comment by ashfurrow** [comment]
Yeah, exactly! We'd need to unindent the code and add Swift code highlighting (see the existing README samples' markdown). :cake:

**Comment by argentounce** [comment]
Can you help me setup a Provider with RxSwift? How a simple RxMoyaProvider should look? How the closure should look?

It would be good that the demo includes examples for both RAC and RX. 

Currently I got my way with the Artsy implementation but im having problems declaring the provider. I know there is a branch about Rx Docs, but this probably be some kinda Faqsy.

**Comment by ashfurrow** [comment]
Hey @argentounce – good question!

The RxMoyaProvider is created using the _exact same_ method as a regular `MoyaProvider`. You just say:

```swift
let provider = RxMoyaProvider<MyAPI>()
```

And that's it! All the examples in the docs that show how to configure the provider apply identically to the RxSwift and RAC providers. Demos for those projects are a great idea :100:

**Comment by argentounce** [comment]
@ashfurrow Thanks! working now :yum:
