### ISSUE TITLE
Lost AnyError in Result 4.0.0

### ISSUE THREAD

**Issue by andmix** [Moya/Moya#1776]
i use Moya 12.0.1 ,  lost struct AnyError in Result 4.0.0

**Comment by SD10** [comment]
@andmix Can you give me some more context here? How are you installing Moya? Can I see your lockfile?

**Comment by andmix** [comment]
i install Moya in my Podspec ,like this:
s.subspec 'Base' do |ss|
        ss.source_files = 'XXXXX'
        ss.dependency 'Moya'

**Comment by andmix** [comment]
it is ok now, it is a cache bug because of xcode
