### ISSUE TITLE
sampleData & Codable

### ISSUE THREAD

**Issue by simonzwicker** [Moya/Moya#1779]
<!--
Please let us know what version of Moya you are using, so we can better pinpoint and/or solve your issue.

11.0.2

Please wrap code blocks in backticks, like so:

```swift
var sampleData: Data {

		return "sample".data(using: .utf8)!
	}
```

Get this compile Error: Cannot convert return expression of type 'Data' to return type 'Data'

Don't know how to fix, bevor I return a Data() but after add Codable Structs to my projects, it says: Cannot invoke initializer for type 'Data' with no arguments

Someone has the same issue and fixed it?

**Comment by simonzwicker** [comment]
My description was not added so here again:

my SampleData return a Data() and after adding a struct as Codable the compileError appears: Cannot invoke initializer for type 'Data' with no arguments

if I add a return "sample".data(using: .utf8)! it says: Cannot convert return expression of type 'Data' to return type 'Data'

What can I do?

**Comment by simonzwicker** [comment]
I use Xcode Version 10.1 (10B61) and Moya 11.0.2

**Comment by simonzwicker** [comment]
Problem solved, I delete the Codable from Project and create it new and it works, but this was a serious bug.

**Comment by pedrovereza** [comment]
Closing this one as it seems solved 😄
