### ISSUE TITLE
pod try Moya failed

### ISSUE THREAD

**Issue by jk** [Moya/Moya#178]
I'm not sure if this is already known or furthermore intended but I tried to use `pod try Moya` and it failed with the following error message:

```
Updating spec repositories

Trying Moya
Performing CocoaPods Installation
Fetching podspec for `Moya` from `../`
[!] Unable to satisfy the following requirements:

- `Moya/RxSwift (from `../`)` required by `Podfile`
- `Moya/RxSwift (from `../`)` required by `Podfile`
- `Moya/RxSwift (= 1.1.1)` required by `Podfile.lock`
```

or did I do something wrong?

**Comment by ashfurrow** [comment]
Hey! Thanks for letting us know. I've not used `pod try Moya` more – honestly I don't know how it works, but I'll take a look and let you know as soon as I figure it out.

**Comment by orta** [comment]
Think someone needs to go into the folder and run a `pod update` since maya' update, there's a more modern issue around this, but it's basically this issue: https://github.com/CocoaPods/CocoaPods/issues/1623

**Comment by ashfurrow** [comment]
That's weird – thought I'd done that. I'll give it a try.

**Comment by orta** [comment]
I'm willing to bet that was done after tagging

**Comment by ashfurrow** [comment]
Mmmhmmmmm.

**Comment by jk** [comment]
Woha. That's a great troubleshooting experience. A lot like following a sports live ticker :)

**Comment by ashfurrow** [comment]
Having trouble getting `pod trunk push` to work, hold tight.

**Comment by esttorhe** [comment]
If its failing on the lint make sure your xcode-select is pointing to NOT Xcode7 
Something like that was happening to me yesterday

--
Esteban Torres
(+506)8813-0934
Twitter: @esttorhe




On Thu, Aug 6, 2015 at 6:48 AM -0700, "Ash Furrow" <notifications@github.com> wrote:












Having trouble getting pod trunk push to work, hold tight.

**Comment by ashfurrow** [comment]
Good idea, @esttorhe. Checked and it's 6, which sucks since I _am_ getting a linker error. 

Set iTerm to "unlimited scrollback" to actually see the failure message. (Why is that _not_ the default??)

**Comment by esttorhe** [comment]
I need to change that on my terminal as well now that you mention it. 

--
Esteban Torres
(+506)8813-0934
Twitter: @esttorhe




On Thu, Aug 6, 2015 at 6:51 AM -0700, "Ash Furrow" <notifications@github.com> wrote:












Good idea, @esttorhe. Checked and it's 6, which sucks since I am getting a linker error. 



Set iTerm to "unlimited scrollback" to actually see the failure message. (Why is that not the default??)

**Comment by ashfurrow** [comment]
Cooooool got it to work! @jk Could you try again? Or, rather, `pod try` again?

![](http://2.bp.blogspot.com/_g88-bL8l6H0/TLPAOwcfosI/AAAAAAAAAA8/UwAQw5vcdLI/s1600/3322267.jpg)

**Comment by orta** [comment]
<.<

**Comment by jk** [comment]
@ashfurrow it does work now. Thanks.

```
pod try Moya
Updating spec repositories

Trying Moya
Performing CocoaPods Installation
Fetching podspec for `Moya` from `../`
Using Alamofire (1.3.0)
Using Box (1.2.2)
Using Moya (2.0.1)
Using Nimble (0.4.2)
Using OHHTTPStubs (4.0.2)
Using Quick (0.3.1)
Using ReactiveCocoa (3.0-beta.6)
Using Result (0.4.4)
Using RxSwift (1.9)
Sending stats
Opening '/private/var/folders/pc/plkw89_s63lb5cj277y8_f580000gn/T/CocoaPods/Try/Moya/Demo/Demo.xcworkspace'
```

And by the way, you don't want to set iTerm to »unlimited scrollback« it will get slow after a certain threshold. I'm very comfortable with it set to 5.000.

**Comment by ashfurrow** [comment]
Oh yeah? I'm a pretty compulsive ⌘K'er, but I'll be on the lookout for slowdown.
