### ISSUE TITLE
Dash docset empty

### ISSUE THREAD

**Issue by philosopherdog** [Moya/Moya#1785]
I notice that the docset is missing from Moya. It's easy to add by just running jazzy. I'm happy to add it in a pull request, but maybe it should be part of the build process so that it is automatically added going forward. Thoughts?

**Comment by SD10** [comment]
Hey @philosopherdog, the documentation can be found [here](https://moya.github.io). Are you trying to convey that this documentation is outdated? I'll update it

**Comment by philosopherdog** [comment]
I'm trying to view it in Dash instead of the web. The docset folder is empty and simply requires running jazzy to generate a docset that is viewable in Dash.

**Comment by SD10** [comment]
Ah, I see @philosopherdog. I'm not too familiar with Dash. We're trying to keep the generated documentation out of the main repo. Can you make this change on the moya/moya.github.io repo?
