### ISSUE TITLE
Moya.StubBehavior, Can I just delay request for some time and NOT stub

### ISSUE THREAD

**Issue by lanjing99** [Moya/Moya#1788]
Moya 12

```swift
public enum StubBehavior {

    /// Do not stub.
    case never

    /// Return a response immediately.
    case immediate

    /// Return a response after a delay.
    case delayed(seconds: TimeInterval)
}
```

Can I just delay a network request for some time and NOT stub, by now,  I have to add a sample Data same with what a network request will return.

**Comment by amaurydavid** [comment]
Could you just perform the request using a simple ```DispatchQueue.asyncAfter(deadline:execute:)``` ?
