### ISSUE TITLE
Unable to use relative paths for target

### ISSUE THREAD

**Issue by artbasil** [Moya/Moya#1791]
Moya 12.0.1

We have baseURL = "www.somehost.com/api/apiversion/"
For each request we have some paths like
target.path = "some/method_a"
or
target.path = "some/method_b"
e.t.c

URL for each request constructs in URL+Moya.swift extension using the next line of code.
```swift
self = target.baseURL.appendingPathComponent(target.path)
```
As a result we have URL like
"www.somehost.com/api/apiversion/some/method_a"
or
"www.somehost.com/api/apiversion/some/method_b"
e.t.c

But what if we need to alternate the path from the root for some rare case?
Like "www.somehost.com/alternative/path/method_z"

It will be logically to use relative path for this case: 
target.path = "../../alternative/path/method_z"

But the current implementation will result with this:
"www.somehost.com/api/apiversion/../../alternative/path/method_z"

Looks like an issue.

It could be solved by creating URL using path relative to the base URL:
```swift
self = URL(string: target.path, relativeTo: target.baseURL)
```

Is there any alternative solutions how to solve such issue?

**Comment by artbasil** [comment]
Hi Pedro,

This is the one of the solutions. But this will require much more than only one line of code in the existing application.

Best regards,
Basil

**Comment by pedrovereza** [comment]
@artbasil I'd like to better understand your use case. 

Why isn't the `baseURL` set to `www.somehost.com`? Have you considered wrapping the custom path creation in functions? Similar to:

```swift
    var baseURL: URL { return URL(string:"http://somehost.com")! }

    var path: String {
        switch self {
        case .method_a:
            return standardApiPath(forMethod: "method_a")
        case .method_b:
            return standardApiPath(forMethod: "method_b")
        case .method_z:
            return alternativeApiPath(forMethod: "method_z")
        }
    }

    private func standardApiPath(forMethod method: String) -> String {
        return "api/apiversion/\(method)"
    }

    private func alternativeApiPath(forMethod method: String) -> String {
        return "alternative/path/\(method)"
    }
```

**Comment by artbasil** [comment]
@pedrovereza sorry for not being clear in my post.
I have some existing project with some existing API implementation based on some third party framework. And we would like to migrate to the Moya.
We have some code already used regular API and the alternative API. And it should be just easy as switch one framework to another. But the existing implementation rely on the possibility to use relative paths. Your framework does not support that feature. I've provided the possible solution. Which is not making conflict with the existing functionality.

**Comment by ashfurrow** [comment]
I don't see any reason this wouldn't work – I'd want to make sure we have a unit test but yeah, sounds like a great idea 👍

**Comment by artbasil** [comment]
There only thing which is needed to think about is error behavior. As this function returns optional. And needs to be unwrapped.
self = URL(string: target.path, relativeTo: target.baseURL) ?? target.baseURL 
as a possible solution.

**Comment by pedrovereza** [comment]
@artbasil I'd rather have it throw an error. If the user is trying to build a malformed URL, we shouldn't hide the problem

**Comment by ashfurrow** [comment]
Does that method throw? I agreed that would be ideal.

**Comment by artbasil** [comment]
That was my first idea. But this method doesn't trow.
