### ISSUE TITLE
请求时，参数想传数组怎么传，不是传字典

### ISSUE THREAD

**Issue by mingios** [Moya/Moya#1792]

**Comment by sea516** [comment]
just help mingios translate Chinese to English.
how to send an array as a parameter instead of a dictionary when request.

**Comment by sea516** [comment]
I believe this is exactly what mingios want

**Comment by sea516** [comment]
> This may be useful [使用自定义的ParameterEncoding](https://github.com/Moya/Moya/blob/master/docs_CN/Examples/ParameterEncoding.md)

I believe this is exactly what mingios want
