### ISSUE TITLE
how to get parameters of the task

### ISSUE THREAD

**Issue by LCBbest** [Moya/Moya#1793]
when i send request ，i want to get parameters ,but i dont honw how to get ....
now i get `Endpoint.task`
print

> requestParameters(parameters: ["type": "4"], encoding: Alamofire.URLEncoding(destination: Alamofire.URLEncoding.Destination.methodDependent, arrayEncoding: Alamofire.URLEncoding.ArrayEncoding.brackets, boolEncoding: Alamofire.URLEncoding.BoolEncoding.numeric))

how to only get `parameters`

thinks

**Comment by LCBbest** [comment]
Can anyone help me?

**Comment by sunshinejr** [comment]
Hey @LCBbest, sorry for the late reply. So let's say you have a `Task` object and you want to fetch `parameters` out of it, right?

First, you need to take into consideration that your `Task` might be [one of many different options](https://github.com/Moya/Moya/blob/master/Sources/Moya/Task.swift#L4-L40). Fortunately, you can just use switch to fetch only the information you need:
```swift
switch task {
    case let .requestParameters(parameters, _):
        // now you have parameters for `.requestParameters` task
    case let .downloadParameters(parameters, _):
        // now you also have parameters, but for `. downloadParameters ` task now
    case let . requestCompositeData(_, urlParameters):
        // now you have _url_ parameters for `. requestCompositeData` task
    case let . requestCompositeParameters(bodyParameters, _, urlParameters):
        // now you have both bodyParameters and urlParameters for `
    case let .uploadCompositeMultipart(_, urlParameters):
        // again you have `urlParameters` but now for multipart upload
    default:
        // here you won't really have any parameters, you have to handle that case as well
}
```

Let me know if this is of any use to you! If not, don't worry, please provide more info about your use-case and we will figure it out :) Cheers!

**Comment by LCBbest** [comment]
Hello, I mean, when making a network request, just like getting the address of the network request, get the parameters of the network request and print them out. In the following method
```
let requestTimeoutClosure = { (endpoint: Endpoint, done: @escaping MoyaProvider<NetWorkService>.RequestResultClosure) in
    guard var request = try? endpoint.urlRequest() else { return }
    request.timeoutInterval = 120  
    //print(request.allHTTPHeaderFields)
    print(request.url)//like this,Can you print parameters in this
    done(.success(request))
}
```

**Comment by pedrovereza** [comment]
@LCBbest In your example, `request` is an instance of `URLRequest`. The [`URLRequest` documentation](https://developer.apple.com/documentation/foundation/urlrequest) has a section called "Accessing Request Components" with all requests fields that you can read.

I think `httpBody` is what you're looking for.

**Comment by LCBbest** [comment]
httpBody can not print parameters

**Comment by pedrovereza** [comment]
Ah sorry, I miss understood what you wanted to print. You want to print the parameters of the `Task` defined in the `TargetType`, right?

If so, you can get the `Task` instance from the `endpoint`:

```swift
let task = endpoint.task
```

And then use the `switch` block that @sunshinejr mentioned

**Comment by LCBbest** [comment]
if request.httpBody != nil {
        print(String(data: request.httpBody!, encoding: String.Encoding.utf8) ?? "")
    }

**Comment by LCBbest** [comment]
```
if request.httpBody != nil {
    print(String(data: request.httpBody!, encoding: String.Encoding.utf8) ?? "")
}
```
