### ISSUE TITLE
Access Token in header issue

### ISSUE THREAD

**Issue by dagad** [Moya/Moya#1794]
Hi, me and my team building an app with login functionality.

our app has access token but never expired. 
so we want just change access token when login and logout repeatedly. 

But after some research we found Moya doesn't provide auth api like change token, refresh token etc...

so is it okay to just insert access token in our TargetType header like below.

`

        var headers: [String: String]? {
        var headers = [String: String]()
        let accessToken = KeychainWrapper.standard.string(forKey: "access_token")
        switch self {
        case .signIn, .refreshToken:
            headers["Content_Type"] = "application/x-www-form-urlencoded; charset=utf-8"
            return headers
        case .getMyInfo,
             .getMyTeams,
             .getCurrentDirectoryFiles,
             .getStorageInfo,
             .getTeamLicenses:
            headers["Authorization"] = "bearer \(accessToken!)"
            return headers
        case .addFolder,
             .renameFile,
             .removeFiles,
             .copyFiles,
             .moveFiles:
            headers["Authorization"] = "bearer \(accessToken!)"
            headers["Content_Type"] = "application/json; charset=utf-8"
            return headers
        case .uploadImage:
            headers["Authorization"] = "bearer \(accessToken!)"
            headers["Content-Type"] = "multipart/form-data"
            return headers
        }
    }`

**Comment by pietrocaselani** [comment]
Hi @dagad 
Please take a look at those docs to see if help your case.
* [Authentication.md](https://github.com/Moya/Moya/blob/master/docs/Authentication.md)
* [AuthPlugin.md](https://github.com/Moya/Moya/blob/master/docs/Examples/AuthPlugin.md)

**Comment by sunshinejr** [comment]
Hi @dagad! What you described is one of the options you have to use an access token in your API and it's totally fine!

However, I believe that using our `AccessTokenPlugin` will give you a little bit more clarity and flexibility in the code. Please take a look [at this tutorial about it](https://github.com/Moya/Moya/blob/master/docs/Authentication.md#access-token-auth) and let me know if you have any more questions about it :)

**Comment by dagad** [comment]
Thanks you for reply @sunshinejr @pietrocaselani. i used `AccessTokenPlugin`
