### ISSUE TITLE
Import Manually

### ISSUE THREAD

**Issue by olivinesguerra** [Moya/Moya#1795]
Hi Guys,

Is there any way I could import moya manually on my custom framework?
I followed the instruction on readme.md. But still no luck. 

Thanks

**Comment by sunshinejr** [comment]
Hey @olivinesguerra, could you please describe where did you fail to manually import Moya? [There are a lot of steps in the Readme](https://github.com/Moya/Moya#manually), so please point me in a direction in which you failed and I will try my best to help you resolve the issue!

**Comment by olivinesguerra** [comment]
Hi Thanks for replying. My problem is, after I followed the instructions, Its seems that Moya does'nt see alamofire. after I import alamofire inside moya. it goes fine but it creates another error which is IOS version since some of them are set to 8.0. After I set all of them to 8.0, it creates another bug which is connected to moya is only available to 10.00. Sorry i have to revert to cocoapod dependent framework, so I don't have any screenshot.
