### ISSUE TITLE
Refresh Token with additional request

### ISSUE THREAD

**Issue by beraybentesen** [Moya/Moya#1801]
By using the latest version of Moya/RxSwift, 

I would like to refresh our bearer token and continue the request. There are some examples with OAuth library but I'd like to make another request instead of using that library.

Does anyone have a custom Moya Provider example for that?

**Comment by pietrocaselani** [comment]
Hi @beraybentesen 
This is a common issue around here, so could you please take a look at those [results](https://github.com/Moya/Moya/search?q=refresh&type=Issues) to see if help your case?

I believe you will find your answer on https://github.com/Moya/Moya/issues/744
