### ISSUE TITLE
Pass already configured URL to Moya Provider 

### ISSUE THREAD

**Issue by SergeyGamayunov** [Moya/Moya#1802]
Hi,

does anybody know is it possible to pass to Moya raw URL? I got the one from webView and I have to execute request with it. I know nothing about it, no baseURL, noPath, so it's impossible to add it in TargetType enum.

**Comment by pedrovereza** [comment]
Hey @SergeyGamayunov you can get around it by adding a new `case` in your `TargetType` enum that takes the raw url and use it as `baseURL`:

```swift
enum ExampleTarget {
    case plainRequest(rawURL: String)
}

extension ExampleTarget : TargetType {
    var baseURL: URL {
        switch self {
        case .plainRequest(let rawURL):
            return URL(string: rawURL)!
        }
    }

    var path: String { return "" }

    var method: Moya.Method { return .get }

    var sampleData: Data { return Data() }

    var task: Task { return .requestPlain }

    var validate: Bool { return true }

    var headers: [String: String]? { return nil }
}
```

Usage:

```swift
provider.request(.plainRequest(rawURL: "https://httpbin.org/get")) { result in
            switch result {
            case .success(_):
                print("Success")
            case let .failure(error):
                print(error)
            }
        }
```

**Comment by SergeyGamayunov** [comment]
Thanks, @pedrovereza 

It's pretty straightforward and obvious way to workaround with plainURL and it's exactly that I wanted to avoid. 

I see two issues in that solution: 

- force unwrap base URL for that case. Even if we add check for value presence, we have to return real URL instance
- baseURL variable is semantically overloaded: it will return URL that basically is not base URL. We always consider that variable as place where you can expect to see one or two _real_ base URLs.

**Comment by pedrovereza** [comment]
> * force unwrap base URL for that case. Even if we add check for value presence, we have to return real URL instance

The url coming from your webView needs to be valid anyway in order to make a request, right? You can avoid force unwrapping by changing the enum to receive an `URL` instead of a `String` and handle the `URL` creation before passing it to the provider (probably not passing it at all if you can't build an `URL` from the `String` you got). 

> * baseURL variable is semantically overloaded: it will return URL that basically is not base URL. We always consider that variable as place where you can expect to see one or two _real_ base URLs.

I don't think I understood what you mean. Can you elaborate on that?

**Comment by SergeyGamayunov** [comment]
Well, I didn't claim that your solution won't work, it certainly will, and I'll probably use it. It's just some reasoning about it.

> I don't think I understood what you mean. Can you elaborate on that?

When you construct Targets via Moya you always know, that baseURL will return you a... you know, base URL - the first and mostly constant part of ALL your URLs. And during debugging you can look up for this variable (_"I need to know what baseURL I have here"_) and you will be confused cause it will equal to some real URL with parameters and probably huge token. Of course, you will figure out after a while, that you have this one specific case in TargetType enum, that destroys logic of Moya in this particular situation.

**Comment by pedrovereza** [comment]
@SergeyGamayunov Ah, got it!

Another option would be to create a `TargetType`  _just_ for this use case, and leave your current `TargetType` as is. You could then have a different provider for the new `TargetType` or consider using a [`MultiTarget` provider](https://github.com/Moya/Moya/blob/master/docs/Examples/MultiTarget.md)

But I'm afraid these are the only options we currently have 😅

**Comment by SergeyGamayunov** [comment]
YES! It looks much better. MultiTarget provider is great option by the way - it seems I overlooked it. 
Now I can have a several TargetTypes enums - for local request, for plainURL and for many other goals, and all of them in one provider.
Thank you very much!
