### ISSUE TITLE
Ambiguous use of 'request(_:callbackQueue:)' when included using CocoaPods

### ISSUE THREAD

**Issue by marco-palumbo** [Moya/Moya#1808]
I've successfully used Moya in my project using Carthage as dependency manager. Now I've switched to CocoaPods, but for some reason my project doesn't compile anymore. As mentioned in the title the error I get is:

```
error: ambiguous use of 'request(_:callbackQueue:)'

Moya.Reactive<Base>:2:17: note: found this candidate
    public func request(_ token: Base.Target, callbackQueue: DispatchQueue? = default) -> RxSwift.PrimitiveSequence<RxSwift.SingleTrait, Moya.Response>
                ^
RxMoya.Reactive<Base>:2:17: note: found this candidate
    public func request(_ token: Base.Target, callbackQueue: DispatchQueue? = default) -> RxSwift.PrimitiveSequence<RxSwift.SingleTrait, Moya.Response>
```

Here is my podfile:

```ruby
platform :ios, '11.0'

target 'MyProject' do
  use_frameworks!

  pod 'Moya/RxSwift', '~> 12.0'

  target 'MyProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

**Comment by sunshinejr** [comment]
Hey @marco-palumbo, sorry for the late reply. Do you happen to have an example project where this problem exists? I would have a look at it and see what could be the culprit.

**Comment by marco-palumbo** [comment]
Thanks for the reply @sunshinejr, when I was trying to make an example project I did find out where the problem was: I messed up with the imports. The strange thing is that in a file I did import RxMoya but the compiler didn't give me the 'No such module' error, so in some ways that has caused the more cryptic error I've reported. Sorry for opening the issue.

**Comment by sunshinejr** [comment]
Oh no worries @marco-palumbo, glad you’ve figured it out!
