### ISSUE TITLE
Type inference problem

### ISSUE THREAD

**Issue by wwdc14** [Moya/Moya#1814]
Where is the syntax wrong?

[![5B8A021D3C72AE20AE0E6DCDF6D542E2.jpg](https://i.loli.net/2019/03/06/5c7f3d804a096.jpg)](https://i.loli.net/2019/03/06/5c7f3d804a096.jpg)
[![E96DB18A611B5EEFE6BA8689F87F5E5F.jpg](https://i.loli.net/2019/03/06/5c7f3d8053400.jpg)](https://i.loli.net/2019/03/06/5c7f3d8053400.jpg)

**Comment by wwdc14** [comment]
@sunshinejr Thank you very much for your answer, how Moya implements multiple API simultaneous requests？

**Comment by sunshinejr** [comment]
@wwdc14 Moya doesn't have an API support for multiple simultaneous request, no. You would have to create it yourself.

**Comment by wwdc14** [comment]
Ok, thank you for your answer.

**Comment by sunshinejr** [comment]
Hey @wwdc14 no problem, happy to help! 👍
