### ISSUE TITLE
How to stub a request with progress?

### ISSUE THREAD

**Issue by chika-kasymov** [Moya/Moya#1819]
I'm using the Moya library with version `12.0.0`.

All plain request stubs work fine, but I can't figure it out how to stub a request with progress. For example, an image uploading request.

For plain requests I use this function: `func request(_ token: Target, callbackQueue: DispatchQueue? = default) -> PrimitiveSequence<SingleTrait, Response>`.
For requests with progress I use this function: `func requestWithProgress(_ token: Target, callbackQueue: DispatchQueue? = default) -> Observable<ProgressResponse>`.
I implemented `var sampleData: Data { get }` for both types of requests and returning related JSON file contents.

My stub closure looks like this:
```swift
private static func stubEndpointClosure() -> ((Target) -> Endpoint) {
    return { target in
        return Endpoint(
            url: URL(target: target).absoluteString,
            sampleResponseClosure: { .networkResponse(target.sampleStatusCode, target.sampleData) },
            method: target.method,
            task: target.task,
            httpHeaderFields: target.headers
        )
    }
}
```

The issue is that for stub requests with progress observable operators like `map`, `do`, and `subscribe` are not called.

I guess `ProgressResponse` should not be plain JSON file data but also contain details about progress.

**Comment by sunshinejr** [comment]
Hey @chika-kasymov! This kinda boils down to two questions:
1. What am I doing wrong that my `map/do/subscribe` operators are not working on requests with progress.
2. Why I can't provide stubbed progress value over time.

The second one is easier: we currently don't have a support for that. We might look into that in the upcoming versions, though!

And about the first one: I'm not sure. I didn't look into Rx + progress in quite some time so I'd need to prepare a test case and go from there. I will try to find some free time and do it, but if anyone from @Moya/contributors wants to chime in and help before me, you're free to go.

**Comment by chika-kasymov** [comment]
OK, I got it. The second question is what I needed to hear :) I will try another approach then to mock these type of requests.

**Comment by leandromperez** [comment]
@chika-kasymov  I'm experiencing the same issue, I have stubbed data for every endpoint, but for requestWIthProgress, even thought the stubbedData functions are called, the subscriptions are not executed, how did you manage to solve this? Thanks!

**Comment by chika-kasymov** [comment]
@leandromperez the app on which I worked had only one place where the `requestWIthProgress` was used, so I decided to comment out the related test until I got a way to solve that problem. Unfortunately, I didn't have time to do it, and therefore can't help you at this moment.

**Comment by leandromperez** [comment]
@chika-kasymov  no problem, I'll let you know if I find a solution, thanks anyway!

**Comment by leandromperez** [comment]
As I see it, the problem is that requestWithProgress is not using the progress when the stub behavior is different that .never. As a workaround I ended up creating a new method that wraps the original requestWithProgress, like this:

```
extension Reactive where Base : MyProvider {
    /// Designated request-making method with progress.
    func requestWithProgressAllowingStubbing(_ token: Base.Target, callbackQueue: DispatchQueue? = nil) -> Observable<ProgressResponse> {

        let stubBehavior = base.stubClosure(token)

        switch stubBehavior {
        case .never:
            //when the stubbing behavior is .never, just execute the normal requestWithProgress
            return base.rx.requestWithProgress(token, callbackQueue: callbackQueue)
        default:
            //when the stubbing behavior is something else, set the progress to 100% and issue a simple request.
            return base.rx
                .request(token, callbackQueue: callbackQueue).asObservable()
                .map{
                    let full = Foundation.Progress.init(totalUnitCount: 10)
                    full.completedUnitCount = 10
                    return ProgressResponse.init(progress: full, response: $0)
            }
        }
    }
}
```

**Comment by chika-kasymov** [comment]
Seems to be a good solution. I'll try it. Thanks!

**Comment by leandromperez** [comment]
It's a workaround, I don't have much time to work on a PR but the problem
is that requestWithProgress when it uses stubed behaviors, it forgets about
the progress object, so it doesn't report progress, that's why the
subscriptions do not work.
