### ISSUE TITLE
How to handle response data graciously?

### ISSUE THREAD

**Issue by callmewhy** [Moya/Moya#182]
Hi, Moya solve the problem of “request”, and how about "response"?
For example, I want to get the “count” of current online user, the code may look like this:
```
    UserProvider.request(.Online) { (data, status, resonse, error) -> () in
        if let data = data {
            let json: AnyObject? = NSJSONSerialization.JSONObjectWithData(data, options: nil, error: nil)
            if let count = json["count"] as? String {
                ...
            }
        }
    }
````
And every time I want to get the count data, I have to repeat the code above to handle response.

But actually, all I need is the "count" value. Is there any way to handle response data graciously?

Thanks

**Comment by justinmakaila** [comment]
You could extend your provider with a `requestCount` method, which handles that logic for you. You can even go a step further, and have a `requestJSON` method, which handles the JSON serialization for you, and then use it within your `requestCount` method.

```
extension MoyaProvider {
    func requestJSON(endpoint: T, completion: (AnyObject?, NSError?) -> Void) -> Cancellable {
        return self.request(endpoint) { (data, status, response, error) in
            if let data = data {
                let json: AnyObject? = NSJSONSerialization.JSONObjectWithData(data, options: nil, error: nil)
                return completion(json, error)
            }
            
            completion(nil, error)
        }
    }
    
    func requestCount(endpoint: T, completion: (Int, NSError?) -> Void) -> Cancellable {
        return self.requestJSON(endpoint, completion: { json, error in
            if let jsonObject = json as? [NSObject: AnyObject], count = jsonObject["count"] as? Int {
                return completion(count, error)
            }
            
            completion(-1, error)
        })
    }
}
```

**Comment by callmewhy** [comment]
Good idea. Thanks

**Comment by justinmakaila** [comment]
Let me know if that works for you, and I'll close the issue.

**Comment by callmewhy** [comment]
It works for me.

**Comment by justinmakaila** [comment]
Awesome! :+1:

**Comment by ashfurrow** [comment]
Another option is to be fancy :cake: You could use method currying in some way:

```swift
func countCompletion (completion: (Int -> Void)) -> (data: NSData?, statusCode: Int?, response: NSURLResponse?, error: NSError?) {
    return {  (data, status, response, error) -> () in
        if let data = data {
            let json: AnyObject? = NSJSONSerialization.JSONObjectWithData(data, options: nil, error: nil)
            if let count = json["count"] as? Int {
                completion(count)
            } else {
                completion(-1)
            }
        }
    }
}
```

Then call `UserProvider.request(.Online, completion: countCompletion { count -> Void in /* your actual callback, accepting an Int */ })`.

This avoids subclassing, which I personally like, and "feels more Swift", whatever that means. 

@callmewhy The overarching question is how do _we_ deal with this, and I can only speak for myself, but I use the ReactiveMoya or RxMoya to turn these into signals/sequences. Here's [one random example](https://github.com/artsy/eidolon/blob/5b724a68acd4e6e42d2e8b1092b4644ba6b6488b/Kiosk/Bid%20Fulfillment/RegistrationPasswordViewModel.swift#L28).

**Comment by callmewhy** [comment]
@ashfurrow Thanks, it's really awesome!
