### ISSUE TITLE
How to add text as MultipartFormData with images

### ISSUE THREAD

**Issue by GKicw** [Moya/Moya#1821]
Moya/Core (12.0.1)

<img width="1092" alt="Screen Shot 2019-03-22 at 9 05 21 AM" src="https://user-images.githubusercontent.com/46900763/54826263-c91d1b00-4c85-11e9-9d12-2ef34a526d30.png">

above is our requirement, below is my code in **task**

```swift
var identificationData = [MultipartFormData(provider: .data(model.frontImage), name: "file1", fileName: "frontImage", mimeType: "jpg/png"),
            MultipartFormData(provider: .data(model.backImage), name: "file2", fileName: "backImage", mimeType: "jpg/png")]
            identificationData.append(MultipartFormData(provider: .data("description".data(using: .utf8)!), name: "description"))
            return .uploadMultipart(identificationData)
```

seeing a http 400 error code.

**Comment by sunshinejr** [comment]
Hey @GKicw. It seems like you might need to update the `name` in your `MultipartFormData`:

```swift
let images = [MultipartFormData(provider: .data(model.frontImage), name: "frontImage", fileName: "frontImage", mimeType: "jpg/png"),
              MultipartFormData(provider: .data(model.backImage), name: "backImage", fileName: "backImage", mimeType: "jpg/png")]
```

You are also lacking `barCodeText` property in your array of properties (you have `description`, though). Plus, take a look at your `mimeType` as well in your images: you are specifying `jpg/png`, but I'm not sure this is a valid MIME-type (I might be wrong though, but I think you would need to specify it as `image/jpeg` or `image/png` depending on your content type).

**Comment by GKicw** [comment]
@sunshinejr i'm using the same for an image it works properly, issue is when adding text.
here is updated code

var identificationData = [MultipartFormData(provider: .data(model.frontImage), name: "file1", fileName: "frontImage", mimeType: "image/jpeg"),
            MultipartFormData(provider: .data(model.backImage), name: "file2", fileName: "backImage", mimeType: "image/jpeg")]
            identificationData.append(MultipartFormData(provider: .data("barCodeText".data(using: .utf8)!), name: "barCodeText"))
            return .uploadMultipart(identificationData)

**Comment by sunshinejr** [comment]
@GKicw hmm, I'm not sure I follow! But also it seems like you've resolved the issue, is that correct? If so, would you please let me know what was the culprit?

**Comment by GKicw** [comment]
@sunshinejr Thanks, you found the issue, updating the name in MultipartFormData fixed my issue.

**Comment by sunshinejr** [comment]
Perfect! Glad you got it working @GKicw 👍🏻
