### ISSUE TITLE
Carthage build fails on XCode 10.2 Swift 5

### ISSUE THREAD

**Issue by wassimseif** [Moya/Moya#1822]
Please let us know what version of Moya you are using, so we can better pinpoint and/or solve your issue.

Please wrap code blocks in backticks, like so:

```swift
Moya 12.0.1
```

Cartfile
```
github "Moya/Moya"
```

Carthage logs
```
*** Checking out ReactiveSwift at "4.0.0"
Build Failed
        Task failed with exit code 65:
        /usr/bin/xcrun xcodebuild -workspace /Users/user/Desktop/com/project/Carthage/Checkouts/ReactiveSwift/ReactiveSwift.xcworkspace -scheme ReactiveSwift-iOS -configuration Release -derivedDataPath /Users/user/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/ReactiveSwift/4.0.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/38/fytrk84151jfgntn774nrpzw0000gn/T/ReactiveSwift SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/user/Desktop/com/project/Carthage/Checkouts/ReactiveSwift)
```

Most probably since Moya is still fetching  ReactiveSwift 4.0.0 in the Cartfile

```
github "ReactiveCocoa/ReactiveSwift" ~> 4.0

```

Any plans to update to 5.0.0 that supports swift 5 ?

**Comment by RiuHDuo** [comment]
update  ReactiveSwift to 5.0.0

**Comment by wassimseif** [comment]
You mean I should put 
```
github "ReactiveCocoa/ReactiveSwift" ~> 5.0

``` 
 in the Cartfile right ?

If i put this and run 

```
carthage update --platform iOS --no-use-binaries
```

carthage freezes when trying to build the schemes and uses 7GB of RAM.
I know I should report this issues to the carthage repository but shouldn't Moya upgrade ReactiveSwift to 5.0.0?

**Comment by zhusongyu** [comment]
Moya has not been updated, so you should change the Cartfile.resolved, 
github "ReactiveCocoa/ReactiveSwift" "5.0.0"

**Comment by wassimseif** [comment]
Can you please list the steps ?

1. Cartfile  
```
github "Moya/Moya"

```
2.` carthage update --platform iOS --no-use-binaries`
3. Build Failed 
4. Change to`github "ReactiveCocoa/ReactiveSwift" ~> 5.0` in the Cartfile.resolved
5. now what ?

**Comment by mindstormygit** [comment]
I'm stuck here too...

**Comment by pedrovereza** [comment]
@wassimseif
> shouldn't Moya upgrade ReactiveSwift to 5.0.0?

 We did! It's on our `development` branch for now (https://github.com/Moya/Moya/pull/1817). 

If you _really_  need this change right now, you can fork the repo and rely on `development` branch. You can also use the branch on this repo, but we can't guarantee it will always be stable 😅

**Comment by wassimseif** [comment]
Ahh okay.
Will do!. Thank you for the help 👍
