### ISSUE TITLE
How to support Xcode10.2?

### ISSUE THREAD

**Issue by LieonShelly** [Moya/Moya#1823]

**Comment by jdisho** [comment]
Thank you for using `Moya` 😊 
To understand better, can you give some more insights regarding the issue?

**Comment by Maxador** [comment]
Xcode 10.2 requires to build projects and dependencies with Swift 5 which is not supported in Moya I guess (I didn't try it yet).

**Comment by jdanthinne** [comment]
Same here, with Carthage
```
*** Valid cache found for Alamofire, skipping build
*** Valid cache found for Result, skipping build
*** Invalid cache found for ReactiveSwift, rebuilding with all downstream dependencies
*** Invalid cache found for RxSwift, rebuilding with all downstream dependencies
*** Downloading RxSwift.framework binary at "Atomic.2"
***  Skipped installing RxSwift.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1) and the local version is 5.0 (swiftlang-1001.0.69.5 clang-1001.0.46.3)."

    Falling back to building from the source
*** Building scheme "ReactiveSwift-iOS" in ReactiveSwift.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/jdanthinne/Développement/Swift/Apps/GroomService/Carthage/Checkouts/ReactiveSwift/ReactiveSwift.xcworkspace -scheme ReactiveSwift-iOS -configuration Release -derivedDataPath /Users/jdanthinne/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/ReactiveSwift/4.0.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/vh/np47mx2j3tl752jkkjh1tyj40000gn/T/ReactiveSwift SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/jdanthinne/Développement/Swift/Apps/GroomService/Carthage/Checkouts/ReactiveSwift)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/vh/np47mx2j3tl752jkkjh1tyj40000gn/T/carthage-xcodebuild.v7J1VB.log
```

**Comment by aabanaag** [comment]
Got the same issue also.

**Comment by pedrovereza** [comment]
Please check #1822 😉

**Comment by kientux** [comment]
Are you planning to release new version of Moya soon? It should be released as soon as Xcode 10.2 is out 😳

**Comment by jdanthinne** [comment]
FYI, there's a lightweight version of Moya (not dependencies), https://github.com/Flinesoft/Microya, already available. Seems to works fine.

**Comment by sunshinejr** [comment]
@kientux yes we are planning to release a new version soon. I'm gonna update this thread once it's done.

**Comment by larsschwegmann** [comment]
Does it make sense to change the Swift version of the Moya targets to Swift 5? As far as I checked, no conversions were necessary and all tests run fine. I just had to upgrade the testing deps to newer versions as the versions specified in `Cartfile.private` were all written in Swift 3 which wont compile with Carthage and Xcode 10.2.

**Comment by BasThomas** [comment]
I think that would make sense for the next version, yes.

**Comment by sunshinejr** [comment]
Hey guys, Moya 13.0.0-beta.1 has been released 🚀 

https://github.com/Moya/Moya/releases/tag/13.0.0-beta.1

Let me know if you have any troubles with this version on Xcode 10.2!

**Comment by sunshinejr** [comment]
Alrighty, seems like no major issues have appeared so I'm gonna release the official 13.0.0 version today (most likely).

**Comment by sunshinejr** [comment]
Hey all! Moya 13.0.0 is officially released. Have fun and in case something happens, please create new issue.

https://github.com/Moya/Moya/releases/tag/13.0.0
