### ISSUE TITLE
Two onNext events from .request

### ISSUE THREAD

**Issue by aabanaag** [Moya/Moya#1825]
I have this method below which is called on button tap `button.rx.tap.flatMap { self.viewModel.login() }` I noticed that I receive two onNext events from one service call. 

Moya: version 12 (development branch, in order to use swift 5.0)
Xcode: 10.2
```swift
func login() -> Observable<APIResult<Any>> {
    return username
      .throttle(0.5, scheduler: MainScheduler.instance)
      .flatMap { uname in
        self.password
          .throttle(0.5, scheduler: MainScheduler.instance)
          .map { ["username": uname, "password": $0] }
          .flatMap { self.service.provider.rx.request(.login(params: $0)) }
          .debug()
          .filterSuccessfulStatusAndRedirectCodes()
          .map(AuthResult.self)
      }
      .map { APIResult.success($0.token) }
      .catchError { self.service.parseServiceError(error: $0) }
  }
```

**Comment by pedrovereza** [comment]
@aabanaag Hey, did you confirm it was not an issue with Moya? Was it something else in your codebase?

**Comment by aabanaag** [comment]
oh. sorry. forgot to add comment. Yes I was able to fix it, it was not an issue with Moya. I had to change from `username.flatMap { password }` to  `username.withLatestFrom`.

**Comment by pedrovereza** [comment]
Awesome, thanks for clarifying! 🙏
