### ISSUE TITLE
how to perform patch

### ISSUE THREAD

**Issue by aabanaag** [Moya/Moya#1836]
Swift version: 5
Xcode version: 10.2
Moya: 13beta

I need to perform a patch so thats `/api/{id}` then I have to pass a body which is `{ photoUrl: "giphy.com/test" }`any ideas how should I structure it?

**Comment by pedrovereza** [comment]
Hey @aabanaag 

Assuming you have an enum with a case like `example(id: Int, photoUrl: String)`, your target type should look like this:

```swift
var path: String {
  switch self {
    case .example(let id, _):
      return "/api/\(id)"
  }
}

var method: Method {
  switch self {
    case .example:
      return .patch
  }
}

var task: Task {
  switch self {
    case .example(_, let photoUrl):
      return .requestParameters(parameters: ["photoUrl": photoUrl],
                                encoding: JSONEncoding.default)
  }
}
```

**Comment by aabanaag** [comment]
Thanks found it from the documentation
