### ISSUE TITLE
Make releasing easier

### ISSUE THREAD

**Issue by ashfurrow** [Moya/Moya#184]
Currently it takes a lot of steps:

1. Update podspec version.
1. In Demo directory, `pod update Moya`.
1. Commit.
1. Tag new version.
1. Push, including tags.
1. `pod trunk push Moya.podspec`.
1. Hope that current tag lints fine on trunk push.

We should automate this process, preferably using Fastlane.

**Comment by skywinder** [comment]
Hi. I crated special gem for this steps ( it do anything except 2 ). I use it for my personal needs, but create a gem also. Check skywinder/bumper-pusher repo for details. Or just intall and try it: 

    gem install bumper_pusher

You can also try a dry run to verify steps.

**Comment by orta** [comment]
^ looks good, can do a `make release` task?

**Comment by skywinder** [comment]
No. But if it is all about running make release command, I believe that it's easy to implement.

**Comment by orta** [comment]
I mean, your method looks good, we can automate it update and then to run `pod update` in the Moya dir via a make task :+1:

**Comment by skywinder** [comment]
Ok, so we can add some shell script in the root directory to bump and update and push pod.
Feel free to ask, if you need any help with `bumper_pusher`
