### ISSUE TITLE
MoyaProvider with abstract, any enum.

### ISSUE THREAD

**Issue by StasanTelnov** [Moya/Moya#1842]
Hello. I trying create more different TargetType enums and one static execute request method.

I try something like this:
```swift
static func executeRequest(_ service: TargetType, isProduction: Bool, success: @escaping(SuccessClosure) = RestClosures.success, failure: @escaping(FailureClosure) = RestClosures.failure) {
    var pluginsList: [PluginType] = []
    if !isProduction {
        pluginsList = [NetworkLoggerPlugin(verbose: true)]
    }

    let provider = MoyaProvider<service>(plugins: pluginsList)
    //...
    provider.request(service) { result in
       //...
    }
}
```

This code is not valid, because type 'service' is not declated. I try declare alias and abstract of TargetType via ```typealias```, but unsuccessfully.
And I not found examples of create MoyaProvider with any enum, which confirm TargetType.

How I can write my static method, which support ```Any<TargetType>``` enum?
I know, that I can declare one "universal" TargetType enum or create many providers with specific enums, but in my in my case it not good idea. 

Thanks for the help. I am not strong in generics types unfortunately.

**Comment by pedrovereza** [comment]
Hey @StasanTelnov, I'm not sure I understood what issue you're facing, but it seems like what you're looking for is a way to use multiple `TargetType` with a single provider, is  that correct?

If that's the case, check out [MultTarget](https://github.com/Moya/Moya/blob/00c5a18e4dccb7a4293b6fd30fc9cf9424bfc85b/docs/Examples/MultiTarget.md)

**Comment by StasanTelnov** [comment]
@pedrovereza yes, thanks, MultiTarget is that I need.
