### ISSUE TITLE
multiple URL query values separated with commas

### ISSUE THREAD

**Issue by alouanemed** [Moya/Moya#1843]
I want to have the commas in URL query to be encoded instead of having special characters like this:

> category_id=0&content_ids=17%2C17%2C7%2C17%2C7%2C15&page=1&per_page=20&pricing_range=0%20-%20100

Here is my API service Moya configs, I tried using different param encoding but no luck:
```swift
var parameters: [String: Any]? {
        var params: [String: Any] = [:]
        switch self {
        case .search(let content, let min, let max):
            params["content_ids"] = content
            params["pricing_range"] = "\(min) - \(max)"

    
    public var parameterEncoding: ParameterEncoding {
        switch self {
        case .search:
            return URLEncoding.queryString
        default:
            return URLEncoding.default
        }
        
    }
    
```

 Moya version: latest.

Thank you for your help.

**Comment by sunshinejr** [comment]
Hey @alouanemed. I'm not sure if I understand your problem correctly. Do you mean that you don't want encoded query in the URL? The one below?
>category_id=0&content_ids=17%2C17%2C7%2C17%2C7%2C15&page=1&per_page=20&pricing_range=0%20-%20100

Or you can't get Moya to encode your query and you have to pass parameters already encoded, like `17%2C17%2C7%2C17%2C7%2C15` instead of `1, 2, 3, 4`?

Also,do you use `post` or `get` http method for the `search` one?

**Comment by alouanemed** [comment]
Thank you for your reply.

I am using `GET`.
I want the url to be like this:

> category_id=0&content_ids=17, 7, 5&page=1&per_page=20&pricing_range=20-100

**Comment by pedrovereza** [comment]
Hey @alouanemed, this is a bit tricky as you will have to [create your own `ParameterEncoding`](https://github.com/Alamofire/Alamofire/blob/master/Documentation/Usage.md#custom-encoding)

I gave it a try and used the `URLEncoding` from `Alamofire` as a starting point. This implementation seems to cover your scenario, but it is very simple and does not include a lot of logic that lives in `URLEncoding`. If your case is as simple as the example you provided, it should be safe to use this code, but if you have more parameter types I strongly encourage it you to test it all first and add whatever is missing 😄 

This encoding generates the url as you wanted:

```
https://service.com?category_id=0&content_ids=17,5,7&per_page=20&pricing_range=20-100
```

```swift
struct CustomUrlEncoding : ParameterEncoding {
    func encode(_ urlRequest: URLRequestConvertible, with parameters: Parameters?) throws -> URLRequest {
        var urlRequest = try urlRequest.asURLRequest()

        guard let parameters = parameters else { return urlRequest }

            guard let url = urlRequest.url else {
                throw AFError.parameterEncodingFailed(reason: .missingURL)
            }

            if var urlComponents = URLComponents(url: url, resolvingAgainstBaseURL: false), !parameters.isEmpty {
                let percentEncodedQuery = (urlComponents.percentEncodedQuery.map { $0 + "&" } ?? "") + query(parameters: parameters)
                urlComponents.percentEncodedQuery = percentEncodedQuery
                urlRequest.url = urlComponents.url
            }

        return urlRequest
    }

    private func query(parameters: Parameters) -> String {
        var components: [(String, String)] = []

        for key in parameters.keys.sorted(by: <) {
            let value = parameters[key]!
            components += queryComponents(fromKey: key, value: value)
        }
        return components.map { "\($0)=\($1)" }.joined(separator: "&")
    }

    public func queryComponents(fromKey key: String, value: Any) -> [(String, String)] {
        var components: [(String, String)] = []

        if let array = value as? [Any] {
            components.append((key, encode(array: array, sepparatedBy: ",")))
        } else {
            components.append((key, "\(value)"))
        }

        return components
    }

    private func encode(array: [Any], sepparatedBy separator: String) -> String {
        return array.map({"\($0)"}).joined(separator: separator)
    }
}
```

Usage:

```swift
// On your TargetType
var task: Task {
        return .requestParameters(
            parameters: [
                "category_id": 0,
                "content_ids": [17, 5, 7],
                "per_page": 20,
                "pricing_range": "20-100"
            ],
            encoding: CustomUrlEncoding())
    }
```

**Comment by alouanemed** [comment]
Thank you @pedrovereza! I will test it out and let you know.
