### ISSUE TITLE
How to set "Content-Type" header to "application/octet-stream"

### ISSUE THREAD

**Issue by metisdev** [Moya/Moya#1844]
Hello,

First of all thanks for such helpful library 👍 
Using: Moya (13.0.0)

My server side guy wants the header "Content-Type" set to "application/octet-stream" when uploading files. Before i was using "multipart/form-data".

I could not find a way to set this header. Would you please guide me for the best way to set this header.

Best Regards

PS: I tried setting it with custom headers but as far as i see Moya or Alamofire overwrites this header

**Comment by sunshinejr** [comment]
Hey @metisdev. AFAIK Alamofire is updating the multipart's `Content-Type` header just before executing the request so you can't really change the `multipart/form-data` into `application/octet-stream` while doing multipart upload.

If you can upload the file without using a `multipart` request, you can use pure `Task.upload()` case and set the header in your `TargetType` - then it shouldn't be overwritten.
