### ISSUE TITLE
Base URL

### ISSUE THREAD

**Issue by thedevme** [Moya/Moya#185]
So I am using ReactiveMoyaProvider and I am able to make calls with a base url and those paths. Everything works perfect so thank you. But my feed provides additional urls example:

"live-chat": "http://example-url-staging.herokuapp.com/plays.json/"
  
I want to be able to pass this string to the Provider and have it make my request.  I have looked around and I can't seem to find anything that points me in the right direction.  Any help would be much appreciated. So basically is there anyway to do a provider that takes both a baseURL and one that doesn't or some else.  Thanks

**Comment by alexito4** [comment]
Hi here!
It's been a while since I don't play with Moya but just to try to help here, the issue seems related to what was discussed in https://github.com/Moya/Moya/issues/102

Hope it helps a little ;)

**Comment by thedevme** [comment]
Thanks for the response.  I am not finding a solution with that link.  I figured that I will need to split the string and pass a base url and the path but I cant seem to figure out how to dynamically set the base url if thats even possible.  My major problem is that the base urls that I have are not always the same.

**Comment by thedevme** [comment]
I actually figured out a way to do it in a simplified way using enums thanks for your help @alexito4

**Comment by chrisfarrell** [comment]
@thedevme can you provide an example of your solution?
