### ISSUE TITLE
Request Body parameters order

### ISSUE THREAD

**Issue by LvJianfeng** [Moya/Moya#1851]
##### Code
```swift
var requestHeaderFields: ([String : Any]?) -> [String: String] = { params in
    let v = "2.0.0"
    let t = "1556977057000" 
    
    print("初始化Sign:\("\("{}\(t)".md5())\(v)".md5())")
    var headerFields = ["key": "\("{}\(t)".md5())\(v)".md5(),
                        "t": t,
                        ...
    ]
    
    if params?.count ?? 0 > 0 {
       print("Update JSON By Params:\(JSON(params!).rawString(.utf8, options: .init(rawValue: 0))!)")
        headerFields.updateValue("\("\(JSON(params!).rawString(.utf8, options: .init(rawValue: 0))!)\(t)".md5())\(v)".md5(), forKey: "key")
    }
    
    return headerFields
}


/// -------

let paramEndpoint = { (target: APIParam) -> Endpoint in
    return MoyaProvider.defaultEndpointMapping(for: target).adding(newHTTPHeaderFields: requestHeaderFields(target.parameters))
}
```

##### Log
```json
// POST Params
Update JSON By Params：{"username":"10000","password":"dd7a8c7d3150ac44e6886d1aaa14da78"}

/// Request Body Parameters
Moya_Logger: [04/05/2019 21:42:01] Request Body: {"password":"dd7a8c7d3150ac44e6886d1aaa14da78","username":"0563031250"}
```

##### Question
In XCode 10.2.1, The order of the request parameters of the header information is inconsistent with the order of the parameters at the time of the request.

Normal in Xcode 10 or 10.1.

Please help.

##### Version
```ruby
  - Moya/Core (12.0.1):
    - Alamofire (~> 4.1)
    - Result (~> 4.0)
  - Moya/RxSwift (12.0.1):
    - Moya/Core
    - RxSwift (~> 4.0)
```

**Comment by sunshinejr** [comment]
Hey @LvJianfeng. Dictionary doesn’t really have an order like an array. Thus, the output might differ each time you print it. See [this SO answer ](https://stackoverflow.com/a/29603477) for a reference.

**Comment by LvJianfeng** [comment]
Hi @sunshinejr , I know, but this problem happened in XCode 10.2.1. The previous version has never happened, so I wondered if it would be caused by XCode or by version.

**Comment by LucianoPAlmeida** [comment]
Hey @LvJianfeng 
There were changes on how the hash seed works for dictionary and set types on swift 5.0, so the order might differ a lot more between two instances with the same values and keys :))
See on the Xcode 10.2 [release notes on the standard library section](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_2_release_notes/swift_5_release_notes_for_xcode_10_2)
<img width="826" alt="Screen Shot 2019-05-05 at 23 00 56" src="https://user-images.githubusercontent.com/8292651/57203881-f7cb2880-6f89-11e9-8544-1b414e58faa2.png">

**Comment by LvJianfeng** [comment]
@LucianoPAlmeida  So, thank you for your answer, we need to get to know Swift 5 as soon as possible, otherwise the same problem will occur in the future with XCode 10.2.1.

**Comment by michellemmy** [comment]
@LvJianfeng 
_Ask, the current version, how do I control the header information to get the submission parameters consistent with the request body's submission parameters?_

Can someone help me answer this previously ask question above? Bump to this issue and quite confuse as to how maintain a consistent request body parameters.
