### ISSUE TITLE
[!] CocoaPods could not find compatible versions for pod "RxSwift":

### ISSUE THREAD

**Issue by GTramp** [Moya/Moya#1852]
[!] CocoaPods could not find compatible versions for pod "RxSwift":
  In snapshot (Podfile.lock):
    RxSwift (= 4.5.0, ~> 4.0)

  In Podfile:
    RxSwift (~> 5.0.0)

None of your spec sources contain a spec satisfying the dependencies: `RxSwift (~> 5.0.0), RxSwift (= 4.5.0, ~> 4.0)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

**Comment by sunshinejr** [comment]
Hey @GTramp, we do not support RxSwift yet. We are preparing the release that would cover RxSwift 5, ReactiveSwift 6 and Alamofire 5, but it’s not ready yet.

**Comment by GTramp** [comment]
I see, thank you !

**Comment by sunshinejr** [comment]
@GTramp We actually released an alpha version 14.0.0-alpha.1 if you want to try. Gonna close this issue but let me know if I can help you with anything else :)
