### ISSUE TITLE
support rxswift 5.0

### ISSUE THREAD

**Issue by FlyingNoob** [Moya/Moya#1854]
support rxswift 5.0 in podsepecs.json for the dependence

**Comment by HydeHunter2** [comment]
@FlyingNoob -- Do you want to work on it? If not, I would like to take it.

**Comment by sunshinejr** [comment]
Hey @FlyingNoob and @HydeHunter2. We already have it working on `development` branch, but we won't really make a new version until Alamofire integration is ready. Sorry for the delay.

**Comment by HydeHunter2** [comment]
Good. Thanks for saying before I started working on it 👍

**Comment by FlyingNoob** [comment]
@HydeHunter2 @sunshinejr Thanks for your help

**Comment by juliengdt** [comment]
AF 5.0 seems to not be hurried to be released; is it thinkable to have a pre-release of Moya (13.x.x-beta) with beta support of Alamofire 5 ? 🤔 

great work everyone on (Rx/Reactive)Moya 👍

**Comment by sunshinejr** [comment]
@juliengdt yeah... I mean, we _could_ do an alpha release, but there will be breaking changes afterwards with the Alamofire transition for sure. Still, I think this is something that many people would want in the meantime, so I'm gonna try to release it in a few minutes 👍

**Comment by sunshinejr** [comment]
Alright y'all, 14.0.0-alpha.1 is released. It covers new RxSwift/ReactiveSwift versions. Bear in mind in the next pre-release we would also add Alamofire and probably remove Result as well.

https://github.com/Moya/Moya/releases/tag/14.0.0-alpha.1

cc @FlyingNoob @HydeHunter2 @juliengdt
