### ISSUE TITLE
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Invalid type in JSON write (__SwiftValue)

### ISSUE THREAD

**Issue by Ualikhan07** [Moya/Moya#1859]
i want filter data when fetching with json,when i send all values app crashes
//1
case retailList(Int,Int)
//2
case .retailList(let cityId, let catId):
struct Filters {
var cityId: Int
var categoryId: Int
}

value["filter"] = Filters(cityId: cityId,categoryId: catId)
//3
case .retailList(let cityId, let catId):
value["filter"] = [{
value["cityId"] = cityId
value["categoryId"] = catId
}]

let request = javaNetworkProvider.request(.retailList(cityId, catId), callbackQueue: Queue, progress: nil, completion: { result in
if let value = result.value {
}

**Comment by sunshinejr** [comment]
Hey @Ualikhan07, sorry for the late response. I'm trying to understand what actually happened, but I can't seem to connect the dots.

Can you post a code and point out which line crashed your project? Also the crash message would be awesome to have as well. For now I only see some lines of code that I can't really connect; is the `value` dictionary a dictionary that you pass as your request parameters? If so, you need to be careful when using `value["filter"] = Filters(cityId: cityId,categoryId: catId)` - this might not be encodable using json & url encoding and that might a culprit for the crash.

**Comment by Ualikhan07** [comment]
@sunshinejr guys I have already found a solution thanks you too much✌️😉

**Comment by sunshinejr** [comment]
@Ualikhan07 awesome! Do you remember what was the issue?

**Comment by Ualikhan07** [comment]
@sunshinejr        
 case .retailList(let cityId, let categoryId,let pageNumber):

            value["filter"] = ["cityId":cityId,"categoryId":categoryId]
            value["pageNumber"] = pageNumber;
            value["size"] = 10;
            break;

**Comment by sunshinejr** [comment]
@Ualikhan07 perfect, thanks so much!
