### ISSUE TITLE
why not use Alamofire.SessionManager.defualt

### ISSUE THREAD

**Issue by Lishaoshuai** [Moya/Moya#1861]
Moya version: 10.0.2
In this func
```
public final class func defaultAlamofireManager() -> Manager {
        let configuration = URLSessionConfiguration.default
        configuration.httpAdditionalHeaders = Manager.defaultHTTPHeaders

        let manager = Manager(configuration: configuration)
        manager.startRequestsImmediately = false
        return manager
    }
```
why not use
```
let manager = Manager.default
manager.startRequestsImmediately = false
```

**Comment by sunshinejr** [comment]
Hey @Lishaoshuai, that's a good question! I think we just wanted to have control over what is the default manager for us and that it won't change without us knowing it. Currently, the implementation is the same and we probably could replace it with the code you just posted, but in Alamofire 5 there is no such thing as `SessionManager` anymore, so it would be pointless.

Let me know if it makes sense!
