### ISSUE TITLE
Regenerate moya.github.io docs on Moya release.

### ISSUE THREAD

**Issue by sunshinejr** [Moya/Moya#1864]
We have a repository that gathers our docs and represents it beautifully on our website https://moya.github.io.

The problem is that these docs currently have to be generated manually and that's easy to forget. @f-meloni suggested that we could use setup similar to the one they use at [danger-swift](https://github.com/danger/swift/blob/master/Package.swift#L57) which generates the docs automatically.

This task is for creating an automation to regenerate the docs on each release. For releasing new Moya version we use our [Rake script](https://github.com/Moya/Moya/blob/master/Rakefile#L158) and this would be a good starting point.

Also see #1862 discussion as this is where the idea came from.

Let me know if you would be interested in helping out or if you have any questions regarding this task!

**Comment by MetalDent** [comment]
Hi, anyone working on this?

**Comment by sunshinejr** [comment]
hey @MetalDent, I don't think anyone started working on this one yet - would you like to try?

**Comment by MetalDent** [comment]
@sunshinejr yeah I can try! 

I saw the danger script to auto-generate docs. Do you want similar implementation? And where should this change go?

**Comment by sunshinejr** [comment]
@MetalDent I don’t have a preference for implementation - you can do whatever you are good at or think will be enough.

The docs should auto-generate on our second repository (https://github.com/Moya/moya.github.io)

**Comment by MetalDent** [comment]
@sunshinejr I'll also use `rocket` . So which files from this repository do you want to auto-generate in the other repository?

**Comment by sunshinejr** [comment]
@MetalDent so once you ran the docs generating using jazzy:
```bash
jazzy -o URL_TO_THE_DOCS
```

we should move all the docs to the `moya.github.io` repo

**Comment by sunshinejr** [comment]
@MetalDent now that I think about it... can it be done from the GitHub Actions?

**Comment by MetalDent** [comment]
@sunshinejr sorry I can't work on this my iOS VM is not working right now :(

**Comment by sunshinejr** [comment]
@MetalDent don't worry, we can wait, it's not something urgent right now - just nice to have 👍

**Comment by hamdshah** [comment]
Why don't we use the same repo for the documentation instead of the separate one ?
I mean we can configure this one for Github pages.
