### ISSUE TITLE
rx subscribe never seems to run

### ISSUE THREAD

**Issue by jimijon** [Moya/Moya#1865]
Latest as of today.

No matter how I structure a RX type call, my subscribe never seems to fire. I am retaining the service. For instance:

            wServiceProvider.rx.request(.getWeatherByCity(city: "London"))
            .debug()
            .map(Weather.self)
            .subscribe({ (event) in
                switch event {
                case let .success(response):
                    print(response)

                case let .error(response):
                    print(response)
                }
            })
            .disposed(by: self.disposeBag)

what am I missing?

**Comment by sunshinejr** [comment]
Hey @jimijon! Do you see any debug logs in your current code? Could you also add `debug("afterMap")` after the `map` operations and post the logs here?

**Comment by jimijon** [comment]
oops sorry. My problem was I was learning it via a test code. I needed to put                   `expectation.fulfill()`
inside the "subscribe" then it ran. It was a XCTest issue.

**Comment by sunshinejr** [comment]
@jimijon awesome, glad you figured it out!
