### ISSUE TITLE
How to send an array of values as form-data

### ISSUE THREAD

**Issue by mkkroliks** [Moya/Moya#1868]
I have to send a parameters as a form-data in following way.

![image](https://user-images.githubusercontent.com/2151961/59193111-f42c5200-8b84-11e9-9dab-3247107ce21e.png)

I can't do it like so `["parameter_id[]": 2, "parameter_id[]": 3]`, because both values has the same key.

I was trying to do it in this way but it also doesn't seems to work.

```
           var data = [MultipartFormData]()

            ids.forEach {
                var intValue = $0
                let myIntData = Data(bytes: &intValue,
                                     count: MemoryLayout.size(ofValue: intValue))
                data.append(MultipartFormData(provider: .data(myIntData), name: "parameter_id[]"))
            }
            
            return .uploadCompositeMultipart(data, urlParameters: [:])
```

Any ideas how can I do it? Maybe there is an other way of sending parameters which server will interpret.

**Comment by sunshinejr** [comment]
Hey @mkkroliks! Really interesting question. Can you use `NetworkLoggerPlugin` and post a `request`/`response` to get logs for this one? Seems like what you're doing should be the same as Postman would do:
```
Content-Disposition: form-data; name="parameter_id[]"
_some_data_
Content-Disposition: form-data; name="parameter_id[]"
_some_data_
```

**Comment by mkkroliks** [comment]
@sunshinejr Thanks for your interest. Actually log does not show a lot since it's multipart request. 

```
Moya_Logger: [10/06/2019 15:10:36] Request: https://sample.com
Moya_Logger: [10/06/2019 15:10:36] Request Headers: ["Content-Type": "multipart/form-data; boundary=alamofire.boundary.477350f9088c225d"]
Moya_Logger: [10/06/2019 15:10:36] HTTP Request Method: POST
Moya_Logger: [10/06/2019 15:10:36] Response: <NSHTTPURLResponse: 0x100adfcd0> { URL: https://sample.com } { Status Code: 422, Headers {
    "Cache-Control" =     (
        "no-cache, private"
    );
    "Content-Type" =     (
        "application/json"
    );
    Date =     (
        "Mon, 10 Jun 2019 13:10:42 GMT"
    );
    Server =     (
        "nginx/1.14.0 (Ubuntu)"
    );
    "x-ratelimit-limit" =     (
        60
    );
    "x-ratelimit-remaining" =     (
        58
    );
} }
{"errors":{"parameter_id.0":["The parameter id.0 must be an integer."],"parameter_id.1":["The parameter id.1 must be an integer."]}}
```

**Comment by JashBalar** [comment]
@mkkroliks hey, I'm trying the same with uploadMultipart and my POSTMAN is the same as yours any idea how to send integer array? I surf on web and found I have to convert [Int] into String using JSONEncoder but I'm still getting error
please help
