### ISSUE TITLE
Manual installation instructions and iOS 7 support

### ISSUE THREAD

**Issue by mikejd** [Moya/Moya#187]
Our app is still required to support iOS 7, so CocoaPods / Carthage are not considered as options. Could you please give any guidance on manual installation of the library? Or would you recommend against using `Moya` in this case? Thank you!

**Comment by justinmakaila** [comment]
Add the `.xcodeproj` to your project, and then link the `Moya.framework` output against your project.

Let me know if you have any issues or need more clarification.

**Comment by esttorhe** [comment]
But doing that wouldn't produce a framework as well?
Which are not available to be used on 7 iirc?

--
Esteban Torres
(+506)8813-0934
Twitter: @esttorhe




On Wed, Aug 19, 2015 at 6:13 AM -0700, "Justin Makaila" <notifications@github.com> wrote:












Add the .xcodeproj to your project, and then link the Moya.framework output against your project.



Let me know if you have any issues or need more clarification.

**Comment by mikejd** [comment]
@justinmakaila, @esttorhe: In iOS 7 we cannot use dynamic frameworks, so probably there's no way to install `Moya` and neither `ReactiveCocoa` (which seemingly dropped iOS 7 support at some point). Please let me know, if I'm wrong.

**Comment by justinmakaila** [comment]
Oh, sorry, just woke up. Skimmed it and missed that part ;)

You can just add the source files straight to the project.

**Comment by mikejd** [comment]
@justinmakaila: It was the first thing that I did. : ) But then you need to add `ReactiveCocoa`, which is not possible for iOS 7. From their `Readme` page:
> ReactiveCocoa supports OS X 10.9+ and iOS 8.0+.

I realized this limitation only after asking the question. Seems that the `Moya` is an iOS 8+ library as well.

**Comment by ashfurrow** [comment]
Maya itself should be usable without frameworks, but would require modification. 

Moya is built atop of Alamofire, so you'd need to have those `.swift` files in your project. Then you'd drop in the Moya `.swift` files, but that's not enough. Moya has `import Alamofire` statements that need to be removed first. Then in should work. 

A similar process _should_ work for ReactiveCocoa, but @mikejd you're right – RAC 3 is iOS 8+ only.

**Comment by mikejd** [comment]
@ashfurrow Thank you for clarification! I realized that there's some manual way to get things work, but it seemed tedious to try. Finally we decided to simply drop iOS 7 support, so this no more an issue.

**Comment by ashfurrow** [comment]
Cool, glad to hear it worked out! :tractor:
