### ISSUE TITLE
Combine-based version of Moya?

### ISSUE THREAD

**Issue by Dschee** [Moya/Moya#1870]
I'm personally not a reactive programming advocate (actually far away from it) but now that Apple has their own take on it with the [Combine](https://developer.apple.com/documentation/combine) library in Xcode 11, I will definitely give it a second chance and therefore also wonder if it would make sense to add `MoyaCombine` to the list of variants we already provide for Moya. That one, I might actually use some day. :)

**Comment by sunshinejr** [comment]
@Dschee I think this is a very good idea. Thanks for bringing it up 👍

**Comment by Dschee** [comment]
Oh god, how I hate these bots. 😅

**Comment by CaptainYukinoshitaHachiman** [comment]
+1, Looking to Combine support too

**Comment by sunshinejr** [comment]
Hey all, I'm implementing the Combine extensions as we speak but I need your help. What API do you like the most? See this poll https://github.com/Moya/Moya/issues/1905 and let me know 👍

**Comment by sunshinejr** [comment]
I just merged the Combine extension, should be in the next beta 👍 will comment here once it's done!

**Comment by sunshinejr** [comment]
Hey all, I just released Moya 14.0.0-beta.1 with Combine extensions in there! 🚀

I'm gonna close this issue but don't hesitate to open new ones for bugs or feature requests!

**Comment by vikmeup** [comment]
@sunshinejr is there any basic example how do you use Combine with SwiftUI? or some samples of the best practices

**Comment by pwnSmithers** [comment]
> Hey all, I just released Moya 14.0.0-beta.1 with Combine extensions in there! 🚀
> 
> I'm gonna close this issue but don't hesitate to open new ones for bugs or feature requests!

Hey @sunshinejr any documentation on using combine with SwiftUI?

**Comment by andrevinic** [comment]
Well, there is still no docs about combine with SwiftUI?...
