### ISSUE TITLE
Result should be 5.0.0?

### ISSUE THREAD

**Issue by Adrift001** [Moya/Moya#1871]
Result should be 5.0.0?

**Comment by Adrift001** [comment]
Who can answer my question?

**Comment by sunshinejr** [comment]
Hey @Adrift001! In latest release of Moya (13.*) we use Result 4.* as this was what we could use at the moment. For new version, Moya 14.*, we will be removing Result dependency as it is no longer needed - both core of Moya and all o its dependencies will use Swift 5 and the built-in Result type.

Hope this clears things up, but don't hesitate to ask more questions regarding this topic!

**Comment by Adrift001** [comment]
Thanks!
