### ISSUE TITLE
Cannot convert value of type 'Result<Response, MoyaError>' to specified type 'Result<Response, MoyaError>'

### ISSUE THREAD

**Issue by Tonku** [Moya/Moya#1872]
Any idea of this error ?

Cannot convert value of type 'Result<Response, MoyaError>' to specified type 'Result<Response, MoyaError>'

**Comment by sunshinejr** [comment]
Hey @Tonku. What Moya version do you use? Do you also use reactive extensions (Rx/ReactiveSwift)?

**Comment by Tonku** [comment]
Hi Buddy I resolved it by importing Result 
:)
Pretty strange error message. 
Thanks for your time

**Comment by sunshinejr** [comment]
@Tonku glad you resolved the issue! 🎉 ( and thanks for posting what was the problem!)

**Comment by jeffasd** [comment]
import Moya
import Result

**Comment by jeffasd** [comment]
> Any idea of this error ?
> 
> Cannot convert value of type 'Result<Response, MoyaError>' to specified type 'Result<Response, MoyaError>'

import Moya
import Result
