### ISSUE TITLE
FormDataProvider the case stream(InputStream, UInt64), how can i input the last parameter?

### ISSUE THREAD

**Issue by FreshAlpha** [Moya/Moya#1874]
/// Method to provide the form data.
    public enum FormDataProvider {
        case data(Foundation.Data)
        case file(URL)
        case stream(InputStream, UInt64)
    }
`let demoData = Data()`
`let demoFormData = MultipartFormData(provider: .stream(InputStream(data: demoData), UInt64(demoData.count)), name: "demoData")`

is this invoking correct?
in case stream(InputStream, UInt64), i'm not sure the last parameter which type is UInt64 means the  demoData's count or the result of InputStream's function 
open func read(_ buffer: UnsafeMutablePointer<UInt8>, maxLength len: Int) -> Int.
help,Thanks!

**Comment by sunshinejr** [comment]
Hey @FreshAlpha, sorry for the late reply! But yeah, you're correct, the `UInt64` is the "length" of the stream. In your case it would be `UInt64(demoData.count)` - this is the length of your data and thus the length of your stream.

Also, what do you think about adding the label "length" to the case? Would it help you or it wouldn't make a difference? You would call it then:
```swift
let demoData = Data()
let demoStream = InputStream(data: demoData)
let demoStreamLength = UInt64(demoStream.count)
let demoFormData = MultipartFormData(provider: .stream(demoStream, length: demoStreamLength), name: "demoData")
```

**Comment by FreshAlpha** [comment]
@sunshinejr thank you for your help and reply！
I think there is no need to add label "length", it will confuse others, for example, me.
sorry, my english is poor.

**Comment by FreshAlpha** [comment]
i have a new question.
`let demoStreamLength = UInt64(demoStream.count)`
demoStream has no function count. I can't invoke demoStream.count.

**Comment by sunshinejr** [comment]
@FreshAlpha ah yes that’s a typo, should be `demoData.count`

**Comment by FreshAlpha** [comment]
@sunshinejr  
get it. Thanks a lot.😊
