### ISSUE TITLE
If the request parameter is Array, there will be a problem with []

### ISSUE THREAD

**Issue by tyzChar** [Moya/Moya#1879]
![image](https://user-images.githubusercontent.com/13286325/60789765-757e0100-a192-11e9-8c4d-e09d1aaf5ef3.png)

![image](https://user-images.githubusercontent.com/13286325/60789670-39e33700-a192-11e9-9332-be6fee9bf44a.png)

Because the default is to add [] to the parameter.
So we need to set no []
![image](https://user-images.githubusercontent.com/13286325/60789783-80389600-a192-11e9-89d1-649d5e048e2b.png)

**Comment by tyzChar** [comment]
请求参数是数组(Array<Any>)请求参数会被默认加上[]的解决方法

**Comment by cddjr** [comment]
即 arrayEncoding 应默认使用 noBrackets 方式
