### ISSUE TITLE
Authorization header field issue

### ISSUE THREAD

**Issue by rupeshsaxena** [Moya/Moya#1882]
Moya Version : 9.0.0

The issue is that when I use the below header field with the API key as a bearer token, the server responds with the invalid token , even though the same token is being used in the Alamofire API directly and it works well (using Alamofire's way of adding header fields). 

``` swift
var headers: [String : String]? {
        
        switch self {
        case .cart(rid: _, cartId: _):
            //.. something..
        case .placeOrder(req: _):
            
            return ["Authorization": "Bearer \(API_KEY)"]
        }
        
    }
```

** Moya Request Log **

Moya_Logger: [12/07/2019 16:36:33] Request: http://API_LINK/api/v1/table_order/push?customer_key= **SOME CUSTOMER KEY**
Moya_Logger: [12/07/2019 16:36:33] Request Headers: ["Content-Type": "application/json", "Authorization": "Bearer **Some Token**"]
Moya_Logger: [12/07/2019 16:36:33] HTTP Request Method: POST

**Response received from API Server :**

Response status code was unacceptable: 401

**Comment by amaurydavid** [comment]
Did you compare the cURL versions of both your requests? Was is different between those two?

Note: To get a cURL version of a moya request you can use the cURL parameter in MoyaLoggerPlugin. 
To get cURL version of an Alamofire request you can use the debugDescription of an Alamofire.Request obejct.
