### ISSUE TITLE
Need map Response in each plugin?

### ISSUE THREAD

**Issue by rakuyoMo** [Moya/Moya#1883]
I am using the latest version of Moya, but I have a problem

In the plugin, I received a parameter of type Moya.Response, which means that if I want to use the data inside, I need to perform a map operation in each plugin.

Does this mean meaningless overhead? Can I avoid this waste through caching, or other simpler ways?

**Comment by rakuyoMo** [comment]
I hope I can get the real Model type in plugin, or when I use `provider.request(target).mapJSON()` or other `map` methods, I can get JSON directly in plugin without having to parse it again.

**Comment by amaurydavid** [comment]
You are right, you can only get Data from the Response. This allows every usages to be possible as a lot of requests don't return JSON but XML, binary or something else.

What are you trying to do with your plugin? There might be an other way to be it without using plugins, hence without having to Decode your data multiple times for the same request.

**Comment by rakuyoMo** [comment]
For our project, the format returned by each API is very similar, for example:

```json
{
  "code": 0,
  "result" : ...
}
```

We determine whether the request is successful based on the content of the `code`, so if I need `code` in my plugin, then I need a `map`.

So is it possible for the author to provide a way to simplify this problem?

**Comment by amaurydavid** [comment]
One way to do it is to use plugin's process func in which you only decode the "code" JSON field, and return a Result matching it.
Here is an example: 
```
final class CodeCheckPlugin: PluginType {

  struct BasicResponseModel: Decodable {
    let code: Int

    private enum CodingKeys: String, CodingKey {
      case code
    }
  }

  enum Error: Swift.Error {
    case unvalidCode
  }

  func process(_ result: Result<Moya.Response, MoyaError>, target: TargetType) -> Result<Moya.Response, MoyaError> {
    guard case let .success(response) = result else { return result }

    //Parse the JSON to get the returned code
    let model: BasicResponseModel
    do {
      model = try JSONDecoder().decode(BasicResponseModel.self, from: response.data)
    } catch {
      return Result.failure(MoyaError.objectMapping(error, response))
    }

    if model.code.isValid() {
      return result
    } else {
      return Result.failure(MoyaError.underlying(Error.unvalidCode, response))
    }
  }
}
```

You only decode the "code" field of your JSON to check its value. If it's valid then you will have to decode the whole response data, if not you only decoded 1 field but not the entire data.
