### ISSUE TITLE
Moya doesn't support add https/http prefix to the baseURL in TargetType

### ISSUE THREAD

**Issue by g-enius** [Moya/Moya#1889]
Moya will fail if I return a URL without "https://" for baseURL in TargetType.

I know the answer will be "why don't you return a constant value". The answer is that we are using remote configs, which returns not only host but also some relative path like "https://abc.com/path/a"

However, when I use URL(:).host to filter the relative path, it will also trim that "https://" prefix. So I have to add that back manually otherwise Moya fails. See examples below:

```swift
extension APIService: TargetType {
    var baseURL: URL {
        switch self {
        case .maskedURL:
            guard let baseString = URL(string: maskedURLRemoteConfig)?.host,
                let baseURL = URL(string: ("https://" + baseString))
                else { return URL(string: "")!}
            return baseURL
     }
}
```

As Moya is such an amazing project, I would expect Moya would do intelligent magic for me. Like what browsers will do, always auto-complete these prefix for uses.

I would say it would be an awesome feature. How do you guys think?

**Comment by amaurydavid** [comment]
The way you create your base url is not optimum and you can prevent manually prefixing the scheme with a String as intermediary object by using `URLComponents` :

```
let url = URL(string: "https://host.com/path/to/resource/a")
var newComponents = URLComponents()
newComponents.scheme = url?.scheme
newComponents.host = url?.host
var baseURL = newComponents.url
```

As for Moya not filling blanks in given baseURLs, I think behind the "autofill" of internet browsers there are a lot of things preformed under the hood and even if it was possible to implement it, I'm not sure it would be worth it. I can't think of a case where you have to perform some http requests and you don't have a complete baseURL to provide.

**Comment by g-enius** [comment]
Thank you @amaurydavid 
I will close this issue and adopt your suggestion.
