### ISSUE TITLE
Add examples to documentation

### ISSUE THREAD

**Issue by ashfurrow** [Moya/Moya#189]
Our documentation is thorough, but not instructive. We need to do a better job of providing examples and real-world scenarios. 

(Continued from #188.)

> In general I would shoot for more complete examples. Newcomers as I am one, lack guidance. For example it wasn't quite clear at first for me if I have to implement my own Provider. Turns out it was sufficient to use the default one with a closure as an initialization parameter. —@jk

**Comment by ashfurrow** [comment]
Might make sense for a more in-depth demo in a separate repo on this organization.

**Comment by bontoJR** [comment]
This is definitely something I would like to see. :)

At the moment I am trying to figure out how to have a parameter always passed to every request, in this case is an `access_token`. It took me some time to understand how to use this library and I had to check the whole source code to master it, I know they are not so much lines, but still... also the RxSwift's version requires some extra documentation b/c it looks like is outdated, I think. :+1:

**Comment by scottrhoyt** [comment]
We have some real-ish examples in the documentation now. Do you think that is enough to close this issue?
