### ISSUE TITLE
Upload Mutilpart File fail

### ISSUE THREAD

**Issue by lokizero00** [Moya/Moya#1895]
I'm using pod 'Moya/RxSwift' 13.0.1
When uploading photos, it always fail
Here is my swift code 💯 

    var task: Task {
        switch self {
        case .uploadImage(let image):
            let data = image.jpegData(compressionQuality: 1.0)
            let form=MultipartFormData(provider: .data(data!),name: "file",fileName:"photo.png",mimeType:"image/png")
            return .uploadMultipart([form])
        case .uploadFile(let data,let mimeType,let fileExt):
            let form=MultipartFormData(provider: .data(data),name: "file",fileName:"file.\(fileExt)",mimeType:mimeType.rawValue)
            return .uploadMultipart([form])
        default :
            return .requestPlain
        }
    }

    var parameterEncoding: ParameterEncoding {
        switch self {
        case .addIdentityCertification,.publishTrade,.addDocking,.addReport,.addEnterpriseCertification:
            return CompositeEncoding()
        default :
            return URLEncoding.default
        }
    }

    var sampleData: Data {
        return "{\"test\": 1}".utf8Encoded
    }

    var headers: [String : String]? {
        switch self {
        case .uploadImage:
            return ["Content-Type":"multipart/form-data"]
        case .uploadFile:
            return ["Content-Type":"multipart/form-data"]
        case .addIdentityCertification,.addEnterpriseCertification,.publishTrade,.addDocking,.addReport:
            return ["Content-Type":"application/json"]
        default :
            return ["Content-Type":"application/x-www-form-urlencoded"]
        }
    }

Server console show the error message : **the request was rejected because no multipart boundary was found!**

When I used the old version,it works. But now,i use the latest version,it fail.

**Comment by lokizero00** [comment]
Anyone encountering this problem? I still can't upload success! Anyone help!

**Comment by lokizero00** [comment]
@sunshinejr Is this a bug?

**Comment by sunshinejr** [comment]
Hey @lokizero00, sorry for the delay. Do you think you can create an example project that reproduces the issue so I can look? Also can you post here your request/response logs using `NetworkLoggerPlugin(verbose: true)`?

**Comment by Natai** [comment]
> @sunshinejr Is this a bug?

the same to me. how did you solve it?

**Comment by sunshinejr** [comment]
Hey @Natai, I was unable to recreate an example project that would fail to upload the image. If you could help me prepare that project I could take a look and give you more detailed answer.

**Comment by Natai** [comment]
@sunshinejr sorry, I tried again. I forgot add fileName and mimeType, after add them, everything is ok. thanks your replay :)

**Comment by sunshinejr** [comment]
@Natai ah no problem at all, glad you figured it out 🎉
