### ISSUE TITLE
can update cathage file ReactiveSwift to 6.1.0?

### ISSUE THREAD

**Issue by RiuHDuo** [Moya/Moya#1899]
can update cathage file ReactiveSwift to 6.1.0?

**Comment by sunshinejr** [comment]
Hey @RiuHDuo, yeah it should be in the next pre-release (there's already a PR for it #1896)

**Comment by sunshinejr** [comment]
@RiuHDuo I just released version 14.0.0-beta.1 of Moya, can you try that out and see if it helps?
