### ISSUE TITLE
'Moya/RxSwift', '~> 13.0' does not support RxSWift 5.0

### ISSUE THREAD

**Issue by tuyuan2012** [Moya/Moya#1900]
'Moya/RxSwift', '~> 13.0' does not support RxSWift 5.0!
The 'Moya/RxSwift', '14.0.0-alpha.2' requires a higher minimum deployment target (iOS 11) which is too hight! But the minimum deployment target of Our App is iOS 9.0!
Thanks!

**Comment by sunshinejr** [comment]
Hey @tuyuan2012. I'm sorry, but the newest major version of Moya has Alamofire 5 which set its minimum deployment target to iOS 10 (if you're seeing that it needs iOS 11 then it is a bug).

**Comment by tuyuan2012** [comment]
Okey! Thanks
