### ISSUE TITLE
How to implement the mutual authentication (two-way authentication)?

### ISSUE THREAD

**Issue by liuwin7** [Moya/Moya#1902]
I know how to authenticate the certificate from the server, but how about sending the client certificate to my server ? 

These is what I do for the version 13.x. 
⚠️ __This may be a wrong way, but let's take a look__.
I use the plugin `CredentialsPlugin`. 
```swift
let cerPlugin = CredentialsPlugin.init { [unowned self] (target) -> URLCredential? in
    let trust = self.extractIdentity()
    let credential = URLCredential.init(identity: trust.identityRef,
                                        certificates: trust.certArray as? [Any],
                                        persistence: URLCredential.Persistence.forSession)
    return credential
}
```
And it will be passed on the `Request`'s `delegate`,  a `TaskDelegate` in `Alamofire`.
When the `TaskDelegate` receives an authentication challenge whose `protectionSpace.authenticationMethod` is not a `NSURLAuthenticationMethodServerTrust`, it will go [here](https://github.com/Alamofire/Alamofire/blob/4.8.2/Source/TaskDelegate.swift).
```swift
if challenge.previousFailureCount > 0 {
    disposition = .rejectProtectionSpace
} else {
    credential = self.credential ?? session.configuration.urlCredentialStorage?.defaultCredential(for: challenge.protectionSpace)
    if credential != nil {
        disposition = .useCredential
    }
}
```
the `TaskDelegate`'s credential is accidentally treated as the one which will be sent to server used to authentication on server.
This is where I think there is a mistake. The `CredentialsPlugin` is used for HTTP Authentication not for the `NSURLAuthenticationMethodClientCertificate`. 
What a lovely mistake! :)

__UNFORTUNATELY  THE DAYS ARE GONE__. 
On the new version 14.0.0-alpha.2 which depends the new version `"Alamofire", "5.0.0-beta.7"`. [Here the code.](https://github.com/Alamofire/Alamofire/blob/master/Source/SessionDelegate.swift)
```swift
switch challenge.protectionSpace.authenticationMethod {
case NSURLAuthenticationMethodServerTrust:
    evaluation = attemptServerTrustAuthentication(with: challenge)
case NSURLAuthenticationMethodHTTPBasic, NSURLAuthenticationMethodHTTPDigest:
    evaluation = attemptHTTPAuthentication(for: challenge, belongingTo: task)
// case NSURLAuthenticationMethodClientCertificate:
// Alamofire doesn't currently support client certificate validation.
default:
    evaluation = (.performDefaultHandling, nil, nil)
}
```
It will give a `nil` to the handler instead of the credential in the `Session`, which is passed on by `CredentialsPlugin`. :( 
As for this, I have created an [issue](https://github.com/Alamofire/Alamofire/issues/2923) on Alamofire.

What should I do?

**Comment by sunshinejr** [comment]
Hey @liuwin7, thank you for the issue. I'm sorry but I have no knowledge of a workaround at the moment. Pinging @Moya/contributors, maybe someone could help!

**Comment by liuwin7** [comment]
With the pull request [#2993](https://github.com/Alamofire/Alamofire/pull/2993) has been approved, the client certificate authentication has been supported by Alamofire. This means the Moya can also got the ability for it.
So, it's over.

**Comment by sunshinejr** [comment]
@liuwin7 this is _awesome_ - thank you so much for fixing it! 🎉
