### ISSUE TITLE
Support for iOS 7 and OS X 10.9 (update podspec)

### ISSUE THREAD

**Issue by mhuusko5** [Moya/Moya#191]
Currently the podspec is limiting use to iOS 8. But there doesn't seem to be anything in moya which is iOS specific, nor iOS 8 specific. Since Alamofire's requirements are iOS 7 and OS X 10.9 and up, it seems like Moya's should be as well.

**Comment by esttorhe** [comment]
I think the `iOS 7` restriction is more along the lines that `Swift` pods are only supported with `use_frameworks!` flags in `CocoaPods`.

And dynamic frameworks are only available in 8.x and above.

**Comment by ashfurrow** [comment]
That makes sense – OS X support seems pretty easy. iOS 7, though, confuses me a bit. How can Alamofire's podspec support iOS 7 if Swift pods require frameworks, and frameworks work only on iOS 8? Or am I misunderstanding something?

**Comment by ashfurrow** [comment]
Ah, beat me to it @esttorhe  :)

**Comment by esttorhe** [comment]
i think we hit `Comment` at the same time :see_no_evil:

**Comment by esttorhe** [comment]
Alamofire's [podspec](https://github.com/Alamofire/Alamofire/blob/master/Alamofire.podspec) points to `8.0` as you can see

**Comment by mhuusko5** [comment]
Oops, silly me. iOS 8 it is.

**Comment by esttorhe** [comment]
I think supporting 10.9 makes sense though, and should be «trivial» to add.

**Comment by ashfurrow** [comment]
Cool, I've opened up https://github.com/Moya/Moya/issues/192 to do just that.

**Comment by ashfurrow** [comment]
Tricky, since ReactiveCocoa has a minimum OS X deploy target of 10.10. I'm having trouble getting this to work with a subspec having a different OS X deploy target. 

Since no one has requested this, I'm fine with closing this as-is. We have OS X support, which was one of the big parts; I'm on with 10.10.

If anyone wants to re-open and investigate, :tada:

**Comment by petester42** [comment]
Ya the ReactiveCocoa podspec also doesn't reflect the project's settings. In the project it is 10.9 but not in the podspec. 😢
