### ISSUE TITLE
Danger fails on our newest Xcode 11 stack.

### ISSUE THREAD

**Issue by sunshinejr** [Moya/Moya#1917]
I know you probably work on this already @f-meloni, but wanted to create this issue just to track it.

We should probably make it a separate build anyways... In fact the whole CI workflow could use some help but yeah, I don't really have time for even creating an issue about the CI improvements so we might wait with that 😅

**Comment by f-meloni** [comment]
@sunshinejr unfortunately I didn't get a release yet, but I pointed to the Marathon's commit with the fix and I released the 2.0.3, can you please check if it fixes this?

**Comment by Robuske** [comment]
I was looking for something else, but just so you know, he made the release a few hours after you did that
https://github.com/JohnSundell/Marathon/releases/tag/3.3.0

**Comment by f-meloni** [comment]
Will point to that one! thank you :)

**Comment by sunshinejr** [comment]
@f-meloni did an awesome job and fixed everything (Marathon included) to get this to work (see #1921). Closing for now!
