### ISSUE TITLE
swift 2.0

### ISSUE THREAD

**Issue by EZabolotniy** [Moya/Moya#193]
Hi, I have the following Podfile:

```
pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift-2.0'
pod 'RxSwift', :git => 'https://github.com/ReactiveX/RxSwift.git', :branch => 'rxswift-2.0'
pod 'RxCocoa', :git => 'https://github.com/ReactiveX/RxSwift.git', :branch => 'rxswift-2.0'
pod 'Moya/RxSwift', :git => 'https://github.com/Moya/Moya.git', :branch => 'swift-2.0'
```

And when I do pod install, I receive the following error:

[!] Unable to satisfy the following requirements:

- `Alamofire (from `https://github.com/Alamofire/Alamofire.git`, branch `swift-2.0`)` required by `Podfile`
- `Alamofire (~> 1.3.0)` required by `Moya/Core (2.0.0)`

**Comment by ashfurrow** [comment]
Hmm. I know @esttorhe is working on Swift 2 support on https://github.com/Moya/Moya/pull/181 – maybe the Moya/Core subspec isn't being used from the `swift-2` branch? Maybe you need also

```rb
pod 'Moya', :git => 'https://github.com/Moya/Moya.git', :branch => 'swift-2.0'
```

But to be honest, I'm not sure of the Swift 2 support in Moya yet. Ill's if I can take a look today.

**Comment by esttorhe** [comment]
AFC right now but if you point to mits 2.0 branch (see the Demo Podfile in there) you'll be able to use everything sans ReactiveCocoa subspec

--
Esteban Torres
(+506)8813-0934
Twitter: @esttorhe




On Thu, Aug 20, 2015 at 8:22 AM -0700, "Ash Furrow" <notifications@github.com> wrote:












Hmm. I know @esttorhe is working on Swift 2 support on #181 – maybe the Moya/Core subspec isn't being used from the swift-2 branch? Maybe you need also

pod 'Moya', :git => 'https://github.com/Moya/Moya.git', :branch => 'swift-2.0'



But to be honest, I'm not sure of the Swift 2 support in Moya yet. Ill's if I can take a look today.

**Comment by esttorhe** [comment]
*Moya 

--
Esteban Torres
(+506)8813-0934
Twitter: @esttorhe




On Thu, Aug 20, 2015 at 8:22 AM -0700, "Ash Furrow" <notifications@github.com> wrote:












Hmm. I know @esttorhe is working on Swift 2 support on #181 – maybe the Moya/Core subspec isn't being used from the swift-2 branch? Maybe you need also

pod 'Moya', :git => 'https://github.com/Moya/Moya.git', :branch => 'swift-2.0'



But to be honest, I'm not sure of the Swift 2 support in Moya yet. Ill's if I can take a look today.

**Comment by EZabolotniy** [comment]
I change my pod file to:

platform :ios, "8.0"

source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift-2.0'
pod 'RxSwift', :git => 'https://github.com/ReactiveX/RxSwift.git', :branch => 'rxswift-2.0'
pod 'RxCocoa', :git => 'https://github.com/ReactiveX/RxSwift.git', :branch => 'rxswift-2.0’

pod 'Moya/RxSwift', :path => "../"
pod 'Moya/ReactiveCocoa', :path => "../"
pod 'Moya', :path => "../"

and still have the following error:

[!] Unable to satisfy the following requirements:

- `Alamofire (from `https://github.com/Alamofire/Alamofire.git`, branch `swift-2.0`)` required by `Podfile`
- `Alamofire (~> 1.3.0)` required by `Moya/Core (2.0.0)`

[!] Your Podfile has had smart quotes sanitised. To avoid issues in the future, you should not use TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of choice.
Evgeniys-MacBook-Pro:Eventgram evgeniy$ open -e Podfile

**Comment by esttorhe** [comment]
Omw. 
I'll check in my computer in a few 

--
Esteban Torres
(+506)8813-0934
Twitter: @esttorhe




On Thu, Aug 20, 2015 at 8:39 AM -0700, "EZabolotniy" <notifications@github.com> wrote:












I change my pod file to:



platform :ios, "8.0"



source 'https://github.com/CocoaPods/Specs.git'



use_frameworks!



pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift-2.0'

pod 'RxSwift', :git => 'https://github.com/ReactiveX/RxSwift.git', :branch => 'rxswift-2.0'

pod 'RxCocoa', :git => 'https://github.com/ReactiveX/RxSwift.git', :branch => 'rxswift-2.0’



pod 'Moya/RxSwift', :path => "../"

pod 'Moya/ReactiveCocoa', :path => "../"

pod 'Moya', :path => "../"



and still have the following error:



[!] Unable to satisfy the following requirements:



Alamofire (fromhttps://github.com/Alamofire/Alamofire.git`, branch swift-2.0)required byPodfile`

Alamofire (~> 1.3.0) required by Moya/Core (2.0.0)





[!] Your Podfile has had smart quotes sanitised. To avoid issues in the future, you should not use TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of choice.

Evgeniys-MacBook-Pro:Eventgram evgeniy$ open -e Podfile

**Comment by esttorhe** [comment]
You are correct @EZabolotniy.

I forgot that we haven't merged my branch into Moya's `swift-2.0` due to the issue with `ReactiveCocoa`.

You should be able to use `Moya` with `Swift 2` if you change your `Podfile` to this:

```ruby
platform :ios, '8.0'
use_frameworks!

pod 'Moya', :git => 'https://github.com/esttorhe/Moya', :branch => 'swift-2.0'
pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire', :branch => 'swift-2.0'
pod 'RxSwift', :git => 'https://github.com/ReactiveX/RxSwift', :branch => 'rxswift-2.0'
pod 'RxCocoa', :git => 'https://github.com/ReactiveX/RxSwift', :branch => 'rxswift-2.0'
```

With the caveat that you won't be able to use the `ReactiveCocoa` extensions ATM

---

Worth noting; I had to change my implementation; from when I created it to now @kzaher promoted `ReactiveX` to an organization and changed the name of the `Swift 2` branches.

I changed the `Podfile` accordingly and tested locally and `CocoaPods` can satisfy all the requirements; note that you'll have to point `Moya` to my branch for the time being since that `podspec` doesn't specify `Alamofire 1.3` as a dependency and leaves it open; then on the `Podfile` you can lock it to the `Swift 2.0` branch; same goes for the `RxSwift` dependencies

**Comment by esttorhe** [comment]
@ashfurrow; would it be worth to merge my WIP branch into the `swift-2.0`?

I mean; right now that branch doesn't work and mine almost work except for `ReactiveCocoa` (which I'm hoping to clear some time to tackle that once and for all by the end of this week).

That way people can use `Moya` on `Swift 2.0` in a somewhat more «official» way

**Comment by ashfurrow** [comment]
I'm thinking merging it as-is is probably a good idea. It's not like we're merging into `master` or anything :)

**Comment by esttorhe** [comment]
I think its ok to close this issue due to #194
