### ISSUE TITLE
MoyaProvider.RequestClosure is there a way to get the enum that is being called?

### ISSUE THREAD

**Issue by DMCApps** [Moya/Moya#1932]
Hello

I'm attempting to add a middleware step to my requests that attempts to refresh my tokens but I only want it to be done when the request requires a token. I don't see anywhere that I can get the request being made and check if it's a request that requires a token.

e.g.
```swift
// Closure run on each request in order to check the validity of the token
// The token will be refreshed whenever needed.
let requestClosure: MoyaProvider.RequestClosure = { (endpoint: Endpoint, done: @escaping MoyaProvider.RequestResultClosure) in
    
    // Only proceed if the task is AccessTokenAuthorizable and it's authorization type is bearer.
    
    // TODO: How do I get the enum being called to check if it's type is AccessTokenAuthorizable and get the value of that key for this request? 
    // Something like below except .task is not the proper value as I can't call these methods on it.
    let authorizationType: AuthorizationType = (endpoint.task as? AccessTokenAuthorizable)?.authorizationType ?? .none
    guard authorizationType  == .bearer else {
            
        done(.success(try! endpoint.urlRequest()))
        return
    }
    
    // There is no state to be updated. Proceed with the request
    guard authManager.state != nil else {
        done(.success(try! endpoint.urlRequest()))
        return
    }
    
    /// State is available and the request uses the auth token. Attempt to refresh before performing request
    authManager.performAction(freshTokens: { (accessToken, idToken, error) in
        guard error == nil else {
            log.error("Failed to refresh token with Error: \(error!.localizedDescription)")
            done(.failure(MoyaError.underlying(error!, nil)))
            return
        }
        
        done(.success(try! endpoint.urlRequest()))
    })
}
```

**Comment by sunshinejr** [comment]
Hey @DMCApps. I'm afraid it's not possible currently. You might want to see https://github.com/Moya/Moya/issues/1671, which is I believe a similar use-case that you specified.

**Comment by DMCApps** [comment]
@sunshinejr aw that's unfortunate. Is there any reason against passing in the target to that closure? e.g. 

This:
```swift
public typealias RequestClosure = (Endpoint, @escaping RequestResultClosure) -> Void
```
becomes:
```swift
public typealias RequestClosure = (Target, Endpoint, @escaping RequestResultClosure) -> Void
```

Wondering if there is a design decision against that or if the use case is not worth the development? From a quick look at the code base it looks like `requestNormal` calls this closure in `MoyaProvider+Internal` which looks to have the `Target` come in it's method signature.

```swift 
func requestNormal(_ target: Target, callbackQueue: DispatchQueue?, progress: Moya.ProgressBlock?, completion: @escaping Moya.Completion) -> Cancellable {

    ...

    requestClosure(endpoint, performNetworking)

    return cancellableToken
}
```

**Comment by sunshinejr** [comment]
@DMCApps not sure why we didn’t add the parameter before - if you want to create a PR with the change I would gladly review it 👍🏻

**Comment by DMCApps** [comment]
@sunshinejr Alright I'll work on that when I get a chance.

**Comment by sunshinejr** [comment]
@DMCApps ah no let’s keep it open until we get this one resolved. 

And for the contribution guidelines, take a look at [this document](https://github.com/Moya/Moya/blob/master/Contributing.md) - should help! If not, we always have our Danger bot on each PR and you can ask here/on the PR and we will help you as soon as possible 👍🏻

**Comment by amaurydavid** [comment]
> @DMCApps not sure why we didn’t add the parameter before - if you want to create a PR with the change I would gladly review it 👍🏻

I think it's because the target is actually replaced by the Endpoint. Having both of them looks a bit overkill as the second derives from the first. There might be a way to be even better by moving the URLRequest construction from Endpoint to Target, and removing the Endpoint type? From what I see this seems to be the only purpose of the Endpoint type.

**Comment by sunshinejr** [comment]
@amaurydavid yeah I agree it kinda duplicates some properties that `Endpoint` got from the `Target`. On the other hand removing `Endpoint` is a really big change in both the core of Moya and usage and I don't feel comfortable removing it, would need to go through a proposal of some sort. Ideally we would add the information needed for the `requestClosure` (the `Target`), maybe as a property of the `Endpoint`? `Endpoint.underlyingTarget`? What do you think?

**Comment by DMCApps** [comment]
@sunshinejr @amaurydavid That solution would work for the use case I presented. It would also give endpoint access to more than the `Moya.Method` and `Task` since those can be replaced with the `Endpoint.underlyingTarget.method` and `Endpoint.underlyingTarget.task` and give access to any extensions used on `TargetType` as well.
