### ISSUE TITLE
Moya + Codable + UrlParameters

### ISSUE THREAD

**Issue by ucerxxx** [Moya/Moya#1939]
Moya (12.0.1)

Moya can work with Swift Encodable:
```case requestJSONEncodable(Encodable)```

and we have the way to provide url parameters:
```case requestCompositeData(bodyData: Data, urlParameters: [String: Any])```

does it make sense to have Encodable + UrlParameters:
```case requestJSONEncodable(encodable: Encodable, urlParameters: [String: Any]))```

thanks

**Comment by sunshinejr** [comment]
Hey @ucerxxx, yeah it would make sense but we try to limit the `Task` cases to the bare minimum (meaning the most popular use-cases would be having a nice API and the use-cases that are not that popular would still be possible to do). However, there is a PR in the works that might get you the option as well #1936 so you could keep an eye on this one 👍
