### ISSUE TITLE
build failed in swiftui preview using moya with swift manager package

### ISSUE THREAD

**Issue by StephenZhuang** [Moya/Moya#1941]
![image](https://user-images.githubusercontent.com/7381748/67443713-96326f80-f638-11e9-91ac-b6913c2f0a5d.png)
what's the problem with CwlCatchException and testing?

**Comment by sunshinejr** [comment]
Hey @StephenZhuang, what Moya version do you use? We had this problem before but in the latest version of Moya 14-beta it should be resolved.

**Comment by StephenZhuang** [comment]
> Hey @StephenZhuang, what Moya version do you use? We had this problem before but in the latest version of Moya (both 14.0.0-beta.3 and 14.0.0-beta.4) it should be resolved.

13.0.1 how can i use 14.00-beta.4 with swift package manager? update seems not working

**Comment by sunshinejr** [comment]
@StephenZhuang you need to specify an exact version until we release official version 14.

**Comment by StephenZhuang** [comment]
ok i got it. thank you

**Comment by mstudzitsky** [comment]
![Снимок экрана 2019-10-30 в 19 47 08](https://user-images.githubusercontent.com/15685681/67863507-3a8f4700-fb4e-11e9-8f28-a543e461137a.png)
Hi! I have a similar problem. I tried my 14 beta 3, 4, 5.
Xcode 11.1 macOs Catalina 10.15.1
