### ISSUE TITLE
rxSwift rxCocoa 5.0.1 support instead of 5.0.

### ISSUE THREAD

**Issue by yaroyk** [Moya/Moya#1943]
Hello, is where a way to use rxSwift rxCocoa 5.0.1 support instead of 5.0.
5.0.1 removed deprecated UIWebView

**Comment by sunshinejr** [comment]
Hey @yaroyk, yes there should be a way! It should be as simple as updating your dependency:
SPM:
```
swift package update
```

CocoaPods:
```
pod update Moya
```

Carthage:
```
carthage update Moya // --platform iOS --cache-builds or any other option you would like
```

**Comment by yaroyk** [comment]
👍🏻
thank you

**Comment by therohansanap** [comment]
@sunshinejr This does not seem to be working. I am using CocoaPods and my podfile says `pod 'Moya/RxSwift'`. It installs RxSwift ~> 4. Is there something I am doing wrong?

**Comment by sunshinejr** [comment]
@therohansanap this means you have installed Moya 13.* (or lower) - we are using RxSwift 5 for Moya 14, which is not yet out of beta phase as Alamofire is not out yet. You can specify version `14.0.0-beta.5` in your Podfile, but be careful as there are breaking changes in this release.

**Comment by therohansanap** [comment]
@sunshinejr noted! Thank you for prompt response.
