### ISSUE TITLE
URLEncoding for request parameters when using requestCompositeData

### ISSUE THREAD

**Issue by sly07** [Moya/Moya#1946]
Version 12.0.1
I have a situation where I need to include body data as well as url parameters which is why I am using requestCompositeData. When I use requestParameters I am able to set the encoding but I am not able to do the same in requestCompositeData for the url parameters. The same goes for requestCompositeParameters where you can define the bodyEncoding but not the encoding for the urlParameters.

**Comment by amaurydavid** [comment]
That is indeed a limitation when using `requestCompositeData` and `requestCompositeParameters`.
As a workaround you can implement the `MoyaProvider`'s `requestClosure` and override the http request and encode your parameters the way it suits you.

There is a current work on Task in #1936 that could solve these limitations.
