### ISSUE TITLE
Can't build project, [unexpected EOF while looking for matching `'']. How to resolve this?

### ISSUE THREAD

**Issue by matheusmaus** [Moya/Moya#1948]

**Comment by sunshinejr** [comment]
Hey @matheusmaus, from my experience it is usually the sign of a bad cache - try to clear project cache, quit Xcode, clear derived data folder and then open again the project.

**Comment by matheusmaus** [comment]
Hello @sunshinejr , turn out the error was in the "product name" because contained a single quote. So a removed it and everything worked fine.

**Comment by sunshinejr** [comment]
@matheusmaus awesome! thanks for the update :)
