### ISSUE TITLE
How do I get the parameters of the task in the target?

### ISSUE THREAD

**Issue by Onenineninetwo-ee** [Moya/Moya#1949]
Hi！

How do I get the parameters of the task in the target, because my header information needs parameters to encrypt, and find that the parameters are a dictionary, there will be an unordered problem, how do I need to control the parameters I get are consistent with the order in the task ,thank you very much

```swift
public var parameters: [String : Any]? {
  switch self {
  case .loanPage(let status, let start, let length):
    return ["status": status,
            "start": start,
            "length": length]
  default:
    return [:]
  }
}

public var task: Task {
  print(String.init(format: "p0：%p", parameters!)) // new pointer
  return .requestParameters(parameters: self.parameters!, encoding: JSONEncoding.default)
}
    
public var headers: [String : String]? { 
  print(String.init(format: "p1：%p", parameters!)) // new pointer
  return nil
}

let endpoint = {(target: Home) -> Endpoint in
  print(String.init(format: "p：%p", target.parameters!)) // new pointer
  return MoyaProvider.defaultEndpointMapping(for: target).adding(newHTTPHeaderFields: genHeaderFields( target.parameters))
}
```
As above，
**If I get parameters from the target, then an unordered problem will occur.**
I tried passing the pointer, but the paramters are immutable, how can I fix it?

**Comment by amaurydavid** [comment]
As you are using `JSONEncoding`, did you try instantiating it with the `sortedKeys` writing options?
You could also override the provider's `requestClosure` to reorder the request's `queryItems` the way that suits you.

**Comment by Onenineninetwo-ee** [comment]
@amaurydavid 
Hello, we are currently using JSONEncoding, sortedKeys is only valid on iOS 11+, due to the limitations of the conditions I am not sure if there will be the same problem below iOS 11, thank you for your reply.

**Comment by Onenineninetwo-ee** [comment]
@amaurydavid 
I found that to solve this problem completely, I can only sort by encryption, sort when requested, or use```Encodable```, thank you for your reply.

**Comment by Onenineninetwo-ee** [comment]
I fix by extend ```ParameterEncoding```.

**Comment by philosopherdog** [comment]
> I fix by extend `ParameterEncoding`.

Be kind. Put down your solution for others.
