### ISSUE TITLE
xcode 11.2.1 swift 5.1 carthage error

### ISSUE THREAD

**Issue by xutengfei** [Moya/Moya#1951]
Hi , we  updated xcode to version 11.2.1 with swift version 5.1 recently . 
Both of moya version13 and version14 gave errors likes this 

```swift
carthage bootstrap Moya --platform iOS  --no-use-binaries 
*** Checking out Moya at "14.0.0-beta.5"
*** Checking out ReactiveSwift at "5.0.1"
*** Checking out Alamofire at "4.9.1"
*** Checking out RxSwift at "4.5.0"
*** xcodebuild output can be found in /var/folders/86/_5vgd1fj5nscjbtrzyrzx0sw0000gq/T/carthage-xcodebuild.JVRVlf.log
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
*** Building scheme "Result-iOS" in Result.xcodeproj
*** Building scheme "ReactiveSwift-iOS" in ReactiveSwift.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/eric/workspace/n2boost/jugg5/Carthage/Checkouts/ReactiveSwift/ReactiveSwift.xcworkspace -scheme ReactiveSwift-iOS -configuration Release -derivedDataPath /Users/eric/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2.1_11B53/ReactiveSwift/5.0.1 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/86/_5vgd1fj5nscjbtrzyrzx0sw0000gq/T/ReactiveSwift SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/eric/workspace/n2boost/jugg5/Carthage/Checkouts/ReactiveSwift)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/86/_5vgd1fj5nscjbtrzyrzx0sw0000gq/T/carthage-xcodebuild.JVRVlf.log
```

**Comment by amaurydavid** [comment]
Can you provide the content of the build log?

**Comment by xutengfei** [comment]
> Can you provide the content of the build log?

CompileSwift normal armv7 (in target 'ReactiveSwift-iOS' from project 'ReactiveSwift')
    cd /Users/eric/workspace/n2boost/jugg5/Carthage/Checkouts/ReactiveSwift
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -emit-bc /Users/eric/workspace/n2boost/jugg5/Carthage/Checkouts/ReactiveSwift/Sources/Signal.swift /Users/eric/workspace/n2boost/jugg5/Carthage/Checkouts/ReactiveSwift/Sources/Optional.swift /Users/eric/workspace/n2boost/jugg5/Carthage/Checkouts/ReactiveSwift/Sources/Disposable.swift /Users/eric/workspace/n2boost/jugg5/Carthage/Checkouts/ReactiveSwift/Sources/SignalProducer.swift /Users/eric/workspace/n2boost/jugg5/Carthage/Checkouts/ReactiveSwift/Sources/ValidatingProperty.swift /Users/eric/workspace/n2boost/jugg5/Carthage/Checkouts/ReactiveSwift/Sources/Deprecations+Removals.swift /Users/eric/workspace/n2boost/jugg5/Carthage/Checkouts/ReactiveSwift/Sources/Observer.swift /Users/eric/workspace/n2boost/jugg5/Carthage/Checkouts/ReactiveSwift/Sources/Reactive.swift /Users/eric/workspace/n2boost/jugg5/Carthage/Checkouts/ReactiveSwift/Sources/Flatten.swift /Users/eric/workspace/n2boost/jugg5/Carthage/Checkouts/ReactiveSwift/Sources/UninhabitedTypeGuards.swift /Users/eric/workspace/n2boost/jugg5/Carthage/Checkouts/ReactiveSwift/Sources/Lifetime.swift /Users/eric/workspace/n2boost/jugg5/Carthage/Checkouts/ReactiveSwift/Sources/Property.swift /Users/eric/workspace/n2boost/jugg5/Carthage/Checkouts/ReactiveSwift/Sources/FoundationExtensions.swift /Users/eric/workspace/n2boost/jugg5/Carthage/Checkouts/ReactiveSwift/Sources/ResultExtensions.swift /Users/eric/workspace/n2boost/jugg5/Carthage/Checkouts/ReactiveSwift/Sources/Event.swift /Users/eric/workspace/n2boost/jugg5/Carthage/Checkouts/ReactiveSwift/Sources/EventLogger.swift /Users/eric/workspace/n2boost/jugg5/Carthage/Checkouts/ReactiveSwift/Sources/Atomic.swift /Users/eric/workspace/n2boost/jugg5/Carthage/Checkouts/ReactiveSwift/Sources/Scheduler.swift /Users/eric/workspace/n2boost/jugg5/Carthage/Checkouts/ReactiveSwift/Sources/Bag.swift /Users/eric/workspace/n2boost/jugg5/Carthage/Checkouts/ReactiveSwift/Sources/Action.swift /Users/eric/workspace/n2boost/jugg5/Carthage/Checkouts/ReactiveSwift/Sources/UnidirectionalBinding.swift -supplementary-output-file-map /var/folders/86/_5vgd1fj5nscjbtrzyrzx0sw0000gq/T/supplementaryOutputs-8f7408 -target armv7-apple-ios8.0 -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk -I /Users/eric/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2.1_11B53/ReactiveSwift/5.0.1/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/BuildProductsPath/Release-iphoneos -F /Users/eric/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2.1_11B53/ReactiveSwift/5.0.1/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/BuildProductsPath/Release-iphoneos -application-extension -g -import-underlying-module -module-cache-path /Users/eric/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2.1_11B53/ReactiveSwift/5.0.1/ModuleCache.noindex -warnings-as-errors -swift-version 4 -enforce-exclusivity=checked -O -serialize-debugging-options -Xcc -working-directory -Xcc /Users/eric/workspace/n2boost/jugg5/Carthage/Checkouts/ReactiveSwift -Xcc -I/Users/eric/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2.1_11B53/ReactiveSwift/5.0.1/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/eric/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2.1_11B53/ReactiveSwift/5.0.1/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/ReactiveSwift-generated-files.hmap -Xcc -I/Users/eric/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2.1_11B53/ReactiveSwift/5.0.1/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/ReactiveSwift-own-target-headers.hmap -Xcc -I/Users/eric/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2.1_11B53/ReactiveSwift/5.0.1/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/ReactiveSwift-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/eric/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2.1_11B53/ReactiveSwift/5.0.1/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/eric/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2.1_11B53/ReactiveSwift/5.0.1/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/ReactiveSwift-project-headers.hmap -Xcc -I/Users/eric/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2.1_11B53/ReactiveSwift/5.0.1/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/BuildProductsPath/Release-iphoneos/include -Xcc -I/Users/eric/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2.1_11B53/ReactiveSwift/5.0.1/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/UninstalledProducts/include -Xcc -I/Users/eric/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2.1_11B53/ReactiveSwift/5.0.1/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/DerivedSources-normal/armv7 -Xcc -I/Users/eric/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2.1_11B53/ReactiveSwift/5.0.1/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/DerivedSources/armv7 -Xcc -I/Users/eric/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2.1_11B53/ReactiveSwift/5.0.1/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/DerivedSources -Xcc -DNDEBUG=1 -Xcc -ivfsoverlay -Xcc /Users/eric/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2.1_11B53/ReactiveSwift/5.0.1/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/unextended-module-overlay.yaml -module-name ReactiveSwift -num-threads 8 -o /Users/eric/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2.1_11B53/ReactiveSwift/5.0.1/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/Objects-normal/armv7/Signal.bc -o /Users/eric/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2.1_11B53/ReactiveSwift/5.0.1/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/Objects-normal/armv7/Optional.bc -o /Users/eric/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2.1_11B53/ReactiveSwift/5.0.1/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/Objects-normal/armv7/Disposable.bc -o /Users/eric/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2.1_11B53/ReactiveSwift/5.0.1/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/Objects-normal/armv7/SignalProducer.bc -o /Users/eric/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2.1_11B53/ReactiveSwift/5.0.1/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/Objects-normal/armv7/ValidatingProperty.bc -o /Users/eric/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2.1_11B53/ReactiveSwift/5.0.1/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/Objects-normal/armv7/Deprecations+Removals.bc -o /Users/eric/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2.1_11B53/ReactiveSwift/5.0.1/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/Objects-normal/armv7/Observer.bc -o /Users/eric/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2.1_11B53/ReactiveSwift/5.0.1/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/Objects-normal/armv7/Reactive.bc -o /Users/eric/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2.1_11B53/ReactiveSwift/5.0.1/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/Objects-normal/armv7/Flatten.bc -o /Users/eric/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2.1_11B53/ReactiveSwift/5.0.1/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/Objects-normal/armv7/UninhabitedTypeGuards.bc -o /Users/eric/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2.1_11B53/ReactiveSwift/5.0.1/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/Objects-normal/armv7/Lifetime.bc -o /Users/eric/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2.1_11B53/ReactiveSwift/5.0.1/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/Objects-normal/armv7/Property.bc -o /Users/eric/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2.1_11B53/ReactiveSwift/5.0.1/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/Objects-normal/armv7/FoundationExtensions.bc -o /Users/eric/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2.1_11B53/ReactiveSwift/5.0.1/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/Objects-normal/armv7/ResultExtensions.bc -o /Users/eric/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2.1_11B53/ReactiveSwift/5.0.1/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/Objects-normal/armv7/Event.bc -o /Users/eric/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2.1_11B53/ReactiveSwift/5.0.1/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/Objects-normal/armv7/EventLogger.bc -o /Users/eric/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2.1_11B53/ReactiveSwift/5.0.1/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/Objects-normal/armv7/Atomic.bc -o /Users/eric/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2.1_11B53/ReactiveSwift/5.0.1/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/Objects-normal/armv7/Scheduler.bc -o /Users/eric/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2.1_11B53/ReactiveSwift/5.0.1/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/Objects-normal/armv7/Bag.bc -o /Users/eric/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2.1_11B53/ReactiveSwift/5.0.1/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/Objects-normal/armv7/Action.bc -o /Users/eric/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2.1_11B53/ReactiveSwift/5.0.1/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveSwift-iOS/IntermediateBuildFilesPath/ReactiveSwift.build/Release-iphoneos/ReactiveSwift-iOS.build/Objects-normal/armv7/UnidirectionalBinding.bc
/Users/eric/workspace/n2boost/jugg5/Carthage/Checkouts/ReactiveSwift/Sources/Signal.swift:1852:71: error: will never be executed
                                lifetime += action(index, strategy) { observer.send($0.map { _ in fatalError() }) }
                                                                                                  ^
/Users/eric/workspace/n2boost/jugg5/Carthage/Checkouts/ReactiveSwift/Sources/Signal.swift:1852:64: note: '_' is uninhabited, so this function body can never be executed
                                lifetime += action(index, strategy) { observer.send($0.map { _ in fatalError() }) }
                                                                                           ^

** ARCHIVE FAILED **


The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
	CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler
	CompileSwift normal armv7
(4 failures)

**Comment by xutengfei** [comment]
> Can you provide the content of the build log?

There's one thousand lines of logs. I just paste last 100 lines . I can email you all the logs if you need.

**Comment by xutengfei** [comment]
> Can you provide the content of the build log?

/Users/eric/workspace/n2boost/jugg5/Carthage/Checkouts/Moya/Sources/Moya/Moya+Alamofire.swift:29:26: error: value of type 'TaskDelegate' has no member 'sessionConfiguration'
        return delegate?.sessionConfiguration.httpAdditionalHeaders as? [String: String] ?? [:]
               ~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~
/Users/eric/workspace/n2boost/jugg5/Carthage/Checkouts/Moya/Sources/Moya/Moya+Alamofire.swift:29:24: error: cannot use optional chaining on non-optional value of type 'TaskDelegate'
        return delegate?.sessionConfiguration.httpAdditionalHeaders as? [String: String] ?? [:]
               ~~~~~~~~^
                       
/Users/eric/workspace/n2boost/jugg5/Carthage/Checkouts/Moya/Sources/Moya/Moya+Alamofire.swift:70:24: error: value of type 'Request' has no member 'cURLDescription'
        return request.cURLDescription()
               ~~~~~~~ ^~~~~~~~~~~~~~~
/Users/eric/workspace/n2boost/jugg5/Carthage/Checkouts/Moya/Sources/Moya/MoyaProvider+Defaults.swift:30:23: error: value of type 'URLSessionConfiguration' has no member 'headers'
        configuration.headers = .default
        ~~~~~~~~~~~~~ ^~~~~~~
/Users/eric/workspace/n2boost/jugg5/Carthage/Checkouts/Moya/Sources/Moya/MoyaProvider+Defaults.swift:30:34: error: type 'Any' has no member 'default'
        configuration.headers = .default
                                ~^~~~~~~
/Users/eric/workspace/n2boost/jugg5/Carthage/Checkouts/Moya/Sources/Moya/MoyaProvider+Internal.swift:99:19: error: pattern cannot match values of type 'Task'
            case .downloadDestination(let destination), .downloadParameters(_, _, let destination):
                 ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/eric/workspace/n2boost/jugg5/Carthage/Checkouts/Moya/Sources/Moya/MoyaProvider+Internal.swift:99:58: error: pattern cannot match values of type 'Task'
            case .downloadDestination(let destination), .downloadParameters(_, _, let destination):
                                                        ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/eric/workspace/n2boost/jugg5/Carthage/Checkouts/Moya/Sources/Moya/MoyaProvider+Internal.swift:269:83: error: cannot convert value of type '(DispatchQueue, @escaping DownloadRequest.ProgressHandler) -> DownloadRequest' (aka '(DispatchQueue, @escaping (Progress) -> ()) -> DownloadRequest') to expected argument type 'Progress?'
                    progressCompletion(ProgressResponse(progress: downloadRequest.downloadProgress, response: value))
                                                                  ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
/Users/eric/workspace/n2boost/jugg5/Carthage/Checkouts/Moya/Sources/Moya/MoyaProvider+Internal.swift:273:79: error: cannot convert value of type '(DispatchQueue, @escaping DataRequest.ProgressHandler) -> DataRequest' (aka '(DispatchQueue, @escaping (Progress) -> ()) -> DataRequest') to expected argument type 'Progress?'
                    progressCompletion(ProgressResponse(progress: dataRequest.downloadProgress, response: value))
                                                                  ~~~~~~~~~~~~^~~~~~~~~~~~~~~~

** ARCHIVE FAILED **


The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
	CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler
	CompileSwift normal armv7
(4 failures)

**Comment by ARGAMX** [comment]
I get the same error. 
Any progress with this problem? 
Can't use Moya in project, very sad.

**Comment by jcabreram** [comment]
Same thing here. 

It seems to be breaking at the point of building ReactiveSwift. Carthage is checking out version 5.0.1 when the latest is 6.0.1 which has Swift 5.1 support: https://github.com/ReactiveCocoa/ReactiveSwift/releases

I also wanted to add that Xcode 11.2.1 uses Swift 5.1.2

**Comment by jcabreram** [comment]
After more playing around with it, seems it works fine if using Moya 14.0.0-beta.5 as such in your Cartfile:

> github "Moya/Moya" "14.0.0-beta.5"

I don't know why it didn't work for you @xutengfei

**Comment by amaurydavid** [comment]
It also works for me: 
Cartfile: `github "Moya/Moya" "14.0.0-beta.5"`
```carthage bootstrap Moya --platform iOS  --no-use-binaries
*** Checking out Moya at "14.0.0-beta.5"
*** Checking out RxSwift at "5.0.1"
*** Checking out ReactiveSwift at "6.1.0"
*** Checking out Alamofire at "5.0.0-rc.3"```

Your error seems to be due to Carthage not using the correct dependencies versions.

**Comment by tomoki69386** [comment]
I am in the same situation.

Did you solve?
If so, please teach me how

**Comment by sunshinejr** [comment]
@tomoki69386 please copy/paste your Cartfile.resolved file and Carthage logs when you do `carthage bootstrap/update`

**Comment by xutengfei** [comment]
> I am in the same situation.
> 
> Did you solve?
> If so, please teach me how

no. I just revert xcode to 10.2.

**Comment by ostap0207** [comment]
We still have the same problem.

>After more playing around with it, seems it works fine if using Moya 14.0.0-beta.5 as such in your Cartfile:

> github "Moya/Moya" "14.0.0-beta.5"

How is using `beta` version is an acceptable solution here?

**Comment by amaurydavid** [comment]
> How is using `beta` version is an acceptable solution here?
It's not a solution, it's the version with which OP had problems.

**Comment by ostap0207** [comment]
I see, my bad.

**Comment by shivanid95** [comment]
Having the same issue
