### ISSUE TITLE
我现在往header添加 post请求参数 和实际发送的参数顺序不一致

### ISSUE THREAD

**Issue by ZeKunLi** [Moya/Moya#1953]

**Comment by ZeKunLi** [comment]
var signature = ""
    //        md5（md5(Y-m-d H:i  拼接 &.82Wjs]~ling웃"卐dong☠:%') 拼接 参数key 拼接 json_encode(参数value)）
            switch task {
            case let .requestParameters(parameters, _):
                print("------")
                    
                let dateformatter = DateFormatter()

                dateformatter.dateFormat = "YYYY-MM-dd HH:mm"// 自定义时间格式

                let time = dateformatter.string(from: Date())

                let format = "\(time)\(salt)"
                
                print(ZHMD5Tool.md5(forLower32Bate: format) ?? 0)

                print(format.md5)
                var parametersFormat = format.md5
                print(parameters)
                
                let reverseds = parameters.reversed()
                
                if (parameters.keys.count != 0) {
                    for dic in reverseds {
                        parametersFormat.append("\(dic.key)\(dic.value)")
                    }
                } else {
                    parametersFormat.append(salt)
                }

                print(parametersFormat.md5)
                signature = parametersFormat.md5
                print("------")
            default:
                print("haha")
            }
    
    let additionalParameters = [
    "Accept":"application/x.app.v1+json",
    "lingdong-app-platform":"2",
    "lingdong-app-software-versioning":UIDevice.current.systemVersion,
    "lingdong-app-manufacturers":"Apple",
    "lingdong-app-os-ver":Bundle.main.object(forInfoDictionaryKey:"CFBundleShortVersionString") as! String,
    "lingdong-app-imei":"(\(String(describing: UIDevice.current.identifierForVendor)))",
    "lingdong-app-channel":"App Store",
    "lingdong-app-devicename":deviceName(),
    "signature":signature,
    ]

**Comment by pedrovereza** [comment]
_对不起，我不会说中文_

What I got from translating the question:

```
I am now adding post request parameters to the header 
and the order of the parameters actually sent is inconsistent.
```

 If that's the case, this is sadly how `Dictionary` works

> The order of key-value pairs in a dictionary is stable between mutations but is otherwise unpredictable. If you need an ordered collection of key-value pairs and don’t need the fast key lookup that Dictionary provides, see the KeyValuePairs type for an alternative.

https://developer.apple.com/documentation/swift/dictionary

**Comment by ZeKunLi** [comment]
// Swift 拼接请求 URL
    let path = request.url!.absoluteString
    let parameter = String(data: request.httpBody!, encoding: String.Encoding.utf8) ?? ""
    let url = path + "?" + parameter
    
    // 遍历参数 URL
    let urlComponents = NSURLComponents(string: url)
    if let queryItems = urlComponents?.queryItems {
        for item in queryItems {
            parametersFormat.append("\(item.name)\(item.value!)")
            print(item.name)
            print(item.value as Any)

        }
    }

I completed in authorization plug-in to add token Hash encryption
