### ISSUE TITLE
How to implement break point continuation？

### ISSUE THREAD

**Issue by ZWBNice** [Moya/Moya#1954]

**Comment by ZWBNice** [comment]
i want to resume the request how to implement? thanks

**Comment by amaurydavid** [comment]
Would you care to elaborate the issue ?
If you are talking of using `cancellable.cancel()`, I don't think you can relaunch it. You'll have to call the `request()` function to get a new cancellable.

**Comment by sunshinejr** [comment]
just to add - currently there is no suspend/resume functionality in Moya, but it is in Alamofire, so maybe we could try implementing it in the future

**Comment by ZWBNice** [comment]
Yes .thanks
