### ISSUE TITLE
How to handle MoyaError  with Result Framework with Swift 5?

### ISSUE THREAD

**Issue by JolChrSA** [Moya/Moya#1959]
Hi there,

I'm using Moya 13.0.1 with swift 5 , and Moya remove Result Framework because it's in built in Swift 5 , so the issue is that in older version of Moya like 12.0.1 when Status code is 400 then it automatically goes to Failure state , but right now with the new version of Moya it goes to Success state . 

This is happened in  Older Version of Moya(12.0.1)
po result
▿ .failure(underlying(Alamofire.AFError.responseValidationFailed(reason: Alamofire.AFError.ResponseValidationFailureReason.unacceptableStatusCode(code: 400)), Optional(Status Code: 400, Data Length: 25)))
  ▿ failure : MoyaError
    ▿ underlying : 2 elements
      ▿ .0 : AFError
        ▿ responseValidationFailed : 1 element
          ▿ reason : ResponseValidationFailureReason
            ▿ unacceptableStatusCode : 1 element
              - code : 400
      ▿ .1 : Optional<Response>
        ▿ some : Status Code: 400, Data Length: 25

This is happened in  Newer Version of Moya(13.0.1)

po result
▿ Result<Response, MoyaError>
  ▿ success : Status Code: 400, Data Length: 25

And other issue is that How to handle Moya error because thay remove error variable from Moya(13.0.1) 

![Screenshot 2019-11-19 at 8 36 41 AM](https://user-images.githubusercontent.com/55090132/69113006-c3433800-0aa7-11ea-93a3-d3d4bfa4168e.png)

and don't know how to use mapError , and FlatmapError 

![Screenshot 2019-11-19 at 8 38 34 AM](https://user-images.githubusercontent.com/55090132/69113083-000f2f00-0aa8-11ea-848e-307f15e3a331.png)

When i am use this function it never come in to the body .

so , please help me that how to handle moya error with this new "mapError" or "flatMapError" and this is bug from moya that Status code like 400 goes to Success case .

**Comment by amaurydavid** [comment]
There seems to be a misunderstanding: the `Result` framework have been replaced by the built-in `Result` in Moya 14, not in Moya 13.

To get the underlying error with the built-in `Result` you case to extract it with a `case let` statement:
```
switch result {
case let .failure(moyaError):
case let .success(response):
}
```

```if case let .failure(moyaError) = result { } ```

About the `mapError` and `flatMapError` I suggest to report to the Apple's doc. Basically `map` and `flatMap` are used to transform the success value, `mapError` and `flatMapError` are used to transform the failure value.

Finally, in Moya 13 the deprecated property `validate ` of `TargetType` has been removed in favor of `validationType`. Maybe your issue with the error 400 is from there? Can you show us your implementation of `TargetType`?
