### ISSUE TITLE
Access to target in endpoint resolver?

### ISSUE THREAD

**Issue by mhuusko5** [Moya/Moya#196]
I'm doing request signing in the endpoint resolver, but it's conditional based on target. At the moment the target is only accessible in the endpoint closure.

**Comment by ashfurrow** [comment]
Hmm tricky. Let me take a look.

**Comment by mhuusko5** [comment]
`request()` currently..
```obj-c
let endpoint = self.endpoint(token)
let request = endpointResolver(endpoint: endpoint)
let stubBehavior = self.stubBehavior(token)
```

... perhaps it could go... 

```obj-c
let endpoint = self.endpoint(token)
let request = endpointResolver(token, endpoint: endpoint)
let stubBehavior = self.stubBehavior(token)
```

**Comment by ashfurrow** [comment]
Maybe, but I feel like that would break the clear chain from target -> endpoint -> request. 

Could you provide more details about the nature of the request signing? Is this something that could be accomplished with HTTP headers alone? There are some details [here](https://github.com/Moya/Moya/blob/master/docs/Endpoints.md#from-target-to-endpoint-) on how that could be accomplished.

**Comment by mhuusko5** [comment]
Yes, definitely gleaned the significance of the pattern/chain vs. this just being an error. Don't want to change it unless necessary.

Unfortunately I'm not sure how to work around it in this case. In the the endpointClosure I'm adding the appropriate headers for my auth flow. That's for all targets.

But for some targets I need to HMAC sign the url requests, which is based off of properties of the url request, so it needs to go in the endpointResolver.

**Comment by ashfurrow** [comment]
Hmm, I tried to make the `Endpoint` an abstraction for URL requests with [all of these properties](https://github.com/Moya/Moya/blob/fa071c26244e5e2aff8ee98b42ac7ccb3cc4e60c/Moya/Endpoint.swift#L22-L27). I didn't anticipate a need to access the request itself. 

It could also be possible to switch based on the endpoint's URL in the resolver. 

```swift
{ (endpoint: Endpoint<ArtsyAPI>) -> (NSURLRequest) in
    let request: NSMutableURLRequest = endpoint.urlRequest.mutableCopy() as NSMutableURLRequest
    switch endpoint.url.absoluteString {
    case let url where url.hasPrefix("http://theRequestThatNeedsAuthentication"):
        return /* signed request */
    }
    return request
}
```

It's a bit janky, but would that work?

**Comment by mhuusko5** [comment]
It is janky, but it'll do for now. Anyway, I guess just see if anybody else runs into a similar issue, and if so maybe this is worth revisiting.
Thanks!

**Comment by ashfurrow** [comment]
Definitely something to keep in mind!
