### ISSUE TITLE
 carthage update --platform iOS --no-use-binaries failed

### ISSUE THREAD

**Issue by williamhqs** [Moya/Moya#1962]
I'd like  to update **moya** to version **13.0** to support Swift 5.0, but I can't update it by carthage. The error is:
Please wrap code blocks in backticks, like so:

```swift
github "Moya/Moya" ~> 13.0
```

```
*** Building scheme "LlamaKit-iOS" in LlamaKit.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/william/B/xxx/Carthage/Checkouts/LlamaKit/LlamaKit.xcodeproj -scheme LlamaKit-iOS -configuration Release -derivedDataPath /Users/william/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2.1_11B500/LlamaKit/v0.6.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/8w/54_h6qts1xlf8tz7h3nzhn380000gn/T/LlamaKit SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/william/B/xxx/Carthage/Checkouts/LlamaKit)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/8w/54_h6qts1xlf8tz7h3nzhn380000gn/T/carthage-xcodebuild.lOTvSt.log
```

Any help please?

**Comment by amaurydavid** [comment]
The error states the failure happened build LlamaKit-iOS, is it really linked to Moya ?
Note that LlamaKit is not updated since 5 years and have been replaced by Result (that may be the cause of the your build failure with xcode 11.2.1), which is a dependency of Moya 13 (removed in Moya 14 in favor of the built-in Result)

**Comment by williamhqs** [comment]
Yes, it linked to Moya. If I removed Moay, the error is gone.  From the documentation, seems Moya latest version is 13.0.0, 

```
Swift | Moya | RxMoya | ReactiveMoya
-- | -- | -- | --
5.X | >= 13.0.0 | >= 13.0.0 | >= 13.0.0
4.X | 9.0.0 - 12.0.1 | 10.0.0 - 12.0.1 | 9.0.0 - 12.0.1
3.X | 8.0.0 - 8.0.5 | 8.0.0 - 8.0.5 | 8.0.0 - 8.0.5
2.3 | 7.0.2 - 7.0.4 | 7.0.2 - 7.0.4 | 7.0.2 - 7.0.4
2.2 | <= 7.0.1 | <= 7.0.1 | <= 7.0.1
```
If I used `github "Moya/Moya" ~> 14.0` then seems not avaliable. Which version should be used?

**Comment by amaurydavid** [comment]
Moya 14 is in beta: https://github.com/Moya/Moya/releases/tag/14.0.0-beta.5
In the cartfile: `github "Moya/Moya" "14.0.0-beta.5" `

**Comment by williamhqs** [comment]
It works, thanks!
