### ISSUE TITLE
Custom plugin didReceive is not work

### ISSUE THREAD

**Issue by lforme** [Moya/Moya#1963]
```swift
public final class LoadingPlugin: PluginType {
    
    public func willSend(_ request: RequestType, target: TargetType) {
        
        DispatchQueue.main.async {
            UIApplication.shared.isNetworkActivityIndicatorVisible = true
        }
    }
    
    public func didReceive(_ result: Result<Moya.Response, MoyaError>, target: TargetType) {
        DispatchQueue.main.async {
            UIApplication.shared.isNetworkActivityIndicatorVisible = false
        }   
}

let provider = MoyaProvider<AuthenticationInterface>(plugins: [LoadingPlugin()])
provider.request(.updateLoginPassword(password: "password")) { (_) in
}

```
Only the will send method is executed， didReceive is not work.
But moya's NetworkLoggerPlugin is working fine. Too confused me.

moya version 13.0.1
CocoaPods version 1.8.4

**Comment by amaurydavid** [comment]
It must be because you didn't `import Result`, resulting in the built-in `Result` being used while the other one being expected.

**Comment by lforme** [comment]
> It must be because you didn't `import Result`, resulting in the built-in `Result` being used while the other one being expected.

It works for me， 😺😺 Thanks

**Comment by MrRogerHuang** [comment]
> It must be because you didn't `import Result`, resulting in the built-in `Result` being used while the other one being expected.

However, for Moya 14.0.0-beta.5, it must use the built-in `Result`. Otherwise, didRecive does not work :)

**Comment by perfectChao** [comment]
> It must be because you didn't `import Result`, resulting in the built-in `Result` being used while the other one being expected.

thank you

**Comment by JxJPu9bD** [comment]
but in moya 15.0 remove Result, with swift 5.5 xcode 13.2.1, it failed again.
