### ISSUE TITLE
Moya_Logger: [01/12/2019 11:25:49] Response: Received empty network response

### ISSUE THREAD

**Issue by asasdasasd** [Moya/Moya#1967]
what's this mean?
same url same request method , postman get response, but moya show this log, I don't know why

**Comment by amaurydavid** [comment]
Before Moya 14 the logger's behavior was to log `Received empty network response for <target>` if the request resulted with an error, regardless of the error. That means this would be logged for a connection error like a timeout, but also for a validation error (checking the http code). In the first case logging an empty response could make sense, but in the second case It could not as the API may have returned some data with the http error.
In Moya 14.0.0-beta.1 the logger have been reworked and this behavior corrected.

**Comment by asasdasasd** [comment]
all message should be shown no matter which type error
I receive this response regardless of  online or offline, even change request method, how can I log  more valuable message

**Comment by amaurydavid** [comment]
You have multiple options:
- Update to Moya 14 beta 1 or later to include the new logger.
- Stay on your version of Moya and copy/paste the new logger into your project and replace your actual logger by the new one in the plugins list.
- Stay on your version of Moya and create your own plugin that will logs event according to your needs.

**Comment by asasdasasd** [comment]
thank you, I'll try it
