### ISSUE TITLE
Upgrade 14.0.0-beta.6 and request crash

### ISSUE THREAD

**Issue by lczalh** [Moya/Moya#1971]

**Comment by lczalh** [comment]
static let cz_provider = MoyaProvider<MultiTarget>(endpointClosure: endpointMapping,
                                                        requestClosure: timeoutClosure,
                                                        plugins: [RequestHudPlugin, RequestAlertPlugin()])
cz_provider.request(MultiTarget(target), callbackQueue: callbackQueue, progress: progress) { (result) in}  This line collapses, and the console has no typos，14.0.0-beta.5 No problem

**Comment by LucianoPAlmeida** [comment]
Hey @lczalh 
Can you please provide more on the crash log, the way you installing Moya, which version of Xcode?  ... so we can better understand what is happening :))

**Comment by lczalh** [comment]
![717A6D6C-2A55-4D84-A49C-2F6D7F301C9A](https://user-images.githubusercontent.com/29446825/70488456-bc9e6280-1b33-11ea-89e9-88e9c7ff6214.png)
Xcode Version 11.2.1

**Comment by LucianoPAlmeida** [comment]
Installing with swift package manager? 
Seems like the same crash reporter in #1958

**Comment by lczalh** [comment]
I use cocoapods,  doesn't crash when using 14.0.0-beta.5

**Comment by LucianoPAlmeida** [comment]
This might seems like an obvious question and maybe you already have done that, but have you tried a clean (clear derived data folder) build with the new version? 
If you already did that and still have the issues, we have to investigate that in more detail :))

**Comment by LucianoPAlmeida** [comment]
Hey @lczalh 
Any updates on this? Did you make it work? if not I can try reproduce the issue get on an investigation :))

**Comment by lczalh** [comment]
Sorry, I'm in a hurry. It's back to 14.0.0-beta.5

**Comment by AYastrebov** [comment]
The same for me, crashes

**Comment by amaurydavid** [comment]
I've just tried creating a dummy project and perform a request with beta6 and it didn't crash. Could you guys provide context about those crashes? Xcode version, parameters used in the `request` call, etc.
Anything will be helpful at this point. The best would be a sample project which replicates the crash.

**Comment by AYastrebov** [comment]
Ok, i've got some free time today and tried to reproduce this strange issue. Updated to latest beta release, but couldn't get any issues. So I think this issue can be closed for now.

**Comment by yourshinsuke** [comment]
```
my_name/Carthage/Checkouts/Moya/Sources/RxMoya/MoyaProvider+Rx.swift:24:29: error: type 'Result<Response, Error>' has no member 'error'
                    single(.error(error))
                           ~^~~~~~~~~~~~
```

Xcode version 12
