### ISSUE TITLE
How to make a request with dynamic url with query params something like this : http://xyz.com/myapp-api/getChapterEvents/{param1}/{param2}}

### ISSUE THREAD

**Issue by Sanket911** [Moya/Moya#1974]

**Comment by Sanket911** [comment]
I have the url something just like this:

http://xyz.com/myapp-api/getChapterEvents/{param1}/{param2}}

**I tried passing param1 and param 2 in Task as request Parameters But did not work and response with error code is 404:**

case .events(let p1, let p2):
                   var params: [String : String] = [:]
                   params["param1"] = p1
                   params["param2"] = p2
    return .requestParameters(parameters: params, encoding: URLEncoding.default)

public var path: String {
    switch self {
    case .events: return "/getChapterEvents"
    }
  }
Kindly suggest how to such send request.

**Comment by amaurydavid** [comment]
Hello :)
The simplest solution is to directly include it in the `path property`:
```
public var path: String {
switch self {
case let .events(p1, p2): return "/getChapterEvents/\(p1)/\(p2)"
}
}
```

Another solution would be to put the 2 parameters a parameters of the Task, and provide a custom encoding that puts those parameters in your url's path instead of the query.

**Comment by Sanket911** [comment]
Thank you @amaurydavid . It Worked
