### ISSUE TITLE
Does the app need a lot of providers when there are many APIs?

### ISSUE THREAD

**Issue by weiminghuaa** [Moya/Moya#1977]
I need to classify the api to avoid file is too big when all API in only one file. My app has maybe 200 APIs. They are usually classified as follows：```UserAPI, FeedAPI, DiscoverAPI, ShoeAPI, etc.```

 Does the app need a lot of providers when there are many APIs, there ars lot of instances in memory. How to solove this to avoid too many instances?

```swift
let ShoeAPIProvider = MoyaProvider<ShoeAPI>()
let UserAPIProvider = MoyaProvider<UserAPI>()
```

ps: In Alamofire or AFNetworking, there is only one default instance，and use extension or category to classified APIs 

```swift
// APIClient+shoe.swift
extension APIClient {
    public static func getShoeHomeArticleList(with page: Int,
                                              pageSize: Int,
                                              completionHandler: @escaping (AFResult<[TalkArticle]?>) -> Void) {
        request("https://ss.com/shoe/home/article"), parameters: ["pageNum": page, "pageSize": pageSize])
    }
}
```

**Comment by amaurydavid** [comment]
Hello :)
You can use `Multitarget` with your provider to avoid having a provider for each target: https://github.com/Moya/Moya/blob/master/docs/Examples/MultiTarget.md

**Comment by weiminghuaa** [comment]
@amaurydavid  That's right. Thank you very much!
