### ISSUE TITLE
Support ObjectMapper

### ISSUE THREAD

**Issue by lkuczborski** [Moya/Moya#198]
It would be great if Moya supported [ObjectMapper](https://github.com/Hearst-DD/ObjectMapper) usage. It already can be accomplished with pure [Alamofire](https://github.com/Alamofire/Alamofire) with the help of [AlamofireObjectMapper](https://github.com/tristanhimmelman/AlamofireObjectMapper).

**Comment by colinta** [comment]
Why just ObjectMapper?  Shouldn't the user decide what library to use?  This is a "middleware" decision, so I think that a separate `MoyaObjectMapper` library would be appropriate - and it could live in the **github.com/Moya** organization!  But there are plenty of other JSON <-> Object libraries:

- Argo
- ObjectMapper
- SwiftyJSON

The trouble I've run into is that it's impossible to have compile-time checking on these, because the endpoints map to *many* different return types.  We've solved this by having `Service` classes that define per-endpoint closures.  Tedious, but at the application-code level we know we'll get back the objects we asked for.

- Api.recentPosts -> [Post] (`PostService.recentPosts() { (posts, error) in }`)
- Api.post(id: 12) -> Post (`PostService.post(id: 12) { (post, error) in }`)
- Api.currentUser -> User? (`UserService.currentUser() { (user, error) in }`)

How are you using ObjectMapper + Moya right now?  Does it lend itself to becoming a generic library?

**Comment by orta** [comment]
I'm not sure this is Moya's responsibility, object mapping in Swift is still painful and there's no obvious winner to back so we'd end up supporting a lot of different cases. I think @colinta's idea makes sense though, a separate pod that could act as a mapper.

FWIW though we didn't find it difficult at all to build our [own mapper](https://github.com/artsy/eidolon/blob/master/Kiosk/App/Networking/RAC%2BJSONAble.swift) that worked with [function chaining](https://github.com/artsy/eidolon/blob/master/Kiosk/App/AppViewController.swift#L76).

**Comment by ashfurrow** [comment]
I don't think this is Moya's job, either, but Orta's right – we may able to be clever about completion blocks that would allow users to easily do this, even without the chaining. It could be a neat demo, case study, or example in the docs. I'll give some more though to what it might look like.

**Comment by justinmakaila** [comment]
I mean, this COULD be solved with the same principles we applied to the `ReactiveMoya` and `RxMoya` extensions, I just think that these things need to be contributed by the community, otherwise we're going to have a hell of a time maintaining it all, or more likely, flat out denying the feature requests.

I can put together a more detailed guide (if anybody's into it), but here are the basics:
1. Add Moya as a submodule.
2. Write your code which uses Moya.
3. Package it up in your package manager of choice and distribute.

I don't think this is ideal, but it is a possibility for those who really want to use Moya to compose their ideal networking stack into a framework.

**Comment by ashfurrow** [comment]
If you're using CocoaPods, I've enjoyed using `pod lib create` – your just add Moya as a dependency and `pod install`.

**Comment by lkuczborski** [comment]
I am happy that I could spark this discussion :) I agree that this is a topic for a separate pod (possibly living inside github.com/Moya organization as @colinta said). Like the @ashfurrow idea about clever completion blocks and I am really curious what will emerge out of it.

**Comment by ashfurrow** [comment]
@lkuczborski we use something [like this](https://github.com/artsy/eidolon/blob/511ebb901289dbeb648cb9b0234e21ab1543c373/Kiosk/App/Networking/RAC%2BJSONAble.swift), but that's built atop signals. You're looking for something with callbacks. 

Well! Let's imagine. 

Basically, you'd want a block that takes a type and returns a closure that can be passed into Moya's `request` function. This hasn't been run through a compiler, but you get the idea:

```swift
func moyaCompletionMapsTo<T: JSONAble.Type>(classType: T, completion:(T?) -> ()) -> MoyaCompletion {
    return { (data: NSData?, statusCode: Int?, response: NSURLResponse?, error: NSError?) -> () in
        // process the response somehow and store result (might be nil) in model
        completion(model)
    }
}
```

Then you'd call:

```swift
provider.request(moyaCompletionMapsTo(Model.self, { model -> () in 
}))
```

Or something to that effect. Does that make sense?

**Comment by SRandazzo** [comment]
I've actually been building, and using, an extension to MoyaProvider that integrates ObjectMapper support. It's been working really great so far, but I haven't gotten to the point of PR-ing it just yet. I feel like pattern of subclassing `MoyaProvider` isn't the best decision, and ultimately limits flexibility (what if i want to use ObjectMapper in on instance, but the RAC extensions in another?)

I like @ashfurrow's idea above, and think we could focus on making Moya more flexible and conducive to extensions without subclassing

The basics of this extensions are:

- The MoyaMappable protcol requires you to specify the key at which the object can be found in the JSon response. (Follows a RESTful assumption)
```Swift
public protocol MoyaMappable : MoyaTarget {
    //The keypath in the response which contains the nested object or objects you want to map
    var rootKeyPath: String { get }
}
```

ObjectMapperMoyaProvider takes generic type MoyaMappable
`public class ObjectMapperMoyaProvider<T: MoyaMappable>: MoyaProvider<T> `

When sending a request, you specify alla generics what type of object is returnd. The object must conform to Mappable
```Swift
    func requestObjects<U: Mappable>(token: T, completion: ((objects: [U]?, data: NSData?, statusCode: Int?, response: NSURLResponse?, error: NSError?) -> ())) -> Cancellable {
```

Here is a Gist to the extension I wrote
https://gist.github.com/SRandazzo/a07500391da99a580937

**Comment by ashfurrow** [comment]
@SRandazzo very cool!

>  I feel like pattern of subclassing MoyaProvider isn't the best decision

Agreed. We've actually opened https://github.com/Moya/Moya/issues/144 concerning the subclassing pattern. With Swift 2's protocol extensions, it might make sense to ditch the MoyaProvider class altogether :tada:

**Comment by orta** [comment]
It feels like things like this would make great separate pods, for example here's my simple [Gloss + RxSwift](https://github.com/artsy/Emergence/blob/master/Emergence/Contexts/Networking/Observable%2BNetworking.swift) extension for Moya - that could happily be it's own thing in a similar way.

**Comment by gregpardo** [comment]
So I messed around on a branch and experimented with making the plugin system middleware style. Where each plugin can transform data before reaching the next plugin. I realize this is a huge change and there may be another way to accomplish some of the same things. One major change in my experiment is that all data is not 'AnyObject?'. This could allow for easy means to mutate response data and such for something like ObjectMapper. 

https://github.com/gregpardo/Moya/tree/experiment/middleware-flow

And example of a plugin that can transform response data might look something like this...
```Swift
public class ResponseTransformPlugin<Target: MoyaTarget>: Plugin<Target> {
    
    public override func didReceiveResponse(object: AnyObject?, statusCode: Int?, response: NSURLResponse?, error: ErrorType?, provider: MoyaProvider<Target>, target: Target) -> MoyaProvider<Target>.Response {
        object = target.responseTransform(object)
        return MoyaProvider<Target>.Response(object, statusCode: statusCode, response: response, error: error, provider: provider, target: target)
    }
    
}

public extension MoyaTarget {
    func responseTransform(object: AnyObject?) -> AnyObject?
}
```

Then the target could look something like this

```Swift
extension MyTarget : MoyaTarget {
   // Other setup here first (baseUrl, path, etc)
   public func responseTransform(object:AnyObject?) -> AnyObject? {
       switch self {
        case .GetUser:
            let user = Mapper<User>().map(object)
            return user
        }
   }
}
```

Does this make any sense or have I taken some strange roundabout approach to attempting to give plugins more power easily?

**Comment by ashfurrow** [comment]
Hmm, I can see this making sense but I agree it is a bit roundabout. I was thinking that this really belongs in the RAC/RxSwift provider extensions? Something like what we currently do at Artsy: https://github.com/artsy/eidolon/blob/f95c0a5bf1e90358320529529d6bf431ada04c3f/Kiosk/App/Networking/RAC%2BJSONAble.swift

Or we could add another `request` method that accepted a class, too. Thoughts?

**Comment by gregpardo** [comment]
Well yeah it works both ways but the downside of the reactive extension approach is a couple things in my opinion. 

* Different extensions need to be written for RxSwift/ReactiveSwift
* Either needs an API wrapper for all requests to map them to the object or each time the request is called the object class to map to has to be specified

The later seems like the approach most have taken but it kind of goes around the simplicity of configuring your provider and being ready to go.

**Comment by petester42** [comment]
I don't think that mapping to objects should be in the library but we could provide an easier way to transform responses for people who don't use reactive extensions. I've been playing around with some changes [here](https://github.com/petester42/Moya/tree/moya-extensions-test) and what we could do is move all responses to `MoyaResponse`.

This change would allow anyone to make an extension to `MoyaResponse` and create functions that map from `MoyaResponse` to anything.

For Argo it would be something like this:

```swift
extension MoyaResponse {
    
    func mapEntity<U: Decodable where U == U.DecodedType>() throws -> U {
        
        let response = try self.mapJSON()
        let decoded: Decoded<U> = decode(response)
        
        switch decoded {
        case .Success(let success):
            return success
        case let .Failure(.MissingKey(key)):
            throw NSError(domain: MoyaErrorDomain, code: MoyaErrorCode.JSONMapping.rawValue, userInfo: ["data": response, "missing": key])
        case let .Failure(.TypeMismatch(expected, actual)):
            throw NSError(domain: MoyaErrorDomain, code: MoyaErrorCode.JSONMapping.rawValue, userInfo: ["data": response, "expected": expected, "actual": actual])
        case let .Failure(.Custom(error)):
            throw NSError(domain: MoyaErrorDomain, code: MoyaErrorCode.JSONMapping.rawValue, userInfo: ["data": response, "custom": error])
        }
    }
    
    func mapEntity<U: Decodable where U == U.DecodedType>() throws -> [U] {
        
        let response = try self.mapJSON()
        let decoded: Decoded<[U]> = decode(response)
        
        switch decoded {
        case .Success(let success):
            return success
        case let .Failure(.MissingKey(key)):
            throw NSError(domain: MoyaErrorDomain, code: MoyaErrorCode.JSONMapping.rawValue, userInfo: ["data": response, "missing": key])
        case let .Failure(.TypeMismatch(expected, actual)):
            throw NSError(domain: MoyaErrorDomain, code: MoyaErrorCode.JSONMapping.rawValue, userInfo: ["data": response, "expected": expected, "actual": actual])
        case let .Failure(.Custom(error)):
            throw NSError(domain: MoyaErrorDomain, code: MoyaErrorCode.JSONMapping.rawValue, userInfo: ["data": response, "custom": error])
        }
    }
}
```  

What does everyone think about solving object mapping this way?

**Comment by gregpardo** [comment]
I like the approach. I think it's a nice bridge and keeps any mapping out of Moya's responsibilities. Would it be possible to write an ObjectMapper plugin that allows me to configure different maps per endpoint with this?

**Comment by petester42** [comment]
Could you clarify what you mean by `configure different maps per endpoint`. Doesn't ObjectMapper handle this?

I believe you can achieve everything you need without plugins, subclasses or changing the library. For example you could do something like this:

```swift
public extension MoyaResponse {

    func mapObjectMapper<U: Mappable>() throws -> [U] {

        let response = try self.mapJSON()
        guard let decoded: [U] = Mapper<U>().mapArray(response) else {
            throw NSError(domain: MoyaErrorDomain, code: MoyaErrorCode.JSONMapping.rawValue, userInfo: nil)
        }
        
        return decoded
    }
}

public extension MoyaProvider {
    
    func request<U: Mappable>(target: Target, completion: (response: [U]?, error: ErrorType?) -> ()) -> Cancellable {
        return request(target) { (response: MoyaResponse?, error: ErrorType?) in
            do {
                completion(response: try response?.mapObjectMapper(), error: error)
            } catch {
                completion(response: nil, error: error)
            }
        }
    }
}
```

And then just call the provider like so: 

```swift
GitHubProvider.request(.UserRepositories(username)) { (response: [Repo]?, error) in
    //do cool things here
}
```

**Comment by gregpardo** [comment]
Okay this looks like a great approach. I suppose whether something is a 'plugin' or not is not really important as someone can download a cocoapod of an approach like this and would get the functionality included. Now I just need to code an ObjectMapper RxSwift version!

**Comment by startupthekid** [comment]
@petester42 I'm a big fan of that approach as well. That's essentially how Alamofire adds support for different `ResponseSerializers`, just extensions on the `Request` object. And I think that's the best way to go because it doesn't really require changes to what Moya is or how it's implemented. Instead the burden is offloaded to the consumer. Another benefit of doing it the Alamofire way is that then the different "transform" or mapping functions can be chained. 

The only thing I would change is instead of having mapping functions like `mapObjectMapper`, just use the built-in response serializer functionality of Alamofire because that's all AlamofireObjectMapper does.

**Comment by gregpardo** [comment]
Sounds good. I guess this ticket could become add examples of how to implement this. I think providing some direction in the documentation on how to accomplish such a thing would be useful to a lot of people. It seems this is a feature that a lot of folks are having to hack together.

**Comment by petester42** [comment]
:+1: for the documentation. We could also add references to moya extensions that do this in the documentation so that people don't have to reimplement things.

**Comment by ivanbruel** [comment]
I created a [pod](https://github.com/ivanbruel/Moya-ObjectMapper) for people who specifically want to use `Moya` alongside with `ObjectMapper`. 

I also created the `RxSwift` bindings, if anyone wants to create the `ReactiveCocoa` ones feel free to create a pull request.

**Comment by ashfurrow** [comment]
@ivanbruel This is _fabulous_ :tada: Great work! 

I think we should be able to close this issue once the Readme has been updated to point to Ivan's library. @ivanbruel: if the maintenance on you ever need a hand maintaining your library, just let us know!

**Comment by petester42** [comment]
I think we could provide a default project for new mapping projects so that people can just copy the project and write their extensions. This would probably help people especially for the carthage support since the carthage support for Moya does have some custom scripts to get around the namespacing issues.

**Comment by ashfurrow** [comment]
Sure, sounds like a kind of super-documentation around ObjectMapper and Carthage? Neato.

**Comment by petester42** [comment]
It would be more like a starting project for any extensions someone would want to create for Moya not just for ObjectMapper. It could also document how the scripts work to change the namespaces when building for carthage.

**Comment by ashfurrow** [comment]
Cool, sounds like a bigger project. I think a mention in the Readme can help people looking for OM support now until we have the extensions documentation done.

**Comment by petester42** [comment]
Ya it would be a bigger project for sure.

**Comment by lkuczborski** [comment]
Wow, never imagined that this would explode to such an active discussion! 🎉

@ivanbruel Great work, thanks for sharing! 👍

@petester42 Very nice idea! Would gladly collaborate myself – thinking about the same thing for [Unbox](https://github.com/JohnSundell/Unbox). We have recently switched to Unbox as it offers immutable model classes, gets rid of empty inits and it basically lives well with basically any model class.

**Comment by ashfurrow** [comment]
Given https://github.com/Moya/Moya/pull/339 I'd like to close this issue. Is the larger project something we ought to open a new issue for? Maybe pointing back to this one for context?

**Comment by petester42** [comment]
I'll open a new issue for it when I have time to put my thoughts into a good description.
