### ISSUE TITLE
Unable to install "Moya 14.0.0-beta.6"

### ISSUE THREAD

**Issue by surida** [Moya/Moya#1983]
I'm trying to install "Moya 14.0.0-beta.6" but failed all.
am I missing something? 

1st try -> Pod install  
     ``` [!] CocoaPods could not find compatible versions for pod "Moya/RxSwift":  In Podfile: Moya/RxSwift (~> 14.0) ```

2nd try -> carthage update 
     ``` No available version for github "Moya/Moya" satisfies the requirement: ~> 14.0.0 ```

3rd try -> SPM
     ``` The package dependency graph can not be resolved; unable find any available tag for the following requirements:	https://github.com/Moya/Moya.git — 14.0.0..<15.0.0 ```

**Comment by sunshinejr** [comment]
@surida ah yes since this is still in beta you probably need to specify a version you want to use.

CocoaPods:
```
pod 'Moya', '14.0.0-beta.6'
```
Carthage:
```
github "Moya/Moya" "14.0.0-beta.6"
```

SPM:
```
.package(url: "https://github.com/Moya/Moya.git", .exact("14.0.0-beta.6"),
```

Sorry for the issue, gonna update the docs in a second.
