### ISSUE TITLE
Moya JWT Token Refresh

### ISSUE THREAD

**Issue by ManishaAstaPartners** [Moya/Moya#1986]
Hi , i am using Moya the issue i am facing is moya does not refresh token end point clouser gets called after request gets hit.

**Comment by ManishaAstaPartners** [comment]
> Hi , i am using Moya the issue i am facing is moya does not refresh token end point clouser gets called after request gets hit.

Hey can you please help me for this case.

**Comment by pietrocaselani** [comment]
Hello @ManishaAstaPartners 
Refresh token is a common situation and we have [a few closed issues](https://github.com/Moya/Moya/search?q=refresh+token&state=closed&type=Issues) related to this.

Could you please check if any of them has the solution you need?

**Comment by ManishaAstaPartners** [comment]
Hi @pietrocaselani i tried using request closure but the issue with that is if token gets expired the current api header does not changed even though the new token methods gets called  for the next it will take the new header. 
We are using firebase refresh token which in their end is returning a token with error in completion block. So that cannot be again used in header return.

**Comment by pietrocaselani** [comment]
Hello @ManishaAstaPartners 

> "but the issue with that is if token gets expired the current api header does not changed"

Are you using [`AccessTokenPlugin`](https://github.com/Moya/Moya/blob/master/Sources/Moya/Plugins/AccessTokenPlugin.swift)?
Can you share some piece of code?

> "We are using firebase refresh token which in their end is returning a token with error in completion block."

Suposing you are using the `AccessTokenPlugin`, then you could use the `requestClosure` to do something like this?

```swift
let accessTokenPlugin = AccessTokenPlugin { () -> String in
    self.firebaseTokenProvider.token ?? ""
}

let requestClosure = { (endpoint: Endpoint, done: @escaping MoyaProvider.RequestResultClosure) -> Void in
    if self.firebaseTokenProvider.isValid == false {
        self.firebaseTokenProvider.refreshToken(done)
    }
}
```

Here the `firebaseTokenProvider` would be an interface that interacts with Firebase and get, refresh and verify the current token.

If you could share some code for me to better understand the situation would be nice.

**Comment by ManishaAstaPartners** [comment]
Hi Pietro
Thanks for the reply.
Are you using AccessTokenPlugin
<https://github.com/Moya/Moya/blob/master/Sources/Moya/Plugins/AccessTokenPlugin.swift>?
No actually we are using firebase current token.
For getting the refresh token i am using the below code snippet.
**

  *let* currentUser = Auth.auth().currentUser

        currentUser!.getIDTokenForcingRefresh(*true*) { tkn, errorrr *in*

            *if* errorrr == *nil*, *let* aToken = tkn {

                UserManager.shared.id = aToken

                TokenCallback(aToken)

            } *else* {

                print("ERRORX-- SOMETHING WENT WRONG WITH TOKEN GENERATION")

                TokenCallback("")

            }

        }
**

For validating JWT Token i had managed a custom method
**


    *static* *func* validateJWTToken(forToken strToken: String,
successCallback completion: *@escaping* (String) -> Void) {

        *do* {

            *let* jwt = *try* decode(jwt: strToken)

            *if* jwt.expired { // TOKEN GOT EXPIRED NOW

                print("TOKEN GOT EXPIRED NOW")

                newToken { refreshedToken *in* // New Token got refreshed

                    completion(refreshedToken)

                }

            } *else* { // TOKEN IS NOT EXPIRED YET

                *return* completion(strToken)

            }

        } *catch* {

            print("ERRORX: During Token Validation \(error)")

            newToken { refreshedToken *in*

                completion(refreshedToken)

            }

        }

    }
**
Now i did not understand how can i call this jwt token method in endpoint
closure. I had called it in the request closure but the problem is when the
token gets expired the first request after that does not change it header
while the next does it may be because the firebase completion takes time.
So i just need to know the other cases.

**Comment by pietrocaselani** [comment]
I think you should be using the `AccessTokenPlugin`.
Have you seen this [document about Authentication](https://github.com/Moya/Moya/blob/master/docs/Authentication.md#access-token-auth) in Moya?

**Comment by ManishaAstaPartners** [comment]
Yes , I did but I don't find something relevant to my code.
Do let me know if you find that we are doing something wrong. Because with
the existing code i am unable to find the solution. If you need i can share
my endpoint manager and token class for your understanding.
