### ISSUE TITLE
I can't use RxSwift. I'm using swift package manager. It show provider doesn't have member rx

### ISSUE THREAD

**Issue by tannhuot** [Moya/Moya#1987]
V 13.0.1

private let provider = MoyaProvider<APITarget>()
    func getListUser() {
        provider.rx.requst //provider has no member rx
    }

**Comment by sunshinejr** [comment]
@tannhuot hey, can you post your `Package.swift`? Also, do you import `RxMoya`?

**Comment by tannhuot** [comment]
Package.swift
// swift-tools-version:5.0
import PackageDescription

let package = Package(
    name: "Moya",
    products: [
        .library(name: "Moya", targets: ["Moya"]),
        .library(name: "ReactiveMoya", targets: ["ReactiveMoya"]),
        .library(name: "RxMoya", targets: ["RxMoya"])
    ],
    dependencies: [
        .package(url: "https://github.com/Alamofire/Alamofire.git", .upToNextMajor(from: "4.1.0")),
        .package(url: "https://github.com/antitypical/Result.git", .upToNextMajor(from: "4.1.0")),
        .package(url: "https://github.com/ReactiveCocoa/ReactiveSwift.git", .upToNextMajor(from: ("5.0.0"))),
        .package(url: "https://github.com/ReactiveX/RxSwift.git", .upToNextMajor(from: "4.0.0"))
    ],
    targets: [
         .target(
            name: "Moya",
            dependencies: [
                "Alamofire",
                "Result"],
            exclude: [
                "Tests",
                "Sources/Supporting Files",
                "Examples"]),
        .target(
            name: "ReactiveMoya",
            dependencies: [
                "Moya",
                "ReactiveSwift"],
            exclude: [
                "Tests",
                "Sources/Supporting Files",
                "Examples"]),
        .target(
            name: "RxMoya",
            dependencies: [
                "Moya",
                "RxSwift"],
            exclude: [
                "Tests",
                "Sources/Supporting Files",
                "Examples"])
    ]
)
//my code
import Foundation
import Moya
import RxMoya
import RxSwift

class UserService {
    static let shared = UserService()
    private let provider = MoyaProvider<UserTarget>()
    func login(email:String, password:String, handler:@escaping(Any?)->Void) {
        _ = provider.rx.request(.login(email: email, password: password))
        .filterSuccessfulStatusCodes()
        .mapJSON()
        .subscribe() { event in
                switch event {
                case .success(let success):
                    print(success)
                    handler(success)
                case .error(let error):
                    print(error)
                    handler(error)
                }
        }
    }
}

// now it crash here
    override func run<O: ObserverType>(_ observer: O, cancel: Cancelable) -> (sink: Disposable, subscription: Disposable) where O.E == SourceSequence.E {
        let sink = FlatMapSink(selector: self._selector, observer: observer, cancel: cancel) //Thread 1: EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
        let subscription = sink.run(self._source)
        return (sink: sink, subscription: subscription)
    }

**Comment by LucianoPAlmeida** [comment]
The crash may be related to #1958
