### ISSUE TITLE
DownloadTask with both url parameter and body

### ISSUE THREAD

**Issue by phi-mai** [Moya/Moya#1990]
Hi guys ,
Currently i need to implement a download task with below info : 
![Screen Shot 2020-02-13 at 14 27 38](https://user-images.githubusercontent.com/58420350/74401470-0e81a280-4e6d-11ea-8d16-5f9b0fe52ff1.png)
And i have no idea how to implement it with Moya. Any recommend for me? Thanks in advance

**Comment by amaurydavid** [comment]
There is currently no way of having parameters in both query and body for a downloadTask by using the built-in URLEncoding. However, you can provide a custom URLEncoding that acts as a meta URLEncoding, using URLEncoding.queryString or URLEncoding.httpBody according to the parameter to encode.
Another solution might be to look at #1936 but be aware that it's a WIP.

**Comment by sunshinejr** [comment]
Oh boy, seems like we didn't include this option in the `Task` type, sorry @phi-mai! You would need a custom encoding as @amaurydavid said, you could also try appending your `URL` parameters in the `path` property and then use `JSONEncoding` for the body properties in the `task` parameter. There is also `endpointClosure` but it doesn't sound like a good workaround.

Anyhow, hopefully we can address it in the PR for refactoring the `Task` type and release soon.

**Comment by phi-mai** [comment]
Thanks for your recommends! , will try these first. By the way, thanks for great + simple library. Hope it can cover all request case soon.
