### ISSUE TITLE
Request with DownloadDestination success download file, but Result is fail with "Received empty network response"

### ISSUE THREAD

**Issue by StasanTelnov** [Moya/Moya#1991]
Hello, I use Moya 13.0.1.
I download file with in my TargetType with `downloadParameters` Task
```swift
var baseURL: URL {
     return URL(string: "http://MyBasePath.com")!
}
    
var path: String {
     return "/file.txt"
}
var method: Moya.Method {
     return .get
}

var task: Task {
     return .downloadParameters(parameters: queryParams, encoding: URLEncoding.queryString, destination: downloadDestination)
}
```
where `downloadDestination` is variable, which return `DownloadDestination`
DownloadDestination work correctly, download file and I can get file text.

But, on MoyaProvider, when I get result of request, I get error, in `.failure`:
Response: Received empty network response for download(MyApp.MyModel)
where MyModel is subclass of `Mappable`

```swift
    private func requestAPI<T: Mappable>(service: MyTargetTypeExtension, type: T.Type, success: @escaping SuccessClosure<T>, fail: @escaping FailClosure) {
        self.provider.request(service) {
            switch $0 {
                
            case let .success(moyaResponse):
                // success handle
                
            case let .failure(error):
                // fail handle
            }
        }
    }
```
I see same problem in https://github.com/Moya/Moya/issues/781#issuecomment-263754958 , but it not solve for me.
What I doing incorrect? How I can `.success` moya response on file download?

**Comment by amaurydavid** [comment]
For more info about the Received empty network response you can read #1967.
Once fixed, having the real error might help a lot ;)

**Comment by StasanTelnov** [comment]
Thanks, I migrate to new Moya version (14.0.0).
But it dont solve my problem. Now, after download file, I also move to `.failure(error)` closure with error `downloadedFileMoveFailed`:

> Domain=NSCocoaErrorDomain Code=256 "The file «eula.txt» couldn’t be opened."  UserInfo={NSURL=http://myurl.com/eula.txt}

But really file downloaded and saved to tmp directory  in  `DownloadDestination` closure.

**Comment by sunshinejr** [comment]
It's really strange, could you post the `DownloadDestination` closure you pass @StasanTelnov?

**Comment by StasanTelnov** [comment]
Yes,
```swift
    var downloadDestination: DownloadDestination {
        let url = URL(string: "\(basePath)\(path)")! // basePath is "http://myurl.com", path is "/eula.txt"
        
        return { tempUrl, response in
            return (url, .removePreviousFile)
        }
    }
```

It is tested closure, which declared in `extension APIService: TargetType`
In `tempUrl`

**Comment by sunshinejr** [comment]
@StasanTelnov AFAIK you need to provide the local path to where to save the file in the `DownloadDestination`. In case you don’t want to save a file on the disk, you can use `Task.request` instead of `.download` and parse the file in the completion closure.

**Comment by StasanTelnov** [comment]
Thaks, I solve this problem via simple request. Not very good solution, but work.
