### ISSUE TITLE
How to change the header parameter "Content-Type" to "image/jpeg"?

### ISSUE THREAD

**Issue by Sadow32** [Moya/Moya#2005]
moya version: 13.0.0

I need help! 

how to change the header parameter "Content-Type" to "image/jpeg" when upload a jpg data?

I try to change "Content-Type" like this: 

```swift
public var headers: [String : String]? {
        switch self {
        case .uploadSomething(_):
            return ["Content-Type" : "image/jpeg"]
        default:
            return myDefaultHeader
        }
    }
```
but it not works.

**Comment by VincentSit** [comment]
Hi @wuyueyang, the `headers` property is fine for normal requests, but for upload requests, Alamofire will [wrap][1] it as a form request (this is also a common practice). So AFAK you need to implement a custom [plugin][2] and implement `prepare(_:target:)` method.

[1]: https://github.com/Alamofire/Alamofire/blob/master/Source/MultipartUpload.swift#L50
[2]: https://github.com/Moya/Moya/blob/master/docs/Examples/CustomPlugin.md

**Comment by wuyueyang** [comment]
But the upload code I see in the example is this: [example](https://github.com/Moya/Moya/blob/master/docs/Examples/MultipartUpload.md)
Still not work this way

**Comment by VincentSit** [comment]
It's weird. I have tried it works. Could you please give more code?
