### ISSUE TITLE
Value of type 'MoyaProvider<Mo>' has no member 'rx'

### ISSUE THREAD

**Issue by haijunli68** [Moya/Moya#2008]
![image](https://user-images.githubusercontent.com/13010224/76544484-1744b300-64c3-11ea-934b-6a644c613f33.png)

**Comment by sunshinejr** [comment]
Hey @haijunli68, you need RxMoya dependency + import to use `.rx` namespace.

**Comment by haijunli68** [comment]
Thank you.

**Comment by susemi99** [comment]
@haijunli68 show me how to fix it please.

**Comment by susemi99** [comment]
I found!

```
import Moya
import RxMoya
```
