### ISSUE TITLE
When I add "pod 'Moya/RxSwift', '~> 14.0'", there is a bug in Xcode. and I dont know how can I do

### ISSUE THREAD

**Issue by zxiang2013** [Moya/Moya#2009]
It like this.
![Uploading 641584431470_.pic.jpg…]()

When I remove 'Moya', and It works.
What should I do?

**Comment by amaurydavid** [comment]
Your screenshot doesn't seem to work. Can you edit it ?

**Comment by zxiang2013** [comment]
> Your screenshot doesn't seem to work. Can you edit it ?

Can you se it now?
<img width="943" alt="EA8C4594-25A4-4EA4-926F-1BF8D8064BAB" src="https://user-images.githubusercontent.com/5276499/76850062-89c9e000-6881-11ea-837a-dc5e7eed01b2.png">

**Comment by eyupcimen** [comment]
Do you have also Alamofire in your project? 
You can run `pod deintegrate` and then you can run `pod install`

**Comment by zxiang2013** [comment]
> Do you have also Alamofire in your project?
> You can run `pod deintegrate` and then you can run `pod install`

Thanks but it doesn't work.
This only happen if I just add Moya. and  it works if I only add Alamofire.
It was good before, so I am confused now.

**Comment by LucianoPAlmeida** [comment]
Hey @zxiang2013 :) 
Thank you for reporting this, mind share more info like Xcode version, swift compiler version ... ?

**Comment by zxiang2013** [comment]
> Hey @zxiang2013 :)
> Thank you for reporting this, mind share more info like Xcode version, swift compiler version ... ?

Xcode version 11.1,Swift 5

**Comment by yourshinsuke** [comment]
```
my_name/Carthage/Checkouts/Moya/Sources/RxMoya/MoyaProvider+Rx.swift:24:29: error: type 'Result<Response, Error>' has no member 'error'
                    single(.error(error))
                           ~^~~~~~~~~~~~
```

Xcode version 12

**Comment by sunshinejr** [comment]
@yourshinsuke this might be an issue where you're using the older version of Moya with newest toolchain because there is a mismatch with Result type (we stopped using an external library once the new Result type was added to Swift). Try updating to version 14, or if you can't try to make sure you have the Result library imported. 

Also, please try to open a new issue since it's not really connected to this one.

**Comment by yourshinsuke** [comment]
@sunshinejr Thank you for replying.
However I use the version, set in my `Cartfile` file.
`github "Moya/Moya" "15.0.0-alpha.1"`

**Comment by sunshinejr** [comment]
@yourshinsuke ah okay - one more question, what RxSwift version do you use?

**Comment by yourshinsuke** [comment]
@sunshinejr Thank you for quick response.
I use `github "ReactiveX/RxSwift" "6.0.0-rc.1"`

**Comment by sunshinejr** [comment]
@yourshinsuke yeah that's likely an issue - we didn't prepare Moya 15 for RxSwift 6 yet - please try downgrading to 5.* for the time being.

**Comment by yourshinsuke** [comment]
@sunshinejr Thank you. I will try downgrade.

**Comment by cherrythia** [comment]
@sunshinejr , I am encountering the same issue. I have to upgrade to rxswift 6 as I have to use the latest xcode version with swift 5.3. Is there any solution for this error?

**Comment by BasThomas** [comment]
Closing as per #2120.
