### ISSUE TITLE
Minimum Deployment Target iOS 9 on Xcode 11.3.1 and Swift 5

### ISSUE THREAD

**Issue by kikisasha** [Moya/Moya#2010]
Hi fellas, 

I'll cut to the chase,
Why is the minimum deployment being set to iOS 10 ? :(
I have a concern regarding the current minimum iOS on the latest version that supports Swift 5.

The current project that I have has been running using Moya for the last 2 years.

TLDR; 
I have no choice but to stay at minimum iOS 9 + I need to keep the project compiled on Xcode 11 + Swift 5 as the App Store requires all submitted app need to do so starting April 2020.

Is there any chances to still maintain the latest App Store policies and still run the project on minimum iOS 9 ? :( 

I'm quite desperate here. 
Any info would help :(

**Comment by amaurydavid** [comment]
Sadly there is nothing we can do about that :/
Moya is based on Alamofire which does supports only iOS 10 since Alamofire 5.

**Comment by kikisasha** [comment]
:( 
......

So basically there's no alternative to maintain iOS 9 ?
Is it possible to fork repo and set the deployment to iOS 9 though ?

**Comment by amaurydavid** [comment]
There are a few possibilities that come in my mind:
- fork Alamofire to make an alternative version supporting iOS 9.
- fork Moya to make an alternative version using Alamofire 4.

Both will be more and more complex tasks as time passes.
