### ISSUE TITLE
SPM adds RxSwift dependency although not used

### ISSUE THREAD

**Issue by b-onc** [Moya/Moya#2012]
Using latest Moya in my Package.swift (14), I put my library like:
```swift
.package(url: "https://github.com/Moya/Moya.git", .upToNextMajor(from: "14.0.0")),
...
.target(name: "MyLib", dependencies: ["Moya"], path: "Sources"),
```
but I see that ReactiveSwift and RxSwift is still added. Why is it so?

**Comment by sunshinejr** [comment]
hey @b-onc, what do you mean "RxSwift is still added"? so as far as I know, currently SPM fetches everything to resolve the package and then only builds what's needed, so it might pull RxSwift but not really add it to the project - though let me know if you experience something different!

**Comment by b-onc** [comment]
Hello @sunshinejr ,

I'm inexperienced in SPM so seeing RxSwift in "Swift Package Dependencies" section I thought it was added. I've checked build logs and surely as you've said, they're not built.

Thanks for helping me quickly!
