### ISSUE TITLE
Request Body Parameter Order Randomly

### ISSUE THREAD

**Issue by kikisasha** [Moya/Moya#2014]
Regarding this matter on the previous question -> https://github.com/Moya/Moya/issues/1851

Can someone help me answer this previously ask question above? 
Bump to this issue and confuse as to how maintain a consistent request body parameters.

Yes I am aware that parameters is a type of dictionary and dictionary itself does not order like array do.

@LvJianfeng
Ask, the current version, how do I control the header information to get the submission parameters consistent with the request body's submission parameters?

**Comment by divkhare** [comment]
I thought i was missing something. is there a fix for this?

**Comment by michellemeiyin** [comment]
I manage to sort the dictionary before request by using this

`Array(paramDictionary).sorted(by: {$0.key < $1.key})`
