### ISSUE TITLE
Update RxSwift in .podspec to ~>5.1.0

### ISSUE THREAD

**Issue by dimpiax** [Moya/Moya#2018]
Hello, where do you plan to update Moya with updated RxSwift version to which uses deprecated `UIWebView`.

https://developer.apple.com/news/?id=12232019b
https://github.com/ReactiveX/RxSwift/releases/tag/5.1.0

**Comment by sunshinejr** [comment]
Hey @dimpiax - please take a look at https://github.com/Moya/Moya/issues/2003, we should be already supporting RxSwift 5.1 and above. Running `pod update` should help (and update to 5.1.0 if you don't have any other version pinning set-up) but let me know if you need any more guidance.

**Comment by dimpiax** [comment]
@sunshinejr all right then, thanks.

**Comment by agoubi** [comment]
woooh woke up on a nightmare man 
one of my apps for a big client just got rejected because of that 
just updated to 5.1 and it works
