### ISSUE TITLE
CocoaPods could not find compatible versions for pod "RxSwift"

### ISSUE THREAD

**Issue by aasamson** [Moya/Moya#2019]
When I update my pod to 'Moya/RxSwift', '~> 14.0' I got an error, can someone help me resolving this error:
```
[!] CocoaPods could not find compatible versions for pod "RxSwift":
  In snapshot (Podfile.lock):
    RxSwift (= 4.5.0, ~> 4.0, ~> 4.1)

  In Podfile:
    Moya/RxSwift (~> 14.0) was resolved to 14.0.0, which depends on
      RxSwift (~> 5.0)

Specs satisfying the `RxSwift (= 4.5.0, ~> 4.0, ~> 4.1), RxSwift (~> 5.0)` dependency were found, but they required a higher minimum deployment target.

```

Thank you in advance.

**Comment by amaurydavid** [comment]
> Specs satisfying the `RxSwift (= 4.5.0, ~> 4.0, ~> 4.1), RxSwift (~> 5.0)` dependency were found, but they required a higher minimum deployment target.
tells you that you have to update your deployment target SDK in the podfile so that Cocoapods can use RxSwift 5

**Comment by aasamson** [comment]
May I ask if what will be the desired deployment target in SDK in the podfile so that I can use RxSwift 5? Thank you.

**Comment by amaurydavid** [comment]
You can see it in the podspec, either from the [cocoapods repo](https://github.com/CocoaPods/Specs/blob/master/Specs/2/e/c/RxSwift/5.0.0/RxSwift.podspec.json) or the [RxSwift repo](https://github.com/ReactiveX/RxSwift/blob/c6c0c540109678b96639c25e9c0ebe4a6d7a69a9/RxSwift.podspec)

**Comment by aasamson** [comment]
But even I change my deployment target to 8.0 -> 10.0 still I'm getting the same error upon installing moya 14.0.0, also I check my podfile : platform :ios, '10.0' is my deployment target. :'(

**Comment by jdisho** [comment]
I think this issue is unrelated to Moya. You need RxSwift ~> 5.0 in order to have Moya/RxSwift ~> 13.0. 

If you cannot upgrade RxSwift for whatever reason, my approach would be to install Moya **without** RxSwift and manually add the RxSwift related files (look inside Moya’s RxSwift folder) to your code base.
