### ISSUE TITLE
CocoaPods could not find compatible versions for pod "RxSwift"

### ISSUE THREAD

**Issue by dahuanghuang** [Moya/Moya#2025]
I want to upgrade RxSwift to the latest version (5.1.1). But I found that Moya is dependent on RxSwift. 

This is my pod: 

> pod 'RxSwift'
  pod 'Moya/RxSwift

So I removed Moya And RxSwift(# "Moya/RxSwift", # "RxSwift"). Then pod installed RxSwift again, it upgrade to the latest version normally. However, when I tried to pod install Moya, I got an error message.

> 
    CocoaPods could not find compatible versions for pod "RxSwift":
    In snapshot (Podfile.lock):
    RxSwift (= 5.1.1, ~> 5, ~> 5.0, ~> 5.1)

    In Podfile:
    Moya/RxSwift was resolved to 1.1.1, which depends on
      RxSwift (= 1.4)

    RxDataSources was resolved to 4.0.1, which depends on
      RxSwift (~> 5.0)

    RxGesture was resolved to 3.0.2, which depends on
      RxSwift (~> 5.1)

    RxOptional was resolved to 4.1.0, which depends on
      RxSwift (~> 5)

The version of Moya I'm using is 10.0.1.

**Comment by amaurydavid** [comment]
Hello :)
The error message states that you are try to use Moya 1.1.1 (!) and not 10.0.1. This version of Moya was indeed dependent to RxSwift 1.4
If you want to use Moya/RxSwift with RxSwift 5.x you will have to upgrade to Moya 14.

**Comment by dahuanghuang** [comment]
I cannot install Moya right now, but the RxSwift I have installed is the latest version. This makes me very confused

**Comment by dahuanghuang** [comment]
If I install Moya and RxSwift at the same time, the version of RxSwift is 4.5.0 (not the latest) and the version of Moya is 13.0.1

> Installing Differentiator (3.1.0)
Installing Moya (13.0.1)
Installing Result (4.1.0)
Installing RxCocoa (4.5.0)
Installing RxDataSources (3.1.0)
Installing RxGesture (2.2.0)
Installing RxKeyboard (0.9.0)
Installing RxOptional (3.6.2)
Installing RxSwift (4.5.0)
Installing RxSwiftExt (3.4.0)

But in my local Specs, both libraries are the latest version

**Comment by amaurydavid** [comment]
May I suggest you add some version rules to each pod of your podfile ? It makes pod updates a lot easier. 
You have a lot of pods using RxSwift If you want to exclusively use RxSwift 5.x,  just add the associated rule on your podfile. Once you've done that you will see in the errors which pod is not compatible with RxSwift 5.x.

**Comment by dahuanghuang** [comment]
Ok ，thank you very much for your suggestions
