### ISSUE TITLE
Extra headers are being included

### ISSUE THREAD

**Issue by nomimalik92** [Moya/Moya#2027]
Moya Version: 14.0

I am adding headers like this but in result I am getting something else.
```swift
*return ["Content-Type":"application/json",
                "SECRET-KEY":SECRET_KEY,
                "SECRET-TOKEN":SECRET_TOKEN]*
```

**here is the output of header.**
Moya_Logger: [10/04/2020, 10:56 PM] Request Headers: ["User-Agent": "Millennium/1.0 (com.Nomi.app; build:1; iOS 13.4.0) Alamofire/5.1.0", "Content-Type": "application/json", "SECRET-TOKEN": "9I6pAyoO1mcJrtUcAvbq3kQzA2Jx9JvbsJwqwEaZzJujxQ=", "Accept-Encoding": "br;q=1.0, gzip;q=0.9, deflate;q=0.8", "Accept-Language": "en-PK;q=1.0", "SECRET-KEY": "9I6pAyoO1mvbq3kQzA2Jx9Jr"]

**Comment by sunshinejr** [comment]
Hey @nomimalik92, this is actually what was always sent in a request - in addition to your custom headers there are also session headers added by Alamofire. We just didn’t add these in the Logger plugin output in previous versions, but in version 14 we made it so you can actually see everything that we send.
