### ISSUE TITLE
xcode11.4      'Moya', '~> 14.0.0'          Failed to produce diagnostic for expression; please file a bug report

### ISSUE THREAD

**Issue by baishikele** [Moya/Moya#2028]
when I update my Xcode version to v11.4, my project has an error.
It seems to be a compile error  like "Failed to produce diagnostic for expression; please file a bug report", my pod Moya version is 14.0.0,  so, how to fix this bug?  😸

**Comment by sunshinejr** [comment]
Hey @baishikele, this doesn't seem like just using Moya is causing the issue. I'm using version 14 on Xcode 11.4 and I don't see such problems. Do you, by any chance, have the log for a bug report that you could copy here?

**Comment by andrei-gorin** [comment]
![image](https://user-images.githubusercontent.com/56085649/80260180-f2318b80-868f-11ea-9c73-9e98480b0056.png)
Same issue here and this is where it happens for me.
`let provider = MoyaProvider<MultiTarget>(requestClosure: requestClosure)`

**Comment by developeng** [comment]
let defaultProvider =
    MoyaProvider(endpointClosure: myEndpointClosure,
                              requestClosure: myRequestClosure,
                              plugins: myPlugins)  升级Xcode12.3 报错 Failed to produce diagnostic for expression; please file a bug report，   how to fix this bug? 😸
