### ISSUE TITLE
How to send String JSON Array as key in parameter?

### ISSUE THREAD

**Issue by zero-times** [Moya/Moya#2033]
post request
let images = ["1.png", "2.png", "3.png"]
let parameters = ["token": "xx", "user_id": 1, "images": images]
It contains a string array and some keyvalues.
[docs/Examples/ParameterEncoding.md](It) can't save me~

**Comment by Vanegas9090** [comment]
Just try using `JSONEncoding.default` to send it as JSON

**Comment by zero-times** [comment]
It can't work
