### ISSUE TITLE
NetworkLoggerPlugin(verbose: true)

### ISSUE THREAD

**Issue by aasamson** [Moya/Moya#2034]
Is there any way to log my request and response in Moya 14 without using verbose?

```
container.register(NetworkLoggerPlugin.self) { r in
            NetworkLoggerPlugin(verbose: true)
            }.inObjectScope(.container)
```

Thank you in advance.

**Comment by amaurydavid** [comment]
Hello,
`NetworkLoggerPlugin(verbose: true)` is not a valid way to init `NetworkLoggerPlugin` and should rise a build error.
By default `NetworkLoggerPlugin` doesn't use the verbose mode and you can customize which `logOptions` you want to use in the plugin's `configuration` object.

**Comment by aasamson** [comment]
Is there a way to see my log request and response in the compiler using NetworkLoggerPlugin logOptions? Thank you.

**Comment by amaurydavid** [comment]
The compiler won't log any request, it just builds the code. The debug console will display your logs.

To know how to use the `NetworkLoggerPlugin` I suggest you check the example app and the `NetworkLoggerPlugin.swift` file in which you will find the list of `logOptions` and a description for each one.

**Comment by aasamson** [comment]
Will do, thank you so much :)
