### ISSUE TITLE
Remove URLSessionTask failed with error from failure error

### ISSUE THREAD

**Issue by rajdhakate** [Moya/Moya#2037]
Moya version 14.0

While calling an api using Moya without any internet connect gives a failure response with error's localizedResponse
```swift
URLSessionTask failed with error: The internet connection appears to be offline
```
Is there any way to remove the URLSessionTask failed message and just keep the localizesd string?

**Comment by adelbios** [comment]
+1

**Comment by amaurydavid** [comment]
What do you call "the localized string" ? 
As far as I know this error message is not from Moya but from URLError, and is already supposed to be a localized string as its the one returned by `error.localizedDescription`

**Comment by rajdhakate** [comment]
> What do you call "the localized string" ? - can be any custom string. Suppose in my app I don't want to be use the default localizedDescription for no offline internet connection. Rather want something custom, like "Please check your internet connection" or anything.
> As far as I know this error message is not from Moya but from Alamofire or URLError, and is already supposed to be a localized string as its the one returned by `error.localizedDescription` - I have not used alomafire in a while... But I guess alomafire doesn't show `URLSessionTask failed with error:` string.

What I want to say is user may not want to see `URLSessionTask failed with error:` as a localizedDescription. Simply `The internet connection appears to be offline` will be more user friendly.

**Comment by amaurydavid** [comment]
Imo when the error comes from a third party SDK, `localizedDescription` is not meant to be directly displayed to users, but rather as an easy way for devs to debug from the console.

If you want to show an alert to users you'll have to provide an app specific message.
