### ISSUE TITLE
Carthage having issues with Pods-DemoTests-Moya

### ISSUE THREAD

**Issue by tettoffensive** [Moya/Moya#204]
It seems it still builds Moya.framework with this podfile:
```
github "Alamofire/Alamofire" ~> 1.3.0
github "ReactiveCocoa/ReactiveCocoa" ~> 3.0
github "ashfurrow/Moya"
```

**But it is spitting out this error:**
`xcodebuild: error: Scheme Pods-DemoTests-Moya is not currently configured for the build action.`

**Comment by rad182** [comment]
+1

**Comment by aloco** [comment]
+1
