### ISSUE TITLE
Avoid to compile RxSwift if we don't use it

### ISSUE THREAD

**Issue by golangnext** [Moya/Moya#2043]
(Using the latest version under Xcode 11 with Swift package manager.)

I don't use RxSwift/ReactiveSwift but came to find that these two frameworks still have to be compiled.

My question:
1. is it possible to avoid compiling RxSwift/ReactiveSwift if not being used

**Comment by sunshinejr** [comment]
Hey @golangnext - are you sure they are compiled versus just fetched? I know that there is an issue with SwiftPM that it needs to fetch everything even though you only use one subproduct out of the Package. There is an accepted Swift Evolution proposal that fixes most of this stuff but AFAIK it's not implemented yet (maybe WWDC?). For now I don't think we can do anything about it but if there is a way for us to help with that on Moya's side we will be happy to do so!
