### ISSUE TITLE
requestJSONEncodableParameters

### ISSUE THREAD

**Issue by gurgeous** [Moya/Moya#2048]
Hey, great library! Thanks for creating.

My use case requires an `Encodable` body along with url parameters. I can make this work with requestCompositeParameters, but that feels clunky. For one thing, my `var task` is doing JSON encoding but I have to silently eat any exceptions that occur.

It would be better if Moya offered `requestJSONEncodableParameters` and possibly `requestCustomJSONEncodableParameters` for completeness. Let me know if a PR would be helpful or if there is a better approach. Thanks guys!

**Comment by amaurydavid** [comment]
Hello :)
#1936 is an opened PR that should satisfy your needs.

**Comment by gurgeous** [comment]
Thank you, I will check it out! At first glance it looks like a good change. Much appreciated.
