### ISSUE TITLE
Specs satisfying the `Moya/RxSwift (~> 14.0)` dependency were found, but they required a higher minimum deployment target

### ISSUE THREAD

**Issue by Jacket12** [Moya/Moya#2056]
Specs satisfying the `Moya/RxSwift (~> 14.0)` dependency were found, but they required a higher minimum deployment target  

What's the reason and how to solve it

**Comment by amaurydavid** [comment]
Your project is compatible for older system version than Moya/RxSwift. To be able to use Moya your project needs to have either the same deploymenet target, or a later one.

Here are the Moya14 deployment targets you can find in the podspec:
```
s.ios.deployment_target = '10.0'
  s.osx.deployment_target = '10.12'
  s.tvos.deployment_target = '10.0'
  s.watchos.deployment_target = '3.0'
```
If you are making an iOS app, your app should use a deployment target >= 10 if you want to use Moya.

**Comment by Jacket12** [comment]
Thank you



发自我的iPhone


------------------ Original ------------------

**Comment by sunshinejr** [comment]
@Jacket12 Closed by feel free to reopen in case you have more questions to that!
