### ISSUE TITLE
Not getting valid error code for network failure

### ISSUE THREAD

**Issue by prateek3255** [Moya/Moya#2059]
I am handling the MoyaError in my request function using the following switch case -

```swift
switch moyaError {
   // All the different kinds of errors handled
  case .underlying(let underlyingError as NSError, _):
            print("code", underlyingError.code,  underlyingError.localizedDescription)
}
```
And I am getting the following output in case of network failure -

```
code 13 URLSessionTask failed with error: The Internet connection appears to be offline.
````

Shouldn't I be getting `-1009` as the code for `NSURLErrorNotConnectedToInternet` instead of 13? Or am I missing something here.

My Moya version is 14.0.0

**Comment by skooal** [comment]
dizzy

**Comment by cpradobliss** [comment]
I have the same problem. receiving error code 13 when I should be receiving a -1009.

**Comment by SAO-Asuna** [comment]
I would like to ask if there is a final solution? How to solve it?
thank you!

**Comment by SAO-Asuna** [comment]
> I have the same problem. receiving error code 13 when I should be receiving a -1009.

I would like to ask if there is a final solution? How to solve it?
thank you!

**Comment by chrsp** [comment]
It's not a solution. But I'm currently using this workaround:

```
            if let alamofireError = moyaError.errorUserInfo["NSUnderlyingError"] as? Alamofire.AFError,
              let underlyingError = alamofireError.underlyingError as NSError?,
              [NSURLErrorNotConnectedToInternet, NSURLErrorDataNotAllowed].contains(underlyingError.code) {
                
                return ConnectionError.noInternetConnection
                
            } 
```

It's a very verbose and ugly code, so I hope some solution be provided anytime soon.

**Comment by stherold** [comment]
No solution yet? We have the same problem. Hard to identify these errors in our Logs :-( ...

**Comment by stherold** [comment]
The answer seems a bit outdated. Didn't work for me. The most important thing here is to receive the correct statuscode. We do that with the following snippet:

```swift
switch moyaError {
[...]
case .underlying(let error, let response):
    let underlyingCode: Int

    // Try to get the correct status code from the most specific to the most general approach.
    // This enables to log the correct (most low level) status code to Crashlytics without switching over
    // each single case of Alamofire.AFError.
    // Read about NSURLError codes on https://stackoverflow.com/a/47328885/971329
    if let underlyingError = (error as? Alamofire.AFError)?.underlyingError {
        underlyingCode = (underlyingError as NSError).code
    } else if let alamofireError = error as? Alamofire.AFError {
        underlyingCode = (alamofireError as NSError).code
    } else {
        underlyingCode = (error as NSError).code
    }
[...]
}
```

We then use the underlying code to log an error with the **correct** status code to Crashlytics 🙌
