### ISSUE TITLE
get request with Task.requestCompositeParameters

### ISSUE THREAD

**Issue by InsectQY** [Moya/Moya#2075]
### Version

Xcode (11.6)

Moya/Core (14.0.0)

Alamofire (5.2.2)

### My problem

When i use `get` method with `Task.requestCompositeParameter` 

```swift
var method: Moya.Method {
   get
}

var task: Task {
 .requestCompositeParameters(bodyParameters: [:],
                             bodyEncoding: URLEncoding.httpBody,
                             urlParameters: parameters)
}
```

An error has occurred

`Alamofire.AFError.URLRequestValidationFailureReason.bodyDataInGETRequest(0 bytes)`

Then I found an answer on [Stackoverflow](https://stackoverflow.com/questions/60960976/swift-5-alamofire-5-get-method-error-alamofire-aferror-urlrequestvalidation)

"Alamofire 5 and Apple's 2019 frameworks now produce an error when you try to make a `GET` request with body data, as such a request is invalid."

Perhaps these two parameters(bodyData: Data, bodyParameters: [String: Any]) can be modified to an optional type.

 Like this

```swift
public enum Task {
  /// A requests body set with data, combined with url parameters.
  case requestCompositeData(bodyData: Data?, urlParameters: [String: Any])

  /// A requests body set with encoded parameters combined with url parameters.
  case requestCompositeParameters(bodyParameters: [String: Any]?, bodyEncoding: 	ParameterEncoding, urlParameters: [String: Any])
}

```

Looking forward to your reply. Thank you.

**Comment by grand-china** [comment]
what the fuck.   rubblish  moya
