### ISSUE TITLE
how to set GET Method no urlEncode 

### ISSUE THREAD

**Issue by xhp281** [Moya/Moya#2076]
Moya Version - 14.0

```swift
var method:Moya.Method{
    return .get
}
    
var task:Task{
     var params: [String: Any]   = [String: Any]()
     switch self {
     case .getUserInfo(let token):
       params = ["token": "xxx=","appid": "xxxx"]
    }
   return .requestParameters(parameters: params, encoding: URLEncoding.default)
}
```

When I create a string for my path like:

"?access_token=ACCESSTOKEN&appid=xxxx"
The '=' gets converted to '%253d' in the url which is sent and the server can't read this. Is there a way to send the '?' rather than the encoded unicode?

What I want to send as the URL:

https://api.test.co.uk/v1-dev/test/3?access_token=e02fkjhbjb4faf363jn0bcbeca0fad4aff==
What is actually sent as the URL:

Request: https://api.test.co.uk/v1-dev/test/access_token=e02fkjhbjb4faf363jn0bcbeca0fad4aff%253d

**Comment by amaurydavid** [comment]
The "=" character is reserved in the query part of an url, this is why it's url encoded. The right thing to do is not to send your token unencoded, but to make sure your API receives it encoded, unencode this, and only then use it.
If you don't want to deal with url encoding you can send your accessToken in a header field.
