### ISSUE TITLE
How do I use a self-signed certificate for HTTPS requests

### ISSUE THREAD

**Issue by huyabin** [Moya/Moya#2077]
Moya:14.0.0/13.0.0

How do I use a self-signed certificate for HTTPS requests.

**Comment by huyabin** [comment]
Can you give me an demo？

**Comment by starup** [comment]
//处理https证书验证
let secManager = Manager(
    configuration: URLSessionConfiguration.default,
    serverTrustPolicyManager: CustomServerTrustPoliceManager()
)
//从bundle里获取自签名证书进行ssl认证
class CustomServerTrustPoliceManager : ServerTrustPolicyManager {
    override func serverTrustPolicy(forHost host: String) -> ServerTrustPolicy? {
        //        return .disableEvaluation
        let pathToCert = Bundle.main.path(forResource: "appssec_root_ca", ofType: "cer")
        let localCertificate:NSData = NSData(contentsOfFile: pathToCert!)!
        
        return .pinCertificates(certificates: [SecCertificateCreateWithData(nil, localCertificate)!], validateCertificateChain: true,
                                validateHost: true)
    }
    public init() {
        super.init(policies: [:])
    }
}

let provider = MoyaProvider<APIService>(manager: secManager, plugins: [NetworkLoggerPlugin(verbose: true)])

**Comment by huyabin** [comment]
Thank you very much for your help

**Comment by huyabin** [comment]
> //处理https证书验证
> 
> ```
> let secManager = Manager(
>     configuration: URLSessionConfiguration.default,
>     serverTrustPolicyManager: CustomServerTrustPoliceManager()
> )
> ```
> 
> //从bundle里获取自签名证书进行ssl认证
> 
> ```
> class CustomServerTrustPoliceManager : ServerTrustPolicyManager {
>     override func serverTrustPolicy(forHost host: String) -> ServerTrustPolicy? {
>         //        return .disableEvaluation
>         let pathToCert = Bundle.main.path(forResource: "appssec_root_ca", ofType: "cer")
>         let localCertificate:NSData = NSData(contentsOfFile: pathToCert!)!
>         
>         return .pinCertificates(certificates: [SecCertificateCreateWithData(nil, localCertificate)!], validateCertificateChain: true,
>                                 validateHost: true)
>     }
>     public init() {
>         super.init(policies: [:])
>     }
> }
> ```
> 
> `let provider = MoyaProvider<APIService>(manager: secManager, plugins: [NetworkLoggerPlugin(verbose: true)])`

Could you please provide the mode of Moya14,Thanks。

**Comment by huyabin** [comment]
> //处理https证书验证
> 
> ```
> let secManager = Manager(
>     configuration: URLSessionConfiguration.default,
>     serverTrustPolicyManager: CustomServerTrustPoliceManager()
> )
> ```
> 
> //从bundle里获取自签名证书进行ssl认证
> 
> ```
> class CustomServerTrustPoliceManager : ServerTrustPolicyManager {
>     override func serverTrustPolicy(forHost host: String) -> ServerTrustPolicy? {
>         //        return .disableEvaluation
>         let pathToCert = Bundle.main.path(forResource: "appssec_root_ca", ofType: "cer")
>         let localCertificate:NSData = NSData(contentsOfFile: pathToCert!)!
>         
>         return .pinCertificates(certificates: [SecCertificateCreateWithData(nil, localCertificate)!], validateCertificateChain: true,
>                                 validateHost: true)
>     }
>     public init() {
>         super.init(policies: [:])
>     }
> }
> ```
> 
> `let provider = MoyaProvider<APIService>(manager: secManager, plugins: [NetworkLoggerPlugin(verbose: true)])`

Thank you very much for your help,Could you please provide the mode of Moya14,Thanks。

**Comment by DouDouYup** [comment]
Support Moya14.0.0 & Alamofire 5.4.3
```
struct Certificates {
    static let certificate: SecCertificate = Certificates.certificate(filename: "certificateFileName")

    private static func certificate(filename: String) -> SecCertificate {
        let filePath = Bundle.main.path(forResource: filename, ofType: "cer") ?? ""
        let data = try! Data(contentsOf: URL(fileURLWithPath: filePath))
        let certificate = SecCertificateCreateWithData(nil, data as CFData)!
        return certificate
  }
}

var session: Session {
    let certificates = [
        (URL.init(string: baseURLString)?.host)!:
            PinnedCertificatesTrustEvaluator(certificates: [Certificates.certificate],
                                             acceptSelfSignedCertificates: true,
                                             performDefaultValidation: true,
                                             validateHost: false)]


    let serverTrustPolicy = ServerTrustManager(
                allHostsMustBeEvaluated: false,
                evaluators: certificates)

    let session = Session(serverTrustManager: serverTrustPolicy)
    return session
}

let provider = MoyaProvider<API>(session: session)
```

**Comment by pangyunxiu** [comment]
> 

Thanks！
