### ISSUE TITLE
HTTP Headers support

### ISSUE THREAD

**Issue by rad182** [Moya/Moya#208]
hi, how can i add additional http headers? e.g Content-Type: application/json

**Comment by ashfurrow** [comment]
Don't worry about it! Glad that's what you're looking for.

**Comment by BMR731** [comment]
`let endpointClosure = { (target: MyTarget) -> Endpoint<MyTarget> in
    let url = target.baseURL.URLByAppendingPathComponent(target.path).absoluteString
    let endpoint: Endpoint<MyTarget> = Endpoint<MyTarget>(URL: url, sampleResponseClosure: {.NetworkResponse(200, target.sampleData)}, method: target.method, parameters: target.parameters)
    return endpoint.endpointByAddingHTTPHeaderFields(["APP_NAME": "MY_AWESOME_APP"])
}

let provider = MoyaProvider<MyTarget>(endpointClosure: endpointClosure)

then i got this error
  "errors" : [
    "Unable to find endpoint"
  ]


`
my usage is not correct or something, i read the documents....,thank you
