### ISSUE TITLE
How to disable Moya Cache?

### ISSUE THREAD

**Issue by mvanegasdev** [Moya/Moya#2080]
Hi I have a basic network layer using Moya 14.0.0. Something like this:

```
struct MoyaRequester {
    private let provider: MoyaProvider<MultiTarget>

    func perform(request target: TargetType, completion: (Result<Data, Error>) -> Void) {
        provider.request(MultiTarget(target)) { response in
            switch response {
            case .success(let result):
                completion(.success(result.data))
            case .failure(let error):
                completion(.failure(error))
            }
        }
    }
}
```
And when I disconnect the device network, and then I make a request, it returns me the stored data, and I don't want to keep it stored but I don't know how to disable it. Could someone help me?

**Comment by mvanegasdev** [comment]
I found a solution in this Issue #1679

**Comment by sunshinejr** [comment]
@mvanegasdev thanks for letting us know! I think this is a pretty good plugin that could go into the documentation. Would you like to add `CachePolicyPlugin` as an example to [Examples](https://github.com/Moya/Moya/tree/master/docs/Examples)? Don't feel pressured though - if you cannot/don't want to do it just let me know, we will create an issue so someone else could try and implement it 👍

**Comment by mvanegasdev** [comment]
@sunshinejr Of course I would like to help adding the plugin as an example 👌🏻 Thanks for letting me help!

**Comment by sunshinejr** [comment]
@mvanegasdev awesome - please let me know in case you have any questions regarding creating a PR, will be happy to help!

**Comment by mvanegasdev** [comment]
I've already made the PR 👌🏻
