### ISSUE TITLE
How can I build with Xcode12 carthage error

### ISSUE THREAD

**Issue by WUYUEZONG** [Moya/Moya#2087]
version: Moya 14.0
macOs: 10.15.16

<code>Task failed with exit code 1:</code>

**Comment by sunshinejr** [comment]
hey @WUYUEZONG, did you solve the issue?

**Comment by WUYUEZONG** [comment]
@sunshinejr 

I can build it now.

by
[Carthage issue](https://github.com/Carthage/Carthage/issues/3019#issue-664185584)

BTW, 

[And a easy way](https://github.com/Carthage/Carthage/issues/3019#issuecomment-694329329)

but, it also happens `swift complier`  error

**Comment by sunshinejr** [comment]
@WUYUEZONG awesome, glad you got it resolved - thanks for the update!

**Comment by YangYouYong** [comment]
I have tried the [workaround page](https://github.com/Carthage/Carthage/blob/master/Documentation/Xcode12Workaround.md), and that worked for me.
