### ISSUE TITLE
Can't compile with Cocopods and Xcode 12

### ISSUE THREAD

**Issue by alouanemed** [Moya/Moya#2088]
I just updated to Xcode 12 and couldn't compile the project.
```
 
Prebuilding Localize-Swift...
Prebuilding Moya...
> Copying Alamofire-umbrella.h
> Processing Alamofire-Info.plist
> Copying RxSwift-umbrella.h
> Processing RxSwift-Info.plist
> Compiling RxSwift_vers.c
> Compiling RxSwift-dummy.m
> Linking RxSwift
> Generating 'RxSwift.framework.dSYM'
> Touching RxSwift.framework (in target 'RxSwift' from project 'Pods')
> Linking Alamofire
> Linking Alamofire
> Copying Moya-umbrella.h

[x] /Users/alouanemed/Projects/a-iOS/Pods/_Prebuild/Moya/Sources/RxMoya/MoyaProvider+Rx.swift:2:8: compiling for iOS 10.0, but module 'RxSwift' has a minimum deployment target of iOS 12.0: /Users/alouanemed/Projects/a-iOS/Pods/build/Release-iphoneos/RxSwift/RxSwift.framework/Modules/RxSwift.swiftmodule/arm64-apple-ios.swiftmodule

import RxSwift

```

**Comment by jordizspmobile** [comment]
Same for me, I try to write this in podfile:

```

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
        end
    end
end
```

but now it said the import RxSwift doesn't exist.

**Comment by jordizspmobile** [comment]
> I just updated to Xcode 12 and couldn't compile the project.
> 
> ```
>  
> Prebuilding Localize-Swift...
> Prebuilding Moya...
> > Copying Alamofire-umbrella.h
> > Processing Alamofire-Info.plist
> > Copying RxSwift-umbrella.h
> > Processing RxSwift-Info.plist
> > Compiling RxSwift_vers.c
> > Compiling RxSwift-dummy.m
> > Linking RxSwift
> > Generating 'RxSwift.framework.dSYM'
> > Touching RxSwift.framework (in target 'RxSwift' from project 'Pods')
> > Linking Alamofire
> > Linking Alamofire
> > Copying Moya-umbrella.h
> 
> [x] /Users/alouanemed/Projects/a-iOS/Pods/_Prebuild/Moya/Sources/RxMoya/MoyaProvider+Rx.swift:2:8: compiling for iOS 10.0, but module 'RxSwift' has a minimum deployment target of iOS 12.0: /Users/alouanemed/Projects/a-iOS/Pods/build/Release-iphoneos/RxSwift/RxSwift.framework/Modules/RxSwift.swiftmodule/arm64-apple-ios.swiftmodule
> 
> import RxSwift
> ```

i think that you need view this post -> https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-object-file-built-for-ios

but Moya need to update this issue

**Comment by rankinit** [comment]
Having the same issue in XCode12

**Comment by jordizspmobile** [comment]
Update to last version of cocoapods with the next line:

`sudo gem install cocoapods --pre`

This version has fixed the problem with arm64 error.

And added to Exclude architectures in your project target -> Build Settings -> Excluded Architectures -> arm64

That work for me :)

**Comment by yourshinsuke** [comment]
@jordizspmobile 
Could you write with indent?

**Comment by alouanemed** [comment]
@jordizspmobile 
I had that in my pod file so removing from Podfile seem to solve the issue

**Comment by jordizspmobile** [comment]
You can close this isssue for me. I just need to add these lines to my all targets.

![Captura de pantalla 2020-10-21 a las 12 44 13](https://user-images.githubusercontent.com/26137680/96709568-28c83480-139b-11eb-846b-2f2f7d23c678.png)

**Comment by sunshinejr** [comment]
Yes that's a known issue for both Carthage and CocoaPods. I will close it, but will pin it at the top of our issues since this is a pretty popular topic nowadays. For Carthage, [this is a script I use](https://github.com/Carthage/Carthage/issues/3019#issuecomment-665136323) for now since the work for proper fix is not yet done.
