### ISSUE TITLE
Async endpoint resolution

### ISSUE THREAD

**Issue by ashfurrow** [Moya/Moya#209]
Our `endpointResolver` currently returns an `NSURLRequest`, which is cool, but makes working with async APIs like [Heimdall](https://github.com/rheinfabrik/Heimdall.swift) very difficult (by the nature of OAuth, [these requests cannot be synchronous](https://github.com/rheinfabrik/Heimdall.swift/blob/f67abd632b6ccc4604ae8fa2b6eab9d6b7855310/Heimdall/Heimdall.swift#L193).

I'm thinking that the the endpointResolver is passed in a closure that accepts the NSURLRequest as an argument, and the resolver calls this closure when the request is finished. Suggestions?

**Comment by ashfurrow** [comment]
So I'm thinking something like this:

```swift
public typealias RequestClosure = (Endpoint<Target>, NSURLRequest -> Void) -> Void
```

That the user passes in to the provider. It's a closure that's given the target, and another closure that accepts an NSURLRequest. The way you'd do this is something like:

```swift
let provider = MoyaProvider<MyTarget>(requestClosure: { endpoint, done in
    let request = endpoint.urlRequest
    // Modify the request, asynchronously.
    done(request)
})
```

My implementation of `request()` looks something like this:

```swift
public func request(token: Target, completion: Moya.Completion) -> Cancellable {
    let endpoint = self.endpoint(token)

    var innerCancellable: CancellableToken?
    var cancelled = false
    let outerCancellable = CancellableToken {
        innerCancellable?.cancel()
        cancelled = true
    }

    let performNetworking = { (request: NSURLRequest) in
        if cancelled { return }
        let stubBehavior = self.stubClosure(token)

        switch stubBehavior {
        case .Never:
            innerCancellable = self.sendRequest(request, completion: completion)
        default:
            innerCancellable = self.stubRequest(request, completion: completion, endpoint: endpoint, stubBehavior: stubBehavior)
        }
    }

    requestClosure(endpoint, performNetworking)

    return outerCancellable
}
```

The hard part is synchronously returning something from `request()` that can cancel an activity that hasn't yet been created. There's almost certainly something nicer than this, but I'm pretty tired :sleeping: 

@MarvinNazari what do you think?

**Comment by ashfurrow** [comment]
Supper we could wrap the cancelation: 

```swift
struct CancellableWrapper: Cancellable {
    var innerCancellable: CancellableToken? = nil

    private var isCancelled = false

    func cancel() {
        innerCancellable?.cancel()
    }
}
```

Which simplifies our implementation a bit: 

```swift
public func request(token: Target, completion: Moya.Completion) -> Cancellable {
    let endpoint = self.endpoint(token)

    var cancellableToken = CancellableWrapper()

    let performNetworking = { (request: NSURLRequest) in
        if cancellableToken.isCancelled { return }

        let stubBehavior = self.stubClosure(token)

        switch stubBehavior {
        case .Never:
            cancellableToken.innerCancellable = self.sendRequest(request, completion: completion)
        default:
            cancellableToken.innerCancellable = self.stubRequest(request, completion: completion, endpoint: endpoint, stubBehavior: stubBehavior)
        }
    }

    requestClosure(endpoint, performNetworking)

    return cancellableToken
}
```

**Comment by MarvinNazari** [comment]
Yeah!! this is awesome!

**Comment by ashfurrow** [comment]
Thanks! What do you think of the implementation? https://github.com/Moya/Moya/pull/230

**Comment by MarvinNazari** [comment]
Looks good! solves my problem 👍

**Comment by ashfurrow** [comment]
Fixed in https://github.com/Moya/Moya/pull/230 Will be released soon.
