### ISSUE TITLE
SPM integration instruction not clear, what link (repo) should I provide for Xcode to get reactive Moya

### ISSUE THREAD

**Issue by atrbx5** [Moya/Moya#2090]
Xcode 12
iOS 14

for pods we had
pod 'Moya/RxSwift', '~> 14.0'

but for SPM I should edit some file, where Xcode require link in some UI

can smbd explain what do I get wrong?

**Comment by sunshinejr** [comment]
Hey @atrbx5, the instructions are for SPM without using Xcode integration built in. If you're using Xcode, it is actually recommended to use the Xcode UI, not the command line instructions. I will add a note to the Readme about that, thanks!

**Comment by atrbx5** [comment]
Hi, I've tried

- "https://github.com/Moya/Moya.git"
- Xcode fetches for my target
- then select rxMoya 
- Got an error when compile

```
service = MoyaProvider<T>(plugins: [NetworkLoggerPlugin()])
service.rx.request(target).map { result -> R? in
```
```
Value of type 'S' has no member 'rx'
Value of type 'MoyaProvider<T>' has no member 'rx'
```

Looks like xcode don't understand to use rx
though is see in fetched dependencies 
```
Moya
ReactiveSwift
RxSwift
```

**Comment by sunshinejr** [comment]
@atrbx5 did you drag `RxMoya` into your target and then import `RxMoya` in the file?

**Comment by atrbx5** [comment]
oh, sorry, so we need all 3 imports
import Moya
import RxSwift
import RxMoya
thanks
