### ISSUE TITLE
[Moya14.0.0, Xcode 12] Unsupported media type, error code: 415.

### ISSUE THREAD

**Issue by JimmieWong** [Moya/Moya#2091]
<img width="595" alt="截屏2020-09-30 下午8 43 25" src="https://user-images.githubusercontent.com/1055066/94689307-4e948780-0361-11eb-9e42-8e96e4b7b921.png">

@sunshinejr  if I use URLEncoding of Moya 14.0 in requestParams, it error - content type unsupported.

**Comment by JimmieWong** [comment]
it works well at below versions.
  - Moya (12.0.1):
    - Moya/Core (= 12.0.1)
  - Moya-ObjectMapper/Core (2.8):
    - Moya (~> 12.0)
    - ObjectMapper (~> 3.4)
  - Moya-ObjectMapper/RxSwift (2.8):
    - Moya-ObjectMapper/Core
    - Moya/RxSwift
    - RxSwift (~> 4)
  - Moya/Core (12.0.1):
    - Alamofire (~> 4.1)
    - Result (~> 4.0)
  - Moya/RxSwift (12.0.1):
    - Moya/Core
    - RxSwift (~> 4.0)

**Comment by sunshinejr** [comment]
Hey @JimmieWong, do you mean that it doesn't work with Moya 14 but works with Moya 12? If so, could you provide more details? I'd love to investigate this.

**Comment by JimmieWong** [comment]
![Uploading 截屏2020-10-02 下午3.27.22.png…]()
<img width="733" alt="截屏2020-10-02 下午3 26 41" src="https://user-images.githubusercontent.com/1055066/94898346-fe820600-04c3-11eb-9248-268ebfab065d.png">

@sunshinejr  the usage is very simple as picture showing - yes, works fine before I upgrade Moya from 12.0.1 to 14.0
I think the magic is from "URLEncoding", any changes between the versions?

I try to customize my Encoding, but still can not work stable. wired.
<img width="774" alt="截屏2020-10-02 下午3 32 54" src="https://user-images.githubusercontent.com/1055066/94898699-9253d200-04c4-11eb-96b4-314a3e2db6b8.png">


FYI The post parameters from app makes error in backend - but backend works well if I use Moya 12.0.1.
<img width="1175" alt="截屏2020-10-02 下午3 34 01" src="https://user-images.githubusercontent.com/1055066/94898778-b4e5eb00-04c4-11eb-80ec-735735b72088.png">

Thanks for your help.

**Comment by JimmieWong** [comment]
@sunshinejr  FYI there is one same  415 error code issue. https://github.com/Moya/Moya/issues/2053 so i am not alone.

**Comment by JimmieWong** [comment]
Case1:: Use URLEncoding in Moya 14.0 & header is nil

    public func requestParams(_ params: [String: Any], encoding: ParameterEncoding = URLEncoding.default) -> Task {
        if !params.isEmpty {
            return .requestParameters(parameters: params, encoding: encoding)
        }
        return .requestPlain
    }

    public var headers: [String: String]? {
        return nil
    }


13:59:36.995 💚 DEBUG Moya+Plugins.prepare():20 - VerboseLogPlugin: request to sent: clientId=App&lastVersion=iPhone%2C%2014.0%2C%20Version%203.0.0%20%2818%29&passKey=a3f53df51-4e99-b1f1-2fd09e507&password=hQ3xxxikvA%3D%3D&platformType=1&secretId=8F5C&secretKey=43861-E5B1-945B-2C750C3B27B4&username=VItfXjTGlwhEmwb4RT32u5fF0pbgoci5jWScA%3D)
2020-10-03 13:59:37.081678+0800 Demo[17350:185104] [] nw_protocol_get_quic_image_block_invoke dlopen libquic failed
13:59:37.120 💚 DEBUG Moya+Plugins.didReceive():33 - VerboseLogPlugin: response: {
    error = "Unsupported Media Type";
    message = "Content type 'application/x-www-form-urlencoded;charset=utf-8' not supported";
    path = "/core/user/login";
    status = 415;
    timestamp = "2020-10-03T05:59:37.111+0000";
})

**Comment by JimmieWong** [comment]
Case1:: Use URLEncoding in Moya 14.0 & header as json
   
     public var headers: [String: String]? {
        return ["Content-Type":"application/json;charset=UTF-8"]
    }

    public func requestParams(_ params: [String: Any], encoding: ParameterEncoding = URLEncoding.default) -> Task {
        if !params.isEmpty {
            return .requestParameters(parameters: params, encoding: encoding)
        }
        return .requestPlain
    }

2020-10-03 14:04:28.122240+0800 Demo[18337:192140] [] nw_protocol_get_quic_image_block_invoke dlopen libquic failed
14:05:23.011 💚 DEBUG Moya+Plugins.prepare():20 - VerboseLogPlugin: request to sent: clientId=App&lastVersion=iPhone%2C%2014.0%2C%20Version%203.0.0%20%2818%29&passKey=a3f53df6-b451-4e99-b1f1-2fd09e607&password=hQ37Z1pdZiepSjikvA%3D%3D&platformType=1&secretId=8F8AC&secretKey=8E861-E585-46B1-945B-2C750C3B27B4&username=VItfXjTGEmwb4RT32ua7mUrH5fF0pbgoci5jWScA%3D)
14:05:23.184 💚 DEBUG Moya+Plugins.didReceive():33 - VerboseLogPlugin: response: {
    code = 20002;
    remark = "Session expired. Please sign in.";
})

Backend Err =========================
HttpMessageNotReadableException: JSON parse error: Unrecognized token 'clientId': was expecting ('true', 'false' or 'null'); nested exception is com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'clientId': was expecting ('true', 'false' or 'null')
 at [Source: (PushbackInputStream); line: 1, column: 10]
2020-10-03 14:09:07.224  WARN 14730 --- [nio-8082-exec-7] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved exception caused by Handler execution: org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Unrecognized token 'clientId': was expecting ('true', 'false' or 'null'); nested exception is com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'clientId': was expecting ('true', 'false' or 'null')
 at [Source: (PushbackInputStream); line: 1, column: 10]

**Comment by JimmieWong** [comment]
@sunshinejr

**Comment by JimmieWong** [comment]
changed to JSONEncoding to fix.

**Comment by JimmieWong** [comment]
Changed to JSONEncoding to fix.
