### ISSUE TITLE
Translate CachePolicyPlugin to Chinese

### ISSUE THREAD

**Issue by sunshinejr** [Moya/Moya#2092]
[We just merged the `CachePolicyPlugin`](https://github.com/Moya/Moya/pull/2083) example and we'd love to have it translated in our CN docs. Please respond here if you'd like to take care of that - thanks!

**Comment by Bhavna777** [comment]
I want to work on it.

**Comment by sunshinejr** [comment]
@Bhavna777 thank you so much 🙏 assigned you to the ticket, let me know if you'd need any help or if you won't have time to implement the translation!

**Comment by Bhavna777** [comment]
As soon as possible, I'll do it

**Comment by sunshinejr** [comment]
This is done - closing!
