### ISSUE TITLE
Fix Peril error

### ISSUE THREAD

**Issue by sunshinejr** [Moya/Moya#2093]
So recently Peril-invite script started to throw errors (e.g. [here](https://github.com/Moya/Moya/pull/2083#issuecomment-702025588)), as I'm not experienced with it I'm not sure what it could be, but it has issues with `addOrgMembership` func - maybe due to some GH/Api changes? 

cc @f-meloni @SD10 if y'all have some time to look at it that would be awesome 🙏

**Comment by f-meloni** [comment]
I will give it a look and see if I find something :)
