### ISSUE TITLE
how to disable cache in RxMoya ? 

### ISSUE THREAD

**Issue by jaipee1** [Moya/Moya#2097]

**Comment by sunshinejr** [comment]
Hey @jaipee1 - what do you mean disable cache? Do you mean to change the cache policy from `URLSession`? In that case you could take a look at our example for `CachePolicyPlugin`: https://github.com/Moya/Moya/blob/master/docs/Examples/CachePolicyPlugin.md

Otherwise please let me know what do you have in mind and we will try to help 👍

**Comment by jaipee1** [comment]
```
input.getFavouriteAddressTrigger.flatMapLatest { () -> Observable<FavouriteAddressResponseModel?> in
            return self.getAllFavouriteAddress()
        }.subscribe(onNext: { (items) in
            favouriteAddress.accept(items?.favouriteAddress)
        }).disposed(by: rx.disposeBag)
        
        
        input.getCitiesTrigger.flatMapLatest { () -> Observable<CityListModel?> in
            return self.getAllCities()
        }.subscribe(onNext: { (items) in
            elements.accept(items?.cities ?? [])
        }).disposed(by: rx.disposeBag)
```

@sunshinejr thanks for respond me back but i have an issue in RXMoya 
i have two Observables 1. getFavouriteAddressTrigger & 2. getCitiesTrigger.
both trigger on view did load simultaneously.

when 1 Observable is trigger hen i got the accurate response which i want but in 2nd Observable i got the 1st observable Response. why is this happening i don't know.

i thought maybe this is RxMoya caching issue so i try that which you mentioned above but didn't work for me.

so Please let me know what is the issue.

i am using [SwiftHub project Architecture](https://github.com/khoren93/SwiftHub)

**Comment by jaipee1** [comment]
> Hey @jaipee1 - what do you mean disable cache? Do you mean to change the cache policy from `URLSession`? In that case you could take a look at our example for `CachePolicyPlugin`: https://github.com/Moya/Moya/blob/master/docs/Examples/CachePolicyPlugin.md
> 
> Otherwise please let me know what do you have in mind and we will try to help 👍

i apply that is my project but didn't resolve the issue.

**Comment by sunshinejr** [comment]
@jaipee1 sorry but I don't think I understand. In the first `Observable` you seem to have a different model than in the second one (favourite address vs cities). I would need a little bit more code to try and help with potential bugs. E.g. what elements do you listen to in the view and how exactly are those populated by the observables.

**Comment by jaipee1** [comment]
```
let elements = BehaviorRelay<[City]>(value: [])
let favouriteAddress = BehaviorRelay<FavouriteAddress?>(value: nil)

input.getFavouriteAddressTrigger.flatMapLatest { () -> Observable<FavouriteAddressResponseModel?> in
            return self.getAllFavouriteAddress()
        }.subscribe(onNext: { (items) in
            favouriteAddress.accept(items?.favouriteAddress)
        }).disposed(by: rx.disposeBag)
        
        
        input.getCitiesTrigger.flatMapLatest { () -> Observable<CityListModel?> in
            return self.getAllCities()
        }.subscribe(onNext: { (items) in
            elements.accept(items?.cities ?? [])
        }).disposed(by: rx.disposeBag)
```


```
    private func getAllCities()-> Observable<CityListModel?> {
        
        guard let provider = self.dependencie.api as? MotoXpressUserAPI else {
            return Observable.just(nil)
        }
        print(HomeViewModel.getCityListParam())
        let request = provider.getAllCities(param: HomeViewModel.getCityListParam())
        return request
            .take(1)
            .trackError(self.error)
            .trackActivity(self.loading)
            .catchErrorJustComplete()
    }
    
    private func getAllFavouriteAddress()-> Observable<FavouriteAddressResponseModel?> {
        
        guard let provider = self.dependencie.api as? MotoXpressUserAPI else {
            return Observable.just(nil)
        }
        print(HomeViewModel.getFavouriteAddressParam())
        let request = provider.getFavouriteUserAddress(param: HomeViewModel.getFavouriteAddressParam())
        return request
            .take(1)
            .trackError(self.error)
            .trackActivity(self.loading)
            .catchErrorJustComplete()
    }
```

Parameters:-
```
    private static func getCityListParam()-> [String: Any] {
        var param = [String: Any]()
        param["action"] = "cityList"
        return param
    }
    
    private static func getFavouriteAddressParam() -> [String: Any] {
        var param = [String: Any]()
        param["action"] = "FavouriteAddressListByUserid"
        param["userid"] = "xxxxx"
        return param
    }
```
when 1st Observable trigger i got  Observable<FavouriteAddressResponseModel?> this kind of result that and inside i got the favouriteAddress that is working fine.

but when 2nd Observable trigger i need Observable<CityListModel?> this response and inside this get cities
but i got 1st Observable json response and i didn't parse that response because expected json of this Observable<CityListModel?> type but got this type Observable<FavouriteAddressResponseModel?>.

in both observable i got same json response but my api and parameters are different.

did you understand my issue?

**Comment by sunshinejr** [comment]
not sure yet - can you provide your provider code, especially `getFavouriteUserAddress()` and `getAllCities()` code + how you initialize the provider?

**Comment by jaipee1** [comment]
[MotoXpressUserRx.zip](https://github.com/Moya/Moya/files/5365512/MotoXpressUserRx.zip)
@sunshinejr  this is the project please open the .xcworkspace and go inside the HomeViewModel.swift file and for provider initialization please check the networking folder 


![Simulator Screen Shot - iPhone 11 - 2020-10-12 at 19 22 44](https://user-images.githubusercontent.com/25658579/95754223-57218200-0cc0-11eb-914f-5772ebc8d635.png)
just for run i just directly call the HomeViewController when you click on Client login

**Comment by jaipee1** [comment]
@sunshinejr that is a demo project want to build in rxswift.

**Comment by jaipee1** [comment]
@sunshinejr  did you check the issue ?

**Comment by sunshinejr** [comment]
@jaipee1 yes, though it was not an easy task! Seems like a very big coincidence with how your API is constructed backend-wise and how the code was structured. TL;DR you used a functionality called `trackInflights` which would return the same response for similar requests, and given how your API is structured it acknowledged the three requests as basically the same (it compares the inner `URLRequests`). The quickfix is to turn off `trackInflights` (in your code it's in `Networking.swift:L40`), but we should probably investigate if we could fix that comparison to make sure this doesn't happen for other people. cc @Moya/contributors if anyone is interested in this!

**Comment by jaipee1** [comment]
Hi, @sunshinejr 
**Thanks for your solution & precious time.** 
i applied this change and its working. 
so basically this issue because of api structure not well as per your understanding?

**Comment by sunshinejr** [comment]
@jaipee1 even though it's a big coincidence, you actually found a bug in the `Endpoint` comparison. I created an issue for that (https://github.com/Moya/Moya/issues/2100) and hoping to get that fixed soon!

**Comment by jaipee1** [comment]
@sunshinejr ok thanks,  and yes its a big coincidence.

**Comment by sunshinejr** [comment]
@jaipee1 this is now fixed and should be soon released with new Moya 15 beta. Thanks again for reporting it!

**Comment by jaipee1** [comment]
@sunshinejr thanks and i just want to know whats did you do for resolving this issue little bit in details so i can understand it. 

Thanks in Advance

**Comment by sunshinejr** [comment]
@jaipee1 we improved `Endpoint` comparison, basically improving `Hashable` & `Equatable` implementations for them. Here's a detailed implementation: https://github.com/Moya/Moya/pull/2101/files#diff-cc9833a5f30ab09611494220339546c0e63b117358562f298f27d99700bf106b

**Comment by jaipee1** [comment]
@sunshinejr thanks & i really appreciate your work. 👍
