### ISSUE TITLE
How to handle same url with different http method?

### ISSUE THREAD

**Issue by syq7970** [Moya/Moya#2103]
My api is like:
GET: /user
POST: /user
DELETE: /user

but moya target enum can not use same name, how can I handle this api style without custom diffrent enum name?

**Comment by e5faf2** [comment]
Seems there is no other way. But I think it is even better to use different cases for enum in your case. It makes your API TargetType more easy to read.
```
enum UserAPI {
    case getUser
    case updateUser // (or createUser)
    case deleteUser
}
```

**Comment by sunshinejr** [comment]
Yeah, what @e5faf2 proposed is definitely something I'd recommend as well.

**Comment by syq7970** [comment]
Thx for help!
