### ISSUE TITLE
Moya ObjectMapper via SPM

### ISSUE THREAD

**Issue by TarekSalama** [Moya/Moya#2106]
I have been using Cocoapods in my project and I decided to switch to SPM.
It seems like Moya ObjectMapper is missing from SPM. Is there a reason it's not included?
Thanks in advance

**Comment by sunshinejr** [comment]
hey @TarekSalama - could you please create an issue on the [Moya-ObjectMapper repository](https://github.com/bmoliveira/Moya-ObjectMapper)? we kinda don't really work on the extension, so it would be best to contact people there - though I see that there is a Package.swift, maybe it's just not updated? Not sure.

**Comment by TarekSalama** [comment]
Oh I didn't know it was in a separate repo. Sorry for the trouble and thanks!
