### ISSUE TITLE
15.0.0-alpha.1 RxSwift Update

### ISSUE THREAD

**Issue by blinkmeoff** [Moya/Moya#2121]
Can u update RxSwift to 6.0 in SPM for 15.0.0-alpha.1 version?

**Comment by jdisho** [comment]
Does #2120 answer your question?

**Comment by HawinShark** [comment]
> Does #2120 answer your question?

it does not work when use cocoapod
what should I do next?

**Comment by HawinShark** [comment]
it does not work when use cocoapod
can u update it both

**Comment by HawinShark** [comment]
> it does not work when use cocoapod
> can u update it both

pod 'Moya/RxSwift', :git => 'https://github.com/peagasilva/Moya.git', :branch => 'rxswift-6'  # https://github.com/Moya/Moya
ummm, it worked

**Comment by ShenYj** [comment]
```
s.subspec "Core" do |ss|
    ss.source_files  = "Sources/Moya/", "Sources/Moya/Plugins/"
    `ss.dependency "Alamofire", "~> 5.0"`
    ss.framework  = "Foundation"
  end

  s.subspec "ReactiveSwift" do |ss|
    ss.source_files = "Sources/ReactiveMoya/"
    ss.dependency "Moya/Core"
    ss.dependency "ReactiveSwift", "~> 6.0"
  end

  s.subspec "RxSwift" do |ss|
    ss.source_files = "Sources/RxMoya/"
    ss.dependency "Moya/Core"
   ` ss.dependency "RxSwift", "~> 5.0"`
  end
```

It seems like to update the dependency lib?

**Comment by Jokemac** [comment]
Can u update RxSwift to 6.1.0 in SPM for 15.0.0-alpha.1 version?

**Comment by PierreBrisorgueil** [comment]
+1

**Comment by ageevvalentin** [comment]
When release it? RxSwift 6.0 released about 4 months ago.

**Comment by PierreBrisorgueil** [comment]
still relevant

**Comment by BasThomas** [comment]
Closing as per #2120
