### ISSUE TITLE
Update Moya to RxSwift 6.0

### ISSUE THREAD

**Issue by alexdcydia** [Moya/Moya#2144]
Currently, the latest RxSwift is 6.0 but Moya require RxSwift 5.0. Please update Moya using the latest RxSwift version.
Many Thanks.

**Comment by mithilesh-parmar** [comment]
My App Got rejected due to this. I'm using RxCocoa 5.0 which has UIWebview, Usage of UIWebView is resulting in rejection. So I updated the RxCocoa to 6.0.1 but then RxCocoa depends on RxSwift and currently RxSwift is 5.0. Please update the RxSwift Version. Im not able to upload the app

**Comment by tunds** [comment]
We seem to be having the same issue also with Carthage, would really appreciate if this could get update

**Comment by norbdev** [comment]
RxSwift 6.1.0
> MoyaProvider+Rx.swift:24:29: error: type 'Result<Response, Error>' has no member 'error'

**Comment by StateMachineJunkie** [comment]
Yeah, I'm dead in the water with Xcode 12.5 and Moya not supporting RxSwift 6. I'm building with Carthage. Please update ASAP.

**Comment by vvit** [comment]
Yep, a PR is already prepared for that: https://github.com/Moya/Moya/pull/2150

**Comment by norbdev** [comment]
Any updates on this?

**Comment by ShenYj** [comment]
Now, We can use the development branch with Rx 6.2.

**Comment by BasThomas** [comment]
Closing as per #2120
