### ISSUE TITLE
update Quick, Nimble to latest version

### ISSUE THREAD

**Issue by makleso6** [Moya/Moya#2146]
Is it possible to update Quick, Nimble to latest version?

**Comment by norbdev** [comment]
+1

**Comment by BasThomas** [comment]
Closing as per #2155

**Comment by makleso6** [comment]
@BasThomas hi, I see that Package.swift was not updated)

**Comment by BasThomas** [comment]
Ah, you're right! Nimble is still at 8.0.0 there. Do you want to open a pull request? :)
