### ISSUE TITLE
Use isEmpty to check whether the data is empty instead of count

### ISSUE THREAD

**Issue by jolyot** [Moya/Moya#2152]
First, thank you for the awesome product！
Moya enables me to handle the network layer more easily than before.

Now my proposal is simple. 
As the title says, you should use `isEmpty` instead of `count` to check whether the data is empty.

Here is my code:
```swift
if data.isEmpty && !failsOnEmptyData
```

The following links are the corresponding codes.
https://github.com/Moya/Moya/blob/e4b331474bdb6e9637f3e574fcde473170070d17/Sources/Moya/Response.swift#L103

https://github.com/Moya/Moya/blob/e4b331474bdb6e9637f3e574fcde473170070d17/Sources/Moya/Response.swift#L176

**Comment by BasThomas** [comment]
Do you want to open a pull request for this? :)
