### ISSUE TITLE
Is Moya still under active development?

### ISSUE THREAD

**Issue by raphaelcruzeiro** [Moya/Moya#2168]
Hello to whoever is still maintaining this package!

First of all, I would like to thank you for your effort as Moya is used in quite a few apps that I maintain. I couldn't help but to notice though that the project seems a bit stale, issues and PRs are piling up and this project has a few easily fixable issues that were not solved in over 6 months (though the PRs are there).

On the README file, user "Project status", the project is listed as under "active development" with the claim that it's being actively used by Artsy. However, to the best of my knowledge, Artsy made the switch to React Native back in 2016 and I have also noticed that the main contributors are not as active anymore.  So it begs the question: is Moya still under active development or is it now under life support? Is the project looking for new contributors and/or maintainers or perhaps someone willing to fork it and have it live on as a new package?

**Comment by raphaelcruzeiro** [comment]
Hey @AndrewSB, I see that you are the most recently active contributor to Moya. Would it be fair to assume that this project is now under life support?

**Comment by AndrewSB** [comment]
hey! sorry for missing this. 
yes, I'd say so. there are no new features planned anytime soon.

if anyone wants to take charge and lead some fixes or new features, I can take a look at them, and help with questions, but unfortunately I don't have more than an hour or so a month to help maintain the project right now

**Comment by raphaelcruzeiro** [comment]
Hey @AndrewSB 

Thank you for responding.

So Moya is still an important piece of software for me and for others. I myself have 3 apps that depend on it and I believe that the biggest hurdle right now is that RxSwift has had a major version update and Moya has a trnasitive dependency to RxSwift 5. I have a [PR open](https://github.com/Moya/Moya/pull/2155) that updates that dependency to RxSwift 6.X.X, but I believe that I might be a better approach to completely remove both RxSwift and ReactiveCocoa from the project and create separate reactive extensions so that Moya doesn't need to be updated every time either of these frameworks has a major version change (even if people themselves have to write these reactive extensions, this is trivial work).

Since I rely on Moya a lot and I really like how it creates a neat interface for network calls, I've been thinking a lot about its future and maybe even volunteering to become a maintainer, but doe to the sheer size of of the project I don't think I would have enough bandwidth to deal with it. This is when it hit me: Moya is quite massive. It's a massive abstraction built on top on another massive abstraction which is Alamofire. I understand that this made a lot of sense when Moya was created at Artsy at around 2015. Artsy was probably already using Alamofire and relying on stuff such as certificate pinning (and the URLSession APIs weren't as competent as they are today). This is when I got the idea: what if I were to write a library based on Moya's interface (with a few adjustments based on what I think it could be after years of usage) and drop the Alamofire dependency which is, IMO, unnecessary in 2021. I have actually started work on this library and it's already working quite well on a project of mine which does all sorts of requests (plain, encodable, multipart, file upload) and it also handles stuff such as authentication methods (including refresh tokens). Now this library will not be ready for third-party usage for some time as I am still working on it as things are still prone to change as I make my mind on how to better do some things in 2021, so Moya is and will still be the first option for many apps out there.

What I propose here is: we do whatever is necessary to merge the RxSwift PR into main (this shall give Moya perhaps another year or so) and update the README to reflect the fact that the project is now under life support and that replacement libraries are not only encouraged but some are already being developed.

What do you think?

**Comment by AndrewSB** [comment]
I also still use Moya for the app that I work on. luckily, I don't use RxSwift or ReactiveSwift any longer so it feels less precarious to me.

That sounds like a good plan to me. I tried to fix CI in https://github.com/Moya/Moya/pull/2159, but I haven't had the time to finish fixing it.

Are you using your RxSwift PR? It seems safe enough to merge into `development` & have people target that branch

**Comment by raphaelcruzeiro** [comment]
@AndrewSB yes, I am using that PR for a while now and it's safe. It basically just replaces the deprecated RxSwift methods with the newer ones and bumps the dependency major version on the Podspec.

**Comment by raphaelcruzeiro** [comment]
>There have been a number of conversations about removing Moya's dependency on Alamofire, I've always thought it was a great idea. The core network abstraction is useful by itself

I think removing that dependency is a great idea but I might be wrong and might yet to stumble on something  big that Alamofire easily solves. Let's see how my little experiment goes. So far, the only thing I noticed is that with one less layer of abstraction, debugging network calls gets way easier.

**Comment by AndrewSB** [comment]
sounds good, if you're able to get something that works, we'll likely leave it on a long-running branch for quite a while. It may not be wise to ship that large a breaking change to a release, or the `master` branch.

I could see another repository under the Moya org that we could use to stage a lighter Moya

**Comment by AndrewSB** [comment]
could you update your PR to target development? we can merge it in there now in that case

**Comment by raphaelcruzeiro** [comment]
@AndrewSB done  ;)

**Comment by BasThomas** [comment]
Now that I can do some open source again, I'm giving Moya some love by making sure we can keep its build succeeding and making sure we can update dependencies. Thanks for reaching out to us, @raphaelcruzeiro — I'm going to close this issue for now given where we're at now. :)
