### ISSUE TITLE
CocoaPods could not find compatible versions for pod "RxSwift" #2021

### ISSUE THREAD

**Issue by Marcoliucc** [Moya/Moya#2169]
[!] CocoaPods could not find compatible versions for pod "RxSwift":
  In Podfile:
    Moya/RxSwift (~> 14.0) was resolved to 14.0.0, which depends on
      RxSwift (~> 5.0)

    RxCocoa (= 6.2.0) was resolved to 6.2.0, which depends on
      RxSwift (= 6.2.0)

**Comment by raphaelcruzeiro** [comment]
Try using the branch from this PR https://github.com/Moya/Moya/pull/2155

**Comment by AndrewSB** [comment]
thanks to @raphaelcruzeiro, this has been merged in to develop! you should be able to target that branch in your Podfile and have this resolve 😄
