### ISSUE TITLE
Xcode 6.4 Swift compilation error?

### ISSUE THREAD

**Issue by nmtitov** [Moya/Moya#217]
Hello again, sorry for disturbing you second time today. I launched Demo in Xcode 6.4 while I was playing with #216 and got Swift compilation error (code from master branch).

Could you please take a look at this gist ? https://gist.github.com/nmtitov/154cd1738a517065593c Looks like toolchain is not set up? But `xcode-select -p` shows correct path.

**Comment by ashfurrow** [comment]
Hi there! No problem at all :) The Demo project on the current master requires Xcode 7 GM. For Xcode 6.4, you can check out the project in the [last release](https://github.com/Moya/Moya/tree/2.1.0). 

Note that the Demo project on master is currently not able to run an app, just unit tests. I'm working on fixing that in #215.

**Comment by nmtitov** [comment]
Oh, I see. Thank you!

**Comment by sauravambastha** [comment]
Hi, i am trying to run Xcode for mac app. No code nothing but still it gives errors . I am using Xcode 6.4.  why ?
Steps i am doing are : open Xcode , select OS X - application- cocoa application, and language swift. errors are with objective c as well. Why so ?

**Comment by petester42** [comment]
The first thing would be that this library requires Xcode 7.1 and the second would be that there are issues with the Mac target if you are not using cocoapods. There is a fix here #283 but we still have some problems.
