### ISSUE TITLE
Simple url request

### ISSUE THREAD

**Issue by cskristof** [Moya/Moya#2172]
I was looking for a simple endpoint call, so after i haven't found anything online that doesn't involve string splitting, done a bit of digging in the source code and came to the conclusion that while `Endpoint` looked the best for what i wanted to do, `TargetType` is so strongly embedded that it cannot be skipped. Considering all this i made a custom `TargetType` and `MoyaProvider` to prevent the splitting of the url.

I am curious if anyone knows a better solution?

```swift
import Moya

class SimpleMoyaProvider: MoyaProvider<SimpleTargetType> {

    init(requestClosure: @escaping MoyaProvider<SimpleTargetType>.RequestClosure = MoyaProvider<Target>.defaultRequestMapping,
         stubClosure: @escaping MoyaProvider<SimpleTargetType>.StubClosure = MoyaProvider.neverStub,
         callbackQueue: DispatchQueue? = nil,
         session: Session = MoyaProvider<Target>.defaultAlamofireSession(),
         plugins: [PluginType] = [], 
         trackInflights: Bool = false) {

        super.init(endpointClosure: SimpleMoyaProvider.simpleEndpointMapping,
                   requestClosure: requestClosure,
                   stubClosure: stubClosure,
                   callbackQueue: callbackQueue,
                   session: session,
                   plugins: plugins,
                   trackInflights: trackInflights)
    }

    class func simpleEndpointMapping(for target: SimpleTargetType) -> Endpoint {
        return Endpoint(
            url: target.absolutePath,
            sampleResponseClosure: { .networkResponse(200, target.sampleData) },
            method: target.method,
            task: target.task,
            httpHeaderFields: target.headers
        )
    }
}
```

```swift
import Moya

class SimpleTargetType: TargetType {

    /// Replaces the split baseURL and path
    var absolutePath: String

    /// Shouldn't be used
    final var baseURL: URL {
        return URL(string: "https://neverShouldBeAccessed.com")!
    }

    /// Shouldn't be used
    final var path: String {
        return ""
    }

    var method: Moya.Method

    var sampleData: Data

    var task: Task

    var headers: [String : String]?

    init(_ url: String, method: Moya.Method = .get, sampleData: Data = Data(), task: Task = .requestPlain, headers: [String: String]? = nil) {
        self.absolutePath = url
        self.method = method
        self.sampleData = sampleData
        self.task = task
        self.headers = headers
    }
}
```
?

**Comment by xingda** [comment]
Thanks a lot!
Inspired by your code, I just simplified a little bit.
I didn't create a new TargetType and MoyaProvider, but just initialized a new provider with customized endpointClosure.
Then it's done.
following is my code sample:
```moya```
        let endpointClosure = { (target: Api) -> Endpoint in
            return Endpoint(url: url, sampleResponseClosure: {.networkResponse(200, Data())}, method: .get, task: .requestPlain, httpHeaderFields: apiHeader()) 
        //the url is the absolute URL stored image in server side.
       //apiHeader() is my func to generate common request headers, you can ignore it
        }
        let provider = MoyaProvider<Api>(endpointClosure: endpointClosure)
        // the above code is the magical sentence, with the new provider, it only calls the endpointClosure no matter which api called with following request, you can write any api instead of .loadImage(url).
        provider.request(.loadImage(url), completion: { result in
            switch result {
            case let .success(r):
                do {
                    onComplete(try Image(uiImage: r.mapImage()))
                } catch {
                    onComplete(Image(""))
                }
            case .failure(_):
                onComplete(Image(""))
            }
        })
```moya```

Good Luck and Thanks again.
BTW: another thread also helps me to make this work simple, but I guess you have read that.
FYI: https://moya.github.io/endpoints.html

**Comment by cskristof** [comment]
You're welcome. I am glad it helped.
Thanks for adding your version.
