### ISSUE TITLE
Danger failing on CI

### ISSUE THREAD

**Issue by ashfurrow** [Moya/Moya#2218]
I submitted [a PR](https://github.com/Moya/Moya/pull/2216) to update some docs and got [a build failure on CI](https://app.circleci.com/pipelines/github/Moya/Moya/289/workflows/bf31b5f5-01e8-49f7-b03c-5760f81965b3/jobs/4356): 

```
Cloning and building inline dependencies: import DangerSwiftProse // package: https://github.com/f-meloni/danger-swift-prose.git, import DangerXCodeSummary // package: https://github.com/f-meloni/danger-swift-xcodesummary.git, this might take some time.
Updating packages...
ERROR: failedToUpdatePackages("/Users/distiller/.danger-swift/Packages/")
```

It looks like this is affecting every PR. I'm looking into it now.

**Comment by f-meloni** [comment]
I've opened https://github.com/Moya/Moya/pull/2221, it seems working

**Comment by ashfurrow** [comment]
Confirmed on other PRs that this worked – thanks again!
