### ISSUE TITLE
Incompatible library

### ISSUE THREAD

**Issue by MarvinNazari** [Moya/Moya#222]
Hi, I'm getting this error with the latest version (using Carthage) and i have the latest Alamofire (2.0.0)

    dyld: Library not loaded: @rpath/Alamofire.framework/Alamofire
    Referenced from: /Users/X/Library/Developer/CoreSimulator/Devices/B3EC90B1-97EC-4E7B-B459-282565E65D17/data/Containers/Bundle/Application/7B3476BB-ECBF-4CB3-8D13-02D44AD934FE/X.app/Frameworks/Moya.framework/Moya
    Reason: Incompatible library version: Moya requires version 2.0.0 or later, but Alamofire provides version 1.0.0

**Comment by ashfurrow** [comment]
Hmm. What are the contents of your Cartfile?

Actually, I'm pretty new at diagnosing Carthage issues. @justinmakaila does this look familiar?

**Comment by MarvinNazari** [comment]
I think this is actually a issue with Cocoapods [check it](http://stackoverflow.com/a/31636313/2129504)

    github "ReactiveCocoa/ReactiveCocoa" ~> 4.0
    github "TransitApp/SVProgressHUD" ~> 1.1
    github "Moya/Moya" ~> 2.2.2
    github "robb/Cartography" ~> 0.6
    github "kishikawakatsumi/KeychainAccess" "swift-2.0"
    github "Hearst-DD/ObjectMapper"
    github "Alamofire/Alamofire" ~> 2.0
    github "tristanhimmelman/AlamofireObjectMapper" ~> 0.8
    github "onevcat/Kingfisher" ~> 1.5

**Comment by ashfurrow** [comment]
@MarvinNazari could you clarify? I built the release of Moya with a version of CocoaPods _newer_ than 0.38.2. 

Again, not terribly familiar with Carthage (we _just_ added support) – what happens if you remove the `Alamofire` and `ReactiveCocoa` lines from your Cartfile, out of curiosity? And just have `Moya` and let Carthage bring in the dependencies for you?

**Comment by MarvinNazari** [comment]
Not sure if its CocoaPods issue, but it didn't work when i removed `Alamofire`  and  `ReactiveCocoa ` from Cartfile

**Comment by justinmakaila** [comment]
@ashfurrow @MarvinNazari you shouldn't have to specify `Moya`'s dependencies in your Cartfile, unless you also have a specific dependency on it. 

The initial error looks like you missed adding the `copy-frameworks` script. Check out [step 4](https://github.com/Carthage/Carthage/blob/master/README.md#if-youre-building-for-ios) in the "Getting Started" section of the `README`.

**Comment by MarvinNazari** [comment]
@justinmakaila I have the `copy-frameworks` script and all the library works except Moya, i removed the `Alamofire` from Cartfile too, but no luck.

**Comment by justinmakaila** [comment]
@MarvinNazari Can you post your updated Cartfile real quick?

**Comment by MarvinNazari** [comment]
github "ReactiveCocoa/ReactiveCocoa" ~> 4.0
    github "TransitApp/SVProgressHUD" ~> 1.1
    github "robb/Cartography" ~> 0.6
    github "Moya/Moya" ~> 2.2.2
    github "kishikawakatsumi/KeychainAccess" "swift-2.0"
    github "Hearst-DD/ObjectMapper"
    github "tristanhimmelman/AlamofireObjectMapper" ~> 0.8
    github "onevcat/Kingfisher" ~> 1.5
    github "MarvinNazari/ICSPullToRefresh.Swift" "master"
    github "raulriera/TextFieldEffects" ~> 0.4.2

**Comment by justinmakaila** [comment]
@MarvinNazari Are you building for Xcode 7 and Swift 2?

**Comment by MarvinNazari** [comment]
Yes.

**Comment by justinmakaila** [comment]
Ah, I'm afraid I can't be of much help right now, I need to install the Xcode 7 GM. Let me get that download started, and I'll report back here if I find anything.

@Moya/contributors: Can anyone step in?

**Comment by MarvinNazari** [comment]
Xcode 7 is coming very soon so just wait for that (https://developer.apple.com/xcode/download/)

**Comment by justinmakaila** [comment]
;) I've been checking the Software update section on my phone every half hour all day.



—Justin Makaila

**Comment by MarvinNazari** [comment]
Xcode 7 is actually out at MAS. :)

**Comment by justinmakaila** [comment]
Ok, all installed. Beginning triage!

**Comment by floskel** [comment]
Any news on this. I've started seeing the error as well. No luck yet.

**Comment by skywinder** [comment]
The same issue with my projects. I believe it's not related with Moya..
https://github.com/Alamofire/Alamofire/issues/55

**Comment by justinmakaila** [comment]
Using the latest of Carthage and RAC 4.0, I built just fine 



—Justin Makaila

**Comment by MarvinNazari** [comment]
it builds fine! when u run the app it crashes!

**Comment by petester42** [comment]
The problem is that ReactiveCocoa doesn't set it's version or compatibility version so it is just one. They use carthage to manage the version so it doesn't matter what the version is in the Xcode project. On the other hand, cocoapods does set it the compatibility version to 4 when building ReactiveCocoa which results in a conflict. You could manually set the compatibility version for all the pods in the `Carthage.xcodeproj` to 1. That should fix the issues. Not really a fix but should work.

**Comment by Alexey-Matjuk** [comment]
@petester42 thanks, changing *compatibility version* to 1 helped

**Comment by petester42** [comment]
Pretty sure the work from #267 closes this issue.
