### ISSUE TITLE
Help wanted with endpointsClosure

### ISSUE THREAD

**Issue by MarvinNazari** [Moya/Moya#223]
Im so sorry i ask this question here! but i didn't get any answer in Stackoverflow here is my problem

     let authorizationEndpointsClosure = { (target: LokaliiAuthorizationAPI) -> Endpoint<LokaliiAuthorizationAPI> in
    let url = target.baseURL.URLByAppendingPathComponent(target.path).absoluteString
    let endpoint = Endpoint<LokaliiAuthorizationAPI>(URL: url, sampleResponse: .Success(200, {target.sampleData}), method: target.method, parameters: target.parameters)
    switch target {
    case .TokenRequest,
         .SignUp,
         .SignInFB,
         .SignUpFB,
         .CreateProfile,
         .TokenRefresh:
        return endpoint
    default:
        MNAuthClient.sharedClient.validateLoginFirst { result in
            switch result {
            case .Success(let token):
                dispatch_async(dispatch_get_main_queue(), {
                    return endpoint.endpointByAddingHTTPHeaderFields(["Authorization": "Bearer \(token.accessToken)"])
                })
            case .Failure(let error):
                dispatch_async(dispatch_get_main_queue(), {
                    return endpoint
                })
            }
        }
    }
    } 

in .default: i need to return the authorization header but i need to check if i need to refresh the token, how can i fix this? again sorry i asked here

**Comment by ashfurrow** [comment]
Hey! Don't worry about asking a question on the repo, that's exactly the right thing to do :smile_cat: 

There's no first-class support for this kind of authentication-if-required behaviour. Moya abstracts network calls away, not your authentication. This is a limitation that's recently come up as a request by others, and we're planning on adding support to Moya: #209. 

I had a similar problem on an app I wrote using Moya. [My solution](https://github.com/artsy/eidolon/blob/e4a92cd40b789099297d4d49d5489efc64286269/Kiosk/App/Networking/XAppAuthentication.swift#L8-L26) uses the ReactiveCocoa extensions. Basically I filter all my API calls through one method. It returns a signal (kind of like a promise). The signal represents all the network stuff that has to happen to retrieve the `target`. So first it checks if it needs to re-authenticate, and includes that work in the signal it returns. 

If using the ReactiveCocoa or RxSwift extensions is something you're open to, I'd be happy to provide more details on what that might look like.

**Comment by MarvinNazari** [comment]
Thanks! Yeah i use ReactiveCocoa would be great if u could provide more details on that :)

**Comment by ashfurrow** [comment]
Sure! So, we're still using the RAC 2 API :cry: but the principles are the same. 

Here's a simplified version of our approach:

```swift
func XAppRequest(token: ArtsyAPI) -> RACSignal {
    // This is just us looking for our auth tokens, which also expire.
    var appToken = XAppToken(defaults: NSUserDefaults.standardUserDefaults)

    // This is a signal that represents a request to update our auth token, *if* we have to. Nothing will be done unless we include this signal in our return value.
    let newTokenSignal = Provider.sharedProvider.request(ArtsyAPI.XApp).filterSuccessfulStatusCodes().mapJSON().doNext({ (response) -> Void in
        if let dictionary = response as? NSDictionary {
            let formatter = ISO8601DateFormatter()
            appToken.token = dictionary["xapp_token"] as? String
            appToken.expiry = formatter.dateFromString(dictionary["expires_in"] as? String)
        }
    }).logError().ignoreValues()

    // Signal that returns whether our current auth token is valid
    let validTokenSignal = RACSignal.`return`(appToken.isValid)

    // If the token is valid, just return an empty signal, otherwise return a signal that fetches new tokens.
    // After whichever of those completes, _then_ we attach our actual API-requesting signal.
    return RACSignal.`if`(validTokenSignal, then: RACSignal.empty(), `else`: newTokenSignal).then {
        return provider.request(token)
    }
}
```

I've written some comments inline – let me know if I can clarify anything!

**Comment by MarvinNazari** [comment]
Just the last question, any idea how i can accomplish 

    then {
        return provider.request(token)
    }
 in ReactiveCocoa v3?

**Comment by MarvinNazari** [comment]
Ah Amazing! thanks. :heart:
