### ISSUE TITLE
`Task` conflicts with `_Concurrency.Task`

### ISSUE THREAD

**Issue by cheungbo-mong** [Moya/Moya#2247]

**Comment by jeremiahk** [comment]
This has been fixed by [Feature add AsyncMoya](https://github.com/Moya/Moya/pull/2233).

**Comment by jbehrens94** [comment]
@BasThomas Any idea when this will be released? :)

**Comment by jbehrens94** [comment]
@BasThomas @AndrewSB Any idea?

**Comment by ijunfly** [comment]
Is there any progress?

**Comment by ImaginativeShohag** [comment]
It's been 2years. 😒

**Comment by AndrewSB** [comment]
as a workaround, please use `Moya.Task`, or add a typealias like `typealias MoyaTask = Moya.Task`
