### ISSUE TITLE
Make parameters optional

### ISSUE THREAD

**Issue by ashfurrow** [Moya/Moya#226]
Alamofire treats them as optional and behaves differently if they are `nil`, so we should allow optionals, too (I guess some servers differentiate between an empty HTTP body and a `nil` one).

Continued from #188.

**Comment by luigidimuzio** [comment]
It looks like the Endpoint main initializer still requires them as a non-optional

**Comment by ashfurrow** [comment]
This is fixed by https://github.com/Moya/Moya/pull/228 – will be merged in an upcoming release (see #236).
