### ISSUE TITLE
Minor release soon? SPM warnings are solved :)

### ISSUE THREAD

**Issue by nacho4d** [Moya/Moya#2267]
Hi, I saw that SPM warnings have been solved. Could we have a minor release soon?

15.0.1 ?

This warning 
<img width="1196" alt="Screen Shot 2022-07-25 at 10 29 20" src="https://user-images.githubusercontent.com/111651/180676294-df8aa061-3b0a-4d20-8820-12eab45fd7f1.png">

Was fixed [here](https://github.com/Moya/Moya/commit/39a907820e39e1132e4df67207a6b728e849aebb) just a bit after last release. Which was various months ago.

**Comment by AndrewSB** [comment]
hey @nacho4d, just pushed a new release for you!

**Comment by nacho4d** [comment]
BRAVO!!!!!!
