### ISSUE TITLE
Compiling for iOS 10.0, but module 'Alamofire' has a minimum deployment target of iOS 11.0

### ISSUE THREAD

**Issue by mibawo** [Moya/Moya#2310]
Hi, our project depends on SuperAwesome pod and recently the builds started failing because Moya is targeting iOS 10, but the Alamofire dependency have bumped their iOS minimum target to 11 so we get this error:
```
Compiling for iOS 10.0, but module 'Alamofire' has a minimum deployment target of iOS 11.0: /Users/[...]/Alamofire/Alamofire.framework/Modules/Alamofire.swiftmodule/arm64-apple-ios.swiftmodule
```

This is a Moya 14.0 dependency issue and needs to either target Alamofire 5.6.X, or update the minimum iOS version.

**Comment by jshier** [comment]
5.7.1 should be out now (depending on CocoaPods' deployment speed), so this should be resolved.

**Comment by DevSean** [comment]
I can confirm this issue has been resolved.

**Comment by mibawo** [comment]
Working for me as well. Thanks @jshier.
