### ISSUE TITLE
Is Moya Active?

### ISSUE THREAD

**Issue by learnwithgabbar** [Moya/Moya#2357]
The last release was on 2022, is moya active and maintain?

**Comment by aiKrice** [comment]
ping @ashfurrow

**Comment by aiKrice** [comment]
ping @AndrewSB

**Comment by ashfurrow** [comment]
Is it active? What does “active” mean? Pull requests are getting reviewed and merged. There are dozens of maintainers with push access. Is that active? 

Moya is ten years old; more important than active at this point IMO is that it is maintained. Adding new features for the sake of it doesn’t help the project, and neither does endless code churn. 

Moya is better than active, it is done. 

If there is a specific need (eg: critical PR review) and no one is answering, pinging maintainers is appropriate. But if the question is “will maintainers stir if I poke them?”, then that’s not a good question IMO.
