### ISSUE TITLE
Release 3.0.0

### ISSUE THREAD

**Issue by ashfurrow** [Moya/Moya#236]
Once #228 is merged.

Unless there's anything showstopping we need in? I was hoping to get #144 in, but haven't got a plan on that yet :sweat:

**Comment by ashfurrow** [comment]
Waiting (possibly) on #144.

**Comment by aschuch** [comment]
I'd like to introduce #238 in 3.0.0 as well. :tada:

**Comment by ashfurrow** [comment]
Agreed. 

--
Ash Furrow
iOS Developer, Author
http://ashfurrow.com

**Comment by ashfurrow** [comment]
Just gonna tidy up the docs around plugins, and we should be good to go on this.

**Comment by ashfurrow** [comment]
Fixed in https://github.com/Moya/Moya/commit/d61003dd3c5e4bea18d69622a9038daa0aae7064 and pushed to CocoaPods trunk: https://raw.githubusercontent.com/CocoaPods/Specs/9186a2cd0f90f5cc20fa56d8a01f93bdeb1480a0/Specs/Moya/3.0.0/Moya.podspec.json
