### ISSUE TITLE
Update podspec to support tvOS

### ISSUE THREAD

**Issue by gregpardo** [Moya/Moya#241]
A lot of pods are being updated to support tvOS and the latest RxSwift development branch has been updated as well. Unfortunately I investigated and found that you can't use specific branches in the podspec dependencies due to versioning issues so we might have to wait for the dependencies to work these changes into a tag. This library is a really great idea and I'd love to use it in a tvOS app I'm coding instead of manually wrapping Alamofire with RxSwift observables.

**Comment by esttorhe** [comment]
I think you can specify the specific branch of `RxSwift` on your `Podfile` with `tvOS` support and `CocoaPods` should be able to use the branch specified in the `Podfile` (as long as that doesn't break current implementation of `Moya`)

**Comment by gregpardo** [comment]
When I did that it said there was conflicts with Moya's dependencies. Also the Moya podspec only defines target of iOS.

**Comment by esttorhe** [comment]
¯\_(ツ)_/¯  sorry; i thought you were trying to use a «custom made» `.podspec`.

It shouldn't take too much to support `tvOS`. I'll try to get to it today.

**Comment by gregpardo** [comment]
Well I did try that too and such resulted in the dependency conflict with my own pods. Here was the pods I was using.

```
pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'tvOS'
pod 'RxSwift', :git => 'https://github.com/ReactiveX/RxSwift.git', :branch => 'develop'
pod 'RxCocoa', :git => 'https://github.com/ReactiveX/RxSwift.git', :branch => 'develop'
```

**Comment by ashfurrow** [comment]
Strange, our dependency on RxSwift is [~> 2.0.0-aplha-1](https://github.com/Moya/Moya/blob/a8a491bf14ab7ad4ce7793a204868fd05f03a4dd/Moya.podspec#L40). 

Esteban, it'd be great if you could do this – I'm travelling and don't have good access to internet. If you need push rights for CocoaPods trunk, let me know.

**Comment by esttorhe** [comment]
@ashfurrow I just updated the `.podspec` to use `2.0.0-alpha.4` which is the one with `tvOS` support.

Also added all supported «devices» like so:
```ruby
s.ios.deployment_target = '8.0'
s.osx.deployment_target = '10.9'
s.watchos.deployment_target = '2.0'
s.tvos.deployment_target = '9.0'
```

I can upload the `.podspec` but I can't push to trunk (I don't have push rights and the `pod spec lint` fails due to the dependency issue with `Alamofire`.

```ruby
Resolving dependencies of
 -> Moya (3.0.0)
    - ERROR | [tvOS] unknown: Encountered an unknown error (The platform of the target `Pods` (tvOS 9.0) is not compatible with `Alamofire (2.0.2)`, which does not support `tvos`.) during validation.

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 1 error.
```

We could have it living on a `tvOS` branch (the `.podspec`) while `Alamofire` merges that branch to `master` or makes an official release supporting it and people could use `Moya` for `tvOS` from our support branch.

**Comment by ashfurrow** [comment]
Sure – it surprises me a library as popular as Alamofire doesn't have tvOS support on trunk yet. Putting the podspec on a branch for now sounds like a good plan.

**Comment by gregpardo** [comment]
A branch would be great. Keeping it out of the main branch until all dependencies are updated solves the issue for me at least. Then I can just use Moya and get rid of all the other libraries! Thanks for looking into this everyone!

**Comment by esttorhe** [comment]
Branch [`tvOS`](https://github.com/Moya/Moya/tree/tvOS) should address this.

Please @gregpardo test it and let me know if something is not working.

PS. I also modified the `Podfile` to use this branch

**Comment by gregpardo** [comment]
In my Podfile

```
pod 'Moya/RxSwift', :git => 'https://github.com/Moya/Moya.git', :branch => 'tvOS'
```

I get this error on pod install

```
[!] The platform of the target `Snapshots TV` (tvOS 9.0) is not compatible with `Alamofire (3.0.0-beta.3)`, which does not support `tvos`.
```

**Comment by esttorhe** [comment]
Yeah; try to specify the `Podfile` like the `Demo` project in that branch => https://github.com/Moya/Moya/blob/tvOS/Demo/Podfile

Chances are you are missing this from the `Podfile`:
```ruby
# Fix for `Alamofire` with `tvOS` support
  pod 'Alamofire', :git => "https://github.com/Alamofire/Alamofire", :branch => "tvOS"
```

---
_Bear in mind this is temporarily until `Alamofire` moves `tvOS` support to the `master`/official branch/release_

**Comment by gregpardo** [comment]
Okay I was anxious to try it and I guess I didn't notice the Alamofire part. It's working now. Not sure if you guys want to close this out or leave open until these libraries catch up and this can be merged into master...

**Comment by esttorhe** [comment]
Added 2 labels to it.

I think leaving it open would be better so we can keep it in mind.

I'll :lock: the issue though since it doesn't make sense to keep it open.

If any @Moya/contributors has other idea as to how to handle this I'm open to ideas.


Thanks for confirming the fix @gregpardo :bow:

**Comment by esttorhe** [comment]
Just noticed that when we merge `tvOS` with `master` we'll be able to close #192 as well since the `.podspec` on that branch already handles `OSX`, `watchOS` and `tvOS` :tada:

**Comment by orta** [comment]
http://search.cocoapods.org/api/v1/pods.flat.ids.json?query=platform:tvos

tvOS support requires someone with the latest CP rc pushing, so it's got a pretty slow adoption ( plus my plugin undermines it somewhat )

**Comment by petester42** [comment]
Ok this will be a little more difficult than anticipated. Its seems like some pods have been pushed to trunk with a new version but without the tvos information. One example is Result. [Repo version](https://github.com/antitypical/Result/blob/master/Result.podspec) vs [trunk version](https://github.com/CocoaPods/Specs/blob/master/Specs/Result/0.6.0-beta.5/Result.podspec.json). The same goes for ReactiveCocoa as well.

**Comment by ashfurrow** [comment]
What an odd discrepancy. @Thomvis is there any reason the CocoaPods trunk version doesn't have TV support?

**Comment by ashfurrow** [comment]
We should see an updated version tomorrow :)

**Comment by ashfurrow** [comment]
Result has been updated on Trunk: https://github.com/CocoaPods/Specs/blob/master/Specs/Result/0.6.0-beta.6/Result.podspec.json @petester42 are there any other that need updating?

**Comment by ashfurrow** [comment]
Thanks to @Thomvis for his quick turnaround on that!

**Comment by petester42** [comment]
Yes. The ReactiveCocoa one needs updating too. There are two things wrong with it.

1. Doesn't specify tvOS when it should
2. OS X target version is 10.10 instead of the project's 10.9

**Comment by ashfurrow** [comment]
OK, I've updated the [ReactiveCocoa podspec](https://github.com/ashfurrow/ReactiveCocoa/blob/v4.0-alpha.3-podspec/ReactiveCocoa.podspec) on my fork (see: [changes](https://github.com/ashfurrow/ReactiveCocoa/commit/6e9fcdaeeb7710289b57979e2e9ad68b69a6ffb6).)

Unfortunately, I don't have 7.1 installed at the moment so I can't validate + push to trunk. Will do when I get to NYC.

**Comment by ashfurrow** [comment]
Oh, wait. Need to replicate `prepare_command` stuff.

**Comment by ashfurrow** [comment]
Cool, did that: https://github.com/ashfurrow/ReactiveCocoa/commit/7dc4d95df1dd3166fb4acef6498662f695e55721 Just need to lint + push.

**Comment by petester42** [comment]
looks good :+1:

**Comment by ashfurrow** [comment]
Opened https://github.com/ashfurrow/ReactiveCocoa/issues/4 to remind me

**Comment by ashfurrow** [comment]
Should be good to go – validated with Xcode 7.1 just in case, and it worked :+1: 

https://raw.githubusercontent.com/CocoaPods/Specs/a6b9eb7156e4809e43056cd54b6f754d98be6150/Specs/ReactiveCocoa/4.0.1-alpha-3/ReactiveCocoa.podspec.json

**Comment by ashfurrow** [comment]
Make that `4.0.2-alpha-3` – had a mistake in the podspec :grimacing: 

https://raw.githubusercontent.com/CocoaPods/Specs/112a7c37ff9e86ccb41c4e56a94ef55d7367658a/Specs/ReactiveCocoa/4.0.2-alpha-3/ReactiveCocoa.podspec.json
