### ISSUE TITLE
Support for setting body of request without passing parameters

### ISSUE THREAD

**Issue by gregpardo** [Moya/Moya#245]
So I've dug into this project and maybe I missed it but is there a way to set the body of the request without sending parameters. I took a look at Artsy's app and they basically have a lot of boilerplate like this. 

```
  case CreateUser(let email, let password,let phone,let postCode, let name):
            return [
                "email": email, "password": password,
                "phone": phone, "name": name,
                "location": [ "postal_code": postCode ]
            ]
```

So what I'm assuming here. And perhaps I'm wrong is that the parameters are converted to 'x-www-form-urlencoded' if the request is a .POST? Does this happen automatically or am I missing something?

Perhaps there is a way to extend this do allow sending an object and passing some sort of request encoding closure to Moya. 

I don't think the current setup is bad for small objects but imagine a complex JSON object body with nested array objects.

**Comment by ashfurrow** [comment]
I guess we haven't needed to set the request body directly. You can do that using the `requestClosure` if you associate a value with your enum case.

```swift
let requestClosure = { (endpoint: Endpoint<YourAPI>, done: NSURLRequest -> Void) in
    let request = endpoint.urlRequest // This is the request Moya generates
    switch endpoint {
    case NeedsBodySetDirectly(let jsonArrays):
        let newRequest = ... // modify request to set the request body to encoded jsonArrays
        done(newRequest)
    default:
        done(request)
    }
}
let provider = MoyaProvider(requestClosure: requestClosure)
```

Our goal is mainly to abstract that messy stuff away and only do the mapping to parameters or body once, instead of at every request. 

Let me know if I can clarify anything.

**Comment by gregpardo** [comment]
That makes sense. The only issue I had with this was that I could not include custom enum types in the parameters

```
public enum MyApi {
    case GetSomething
    case SendSomething(CustomObject)
}
```

However I suppose this may not be a good idea and maybe I should map my objects to [String: AnyObject] before sending them through the parameters instead?

**Comment by ashfurrow** [comment]
Is that a limitation of Swift's? As far as I know, you should be able to associate enums with custom types.

**Comment by gregpardo** [comment]
Apparently you can't if the object is marked as 'public'. I'm sure there's some sort of reason the compiler doesn't allow it. I'll just attempt to convert the object before hand and it should work fine for now. 

One thing to mention though is that on [Endpoint Documentation](https://github.com/Moya/Moya/blob/master/docs/Endpoints.md) it mentions that:

> Note that the endpointResolver is not intended to be used for any sort of application-level mapping. This closure is really about modifying properties specific to the NSURLRequest, or providing information to the request that cannot be known until that request is created, like cookies settings.

Is that supposed to say endpointClosure? Also it's kind of confusing wording at first glance. Maybe something like...

> This requestClosure is useful for modifying properties specific to the NSURLRequest or providing information to the request that cannot be known until that request is created, like cookies settings. Note that the endpointClosure mentioned above is not intended for this purpose or any request-specific application-level mapping.

**Comment by ashfurrow** [comment]
Ah yeah, thanks! We recently did a large rename and some of the documentation slipped throw :grimacing:
