### ISSUE TITLE
Carthage installs require explicit dependency listing

### ISSUE THREAD

**Issue by JRHeaton** [Moya/Moya#246]
Hi there. I've noticed that this library is set up to resolve its own dependencies via CocoaPods, but shares the Pod project's framework targets to be built as shared so that Carthage can see them. So far so good.

The "issue" is that when installing Moya via Carthage, if you were to simply list Moya itself as a dependency, it will not fetch for example, Alamofire, which is a mandatory dependency of Moya.

Thus, our app that uses Moya must have the following entries in the Cartfile (since we also use ReactiveMoya):
```
github "Alamofire/Alamofire" ~> 2.0.2
github "Moya/Moya"	 ~> 2.4.1
github "ReactiveCocoa/ReactiveCocoa" "swift2"
```

I think this can _possibly_ be remedied by including a Cartfile for Moya in the root of the repository that lists the dependencies. It won't need to be used obviously during development of Moya, but will provide a way for Carthage to know which deps to download + build. At the very least, I feel like this should be detailed in the README so that people don't have to debug this.

**Comment by gregpardo** [comment]
Erm realized I should have used ~> 2.0 on that instead... Grr

**Comment by JRHeaton** [comment]
I've also realized another fault due to Moya's project dependencies coming from the podspec. We are attempting to install Moya via Carthage with yesterday's Xcode beta, and using the `swift2` branch of ReactiveCocoa. Moya builds its own version of RAC that comes from its pod dependency on it. Because of this, and since it's an older version of RAC than we actually depend on, Carthage fails to build Moya's RAC w/ the beta command line tools.

**Comment by gregpardo** [comment]
I remember seeing talk about this in the Carthage issues tracker. If I remember correctly there is nothing like subspecs in Carthage so essentially ReactiveMoya and RxMoya need to be separated into their own repositories/frameworks I believe.

**Comment by JRHeaton** [comment]
Just brainstorming possible solutions here.

RXMoya, ReactiveMoya, and Moya could each have their own (shared) framework target inside of a dedicated xcodeproj (allowing carthage to build them), and then your subspecs could be kept to point to the same files still for people installing through pods. The demo project could install the library via either method (or both, with two targets).

**Comment by orta** [comment]
We've gone through all this before, and eventually found that this was the least-bad ways to support Carthage users without placing an unreasonable amount of extra work on people maintaining and improving Moya. We're not moving to separate repos and multiple xcodeprojects to keep up to date for a a file or two per sub-project.

The alamofire PR looks like a good idea

**Comment by JRHeaton** [comment]
@orta There isn't a need for multiple repos as I understand it.  It's just having one single standard project w/ the 3 framework targets, and a Demo project that installs/uses it locally. Theoretically the Demo target(s) could even be in the same project file as the framework targets I think. The only maintenance I see being needed there is adding/removing references to source files to the framework targets when files are created/deleted, whereas they are already (usually) automatically included via the podspec's source file patterns.

When installed via Carthage, that project's 3 targets would be built and made available, as well as the dependencies listed in the Cartfile as expected. When installed with Pods, the podspecs work as they do now, generating targets to build etc.

Our team is currently working on a framework we plan to make available via Carthage, and would be nice to make usable via pods as well. So I'm genuinely interested from an author perspective what you feel the burdensome work deriving from such changes could be. It could help us save some time in the future potentially also :)

**Comment by orta** [comment]
Most projects will "just work" with Carthage,which is why I made `pod lib create` work with it by default and it's likely that most libs that ship with support come from CP. Moya seems to have hit the point where it was too complex to do it that way. A lot of this is in https://github.com/Moya/Moya/pull/215- but I'm afraid I'm going to decline your request for more information, given my position on the CP team.

**Comment by JRHeaton** [comment]
I don't see how most will "just work" – factually, you are missing one single file at minimum that will _not at all disrupt your current setup_ (`Cartfile`) that is _required_ to have it checkout/build these frameworks, unless people want to use the ones Pods built (which requires going into the Pods build dir, rather than `Carthage/Build, and takes away dep version specification control from the depending target's Cartfile which is confusing to everyone). 
We ran into confusion at first when realizing Alamofire was missing when it's a direct dep of Moya, and then again when we adopted ReactiveMoya and ReactiveCocoa was missing. I can't quite see how maintaining a 2 line file is determined to be too much work; I think it could be at the very least a good compromise?

Otherwise, it reasonable to at least put proper usage instructions in the README? Saying use `github "Moya/Moya"` and that alone is gonna wind up with people going through the same aforementioned confusion, however brief (though this will be hard on beginner users of Carthage, which many are w/ it being new).

Also, not sure what's up with "declining request for information" (had a "whut" moment reading that actually) – not only was it a pretty innocent request for opinion based on experience of what the "extra" work on similar goals we have was (in attempts of just understanding why not to properly support Carthage), but also stated that you're not saying anything because you work on Pods? I didn't realize there was a "don't use that guy's tool" war going on :'( Saying "we don't wanna support X because our Y will be supported by more people" serves only to perpetuate that truth. I was not trying to overstep or pry for information that isn't public or is special sauce... My apologies if I did. I will look at the PR you linked to and try to deduce what the deterrent was.

I guess we will fork Moya in the mean time and update it to support the dependency and Xcode versions we need. Thanks for the replies guys.

**Comment by gregpardo** [comment]
The Cartfile is there now but I don't think it should include ReactiveMoya. Not all projects will need that dependency. Can't we just update the README to include instructions for setting up your personal Cartfile for all configurations: Moya, RxMoya, ReactiveMoya?

**Comment by esttorhe** [comment]
I agree with @gregpardo on this.

Like Orta stated already `Moya` grew to a «too complex» scenario where there's no «works for all» solution; I think supporting `Carthage` via the underlying `Pods` project works for *most* of the cases and having a more «detailed» installation instruction for `Carthage` on the `README` would satisfy those scenarios not covered by the `Pods` project.

**Comment by JRHeaton** [comment]
Updating the README w/ proper directions for Carthage is an understandable compromise. I think that is helpful from the perspective of someone using the library.

> The Cartfile is there now but I don't think it should include ReactiveMoya. Not all projects will need that dependency.
I think you mean `ReactiveCocoa`. While true, RAC is already built anyway when Carthage builds all 3 framework targets in the Pods project (there are no subspec-specific installs w/ Carthage), so would including it to build into `Carthage/Build` (as expected anyway – this will eliminate "hunting" for the build RAC result from Pods) be an actual issue?

**Comment by gregpardo** [comment]
So it looks like anyone using Carthage has to install Alamofire, Moya, ReactiveCocoa, RxSwift, ReactiveMoya, and RxMoya it seems. Is that correct?

**Comment by JRHeaton** [comment]
That is correct, those all need checked out and built, though not all will need integrated into the dependent target (Rx/RAC mutually exclusive in this case).

**Comment by gregpardo** [comment]
Okay so what's the downside if any of adding the other required install dependencies to the Cartfile?

**Comment by JRHeaton** [comment]
The only downside would be that for people installing Moya via Carthage with no intent to use the Reactive or Rx extensions will have to wait for Carthage to build its RxSwift and ReactiveCocoa checkouts. But this is sort of the nature of Carthage with there being no support for subspecs or any way to specify specific targets to build when checked out.
