### ISSUE TITLE
ReactiveMoya broken on 3.0.1 (Carthage install)

### ISSUE THREAD

**Issue by JRHeaton** [Moya/Moya#251]
I updated the version of `ReactiveMoya` I depend on from `2.x.x` to `3.0.1`. All frameworks previously worked as expected, and everything is being installed via Carthage.

The Moya-dependent code now fails to build, and when trying to view the generated module interface page in Xcode for `ReactiveMoya`, this is shown:
![](https://cldup.com/aYlLD0bpI1.png)

I've verified that this happens even in an empty iOS template project with `ReactiveMoya` + deps properly set to be linked and embedded. The normal `Moya` framework can be viewed as expected, so It's definitely isolated to `ReactiveMoya`. I am using the Xcode 7 GM to build everything.

**Comment by JRHeaton** [comment]
Update: The issue remains with the 7.0.1 Xcode. We are unable to use ReactiveMoya via Carthage, and unable to install ReactiveMoya(Moya/ReactiveCocoa) via CocoaPods if we want to also use Mantle(https://github.com/ReactiveCocoa/ReactiveCocoa/issues/2464), leaving us no good option for integration currently. 💔We'd very much like to be able to use Moya for our SDK.

**Comment by ashfurrow** [comment]
I'm sorry that you're having this problem :cry: I'm not sure how I can help – there's [work being done](https://github.com/CocoaPods/CocoaPods/issues/4376) to address the shortcoming in CocoaPods now. If you can, maybe ask there what can be done to help fix the issue?
