### ISSUE TITLE
NetworkActivityPlugin vs Moya.NetworkActivityClosure

### ISSUE THREAD

**Issue by vishvish** [Moya/Moya#252]
Great work all round, just trying to figure out how this change works when creating a `ReactiveCocoaMoyaProvider`.

Presumably,
`typealias OnlineSignalClosure = () -> RACSignal` won't work.

Porting the older code leads to:

    typealias OnlineSignalClosure = () -> RACSignal

    // Closure that returns a signal which completes once the app is online.
    let onlineSignal: OnlineSignalClosure

    init(endpointClosure: MyTarget -> Endpoint<MyTarget>, requestClosure: (Endpoint<MyTarget>, NSURLRequest -> Void) -> Void, plugins: [NetworkActivityPlugin<MyTarget>]) {
        // code
    }

But I can't figure out how to port the onlineSignal hooks.

**Comment by vishvish** [comment]
I guess I should ask if there's an updated version of the Artsy app :)

**Comment by ashfurrow** [comment]
Hey! Good question! The `onlineSignal` isn't a part of Moya, just our app. I actually just sent a PR changing the behaviour of the `onlineSignal` – maybe that would help answer your question? https://github.com/artsy/eidolon/pull/527

**Comment by vishvish** [comment]
Thanks @ashfurrow - appreciate the response. ReactiveCocoa is changing so quickly that when I tried the Artsy app to help me, it was clear that they've diverged somewhat! I'm still using Moya 2.2.0 as I can't get up to speed with the changes yet, but thanks for the software, it's pretty good stuff.
