### ISSUE TITLE
Enable request Cancelables to print AlamoFire debug curls 

### ISSUE THREAD

**Issue by nosrak113** [Moya/Moya#256]

**Comment by ashfurrow** [comment]
Hmm, neat idea! I don't see a downside to it, other that we'd be leaking out information that a developer could misuse... Doesn't seem like a big risk to me. We'll give it some time for anyone else to chime in and then whip this up!

@nosrak113 If you'd like, I can give next steps for how you could submit a pull request to add this feature. No pressure – just let me know if I can help!

**Comment by nosrak113** [comment]
#257
