### ISSUE TITLE
dyld: Library not loaded

### ISSUE THREAD

**Issue by istvanelekes** [Moya/Moya#258]
Incompatible library version: RxMoya requires version 2.0.0 or later, but RxSwift provides version 1.0.0

I have the latest RxSwift 2.0beta1, what should I do?

**Comment by ashfurrow** [comment]
How are you installing Moya? CocoaPods? What does your podfile look like? Xcode 7, right? Did a clean build produce a different error? 

--
Ash Furrow
iOS Developer, Author
http://ashfurrow.com

**Comment by istvanelekes** [comment]
Carthage

**Comment by bojan** [comment]
@ashfurrow I think that some of the fixes in f6a791398b47b4a982c91305d1bdd25533a52407 were somehow reverted in the later commits. I've tried recreating the Demo project with 0.39.0 (not b4) on 4.0.2, it builds and works just fine.

**Comment by ashfurrow** [comment]
Interesting! Could you send a pull request?

**Comment by bojan** [comment]
I'm already on it.

**Comment by bojan** [comment]
#261 should do it.

**Comment by ashfurrow** [comment]
Since #261 is merged, I'm going to close this. If it's still a problem, please re-open!
