### ISSUE TITLE
Contributing docs

### ISSUE THREAD

**Issue by ashfurrow** [Moya/Moya#270]
Adding/removing files specifically is fairly non-straightforward. /cc @JRHeaton

**Comment by ashfurrow** [comment]
We should also document a checklist of what makes a great PR (with the understanding that some people won't read it, and that's OK because we're all doing our best). Things like:

- A changelog entry (what is it, why does it matter, how do I make one?)
- Updated tests (if you add something new, it should be tested)
- Passing CI (what is CI?)

We should also consider automating some of this, maybe with [SwiftLint](https://github.com/realm/SwiftLint). Anyone have any experience with it?

**Comment by ashfurrow** [comment]
We should also formalize the fact that after a merged PR – even for documentation or whatever – contributors get push access to the repo. It's briefly mentioned in the readme, but we can do better. 

(We have turned on protection on the `master` branch so it can't be force-pushed to – there are no downsides to this policy imo.)

/cc @orta

**Comment by orta** [comment]
> We should also formalize the fact that after a merged PR – even for documentation or whatever – contributors get push access to the repo. It's briefly mentioned in the readme, but we can do better.

I'd like to see a separate repo for that so that we can call it the "Moya Community Onboarding" or something similar

**Comment by ashfurrow** [comment]
Great idea!
