### ISSUE TITLE
Redundant/superfluous SignalProducer in request()?

### ISSUE THREAD

**Issue by JRHeaton** [Moya/Moya#276]
Howdy. Please forgive me if I am wrong here. I've been working with the Swift version (v4) of ReactiveCocoa for a week or so.

I was reading this code: https://github.com/Moya/Moya/blob/3cd402cfddf2b361b6251de6d24214758ae54511/Source/ReactiveCocoa/Moya+ReactiveCocoa.swift#L20-L47

and it looks a lot like there's a redundancy. The outer producer, when started, starts the inner signal, and seemingly just pipes the events from inner -> outer, and links the inner disposable to dispose when the outer does. The outer producer seems superfluous.

As an experiment, I reduced it down to this:
```swift
public func request(token: Target) -> SignalProducer<MoyaResponse, NSError> {
    
    // Creates a producer that starts a request each time it's started.
    return SignalProducer { [weak self] observer, requestDisposable in
        
        let cancellableToken = self?.request(token) { data, statusCode, response, error in
            if let error = error {
                observer.sendFailed(error as NSError)
            } else {
                if let data = data {
                    observer.sendNext(MoyaResponse(statusCode: statusCode!, data: data, response: response))
                }
                observer.sendCompleted()
            }
        }
        
        requestDisposable.addDisposable {
            // Cancel the request
            cancellableToken?.cancel()
        }
    }
}
```

And it still works as-expected, and unit tests pass. So am I missing a specific reason or behavior of producers that requires it to be the first way in some specific scenario? If there is, please explain if you're willing, I'd love to understand and improve my RAC-fu 👊🤓. Otherwise, I will PR this.

**Comment by ashfurrow** [comment]
Interesting – I think it's likely a relic of when we were keeping track of inflight requests, and deduplicating new ones. I think @justinmakaila would be able to give a concrete answer about it.

**Comment by petester42** [comment]
Ya it is a relic from the inflight request days and not needed. The RxSwift version has this issue too.

**Comment by ashfurrow** [comment]
Coooool, @JRHeaton did you want to open a PR?

**Comment by JRHeaton** [comment]
Yes, will do. Thanks for verifying! :+1:

**Comment by ashfurrow** [comment]
Going to reopen this, as @petester42 pointed out the issue is in the RxSwift provider, too.
