### ISSUE TITLE
Manual integration instructions

### ISSUE THREAD

**Issue by dowhilenet** [Moya/Moya#287]
How to integrate `Moya` into my project manually. Thanks

**Comment by ashfurrow** [comment]
Hmm, this is a question that has not come up before. Generally, there's [no all-purpose solution](http://stackoverflow.com/questions/28131329/how-to-install-projects-without-cocoa-pods) to using a CocoaPods library without CocoaPods. If you must integrate normally, dragging in the Moya files in the `Source` directory should age good, but you'll need to remove RxSwift and ReactiveCocoa files if you aren't using them, also integrate Alamofire, and remove the `import Alamofire` statements from the Moya files. That _should_ do it – let me know if you run into issues.

**Comment by dowhilenet** [comment]
thanks. I download `Moya-4.4.0` to my project. dragging the `Moya.xcodeproj` to project  and remove `RxSwift` 、`ReactiveCocoa ` also remove the `import Alamofire` from the Moya files. Click on the + button under the "Embedded Binaries" section. add the `Moya.framework`.  Then have an error:

```
clang: error: no such file or directory: '/Users/xiaolei/Library/Developer/Xcode/DerivedData/WeatherQ-cvhqwncoeewmnxemtgteetjgepxd/Build/Products/Debug-iphonesimulator/Moya.framework/Moya'
```

**Comment by ashfurrow** [comment]
Instead of dragging in Xcode projects, try dragging in the individual swift files.

**Comment by petester42** [comment]
The reason the Xcode project won't work is because it relies on frameworks that aren't present in the folder. You need to run `carthage bootstrap` to get them. Other than that, just dragging the project should work. No need to delete anything.

**Comment by orta** [comment]
It might be worth doing what AFNetworking does and just not supporting manual installation, you need to have a lot of prerequisites set up for Moya, and the more useful interesting stuff can only really happen when you have a larger dependency graph, of which doing manually is just a waste of time.

**Comment by ashfurrow** [comment]
Agreed.

**Comment by dowhilenet** [comment]
Think you, I will try other methods.
