### ISSUE TITLE
MoyaError (formerly: ReactiveCocoa Error Type)

### ISSUE THREAD

**Issue by tomburns** [Moya/Moya#288]
I'm just getting started with Moya (and ReactiveCocoa, for that matter), but when using `request()`, `mapJSON()` etc to create a `SignalProducer` I find that I'm having to do a lot of mapping from the many underlying `NSError`s to a typed error enum in my code.

Is this something Moya could take care of by having an intermediate `ErrorType`, or is it best handled in my code? Personally I'd much rather see `request()` return something like `SignalProducer<MoyaResponse,MoyaError>` than `SignalProducer<MoyaResponse,NSError>`, but it's entirely possible I'm just holding it wrong :smile: 

Let me know either way; this seems like it'd make a decent first PR for me to tackle if you like the idea.

**Comment by tomburns** [comment]
I think this would cause the RAC4 support to diverge a bit from the legacy `RACSignal` interface, but I'm not sure that's a bad thing either.

**Comment by ashfurrow** [comment]
Cool, that approach sounds reasonable. @justinmakaila @petester42 do either of you have opinions about it? Whatever is more idiomatic for RAC 4. 

To be honest, I'd be OK with deprecating [`request()`](https://github.com/Moya/Moya/blob/136e3260e03a2d2e01ea6d9604e354ff3f9ed55d/Source/ReactiveCocoa/Moya%2BReactiveCocoa.swift#L39-L41) and shifting the responsibility to call `toRACSignal()` to the user. Thoughts?

**Comment by petester42** [comment]
Im not sure how `RACSignal` would work with an error other than `NSError`. I have never tried it. But other than that everything looks good.

**Comment by tomburns** [comment]
I believe anything that conforms to `ErrorType` can be bridged to an `NSError`, but honestly I don't know enough about the older `RACSignal` ReactiveCocoa interface to guarantee that'd work in this specific case.

**Comment by ashfurrow** [comment]
I think they'll just get an error like they do now, it's just it'll be an `NSError` cast from this new type instead of an `NSError` we construct presently. I like that change, but we'll need to bump Moya up a major version to adhere to [semantic versioning](http://semver.org) :checkered_flag:

**Comment by justinmakaila** [comment]
I think a custom error type is the way to go, because it gets rid of some guessing on the end-user side. I'm all for it

**Comment by tomburns** [comment]
#289 is nearly merged, so I'm moving conversation back here to continue discussing which associated value's we'd like to see on the newly minted `MoyaError` type.

Here's what we have currently:

```
public enum MoyaError: ErrorType {
    case ImageMapping(MoyaResponse)
    case JSONMapping(MoyaResponse)
    case StringMapping(MoyaResponse)
    case StatusCode(Int,MoyaResponse)
    case Data(MoyaResponse)
    case Underlying(ErrorType)
}
```

At the very least i think it might be helpful to add names to these tuples for clarity's sake; does anyone else have suggestions?

**Comment by petester42** [comment]
Names aren't needed. All the errors only have 1 thing which is easy to understand. If you absolutely wants names then `reponse` I guess.

**Comment by JRHeaton** [comment]
Gonna go ahead and close this since #289 is merged. Nice job on this again @tomburns
