### ISSUE TITLE
Send string in body of request

### ISSUE THREAD

**Issue by justinmakaila** [Moya/Moya#290]
Currently, with the way that the `MoyaTarget` protocol is written, there's no straightforward way to send a string as the body of the request (i.e. GraphQL query).

Any suggestions from the community?

cc: @Moya/contributors

**Comment by ashfurrow** [comment]
Hmm, this could be accomplished using the custom parameter encoding block, but I agree it's a bit awkward. Maybe we could look around ways to make it easier to use custom encoding (or including an implementation that works with GraphQL? Is Alamofire doing anything lime this?). Regardless, a good solution to this issue should include good documentation and maybe even an example project :cake:

**Comment by justinmakaila** [comment]
We want to be able to recreate this CURL functionality:
```bash
$ curl -XPOST -H 'Content-Type:application/graphql'  -d '{ count }' http://localhost:3000/graphql
```

As far as custom parameter encoding, I'm seeing something like this:
```Swift
// A GraphQL utility that I'm currently developing
import GraphQL

static let ApplicationBaseAPIURL = NSURL(string: "https://myDomain.com/")!

// The query for a user matching an ID
func userQuery(id: String) -> GraphQLNode {
  return GraphQLNode(name: "user", arguments: ["id": id], properties: [
    "id",
    "firstName",
    "lastName",
    "username",
    "email"
  ])
}

enum UserEndpoint: MoyaTarget {
  case GetUserByID(id: String)

  var baseURL: NSURL {
    return ApplicationBaseAPIURL
  }

  var path: String {
    return "graphql"
  }

  var method: Moya.Method {
    switch self {
      case GetUserByID(_):
        return .GET
    }
  }

  var parameters: [String: AnyObject]? {
    switch self {
      case GetUserByID(let id):
        return ["query": userQuery(id)]
    }
  }

  var sampleData: NSData {
    // Return sample data in the same shape specified by the query.
  }
}


let GraphQLProvider = ReactiveCocoaMoyaProvider(endpointClosure: { target in
    let graphQLParameterEncoding = Moya.ParameterEncoding.Custom { requestConvertible, parameters -> (NSMutableURLRequest, NSError?) in
        // A little pseudo cod never hurt... 
        let urlRequest = requestConvertible.URLRequest.mutableCopy()
        if let query = parameters["query"] as? GraphQLQueryType {
            urlRequest.body = query.description
        }
        
        return urlRequest
    }
    
    let graphQLEndpoint = Endpoint(
        URL: target.baseURL,
        sampleResponseClosure: {
            return .NetworkResponse(200, NSData())
        },
        method: target.method,
        parameters: target.parameters,
        parameterEncoding: graphQLParameterEncoding)
})
```
But I don't really like how we abstract away the requirement of there being a `GraphQLQueryType` available at the `query` key in the parameters dictionary.

We *could* change the `parameters` property of `MoyaTarget` to `AnyObject?`, and have `Endpoint` do some assertions to ensure that `parameters` is either an `Array`, `[NSObject: AnyObject]`, or `String`, which would allow us to supply the `GraphQLQueryType.description` to the `parameters`, but this is more of the same black-box functionality that I'd like to avoid.

**Comment by ashfurrow** [comment]
Agreed about the black-box functionality. Would making the `GraphQLQueryType` an associated value on the enum help? Not too much. Hmm. 

It could be a lot cleaner if the custom parameter encoding closure had access to the `endpoint` (or the target, I suppose). We only use that closure signature because we pass directly into Alamofire. If expanding it would help, that seems like a cool idea. 

I've not thought the issue through as much as you have – what sort of obstacles would that present?

**Comment by justinmakaila** [comment]
Could you elaborate a little bit on that idea?

I'm starting to think that it might be best to leave that on the end user's side, and have them use similar logic to what was outlined above. I can't think of a way to do it without breaking changes, and without making assumptions about what was intended.

**Comment by ashfurrow** [comment]
Hmm, yeah. I mean, I know GraphQL is getting more popular so I think we should consider first-party support at some point. But for now I'm fine leaving it up to the user. 

This is what I was thinking of, probably not a huge improvement.

```swift
let parameterEncodingEnpoint = { (target: GitHub, request: URLRequestConvertible, parameters: [String: AnyObject]?) -> (NSMutableURLRequest, NSError?) in
    // Instead of accessing the parameters dictionary to construct body,
    // You can access associated values of the target directly.
}
```

**Comment by swizzlr** [comment]
A protocol, "ParameterEncodable" might be a good plan. We could add conformance for dicts to keep previous behavior, and then allow further smarts by providing a "GraphQLNode" struct (or let the users define it as an optional third party extension to Moya, until such time as it's a huge demand).

**Comment by justinmakaila** [comment]
I have a GraphQL framework that I've been working on, in case anyone wants to contribute ;)



—Justin Makaila

**Comment by aamctustwo** [comment]
:+1: to the idea of a `ParameterEncodable` protocol.

**Comment by offbye** [comment]
How to  add post data in MoyaProvider subclass?  Is there a solution?

**Comment by thomasmarsh** [comment]
I have a similar issue. We have an S3 proxy endpoint where we would like to perform the equivalent of curl's `--data-binary` (i.e., setting the URLRequest body to a binary file) and can't send multipart form data. Is there a suggested idiomatic approach for this now, or some workaround (e.g., getting a mutable URLReqest)?

**Comment by ashfurrow** [comment]
@thomasmarsh I think that using the custom parameter encoding solution would be the easiest workaround. Let us know how it goes!

**Comment by thomasmarsh** [comment]
Ah, sorry, I'm new to all this and didn't understand what was happening the custom parameter encoding solution. I understand now and got it working. Thanks, @ashfurrow!

**Comment by ashfurrow** [comment]
@justinmakaila I've since used a GraphQL API, want to pick up the conversation on this? How did the framework go?

**Comment by fruitcoder** [comment]
Hey @ashfurrow! Do you use GraphQL in combination with Moya? Is there any update on how to make parameter encoding more generic? I'm very new to GraphQL and try to integrate [Apollo iOS](https://github.com/apollostack/apollo-ios) with how I use Moya and Alamofire to make network requests.

**Comment by ashfurrow** [comment]
I'm afraid that I haven't used GraphQL with Moya yet, if you find things non-obvious, I'd love to see a PR adding GraphQL to our documentation 🎉

**Comment by justinmakaila** [comment]
Dope, just realized that my email response never sent:

@ashfurrow I wrote a simple framework that provided typed interfaces for GraphQL structures. You could then use the `description` property to build the proper strings. I implemented this around Moya like so:

```swift
enum APITarget: TargetType {
    case graphOperation(GraphQLType, [String: Any])

    public var path: String {
        switch self {
            case .graphOperation:
                return "graphql"
            // ...
        }
    }

    public var method: Moya.Method {
        switch self {
        case .graphOperation:
            return .post
        default:
            return .get
        }
    }

    public var parameters: [String : Any]? {
        switch self {
        case let .graphOperation(operation, variables):
            return [
                "query": operation.description,
                "variables": variables
            ]
        // ...
        default:
            return nil
        }
    }

    public var task: Moya.Task {
            return .request
    }

    public var sampleData: Data {
        case let .graphOperation(operation, variables):
            // Your sample response based on the operation here
        // ...
        default:
            return Data()
    }
}
```

Turns out my initial issue with sending a raw string wasn't necessarily an issue with Moya, per se.

**Comment by justinmakaila** [comment]
@ashfurrow the framework went wonderfully for my use case, it's OS on my
profile.

I ended up just using standard JSON encoding to send queries/variables.

Not so familiar with Apollo though.

**Comment by BasThomas** [comment]
Seems like this has been resolved, please reopen if there's any other issues. :)
