### ISSUE TITLE
  ignoring import

### ISSUE THREAD

**Issue by dowhilenet** [Moya/Moya#292]
Hi,I use CocoaPods Installation `Moya`

xcode issue a warning:

`ViewController.swift` is part of module `Moya`;ignoring import

**Comment by ashfurrow** [comment]
That's odd – can you upload a project that demonstrates the error somewhere?

**Comment by dowhilenet** [comment]
I think this is a bug in Xcode. When I delete the project to re-establish this project, everything becomes normal.Thank you for your answer, then what is the problem I will initiate issue.

**Comment by ashfurrow** [comment]
:+1: Glad it worked out.
