### ISSUE TITLE
Change completion block type.

### ISSUE THREAD

**Issue by petester42** [Moya/Moya#293]
Since we are going to merge a breaking change with #289 I'd like to propose that we change the completion block type.

From
`public typealias Completion = (data: NSData?, statusCode: Int?, response: NSURLResponse?, error: ErrorType?) -> ()`

To
`public typealias Completion = (response: MoyaResponse?, error: ErrorType?) -> ()`

This would allow people that do not use the reactive extensions to be able to use the helpful mapping functions and simplify the integrating with various json parsing libraries.

What do people think?

**Comment by ashfurrow** [comment]
Great idea! Thoughts @Moya/contributors ?

**Comment by gregpardo** [comment]
On board with this. This is much simpler. I was kind of wondering why it was broken up into 3 values related to response.

**Comment by SRandazzo** [comment]
Like this a lot :+1:

**Comment by justinmakaila** [comment]
Into it

**Comment by esttorhe** [comment]
:100:

**Comment by tomburns** [comment]
This is a great idea :+1:

**Comment by jarrodrobins** [comment]
![giphy](https://cloud.githubusercontent.com/assets/1313663/11134697/e28bfeb6-89f2-11e5-8471-d781b4936e96.gif)

Sounds good to me. :+1:

**Comment by swizzlr** [comment]
I think this should definitely be included in version 5.

**Comment by petester42** [comment]
I've been playing with this idea a little bit and would like to suggest something a little different. How about the following:

`public typealias Completion = (result: () throws -> MoyaResponse) -> Void`

The advantage is that there is a clear distinction between the success and error paths. Which would look something like this:

```swift
GitHubProvider.request(.UserRepositories(username)) { result in
    do {
        let response = try result()
        print(response)
    } catch {
        print(error)
    }
}
```

**Comment by ashfurrow** [comment]
Hmm, super-interesting! I like it. Anyone else have feelpinions?

**Comment by swizzlr** [comment]
Well, I'd rather have a result type, because otherwise everyone's just going to be writing `let e = error as! MoyaError`, but what do I know checked exception bleh etc

**Comment by swizzlr** [comment]
I have a massive PR incoming btw that addresses this issue plus a bunch of other stuff; this approach is better than our strange disjoint union of optional types.

**Comment by JRHeaton** [comment]
> Well, I'd rather have a result type, because otherwise everyone's just going to be writing `let e = error as! MoyaError`

@swizzlr I agree with that, at least with Swift's current shortcomings when it comes to specifying throwable error types. Leaving our known error type declared as `ErrorType` in the completion block requires a cast back to `MoyaError` to work with. 

What about the original idea, but with the explicit error type:
`public typealias Completion = (response: MoyaResponse?, error: MoyaError?) -> ()`

That also aligns more closely with the RAC signal type for requests:
`public func request(token: Target) -> SignalProducer<MoyaResponse, MoyaError>`

**Comment by ashfurrow** [comment]
I'm not a fan of the double-optional parameters, just because there's this weird state where both are nil that no one is quite sure what to do about and mostly ignore it. A result type feels like a reasonable compromise.

**Comment by steam** [comment]
I like the idea of using a single result type. :+1:

**Comment by petester42** [comment]
I'm fine with a result type. I was going to go with a result type but I was trying to find way that we could remove the `Underlying` error from MoyaError. This would mean that we could have a clear distinction between our errors and cocoa errors. It would give the user a better indication of where things are going wrong.

So you could do something like this:
```swift
GitHubProvider.request(.UserRepositories(username)) { result in
    do {
        let response = try result()
        print(response)
    } catch let error as MoyaError {
        print("moya errors", error)
    } catch {
        print("other errors", error)
    }
}
```
