### ISSUE TITLE
Deprecate RAC2 support?

### ISSUE THREAD

**Issue by ashfurrow** [Moya/Moya#298]
Not insignificant time is being spent maintaining the RACSignal extensions, as well as the non-RAC3+ provider. We should consider officially marking these as deprecated for some time, before eventually removing them. 

Not sure if anyone else is using them or if its just me, and I won't be for much longer. Open for discussion!

**Comment by petester42** [comment]
I'm all for removing them. We could mark them as depreciated in the next major version and keep them in as long as RAC4 is still not final.

**Comment by ashfurrow** [comment]
Sounds like a plan!

**Comment by gregpardo** [comment]
+1. Out with the old in with the new.

**Comment by swizzlr** [comment]
Next action would be to add `@available(*, deprecated, message="This will be removed in the next major version of Moya. Please visit https://github.com/Moya/Moya/issues/298 for more information.")` to all relevant methods (I should think `request` overload).
