### ISSUE TITLE
[Discussion] Protected Branches

### ISSUE THREAD

**Issue by SRandazzo** [Moya/Moya#308]
Hey Moya Contributors (moyers?)

I believe only admins like @ashfurrow have access to the repo settings, so I aplogize in advance if it's already enabled as i'm unable to tell, BUT I wanted to field opinions on protected branches/status checks.

Here is the gist:
- By making master a "protected branch", we can enforce that no one can force push to it, preventing a potential flurry of git surgery/issues (which is what prompted me to do it on my own repo)
- More importantly, we can enforce that _any_ pull request to Moya must be passing certain status checks (CI + Unit Tests passing, either one, or all) before the pull request can be merged. 

One of the big questions I would want to pose to the community is `Would we ever want master to be in a failing state?`. My personal opinion is no, because if master is failing, and others begin branching and contributing back, now we all have broken tests :open_mouth:  

I have been using this on a private org repository with 6 other developers, and it has been working great! Pasting some screenshots from my private repo for reference:

Thanks! :tada: 

 
<img width="718" alt="screen shot 2015-11-16 at 5 44 58 pm" src="https://cloud.githubusercontent.com/assets/307819/11197332/d0b32288-8c8a-11e5-98d5-04c5ed32ee54.png">

<img width="703" alt="screen shot 2015-11-16 at 5 51 36 pm" src="https://cloud.githubusercontent.com/assets/307819/11197338/d4f8e616-8c8a-11e5-8f82-765f050eb30b.png">

**Comment by swizzlr** [comment]
Disabling force pushes: probably good.
Requiring status checks: probably good, but there are instances where discretion is required.

Then again, that discretion can be exercised by temporarily disabling the protection setting.

**Comment by ashfurrow** [comment]
Thanks for the great idea @SRandazzo! I turned on protection for master when we made Moya an organization, and even clarify(ish) this in the [contributor guidelines](https://github.com/Moya/contributors#when-should-you-use-push-access). Great minds :)

As far as CI passing, that's a trickier one. Sometimes we'll merge in broken tests because getting a PR merged is more important than getting the submitter to fix the tests (they're a first-time contributor and it's easier for me or someone to fix it after it's been merged). Also, we have intermittently-failing CI (see #259 ).

I think @swizzlr's "discretion"-based model is :+1:, and I want to give all the contributors a chance to use their own discretion. 

That's just my ¢2, if the community wants this then of course we'll enable it. Thanks again for the great suggestion!

**Comment by SRandazzo** [comment]
Glad to hear master is already ⚠️protected⚠️!!!

 Sorry to hear about the intermittent CI failures, those are always fun :grimacing: 

You have a great point that getting a PR merged may be more important than passing tests. I'm coming from an app-based repository mindset with bi-weekly releases, so pretty different :fish: here. 
I think that with the right kind of friendly community (which Moya has!) either approach can work, and barring the intermittent failure issue, it could get people more involved and focused on testing, with other contributors pitching in to help people out with tests!

If it weren't for those intermittent failures, I would propose an experiment to try it out, but we should figure those failures out first! I'll do a little bit of researching on that issue 

Thanks again @swizzlr @ashfurrow :tada:

**Comment by ashfurrow** [comment]
> If it weren't for those intermittent failures, I would propose an experiment to try it out

Agreed! Definitely worth a shot. Do you think it's worthwhile to keep this issue open for more discussion? Let me know if I can help answer questions about CI :boat:

**Comment by SRandazzo** [comment]
Awesome, possible fix for the failures is merged!

We should probably wait a couple days, see if they resolve, then pick back up here. If we do want to try this idea out, we could use this issue as a tracker/retro on how we think the process went, and if we want to revert the change or not! Good way to keep track of on an on-going experiment :hammer: 

Maybe like a 1 month trial run of it, open to suggestions!

**Comment by ashfurrow** [comment]
We're still pretty consistently getting CI failures, which sucks. I heard a rumour Circle might have a feature soon to restart builds failed with the infamous "Error 65", we'll see. 

In any case, we now have Danger on the repo's pull requests, and sometimes we do need to override. I really liked the discussion here, but I think we've settled into a groove with the somewhat protected branches. Thanks again for sparking a good discussion!
