### ISSUE TITLE
Build failures in RAC/Rx framework targets due to prefix-less type names

### ISSUE THREAD

**Issue by JRHeaton** [Moya/Moya#313]
Hi guys. Today I pulled master and tried building all targets on all platforms in the project, to make sure all was gooby. I noticed that ReactiveMoya and RxMoya targets have incurred some errors as a result of the prefix-less type name changes. 

![](https://cldup.com/XzupFOCUYn-1200x1200.png)

Errors like this are happening on uses of types like `Moya.Completion` because `Moya` is only actually the module name in the "base" Moya, and the base source is shared. The reason this can't work is because Swift doesn't currently provide a way to reference things by the "current module." A lot of the decls in the source don't actually require the prefix where we use it, but some do, due to ambiguity, etc.

From what I can see, here are a few ways to fix this:
- Convert the Rx/ReactiveCocoa additions be extension frameworks that themselves link against Moya
- Revert type names back to having the Moya prefix
- Change the reactive framework targets' module names to `Moya` (though this would be kinda weird, linking to `RxMoya.framework` but using `import Moya`)

I had previous said I saw no drawbacks to moving to this naming convention, so I apologize 🙁 but I'd like to hear thoughts on what the best option for resolution is.

**Comment by ashfurrow** [comment]
Hey, no problem! The third option sounds appealing; it's how CocoaPods works anyway. We can also use preprocessor directives cleverly somehow maybe.

**Comment by JRHeaton** [comment]
I may have spoken too soon about that option. It seems that Xcode for whatever reason won't let you alter the module name setting. ![](https://cldup.com/kesfU5dzwf-3000x3000.png)

**Comment by JRHeaton** [comment]
It appears this was already brought up in the description of #310. Definitely something we should fix before doing a release with all of these new changes lest we break Carthage support.

**Comment by petester42** [comment]
Ya. I am unsure of how to solve this. If you change the module name and the framework name it works. The problem with that is that it build 3 frameworks but overwrites the previous one since it is also called Moya.framework. Im gonna try to rename them in the post build phase. Maybe that will work.

**Comment by petester42** [comment]
I believe I found a solution to this problem. I still need to test out if works with Carthage but it works fine in Xcode so I don't see why it wouldn't work.
