### ISSUE TITLE
Moya version 4.5.0 use of undeclared 'TargetType'

### ISSUE THREAD

**Issue by ivanruizscm** [Moya/Moya#323]
I have installed Moya trought Cocoapods in a new fresh project.
And im getting an error when i try to subclass my enum. (Use of undeclared TargetType).

ivangodfather
<img width="1046" alt="captura de pantalla 2015-11-30 a las 16 28 53" src="https://cloud.githubusercontent.com/assets/15628215/11475845/cf7283f0-977f-11e5-9f0e-115e5896912b.png">
-> pod install
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Using Alamofire (3.1.3)
Installing Moya 4.5.0 (was 4.5.0)
Installing RxSwift (2.0.0-beta.3)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 2 dependencies from the Podfile and 3 total
pods installed.

**Comment by petester42** [comment]
For 4.5 it is still called `MoyaTarget`. Sorry about the confusion in documentation but we are getting ready for 5.0 which should be out real soon.

**Comment by ivanruizscm** [comment]
Ok! Fixed. Waiting for it. Theres a branch for 5.0 so i dont have to rename it later?

**Comment by petester42** [comment]
Master is the branch for 5.0. Setting `:git =>` in your podfile to this repos url should get you 5.0.

**Comment by ivanruizscm** [comment]
ivan.ruiz$ pod update
Update all pods
Updating local specs repositories
Analyzing dependencies
Pre-downloading: `Moya` from `https://github.com/Moya/Moya`
Removing RxSwift
Downloading dependencies
Using Alamofire (3.1.3)
Installing Moya 4.5.0 (was 4.5.0)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 2 total
pods installed.
AFE0806015:TestingMoya ivan.ruiz$ cat Podfile
# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'TestingMoya' do
    pod 'Moya', :git => 'https://github.com/Moya/Moya'
end

target 'TestingMoyaTests' do

end

target 'TestingMoyaUITests' do

end

**Comment by petester42** [comment]
Ah ya my mistake. The podspec probably was still pointing to 4.5. Anyways the update should be available shortly. @ashfurrow is currently releasing it.

**Comment by ashfurrow** [comment]
Aye, sorry for the confusion @ivanruizscm. I've released the podspec, so the best thing you can do is go back to your original Podfile (the instructions in the project's Readme) and do a `pod update Moya`. Let us know if that works :+1:

**Comment by ivanruizscm** [comment]
Yes, now points to 5.0.0 
Thank you all

**Comment by ashfurrow** [comment]
Cool! Glad that's working. @ivanruizscm would you mind if we close this issue?
