### ISSUE TITLE
Parse apiResponse RxSwift + Moya

### ISSUE THREAD

**Issue by ivanruizscm** [Moya/Moya#331]
I want to parse the response of Moya into a Model with objectmapper.
Basically i want to transform this:

    func getCustomers(user: User, callback: Result<[Customer], NetworkStatus> -> ()) {
        _ = apiProvider.request(Api.Customers(userString: user.userName, passwordString: user.password)).subscribe { (event) -> Void in
            switch event {
            case .Next(let response):
                if let customersJSON = (try? response.mapJSON() as? NSArray) {
                    let customers = Mapper<Customer>().mapArray(customersJSON)!
                    callback(Result(success: customers))
                    return
                }
                callback(Result(failure: NetworkStatus.Other))
            case .Error(_):
                callback(Result(failure: NetworkStatus.Server))
            case .Completed:
                break
            }
        }
    }

Into this:

        func getCustomersRx(user: User) -> Observable<[Customer]> {
        let apiResponse = apiProvider.request(Api.Customers(userString: user.userName, passwordString: user.password))
        apiResponse.map { response in
            do {
                if  let customersJSON: NSArray? = try response.mapJSON() as? NSArray {
                    return Mapper<Customer>().mapArray(customersJSON)!
                }
            } catch {
                fatalError()
            }
        }
       
And i get this error in the .map line:
Cannot invoke 'map' with an argument list of type '(Response throws -> _)'
The problem seems with .mapJSON wich can throw an error, but i dont know how to continue

**Comment by ivanruizscm** [comment]
And its weird to me that if i do in one line forcing everything seems working:
Works:
![captura de pantalla 2015-12-04 a las 11 51 58](https://cloud.githubusercontent.com/assets/15628215/11587985/a68bbde8-9a7d-11e5-9eb0-02d00a8f746f.png)

Dont work:
![captura de pantalla 2015-12-04 a las 11 52 18](https://cloud.githubusercontent.com/assets/15628215/11587986/a6961004-9a7d-11e5-85cf-b83aee80527f.png)

**Comment by ashfurrow** [comment]
Hey there! Great question, I've had this kind of error happen before too. I think it's a bug in Swift surrounding error-handling and inferring closure return types. The way I've fixed it is to explicitly tell swift what the closure return type is. `.map { response -> [Model] in` or whatever. Let me know if that works!

**Comment by ivanruizscm** [comment]
Yes, as you said you had to explicy set the return type. If anyone interested:    
func getCustomers() -> Observable<[Customer]> {
        return TestApiProvider.request(TestApi.Customers).map { response -> [Customer]  in
            do {
                if  let customersJSON: NSArray? = try response.mapJSON() as? NSArray {
                    if let customers = Mapper<Customer>().mapArray(customersJSON) {
                        return customers
                    }
                    throw CustomError.ParseError
                }
            } catch {
                throw CustomError.ServerError
            }
        }
    }

    enum CustomError: ErrorType {
        case ParseError
        case ServerError
    }

**Comment by ashfurrow** [comment]
Great! Glad that worked, thanks for posting the solution! Should we close this issue?
