### ISSUE TITLE
carthage installed 4.0.2 not 5.1.0. is it real?

### ISSUE THREAD

**Issue by minhoryang** [Moya/Moya#332]
```Cartfile
github "moya/moya"
```
installs 4.0.2

expected: 5.1.0

I want a warning message at README.md.

**Comment by ashfurrow** [comment]
Hello, sorry you're experiencing this error. Not sure what's going on, as I'm not as familiar with Carthage. Any ideas @justinmakaila ?

**Comment by mpurland** [comment]
This is because 4.0.2 is the Latest release. The others are just tags. 

@minhoryang To fix this right now you can use:
```github "Moya/Moya" "5.1.0"```

**Comment by ashfurrow** [comment]
You should be able to try again now and have it work – see https://github.com/Moya/Moya/issues/335 for more details.

**Comment by minhoryang** [comment]
Resolved!!! Thanks All!
