### ISSUE TITLE
Avoid duplicate code to add headers

### ISSUE THREAD

**Issue by ivanruizscm** [Moya/Moya#333]
Since all my calls to the API needs to add custom headers, theres an easy way to avoid this?

```swift
var endpointClosure = { (target: TestApi) -> Endpoint<TestApi> in
    let endpoint: Endpoint<TestApi> = Endpoint<TestApi>(URL: url(target), sampleResponseClosure: {.NetworkResponse(200, target.sampleData)}, method: target.method, parameters: target.parameters)
    switch target {
    case .Customers(let u, let p):
        let credentialData = "\(u):\(p)".dataUsingEncoding(NSUTF8StringEncoding)!
        let base64Credentials = credentialData.base64EncodedStringWithOptions([])
        return endpoint.endpointByAddingHTTPHeaderFields(["Authorization": "Basic \(base64Credentials)"])
    case .Properties(let u, let p):
        let credentialData = "\(u):\(p)".dataUsingEncoding(NSUTF8StringEncoding)!
        let base64Credentials = credentialData.base64EncodedStringWithOptions([])
        return endpoint.endpointByAddingHTTPHeaderFields(["Authorization": "Basic \(base64Credentials)"])
    }
   case .Other(let user, password):
      //repeat the same... :-1: 
}
```

**Comment by wangshengjia** [comment]
In this case, you can take advantage from "Pattern Matching" in Swift:
```
switch target {
    case (let u, let p):
        let credentialData = "\(u):\(p)".dataUsingEncoding(NSUTF8StringEncoding)!
        let base64Credentials = credentialData.base64EncodedStringWithOptions([])
        return endpoint.endpointByAddingHTTPHeaderFields(["Authorization": "Basic \(base64Credentials)"])
    }
```
The code above is kind of "Wildcard pattern matching", should work for all cases which has the same signature. :wink:

**Comment by ivanruizscm** [comment]
<img width="891" alt="captura de pantalla 2015-12-07 a las 16 14 43" src="https://cloud.githubusercontent.com/assets/15628215/11630399/a8a652d2-9cfd-11e5-83b3-8bfa42be759c.png">

**Comment by wangshengjia** [comment]
Ok...I also run my tests this time, it won't work. I removed my answer

**Comment by ivanruizscm** [comment]
For now i can leave like this: :-1:    

     switch target {
    case .Customers(let u, let p):
        return endPointWithAuthHeader(u, p: p, endpoint: endpoint)
    case .Properties(let u, let p):
        return endPointWithAuthHeader(u, p: p, endpoint: endpoint)
    case .Login(let u, let p):
        return endPointWithAuthHeader(u, p: p, endpoint: endpoint)
    }
    }

    func endPointWithAuthHeader(u: String, p:String, endpoint: Endpoint<NextVisitApi>) -> Endpoint<NextVisitApi> {
        let credentialData = "\(u):\(p)".dataUsingEncoding(NSUTF8StringEncoding)!
        let base64Credentials = credentialData.base64EncodedStringWithOptions([])
        return endpoint.endpointByAddingHTTPHeaderFields(["Authorization": "Basic \(base64Credentials)"])
    }

**Comment by wangshengjia** [comment]
If you need to put the same `user` and `password` for any kind of `endpoint`, why not just add auth header directly without `switch` cases ?

**Comment by ivanruizscm** [comment]
How can i add it without retreiving the username/password?

**Comment by ivanruizscm** [comment]
When i call the endPoint i pass a username/password stored in disk. Then i add those to the header. I dont want to retreive those directly from here. I have a  'user repository' where i store them.

**Comment by ashfurrow** [comment]
OK, so if the username and password apply to _every_ endpoint, you have a few options. The easiest is to store the username and password in a globally-accessible place. Then your closure would look like:

```swift
var endpointClosure = { (target: TestApi) -> Endpoint<TestApi> in
    let credentialData = "\(globalUserName):\(globalPassword)".dataUsingEncoding(NSUTF8StringEncoding)!
    let base64Credentials = credentialData.base64EncodedStringWithOptions([])
    let endpoint = Endpoint<TestApi>(URL: url(target), sampleResponseClosure: {.NetworkResponse(200, target.sampleData)}, method: target.method, parameters: target.parameters)
        .endpointByAddingHTTPHeaderFields(["Authorization": "Basic \(base64Credentials)"])

    switch target {
    // TODO: Customize any parameters on an as-needs basis.
    default:
      return endpoint
    }
}
```

There are other ways to do this, like using composition to encapsulate the username/password inside an object that also holds onto the Moya provider for you. We do something similar [here](https://github.com/artsy/eidolon/blob/a93f9f67aca6b27996076b3042ea532b4fbb9fb5/Kiosk/App/Networking/ArtsyAPI.swift#L349-L408), but for other purposes. You could also store the credentials in [another type](https://github.com/artsy/eidolon/blob/f95c0a5bf1e90358320529529d6bf431ada04c3f/Kiosk/App/Networking/XAppToken.swift#L10-L64). There are lots of different options to do this _well_, but I'd first focus on getting it to work, and then make it awesome after :tada:

Does that help?

**Comment by ivangodfather** [comment]
Ok thx you!
