### ISSUE TITLE
Sending extra parameters using the ReactiveCocoaMoyaProvider

### ISSUE THREAD

**Issue by AvdLee** [Moya/Moya#334]
We're using Moya throughout most of our apps. One feature we're missing is sending extra parameters together with the token.

We're using the `ReactiveCocoaMoyaProvider`, which simply accepts sending a token conform the MoyaTarget protocol.

It would be great to send the request with an extra value parameters, in which we can sending optional parameters specific for some of the API calls.

The scenario we're using it for is pagination. Some API calls accept pagination with parameters "offset" and "limit", which we want to send like this:

`MyProvider.request(token: Target, extraParameters: ["offset": 0, "limit": 15])`

Any suggestion in how to set this up with the current version of Moya is welcome, else we would like to send this as a feature request.

**Comment by swizzlr** [comment]
@AvdLee I should think the correct way to do this would be to embed it within the Target and correctly generate the params using the `parameters` property of the `TargetType` so you have a single point of entry.

**Comment by AvdLee** [comment]
The thing is, we're using Moya the same as the Artsy project, using Enums. These can't contain stored properties.

The way I'm now doing this is by creating a seperated class conforming the MoyaTarget protocol, in which I'm copying the properties of the Enum and adding the extra parameters as you describe.

It just doesn't feels like the way it should be done.

**Comment by ashfurrow** [comment]
Hmm, that's odd – sorry this is being problematic. So Moya actually _used_ to let you do this, and we took it out to sort of "force" developers to put these types of parameters inside enum associated values. 

You're right that enums can't have stored properties, but an enum _case_ can. In [our login case](https://github.com/artsy/eidolon/blob/a93f9f67aca6b27996076b3042ea532b4fbb9fb5/Kiosk/App/Networking/ArtsyAPI.swift#L8), we attach username and password as associated values. Then later when we need to return our parameters, [we use those associated values](https://github.com/artsy/eidolon/blob/a93f9f67aca6b27996076b3042ea532b4fbb9fb5/Kiosk/App/Networking/ArtsyAPI.swift#L140-L147). This lets us store, and then retrieve the parameters. Your code to invoke the endpoint would change to look like the following:

```swift
MyProvider.request(token: Target(offset: 0, limit: 15))
```

Does that make sense?

**Comment by AvdLee** [comment]
I agree, this should be the way to do this. Downside of this, is that I have multiple calls like:

```case getMovies
case getSeries
case getCollection(collectionId:Int)```

Which are all `pageable`. 

I was hoping to create a generic solution to call these targets, with the paging logic handled by a seperated paging class:

```
final class PageableOperation {
 
    private let endpoint:ExampleAPI
    
    init(endpoint:ExampleAPI){
        self.endpoint = endpoint
    }
    
    func pagingSignalWithOffset(offset:Int, limit:Int) -> RACSignal {
        
        var parameters = self.endpoint.parameters as [String : AnyObject]
        
        parameters["offset"] = offset
        parameters["limit"] = limit

        return TIFProvider.request(self.endpoint, parameters: parameters)
    }
}
```

But I guess I'll go for a datasource implementation, which should send back a new paging signal based on the given offset and limit. Seems to be OK for this as well.

If you have any other suggestions, feel free to let me know!

**Comment by ashfurrow** [comment]
Ok cool, this looks like it got sorted out. Going to close, feel free to re-open 👍

**Comment by mingyeow** [comment]
@AvdLee i am having very similar issues / concerns. i am currently a struct called pagination that encapsulates the page # calculation based on current offset/perpage, amongst other things.

Do you mind sharing a gist of your datasource implementation when you are done? I would love to get some inspiration.
