### ISSUE TITLE
Add support for RxSwift beta 4

### ISSUE THREAD

**Issue by phamquochoan** [Moya/Moya#335]
my cartfile:
```
github "Alamofire/Alamofire"
github "ReactiveX/RxSwift" "2.0.0-beta.4"
github "Moya/Moya" "5.1.0"
```
When I update carthage, it shows:
```
Could not pick a version for github "ReactiveX/RxSwift", due to mutually incompatible requirements:
	"2.0.0-beta.4"
	"2.0.0-beta.2"
```

However, if I remove `"5.1.0"` of Moya, it will checkout `Moya 4.1.0`

**Comment by ashfurrow** [comment]
Oh, right. Carthage means different things between specifying "git" and "github" – we've seen this before, sorry it's not fixed yet. 

I've created a [5.1.0 "Release"](https://github.com/Moya/Moya/releases/tag/5.1.0) in addition to our existing tag. Try again and let me know if that works.

**Comment by phamquochoan** [comment]
Hi ashfurrow,

It still doesn't work. I've tried these cases so far

```
cartfile:
github "Moya/Moya"

*** Checking out RxSwift at "2.0.0-beta.2"
*** Checking out Moya at "5.1.0"
```


```
cartfile:
github "Alamofire/Alamofire"
github "ReactiveX/RxSwift" "2.0.0-beta.4"
github "Moya/Moya"

*** Checking out Alamofire at "3.1.3"
*** Checking out Moya at "4.1.0"
*** Checking out RxSwift at "2.0.0-beta.4"
```


```
cartfile:
github "Alamofire/Alamofire"
github "ReactiveX/RxSwift" "2.0.0-beta.4"
github "Moya/Moya" "5.1.0"

Could not pick a version for github "ReactiveX/RxSwift", due to mutually incompatible requirements:
    "2.0.0-beta.4"
    "2.0.0-beta.2"
```

**Comment by ashfurrow** [comment]
Ah I see, right. Moya 5.1.0 has a different version of RxSwift as a dependency. I'll fix that tonight, or roll back to beta 2 for now. 

For anyone interested in the problems with releases vs. tags in Carthage, check out the end of this thread: https://github.com/Moya/Moya/pull/329

**Comment by orta** [comment]
#361 deprecates this
