### ISSUE TITLE
Moya's Result type shadows Result's Result type

### ISSUE THREAD

**Issue by mhuusko5** [Moya/Moya#338]
Now that Moya has a Result type, it isn't possible to use Result's Result type in a file that imports Moya
Same thing as happened when Alamofire added a Result type

Might it be better to just add Result as a dependency? It's quite a small/stable one, and unlike usual dependencies, it's *less* troublesome to the end user..

**Comment by ashfurrow** [comment]
Doesn't type inference tell Swift which to use? It's also possible to use Moya.Result. I'm not opposed to adding a dependency if we need it.

**Comment by petester42** [comment]
There is a technical reason we can't. Since alamofire uses its own result we can't use the standard result library because we need to namespace it. Sadly you can't do `Result.Result` as a type for the completion block. Compiler no like. 

Is there a thing like `hiding` in Haskell for swift that I don't know of?

**Comment by mhuusko5** [comment]
Unfortunately as @petester42 mentions, Result.Result doesn't work because of an ongoing Swift quirk where you cant explicitly access a type that has the same name as its module.

So, Moya.Result can be access inferred or explicitly, but if Moya is imported in a file, inferred use of Result is ambiguous/won't compile, but Result.Result can't be accessed either.

And there's no `hiding` or such, as far as I know :(

It's a weird position to be in, because this could be fixed in the language tomorrow, or.. not tomorrow. I personally think it's worth integrating the defacto Result.Result, but I haven't been bitten by adding a dep to a large OSS library before.

**Comment by petester42** [comment]
As for your original issue. You can use Result's Result type just prefix the Moya one like so `Moya.Result` where the two clash.

**Comment by mhuusko5** [comment]
Moya.Result makes it so *those* uses are unambiguous. It doesn't make it so I can use Result.Result. Those instances are still ambiguous (because can't prefix).

**Comment by ashfurrow** [comment]
Sounds like the easiest solution is just to add a dependency to Result. I'm totally OK with that – anyone have time to send a PR?

**Comment by mhuusko5** [comment]
Little busy atm, but should be able to some time this week. Perhaps that will also give some time for others (@Moya/contributors), if anyone has strong opinions about additional dependencies, to chime in.

**Comment by ashfurrow** [comment]
Fab idea. This would also be a great "first time" contribution, too!

**Comment by petester42** [comment]
You might need to do some hacks to make it work. I tried added this dependency when we moved to result but the compiler was not happen. Maybe moving the completion typealias to another file would work. Any file with `import Alamofire` will cause issues.

**Comment by ashfurrow** [comment]
This was fixed in #344, I believe. If it's still an issue, we can re-open.
