### ISSUE TITLE
Make path an optional

### ISSUE THREAD

**Issue by Austinate** [Moya/Moya#341]
**Hi! 
First of all — thanks for an awesome tool which helps with making projects better** :+1: 

I've faced one situation while using Moya, but since that seems to be breaking change i'd like first to discuss (or sort for approval to make that change). 

What we have:
Let's imagine some api with parameter/based URLs (Flickr, for example).

and code:

```
    public var baseURL: NSURL { return NSURL(string: "https://api.flickr.com/services/rest")! }
    
    public var method: Moya.Method {
        return .GET
    }
    
    public var path: String {
        return ""
    }
```

So a thing here — returning empty string as path looks a bit creepy.
Wouldn't it be better if we will make path optional? 
So Target type will look like: 
```
public protocol TargetType {
    var baseURL: NSURL { get }
    var path: String? { get }
    var method: Moya.Method { get }
    var parameters: [String: AnyObject]? { get }
    var sampleData: NSData { get }
}
```

Not sure if this still looks good. Maybe better option will be to provide different target types (🙄) or default implementation for protocol functions in extension? So if you don't want to return parameters — no need to implement getter which will return nil. 

Thanks for attention :)

**Comment by petester42** [comment]
Having an empty path is fine. Wouldn't it be better to set "rest" as the path and "https://api.flickr.com/services" as the base url. That seems to be the intent that you want to describe.

**Comment by Austinate** [comment]
Thanks, your sight on this seems to be much more reasonable.

**Comment by petester42** [comment]
I like to define my API as explicitly has possible. If I have to make an empty path then maybe I didn't use the proper baseURL. Hope that helps.

**Comment by Austinate** [comment]
I see now,  thanks fkr making this more clear.
