### ISSUE TITLE
Response parsing

### ISSUE THREAD

**Issue by mpurland** [Moya/Moya#347]
I just wanted to start a discussion around response parsing for `TargetType`. I have an existing solution using ReactiveMoya with some protocol extensions. It would be nice to have it built into Moya though.

Example:
```swift
protocol ProducerTargetType: MyTargetType {
    typealias ResponseType = Response
    
    func producer(provider: ReactiveCocoaMoyaProvider) -> SignalProducer<ResponseType, ErrorType>
}
```

**Comment by petester42** [comment]
This is very interesting but wouldn't this mean that a Target could only map to one type of response. Wouldn't you need to create an extension for every single endpoint?

**Comment by justinmakaila** [comment]
I think the best way to handle response parsing is by extending the SignalProducerType, similarly to what we do in [SignalProducer+Moya](https://github.com/Moya/Moya/blob/master/Source/ReactiveCocoa/SignalProducer%2BMoya.swift), or by creating a global function.

**Comment by ashfurrow** [comment]
Sounds like this is resolved, feel free to re-open if not 👍
