### ISSUE TITLE
Need help on calling 'GET' api

### ISSUE THREAD

**Issue by AnnieNinaJoyceV** [Moya/Moya#352]
I hope, it is allowed to ask queries here. I couldn't get `Moya` tag on stackoverflow site.
And thank you very much for creating such a wonderful library.

Question:
I want to make a API call - the URL looks in this format
`BaseURL/MethodName?ParameterName=valueToPass`

And when I pass it like '/MethodName?ParameterName=valueToPass' in the `public var path: String {}` method, it percent encodes '?' to %235F. Thus, always returning error in response.

Can you please let me know the procedure to make such API calls?

**Comment by wangshengjia** [comment]
Checkout `path` & `parameters` which mentioned in documentation [Target](https://github.com/Moya/Moya/blob/master/docs/Targets.md).

Hope this is helpful :)

**Comment by AnnieNinaJoyceV** [comment]
Thank you for the help :)
The solution was to use `EndPoint` :+1:
