### ISSUE TITLE
Remove pod install warnings with COCOAPODS_DISABLE_DETERMINISTIC_UUIDS

### ISSUE THREAD

**Issue by petester42** [Moya/Moya#355]
Follow up to the conversation here:
https://github.com/Moya/Moya/pull/351#commitcomment-15109811

Adding `ENV['COCOAPODS_DISABLE_DETERMINISTIC_UUIDS'] = 'true'` to our podfile will remove the long warning we get when running `pod install`.

**Comment by ashfurrow** [comment]
This should be fixed, especially with CocoaPods 1.0 out.
