### ISSUE TITLE
About insatll

### ISSUE THREAD

**Issue by cconecode** [Moya/Moya#357]
When I use carthage install the Argo，It‘s spent a lot of time to Fetching LlamaKit，And finally, it's failure

**Comment by ashfurrow** [comment]
Did you get this figured out? Is it a duplicate of https://github.com/Moya/Moya/issues/356 ?

**Comment by cconecode** [comment]
Sorry, my description of the problem is wrong，I mean the Moya’s dependencies is too much，When I use carthage，I failed in Fetching LlamaKit，But sometime，success. The causes of the network?

**Comment by alfredcc** [comment]
Moya’s dependencies is too much? See here[Checkouts](https://github.com/Moya/Moya/blob/master/Cartfile)  
And i think your problem is your network.

**Comment by cconecode** [comment]
OK, thx

**Comment by cconecode** [comment]
Moya is so great, I love it
