### ISSUE TITLE
Intercept request for missing authentication

### ISSUE THREAD

**Issue by Skornos** [Moya/Moya#359]
I am getting deeper into this library and I must say love it. 

I am trying to solve the following issue. Every request I make must be authenticated (except for the authentication endpoint) and if I am missing the authentication information I want to intercept the request, ask for new `identity` and when it responds then continue with the original request.

I was thinking about using using `endpointClosure` (or `requestClosure` but sadly I wasn't able to check the request `TargetType` here) but it isn't possible to use the same `Provider` within its own type to call for this new `identity`.

Another solution I am thinking about is writing custom `Plugin` or am I missing some easier way?

Thanks :)

**Comment by ashfurrow** [comment]
Thanks for the kind words! I'm not entirely sure what the identity is, but I've only used Moya for OAuth/XApp/Basic HTTP authentication methods. As you noted, [the request closure](https://github.com/Moya/Moya/blob/master/docs/Authentication.md#oauth) is where I would think this would go, but it's clearly a no-go if you need only _some_ endpoints to be authenticated.

A Plugin could work. We [have a basic auth one](https://github.com/Moya/Moya/blob/master/Source/Plugins/CredentialsPlugin.swift) but it [has some issues right now](https://github.com/Moya/Moya/issues/326). I've done something [here](https://github.com/artsy/eidolon/blob/cb31168fa29dcc7815fd4a2e30e7c000bd1820ce/Kiosk/App/Networking/XAppAuthentication.swift#L8) that might work, but that approach relies on RxSwift/RAC.

A sort of hacky way to do this (for now, until we have a better answer) is to use the `requestClosure` and check against the Endpoint's URL or something. It's not great, but it would work. 

This seems like a common-enough problem that we should a) fix #326 and add documentation on how to do general-purpose authentication plugins.

**Comment by Skornos** [comment]
Checking against the Endpoint's URL seems like a solution but it is not possible to call the same Provider request within it's own init method (getting `'requestClosure'` used within its own type) error. 

Does it mean that it's necessary to create new Provider which will serve only for Authetication to be able to call it within `requestClosure`?

**Comment by ashfurrow** [comment]
Ah, I see. Good point. I'm not sure if the best way to approach this – the existing examples focus on authentication outside of Moya _or_ authentication at the Target level in the endpoints closure. 

@Moya/contributors any suggestions here?

**Comment by aamctustwo** [comment]
@skornos A couple of questions to help me understand your situation. I want to make sure I'm not missing anything!

1. Why are you waiting till the call is made to check if the request is authenticated? Why not have a `bool` that is checked prior to preparing any network requests that would need to be authenticated?
2. Why are you concerned about checking the authentication at the time of the request? You will need to implement handling for a failed authentication response anyway in case their token/sessions/etc. has expired. This handling would include re-authentication and re-making the original (now properly authenticated) request.

In the end it may not be such a bad idea in the end to separate out your authentication endpoint from your other endpoints. There are a number of Moya regulars who use multiple `TargetType`s and `Provider`s to separate out categories of endpoints.

**Comment by ashfurrow** [comment]
Any further discussion on this?

**Comment by ashfurrow** [comment]
Going to close this issue, but I'll note that there's a demo of a re-authentication plugin in this issue that's worth checking out: https://github.com/Moya/Moya/issues/744 Thanks again for opening @Skornos!
