### ISSUE TITLE
After updating my pods Moya decreased version

### ISSUE THREAD

**Issue by ivangodfather** [Moya/Moya#363]
pod update...
Installing Moya 5.1.0 (was 5.2.1)
And now since RxSwift updated i get errors "Use of unresolved identifier 'just'".
My pods are:
pod 'Moya'
pod 'Moya/RxSwift'

**Comment by ivanruizscm** [comment]
I solved by manually setting the version in Cocoapod:
pod 'Moya/RxSwift', '5.3.0'

**Comment by ashfurrow** [comment]
Yeah, Moya 5.3.0 uses RxSwift 2, which changed `just` to be a static function on `Observable`. This means `just(whatever)` became `Observable.just(whatever)` (or `.just(whatever)`). Running `pod update Moya` should fix this :+1:
