### ISSUE TITLE
4.5.0->6.0.0 migration issue (befuddling compilation error)

### ISSUE THREAD

**Issue by aehlke** [Moya/Moya#365]
I'm upgrading from 4.5.0 to 6.0.0 and have one last compilation error that's stumping me. My code was inspired from a combination of Moya docs and the Eidolon source from a year or so ago. Any help is most appreciated - I'm having a rough time since the error message is quite opaque to me (it sounds like a contradiction). It should be pretty familiar to how Eidolon's API was structured a while back, though it seems to have had a lot of new abstraction added since then.

Here's where compilation fails:
```
static func DefaultProvider() -> ReactiveManabiAPIProvider<ManabiAPI> {
        return ReactiveManabiAPIProvider(endpointClosure: endpointsClosure,
            requestClosure: endpointResolver(),
            stubClosure: StubBehaviour,
            plugins: APIProvider.plugins)
    }
```
```
error: cannot convert value of type '(ManabiAPI) -> Endpoint<ManabiAPI>' to expected argument type '_ -> Endpoint<_>'
        return ReactiveManabiAPIProvider(endpointClosure: endpointsClosure,
                                                          ^~~~~~~~~~~~~~~~
```

And here are the relevant bits referenced above:
```
enum ManabiAPI {
[...]
}

extension ManabiAPI : TargetType {
    var baseURL: NSURL { return NSURL(string: "[...]")! }    
    var path: String {
    [...]
    }
    var parameters: [String: AnyObject]? {
    [...]
    }
    var method: ReactiveMoya.Method {
    [...]
    }
    [...]
}

public class ReactiveManabiAPIProvider<Target where Target: TargetType> : ReactiveCocoaMoyaProvider<Target> {
    var appController: AppController
    var requestErrors: RACSubject
    
    override init(endpointClosure: MoyaProvider<Target>.EndpointClosure = MoyaProvider.DefaultEndpointMapping,
        requestClosure: MoyaProvider<Target>.RequestClosure = MoyaProvider.DefaultRequestMapping,
        stubClosure: MoyaProvider<Target>.StubClosure = MoyaProvider.NeverStub,
        manager: Manager = Alamofire.Manager.sharedInstance,
        plugins: [PluginType] = [], stubScheduler: DateSchedulerType? = nil) {
            let appDelegate = (UIApplication.sharedApplication().delegate as! AppDelegate)
            appController = appDelegate.appController!
            
            requestErrors = RACSubject()
            
            super.init(endpointClosure: endpointClosure, requestClosure: requestClosure, stubClosure: stubClosure, manager: manager, plugins: plugins)
    }
[...]
}
```

Please let me know if it'd be helpful to see anything else. Thanks!

**Comment by aehlke** [comment]
I've posted the question on StackOverflow since it's not particularly Moya-specific: http://stackoverflow.com/questions/34707426/what-does-this-swift-type-error-mean-it-reads-like-whats-expected-is-already-t

**Comment by ashfurrow** [comment]
Yikes! I'll take a closer look later, but when I encountered problems upgrading eidolon to Moya 6, most problems were solved by being more explicit about closure parameter/return types. You can check out our existing inplementation, too.

**Comment by gregpardo** [comment]
I'm having the same problem. I thought it was a derived data issue or something like that but nothing I could do was working. When I removed my plugins it would compile but none of the autocomplete was working and it was seeming to happen with other pods to. It was driving me a little crazy glad I'm not the only one.

**Comment by aehlke** [comment]
Just realized I didn't post the actual implementation of `endpointsClosure`, at the top of this:

```
struct APIProvider {
    static var username: String? = nil
    static var password: String? = nil
    
    static var endpointsClosure = { (target: ManabiAPI) -> Endpoint<ManabiAPI> in
        var base64Login: NSString?
        
        if let username = username {
            if let password = password {
                let login = NSString(format: "%@:%@", username, password)
                let loginData: NSData = login.dataUsingEncoding(NSUTF8StringEncoding)!
                base64Login = loginData.base64EncodedStringWithOptions([])
            }
        }
        
        let parameterEncoding: ReactiveMoya.ParameterEncoding = target.method == .GET ? .URL : .JSON
        
        let endpoint: Endpoint<ManabiAPI> = Endpoint<ManabiAPI>(
            URL: url(target),
            sampleResponseClosure: {.NetworkResponse(200, target.sampleData)},
            method: target.method,
            parameters: target.parameters,
            parameterEncoding: parameterEncoding)
        
        if let base64Login = base64Login {
            let headerFields = ["Authorization": "Basic \(base64Login)"]
            return endpoint.endpointByAddingHTTPHeaderFields(headerFields)
        } else {
            return endpoint
        }
    }
    
    static func StubBehaviour(_: ManabiAPI) -> ReactiveMoya.StubBehavior {
        return .Never
    }
    
    static func DefaultProvider() -> ReactiveManabiAPIProvider<ManabiAPI> {
        return ReactiveManabiAPIProvider(endpointClosure: endpointsClosure,
            requestClosure: endpointResolver(),
            stubClosure: StubBehaviour,
            plugins: APIProvider.plugins)
    }
    
    private struct SharedProvider {
        static var instance = APIProvider.DefaultProvider()
    }
    
    static var sharedProvider: ReactiveManabiAPIProvider<ManabiAPI> {
        get {
            return SharedProvider.instance
        }
        
        set (newSharedProvider) {
            SharedProvider.instance = newSharedProvider
        }
    }
}
```

**Comment by gregpardo** [comment]
Update for me. I was also getting a casting to objc bridge error on my plugins array. Which is odd because I wasn't doing any objc. 

```swift
let plugins = [somePlugin]
```

Now works as
```swift
let plugins:[PluginType] = [somePlugin]
```

Not sure if this is a related issue but was a similar obscure result.

**Comment by aehlke** [comment]
Thanks @gregpardo that may help. But I've disabled plugins in an attempt to narrow down this issue. Glad you found your fix.

**Comment by aehlke** [comment]
Ah I think I've solved it, something stupid - I specify `plugins: APIProvider.plugins` despite having commented out `APIProvider.plugins` - it gave that unrelated error for that static var not existing. I don't know if this is related to what you ran into, but at least your problem led me to it.

**Comment by ashfurrow** [comment]
Ah, sounds like trouble :) Is this issue good to be closed?

**Comment by gregpardo** [comment]
It may be more of a swift 2 lint/compile error than anything else. Just seems like sometimes the errors are really unrelated to what is actually going on.

**Comment by aehlke** [comment]
Yep, all resolved now... Sorry for the noise, thanks.

**Comment by ashfurrow** [comment]
Hey, don't worry about it! Issues are the perfect spot for questions like this. I guarantee other Swift developers are getting similar errors, and if we debug problems like this in the open, then they won't have to fix it by themselves next time :wink:

**Comment by jschneier** [comment]
I'd just like to note for posterity that if anyone lands here I had the exact same issue and the fix was being more explicit about the types.

I had something like
```swift
static var sharedProvider = ...
```
That then returned my provider.

I fixed the issue by switching to
```swift
static var sharedProvider: MoyaProvider<EtherAPI> = ...
```

**Comment by gregpardo** [comment]
Seems like a very similar issue. The swift compiler sometimes needs to be explicit but does not properly hint on where the problem is. I'm going to keep this in mind for this and other projects.
