### ISSUE TITLE
Where is the best place to add display activity indicator to code?

### ISSUE THREAD

**Issue by mertnesvat** [Moya/Moya#366]
I need to add activity indicator before response came. Is there any way to access all request from one place?

**Comment by alfredcc** [comment]
May `NetworkActivityPlugin ` can do this. See end of the [Providers Doc](https://github.com/Moya/Moya/blob/master/docs/Providers.md)

**Comment by mertnesvat** [comment]
Thanks @alfredcc I tried to add plugins but couldn't. Can you give me an example code or some more detailed link about plugins?

**Comment by aamctustwo** [comment]
You add the plugins as part of the initialization for your `provider`. It is passed in as an array. As an example, to add the `NetworkLoggerPlugin` to your provider, use the following sample code:

```swift
let plugins: [PluginType] = [NetworkLoggerPlugin(verbose: true)]
let myProvider = MoyaProvider<MyTarget>(plugins: plugins)
```

Here is [the full spec](https://github.com/Moya/Moya/blob/464d2beb9d558dbfbd2098daa09be932389d078a/Source/Moya.swift#L54-L58) for the `init` of a `MoyaProvider`.

**Comment by mertnesvat** [comment]
thanks @aamctustwo :+1:

**Comment by ashfurrow** [comment]
Thanks @aamctustwo – much appreciated :bow:

**Comment by mrfarukturgut** [comment]
@aamctustwo What about usage `NetworkActivityIndicator`? Can you please give sample code about that?
