### ISSUE TITLE
Subclass vs. Plugins, or: Unable to override request(token: Target) in RxMoyaProvider subclass

### ISSUE THREAD

**Issue by tomburns** [Moya/Moya#367]
I'm attempting to bake in some standard exponential backoff logic in my RxMoyaProvider subclass.

When I attempt to override the request function like so:

```
    override func request(token: Target) -> Observable<Response> {
        return super.request(token)
    }
```

 the compiler tells me 

`Reference to generic type 'Response' requires arguments in <...>`

I suppose my questions are twofold: 1) What am I missing regarding `Response` and generics, and 2) am I barking up the wrong tree here? Could what I'm doing be better accomplished via a Plugin?

Thanks!

**Comment by ashfurrow** [comment]
I think subclassing makes sense for this task :+1: However, the error you're getting suggests that maybe there's another `Response` type that's confusing the compiler. Can you try being explicit? Like `Moya.Response` (or `ResponseType` or whatever it is now – gosh, I can't keep track of my own library :sweat_smile: ). Let us know if that works.

**Comment by tomburns** [comment]
...and of course that did it. Thanks! :laughing:

**Comment by tomburns** [comment]
For anyone curious, it was colliding with Alamofire.Response.

**Comment by ashfurrow** [comment]
Cool, glad that worked! Do you think we could/should improve our documentation around this?

**Comment by tomburns** [comment]
@ashfurrow Thinking about it, I'm not a huge fan of the fact that we're knowingly shadowing a type from our dependency; this is something that's likely to come up for all consumers interacting with the type from outside the Moya/RxMoya modules. I'll open another issue for discussion.

**Comment by ashfurrow** [comment]
Please do, and @ mention the contributors, too. We discussed this some time ago, and I feel like we've tried to adhere to an ideal that may not be best in practice.
