### ISSUE TITLE
Extend Provider Examples

### ISSUE THREAD

**Issue by Prayer-RecycleSmart** [Moya/Moya#369]
Hi All,

I m struggling to extend the MoyaProvider so I dont have to explicitly pass the endpoint block to the initialiser.

Can we include an example of how to extend the MoyaProvider class in the Demo for example? I think that would really decrease the learning curve for most of the newer users. Otherwise would you suggest me a better implementation? 

this is what im doing
```
class MyProvider<Target where Target: TargetType>: MoyaProvider<MyAPI> {
    
    override init(endpointClosure: EndpointClosure = MyProvider.MyEndpointMapping,
        requestClosure: RequestClosure = MoyaProvider.DefaultRequestMapping,
        stubClosure: StubClosure = MoyaProvider.NeverStub,
        manager: Manager = MoyaProvider<Target>.DefaultAlamofireManager(),
        plugins: [PluginType] = []) {
            
            super.init(endpointClosure: endpointClosure, requestClosure: requestClosure, stubClosure: stubClosure, manager: manager, plugins: plugins)
    }
    
    internal final class func MyEndpointMapping(target: FreelancerAPI) -> Endpoint<MyAPI> {
        let endpoint: Endpoint<MyAPI> = Endpoint<MyAPI>(URL: url(target), sampleResponseClosure: {.NetworkResponse(200, target.sampleData)}, method: target.method, parameters: target.parameters)
        
        // Sign all non-authenticating requests
        switch target {
        case .ListOfJobs:
            return endpoint
        default:
            return endpoint
        }
    }
    
}
```

Thanks

**Comment by ashfurrow** [comment]
Hey there! Sorry you're having trouble. It looks like you're just customizing the endpoint mapping, right? If that's the case, you don't have to subclass the provider at all, you can just pass in the closure when you create the provider. Subclassing the provider is generally only needed when you have to change the behaviour of the `request` method. For example, [waiting until there is internet](https://github.com/artsy/eidolon/blob/04a0c8488525be4b918e212e92a29f143e0f5838/Kiosk/App/Networking/Networking.swift#L22-L31) before sending the request.

**Comment by Prayer-RecycleSmart** [comment]
Thanks Ash!

Yea I was looking forward to create a clean implementation, not having to pass the closure all the times.
I kinda reached that point with the code above, not sure if I will keep it in my code.

If you had some spare time I would suggest you to include another Demo project that explores other advanced customisations. Everything is already pretty much explained in the docs, but having other examples to wrap up all the concepts would not hurt. Imagine that I ended up here after I started to study your Kiosk app... :) OnlineProvider is a subclass and I struggle to understand how to compose my provider implementation (without Rx and all the rest).. Now its definitely clear!

Thanks again!

**Comment by ashfurrow** [comment]
Definitely – we need more examples for sure, and are tracking ideas here: https://github.com/Moya/Moya/issues/189 Let me know if there's anything else I can clarify :smile_cat:

**Comment by offbye** [comment]
Who knows how to post a json string use Moya?

**Comment by mertnesvat** [comment]
Great question @offbye I was wondering that too. I would like to send my requests with JSON and I found that I need to change Parameter Encoding like below

```
   public var parameterEncoding : Moya.ParameterEncoding {
        return .JSON
    }
```
what else should I do?

**Comment by mertnesvat** [comment]
@offbye I found the solution among the other issues #188 check it out :+1:

**Comment by sunshinejr** [comment]
I think we can close this one, if you have any ideas for our new [Examples docs](doc/Examples), please let us know! 🐼
