### ISSUE TITLE
Allow plugin to alternate response

### ISSUE THREAD

**Issue by nikita-leonov** [Moya/Moya#370]
Looks like plugin does not allow to modify response. I expected that ObjectMapper or alternative mapping for result/error should be done on a plugin level. Is it a fair expectation or there some other place for doing this in the current architecture? Thanks.

**Comment by ashfurrow** [comment]
Hmm, good question. Based on the current architecture, the plugins are only notified about the response (they're more meant for dealing with requests, not responses). For ObjectMapper, have you taken a look at this library? https://github.com/ivanbruel/Moya-ObjectMapper

**Comment by nikita-leonov** [comment]
@ashfurrow I did review ObjectMapper. It is a nice work, but the way how it is integrated into Moya makes me worry. My expectation that Plugins should be integratabtle through plugin system. The fact that it just an extension on some types of results limits an option to vary capabilities depends on the end point. So here is another example to make my idea a little bit more clear. This is the real production scenario that I am experiencing now. We have different endpoints, all of them return status 200 independently of result. One of outcomes actually can be error and it will be explained in the body. It would be nice to have an option to redefine mapping rules for result/error as a Plugin, so the rest of routine of work with Moya will be kept the same.

**Comment by ashfurrow** [comment]
Yeah, I understand that perspective. But I'm not sure that level of extensibility is right for Moya's level of abstraction. 

What you're describing sounds like it might go well with the reactive approach, which [I've used here](https://github.com/artsy/eidolon/blob/32442b5099f2cd9e937a2c79eb0c94079646bd39/Kiosk/Bid%20Fulfillment/BidCheckingNetworkModel.swift#L124-L128). Happy to clarify anything.

**Comment by nikita-leonov** [comment]
Got it. Thanks. Just want to be sure that I didn't miss a built-in extension point.

**Comment by ashfurrow** [comment]
Cool cool – let us know if you have any other questions or if we can clarify anything else :+1:
