### ISSUE TITLE
Moya.Error error 5.

### ISSUE THREAD

**Issue by AnnieNinaJoyceV** [Moya/Moya#371]
case let .Failure(error):
                
                print((error as NSError).localizedDescription)
                print(Moya.Error.Underlying(error))
                guard let error = error as? CustomStringConvertible else {
                    break
                }

This is how my failure block looks.
On the first print as `NSError`, I get the following response:
**The operation couldn’t be completed. (Moya.Error error 5.)**
For the second print, underlying error:
**Underlying(Moya.Error.Underlying(Error Domain=NSURLErrorDomain Code=-1 "(null)"))**

I'm not sure what happened, it was working fine just few minutes back.
Any help is much appreciated! Thanks.

**Comment by ashfurrow** [comment]
Hmm, hard to say what's happening without more code. The underlying error isn't too descriptive in this case. 

Have you made any recent changes? Upgraded the library? Can you double-check the base URL?

**Comment by ashfurrow** [comment]
Oh, forgot to say: sorry about this! We try to have descriptive errors. Thanks for opening the issue, we'll do our best to figure out what's going on :+1: \

**Comment by AnnieNinaJoyceV** [comment]
Again, not sure what happened. It is working fine now!! I have done no changes.
Might be some network connection issue??

**Comment by ashfurrow** [comment]
Well! Glad to hear it's working :smile: It must've been a network issue, since an error like that indicates that there is no response (otherwise, you'd get a status code and stuff).

**Comment by aleufms** [comment]
I've been having the same problem. I'm displaying the localized description to the user, but it always have the same error (The operation couldn’t be completed. (Moya.Error error 5.)). 

Is there a way to Moya.Error provide the original network error? (e.g. Network seems to be down)

**Comment by ashfurrow** [comment]
Hey there! Sorry you're having a problem – not sure which version of Moya you're using, but an error code of 5 suggests that you can access the underlying error. Check the source code out here: https://github.com/Moya/Moya/blob/master/Source/Error.swift

**Comment by aleufms** [comment]
Oh. Thank you. This method is marked as deprecated. Will it have a replaced method? I'm using with rxSwift

**Comment by ashfurrow** [comment]
That's strange, RxSwift should already be using the new error-handling. You can use the Swift `case` syntax to unwrap the enum and the underlying data: https://github.com/artsy/eidolon/blob/24e36a69bbafb4ef6dbe4d98b575ceb4e1d8345f/Kiosk/Bid%20Fulfillment/PlaceBidNetworkModel.swift#L49

**Comment by sunshinejr** [comment]
Just to chime in here, what I think @aleufms understood was that he could use the `nsError` property of the [Error](https://github.com/Moya/Moya/blob/master/Source/Error.swift). If it is true, yes this is deprecated as of now, but the discussion about it is still going on in #489. 

Additionally, in your case you could just get the `.Underlying(let error)` case from the response error. Having in mind your response error has a name `responseError`, you can get it as following:
```swift
if case .Underlying(let error) = responseError {
    // Now you can use error property as an object of NSError
}
```

Hope it helps!

**Comment by ashfurrow** [comment]
With @sunshinejr's comment, I think this is closed. Please re-open if not.

**Comment by namhn** [comment]
I am experiencing the above error, how to turn off the above message. I am using on swift version 2.3

**Comment by namhn** [comment]
I am experiencing the above error, how to turn off the above message. I am using on swift version 2.3
