### ISSUE TITLE
ReactiveCocoa and RxJava still use Manager.sharedInstance

### ISSUE THREAD

**Issue by aschuch** [Moya/Moya#373]
I guess we should change it to use the default provider introduced in 6.0.

**Comment by ashfurrow** [comment]
Ahhh, yup 😅

**Comment by aschuch** [comment]
I'll submit a PR as soon as I get time. Just wanted to report in case anyone wants to take a shot at it right away. We should potentially cut a `6.0.1` release after that as well.
