### ISSUE TITLE
Upgrading to 6.0.0 with Carthage

### ISSUE THREAD

**Issue by crenwick** [Moya/Moya#375]
I'm getting errors when trying to run my app after upgrading Moya to 6.0.0 using Carthage on both my simulator and device.

Logs spits out:
```sh
dyld: Library not loaded: @rpath/Result.framework/Result
  Referenced from: /Users/.../Library/Developer/CoreSimulator/Devices/BE2AC542-454F-42EB-AE64-B40BB3F1F49F/data/Containers/Bundle/Application/63470171-C041-4DB6-8F0D-6FD1CD9C5F99/....app/Frameworks/Moya.framework/Moya
  Reason: image not found
(lldb) 
```

Tried this after running `carthage update --platform iOS` (and tried with `--use-no-binaries`). I've also reset the simulators and cleaned my build.

The framework seems to build just fine in my app's `Carthage/Build` directory, but downgrading back to 5.1.0 and rebuilding immediately fixes the problem.

I apologize if this is a common problem and if I'm just using Carthage incorrectly, as I'm new to the Carthage ecosystem. Though after searching around, it doesn't feel like I'm using Carthage incorrectly as my app is already set up for it. 

And unfortunately, I cannot use pods on this app :(.

**Comment by Austinate** [comment]
Hi! Just to be sure, do you have Run Script which fixes well-known issue with frameworks? 
It's on 4th step [here](https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos)

**Comment by crenwick** [comment]
Yup. Even tried redoing the Run Script but still no luck.

**Comment by Austinate** [comment]
So you have Moya & Result & Alamofire to project and all specified in script? 
I remember i had issue after updated when i forgot to add Result.framework too

Probably if all is set up properly it would be good to share some sample proj which reproduces issue?

**Comment by crenwick** [comment]
Ohhh, I had no idea about Result. Didn't seem to run into that issue before now, but I'll give it a shot and report back.

**Comment by petester42** [comment]
Yep. Result has been added to replace Moya's own result type because some users where having issues with it.

**Comment by crenwick** [comment]
!! Worked! Upgraded to 6.0.0 successfully after adding `Result.framework` to the Embedded Binaries of the target.

Closing :) Thank you @Austinate and @petester42 for the help!
