### ISSUE TITLE
HTTP status code handling

### ISSUE THREAD

**Issue by novak** [Moya/Moya#379]
I noticed that responses such as a 400, 422, 503, etc. are being returned in the Result as a .Success. This requires the .Success case to have additional logic to handle errors in addition to the .Failure case.

I'm wondering if this was by design? If so, are there best practices for handling errors returned from a server? The API for handling responses in Moya is fantastic, it is incredibly clean. This particular case is  where my code organization breaks a bit.

Any input would be appreciated, thanks.

**Comment by colinta** [comment]
I, for one, consider this behavior to be *correct*, because Moya is only responsible for sending and receiving, not interpreting, the requests and responses.

A "Failure" in this context is a total network failure: either couldn't send, or couldn't receive the request.

In the Ello app, we re-send failed requests.  When the response is a 4xx, we create an error object (based on JSON data that comes back) and pass *that* to a failure closure, which displays the error to the user.

**Comment by novak** [comment]
Thanks for the quick input @colinta. Extremely valid points.

What's your scenario like for a 5xx response? In that case do you attempt any retries?

**Comment by colinta** [comment]
The only response that we handle from inside our Provider is a `401 Unauthorized`, which triggers a request for a new token (and while that is in flight we queue up requests, then send them once the new token is in hand).  500s are plain-jane errors that we show to the user, in this case with a generic error message (if no JSON / error message is provided from the server, we have a fallback error message)

**Comment by novak** [comment]
Thanks. I would say that answers my question. Appreciate it.

**Comment by marchinram** [comment]
@colinta How do you handle the the response in your provider, with a plugin?

**Comment by AndrewSB** [comment]
@marchinram: Is it possible to use a plugin?

Both @colinta and I are using static functions after we see errors, that parse the JSON in an error state. @colinta's code is actually open source, his function is called `generateElloError` https://github.com/ello/ello-ios/search?utf8=✓&q=generateElloError

**Comment by mrfarukturgut** [comment]
@colinta Hey, how do queue the requests while the refreshing request is on the air, then when it is done executing the queued ones?

**Comment by colinta** [comment]
@mrfarukturgut All requests are sent via a class we called `ElloProvider`, and in that `request` method we check to see if the request needs authentication, and if so we make sure we are in the appropriate state.  If the auth state is "attempting to log in" we add the request to a queue.  If the auth state is "anonymous" or "none" we send back an error.

The auth state transitions are handled outside this request cycle, so when we get back a success after sending credentials we can change the auth state from "attempting" to "logged in" and then we send out all the pending requests.

Our code is open source, so you can check this out at <https://github.com/ello/ello-ios>

**Comment by stephenjames** [comment]
If you implement validation on your endpoint, you define which codes are considered a success
public var validationType: ValidationType
