### ISSUE TITLE
Return SignalProducer<Model, Moya.Error> from within enum

### ISSUE THREAD

**Issue by AvdLee** [Moya/Moya#383]
I'm struggling with a solution for our internal networking library.
We're using Moya ReactiveCocoa, together with [Moya-SwiftyJSONMapper](https://github.com/AvdLee/Moya-SwiftyJSONMapper), which makes it possible create calls like this:

```swift
RCStubbedProvider.request(ExampleAPI.GetObject).mapObject(GetResponse).on(failed: { (error) -> () in
    print(error)
}) { (response) -> () in
    print(response)
}.start()
```

This makes mapping to models quite easy, but the disadvantage is that we have to know the type for mapping on the implementation level.

We could solve this by creating wrappers for each defined method, like this:

```swift
extension ExampleAPI {
    static func getObjectCall() -> SignalProducer<GetResponse, Moya.Error> {
        return RCStubbedProvider.request(ExampleAPI.GetObject).mapObject(GetResponse)
    }
}
```

This makes it clear on implementation level that the method will return a GetResponse object.

I'm looking for a generic way to define this within the Enum, which seems to be impossible (based on my Swift knowledge). That's why I'm here to open this issue, maybe you guys have an idea for this.

My "everything is possible" way of doing this would be to add an extra requirement to the `TargetType` protocol:

``` swift
var responseType:ALSwiftyJSONAble { get }
```

Where this part would automatically return a `GetResponse` model:
```swift
RCStubbedProvider.request(ExampleAPI.GetObject)
```

Curious about your ideas guys!

**Comment by ashfurrow** [comment]
Hmm, yeah. nothing pops into my head immediately. I agree that automating this somehow would be :100:

**Comment by aschuch** [comment]
I think mapping responses to models is something that is quite far away from a networking abstraction library such as Moya. I do not see this kind of stuff directly within Moya.
 
That said, you could create an internal protocol `JSONMappable` that defines the `responseType` property and conforms to `TargetType`. Your API definition(s) may then conform to `JSONMappable`.

I've done something similar with [Argonaut](https://github.com/aschuch/Argonaut) but opted for an implementation where you can optionally parse the response to Argo model(s).
Something along the lines of

```swift
Provider.request(.Profile)
    .filterSuccessfulStatusCodes()
    .mapJSON()
    .mapToType(User) // maps to a User model
```

**Comment by AvdLee** [comment]
Yeah, but the problem remains, as I still have to know the model type on implementation level (User in your example).

In my ViewModel / ViewController etc. I simply want to call `Provider.request(.Profile)` which then should return a `SignalProducer<User, Moya.Error>`.

**Comment by aschuch** [comment]
Ok, I guess you can do something like this.

```swift
// Create your own protocol that extends `TargetType`
protocol JSONMappableTargetType: TargetType {
    var responseType: ALSwiftyJSONAble { get }
}

// Implement your Moya enum using `JSONMappableTargetType `
enum ExampleAPI:  JSONMappableTargetType {
    // Implement all TargetType properties

    var responseType: ALSwiftyJSONAble.Type {
        switch self {
        case .X:
            return GetResponse.self
        // etc.
    }
}


// Then add an additional request method
func requestType<T>(target: JSONMappableTargetType) -> SignalProducer<T, Error> {
    return request(target).mapObject(target.responseType)
}
```

**Comment by petester42** [comment]
Yep. I was gonna suggest something like that.

**Comment by AvdLee** [comment]
Alright, interesting. I've implemented your suggestion and encountered some issues. You can check the example project here:
https://github.com/AvdLee/Moya-SwiftyJSONMapper/tree/ObjectMapper_from_enum

Problems encountered:
<img width="783" alt="screen shot 2016-01-29 at 20 52 11" src="https://cloud.githubusercontent.com/assets/4329185/12686712/9c85474a-c6cb-11e5-8f53-97335b0a311a.png">


After rewriting, the project compiled:
```swift
// Works but has al the mapping logic in it, I don't want that!
func requestType<T:ALSwiftyJSONAble>(target: ExampleAPI) -> SignalProducer<T, Moya.Error> {
    return RCStubbedProvider.request(target).flatMap(FlattenStrategy.Latest, transform: { (response) -> SignalProducer<T, Moya.Error> in
        do {
            let jsonObject = try response.mapJSON()
            
            guard let mappedObject = T(jsonData: JSON(jsonObject)) else {
                throw Error.JSONMapping(response)
            }
            
            return SignalProducer(value: mappedObject)
        } catch let error {
            return SignalProducer(error: Moya.Error.Underlying(error))
        }
    })
}
```

However, on the implementation level, where I want this to work:
```swift
    func exampleRequestDirectMapping(){
        requestType(ExampleAPI.GetObject).on { (object) -> () in
            print("Example origin \(object.origin)")
        }.start()
    }
```

It still doesn't. When I explicit cast to the given return type, it does work:
```swift
    func exampleRequestDirectMapping(){
        // This instead works, with type definition
        let producer:SignalProducer<GetResponse, Moya.Error> = requestType(ExampleAPI.GetObject).on { (object) -> () in
            print("Example origin \(object.origin)")
        }
        producer.start()
    }
```

I would suggest to open the Example project yourself and see the problem in action. Hoping we can find the solution for this!

**Comment by ashfurrow** [comment]
If this is wrapped up, I'm going to close it. Feel free to re-open if we can help further.
