### ISSUE TITLE
RxSwift 2.1.x

### ISSUE THREAD

**Issue by philipengberg** [Moya/Moya#386]
You state that Moya `6.1.1` has obtained compatibility with RxSwift `2.1.x`, however, the subspec still states it needs `~> 2.0.0`

**Comment by ashfurrow** [comment]
Huh, good point. Would you mind submitting a pull request to fix it?

**Comment by orta** [comment]
It should probably be cool to use `~> 2.0` - assuming @kzaher keeps to SemVer

**Comment by kzaher** [comment]
`~> 2.0` :+1:

**Comment by philipengberg** [comment]
We use hard versioning, so that's not really an option for us. I'll submit a PR.

**Comment by ashfurrow** [comment]
I think what @orta is saying is that by using `~> 2.0`, it'll take 2.anything which is what we want, right? You can continue to explicitly define versions (I think that's what "hard versioning" is?) and it'll work for you, and for everyone. Does that make sense?

**Comment by philipengberg** [comment]
That's correct. But allowing 2.x might be a little too agressive.

**Comment by ashfurrow** [comment]
How so? I'd say that requiring 2.1.x is more aggressive than 2.x, isn't it? `~> 2.0` is the most flexible, right? Maybe I'm confused.

**Comment by Austinate** [comment]
In my opinion automatically receiving minor updates for dependencies is much better. 
I don't think RxSwift will break something during minor update.

**Comment by philipengberg** [comment]
It's fine by me. I just wanted to allow for the Moya community to test new 2.x features before officially supporting them.
