### ISSUE TITLE
Request Coalescing. Possible? 

### ISSUE THREAD

**Issue by joedaniels29** [Moya/Moya#390]
Suppose I want to do this: 
```swift
provider.request(.UserProfile(1)) { result in
    // do something with the result
}
provider.request(.UserProfile(2)) { result in
    // do something with the result
}
provider.request(.UserProfile(3)) { result in
    // do something with the result
}
```
Suppose further that I'd like these 3 requests to be coalesced into one request: `/UserProfile?ids=[1,2,3]` perhaps based on the runloop; i.e. if I make 4 requests to the UserProfile route in one turn of the loop, coalesce them into one request.
is this possible? In the Web Version of the App that I'm writing, i'm able to accomplish this with Ember data (another Network abstraction layer)

**Comment by colinta** [comment]
What does it look like in ember-data?

**Comment by ashfurrow** [comment]
If you're using RxSwift or RAC, you can use `flatMap`. I don't know if this approach is common, but [I do this](https://github.com/artsy/eidolon/blob/24e36a69bbafb4ef6dbe4d98b575ceb4e1d8345f/Kiosk/Bid%20Fulfillment/BidderNetworkModel.swift#L29-L37).

**Comment by sunshinejr** [comment]
I'm gonna close this one, if you have more questions about it @joedaniels29, please let us know! 🐼
