### ISSUE TITLE
Wrong carriage return character for NetworkLoggerPlugin

### ISSUE THREAD

**Issue by yinanfang** [Moya/Moya#391]
I've got Moya up and running. But I notice that there's some problem with the newline of NetworkLoggerPlugin. Would you be able to fix the default separator and terminator?
Or could you provide a working example about how to modify the existing logger? 
![image](https://cloud.githubusercontent.com/assets/4115566/12688539/e1bb78b0-c6a4-11e5-882d-412c71ecbbb0.png)

**Comment by ashfurrow** [comment]
Hmm, I see the problem: the "terminator" is really in the `print` sense, something the logger terminates its output with. The `\n` you're seeing is due to the nature of the logging: we take a response, take its data, and turn it into a raw string. When we do this, and we that string is printed, the `\n` characters get printed. 

I _think_ that's what's going on. What you're looking for, I think, is a plugin to log the response data formatted as JSON, right? I think that's a reasonable request – we should consider creating a new plugin, or even just adding an option to our current one to accommodate this.

**Comment by yinanfang** [comment]
@ashfurrow Thanks for the quick response! Yes, I just want to log JSON in this case. I saw that Alamofire let me log out a nicely formatted JSON. Maybe you can borrow their formatter? I'm not sure how their's formatter works though. 
Also, It would be great if Moya can let the user specify which specific request their want to log out. The current plugin will show verbose log output for all requests. Once the app grows, the log may not be readable.

**Comment by ashfurrow** [comment]
Good idea, I think that'd be a great idea for a feature. I'm not sure I have availability to work on it right now, though. We'll take a loot (I've opened #392 to develop it). 

As for whitelist/blacklist, I've run into this issue before, too. Here's my solution: https://github.com/artsy/eidolon/blob/32442b5099f2cd9e937a2c79eb0c94079646bd39/Kiosk/App/Networking/NetworkLogger.swift It might make sense for you to write your own logger in the short term until we have these features built into Moya. Let me know if can clarify anything!

**Comment by yinanfang** [comment]
I think that solution is great for requests for some TargetType but not individual requests. What I wanted is to separate the Moya request and response closure like Alamofire does so that we can log out only one outgoing request or one incoming response. I just want to clarify my thoughts. I know that's not the most important feature now. I can just use search and find to dig through the logger. 

By the way, I just tried the ReactiveCocoa example on the ReadMe and it doesn't work. Xcode points to my target and says "... has no member MyTarget". Maybe you forgot the update the ReactiveCocoa part of the ReadMe? Is there an working example somewhere?
https://github.com/Moya/Moya#reactivecocoa

**Comment by ashfurrow** [comment]
Yeah, Moya is not designed to give that level of granularity for plugins, the Target is as low-level as we want to go. 

For the RAC issue, could you open a new issue? There are examples of using it in the Demo project's unit tests in the mean time.

**Comment by sunshinejr** [comment]
_I think_ we can close this one for now, if anything pops out, let us know! 🐼

**Comment by yinanfang** [comment]
Thanks! @ashfurrow @sunshinejr

**Comment by beretis** [comment]
Hi, guys, I recently updated to swift 3, and now the JSONResponseDataFormatter prints data with brake line characters and quotes are escaped. Before swift 3, it was OK. Any idea how to solve this?

**Comment by pedrovereza** [comment]
Hey @beretis, we heard something similar before. Can you check https://github.com/Moya/Moya/issues/739#issuecomment-257120482 and see if it fixes for you?

If not, please open a new issue :wink:
