### ISSUE TITLE
Possible outdated ReadMe for ReactiveMoya?

### ISSUE THREAD

**Issue by yinanfang** [Moya/Moya#393]
As I mention at the end of the discussion of  #391 , I found that the [ReactiveMoya ReadMe example](https://github.com/Moya/Moya#reactivecocoa) doesn't work. The Demo project is only using [Moya framework](https://github.com/Moya/Moya/blob/master/Demo/Demo/GitHubAPI.swift#L2) and the [Unit Test](https://github.com/Moya/Moya/blob/master/Demo/Tests/ReactiveCocoaMoyaProviderTests.swift) doesn't test "start" method. I noticed that they are all "startWithSomething". So I guess maybe the ReadMe is outdated?

**Comment by ashfurrow** [comment]
I've not used the ReactiveCocoa extensions with Moya. @justinmakaila would you take a look when you get a chance?

**Comment by justinmakaila** [comment]
@yinanfang Can you post an example of what you're trying to do? The example looks to be accurate.

**Comment by yinanfang** [comment]
@justinmakaila Here's a screen shot of what I'm trying to do. I've correctly set up the Moya framework and the first example is working. However, when I'm trying to use the ReactiveCocoa extension, it doesn't work and gives an error. 
![gcappdependencies_swift_ _edited](https://cloud.githubusercontent.com/assets/4115566/12739032/bfdde066-c933-11e5-889a-bd7f8601a7e3.png)

**Comment by petester42** [comment]
I would assume that your provider is not of type `ReactiveCocoaMoyaProvider`

**Comment by yinanfang** [comment]
@petester42 Oh! That's it! Thank you so much. I felt like Swift's error message is sometimes irrelevant to the actually problem. If the error message were to be something like "there's no such method as start" then I would probably think about I'm inheriting the wrong type. Or maybe it was just that I misunderstood Swift's error message.

**Comment by petester42** [comment]
The error message is correct. The problem is that he normal provider and the reactive provider have the same `request` method. The code up to `start` would be correct for the normal provider so that's why you don't get a type mismatch error.

**Comment by yinanfang** [comment]
Thanks for explanation! I'm new to Swift and I think I misunderstood its error message!
