### ISSUE TITLE
Add http body

### ISSUE THREAD

**Issue by ivanruizscm** [Moya/Moya#403]
I have an endPoint:

```swift
var endpointClosure = { (target: MyCustomApi) -> Endpoint<MyCustomApi> in
    let endpoint: Endpoint<MyCustomApi> = Endpoint<MyCustomApi>(
        URL: url(target),
        sampleResponseClosure: {.NetworkResponse(200, target.sampleData)},
        method: target.method,
        parameters: target.parameters
    )
    switch target {
    case .Person(let json):
        //How to add HTTPBody here?  endpoint.urlRequest is not mutable, so i can't change the request.
    default:
        return endpoint
    }
}

enum NextVisitApi {
    case Person(someJSON: JSON)
}
```

**Comment by ashfurrow** [comment]
Typically HTTP bodies come from parameters, looks like you have one that's specified in `JSON`. So to set the HTTP body to the json, you just need to tell Moya which parameter encoding to use. 

```swift
var endpointClosure = { (target: MyCustomApi) -> Endpoint<MyCustomApi> in
    let endpoint: Endpoint<MyCustomApi> = Endpoint<MyCustomApi>(
        URL: url(target),
        sampleResponseClosure: {.NetworkResponse(200, target.sampleData)},
        method: target.method,
        parameters: target.parameters
    )
    switch target {
    case .Person(let json):
        return endpoint.endpointByAddingParameterEncoding(.JSON)
    default:
        return endpoint
    }
}
```

And that should work. You can check out the different options for parameter encoding [here](https://github.com/Moya/Moya/blob/aece4ebe3ad3cab946d8df93de4ee72c7024c8e7/Source/Moya%2BAlamofire.swift#L9).

Let me know if that helps :+1:

**Comment by Austinate** [comment]
Also i'd like to add [this link](https://github.com/Moya/Moya/blob/23c4d506c5be9b94d9ecf16cb1f70893ad0b4f41/docs/Endpoints.md#request-mapping)
Hope it will be helpful

**Comment by ashfurrow** [comment]
Yeah, good point! The request-mapping is later-stage stuff in the [pipeline](https://github.com/Moya/Moya/tree/master/docs#documentation), but it's there that I'll often play around with stuff I can't get working at higher levels.

**Comment by ivanruizscm** [comment]
This is correct?

var endpointClosure = { (target: NextVisitApi) -> Endpoint<NextVisitApi> in
    let endpoint: Endpoint<NextVisitApi> = Endpoint<NextVisitApi>(
        URL: url(target),
        sampleResponseClosure: {.NetworkResponse(200, target.sampleData)},
        method: target.method,
        parameters: target.parameters
    )
    switch target {
    case .VisitsPUT:
        return endpoint.endpointByAddingParameterEncoding(.URL).endpointByAddingHTTPHeaderFields(["Content-Type":"application/x-www-form-urlencoded; charset=UTF-8"])
    default:
        return endPointWithAuthHeader(endpoint)
    }
}

**Comment by ashfurrow** [comment]
That would URL encode it, which might be what you want, I'm not sure of your server setup. 

In general, yes, this is exactly how you customize attributes of requests, through the endpoints closure.

**Comment by sunshinejr** [comment]
I think we can close this one for now, if anything pops out, let us know! 🐼

**Comment by KimSmitth** [comment]
@sunshinejr @ashfurrow @ivanruizscm I have encountered this issue too. But there is no `endpointByAddingParameterEncoding` method in Moya 10.0.0 anymore. Could you guide me how to do this?
