### ISSUE TITLE
Updating to 6.2 makes the request duration really longer and (sometimes) never call the completion

### ISSUE THREAD

**Issue by tbaranes** [Moya/Moya#419]
After updating to Moya 6.2, I'm getting some really weird issues:
- Some requests never come back (Charles, a HTTP tracker, get a response 200), but Moya never call the completion. Apparently, that happens only with the GET method, the POST request is responding well
- The request duration has increased a lot: 58ms (6.1.3) -> 10s (6.2). These numbers are from Charles

I confirm that these both bugs has been creating in the 6.2. Rolling back to v6.1.3 solve both of them.
I also look at the CHANGELOG, but didn't see any breaking changes that could create these weird behaviours. 

Any ideas?

**Comment by ashfurrow** [comment]
Yikes! Looking through [the changes](https://github.com/Moya/Moya/compare/6.1.3...6.2.0), I don't see anything that immediately jumps out that would cause a slowdown like this... 

Could you describe your setup in more detail? Are you using CocoaPods or Carthage? I looked through Alamofire's recent issues and didn't see anything that might cause this either.

**Comment by tbaranes** [comment]
Sure. Moya and Alamofire are installed using CocoaPods, but not using `RxSwift`, or `ReactiveCocoa`.
Moya setup is completely inspired from your project `Eidodolon`, it's following exactly the same pattern, with some adaptations following the needs of my project.

I really don't get what could make this errors. I also tried to track them, but I got nothing yet. The only tips I got is that's working well with the version 6.1.3...

**Comment by ashfurrow** [comment]
Thanks for the details. I'm travelling right now but will try to reproduce locally. In the mean time, if anyone from @Moya/contributors could lend a hand, that'd be awesome. This is a pretty serious problem and we should make input top priority.

**Comment by sunshinejr** [comment]
@tbaranes Could you please try to clone the repo, then use the pod from the cloned repo (using the path in Podfile, like in Demo project) and go from commit with version 6.1.3. to the latest one? We could get the commit that produced the error and work with it. Other than that I don't see a reason for the behavior on the spot. :cry:

**Comment by tbaranes** [comment]
That's a great idea @sunshinejr. I will try that tomorrow at work and keep you in touch!

**Comment by sunshinejr** [comment]
@tbaranes Perfect! 🎉 I was trying to reproduce the long request on 6.2.0 but got nothing so far. Might be some edge case that you have on your environment. I will try again anyways 😇

**Comment by tbaranes** [comment]
I retried the v6.2.0 to make sure that the bug was always happening (who knows what's happening during the night...), and sadly, I encountered the same bugs.

Finally, I tracked the commit which _might introduced_ these issues as suggested by  @sunshinejr. The guilty commit would be (fe7d25c)[https://github.com/Moya/Moya/commit/fe7d25ced66c5f79e7028359fe71af9088a7691f]: _Add endpointByAdding method and refactor others._ :smiling_imp: 

Before this commit, everything is working as expected, but starting at this one, the both issues are starting.

Seems logical, but I'm using `endpointByAddingHTTPHeaderFields` to add the authorisation token in my project, which is the main change fro the commit.

**Comment by tbaranes** [comment]
I was curious about it, so I started some tests, I rollback to Moya 6.2.0, and replace some of the changes from the evil commit. 

If I rollback the implementation of `endpointByAddingHTTPHeaderFields` and `endpointByAddingParameters`, everything is working well.

**Comment by tbaranes** [comment]
I think I got it. I'm making some tests, then creating PR.

**Comment by tbaranes** [comment]
Seems we are not completely done with that one :laughing: 
I reproduced exactly the same bugs, and this time, they are easy to reproduce (now I know why am I getting them :see_no_evil:)

- Create a provider by using a custom endpoint closure  / resolver
- In your closure / resolver, do nothing
- Send a request 

Something like: 

```
let provider = MoyaProvider(endpointClosure: Networking.endpointsClosure(),
        requestClosure: Networking.endpointResolver(),
        manager: Networking.defaultAlamofireManager(),
        plugins: plugins)
}

    static func endpointResolver<T where T: TargetType>() -> MoyaProvider<T>.RequestClosure {
        return { (endpoint, closure) in
            let request: NSMutableURLRequest = endpoint.urlRequest.mutableCopy() as! NSMutableURLRequest
            closure(request)
        }
    }
    
    static func endpointsClosure<T where T: TargetType, T: QuizAPIType>()(_ target: T) -> Endpoint<T> {
        var endpoint: Endpoint<T> = Endpoint<T>(URL: url(target), sampleResponseClosure: {.NetworkResponse(200, target.sampleData)}, method: target.method, parameters: target.parameters, parameterEncoding: .JSON)
        }
        return endpoint
    }
```

In my case, I had an error in my implementation (didn't need a closure / resolver in this context), but I do think that is some bugs case left.

Let me know if I can help!

**Comment by ashfurrow** [comment]
Hmm interesting, yikes. If this is still an issue, let's re-open so this stays on our radar.

**Comment by ashfurrow** [comment]
@tbaranes I'm not sure I quite follow the remaining issues, could you clarify? Is this a case of not calling `closure(request)`?

**Comment by tbaranes** [comment]
The remaining issues are the same as the first ones but with another implementation:
- Some requests never come back (Charles, a HTTP tracker, get a response 200), but Moya never call the completion. Apparently, that happens only with the GET method, the POST request is responding well
- The request duration has increased a lot: 58ms (6.1.3) -> 10s (6.2). These numbers are from Charles

The first time, I was getting these issues by using a headers without params (that one was fixed in #420), but I reproduce these case by setting an endpoint / resolver, but without doing nothing in (like in my above example).

**Comment by ashfurrow** [comment]
OK, this sounds like a serious problem. I'll take a look this afternoon. From your description, it sounds like I should just be able to load the Demo app (hitting GitHub's API) and see reeeaaally slow responses, aye?

**Comment by tbaranes** [comment]
Think so, I mean, I reproduce it easily in my own project, so it shouldn't be hard to have it with the demo project.

Anyway, it's not that serious since we can easily has a workaround this time!

**Comment by ashfurrow** [comment]
Ah, I think I see! So this:

> I reproduce these case by setting an endpoint / resolver, but without doing nothing in (like in my above example).

You mean something like this?

```swift
{ (endpoint: Endpoint<StructTarget>, done: NSURLRequest -> Void) in
    requestedURL = endpoint.URL
    // specifically _not_ calling done(endpoint.urlRequest)
}
```

So the problem is not calling `done`? Or is it when you _just_ call it, as in your example?

```swift
{ (endpoint: Endpoint<GitHub>, done: NSURLRequest -> Void) in
    let request: NSMutableURLRequest = endpoint.urlRequest.mutableCopy() as! NSMutableURLRequest
    done(request)
}
```

I've tried it the second way, and I'm not seeing the slow network calls.

**Comment by tbaranes** [comment]
Hmm, I'm gonna make a try next week using the demo project. 
I will reopen it if I reproduce that issue again

**Comment by tbaranes** [comment]
Sorry for the delay, but I try it again, and I definitely have a bug, when I'm using an `endpointClosure`, the request makes 10s to come back, without it, it takes 50ms.

The endpoint has no parameters, and no headers. It's like an empty endpoint. Here the closure:

```
    static func endpointsClosure<T where T: TargetType, T: QuizAPIType>()(_ target: T) -> Endpoint<T> {
        var endpoint: Endpoint<T> = Endpoint<T>(URL: url(target),
                                                sampleResponseClosure: {.NetworkResponse(200, target.sampleData)},
                                                method: target.method,
                                                parameters: target.parameters,
                                                parameterEncoding: .JSON)
        if target.addAuth {
            endpoint = endpoint.endpointByAddingHTTPHeaderFields(["Authorization": "Token \"\(UserManager().apiAuth ?? "")\""])
        }
        return endpoint
    }
```

When initialise my provider without endpoint, it's working as expected:

```
    static func newDefaultNetworking() -> Networking {
        let provider: APIProvider<QuizAPI> =  APIProvider(manager: Networking.defaultAlamofireManager(), plugins: plugins)
        return Networking(provider: provider)
    }
```

but when setting an endpoint, the request is really longer:

```
    static func newDefaultNetworking() -> Networking {
        let provider: APIProvider<QuizAPI> =  APIProvider(manager: Networking.defaultAlamofireManager(), endpointClosure: Networking.endpointsClosure(), plugins: plugins)
        return Networking(provider: provider)
    }
```

I'm gonna check this deeper.

**Comment by tbaranes** [comment]
A workaround: `parameterEncoding: target.parameters?.count > 0 ? .JSON : .URL`
I will try to go deeper when I will have more time.

**Comment by petester42** [comment]
Are you sure that `UserManager().apiAuth` isn't taking a long time to execute?

**Comment by tbaranes** [comment]
Yes, it's working well for all the others request, with or without apiAuth. The only change is that they are taking parameters.
Moreover, if I don't set `parameterEncoding` to `.JSON`, it's working well.

**Comment by tbaranes** [comment]
Just found my error, I was passing an empty dictionary `[:]` in parameters instead of `nil`. Is that normal it takes longer just because I set `parameterEncoding` to `.JSON` and passing an empty dictionary?
