### ISSUE TITLE
Update docs with more detailed examples.

### ISSUE THREAD

**Issue by sunshinejr** [Moya/Moya#432]
We need more examples in our docs page. I'm thinking about making a Table of contents in our [Examples.md](https://github.com/Moya/Moya/blob/master/docs/Examples.md), where we could make few examples. One would be the easiest, the most basic setup with `.GET` request, then we could make another one with POST, another one with custom and specific examples of endpoints, stubs, and we could even add the setup with structs (vide #428). Also the **Examples** document feels like too much text at once, we could make something like description of _how_ you can setup Moya and _why_, and then the examples step by step. 

This is just an idea but we can brainstorm together 🤔

What are your thoughts? 🎉

**Comment by ashfurrow** [comment]
I like this idea, but I don't want the docs to get overwhelming. Maybe we should expand from a single `Examples.md` and do something more like "TargetExamples.md" etc? That way each document stays bite-sized.

Seems like a bit of a duplicate from https://github.com/Moya/Moya/issues/189 , what do you think? Might be worth having a milestone around documentation to gather all the ideas in one place. 

Probably related to #428 and #369 as well.

**Comment by sunshinejr** [comment]
First, milestone is a good choice, it would be much easier to read (also yeah, kinda a duplicate, sorry about that). About examples I agree that multiple files are a way to go, also we could have one file that will guide new user through examples, like in this file you can learn basic and the simplest usage, then here you have this and that because reasons. Or maybe do it in the main docs? Hmm 🤔

**Comment by ashfurrow** [comment]
I think this might be a good structure:

```
docs/
  Targets.md
  ... etc ...
  Examples/
    Readme.md
    TargetExamples.md
    ... etc ...
```

Then the readme in the new directory can be a guide to the other documents, like [what we have now](https://github.com/Moya/Moya/tree/master/docs).

**Comment by sunshinejr** [comment]
I _really_ like that one! 🙌

**Comment by Dschee** [comment]
I would appreciate more detailed examples a lot.

I'm currently trying to implement an API the Moya way but I'm struggling with all the options and plugins and how to actually integrate them. Specifically it's not clear to me from reading the current docs which parts are required and what the default behavior of Moya is if only the required things are implemented. Also I can't figure out how to add a logging plugin right now – seems like I have to dig much deeper into Moya than I wanted to. I think things would be much easier if multiple examples were provided.

**Comment by sunshinejr** [comment]
Thank you for your input, @Dschee ! 🎉 

Yeah, we know that our documentation has to be improved. We are working on it and every hint at what we could improve is a great help. While I understand the problem with the required implementation, I kinda don't think I understand the logging part. Could you explain what exactly do you have in mind?

Also if you have any other feedback about current docs, feel free to write it here. Thanks!✌️

**Comment by Dschee** [comment]
Thank you @sunshinejr for getting back to me so quickly.

I think the **best way to answer your question** and clarify what I mean is to **provide a PR** with updated Docs – please take a look at #438. Thank you!

**Comment by ashfurrow** [comment]
What else is missing now that #438 is merged?

**Comment by sunshinejr** [comment]
Close in favor of #466.
