### ISSUE TITLE
make convertResponseToResult accessible

### ISSUE THREAD

**Issue by aloco** [Moya/Moya#433]
Hi!

I just hit the situation that I have to use  `Alamofire` / `AlamofireImage` directly for specific requests. I am using `ReactiveMoya` and would like to integrate those specific calls into my chains of Signals without mapping the Values and Errors to ReactiveMoya´s equivalents manually. Therefore it would come in handy if `convertResponseToResult`would be accessible from outside the module.

https://github.com/Moya/Moya/blob/master/Source/Moya.swift#L249-L262

Any thoughts / concerns on this?

**Comment by ashfurrow** [comment]
Sounds reasonable to me – it simply wasn't included because we didn't see a need for it. Clearly there is one :) Would you be able to submit a pull request? Adding a comment above the function and an entry into the changelog would be 💯  
--  
Ash Furrow
https://ashfurrow.com/
