### ISSUE TITLE
Moya vs Alamofire with API Param Abstraction

### ISSUE THREAD

**Issue by gedward** [Moya/Moya#435]
Love the concept of Moya, just reading the docs and struggling to see the benefits of it compared to just using vanilla Alamofire with an enum that conforms to URLRequestConvertible: https://github.com/Alamofire/Alamofire#api-parameter-abstraction

I like that Moya formalizes the pattern, as it does seem like a side thought in the Alamofire readme. But are there other intentions/benefits compared to it?

*Moya*:
```
provider.request(.UserProfile("ashfurrow")) { result in
    // do something with the result
}
```

*Alamofire*:
```
Alamofire.request(Router.UserProfile(name: "ashfurrow"))
    .responseJSON { response in
        // do something with the result
    }
```

**Comment by colinta** [comment]
Stubbed responses, for one (testing as a first-class consideration).

**Comment by ashfurrow** [comment]
Yup, the main features of Moya are:

- Compile-time checking for correct API endpoint accesses.
- Lets you define a clear usage of different endpoints with associated enum values.
- Treats test stubs as first-class citizens so unit testing is super-easy.

But philosophically, Moya represents a framework that encourages developers to think about the network calls they want to make upfront, to encourage more thoughtful coding.

Let us know if we can clarify anything!

**Comment by gedward** [comment]
That makes sense, thanks! I'd love if that was in the readme, but I see it in action in the demo. I'm going to close this.

**Comment by ashfurrow** [comment]
I'd happily review a pull request 😉
--  
Ash Furrow
https://ashfurrow.com/
