### ISSUE TITLE
underlying issue on cancel a request

### ISSUE THREAD

**Issue by jasl** [Moya/Moya#440]
PS: I can't judge this is a bug of Moya or just a wrong usage, and this is my thought, not proving yet.

For example, I use `NetworkActivityPlugin`, and I can set a `NetworkActivityClosure` to do something about UI, like set a loading tips on sending request, and hide after received response.

In most case, that should be worked fine, but if I cancel the request, `hide after received response` may not work, because `PluginType#didReceiveResponse` invoked in [Alamofire's completion](https://github.com/Moya/Moya/blob/master/Source/Moya.swift#L210).

**Comment by ashfurrow** [comment]
Hi @jasl – thanks for the bug report. I'd like to ask you to rephrase your comment about carelessness, as it could be interpreted as an accusation; we aim to discuss bugs without calling anyone's abilities into question. Thanks for helping keep Moya a positive place :bow: 

Sounds like this is always reproducible? Like it's not intermittent? When you get a chance, could you post a code snippet or PR a failing unit test to demonstrate the bug? Thanks!

**Comment by jasl** [comment]
@ashfurrow I'm very sorry for inappropriate words, I'm not to offensive, you know... I've edited the issue. very sorry.

I'm just thinking that, it seems if cancel the Alamofire Request, the response completion will not be triggered. 

`PluginType#didReceiveResponse` invoked in [Alamofire's response completion](https://github.com/Moya/Moya/blob/master/Source/Moya.swift#L210)

The point is, does `PluginType#didReceiveResponse` should always be invoked for request? if yes, that would be a bug.

pseudocode for example

```swift
// In a ViewController
let networkActivityClosure: NetworkActivityPlugin.NetworkActivityClosure = { change in
  switch change {
  case .Began:
    ShowTipBar()
  case .Ended:
    HideTipBar()
  }
}

let networkActivityPlugin = NetworkActivityPlugin(networkActivityClosure: networkActivityClosure)
let provider = MoyaProvider<GithubAPI>(plugins: [networkActivityPlugin])

// do a request
let cancellableToken = provider.request(.UserProfiles) { result in
  // do something
}
```

if networking toooo terrible, and for some reason I cancel the request by `cancellableToken.cancel()`, the `HideTipBar` may not be triggered.

**Comment by jasl** [comment]
have read the doc again,
in <https://github.com/Moya/Moya/blob/master/docs/Providers.md#plugins>
```swift
    /// Called by the provider as soon as a response arrives
    public func didReceiveResponse(data: NSData?, statusCode: Int?, response: NSURLResponse?, error: ErrorType?, target: TargetType) {
        networkActivityClosure(change: .Ended)
    }
```
the comment and the functional naming is clear and point out that will be called when response arrives

but, as the doc tips `This is useful for working with the network activity indicator`, if the response not arrives (the request be canceled or some other reasons), the `.Ended` state would not be reached, and if developer not consider this possibility, that would have issue.

**Comment by jasl** [comment]
My mistake, just do some experiment, when cancel a request, the callback will be triggered but got `Error Domain=NSURLErrorDomain Code=-999 "cancelled"`

Sorry for my inappropriate words again @ashfurrow , just closing the issue.

**Comment by ashfurrow** [comment]
No problem! Thanks for looking into this, I'm sure it'll help when someone else has this issue. If you have any suggestions for documentation improvements, please let us know :bow:

**Comment by jasl** [comment]
Yes!

- <https://github.com/Moya/Moya/blob/master/Source/Plugins/NetworkActivityPlugin.swift#L9>
- <https://github.com/Moya/Moya/blob/master/Source/Plugins/NetworkActivityPlugin.swift#L26> the `didReceiveResponse` not only triggered by the response arrives but also the request be cancelled.

**Comment by ashfurrow** [comment]
Cool! Could you open a new issue with suggestions or – if you're comfortable – a pull request with the changes?

**Comment by jasl** [comment]
No problem! I'll give a PR later.
