### ISSUE TITLE
Enums with private types

### ISSUE THREAD

**Issue by esttorhe** [Moya/Moya#447]
I know #408 addresses some of the issues with `enum`s and `struct`s but today a friend (@PiXeL16) showed me this link: [`Enums with private types`](http://cjwirth.com/2016/03/14/easier-enums/?utm_campaign=Swift%2BSandbox&utm_medium=email&utm_source=Swift_Sandbox_33) and the first thing that came to my mind was how this could benefit a project like `Moya`.

Would love to have the @Moya/contributors weight on this and perhaps analyze if its worth going through the pain of implementing this or if its too much with too little benefit.

Regardless of what the decision is I thought it was worth bringing this to everyone @ `Moya`.

PS. If this was already shared/discussed apologies.

**Comment by ashfurrow** [comment]
Interesting article! I hadn't seen that, I'll take a look :+1:

**Comment by ashfurrow** [comment]
I confess I've not had a chance to give this consideration, will add to my todo list :+1:

**Comment by BasThomas** [comment]
Hmm, after looking through Moya's code, I don't really see how we can use this to enhance it. Maybe I am missing something. 🤔

**Comment by BasThomas** [comment]
Closing this for now, please reopen if you *do* find a way to improve the enums with private types.
