### ISSUE TITLE
Error when build with carthage

### ISSUE THREAD

**Issue by rmuhamedgaliev** [Moya/Moya#449]
*** Building scheme "Moya iOS" in Moya.xcodeproj
*** Building scheme "ReactiveMoya iOS" in Moya.xcodeproj
** BUILD FAILED **

The following build commands failed:
	CompileSwift normal arm64 /Users/rmuhamedgaliev/Projects/TemplateApp/Carthage/Checkouts/Moya/Source/ReactiveCocoa/RACSignal+Moya.swift
	CompileSwift normal arm64 /Users/rmuhamedgaliev/Projects/TemplateApp/Carthage/Checkouts/Moya/Source/Error.swift
	CompileSwift normal arm64 /Users/rmuhamedgaliev/Projects/TemplateApp/Carthage/Checkouts/Moya/Source/Image.swift
	CompileSwift normal arm64 /Users/rmuhamedgaliev/Projects/TemplateApp/Carthage/Checkouts/Moya/Source/Plugins/NetworkActivityPlugin.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(5 failures)
: Auto-Linking supplied '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/XCTest', '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/XCTest' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target.
ld: warning: linking against a dylib which is not safe for use in application extensions: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos/libswiftXCTest.dylib
ld: warning: Auto-Linking supplied '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/XCTest', '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/XCTest' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target.
ld: warning: linking against a dylib which is not safe for use in application extensions: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator/libswiftXCTest.dylib
ld: warning: linking against a dylib which is not safe for use in application extensions: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks/XCTest.framework/XCTest
ld: warning: linking against a dylib which is not safe for use in application extensions: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator/libswiftXCTest.dylib
ld: warning: linking against a dylib which is not safe for use in application extensions: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks/XCTest.framework/XCTest
<unknown>:0: error: unable to execute command: Segmentation fault: 11
<unknown>:0: error: compile command failed due to signal (use -v to see invocation)
A shell task failed with exit code 65:
** BUILD FAILED **

The following build commands failed:
	CompileSwift normal arm64 /Users/rmuhamedgaliev/Projects/TemplateApp/Carthage/Checkouts/Moya/Source/ReactiveCocoa/RACSignal+Moya.swift
	CompileSwift normal arm64 /Users/rmuhamedgaliev/Projects/TemplateApp/Carthage/Checkouts/Moya/Source/Error.swift
	CompileSwift normal arm64 /Users/rmuhamedgaliev/Projects/TemplateApp/Carthage/Checkouts/Moya/Source/Image.swift
	CompileSwift normal arm64 /Users/rmuhamedgaliev/Projects/TemplateApp/Carthage/Checkouts/Moya/Source/Plugins/NetworkActivityPlugin.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(5 failures)

**Comment by ashfurrow** [comment]
This looks similar to #445, could you try the solution from there? (Something about `carthage update --platform iOS --no-use-binaries` and deleting a folder.)

**Comment by alskipp** [comment]
Wasn't sure whether to open a new issue, or add to this one? I'm experiencing trouble trying to build the dependencies with Carthage too, but a different error:
`xcodebuild timed out while trying to read Rx.xcworkspace 😭`

* * *

Xcode 7.3, Carthage 0.15.2 
(Using: `carthage update --platform iOS --no-use-binaries`)

**Comment by ashfurrow** [comment]
Hmm, sounds like a different problem. Discussing here sounds fine. 

Afraid I'm not very knowledgeable about Carthage, looping in @Moya/contributors to get another set of eyes. I didn't see any related [issues](https://github.com/ReactiveX/RxSwift/issues) on RxSwift or [ReactiveCocoa](https://github.com/ReactiveCocoa/ReactiveCocoa/issues). What would help diagnose the problem would be the contents of your Cartfile.

**Comment by alskipp** [comment]
Perhaps I'm misunderstanding how to set up the project, but I'm just trying to build the dependencies for Moya itself, using the Moya Cartfile. Was hoping to contribute towards Moya, but fell at the first hurdle 😂

**Comment by Dschee** [comment]
Did you follow the complete insallation instructions like written in the Carthage docs [here](https://github.com/Carthage/Carthage#getting-started) including adding the copy-frameworks build script?

**Comment by justinmakaila** [comment]
@alskipp So you're running with a freshly cloned version of Moya, and just trying to run `carthage update --platform iOS --no-use-binaries` in the root of the directory, right?

**Comment by alskipp** [comment]
@justinmakaila, yep pretty much (just forked Moya).

**Comment by justinmakaila** [comment]
@alskipp Are you trying to open the `Moya.xcodeproj`, or the `Demo/Demo.xcworkspace`? Also, see my comment above. I edited it, probably after the notification was sent out.

**Comment by alskipp** [comment]
@justinmakaila I've been trying to open the `Moya.xcodeproj`, am I about to have a “D’oh!” moment?

**Comment by alskipp** [comment]
D’oh! So the correct way of getting started is to run `pod install` in the `Demo` folder then make any changes in the `Demo/Demo.xcworkspace`?

**Comment by justinmakaila** [comment]
@alskipp No, you should be able to edit the source in the `Moya.xcodeproj`, and then the CocoaPods implementation in `Demo` pulls that in as a Development Pod. `Demo` houses the implementation tests/examples, and the unit tests.

I just cloned the repo into a new folder, `cd`'d in, and ran `carthage update --platform iOS --no-use-binaries` with no problem.

I'm thinking your issue could be with the Carthage cache, perhaps pulling old versions of the dependencies?

`rm -rf ~/Library/Caches/org.carthage.CarthageKit/dependencies/`

**Comment by alskipp** [comment]
@justinmakaila, thanks for the suggestion. Just tried clearing the cache, but still no joy (same inexplicable error) : (

Perhaps things will settle down a bit once a few more people have battle tested Xcode 7.3/Swift 2.2 and the next version of Carthage is released? In the meantime, I'm going to retrain as a carpenter – a craft that can be indulged in without fear that your tools are conspiring against you! : )

**Comment by justinmakaila** [comment]
@alskipp can you send me the output of the carthage build? the issue always lies in there, and not in the console output.

**Comment by momo13014** [comment]
carthage version 0.17.2
Xcode     version 10.11.6
When I run carthage update --platform iOS --no-use-binaries, I got the error :xcodebuild timed out while trying to read CoreDataLogger.xcodeproj 😭.

**Comment by petester42** [comment]
What happens if you use the most recent Carthage version. I think it's 0.18.1
