### ISSUE TITLE
New Pod Owners

### ISSUE THREAD

**Issue by ashfurrow** [Moya/Moya#454]
Currently, I'm the only one who deploys Moya releases. This sucks because I'm not always available to do it, and I don't want to be a bottleneck for anyone else. 

So, I'm looking for existing contributors who are willing and able to occasionally release a new Moya version. It's not a huge job at all, but I feel like it's a bigger responsibility than being a contributor, so there's absolutely no pressure to accept. @petester42 @colinta @esttorhe @aschuch anyone interested?

(I would need to add some documentation around _how_ to make a release as well.)

**Comment by colinta** [comment]
I'm not at all opposed to helping out with this, would love to have someone else involved to "have my back" (look over the release, sanity check that it's good to go, etc).

**Comment by petester42** [comment]
I'd be down to help with releases.

**Comment by sunshinejr** [comment]
I could help as well if needed.

**Comment by ashfurrow** [comment]
Awesome, I've added you three :tada: Thanks so much. I'll submit a doc about deploying this weekend.

**Comment by ashfurrow** [comment]
It's basically just `rake release["X.Y.Z"]` and mostly everything else is automatic.

**Comment by esttorhe** [comment]
interesting; github did not notify me of this

aaaaanyways; If you need more hands i'm down to help with this as well
