### ISSUE TITLE
RxMoyaProvider.mapArray/mapArrayOptional in nested structures? 

### ISSUE THREAD

**Issue by freak4pc** [Moya/Moya#461]
Hey! I'm just starting off with RxSwift/RxMoya and trying to figure out something that seems like it should be very simple. 

I have an HTTP request that returns a data array in the following format: 
```JSON
   {data: 
       {results:  [...] 
   }
```

So, the response isn't a flat JSON Array, there's some cascading. 
So the following code would clearly not work. 

```swift
    self.provider
        .request(Marvel.Characters(startsWidth: "Iron", limit: nil, offset: nil))
        .debug()
        .mapArrayOptional(MarvelCharacter.self)
```

So, I guess I need to some how map the response to expose just the `results` field before passing it to `mapArrayOptional` ? Or there's a more global way to define the response structure expected from the server? 

Would appreciate your help on this :)

Thanks
Shai

**Comment by sunshinejr** [comment]
Hey Shai!

I'm afraid there is no direct solution other than mapping response to have the top object that should be the array with objects. 😢

**Comment by freak4pc** [comment]
Thanks @sunshinejr! 
How would that look? I need to map from one Response to a new Response and pass that? Could you help with some sample code?

**Comment by aschuch** [comment]
Although I don't use RxSwift, [I have done something similar](https://github.com/aschuch/Argonaut/blob/master/Argonaut/JSONMapping%2BReactiveCocoa.swift#L55) for ReactiveCocoa and [Argo](https://github.com/thoughtbot/Argo). This might point you in the right direction.

**Comment by aschuch** [comment]
Actually, thinking about it again, my solution does not really work around your problem. However, Argo has a way to extract an object [based on a root key](https://github.com/thoughtbot/Argo/blob/b0b6920e5c34591e3884a4e50a740167e6cbaf68/Argo/Functions/decode.swift#L21).

**Comment by sunshinejr** [comment]
Sure! Here I have a method that gets user on a repository given name. Let's say I give name **Moya/Moya**, it does the request here, and retrieves the **owner** object to parse it:
```swift
    func getUser(byRepoName name: String) -> Observable<User> {
        return self.provider
            .request(GitHub.Repo(fullName: name))
            .debug()
            .map { response -> Response in
                guard let responseDict = try? response.mapJSON(),
                    owner: AnyObject = responseDict["owner"],
                    newData = try? NSJSONSerialization.dataWithJSONObject(owner, options: NSJSONWritingOptions.PrettyPrinted) else {
                    return response
                }
                
                let newResponse = Response(statusCode: response.statusCode, data: newData, response: response.response)
                return newResponse
            }
            .mapObject(User.self)
    }
```

**Comment by freak4pc** [comment]
Perfect @sunshinejr  ! That's exactly what I tried to do and started doing but thanks for refining that. 
Is there any way to do that globally? meaning, for every request? because this data structure (data->results->actual array) is global to the entire API I'm using. 

Also thanks for your attempt to assit @aschuch ! :] 

![image](https://cloud.githubusercontent.com/assets/605076/14227937/8b8c0fce-f910-11e5-8eda-63857ba2132f.png)

**Comment by sunshinejr** [comment]
Sure! You can make your own mapper extensions for it :)
```swift
extension ObservableType where E == Response {
    func marvelMapArrayOptional<T: Mappable>(type: T.Type) -> Observable<[T]?> {
        return map { response -> Response in
            // your map
        }
        .mapArrayOptional(type)
    }
}
```

Just copy your map code above and you should be fine. And then you could use `marvelMapArrayOptional` instead of `mapArrayOptional`. You could also do a generic method if you would like to do it for more methods like `mapObject` and so on. Hope it helps! 🎉

**Comment by freak4pc** [comment]
Perfect! Thank you! :] 
Is there a Moya slack channel or something of sorts or all questions should be filed here? I'm sure more  questions will pop as I start digging deeper into this.

**Comment by sunshinejr** [comment]
Unfortunately we don't have a slack channel, but you could try asking on the RxSwift channel if it is more connected to RxSwift, or on this slack for ios-devs, they are all very helpful. Of course you could still ask the questions on here, no problem with that as well 🎉

**Comment by freak4pc** [comment]
So another question I had is , Is there a way to merge two `maps` together ? 

e.g. , I'm mapping something likes this 
```json 
    {"thumbnail": 
        {"path": "http://some.path.to/file", 
         "extension": "jpg"}
   }
```

Right now in my `Mappable` I'm doing
```swift
try thumbPath   = map.from("thumbnail.path")
```

but I would like `thumbPath` to include both `thumbnail.path` and `thumbnail.extension`, concatenated together. Any way to merge those?

**Comment by sunshinejr** [comment]
That is actually a question for [Mapper](https://github.com/lyft/mapper) rather than Moya itself, so please make an issue there. Other than that it would be really helpful if you could make new issues as the questions go, it will be then useful for other people if they need the answer as well (rather than scrolling). Thanks!
