### ISSUE TITLE
"ERROR invalid body size" when submitting an GET request with parameters

### ISSUE THREAD

**Issue by mingyeow** [Moya/Moya#463]
The following GET is submitting an invalid request to my Rails server, which is actually rejecting it outright without even processing it. It is similar to this SO request [here ](http://stackoverflow.com/questions/23834179/heroku-rails-log-error-message-on-text-field-error-invalid-body-size)

I know my setup works because it has been working fine before i added the parameters to the GET request, and it works for POST requests.

1) I would like to print and see the full request it is making to the server. Is there a way to automatically print the full network request?
2) Is there anything i can change to make the GET work?

M

```
extension Routes: TargetType {
  var baseURL: NSURL { return NSURL(string: "http://localhost:3000")! }
  
  var path: String {
    switch self {
    // POST REQUEST - WORKS
    case .CreateUser:
      return "/users.json"
    // GET REQUEST - FAILS WHEN THERE ARE PARAMETERS
    case .Stickers:
      return "/stickers.json"
    }
  }
  
  var method: Moya.Method {
    switch self {
    case .CheckUsernameAvailability, .CreateUser:
      return .POST
    default:
      return .GET
    }
  }
  
  
  var parameters: [String: AnyObject]? {
    switch self {
    case .CreateUser (let username, let phoneNumber):
      return ["username":username, "phone_number": phoneNumber ]
    case .Sticker:
      return ["test""test]
    default:
      return nil
    }
  }
  

let endpointClosure = { (target: Routes) -> Endpoint<Routes> in
  let epc = Endpoint<Routes>(URL: url(target), sampleResponseClosure: {.NetworkResponse(200, target.sampleData)}, method: target.method, parameters: target.parameters,         parameterEncoding: .JSON )

  return epc.endpointByAddingParameters(target.defaultParameters)
}

```

**Comment by Austinate** [comment]
Hi! Let me try to help you :) 
1) When you're creating request via your MoyaProvider — it returns you a thing conforming to Cancellable protocol.
 You can simply print it to your logs so see how you can re-create this request via curl
2) I believe you should use .URL parameters encoding for get request, instead of .JSON

**Comment by mingyeow** [comment]
thanks! both works great. 

i was not aware of the need to use .URL when doing GET requests. :)

**Comment by mingyeow** [comment]
By the way, @Austinate is there an example of using headers to pass in authentication information like tokens?

**Comment by Austinate** [comment]
OAuth & HTTPAuth are described [here](https://github.com/Moya/Moya/blob/master/docs/Authentication.md)

But if you need just token as header field — i'd configure custom Alamofire.Manager with header fields as described [here](https://github.com/Moya/Moya/blob/master/docs/Providers.md).
 I'm not 100%(just 99.9% 🙃) sure that's the best way for Moya, so maybe someone will correct me

**Comment by Austinate** [comment]
@mingyeow for additional fields just take a look at [Alamofire readme](https://github.com/Alamofire/Alamofire) (Advanced Usage section)

**Comment by sunshinejr** [comment]
For additional token fields you could use Endpoint settings, explained [here](https://github.com/Moya/Moya/blob/master/docs/Endpoints.md#from-target-to-endpoint-) (with auth token as well).

**Comment by Austinate** [comment]
0.01% ¯\_(ツ)_/¯
