### ISSUE TITLE
RequestClosure error

### ISSUE THREAD

**Issue by dccarmo** [Moya/Moya#465]
How should I handle an error on requestClosure? Right now it only has a `done` call, but what if my OAuth provider fails to authenticate a request?

**Comment by ashfurrow** [comment]
Hmm, this is a really good question – this isn't a scenario we thought about when making the request closure asynchronous. I think it would make sense for Moya to provide a way for the request closure to produce an error – this would be a new addition to Moya, and likely a breaking change. @Moya/contributors anyone have thoughts/feels about this?

**Comment by morgz** [comment]
I currently check oauth credentials in the requestClosure and would appreciate the ability to bubble out an error back out.

**Comment by ashfurrow** [comment]
I think that's a smart move. Maybe make the parameter for `done()` be a `Result<NSURLRequest, ErrorType>`? It would be a breaking change, but we already have several of those merged in master, so now is an idea time to make this kind of change. Is anyone interested in sending a PR?

**Comment by sunshinejr** [comment]
Sure! I can take at that.

**Comment by sunshinejr** [comment]
Closing in favor of #488.
