### ISSUE TITLE
Url optional query parameters

### ISSUE THREAD

**Issue by bitomule** [Moya/Moya#468]
I want to include some optional query parameters in my request. What's the best way to do it? Can't find any example of query parameters.

For example. How can I call:

`api/users?limit=10`

but also:

`api/users`

**Comment by ealeksandrov** [comment]
Try this:

```swift
public enum MyService {
	case Users(limit: Int?)
}

extension MyService: TargetType {
//...
	public var parameters: [String: AnyObject]? {
	        switch self {
	        case .Users(let limit):
	            var params: [String : AnyObject] = []
				params["limit"] = limit
	            return params
	        default:
	            return nil
	        }
	    }
//...
}
```

In this case `params["limit"] = nil` will be equal of removing object for key `limit`.

**Comment by bitomule** [comment]
But parameters is for POST parameters no? I need optional GET parameters.

**Comment by ealeksandrov** [comment]
Doesn't matter, method type is defined in separate property

```swift
extension MyService: TargetType {
//...
    public var method: Moya.Method {
        switch self {
        case .EmailAuth:
            return .POST
        default:
            return .GET
        }
    }
//...
}
```

**Comment by bitomule** [comment]
You're right. I'm going to try that way. Thanks!

**Comment by vfunc** [comment]
I have same question ， are you fix up？

**Comment by BasThomas** [comment]
What is your problem exactly? Check the samples above or check the [docs](https://github.com/Moya/Moya/blob/master/docs/Examples/OptionalParameters.md).

**Comment by vfunc** [comment]
i'm wrong.  if moya  Response: Received empty network. You can check your network,then check ParameterEncoding.
