### ISSUE TITLE
Handle empty response

### ISSUE THREAD

**Issue by bitomule** [Moya/Moya#469]
I have some API endpoints with PATCH or DELETE that just return empty body and 204 code.

¿How can I handle those cases?

Right now I get and Underlying error with NSCocoaErrorDomain and Code=3840 saying "No value."

**Comment by kevin5396** [comment]
Same here :(

**Comment by kevin5396** [comment]
@bitomule Did you use ~.mapJson()~ or something like that?
After I removed it and manually convert it to json in the handler(process error response), it worked.

**Comment by bitomule** [comment]
@kevin5396 I'm finally using another method for those api calls

**Comment by ashfurrow** [comment]
@bitomule what method did you end up using?

**Comment by bitomule** [comment]
Those methods also do image and files uploading so I just ended using pure alamofire

**Comment by ashfurrow** [comment]
Okay to close this issue?

**Comment by bitomule** [comment]
@aschuch nop, it's not fixed. Moya needs to handle 204 no-content responses

**Comment by ashfurrow** [comment]
Do we know how/if Alamofire handles this? Moya's goal is to abstract away the actual network layer, so handling these types of responses seems like it's something we should take responsibility for.

**Comment by bitomule** [comment]
Ok, I've managed to handle empty responses. It was my fault, I was filtering status codes but no content comes with a 204 that was reported as error. Changed filter and now works.

**Comment by ashfurrow** [comment]
Glad you got it working! Is there anywhere in Moya's documentation where some info about empty responses would have been helpful to you? I'm sure you're not the only one to run into this.

**Comment by bitomule** [comment]
The issue I still have is with multipart / uploading files with moya but there's other issues for that. I don't think we can add something to make this clearer, it was my mistake.

**Comment by ashfurrow** [comment]
No problem, always feel free to open issues or send improvements to documentation.

**Comment by PatrickSCLin** [comment]
Can Moya just return 204 no content response directly instead of wait underlying error when request was GET ?
