### ISSUE TITLE
Moya with charles proxy

### ISSUE THREAD

**Issue by samirGuerdah** [Moya/Moya#471]
Hello,

When i use Moya i don't  see the in the charles proxy the detail of the request and the responses. if i remove Moya, all works fine ( I am using Alamofire).

Do you have any idea ? Thanks

**Comment by ashfurrow** [comment]
Hmm, hard to say. I've not used Charles much, are you stubbing the requests? Could you post the Moya code that's not working?

**Comment by colinta** [comment]
I've used Charles w/ Moya a ton - but when we added SSL pinning, that causes Charles to stop working.

**Comment by jimmy0251** [comment]
Charles works fine for me with Moya without any additional configuration. Please make sure you've not excluded domain from logging.

**Comment by samirGuerdah** [comment]
Very strange. I am using Moya in a sample way ( Just a target with an endpoint to add additional headers). I Will look what i am doing wrong and give you feedback very soon. Thanks

**Comment by ashfurrow** [comment]
@samirGuerdah Hey there! Did you get this working?

**Comment by fruitcoder** [comment]
@samirGuerdah What exactly is your problem? Actually SSL Pinning is used to prevent Man-In-The-Middle atacks with tools like Charles. Or don't you get any requests/responses regardless of whether they are encrypted or not?

**Comment by samirGuerdah** [comment]
Hello,

Sorry for the retarded response. Finally it was a misuse in my side. No problem to use Moya with Charles proxy. Closing...
