### ISSUE TITLE
How to implement multi parameters separated with comma

### ISSUE THREAD

**Issue by VivienGiraud** [Moya/Moya#474]
Hi,
I would like to know how can I implement this with Moya as I have no idea how to send multiple parameter separated with comma.

`curl -X GET "https://api.spotify.com/v1/albums/?ids=41MnTivkwTO3UUJ8DrqEJJ,6JWc4iAiJ9FjyK0B59ABb4,6UXCm6bOO4gFlDQZV5yL37"`

Thanks

**Comment by ashfurrow** [comment]
Hmm, good question. Generally, parameter encoding doesn't work like that (as far as I know). You'd more typically see `ids` sent as an array, like `ids[]=41MnTivkwTO3UUJ8DrqEJJ&ids[]=6JWc4iAiJ9FjyK0B59ABb4&ids[]=6UXCm6bOO4gFlDQZV5yL37`, but I admit it's been a while. Let's see how we would do what you're looking for.

This is how I would accomplish this; add an associated value to the `Album` enum case that holds a `String` array of the ideas:

```swift
case Albums(ids: [String])
```

Then, in the `parameters` implementation, do the following:

```swift
var parameters: [String: AnyObject]? {
  switch self {
    ...
    case .Albums(let ids):
      return ["ids": (ids as NSArray).componentsJoinedByString(",")]
    ...
  }
}
```

And that should do it. Let us know how it goes!

**Comment by Miasma87** [comment]
Seams that case Albums(ids: [String]) doesn't works.
![image](https://cloud.githubusercontent.com/assets/262924/14894778/9cf4398e-0d75-11e6-95d4-a7870b1e5619.png)

**Comment by colinta** [comment]
@Miasma87 This is an error with your swift code:

```
case .getSeveralAlbums(let ids):  // remove ': [String]' from your code
```

**Comment by colinta** [comment]
And it looks like you're in the wrong section - you should be modifying the `var parameters`, not the URL path.

**Comment by Miasma87** [comment]
@colinta Yeah but I will not be able anymore to pass Array, right?

**Comment by Miasma87** [comment]
@colinta But the array is passed through the `path`

**Comment by colinta** [comment]
Sure you can - the list of ids is assigned to the enum as an associated value.

The `path` is not supposed to include the `?-` GET parameters.  They will be added to the URL *for* you, when you return them from the `parameters` property.  Don't try to construct the entire URL yourself (like you might in JavaScript).

```swift
enum API {
  case .Status
  case .Albums([String])
}

var parameters: AnyObject? {
  switch self {
  case .Status: return nil
  case .Albums(let ids):
    return ["ids": (ids as NSArray).componentsJoinedByString(",")]
  }
}
```

**Comment by aehlke** [comment]
These solutions end up encoding the commas a `%2C` which isn't ideal.

**Comment by ashfurrow** [comment]
@Miasma87 has this issue been addressed to your satisfaction?

**Comment by VivienGiraud** [comment]
Hi, Sorry for the delay, I came back to this issue but I switch to Swift 3.
So now I'm stuck with a `Cannot call value of non-function type '((String) -> String)!'` On `.componentsJoined(",")`  
Any idea?
:/

**Comment by VivienGiraud** [comment]
Ok, I found it, it's:
`(embedded as AnyObject).componentsJoined(by: ",")`
Let me check that it works correctly and I come back here.

**Comment by VivienGiraud** [comment]
It seems to work :)
Thanks guys!
@aehlke Yeah I have the `%2C`  even adding `removingPercentEncoding` to `(embedded as AnyObject).componentsJoined(by: ",")` does not works :/

**Comment by sunshinejr** [comment]
@VivienGiraud glad you found out the issue! Also looking by code, if you are using Swift's Structs API for arrays (instead of `NSArray`), you don't have to cast it and you can just use `joinWithSeparator(_:)` (in Swift 2) or `joined(separator:)` (in Swift 3) method:
```swift
["test", "test2"].joined(separator: ",")
```

**Comment by VivienGiraud** [comment]
Yeah, that's what I did :)
Thanks!

**Comment by aniruddha211** [comment]
Hi , 
I am facing same issue,    // MARK: - Parameters
    var parameters: Parameters? {
        var params = Parameters()
        switch self {
        case .jobList(let page, let pageSize, let jobTypes):
            params["page"] = page
            params ["statuses"] = jobTypes.joined(separator: ",")
            params["page_size"] = pageSize
        }
        return params
    }
    
It doesn't work.
