### ISSUE TITLE
Does not conform to protocol 'TargetType'

### ISSUE THREAD

**Issue by vishal91** [Moya/Moya#475]
Described all these . still getting error 

` public var baseURL: NSURL { get }
    public var path: String { get }
    public var method: Moya.Method { get }
    public var parameters: [String : AnyObject]? { get }
    public var sampleData: NSData { get }`

**Comment by sunshinejr** [comment]
Hey @vishal91. 🎉 Can you please provide the code where you described all of these? It will help us with helping you 😉

**Comment by vishal91** [comment]
`public var baseURL: NSURL { return NSURL(string: "https://api.myservice.com") }
    
    public var path: String {
        switch self {
        case .CustomerSignup://
            return "auth/customer_signup"
        case .SignupVerifyOTP://
            return ""
        case .ExistingCustomer://
            return ""
        case .SigninOTP://
            return ""
        case .Signin://
            return ""
        case .ResendOTP://
            return ""
        }
    }
    
    public var method: Moya.Method {
        switch self {
        case .CustomerSignup,
             .SignupVerifyOTP,
             .ExistingCustomer,
             .SigninOTP,
             .Signin:
            return .POST
        case .Services,
             .AppVersion:
            return .GET
        }
    }
    
    public var parameter: [String:AnyObject]? {
        switch self {
        case .MyTrips,.RateTrip,.UserDetail,.GetReferal,.GetSaveAddress,.PostSaveAddress,.ApplyPromo,.SendInvoice,.RateCard,.CreditBalance:
            return nil
        case .CustomerSignup(let phoneNo, let referelCode):
            return ["phoneNo":phoneNo,"referelCode":referelCode]
        default:
            return nil
        }
    }
    
    public var sampleData: NSData {
            return "Half measures are as bad as nothing at all.".dataUsingEncoding(NSUTF8StringEncoding)!
    }
    
    public func url(route: TargetType) -> String {
        return route.baseURL.URLByAppendingPathComponent(route.path).absoluteString
    }
`

**Comment by sunshinejr** [comment]
At a first glance, it seems like your switches in `method` (and/or) `path` are not exhaustive, there are different number of cases. I'd try to add `default` to both of them and see what happens.

**Comment by vishal91** [comment]
@sunshinejr : ok ..Thanks .. Will wait for reply

**Comment by vishal91** [comment]
@sunshinejr Basically i have removed some cases .. Don't wanna show . But i have encountered all the cases . Don't know where the problem is coming. And how we have secure tokens and refresh token .Moya does that ? How to pass header to endpoint. If this bug gets resolved

**Comment by ealeksandrov** [comment]
First of all, add `default` case to each `switch` and let us know. This should solve your issue, no matter how many cases you actually have.

You can add http headers in `endpointClosure`: https://github.com/Moya/Moya/blob/master/docs/Endpoints.md

**Comment by vishal91** [comment]
Added default to all the 'switch' . Same error.

**Comment by colinta** [comment]
Usually this error comes with more details, hidden behind a "disclosure triangle" - there's no other detail related to this error?

**Comment by vishal91** [comment]
@colinta : Thanks a lot @sunshinejr Issue solved parameter*s* s was missing :(

**Comment by colinta** [comment]
Cool! Glad to help!
