### ISSUE TITLE
How target.shouldRetry looks like?

### ISSUE THREAD

**Issue by SSamanta** [Moya/Moya#476]
I have seen below code in Moya [example](https://github.com/Moya/Moya/blob/6a437938c4ac3ae1d6ffce161cfb1fb3c78c67b9/docs/Examples.md) 

```
if target.shouldRetry {
    retryWhenReachable(target, successCallback, errorCallback, failureCallback)
}
```
Are there any example code how `shouldRetry` should looks like in real case?

**Comment by ashfurrow** [comment]
If you're able to use RxSwift or ReactiveCocoa, they have retry operators that make this easy. You can also see [an example](https://github.com/artsy/eidolon/blob/1c746f9a9c6420cda9f691468783fee67376e8b1/Kiosk/App/Networking/Networking.swift#L22-L31) of how to write try-when-network-is-available logic.

**Comment by asasdasasd** [comment]
@ashfurrow 
what does the example mean "// Take 1 to make sure we only invoke the API once."
is it mean after `online = true` then only one API will be invoked or  after offline time all the ignored API will be invoke?

**Comment by ashfurrow** [comment]
No, they all will be invoked. The `take(1)` is to protect against the following scenario:

1. Device is offline
1. App makes some network calls, which wait until the device is online
1. Devices goes online, network calls are made
1. Device goes offline again
1. Devices goes online again
1. App makes identical network calls

The `online` observable is going to send `true` or `false` every time the network status changes. We `ignore(false)`, but want to make sure that two `true` events don't trigger the `flatMap` more than once.

**Comment by asasdasasd** [comment]
@ashfurrow  thanks a lot , my previously thought is totally wrong. such a small detail contains so much information.
really admire you

**Comment by SuiFengLiuNian** [comment]
> If you're able to use RxSwift or ReactiveCocoa, they have retry operators that make this easy. You can also see [an example](https://github.com/artsy/eidolon/blob/1c746f9a9c6420cda9f691468783fee67376e8b1/Kiosk/App/Networking/Networking.swift#L22-L31) of how to write try-when-network-is-available logic.

How to realize the retrial request when R small s wift is not used ？？
