### ISSUE TITLE
Confused about NSError removal

### ISSUE THREAD

**Issue by Paldom** [Moya/Moya#478]
Hello,

as I see `Moya.Error`'s `nsError` property is depreceted (also confirmed by @sunshinejr in #437). What other solution would you recommend to get `NSError`'s domain from an `Underlying` type? I mean how can I get the reason of the error if e. g. if I receive the code of `NSURLErrorTimedOut` or `NSURLErrorNotConnectedToInternet`?

Thanks!

**Comment by ashfurrow** [comment]
The `nsError` property was created for use with ReactiveCocoa. If you want to get at an underlying response, you can `switch` on the error in your completion closure, like:

```swift
switch error {
  ...
  case .Underlying(let error as NSError):
  // now can access error.domain or whatever
}
```

It's a bit weird to have to case `error as NSError`, maybe the `.Underlying` case should use `NSError` instead of `ErrorType`. Any thoughts?

**Comment by Paldom** [comment]
Thanks @ashfurrow! I missed the `ErrorType` in `.Underlying`.

**Comment by ashfurrow** [comment]
No problem! This seems like something we might want to document better, and maybe make the change to `.Underlying` I mentioned above. You wouldn't be interested in making a pull request, would you?

**Comment by sunshinejr** [comment]
+1 for the change from `ErrorType` to `NSError`, also we should provide an example/document it better.

**Comment by Paldom** [comment]
I can make a pull request about this, only I'm not comfortable with casting `error` to `NSError` in `Response.swift` which should be done:
```
    /// Maps data received from the signal into a JSON object.
    func mapJSON() throws -> AnyObject {
        do {
            return try NSJSONSerialization.JSONObjectWithData(data, options: .AllowFragments)
        } catch {
            throw Error.Underlying(error as NSError)
        }
    }
```
As I see it won't be a problem, are you ok with that?

**Comment by ashfurrow** [comment]
If we change `.Underlying` to have an `NSError` instead of `ErrorType`, then we won't need to cast, right? In any case, casting from ErrorType to NSError is guaranteed to always succeed, so it would be fine too.

**Comment by Paldom** [comment]
In fact it needs casting when `.Underlying` have `NSError`. Bit confusing, but found an explanation [here](http://roadfiresoftware.com/2015/10/how-to-parse-json-with-swift-2/):

> First of all, everything is surrounded in a do/catch block since JSONObjectWithData:options: may throw an error. If you’re familiar with Objective-C, you’ll notice that we don’t pass in an NSError pointer here – instead, JSONObjectWithData is marked with throws, meaning it may throw an error. The error that we catch (which is called error by default) replaces the NSError pointer from Objective-C.

**Comment by ashfurrow** [comment]
Ah, you're right. I misunderstood.
