### ISSUE TITLE
I got some trouble .Success(Status Code: 404, Data Length: 177)

### ISSUE THREAD

**Issue by Ryan0520** [Moya/Moya#484]
This is I use Alamofre 

```swift
let params =  ["service"	 :"contacts.list",
		               "access_token":"37921b0595da0c02166464bd7538e075fc8c6154",
		               "params"		 :""]`

Alamofire.request(.POST, "http://124.172.184.216:8080/open_api/api?sign=f93404972addb2b806a7bcb5adbaa8c3&app_id=123", parameters: params, encoding: .JSON, headers: nil).responseJSON { response in
			print(response.result)
			if let value = response.result.value {
				print(value)
			}
}
```		

it's work! But when I use Moya to do this,it show 

```swift
Optional(<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.4.6 (Ubuntu)</center>
</body>
</html>
)
.Success(Status Code: 404, Data Length: 177)
false

//let GitHubProvider = MoyaProvider<GitHub>(plugins: [NetworkLoggerPlugin(verbose: true, responseDataFormatter: JSONResponseDataFormatter)])

let GitHubProvider = MoyaProvider<GitHub>(endpointClosure: {(target: GitHub) -> Endpoint<GitHub> in
	
	let url = target.baseURL.URLByAppendingPathComponent(target.path).absoluteString
	
	return Endpoint(URL: url,sampleResponseClosure: {.NetworkResponse(200, target.sampleData)},
					method: target.method,
					parameters: target.parameters,
					parameterEncoding:ParameterEncoding.JSON)
})

// MARK: - Provider support

private extension String {
	// 百分号编码转码，针对中文
    var URLEscapedString: String {
        return self.stringByAddingPercentEncodingWithAllowedCharacters(NSCharacterSet.URLHostAllowedCharacterSet())!
    }
}

public enum GitHub {
    case Zen
    case UserProfile(String)
    case UserRepositories(String)
	case CompanyList
}

extension GitHub: TargetType {
    public var baseURL: NSURL {
		switch self {
		case .CompanyList:
			return NSURL(string: "http://124.172.184.216:8080/open_api/api?sign=f93404972addb2b806a7bcb5adbaa8c3&app_id=123")!
		default:
			return NSURL(string: "https://api.github.com")!
		}
	}
    public var path: String {
        switch self {
        case .Zen:
            return "/zen"
        case .UserProfile(let name):
            return "/users/\(name.URLEscapedString)"
        case .UserRepositories(let name):
            return "/users/\(name.URLEscapedString)/repos"
		default:
			return ""
        }
		
    }
    public var method: Moya.Method {
		switch self {
		case .CompanyList:
			return .POST
		default:
			return .GET
		}
    }
    public var parameters: [String: AnyObject]? {
        switch self {
        case .UserRepositories(_):
            return ["sort": "pushed"]
		case .CompanyList:
			return ["service"	  : "contacts.list",
			        "access_token": "37921b0595da0c02166464bd7538e075fc8c6154",
			        "params"	  : ""]
        default:
            return nil
        }
    }
```

How can I get my data? And How can I change the code?

**Comment by ashfurrow** [comment]
Everything looks fine, hmm. Very strange. Can you try using the [network logging plugin](https://github.com/Moya/Moya/blob/38b0bda890b7b4598552a353b3f8db4248c37d6e/docs/Providers.md#plugins) to see what request is getting sent?

**Comment by Ryan0520** [comment]
OK,I will try~

**Comment by Ryan0520** [comment]
`Moya_Logger: [16/05/2016 10:30:51] Request: <NSMutableURLRequest: 0x7fc7facbeb60> { URL: http://124.172.184.216:8080/open_api/api/?sign=f93404972addb2b806a7bcb5adbaa8c3&app_id=123 }
Moya_Logger: [16/05/2016 10:30:51] Request Headers: ["Content-Type": "application/x-www-form-urlencoded; charset=utf-8"]
Moya_Logger: [16/05/2016 10:30:51] HTTP Request Method: POST
Moya_Logger: [16/05/2016 10:30:51] Request Body: access_token=37921b0595da0c02166464bd7538e075fc8c6154&params=&service=contacts.list
Moya_Logger: [16/05/2016 10:30:52] Response: <NSHTTPURLResponse: 0x7fc7fd022280> { URL: http://124.172.184.216:8080/open_api/api/?sign=f93404972addb2b806a7bcb5adbaa8c3&app_id=123 } { status code: 404, headers {
    Connection = "keep-alive";
    "Content-Encoding" = gzip;
    "Content-Type" = "text/html";
    Date = "Mon, 16 May 2016 02:26:48 GMT";
    Server = "nginx/1.4.6 (Ubuntu)";
    "Transfer-Encoding" = Identity;
} }
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.4.6 (Ubuntu)</center>
</body>
</html>

.Success(Status Code: 404, Data Length: 177)`

**Comment by Ryan0520** [comment]
404 Not Found is not come form my service,and when I use Alamofire buy default POST method,it is work. But it doesn't work in Moya! And, I don't know how to change the code.

**Comment by Ryan0520** [comment]
I solve the problem, the result is my url is wrong, and I wonder know, why I set my URL is `http://192.168.172.243/public_gateway/web/index.php?r=api&sign=c672431482bf5063f5d33a8654aecb41&app_id=123` ,but when I look the request `Request: <NSMutableURLRequest: 0x7fa9485e9600> { URL: http://192.168.172.243/public_gateway/web/index.php/?r=api&sign=c672431482bf5063f5d33a8654aecb41&app_id=123 }` It will insert "/" to index.php/?,and My orginal URL is index.php? not index.php/?,so it show 404 not found. I solve the problem to use

`let endpointClosure = { (target: GitHub) -> Endpoint<GitHub> in
	let url = "http://192.168.172.243/public_gateway/web/index.php?r=api&sign=c672431482bf5063f5d33a8654aecb41&app_id=123"
	
	return Endpoint(URL: url,
	                sampleResponseClosure: {.NetworkResponse(200, target.sampleData)},
	                method: target.method,
	                parameters: target.parameters,
	                parameterEncoding: Moya.ParameterEncoding.JSON)
}`

`let GitHubProvider = MoyaProvider<GitHub>(endpointClosure: endpointClosure,
                                          plugins: [NetworkLoggerPlugin(verbose: true, responseDataFormatter: JSONResponseDataFormatter)])`   And It work!

**Comment by Ryan0520** [comment]
If my URL is "http://192.168.172.243/public_open_api/api?sign=c672431482bf5063f5d33a8654aecb41&app_id=123", my baseURL is http://192.168.172.243/public_open_api/api?, the sign and app_id is change by parameters, how I change the code in MyTargetType?

**Comment by ashfurrow** [comment]
Gotcha, looks like your `baseURL` has the query string and everything included with it. Moya uses `NSURL` to add additional paths, and that must be confused by the `?sign=...`. I would recommend returning only `http://124.172.184.216:8080/open_api/api` from the baseURL and use the `endpointClosure` to add those additional parameters. [Here](https://github.com/Moya/Moya/blob/master/docs/Endpoints.md#from-target-to-endpoint-) are some examples.

**Comment by Ryan0520** [comment]
Thanks very much, I solve the problem by do `let oauthEndpointClosure = { (target: OAuth) -> Endpoint<OAuth> in
	
	let baseURLString = target.baseURL.absoluteString

    let dict = target.parameters?["params"]
    
    var sign = ""
    
    if let dict = dict as? [String : AnyObject] {
        sign = signWithParamters(dict)
    }
    
    let url = baseURLString + "sign=" + sign + "&app_id=123"
	
	return Endpoint(URL: url,
	                sampleResponseClosure: {.NetworkResponse(200, target.sampleData)},
	                method: target.method,
	                parameters: target.parameters,
	                parameterEncoding: Moya.ParameterEncoding.JSON)
}

let OAuthAPI = MoyaProvider<OAuth>(endpointClosure: oauthEndpointClosure,
                                    plugins: [NetworkLoggerPlugin(verbose: true, responseDataFormatter: JSONResponseDataFormatter)])` It's work~ But I wonder know, Can I use the ObjectMapper to change the data to JSON object?

**Comment by ashfurrow** [comment]
Yeah, that should work. Here's a project that does ObjectMapper and Moya work: https://github.com/ivanbruel/Moya-ObjectMapper

**Comment by Ryan0520** [comment]
OK, thanks your adive!
