### ISSUE TITLE
Cookies on response from POST

### ISSUE THREAD

**Issue by andrewjtodd** [Moya/Moya#485]
HI,

Can you demonstrate how you would solve this problem with your library?
https://github.com/Alamofire/Alamofire/issues/946
I'm yet to find something that will work on IOS.
Thanks

**Comment by ashfurrow** [comment]
This should be possible, Moya's completion handler provides a `Response` object when a network call is successfully sent/returned (failure is for things like not being connected to the internet). The response object has a [`NSURLResponse?` property](https://github.com/Moya/Moya/blob/master/Source/Response.swift#L6) you can access to use a similar solution as in the StackOverflow answer.
