### ISSUE TITLE
Type X does not conform to protocol 'TargetType'

### ISSUE THREAD

**Issue by mlvhub** [Moya/Moya#487]
Hello,

I'm having the exact same issue as #464.

I posted a comment there but here the relevant information:

I'm using Carthage to manage my dependencies. I've also used Cocoapods before, and this didn't happen.

Here is my Cartfile:
```
github "ReactiveX/RxSwift" ~> 2.0
github "Moya/Moya"
github "sunshinejr/Moya-ModelMapper"
```

I'm using the following command to build the dependencies:
```
carthage update --platform iOS
```
And then I'm just linking the frameworks that are in ``` Carthage/Build/iOS``` inside the project.

I'm trying to create an endpoint for authentication:
```swift
import Foundation
import Moya

enum Auth {
    case Login(email: String, password: String)
    case Logout()
}

extension Auth: TargetType {
    
    var baseURL: NSURL { return NSURL(string: "https://localhost/api")! }
    
    var path: String {
        switch self {
        case .Login(_, _):
            return "/users"
        case .Logout(_):
            return "/users"
        }
    }
    
    var method: Moya.Method {
        switch self {
        case .Login(_, _):
            return .POST
        case .Logout(_):
            return .DELETE
        }
    }
    
    var parameters: [String: AnyObject]? {
        switch self {
        case .Login(let email, let password):
            return ["email": email, "password": password]
        case .Logout(_):
            return nil
        }
    }
    
    var sampleData: NSData {
        switch self {
        case .Login(_, _):
            return "".dataUsingEncoding(NSUTF8StringEncoding)!
        case .Logout(_):
            return "".dataUsingEncoding(NSUTF8StringEncoding)!
        }
    }
}

private extension String {
    var URLEscapedString: String {
        return self.stringByAddingPercentEncodingWithAllowedCharacters(NSCharacterSet.URLHostAllowedCharacterSet())!
    }
}
```

And I'm using it like so:
```swift
let provider = RxMoyaProvider<Auth>()
```

This throws the following error:
```swift
Type 'Auth' does not conform to protocol 'TargetType'
```

I've used Cocoapods before and didn't get this error.

Thanks!

**Comment by ashfurrow** [comment]
Very strange, sorry to hear about this. Not sure what the issue could be. Usually, Xcode's error inspector will have a drop-down arrow beside the "does not conform to protocol" that says which function is missing, is it there?

**Comment by mlvhub** [comment]
Thanks for your reply, yeah, it usually says what's missing for it to conform to the protocol, but in this case there is no arrow.

This is a wild guess, but I think there may be something wrong with the generated frameworks, I've seen something like this before, and it usually means that the 'TargetType' from the RxMoya framework, is different from the 'TargetType' in the Moya framework. 

I guess I'll make a fork and start looking around into the project's configuration.

If I don't have any luck (I'm new to Carthage), I'll guess I'll continue using Cocoapods for now.

Thanks!

**Comment by ashfurrow** [comment]
Gotcha. Thanks for taking a look through – I'm not experienced with Carthage either, so if you find anything, please let us know!

**Comment by mlvhub** [comment]
Yeah, I think that's the reason, by command-clicking the TargetType in the endpoint, I can see it under the Moya framework, but in the ViewController, the TargetType is inside RxMoya.

The endpoint now looks like:
```
import Foundation
import RxMoya

enum Auth {
    case Login(email: String, password: String)
    case Logout()
}

extension Auth: RxMoya.TargetType {
    
    var baseURL: NSURL { return NSURL(string: "http://localhost/api")! }
    
    var path: String {
        switch self {
        case .Login(_, _):
            return "/users"
        case .Logout(_):
            return "/users"
        }
    }
    
    var method: RxMoya.Method {
        switch self {
        case .Login(_, _):
            return .POST
        case .Logout(_):
            return .DELETE
        }
    }
    
    var parameters: [String: AnyObject]? {
        switch self {
        case .Login(let email, let password):
            return ["email": email, "password": password]
        case .Logout(_):
            return nil
        }
    }
    
    var sampleData: NSData {
        switch self {
        case .Login(_, _):
            return "".dataUsingEncoding(NSUTF8StringEncoding)!
        case .Logout(_):
            return "".dataUsingEncoding(NSUTF8StringEncoding)!
        }
    }
}

private extension String {
    var URLEscapedString: String {
        return self.stringByAddingPercentEncodingWithAllowedCharacters(NSCharacterSet.URLHostAllowedCharacterSet())!
    }
}
```

**Comment by ashfurrow** [comment]
Hmm, must be a consequence of our Carthage setup. Some background: Carthage doesn't support any sort of "subspec" style organization. Since we keep Moya and the RxSwift/ReactiveCocoa code in the same repo, Carthage downloads all three targets even if you don't use them. Because of the project organization, `TargetType` is re-defined in three different modules. The solution you have will work.

I'm surprised we haven't run into this before, I think we should add documentation around this. @mlvhub when you first ran into this problem, where did you look for an answer? We should add documentation there so others can find the answer easily.

**Comment by mlvhub** [comment]
The issue is all the source files are included in both Moya and RxMoya targets, usually, you'd only include RxSwift specific files inside the RxMoya target, and then you specify Moya as a RxMoya dependency.

This way you'd import both frameworks, but as it is right now, you should only use RxMoya, and you must not include Moya otherwise you'll get that error. I'm okay with the way it is right now, but it should be worth mentioning that with Carthage you should only use one. 

I'm surprised as well that this hasn't turn up before. I usually look for the project's documentation at first, so it might be helpful to add this into some sort of notes regarding to Carthage usage, I also look into the project's issues, open and close, and then SO.

**Comment by petester42** [comment]
Since the project was built around cocoapod subspecs the source doesn't have `import Moya` in the subspec's files. To get Carthage support the easiest solution without changing the source too much was to include all the files. This matches the way cocoapods builds the project. 

I like the idea of dependent frameworks. I'll look into how much effort it would be.

**Comment by ashfurrow** [comment]
Yeah, last time we looked it involved splitting out into three repositories, which is a lot of work to keep in sync, etc. Let us know what you find, thanks!

**Comment by mlvhub** [comment]
Yeah, there are some changes, I already tried to do it in a fork, but got some weird errors when using it in another project through Carthage.

You don't really need another repo, you can just remove the source files from the RxMoya target, add the Moya target as a dependency inside RxMoya, and then you just ```import Moya``` whenever needed.

This was working for me inside the Moya project, it was building correctly, but as I mentioned above, I couldn't use it succesfully, and I'm not sure how these changes will affect the Cocoapods setup.

**Comment by petester42** [comment]
I have a working branch that does this but the Carthage build command gives some errors. Works fine in Xcode though. 

The only problem was that certain things needed to be made public. I'll try to push my branch later today. Could you give it a try to see if it works for you?

**Comment by mlvhub** [comment]
I see, nice. Sure, let me know when it's up and I'll give it a try.

**Comment by ashfurrow** [comment]
@mlvhub is this still causing problems for you, or is it safe to close the issue?

**Comment by mlvhub** [comment]
feel free to close for now, I'll reopen if I get it again.
