### ISSUE TITLE
GET not working with JSON parameterEncoding

### ISSUE THREAD

**Issue by awclives** [Moya/Moya#497]
Greetings,

When I try to send a GET request using Moya with parameterEncoding .JSON to my server, the request fails with 400 because it says that the client disconnected too quickly.  Using httpie to make the same GET request works fine.  However, when I change both Moya and the server to treat the same method as a POST rather than a GET, everything works.

I am wondering whether GET with parameterEncoding .JSON is rather uncommon?  Here is my endPoint.

```

	let endpoint = Endpoint<MyAPI>(URL: url, sampleResponseClosure: { .NetworkResponse(200, target.sampleData) }, method: target.method, parameters: target.parameters, parameterEncoding: .JSON)

	let headerFields = [
		"Content-Type": "application/json"]

	return endpoint.endpointByAddingHTTPHeaderFields(headerFields)
}
```

**Comment by sebbean** [comment]
GET is meant as simply a request to a URL. Thus URL encoding is the only real thing that makese sense.

I'd try switching over to POST.

**Comment by colinta** [comment]
Not to belabor the point, but there is a lot wrong with parsing the body of a GET request. Here's a great explanation: http://stackoverflow.com/a/983458

**Comment by awclives** [comment]
Got it.  Thank you.

**Comment by sunshinejr** [comment]
I think we can close this one, but if you will have any more questions @awclives about this topic, let us know! 🐼

**Comment by strikernani** [comment]
Hi Team,

http://BaseURL?loginUserId=17&searchKey=&pageNumber=0 (Actual)
http://BaseURL/%3FloginUserId=17&searchKey=&pageNumber=0 (After Parsing with Moya)

I am using moya wrapper it is working great.But How can I parse query parameters in GET request.
