### ISSUE TITLE
POST request parameters are not appended to the URL 

### ISSUE THREAD

**Issue by iDiyor** [Moya/Moya#500]
I am trying to make a POST request with parameters in the url and without body. But when I got the response there was not any parameter in the requested url. Does it mean for POST requests, Moya uses parameters to build their body? I also tried to change ParameterEncoding to .URL but still it is not adding anything to the url.

**Comment by sunshinejr** [comment]
Hey @iDiyor, thanks for opening an issue! :tada: 

Moya uses Alamofire's [parameter encoding](https://github.com/Alamofire/Alamofire#parameter-encoding) which has URLEncodedInURL case, which I believe you can use in your case.

Hope it helps!
