### ISSUE TITLE
Dynamic Endpoints

### ISSUE THREAD

**Issue by wonc003** [Moya/Moya#503]
Our applications read in a configuration api that has a list of web services the application will use. 

Is there a way to dynamically generate these webservice endpoints into moya at runtime?

**Comment by ashfurrow** [comment]
Hmm, not easily, though you could use the `StructTarget` to use a `struct` instead of an `enum` for your `MoyaTarget`. I'm not aware of anyone doing this, if you find anything online that helps, please let us know 🙇

**Comment by Gurpartap** [comment]
Perhaps, something like this could work:

```swift
enum APIProvider {
	// returns an array of objects with `apiPath` in each.
	/* Example: [
		{
			"title": "Followers",
			"apiPath": "/people_components/{userUUID}/followers", 
		},
		{
			"title": "Following",
			"apiPath": "/people_components/{userUUID}/following"
		},
		{
			"title": "Blocked",
			"apiPath": "/people_components/{userUUID}/blocked", etc.
		}
	] */
	case PeopleComponents

	case People(apiPath: String, userUUID: String)
}

extension APIProvider: TargetType {
	var baseURL: NSURL { return NSURL(string: "http://localhost:3000")! }

	var path: String {
		switch self {

		case let .PeopleComponents:
			return "/people_components"

		case let .People(apiPath, userUUID):
			return apiPath.stringByReplacingOccurrencesOfString("{userUUID}", withString: "\(userUUID)")

	}
}

// ...
```

**Comment by orta** [comment]
You may want to consider generating the Moya source code from your API similar to this: https://github.com/lkuczborski/SwiftMoyaCodeGenerator - you can't really get the advantages of maya without their being defined types in code

**Comment by ashfurrow** [comment]
@wonc003 did you manage a solution for this issue? Would love to have it added to our documentation 👍

**Comment by scottrhoyt** [comment]
Since there hasn't been any activity on this thread for some time, I am going to go ahead and close it. Please re-open or create a new issue if you would like to discuss further. Thanks.
