### ISSUE TITLE
Custom/Default HTTP headers

### ISSUE THREAD

**Issue by mrfarukturgut** [Moya/Moya#510]
Hi. I am trying to build network layer for my app with moya, but i have this issue. I have like 25-30 endpoints and i need a custom header for almost all of them. (headers which containing token etc.). 
Can I set a default header or return header for all endpoints from TargetType enumaration? 

Or do I have to create a endpoint closure for all of them?

**Comment by colinta** [comment]
Just one, for sure!  Here's how we do it in the Ello app:

###### ElloProvider.swift
```swift
    public static func endpointClosure(target: ElloAPI) -> Endpoint<ElloAPI> {
        let sampleResponseClosure = { return EndpointSampleResponse.NetworkResponse(200, target.sampleData) }

        let method = target.method
        let parameters = target.parameters
        let endpoint = Endpoint<ElloAPI>(URL: url(target), sampleResponseClosure: sampleResponseClosure, method: method, parameters: parameters, parameterEncoding: target.encoding)
        return endpoint.endpointByAddingHTTPHeaderFields(target.headers())
    }
```

###### ElloAPI.swift
```swift
    public func headers() -> [String: String] {
        var assigned: [String: String] = ["Accept": "application/json", "Accept-Language": "", "Content-Type": "application/json"]

        if self.requiresAnyToken {
            assigned += [
                "Authorization": AuthToken().tokenWithBearer ?? "",
            ]
        }
```

**Comment by colinta** [comment]
[ElloProvider](https://github.com/ello/ello-ios/blob/master/Sources/Networking/ElloProvider.swift#L32)

[ElloApi](https://github.com/ello/ello-ios/blob/master/Sources/Networking/ElloAPI.swift#L455)

**Comment by mrfarukturgut** [comment]
Thank you! I think there would be no problem, if I examine your library and get some inspirations :)

I am following Ello as much as I can by the way. You are doing great work! May the success be with you 👍

**Comment by justinmakaila** [comment]
I'm going to close this issue. @mrfarukturgut, feel free to open it again if you still have questions!
