### ISSUE TITLE
How to get response headers 

### ISSUE THREAD

**Issue by Ravichandrane** [Moya/Moya#515]
Hi, 

I'm wondering how can I get the response headers ? e.g access_token or content-type

Thanks,
Ravi.

**Comment by iiiyu** [comment]
I also met the same problem, @Ravichandrane can you tell me is how to solve.

**Comment by Ravichandrane** [comment]
@iiiyu On you success you just need to do that : 

```swift
if let httpResponse = value.response as? NSHTTPURLResponse {
   debugPrint(httpResponse.allHeaderFields)
}
```

**Comment by iiiyu** [comment]
@Ravichandrane  Thanks for your reply.
MoyaProvider is work.
But RxMoyaProvider response is NSURLResponse. 
So I don't use RxMoyaProvider. 
Thanks again.

**Comment by IgorBelyayev** [comment]
What is the way to do this with reactive extensions?
