### ISSUE TITLE
OSSpinLockLock

### ISSUE THREAD

**Issue by DeepMissea** [Moya/Moya#516]
Maybe ‘OSSpinLockLock’ is unsafe. 

http://mjtsai.com/blog/2015/12/16/osspinlock-is-unsafe/
https://lists.swift.org/pipermail/swift-dev/Week-of-Mon-20151214/000372.html

**Comment by ashfurrow** [comment]
Yikes, I hadn't heard that. Can't remember why we used spin locks, we can probably move to `NSLock` without too much fuss. Anyone up for a pull request?

**Comment by DeepMissea** [comment]
'dispatch_semaphore' is a better one, I'll pull a request later.
