### ISSUE TITLE
Moya on swift 3.0

### ISSUE THREAD

**Issue by tdouglas1313** [Moya/Moya#522]
After seeing Moya and that it has support for RxSwift I was really hoping to add it to a project that I was just about to get started on. However without support for swift 3.0 I would be unable to use Moya without updating it myself. I was wondering what the plans for swift 3.0 are and if there will be an update in the near future.

**Comment by sunshinejr** [comment]
Hey @tdouglas1313. There is a conversation in #513 about Swift 2.3 and 3.0 support. However, there is no PR with updates for any of versions _yet_.

**Comment by tdouglas1313** [comment]
Thank you for referring me to that. It may be beneficial to add /3.0 to the end of the title because there is discussion about more than just 2.3.

**Comment by sunshinejr** [comment]
Good suggestion! I've changed the title, thanks! I think in this case I can close this one in favor of #513.
