### ISSUE TITLE
why sample data function is required ?

### ISSUE THREAD

**Issue by AsimNet** [Moya/Moya#524]
Hello, 

why sample data function is required ? and not optional ?

thanks.

**Comment by orta** [comment]
To encourage better testing strategies 👍

**Comment by justinmakaila** [comment]
@AsimNet Worst case:
```
var sampleData: NSData {
  return NSData()
}
```

...But as @orta said, mostly for testing. You don't realize how great it is until you start writing your tests.

**Comment by AndrewSB** [comment]
Are there any good examples of how people have setup testing for their apps?

**Comment by colinta** [comment]
The Ello iOS app makes very heavy use of `sampleData` <https://github.com/ello/ello-ios>

**Comment by AndrewSB** [comment]
Woah - thank you for open sourcing @colinta 🎉

**Comment by colinta** [comment]
Well it's way more than just me!  The entire Ello team - from devs to marketing to leadership - were all very much a part of the decision to open source and the process that got us there.

So on behalf of everyone at Ello: happy to help!

**Comment by colinta** [comment]
OK to close?
