### ISSUE TITLE
master doesn't build currently

### ISSUE THREAD

**Issue by AndrewSB** [Moya/Moya#525]
The file `NetworkCurlLoggerPlugin.swift` doesn't exist. Tried looking back in the logs & blame, couldn't find much about the file. May be related to #505?

**Comment by ashfurrow** [comment]
It's possible; how are you building the project that's not working? Any details around Xcode version etc would be awesome too.

**Comment by AndrewSB** [comment]
of course, sorry about the lack of details @ashfurrow.

I'm on Xcode Version 7.3.1 (7D1014). I've tried building by:
1. Cloning the repo, opening in Xcode and building
2. Doing a `carthage update --no-use-binaries --platform ios` with `github "Moya/Moya" "master"` in my Cartfile

**Comment by orta** [comment]
I wonder if the Xcodeproj needs updating?

**Comment by ashfurrow** [comment]
No problem, thanks! First, if this is blocking your project, you should be able to use our most recent release. But as far as fixing master, hmm. The `Moya-iOS` Xcode project was added by @JRHeaton for Carthage compatibility. I can't remember the mechanism for updating it – it doesn't look like it's from the release task, but I'm not sure if it's generated by CocoaPods either.

**Comment by ashfurrow** [comment]
Looking at #505 it does look like `NetworkCurlLoggerPlugin.swift` was added to the project file, but not to the repo, probably by accident. Removing those lines [added to the project](https://github.com/Moya/Moya/pull/505/files#diff-a24d686152f5e86f361b118f3c399d22) should fix it. @AndrewSB are you able to test + send a pull request?

**Comment by AndrewSB** [comment]
@orta that sounds right

@ashfurrow I downgraded to the latest release (6.5.0), so its not blocking 😄 thank you for the suggestion 
I'll work on that PR and have it up in a couple minutes!
