### ISSUE TITLE
Without the "Carthage/Checkouts" directory, the `.gitmodules` file causes issues when installing with Carthage

### ISSUE THREAD

**Issue by justinmakaila** [Moya/Moya#534]
While trying to install the latest on master, I kept getting an error saying the following:
```
...
*** Checking out Alamofire at "3.4.1"
...
*** Checking out Result at "2.1.2"
*** Checking out ReactiveCocoa at "4bd8d7839d70e41ecb5a58e99bf3a06917b4c7d8"
...
*** Checking out RxSwift at "2.6.0"
*** Checking out Moya at "6c0880a4dee1f4014c8f7ed221de06ebafe5a566"
...
Parse error: expected submodule commit SHA in output of task (ls-tree -z 6c0880a4dee1f4014c8f7ed221de06ebafe5a566 Carthage/Checkouts/Alamofire) but encountered: 
```
This error only occurred if I tried to update `Moya` (I had it pointing to my `multipart-upload` branch). I noticed that the change coming from my branch to master was the removal of the `Carthage/Checkouts` file in `47a226adb44a0983976b26892435159490147bdb`.

My fix was to run `carthage update`, cancel the command once the check out finished, followed by:
```fish
$ cd Carthage/Checkouts/Moya
$ rm -rf .gitmodules
$ cd ../../../; and carthage build Moya
```

The `Carthage` source checks a dependencies `.gitmodules` file for the dependencies, and then attempts to copy them into the project. Since our `.gitmodules` file local directories within the `Moya` directory, it's causing the `git ls-tree` command to return an empty string, killing the `carthage` process.

@Moya/contributors is there any reason we have those `.gitmodules` hanging around anymore? They appear to be left over from someone running `carthage update --use-submodules`

**Comment by justinmakaila** [comment]
Removed `.gitmodules` file on my fork and currently testing. Will file PR and leave merging to you guys

**Comment by ashfurrow** [comment]
This is good to close by #536?
