### ISSUE TITLE
New release 🚀

### ISSUE THREAD

**Issue by AvdLee** [Moya/Moya#535]
I think it's time to craft a new release, especially for those who are using CocoaPods to reference Moya.

It will be a release with breaking changes and some great improvements, probably a 7.0.0 release?

**Comment by ashfurrow** [comment]
I think this is a good idea, I don't see any other issues tagged "breaking changes", but we need to cleanup those issue tags anyway 😁 

I'll give some time for other @Moya/contributors to chime in, and if no one objects, we'll release Moya 7.0.0 🎉

**Comment by ashfurrow** [comment]
We _might_ have a non-backwards-compatible feature request worth squeezing in: https://github.com/Moya/Moya/issues/542 I believe @colinta is taking a look, I can help too.

**Comment by colinta** [comment]
Working on it right now, looks straightforward.  Thanks for stalling!

**Comment by ashfurrow** [comment]
Cool, I think we're good?

**Comment by colinta** [comment]
I'm done I swear! 😃

**Comment by ashfurrow** [comment]
Okay! That's tagged and pushed to CocoaPods, Carthage folk have their GitHub release, too: https://github.com/Moya/Moya/releases/tag/7.0.0

Thanks for the help all our contributors have put in to getting us to Moya's _seventh_ major release in two years!

**Comment by colinta** [comment]
👏
