### ISSUE TITLE
Carthage issue due to RxSwift

### ISSUE THREAD

**Issue by mbuchetics** [Moya/Moya#540]
RxSwift is causing the current Moya version not to build using Carthage:

> A shell task failed with exit code 66:
> xcodebuild: error: Scheme RxExample-iOS-no-module is not currently configured for the build action.

Once we delete the scheme  RxExample-iOS-no-module, everything works fine. 
We aren't using RxSwift at all but it keeps causing problems.

Related RxSwift issue: https://github.com/ReactiveX/RxSwift/issues/793

**Comment by ashfurrow** [comment]
What's the `carthage` command you're running that's producing the error?

**Comment by mbuchetics** [comment]
`carthage update --platform iOS`

**Comment by ashfurrow** [comment]
We've seen [other issues](https://github.com/Moya/Moya/issues/445) with Carthage that were solved by running `carthage update --platform iOS --no-use-binaries` instead. Can you try that and see if it works? If that's the fix, we should add it to our readme.

**Comment by ikesyo** [comment]
See https://github.com/ReactiveX/RxSwift/issues/793#issuecomment-232515707.

**Comment by ikesyo** [comment]
#445 is a Swift's binary compatibilty issue, so that is not related to this.

**Comment by ashfurrow** [comment]
I'm not sure then, I don't use Carthage so I'm not the best to help out with troubleshooting.

**Comment by mbuchetics** [comment]
Seems to be working fine with Moya 7.0 and RxSwift 2.6. Looks like the problem was with RxSwift 2.5.0 and is fixed. Thanks for your help!
