### ISSUE TITLE
Track progress of request

### ISSUE THREAD

**Issue by alexdoloz** [Moya/Moya#542]
Hello everyone! I read the docs but couldn't find a way to track progress of current request – for example, to show progress bar. Is it possible in Moya?

**Comment by ashfurrow** [comment]
Moya only supports progress notifications while uploading a file, not for regular requests (thought Alamofire _does_ support this, so it shouldn't be too difficult to add this to Moya. I'm a little surprised that Moya doesn't already support this, to be honest, it's something we should consider adding. Could you tell us more about how you'd expect this to work?

**Comment by colinta** [comment]
It shouldn't be a ton of work (and should even be backwards compatible) to add support for `Moya.ProgressBlock` to the internal `requestNormal` method. Actually, now that I'm looking at it, `sendUpload` and `sendRequest` have a lot of duplicated code...

**Comment by ashfurrow** [comment]
@colinta aye, could be worth factoring a bit out. If we can be backwards compatible, that's great, but we're about to have a major release with other breaking changes, so we could roll this feature into that release.

**Comment by alexdoloz** [comment]
Thanks for answer @ashfurrow. I don't know how to implement this in Moya but I would suggest this interface for end user:
`public func request(target: Target, progressClosure: ((progress: NSProgress) -> Void)? = nil, completion: Moya.Completion) -> Cancellable`. Probably this interface won't break current code (not sure how it will work with trailing closure syntax though).

**Comment by ashfurrow** [comment]
@alexdoloz yup, that makes sense! The trailing closure syntax is preserved that code.

**Comment by ashfurrow** [comment]
@alexdoloz now that #543 is merged, this should work if you use the latest version of Moya, on the master branch. If you're using CocoaPods, you can change the Podfile to include `pod 'Moya', git: 'https://github.com/Moya/Moya.git'` and do a `pod update` and it should work. Let us know!

**Comment by colinta** [comment]
I might have ONE more PR...

**Comment by ashfurrow** [comment]
Ah, okay! No rush.

**Comment by colinta** [comment]
#544 whitespace changes only 😃

**Comment by ashfurrow** [comment]
I think this was closed by #543, re-open if not.

**Comment by alexdoloz** [comment]
Hello again, guys! Thank you for all your hard work implementing this feature. However, i tried to integrate it into application and noticed it doesn't work as I expect. For some reason, `bytesExpected` is always -1, therefore progress is always 1.0. 

Progress: ProgressResponse(totalBytes: 21654, bytesExpected: -1, response: nil)

Do you have any ideas about it?

**Comment by ashfurrow** [comment]
Can you open another issue about the -1 bytes expected? Link back here for context 👍 

I think the bytes expected comes from Alamofire, and ultimately the server. It may be that -1 is what ALamofire provides when there is no expected number of bytes available, which might could from the server. Not sure, though.

**Comment by alexdoloz** [comment]
Okay, I figure out what happened. Server doesn't return `Content-Length` header. I tested other resources and progress works fine (provided these servers return `Content-Length`). So it was my mistake, no need to create new issue :)

**Comment by ashfurrow** [comment]
@alexdoloz I'm glad you got it figured out!

**Comment by colinta** [comment]
Glad to hear that you got to the bottom of it! Good to know about the Content-Length header. 

When you feel good about it, please close this issue. 👍
