### ISSUE TITLE
Question: Encoding parameters for http://jsonapi.org structure

### ISSUE THREAD

**Issue by raven** [Moya/Moya#545]
Just wondering if anyone had any tips or ideas about the way to setup parameters for http://jsonapi.org structure. 

For example the json structure for our Login is:
```json
{
  "data": {
    "attributes": {
      "email": "pete@thegmail.com",
      "password": "password",
      "client-uuid": "e43ccaf0-b66f-49f8-95f1-ee9e14a88962"
    }
  }
}
```

And the structure for refreshing a token is:
```json
{
  "data": {
    "type": "user-authentications",
    "id": "58fc7178-e135-462e-b328-ec8802023579",
    "attributes": {
      "long-jwt": "eyJ0eX...TIE"
    }
  }
}
```

My question is around defining a way to shuffle values into the `data.attributes`, vs `data.id` etc.
The obviously terrible, poor man's way to do it:
```swift
extension AwesomeAPI: RxMoya.TargetType {
  ...
  var parameters: [String: AnyObject]? {
    switch self {
    case .Login(let email, let password, let clientID):
      return ["data": ["type": "user-authentications", "attributes": ["email": email, "password": password, "client-uuid": clientID]]]
    case .RefreshToken(let longToken, let clientID):
      return ["data": ["type": "user-authentications", "id": clientID, "attributes": ["long-jwt": longToken]]]
   }
}
```

Would this be the responsibility of the conformer to `TargetType`, or should someone else create these structures?
Any thoughts would be super appreciated :) This is probably more of a Slack question than a question on issues.

**Comment by ashfurrow** [comment]
What you've got is actually how things are done, except broken into several lines. [Here's an example](https://github.com/artsy/eidolon/blob/70b59b1cfd0c68730b6a2860fabeb8cbaca2acca/Kiosk/App/Networking/ArtsyAPI.swift#L112) of using it.

**Comment by davidlondono** [comment]
I'm going to create a `mapper` for it, a public pod, if you want to participate

**Comment by ashfurrow** [comment]
Cool! Please consider submitting a PR to the readme to add it :+1:
