### ISSUE TITLE
Xcode error with new requestClosure in 7.0

### ISSUE THREAD

**Issue by bryanbartow** [Moya/Moya#549]
My request closure looks like this:
```Swift
let requestClosure = { (endpoint: Moya.Endpoint<ICanHazProvider>, done: Result<NSURLRequest, Moya.Error> -> Void) in
  let request = endpoint.urlRequest.mutableCopy() as! NSMutableURLRequest

  if let token = self.getToken() {
    request.setValue(token, forHTTPHeaderField: "token")
  }

  return done(.Success(request))
}

hazAPI = MoyaProvider<ICanHazProvider>(endpointClosure: endpointClosure, requestClosure: requestClosure)
```
I'm getting the following error in Xcode now:
```
Unable to infer closure return type in current context
```
Is there any secret to getting this to work?

**Comment by ashfurrow** [comment]
When you get this error, the next step is usually to specify the return type explicitly. Looking at the Moya source code, you can change your line to the following:

```swift
let requestClosure = { (endpoint: Moya.Endpoint<ICanHazProvider>, done: Result<NSURLRequest, Moya.Error> -> Void) -> Void in
```

Let us know how it goes!

**Comment by bryanbartow** [comment]
Now gives me this error:
```
Cannot convert value of type '(ICanHazProvider) -> Endpoint<ICanHazProvider>' to expected argument type '_ -> Endpoint<_>'
```

My endpoint looks like this:
```Swift
let endpointClosure = { (target: ICanHazProvider) -> Endpoint<ICanHazProvider> in

  let url = target.baseURL.URLByAppendingPathComponent(target.path).absoluteString

  var encoding: Moya.ParameterEncoding = .JSON

  switch target.method {
  case .GET:
    encoding = .URL
  default:
    encoding = .JSON
  }
			
  let endpoint: Endpoint<ICanHazProvider> = Endpoint<ICanHazProvider>(URL: url, sampleResponseClosure: {.NetworkResponse(200, target.sampleData)}, method: target.method, parameters: target.parameters, parameterEncoding: encoding)

  return endpoint
}
```

**Comment by bryanbartow** [comment]
I should clarify a bit: Error is on the next line:
```Swift
hazAPI = MoyaProvider<ICanHazProvider>(endpointClosure: endpointClosure, requestClosure: requestClosure)
```

**Comment by dccarmo** [comment]
Having a related issue. 

If I have this:

```swift
private let authenticatedRequestClosure =  {
    (endpoint: Endpoint<SmartContactsPluginService>, done: MoyaProvider.RequestResultClosure) in
    let request = endpoint.urlRequest

    GlobalOAuth.authenticateRequest(request, completion: {
        result in
        switch result {
        case .Success(let signedInRequest):
            done(Result<NSURLRequest, Moya.Error>.Success(signedInRequest))

        case .Failure(let error):
            done(Result<NSURLRequest, Moya.Error>.Failure(.Underlying(error)))
        }
    })
}
```

It gives me:

![screen shot 2016-07-22 at 17 01 46](https://cloud.githubusercontent.com/assets/638474/17074223/097e32e4-502e-11e6-813c-86f74a33c2d7.png)

But if I have this:

```swift
private let authenticatedRequestClosure =  {
    (endpoint: Endpoint<SmartContactsPluginService>, done: Result<NSURLRequest, Moya.Error> -> Void) in
    let request = endpoint.urlRequest

    GlobalOAuth.authenticateRequest(request, completion: {
        result in
        switch result {
        case .Success(let signedInRequest):
            done(Result<NSURLRequest, Moya.Error>.Success(signedInRequest))

        case .Failure(let error):
            done(Result<NSURLRequest, Moya.Error>.Failure(.Underlying(error)))
        }
    })
}
```

It gives me:

![screen shot 2016-07-22 at 17 04 31](https://cloud.githubusercontent.com/assets/638474/17074256/7724f288-502e-11e6-84ad-4f17a3d68fa5.png)

**Comment by kamil-tomaszewski** [comment]
I think I'm lost too with the same error for endpointClosure. I'm out of ideas :(
<img width="1028" alt="screen shot 2016-07-25 at 09 11 25" src="https://cloud.githubusercontent.com/assets/1580732/17093157/dda3889c-5247-11e6-9c2a-a1f89ce36061.png">

**Comment by kamil-tomaszewski** [comment]
This closure also doesn't work in the Demo app.

**Comment by bryanbartow** [comment]
@ashfurrow Is this a known issue or are we all doing something wrong? Any help would be greatly appreciated.

**Comment by ashfurrow** [comment]
Yup, taking a look now. I've not seen this before, things are working for me with the latest `master` branch with Xcode 7.3.1. Have you run `pod install` in the Demo directory? What version of CocoaPods are you using?

**Comment by ashfurrow** [comment]
@bryanbartow I think the second example might be getting confused with the `nil`s used as parameters (they're non-optional, just remove them and they'll fallback to the defaults). But that doesn't explain the first error. 

I'm really at a loss on that one. Would it be possible to share a small Xcode project demonstrating the problem? It would help figure out what the problem is.

**Comment by bryanbartow** [comment]
@ashfurrow Well, as I was preparing the example project, I realized that if I omit the variable type declarations in the closure it seems to compile and work fine. So I changed
```Swift
let requestClosure = { (endpoint: Moya.Endpoint<ICanHazProvider>, done: Result<NSURLRequest, Moya.Error> -> Void) in
  let request = endpoint.urlRequest.mutableCopy() as! NSMutableURLRequest

  if let token = self.getToken() {
    request.setValue(token, forHTTPHeaderField: "token")
  }

  return done(.Success(request))
}
```
to
```Swift
let requestClosure: MoyaProvider<ICanHazProvider>.RequestClosure = { endpoint, done in
  let request = endpoint.urlRequest.mutableCopy() as! NSMutableURLRequest

  if let token = self.getToken() {
    request.setValue(token, forHTTPHeaderField: "token")
  }

  done(.Success(request))
}
```

**Comment by ashfurrow** [comment]
Awesome! So that works? Where do you think we should document this?

**Comment by sunshinejr** [comment]
@bryanbartow your problem might be returning the `Result` type in the closure that takes `Void` as a return type. Below code works under Xcode 7.3.1 & Moya 7.0.0:

```swift
let requestClosure = { (endpoint: Moya.Endpoint< ICanHazProvider >, done: MoyaProvider.RequestResultClosure) in
    let request = endpoint.urlRequest.mutableCopy() as! NSMutableURLRequest
        
    done(.Success(request))
}
```

**Comment by bryanbartow** [comment]
@sunshinejr Changing my code to your suggestion yields the error in my original post in this issue:
```
Unable to infer closure return type in current context
```

**Comment by bryanbartow** [comment]
@ashfurrow @sunshinejr I'm starting to wonder if this has something to do with the Result library, which I'm using elsewhere in my project...

**Comment by dccarmo** [comment]
@sunshinejr omitting the `Result` type did the trick, thanks!

**Comment by ashfurrow** [comment]
@bryanbartow Yeah, we've had issues before when using multiple `Result` identifiers. You can use modules names to namespace the specific `Result` type, like `Result.Result` or `MyLibrary.Result`, it can get tricky. Let us know how it goes :+1:

**Comment by kamil-tomaszewski** [comment]
So - the issue is really weird.
If you do:
```
let endpointClosure={ (target: GitHub) -> Endpoint<GitHub> in
            let url = target.baseURL.URLByAppendingPathComponent(target.path).absoluteString
            let endpoint: Endpoint<GitHub> = Endpoint<GitHub>(URL: url, sampleResponseClosure: {.NetworkResponse(200, target.sampleData)}, method: target.method, parameters: target.parameters)
            return endpoint
        }
        

       _ = MoyaProvider<GitHub>(endpointClosure: endpointClosure)
```

Everything is peachy.
If you pass all the parameters, even if you copy them from the default implementation of `init` it gets the above result. So:
1. The issue isn't with endpointClosure.
2. Issue is with Xcode? compiler? I have no idea and unfortunately after being stuck for one day with this I don't have more time to deal with it.

**Comment by ashfurrow** [comment]
@kamil-tomaszewski It could be that in the original code, you had `let endpointClosure: MoyaProvider.EndpointClosure` without specifying the generic type of `MoyaProvider` and it confused the type system? Try `let endpointClosure: MoyaProvider<GitHub>.EndpointClosure` and see what happens. (It works if you don't specify anything because the compiler can infer from the closure signature what `MoyaProvider`'s generic type is.)

**Comment by BasThomas** [comment]
It seems the issue here has been solved, so I guess this issue can be closed, right?

**Comment by bryanbartow** [comment]
@BasThomas I would think so. Not sure about everyone else, but my issue has been resolved and I'm the original reporter ;)

**Comment by zhaoyunyi** [comment]
@ashfurrow  thanks let endpointClosure: MoyaProvider.EndpointClosure can slove it, but 
![image](https://cloud.githubusercontent.com/assets/8953791/18407680/edb64486-774a-11e6-8489-8bad8ca79579.png) can not
