### ISSUE TITLE
Why duplicate GitHub enum in /Demo/Tests/TestHelpers.swift

### ISSUE THREAD

**Issue by simonxcheng** [Moya/Moya#555]
Why GitHub enum is duplicated in /Demo/Tests/TestHelpers.swift? I commented out the duplicated code and tried to use **@testable import Demo** and got linking errors. Ideally we should directly test the target code. Is it possible to solve the issue?

**Comment by ashfurrow** [comment]
The code is repeated because the app target is specific against iOS, but the three testing targets are specific to iOS, tvOS, and macOS. They all use the same files, but can't link against the app target because it's only iOS. Does that make sense?

**Comment by simonxcheng** [comment]
Yes. Thanks.

**Comment by ashfurrow** [comment]
It's a good question, thanks for opening an issue 👍
