### ISSUE TITLE
Unable to find module `Result`

### ISSUE THREAD

**Issue by jcampbell05** [Moya/Moya#558]
When using `Moya/RxSwift` Xcode complains it can't find the Result module for the file `CredentialManager`/

**Comment by ashfurrow** [comment]
What's your setup like, CocoaPods or Carthage? What Xcode and Moya version are you using?

**Comment by jcampbell05** [comment]
CocoaPods 0.39.0
Xcode 7.3
Moya 7.0

**Comment by ashfurrow** [comment]
Hmm, I haven't been installing Moya with CocoaPods 0.39 for a while. Can you post the relevant parts of your Podfile? I can take a look at it later tonight if someone hasn't chimed in by then.

**Comment by ashfurrow** [comment]
@jcampbell05 I'm going to close the issue, if this is causing problems, feel free to reopen 👍
