### ISSUE TITLE
Stickers

### ISSUE THREAD

**Issue by ashfurrow** [Moya/Moya#559]
Moya's gotten pretty big, I reckon it's time we get some stickers 🎉 There are a few aspects to this issue:

- [x] Pick a sticker medium (probably through [stickermule](https://www.stickermule.com)). Thinking a single-colour [transfer sticker](https://www.stickermule.com/products/transfer-stickers) would be the coolest
- [x] Make a sticker design based on the chosen medium ☝️.
- [x] Figure out how to collect addresses for contributors to mail them stickers
- [x] Order the stickers.
- [x] Mail them out.

This is a long-term ticket, I'm thinking we'll try to get it wrapped up sometime before the end of 2016.

**Comment by esttorhe** [comment]
I totally understand going with single-colour but oh boy; i'm going to miss the colors 😉

**Comment by ashfurrow** [comment]
Yeah, I'm leaning more and more towards the colours too 😄

**Comment by orta** [comment]
IMO, think the colours too - can work with https://www.stickermule.com/products/clear-stickers 
Moya logo has too thin lines to pull off the ones CP/Artsy use

**Comment by ashfurrow** [comment]
Agreed, I think either the clear ones or maybe the [square ones](https://www.stickermule.com/products/square-stickers) could work. I think the square ones would go well if we used the GitHub avatar rather than the entire logo:

![](https://raw.githubusercontent.com/Moya/Moya/master/web/logo_square.png)

I'm not sure which one, either that or the actual logo would be more recognizable:

![](https://raw.githubusercontent.com/Moya/Moya/master/web/logo_github.png)

**Comment by orta** [comment]
Agree re:square

Re: full logo might want type e.g.

![screen shot 2016-07-23 at 11 48 54 pm](https://cloud.githubusercontent.com/assets/49038/17081683/0ab56b34-5130-11e6-8215-b5aefe19bd75.png)

specifically done bad on purpose to not think of design

**Comment by ashfurrow** [comment]
It's like "lorem ipsum" but for visual design 😆 

Cool. Okay, maybe a straw poll? Vote by reacting to this comment on if you think a square logo or a full logo would be more recognizable in sticker format.

| Square Logo | Full Logo |
|--------------|----------|
| 🎉                  | ❤️           |

**Comment by ashfurrow** [comment]
Cool, calling it: square logo. Which means the design is finished :tada:

I'll take care of ordering them, the tricky bit is figuring out how to collect addresses. @orta you have experience with this. Google Forms?

**Comment by orta** [comment]
I used a shared google spreadsheet, but forms can work too 👍 ( sheets made it easier to me to ask for edits etc )

**Comment by ashfurrow** [comment]
Stickers arrived: 

![ashfurrow_2016-aug-10](https://cloud.githubusercontent.com/assets/498212/17555701/87c18796-5ede-11e6-93c7-285678ed2d4a.jpg)

(Pen included for size comparison, they're 3.5cm squared.)

**Comment by delta98** [comment]
@ashfurrow how do you get hold of a sticker?

**Comment by ashfurrow** [comment]
The US-bound stickers are already in the mail, the international post should be going out this week. Thanks for your patience!

**Comment by colinta** [comment]
Mine arrived today!

**Comment by esttorhe** [comment]
Hi @ashfurrow do you reckon I still have time to update my address?

The current address is `SoundCloud` but attention to «Pedro Piñera» because I didn't know if I was going to be in 🇩🇪 by the time the stickers would arrive.

If its too much hassle I won't update, was just wondering

**Comment by ashfurrow** [comment]
@esttorhe Aye, I've addressed it to Berlin, but if you're not there anymore I can change it. 

If anyone else has address updates, please send the updated address to ash@ashfurrow.com . Thanks!

**Comment by esttorhe** [comment]
Thanks @ashfurrow.
I'm in Berlin now actually. I just didn't want to bother Pedro now that I can actually get it myself 😊

But like I said. No biggie

–
Esteban Torres
CraftKollective (http://craftkollective.com) Co-Founder

Phone: (+506)8813-0934 (tel:(+506)8813-0934)
Skype: esteban.a.torres.hernandez
Twitter: @esttorhe (https://twitter.com/esttorhe)

**Comment by ashfurrow** [comment]
Alright, I've sent these all out, let me know if you don't get them. Thanks again for everyone's work in making Moya such a successful community project, I'm incredibly proud of what we've built together.

**Comment by BasThomas** [comment]
Thank *you*, Ash!

**Comment by sunshinejr** [comment]
Exactly, thank _you_ Ash & @orta for starting this journey 👏
