### ISSUE TITLE
Inline testing providers 

### ISSUE THREAD

**Issue by orta** [Moya/Moya#56]
right now a test suite doing some networking looks like:

``` swift
    beforeSuite { () -> () in
        // Force provider to stub responses
        APIKeys.sharedKeys = APIKeys(key: "", secret: "")
        Provider.sharedProvider = Provider.StubbingProvider()
    }

    afterSuite { () -> () in
        // Reset provider
        APIKeys.sharedKeys = APIKeys()
        Provider.sharedProvider = Provider.DefaultProvider()
    }

    it("returns some data") {
        setDefaultsKeys(nil, nil)

        var called = false
        XAppRequest(.Auctions).subscribeNext({ (object) -> Void in
            called = true
        })

        expect(called).to(beTruthy())
    }

    ... etc
```

This is fine, and it goes and access pre-rendered stubs etc. I'd like some choice, and to allow making something like this (excusing broken syntax):

``` swift
  let networkProvider = Provider.runtimeProvider()
  beforeSuite { () -> () in
      Provider.sharedProvider = networkProvider
  }

  afterSuite { () -> () in
      Provider.sharedProvider = Provider.DefaultProvider()
  }

  it("returns some data") {

      var called = false

      networkProvider.responseString(.Auctions) {
        return "{ 'foo':'bar' }"
      }

      XAppRequest(.Auctions).subscribeNext({ (object) -> Void in
          called = true
      })

      expect(called).to(beTruthy())
  }


```

with maybe the potential of returning strings, json objects and data?

**Comment by colinta** [comment]
I had a similar thought not long ago.  Being able to define the response *in* the test would have been convenient when I needed to stub out a *sequence* of responses... I don't recall the actual example, but a contrived example would be a combined signup screen that also tests to make sure the user isn't trying to create their existing account:

1. Try to login (`login_failure.json`)
1. API says username is available (`availability_success.json`)
1. Submit a signup request (`signup_success`)
1. Now try to login (`login_success.json`)
1. Screen should transition to onboarding.

I think orta's "in line provider" would be one way to solve this.  What would be another way for `sampleData` to be more dynamic?

**Comment by ashfurrow** [comment]
Well, for the 1.0 release, we moved `sampleData` to be a closure that returns data, so it could return different things on different invocations. I know it's not enough, but it might help, and might help figure out better ideas.

**Comment by ashfurrow** [comment]
I'm thinking we'll have a new initializer that does two things: 

- accepts an argument of some kind of representation of new stubbing behaviour to be defined.
- sets a private/internal property – something like a "parent provider" that, when performing requests, would call through to the parent if the request didn't meet the newly added stubbing behaviour. 

In this way, you could chain things together, and every request would start at the bottom and work its way up:

```swift
provider.addStubbing(someRequest)
    .addStubbing(someOtherRequest)
    .addStubbing(someFinalRequest)
```

Or something like that. Does anyone have idea thoughts on this approach?

**Comment by colinta** [comment]
I dig it, very readable way to set up a series of requests/responses.

To flesh this out a little more, these requests would be instances of the API enum?

```swift
let firstReq = Api.Status  // will return "broken"
let secondReq = Api.FixTheThings
let lastReq = Api.Status  // will return "fixed"

// how do these get associated with
// the appropriate JSON file?
let provider = ApiProvider.StubbingProvider().addStubbing(firstReq)
  .addStubbing(...)
```

**Comment by ashfurrow** [comment]
I was thinking more like you would need to specify both a target _and_ an `EndpointSampleResponse` to accompany it. 

```swift
let request = Api.Status
let response = EndpointSampleResponse.Success(200, { /* Some sample data here */ })
let newProvider = provider.addStubbedResponse(response, forRequest: request)
```

Or something to that effect.

**Comment by colinta** [comment]
Yeah I dig it.  So, continuing to flesh out:

```swift
let firstReq = Api.Status  // will return "broken"
let secondReq = Api.FixTheThings
let lastReq = Api.Status  // will return "fixed"

let provider = ApiProvider.StubbingProvider()
// push? queue?  add?  something that indicates that this stubbed response will only be used once
  .pushStubbedResponse(success("status__broken.json"), forRequest: firstReq)
  .pushStubbedResponse(success("fixed__success.json"), forRequest: secondReq)
  .pushStubbedResponse(success("status__ok.json"), forRequest: lastReq)
```

**Comment by ashfurrow** [comment]
I'm thinking that the stubbed responses would be used for any request matching that `Api` enum. This makes sense to me as a simple use case, which is what this would provide. 

It's already possible to create this behaviour using custom endpoint resolvers that are passed into the `MoyaProvider` initializer. What this feature would do, in my mind, would let you have a sort of shorthand for this where only one or two requests need to be stubbed differently, for a specific test case. 

Does that make sense? So something like you have would work-ish, but the behaviour would be more consistent with the default Moya stubbing behaviour.

**Comment by alcarvalho** [comment]
Maybe this complicated test case would fit better as a separate test component. Even more integrated with Nimble as a matcher or something like that.

That way, we could have an implementation of this matcher as something that expects to be called in that particular order and when called respond with that particular stub response.

This is would work very much like RSpec, if anyone is acquainted to Ruby code:

```ruby
it "should call 'bar' with appropriate arguments" do
  expect(subject).to receive(:bar).with("an argument I want")
  subject.foo
end
```

**Comment by ashfurrow** [comment]
Neat, I hadn't even considered marchers for Moya. I was only thinking of functional or view snapshot tests. The idea of testing that a request was made... hmm. Sounds useful, but is it something to encourage? 

Like, it's possible now for sure, but a bit of work. I can't think of many scenarios where testing that a request was made would be more ideal than testing the actions based on the network response. Does that make sense? Curious about the use case.

**Comment by alcarvalho** [comment]
Yeah, I don't really have a use case for that. I just remembered of that when I saw @colinta's comment.

But something that generally annoys me when writing tests with stubbed requests is that we usually only test the response component of it. Not what we send to the request. With this mechanism we could have both.

**Comment by scottrhoyt** [comment]
What do you guys think about revisiting this and how it might fit in with #881 ?

**Comment by scottrhoyt** [comment]
Since there hasn't been any activity on this thread for some time, I am going to go ahead and close it. Please re-open or create a new issue if you would like to discuss further. Thanks.
