### ISSUE TITLE
CodeCov is not working correctly

### ISSUE THREAD

**Issue by ashfurrow** [Moya/Moya#562]
I noticed this when our CI tries to upload unit test code coverage reports:

```
error: Failed to load coverage
```

([Example build](https://circleci.com/gh/Moya/Moya/343).)

It happens for quite a few files, which may explain why as of a few weeks ago, our coverage dropped for %90 to %60. 

I have no experience with the tool, this might be an easy fix. If anyone nom @Moya/contributors who has experience could take a look, I would be very grateful :bow:

**Comment by ashfurrow** [comment]
@sizzlr Do you still use CodeCov? Is this anything you've seen before?

**Comment by pedrovereza** [comment]
The [example project from CodeCov](https://github.com/codecov/example-swift) is having the same issue: https://travis-ci.org/codecov/example-swift/builds/146633163

Seems like it's an issue with the tool itself.

**Comment by ashfurrow** [comment]
Maybe we should remove it from continuous integration until it's working again?

**Comment by pedrovereza** [comment]
Hm, found something while digging in the tool

![image](https://cloud.githubusercontent.com/assets/1916041/17272624/e8dd3752-5671-11e6-94b5-41b6c326c7e3.png)

[These changes](https://codecov.io/gh/Moya/Moya/branch/master/commits?from=2016-07-07%2000%3A00%3A00&to=2016-07-11%2000%3A00%3A00) happened on the day the coverage went down:

![image](https://cloud.githubusercontent.com/assets/1916041/17272691/af68ea6e-5673-11e6-8024-5e6c1a7956dd.png)

The build for `48e4b01` has the same error messages in the coverage log: https://circleci.com/gh/Moya/Moya/285

Feels like it's an actual drop in the coverage, not an issue with the tool.

**Comment by ashfurrow** [comment]
Huh! When I get a chance, I'll take a look at Xcode's code coverage and see what it thinks. We might need to close this and open an "increase code coverage" issue 😉

**Comment by BasThomas** [comment]
Have you been able to have a look at this, @ashfurrow?

**Comment by ashfurrow** [comment]
I have not, would anyone be able to take a look?

**Comment by BasThomas** [comment]
Sure, how can I do so? Where are the tests located? It (obviously) doesn't work for the demo tests.

**Comment by BasThomas** [comment]
Xcode itself reports 0% (as it checks the demo itself, not the library)... or am I overlooking something?

<img width="1512" alt="screen shot 2016-08-26 at 14 31 42" src="https://cloud.githubusercontent.com/assets/4190298/18005381/e6aacd90-6b99-11e6-8581-766d1fdbfa3a.png">

**Comment by pedrovereza** [comment]
@BasThomas You have to check `Show Test Bundles` on the upper right corner 😉

**Comment by BasThomas** [comment]
Ah great, thanks. The overall coverage reported by Xcode is 80% (see attached)

<img width="1680" alt="coverage1" src="https://cloud.githubusercontent.com/assets/4190298/18006575/74644958-6ba0-11e6-8426-0610ab22a571.png">
<img width="1680" alt="coverage2" src="https://cloud.githubusercontent.com/assets/4190298/18006576/75c4e8fc-6ba0-11e6-81d2-d0e86270dccf.png">

**Comment by ashfurrow** [comment]
Thanks for looking into that! 80% is a far cry from the 66% CodeCov is reporting, looks like there may be a config issue. Anyone familiar with this?

**Comment by BasThomas** [comment]
Not familiar with CodeCov, but the algorithms to get a percentage might be different, explaining the difference. But the gap would still be pretty big...

**Comment by pedrovereza** [comment]
Coverage reported by CodeCov is back to 79%. Closing this for now.
