### ISSUE TITLE
Multipart PATCH not supported

### ISSUE THREAD

**Issue by AlexQuinlivan** [Moya/Moya#567]
In Moya+Internal.swift the case for uploading with a PATCH is not allowed. 
The multipart upload seems to be limited by this check:
`target.method == .POST || target.method == .PUT`

Alamofire supports PATCH-ing with multipart as a PATCH is just a partial PUT, is it intended for Moya to not support it?

**Comment by colinta** [comment]
I think we could just add PATCH to that list.

**Comment by colinta** [comment]
Do you want to open a PR to address this?  I was looking at this table: <https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol#Summary_table> and it looks like even `CONNECT` can have a body.  I looked around and found no reason that it would need to receive a file (I couldn't find an example of sending a body at all), but on the other hand - why not support it?

**Comment by colinta** [comment]
A slick way to do this would be to add an extension to `Moya.Method` (aka `Alamofire.Method`) that adds `var supportsMultipart: Bool`, then we can add specs for that var.

**Comment by ashfurrow** [comment]
That is a 💯 idea.

**Comment by colinta** [comment]
We can move discussion to PR #569
