### ISSUE TITLE
Request cancelled vs network failure (error.nserror)

### ISSUE THREAD

**Issue by mingyeow** [Moya/Moya#570]
i am dependent on the error.nserror to inform me of whether the operation is cancelled, or it is a network failure.

Right now, i can cast it as customconvertiblestring, but i lose the parsing, and if i cast it as error, i do not get the needed information (999)

See below for what i am doing. I do not want to throw a error message if operation is cancelled, rather than network failure.

Thanks in advance! 

``` swift
struct Network {

  static let sharedInstance = Network()
  let provider = MoyaProvider(endpointClosure: endpointClosure)
  let db = DisposeBag()

  // this returns an reactive operation able to be triggered asynchronously
  func reactiveRequest<T:Mappable>(target:Spark) -> Operation<[T], NSError> {
    return Operation(producer: { observer in
     .....
        case let .Failure(error):
          if error.nsError.code == -999{
            print ("operation cancelled")
          } else {
            self.defaultFailureCallback(error)
            // this throws an error message
          }
          observer.completed()
        }
      }

      return BlockDisposable({
        request.cancel()
      })
    })
  }

```

**Comment by leoneparise** [comment]
So, do you want to catch and ignore the error?

**Comment by mingyeow** [comment]
Yes, that is what i would like to do - catch and ignore the error. 

As you can see, if the errorcode is -999, i am not showing the user any UI. otherwise, i am calling the default network failure indicator.

```
          if error.nsError.code == -999{
            print ("operation cancelled")
          } else {
            self.defaultFailureCallback(error)
            // this throws an error message
          }

```

**Comment by ashfurrow** [comment]
Tricky problem! It might be possible for us to handle this, but it would be a departure from `URLSessionTask`'s behaviour. I'm not sure if Moya should be circumventing the behaviour of CocoaTouch libraries. 

A workaround could be to (manually?) dispose of the `Observable` before cancelling, which should prevent errors from being sent on the observable. Let us know how it's going :+1:

**Comment by BasThomas** [comment]
Hey @mingyeow, did you find a way to make it work as you wanted?

**Comment by scottrhoyt** [comment]
Since there hasn't been any activity on this thread for some time, I am going to go ahead and close it. Please re-open or create a new issue if you would like to discuss further. Thanks.
