### ISSUE TITLE
Error: unable to find endpoint

### ISSUE THREAD

**Issue by BMR731** [Moya/Moya#573]
```swift
let endpointClosure = { (target: MyTarget) -> Endpoint in
  let url = target.baseURL.URLByAppendingPathComponent(target.path).absoluteString
  let endpoint: Endpoint = Endpoint(URL: url, sampleResponseClosure: {.NetworkResponse(200, target.sampleData)}, method: target.method, parameters: target.parameters)
  return endpoint.endpointByAddingHTTPHeaderFields(["APP_NAME": "MY_AWESOME_APP"])
}

let provider = MoyaProvider(endpointClosure: endpointClosure)
```

then i got this error

```swift
"errors" : [
"Unable to find endpoint"
]
```

my usage is not correct or something, i read the documents....,thank you

**Comment by ashfurrow** [comment]
Interesting! "Unable to find endpoint" suggests that the request is failing on the server side of things, like maybe the URL you're trying to hit isn't correct? Can you try using the [network activity plugin](https://github.com/Moya/Moya/blob/master/docs/Plugins.md#network-activity-indicator) to print out what exact URLs Moya is using, and then double-check that they're correct?

**Comment by BMR731** [comment]
ok..thank you, i will check it again

**Comment by BMR731** [comment]
i find this things,
when i use the
