### ISSUE TITLE
Text and Image added to "files" in multipart form data

### ISSUE THREAD

**Issue by mattfxyz** [Moya/Moya#580]
Using Charles, I noticed anything in the MultipartFormData array is added to the files section of the request. When testing the same request Postman, text is added to "fields" and the image is added to "files". 

Is this Moya's intended behavior? It seems like only files should go to files

**Comment by mattfxyz** [comment]
I did some digging, it looks like by setting the `mimeType` to "", Moya tells Alamofire that it's a file type, adding it to the files section of the multipart/form-data request. 

I'm happy to provide a fix.

**Comment by spxrogers** [comment]
a PR would be awesome @mattfxyz :)

**Comment by leoneparise** [comment]
@mattfxyz Is it fixed?

**Comment by mattfxyz** [comment]
This change never made it into Swift 2.3 or 2.2. Are there plans to release an update or can I merge into the release branch?

**Comment by mattfxyz** [comment]
I have a fix in my fork. Can we create a new release branch?

**Comment by BasThomas** [comment]
Should be possible, can you create a PR?

**Comment by mattfxyz** [comment]
What branch? Should I just make a new 2.3 one?

**Comment by BasThomas** [comment]
I suppose so, and then release a `7.something` release for CP / Carthage. @ashfurrow, is this possible?

**Comment by ashfurrow** [comment]
Makes sense to me. You should be able to branch off from the tags of our releases.

**Comment by mattfxyz** [comment]
I created a release-7.0.4 branch and opened a PR to migrate the changes into it.
