### ISSUE TITLE
Document multipart upload

### ISSUE THREAD

**Issue by leoneparise** [Moya/Moya#586]
A lot was done to multipart upload last month. Now I see that this was a requested feature by a lot of users. I'm opening this issue to document our current implementation and provide some guidelines of how it works and how can be used. I think next version should be released with this new doc.

The documentation must include:
- [x] How to configure the Target for multipart
- [ ] How to use with Rx extensions
- [ ] Update the main page to tell all users that Moya supports upload

What do you think @colinta @ashfurrow?

**Comment by ashfurrow** [comment]
Makes sense. One note: we don't use the GitHub wiki, but rather the `/docs` folder. Sounds awesome, thanks for opening the issue :+1:

**Comment by stevenbedrick** [comment]
This is an extremely timely issue, as I found this issue just now while searching for some documentation on this very feature! One question: in the `demo` directory tree, there is a sample implementation of the Giphy API that appears to demonstrate how to use the multipart-form-upload features. Does anybody know if the code in this demo is accurate according to the final API? If so, that might be a good place to start with formal documentation.

**Comment by colinta** [comment]
Sorry for the long delay, didn't notice I was mentioned till just now.  AFAIK the code in `demo/` that uses the multiform upload is correct, unless something changed and it wasn't updated!  It should be easy to document the usage, I think the code is straightforward.

**Comment by sunshinejr** [comment]
This one was implemented as well, closing it.
