### ISSUE TITLE
Should Moya be used in conjunction with Promise?

### ISSUE THREAD

**Issue by rlam3** [Moya/Moya#587]
Should Moya be used in conjunction with Promise?

**Comment by colinta** [comment]
Sure!  If you want.  We've started using it with FutureKit, and it works great.

Should Moya *require* or *depend on* one of these microframeworks?  Could, but I would not like that decision made for me.  So I hope we don't go in that direction.

**Comment by colinta** [comment]
https://github.com/ello/ello-ios/blob/cg/add/hire-me-button/Sources/Networking/HireService.swift

**Comment by rlam3** [comment]
@colinta Is there a reason for you guys to choose FutureKit over PromiseKit?

**Comment by colinta** [comment]
Nope, I didn't even look at PromiseKit at the time. Pick whichever seems right for you.

**Comment by rlam3** [comment]
@colinta the source code seems to be missing. Please update? Thanks!

**Comment by ashfurrow** [comment]
@rlam3 has this question been solved to your satisfaction? Happy to provide further clarification.

**Comment by loryhuz** [comment]
Here is an example of implementation I did with PromiseKit, the first is Moya native, the second is a promise which wrap the native call. Of course you don't need the first request is you only use Promises, this is for example:

```swift
    /// Load Place object fullfilled by Google Place API Details response
    ///
    /// - Parameter query: placeID, id of the place to be loaded
    static func getPlace(
        placeID: String,
        success successCallBack: @escaping (Place) -> Void,
        error errorCallback: @escaping (_ error: Moya.Error) -> Void
        ) {
        self.request(
            target: .placeDetails(placeID: placeID),
            success: { response in
                do {
                    let place = try response.mapObject(Place.self)
                    successCallBack(place)
                } catch {
                    errorCallback(.jsonMapping(response))
                }
            }) { error in
                errorCallback(error)
        }
    }
    static func getPlace(placeID: String) -> Promise<Place> {
        return Promise { fulfill, reject in
            self.getPlace(
                placeID: placeID, success: { place in
                    _ = fulfill(place)
                }, error: { error in
                    _ = reject(error)
            })
        }
    }
```

Then in your code, you can use PromiseKit as usually:

```swift
GooglePlacesProvider.getPlace(placeID: "placeId").then { place in
    // Do something
}
```
