### ISSUE TITLE
Introduction on Basic.md doesn't work for me ...?

### ISSUE THREAD

**Issue by hiragram** [Moya/Moya#588]
Hi,
I am new to Moya.
Working on Basic.md and try to stub response, `endpointClosure` is called, but then `sampleResponseClosure` won't be called.
I don't know very well about architecture of Moya, but I want you to confirm that instruction on Basic.md is correct.

**Comment by hiragram** [comment]
I'm using v7.0.0

**Comment by BasThomas** [comment]
A PR to update that would be great!
