### ISSUE TITLE
Alamofire 4 and RxSwift 3 Compatibility

### ISSUE THREAD

**Issue by DenisLaboureyras** [Moya/Moya#589]
Hello,

Alamofire and RxSwift have updated their pods recently to meet swift 3 requirements, and change their major versions (Alamofire 4 and RxSwift 3). We are using them now in our app, but Moya, even in the swift 3 branch, needs older versions.
Also the code in the swift 3 branch seems outdated comparing to master.
We're kind of stuck and can't continue our migration to swift 3 now because of that. We will give a shot to update the code by ourselves but I'm not sure It will be easy for us to do it.
So I was wondering, do you plan to update Moya soon or are you waiting for the GM version of XCode to update your code ?

Thanks a lot.

Kind regards,
Denis

**Comment by BasThomas** [comment]
I'm not sure what the plans on this are, but a PR to update the branch would be great!

**Comment by BasThomas** [comment]
Also, there seems to be an [issue](https://github.com/Moya/Moya/issues/513) that's tracking the progres. I am not sure how up-to-date it is, though. But it might be helpful.

**Comment by DenisLaboureyras** [comment]
OK thanks for the comment! I will track also this issue :)
We're trying to redo the migration from master since this morning, but we have many errors...

**Comment by jefflovejapan** [comment]
I'm trying to get the demo app building with Alamofire 4 and RxSwift 3.0.0.alpha.1 and am having issues with Cocoapods. Changing the `libraries` target like so:

```
def libraries
  pod 'Moya', :path => "../"
#  pod 'Moya/ReactiveCocoa', :path => "../"
  pod 'Moya/RxSwift', :path => "../"
  pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :tag => '4.0.0-beta.2'
  pod 'RxSwift', '~> 3.0.0.alpha.1'
  pod 'RxCocoa', '~> 3.0.0.alpha.1'
#  pod 'ReactiveCocoa', :git => 'https://github.com/mhuusko5/Podspecs.git', :branch => 'swift3.0'
end
```

and running `pod install` or `pod update` generates the following error:

```
Analyzing dependencies
Pre-downloading: `Alamofire` from `https://github.com/Alamofire/Alamofire.git`, tag `4.0.0-beta.2`
Fetching podspec for `Moya` from `../`
Pre-downloading: `Nimble` from `https://github.com/Quick/Nimble.git`, branch `swift-3.0`
Pre-downloading: `Quick` from `https://github.com/Quick/Quick.git`, branch `swift-3.0`
[!] Unable to satisfy the following requirements:

- `RxSwift (~> 3.0.0.alpha.1)` required by `Podfile`
- `RxSwift (~> 3.0.0.alpha.1)` required by `Podfile`
- `RxSwift (~> 3.0.0.alpha.1)` required by `Podfile`
- `RxSwift (~> 3.0.0.alpha.1)` required by `Podfile`

Specs satisfying the `RxSwift (~> 3.0.0.alpha.1)` dependency were found, but they required a higher minimum deployment target.
```

Looking at the [Cocoapods source](https://github.com/CocoaPods/CocoaPods/blob/a2be2d30e7311a5ed33888fd32b3e42d90c768ab/lib/cocoapods/resolver.rb#L435), it looks like this error is actually a catchall for a general failure to resolve dependencies. I've tried updating the `platform` in both the `test_pods` and `Demo` targets to iOS 9.0 but it doesn't help. There's also no reason why the minimum target should be bad, given that RxSwift 3.0.0.alpha.1 [targets iOS 8.0](https://github.com/ReactiveX/RxSwift/blob/3.0.0.alpha.1/RxSwift.podspec#L30).

Does anyone have any idea why this error would be generated? Or, failing that, has anyone been able to get the demo app running with AF4 and RxSwift 3?

**Comment by ashfurrow** [comment]
The Podfile currently uses [10.9 as a target](https://github.com/Moya/Moya/blob/fd2cb69a3e9a6c5e4c978c38563c90941ecbccc5/Demo/Podfile#L37) but [RxSwift requires 10.10](https://github.com/ReactiveX/RxSwift/blob/3.0.0.alpha.1/RxSwift.podspec). Maybe upping that would work?

**Comment by ashfurrow** [comment]
@DenisLaboureyras is this issue still causing trouble?

**Comment by DenisLaboureyras** [comment]
I'm in holidays for 2 weeks, so I don't have any issue :).
If it's ok for you, you can close the issue, I will test it at the end of the month, and keep you posted if there's a problem.
