### ISSUE TITLE
Error Types for Request Closure failures

### ISSUE THREAD

**Issue by tpesce** [Moya/Moya#595]
I'm implementing something similar to the [OAuth example](https://github.com/Moya/Moya/blob/master/docs/Authentication.md#oauth), but in my case I'm wrapping a third-party API call as an RxSwift Observable. The success case works just fine, but I'm having a bit of difficulty with error types in the failure case.

``` swift
let requestClosure = { endpoint, done:RequestResultClosure in
    self.auth(endpoint.urlRequest)
        .subscribe { event in
            switch event {
            case .Error(let error):
                done(.Failure(...))
```

Since RequestResultClosure expects the failure to be a Moya.Error type, I can't use the error directly. Moya.Error.Underlying seems to be the intended way to handle these situations, but since it expects an NSError there are a few shortcomings with it's use; casting to NSError loses fidelity, and a mapping layer is a bit painful since the underlying error domain is part of the third-party library.

I know there have been discussions and changes in this area in the past, so forgive me if this is rehashing old conversations...

Question 1: Would it make sense to add another case to Moya.Error for wrapping underlying ErrorTypes?, something like:

``` swift
case UnderlyingErrorType(ErrorType)
```

Question 2: What about widening the type of RequestResultClosure to allow for a broader range of errors? Perhaps something like:

``` swift
public typealias RequestResultClosure = Result<NSURLRequest, ErrorType> -> Void
```

Question 3: Is this a non-issue once we have Swift 3 and [SE-0112](https://github.com/apple/swift-evolution/blob/7fcba970b88a5de3d302d291dc7bc9dfba0f9399/proposals/0112-nserror-bridging.md)?

**Comment by ashfurrow** [comment]
Great question! I wouldn't mind implementing something for our existing Swift 2.x code, but moving to `ErrorType` on `UnderlyingErrorType` and `RequestResultClosure` removes the ability for developers to switch o a specific `Moya.Error`. 

I'm not sure of the best approach here. @Moya/contributors any ideas?

**Comment by morgz** [comment]
I've also ran into this issue. I've done a auth check in a requestClosure and found myself wanting to throw my own ErrorType. One way around this is to check for conditions that might throw errors beforehand by wrapping the request like is shown [here](https://github.com/Moya/Moya/blob/master/docs/Examples/WrappingInAdapter.md
)

Although, if you need to add a header to the http request then you can't do everything by wrapping the Request, and still have to alter the headers in the requestClosure.

**Comment by morgz** [comment]
Just a follow up. I've found an OK work-around this:

In my request closure I am putting my own ErrorType into the underlyingError like so:

```
let error = Moya.Error.Underlying(ErrorController.LocalError.NoCurrentUser as NSError)
                        done(Result.Failure(error))
```
Then by [wrapping the request](https://github.com/Moya/Moya/blob/master/docs/Examples/WrappingInAdapter.md) I am checking for the existence of the ErrorType, casting it, and throwing it. 

````    
func authenticatedRequest(token:AuthenticatedRemoteService) -> Observable<Response> {
        
        return Observable.create {[unowned self] observer in
            
            self.authenticatedRemoteService
                .request(token)
                .filterSuccessfulStatusCodes()
                .subscribe(
                    onNext:{ response in
                        observer.onNext(response)
                    },
                    onError: { error in
                        
                        // If the underlying error is one of our own types. Then throw it as an Error Type.
                        if case Moya.Error.Underlying(let error) = error {
                            if (error as ErrorType) is ErrorController.LocalError {
                                observer.onError(error)
                                return
                            }
                        }
                        
                        observer.onError(error)
                    }, onCompleted: {
                        observer.onCompleted()
                    }, onDisposed: nil)
                .addDisposableTo(self.disposeBag)
            
            return NopDisposable.instance
        }
    }
```

Not ideal but it seems to work.

**Comment by BasThomas** [comment]
Thanks for the follow up!

**Comment by scottrhoyt** [comment]
Since there hasn't been any activity on this thread for some time, I am going to go ahead and close it. Please re-open or create a new issue if you would like to discuss further. Thanks.
