### ISSUE TITLE
Error example creates Xcode warning

### ISSUE THREAD

**Issue by perlguy99** [Moya/Moya#596]
The example code at the bottom of the Examples/ErrorTypes page generates the following warning in Xcode:

“Conditional cast from 'Error' to 'Error' always succeeds” 

It is generated on the

`if let moyaError = error as? Moya.Error {`

 line.

Any ideas on how to get rid of that warning?

Thank you.

**Comment by BasThomas** [comment]
I think you can omit the `?` when casting (so, `as` instead of `as?`).

**Comment by perlguy99** [comment]
I had tried that.   If you omit the ?, then you get an error which says:

`Enum case 'Some' not found in type 'Error'`

**Comment by BasThomas** [comment]
I have been taking a look, and it seems the `error` is not an optional. The unwrapping therefore makes no sense. Also, I found converting the `error` from `Error` to `Moya.Error` has no effect either, so that can be committed as well. That means you can the following in your closure:

```swift
let provider = MoyaProvider<MyService>()
provider.request(.CreateUser(firstName: "James", lastName: "Potter")) { result in
  switch result {
  case let .Success(response):
    ()
  case let .Failure(error):
    switch error {
    case .Data(let response):
      print(response)
    case .ImageMapping(let response):
      print(response)
    case .JSONMapping(let response):
      print(response)
    case .StatusCode(let response):
      print(response)
    case .StringMapping(let response):
      print(response)
    case .Underlying(let nsError):
      // now can access NSError error.code or whatever
      // e.g. NSURLErrorTimedOut or NSURLErrorNotConnectedToInternet
      print(nsError.code)
      print(nsError.domain)
    }
  }
}
```

which will 'just work'.
