### ISSUE TITLE
How to implement parameters in this format: ["15", "19"] ?

### ISSUE THREAD

**Issue by Unihilator** [Moya/Moya#597]
Hey guys! There is a get request which might be in this format: 
`http://address.com?parameter1=["15", "19"]`
I tried many things: tried to pass array of int `[Int]`, try to pass array of String `[String]`, tried to generate simple string like `["15", "19"]`. In the last case it encodes with percent encoded string. For me no need to encode this parameter. What should I do? Please help

**Comment by ashfurrow** [comment]
Great question – we actually had developers with a similar problem a while ago, check out their issue: https://github.com/Moya/Moya/issues/431 I think you'll find the solution here. Let us know how it goes.

**Comment by Unihilator** [comment]
I used already this solution with Custom parameter encoding. But It did not resolve a problem. 
```swift
let AuthURLEncodingclosure: AuthEncoding = { request, data in
    var queryParameters: [NSURLQueryItem] = []
    for (key, value) in Session.authParameters() {
        let queryParameter = NSURLQueryItem(name: key, value: value)
        queryParameters.append(queryParameter)
    }
    
    if let data = data {
        for (key, value) in data {
            let queryParameter = NSURLQueryItem(name: key, value: "\(value)")
            queryParameters.append(queryParameter)
        }
    }
    var req = request.URLRequest as NSMutableURLRequest
    
    guard var components = NSURLComponents(string: req.URL!.absoluteString) else {
        return (req, nil)
    }
    
    components.queryItems = queryParameters
    req.URL = components.URL
    
    return (req, nil)
}
```
The problem is when I print req from last string - it is percent encoded(param1==%5B%2215%22,%20%22418%22)

**Comment by ashfurrow** [comment]
I think I may have misunderstood your initial question, but I think you should be able to use the default `.URL` parameter encoding.

When returning `parameters` from the target, does the following work?

```swift
return ["parameter1": "[\"15\", \"19\"]"]
```

Normally when URL-encoding an array, the format is something like `parameter[]=15&parameter[]=19`, I think. If that's not what you want, then you'll need to create the final string you're looking for manually, which is a bit messy I admit. Just using the `parameters` property of `Target` should be enough.

**Comment by Unihilator** [comment]
Thanks @ashfurrow ! Sorry for late response. We postpone this issue and will change api. 
It's bad expirience to use that kind of request parameters. 
And yes - I've try kind of string for the parameters. I generate it in a string messy way. 
This does not work. Waiting for api changes 😄
