### ISSUE TITLE
How do we debug/see the request being set over to backend servers when using RxSwift?

### ISSUE THREAD

**Issue by rlam3** [Moya/Moya#604]
How do we debug the request being set over to backend servers? \

I'd like to be able to see exactly or print out the full request with headers parameters, etc... that is being sent over to servers when i'm doing rxswift with moya...

How exactly should we be using the .debug()? 

Thanks!

**Comment by ashfurrow** [comment]
You can use the [built-in network logging plugin](https://github.com/Moya/Moya/blob/master/docs/Plugins.md) which can be used to log all requests.

**Comment by rlam3** [comment]
@ashfurrow Thanks!
