### ISSUE TITLE
Numbers serialization

### ISSUE THREAD

**Issue by Rommanski** [Moya/Moya#605]
Hi, thank you for the cool framework!
I have parameters in request:

```swift
case .SearchUPC(let ups):
      return [   "upc": ups,
                 "limit": 1  ]
```

On server side I am getting this:

```json
{
  "upc": "9",
  "limit": "1"
}
```

How I can serialize parameters this way:

```json
{
  "upc": "9",
  "limit": 1
}
```

**Comment by ashfurrow** [comment]
Moya relies on Alamofire to do its parameter encoding, I'm a bit surprised that it behaves this way. There is a workaround though.

Sounds like you might need to use a custom parameter encoding, similar to [what's described here](https://github.com/Moya/Moya/blob/master/docs/Examples/ArrayAsRootContainer.md). You can do this on a per-target basis, so just `SearchUPC` if that makes sense for your code.

**Comment by Rommanski** [comment]
Thank you @ashfurrow I was surprised too. It looks pretty weirdly. I have checked all stuff twice and didn't find any reason for this behavior.
By the way, I have solved issue. Thank you for the help again!

**Comment by BasThomas** [comment]
Care to share how you solved it? :)

**Comment by Rommanski** [comment]
Hello @BasThomas I have changed server side for accepting ups in String. Not very good solution :)
I am wondered. Why this problem occurs only with me. I suppose it my fault.
