### ISSUE TITLE
How/where to set the HTTP JSON body.

### ISSUE THREAD

**Issue by zhaoyunyi** [Moya/Moya#619]
#Moya_Logger: [11/09/2016 15:53:17] Request Headers: ["X-ApiKey": "Q2Cf8Qs1E1B85A201", "Content-Type": "application/json"]
Moya_Logger: [11/09/2016 15:53:17] HTTP Request Method: POST
Moya_Logger: [11/09/2016 15:53:17] Request Body: {"country_code":"86","phone":18815289863}
Moya_Logger: [11/09/2016 15:53:17] Response: Received empty network response for register("86", 18815289863).

    let endpoint: Endpoint<RequestAPI> = Endpoint<RequestAPI>(URL: url,
                                                              sampleResponseClosure: {.NetworkResponse(200, target.sampleData)},
                                                              method: target.method,
                                                              parameters: target.parameters,
                                                              parameterEncoding: target.parameterEncoding,
                                                              httpHeaderFields: ["X-ApiKey": ApiKey,
                                                                "Content-Type": "application/json"])

    public var parameterEncoding: Moya.ParameterEncoding {
        switch self {
        case .uploadPictureTest:
            return ParameterEncoding.URL
        case .register:
            return ParameterEncoding.JSON
        default:
            return ParameterEncoding.Custom(MyAPICallCustomEncodingClosure)
        }
    }

**Comment by BasThomas** [comment]
What exactly is your question?

**Comment by zhaoyunyi** [comment]
How/where to set the HTTP JSON body...this code is unusefule

**Comment by zhaoyunyi** [comment]
typealias MyAPICallCustomEncoding = (URLRequestConvertible, [String:AnyObject]?) -> (NSMutableURLRequest, NSError?)

let MyAPICallCustomEncodingClosure: MyAPICallCustomEncoding = { request, data in
    let sort = NSURLQueryItem(name: "sort", value: "distance")
    var req = request.URLRequest as NSMutableURLRequest
    
    guard var components = NSURLComponents(string: req.URL!.absoluteString)
        else {
            // even though this is an error, Alamofire ignores the returned error.
            return (req, nil)
    }
    //Create our query string params
//    components.queryItems = [sort]
    req.URL = components.URL
    
    //Add our JSON body
    do {
        let json = try NSJSONSerialization.dataWithJSONObject(data!, options: NSJSONWritingOptions.PrettyPrinted)
        req.setValue("application/json; charset=utf-8", forHTTPHeaderField: "Content-Type")
        req.HTTPBody = json
        
        print(String(json))
    } catch {
        return (req, nil)
    }
    
    return (req, nil)
}

**Comment by BasThomas** [comment]
Ref #620
