### ISSUE TITLE
[Swift 2.3] Moya tag 7.0.1 is identical to tag 7.0.0

### ISSUE THREAD

**Issue by hewigovens** [Moya/Moya#623]
Hi, I tried Moya 7.0.1 to support Xcode 8 & Swift 2.3 but failed, then I noticed that the tag in the new added [Moya 7.0.1 podspec (for Swift 2.3)](https://github.com/CocoaPods/Specs/blob/master/Specs/Moya/7.0.1/Moya.podspec.json) is 7.0.1 which identical to tag 7.0.0.

Could you please update the tag 7.0.1? Thanks

**Comment by pedrovereza** [comment]
Hey @hewigovens, this is being worked on in #594 :wink:
