### ISSUE TITLE
Question: Are you supposed to create different services for the endpoints or just one?

### ISSUE THREAD

**Issue by peterwarbo** [Moya/Moya#624]
Lets say I have an API with endpoints 

- `/CreateUser `
- `/GetActivities` 
- `/GetSettings`

Should I create:

- `UserService`
- `ActivityService`
- `SettingsService`

And then `MoyaProvider<UserService>` ... `MoyaProvider<ActivityService>` and so on?

Or should should I just create one Service which manages all endpoints? 
Like `MoyaProvider<APIService>` ?

I don't really understand the architecture of Moya.

**Comment by filograno** [comment]
You need to create only one Service that manages all endpoints. To better understand how to use Moya see the documentation at:<https://github.com/Moya/Moya/blob/master/docs/Examples/Basic.md>

If you have further question write here!
