### ISSUE TITLE
How to use Moya in swift3.0

### ISSUE THREAD

**Issue by lixingshi** [Moya/Moya#627]
today ,i updated my Xcode to 8.0 and found that moya does not support swift 3.0,what can i do then?

**Comment by sunshinejr** [comment]
Hey @lixingshi! We are currently working hard on releasing Moya for Swift 3.0 in PR#608. For now you can use Moya with CocoaPods specifying the branch "swift-3.0", like:
```
pod "Moya", :git => "https://github.com/Moya/Moya", :branch => "swift-3.0"
```
And switch to Moya 8.0 when the release happens.

Hope it helps!

**Comment by rlam3** [comment]
@sunshinejr What if we need moya with rxswift and swift 3.0?

**Comment by ashfurrow** [comment]
This should work:

```rb
pod "Moya/RxSwift", :git => "https://github.com/Moya/Moya", :branch => "swift-3.0"
```

Let us know how it goes :+1:

**Comment by gordoneliel** [comment]
Hi @ashfurrow, I tried using the above but it doesn't seem to work as Moya/RxSwift is pointing to this branch of RxSwift (~> 3.0.0-beta.1). Is there any temporary solution to this?

**Comment by BasThomas** [comment]
Is there a problem with `Moya` here, or the `RxSwift` branch? @gordoneliel

**Comment by gordoneliel** [comment]
@BasThomas The RxSwift branch
<img width="361" alt="screen shot 2016-09-15 at 12 02 09 am" src="https://cloud.githubusercontent.com/assets/5516761/18541072/b3d4b03c-7ad7-11e6-983a-286d52315a08.png">

**Comment by BasThomas** [comment]
But does that not work? It should point to the / a Swift 3 branch of Rx of course.

**Comment by zhaoyunyi** [comment]
use of undeclared type RxMoyaProvider...the same problem,how to slove

**Comment by BasThomas** [comment]
Any idea @sunshinejr?

**Comment by zhaoyunyi** [comment]
waiting for answer ，thank

**Comment by sunshinejr** [comment]
Hmm, what is your Podfile @zhaoyunyi? Can you download our Demo and check if it works for you? Because I've downloaded it, and `RxMoyaProvider` works just fine in the Demo. Another idea could be that you maybe forgot importing `RxSwift` at the top of your file along with `Moya`?

**Comment by zhaoyunyi** [comment]
you are right , i check my Podfile and modify it.
use this can slove it
pod "Moya/RxSwift", :git => "https://github.com/Moya/Moya", :branch => "swift-3.0"

**Comment by lixingshi** [comment]
@sunshinejr thank you ,it works well
