### ISSUE TITLE
What version is still compatible with xcode 7 and swift 2.3?

### ISSUE THREAD

**Issue by rlam3** [Moya/Moya#631]
What version is still compatible with xcode 7 and swift 2.3?

**Comment by ashfurrow** [comment]
7.0.1 is the last version that is compatible with Xcode 7 / Swift 2.2. Moya 7.0.2 is compatible with Xcode 8 running Swift 2.3. Swift 3 support is still a work-in-progress: #608.

**Comment by marcelofabri** [comment]
There's also a table in README now: https://github.com/Moya/Moya#moya-version-vs-swift-version

**Comment by BasThomas** [comment]
Does that answer your question, @rlam3? :)

**Comment by rlam3** [comment]
@BasThomas Thanks!
