### ISSUE TITLE
Cannot use optional chaining on non-optional value of type 'NSURL'

### ISSUE THREAD

**Issue by iwheelbuy** [Moya/Moya#634]
Just updated from 7.0.0 to 7.0.2 and received an error in:

```swift
public extension MoyaProvider {

    public final class func DefaultEndpointMapping(target: Target) -> Endpoint<Target> {
        guard let stringURL = target.baseURL.URLByAppendingPathComponent(target.path)?.absoluteString  else {
            fatalError("\(target) url is not valid")
        }
        return Endpoint(URL: stringURL, sampleResponseClosure: {.NetworkResponse(200, target.sampleData)}, method: target.method, parameters: target.parameters)
    }
}
```

`URLByAppendingPathComponent` is non-optional, but there is a "?".
What am I doing wrong? :)

**Comment by BasThomas** [comment]
I think you are still using Swift 2.2, correct? `7.0.2` is a Swift 2.3 release :)

**Comment by isatria** [comment]
So what should i do to fix that ? @BasThomas

**Comment by BasThomas** [comment]
Use `7.0.0` on Swift 2.2 instead, upgrading to `7.0.2` once you switch to Swift 2.3 :)

**Comment by Denis1992** [comment]
Hi,
pod 'Moya', '~> 7.0.0'
pod install
Using Moya (7.0.2) 

O_o

**Comment by BasThomas** [comment]
I think you did a pod update before? I don't think `pod install` automatically downgrades to the specific pod version. You should be able to update to `7.0.0` again now, I think?

**Comment by Denis1992** [comment]
No,
pod 'Moya', '~> 7.0.0'
pod update
Installing Moya 7.0.2 (was 6.5.0)

**Comment by sunshinejr** [comment]
@Denis1992 please use specific Moya version, like:
```
pod 'Moya', '7.0.0'
```

**Comment by Denis1992** [comment]
@sunshinejr thx.

**Comment by BasThomas** [comment]
Fixed now? ^^

**Comment by Denis1992** [comment]
@BasThomas yep, thx for answer :)

**Comment by BasThomas** [comment]
🙌

**Comment by v-ken** [comment]
README needs to be updated...

<img width="307" alt="screen shot 2016-10-13 at 4 58 40 pm" src="https://cloud.githubusercontent.com/assets/5682879/19338092/6576ee46-9166-11e6-8756-9db5b1bd8deb.png">

**Comment by sunshinejr** [comment]
You are right @v-ken, it should be fixed now. Thanks for mentioning! 🙇
