### ISSUE TITLE
Reasoning behind iOS 9 minimum requirement?

### ISSUE THREAD

**Issue by joshuawright11** [Moya/Moya#639]
Just wondering why the .podspec  (of the Swift 3.0 version) has a minimum requirement of iOS 9. According to https://developer.apple.com/support/app-store/ iOS 8 is still 9% of the market share, and our app tends to target people with slower adoption rates.

Cheers!

Love the project and all your work in the iOS/Swift/MVVM community. Our product would be far worse off if you didn't exist ;)

**Comment by AndrewSB** [comment]
https://github.com/Moya/Moya/pull/608#issuecomment-247292895

**Comment by ashfurrow** [comment]
Thanks for the kind words! I dug around the Alamofire repository and found this discussion which includes rationale for their decision: https://github.com/Alamofire/Alamofire/issues/1367 I personally find this regrettable, but there are comments in that issue of using forks of Alamofire that continue to support iOS 8. If you find one that works, I'd be happy to help you use Moya with them.
