### ISSUE TITLE
Sorted Parameters 

### ISSUE THREAD

**Issue by Henawey** [Moya/Moya#644]
Hi,
I have a problem where I'm required to sort the request parameters before sending it ,Is there any way to sort request parameters? or sending it as String instead of a dictionary?

**Comment by aamctustwo** [comment]
@Henawey My initial thought would be to pass in a custom `RequestClosure` when you create your `MoyaProvider`. You can modify a request that's been assembled by Moya just before it goes out the door. So it should already be populated with your parameters and just need last meeting adjusting by you.

See:
- [RequestClosure Documentation](https://github.com/Moya/Moya/blob/master/docs/Endpoints.md#request-mapping)
- [MoyaProvider Initializer](https://github.com/Moya/Moya/blob/7adb73ae4736c4f02b4cf9e076c6ddaeb435c56a/Source/Moya.swift#L58-L72)

**Comment by BasThomas** [comment]
Does @aamctustwo's answer solve your problem, @Henawey? Let us know it doesn't :)

**Comment by Henawey** [comment]
Yes, I do it with Custom `RequestClosure` and add string with structure I want I know this is not a good practice but solve the problem :)
