### ISSUE TITLE
Thoughts on Issue / PR templates

### ISSUE THREAD

**Issue by BasThomas** [Moya/Moya#646]
@Moya/contributors was thinking of this. Should we add templates for issues / PRs? For example, I noticed some issues with no / incomplete Podfiles / Carthage files, which makes it harder for us to help the person with the question.

I am not sure what exactly should be in them - but they should be able to both help people with questions, as well as the people helping.

Let me know what you think; feedback is definitely welcome!

**Comment by ashfurrow** [comment]
I think this is a good idea, what are the most common miscommunications we need to address in issues?

**Comment by orta** [comment]
Some examples:
* https://github.com/CocoaPods/CocoaPods/blob/master/.github/ISSUE_TEMPLATE.md
* https://github.com/danger/danger/tree/master/.github

**Comment by lucasp90** [comment]
I find the [Realm](https://github.com/realm/realm-cocoa/blob/master/.github/ISSUE_TEMPLATE.md) template really useful.

**Comment by BasThomas** [comment]
It would also be useful to make users aware of syntax highlighting for code in these templates.

**Comment by devxoul** [comment]
Totally agreed with @BasThomas. Some users don't know how to use code blocks. We can add some examples in issue/PR templates. For example:

<pre>
### What you did:

```swift
func example() {
  thisCodeWillBeFormatted(in: .swift)
}
```

### What you expected:

blah blah
</pre>

**Comment by lucasp90** [comment]
I agree with @devxoul, templates are helpful for newcomer contributors.

**Comment by pedrovereza** [comment]
Closed after #704

**Comment by BasThomas** [comment]
A PR template still has to / can be done maybe?

**Comment by pedrovereza** [comment]
@BasThomas you're right, my bad 😅

**Comment by BasThomas** [comment]
I don't see the need to add a PR template right now. If someone does, please reopen or submit a PR :)
