### ISSUE TITLE
Rename ReactiveCocoa subspec

### ISSUE THREAD

**Issue by ashfurrow** [Moya/Moya#648]
We don't depend on ReactiveCocoa anymore (in Swift 3), just its new cousin: [ReactiveSwift](https://github.com/ReactiveCocoa/ReactiveSwift). It's a really cool project they're undertaking, separating ReactiveCocoa into two libraries. 

Since we now have a different dependency, I think it's worth considering renaming the `Moya/ReactiveCocoa` subspec to `Moya/ReactiveSwift`. We'd also need to rename directories, Swift extension file names and extension names, and document it as well.

**Comment by orta** [comment]
This is a major breaking change, will need docs in the changelog etc on how to migrate blah blah blah

**Comment by BasThomas** [comment]
Do we want to take this on for `8.0.0`? This might be the best time to do so.

**Comment by ashfurrow** [comment]
Makes sense to me. I was thinking we could include it as two subspecs, and deprecate the old one in favour of the new. To avoid repeating ourselves in the podspec, we can have the old deprecated subspec simply have a dependency on the new one. Does that make sense?

**Comment by BasThomas** [comment]
That does make sense, but I am not sure how to do that myself. @Moya/contributors, anyone that wants to take a stab at this?

**Comment by AndrewSB** [comment]
8's going to be a big one 😮

**Comment by ashfurrow** [comment]
Yup. I think we should be about good to go. Anything else we need for 8.0?

**Comment by BasThomas** [comment]
Wait for an official release for ReactiveSwift is about it, I think.

**Comment by BasThomas** [comment]
#805 has been merged. 🤗

**Comment by ashfurrow** [comment]
Cool cool. I don't see any more 1.0 issues on their repo, and they just had a new pre-release of 1.0 ship two days ago, so hopefully it won't be too long.

**Comment by BasThomas** [comment]
Let's hope so. 😀

**Comment by BasThomas** [comment]
Seems like there's now one issue still open for [1.0](https://github.com/ReactiveCocoa/ReactiveSwift/milestone/1) there, but I bet it won't take too long anymore.
