### ISSUE TITLE
Carthage CI is taking a long time

### ISSUE THREAD

**Issue by ashfurrow** [Moya/Moya#656]
Circle CI executes the following command, to make sure we don't break Carthage compatibility:

```sh
carthage bootstrap --platform 'iOS'
```

This takes about 15 minutes, which about doubles the length of a build. I'm wondering if there's something we're not doing right that's contributing to this, since (if I understand correctly) we're just cloning + building the dependencies. @justinmakaila just wondering, do you have any ideas on ways we could improve Carthage CI build times?

**Comment by AndrewSB** [comment]
@ashfurrow carthage is pretty slow, so unfortunately a 15 minute bootstrap is not unexpected. We could use something like https://github.com/guidomb/carthage_cache to speed up build times though

**Comment by ashfurrow** [comment]
Gotcha. Circle CI doesn't support parallelism on macOS builds, but we could try moving Carthage to Travis CI to have it run parallel with our unit tests, which should cut CI times in half.

**Comment by ashfurrow** [comment]
Tried this, not really worth it.
