### ISSUE TITLE
[RX] Debugging Mode between Moya and Alamofire

### ISSUE THREAD

**Issue by juliengdt** [Moya/Moya#658]
Hello everyone,

I'm using Moya with pleasure but i'm facing a problem. I like seeing in XCode my REST requests be launched, with header fields, url and params.

Is it possible to add some debugRequest()/debugResponse() Observables to let us show or not full informations about what has been sent ?

I don't know how to do it but if there are some clue on Moya how to do it, I can try !

PS: same question for users who don't use RxSwift 

tag: question, enhancement, feature

**Comment by pedrovereza** [comment]
Hey, check #604

**Comment by juliengdt** [comment]
You completely right ! Sorry for this question, can be closed
