### ISSUE TITLE
`ReactiveMoya` doesn't build for Carthage (also assuming for CocoaPods)

### ISSUE THREAD

**Issue by justinmakaila** [Moya/Moya#660]
There are some slight API updates coming from `ReactiveCocoa` -> `ReactiveSwift` that cause `ReactiveMoya` to fail during build.

Working on those updates now, PR soon.

**Comment by ashfurrow** [comment]
Interesting, things seem to be working on CI, but that's with a specific version of ReactiveSwift (specifically, their d4de1ff81c12124d148f726b8b44dd6887b41ae0 commit).

**Comment by justinmakaila** [comment]
I'm talking about the `send(value:)` vs `sendNext` methods

**Comment by ashfurrow** [comment]
Gotcha, thanks!

**Comment by justinmakaila** [comment]
Closed #661
