### ISSUE TITLE
Shouldn't Response.mapJSON() throw Error.jsonMapping?

### ISSUE THREAD

**Issue by marcusficner** [Moya/Moya#662]
Hi all!

I'm wondering why there is an ```Moya.Error``` ```jsonMapping```, but it isn't used anywhere.
Shouldn't mapJSON throw this error like this?

```swift
func mapJSON(failsOnEmptyData: Bool = true) throws -> Any {
        do {
            return try JSONSerialization.jsonObject(with: data, options: .allowFragments)
        } catch {
            if data.count < 1 && !failsOnEmptyData {
                return NSNull()
            }
            throw Error.jsonMapping(self)
        }
    }
```

**Comment by sunshinejr** [comment]
Hey @marcusficner! This is a really good question, I'm not really sure _why_ we don't use it in the `mapJSON()` function, but I would be up for introducing it there!

**Comment by marcusficner** [comment]
Hi @sunshinejr! Alright, I've committed a pull request ✌🏼

**Comment by sunshinejr** [comment]
Closing in favor of #664 then!
