### ISSUE TITLE
Increase code coverage

### ISSUE THREAD

**Issue by ashfurrow** [Moya/Moya#668]
Our code coverage is okay, at a solid 80%. We've held this for a while, but we could do a bit better. Our [current coverage](https://codecov.io/gh/Moya/Moya/tree/master/Source) has some places we could improve:

<img width="1154" alt="screen shot 2016-09-21 at 9 37 47 pm" src="https://cloud.githubusercontent.com/assets/498212/18734570/d21c2478-8043-11e6-8c54-86b7d0d3c683.png">

I'll take a look sometime, this is probably a longer-term task though.

**Comment by Viniciuscarvalho** [comment]
@ashfurrow this task requires expanding the use of different classes? Or use more RxSwift and others?

**Comment by ashfurrow** [comment]
Both actually, the graph above is just an outline, you can see individual files' coverage in the link.

**Comment by Viniciuscarvalho** [comment]
@ashfurrow There are some files that are not being found for example Moya + Internal, is giving 404 error.

**Comment by ashfurrow** [comment]
Hmm. Sounds like it could be a configuration issue, do you have experience with CodeCov? Could be worth a look.

**Comment by ashfurrow** [comment]
Looks like CodeCov can't access file names with + in them, like https://codecov.io/gh/Moya/Moya/src/master/Source/Moya%2BInternal.swift . I've contacted their support team to clear it up.

**Comment by ashfurrow** [comment]
We're in the high 80's, CodeCov seems to be working. Gonna close this, thanks everyone 👍
