### ISSUE TITLE
Update ReactiveCocoa installation instructions

### ISSUE THREAD

**Issue by ashfurrow** [Moya/Moya#673]
And Demo file, since they have a release we can reference now: https://github.com/ReactiveCocoa/ReactiveSwift/issues/20

**Comment by Viniciuscarvalho** [comment]
Update these statements, `https://github.com/Moya/Moya/blob/master/docs/ReactiveCocoa.md` or that are in the readme? @ashfurrow

**Comment by ashfurrow** [comment]
The readme, needs to use the same Podfile format as the Demo project. A PR would be awesome!

**Comment by Viniciuscarvalho** [comment]
@ashfurrow I made a change in the ReadMe for Active installation equal to podfile Demo project. 👍  #693

**Comment by ashfurrow** [comment]
Cool, thanks!
