### ISSUE TITLE
Maya dependency fails a pod lint

### ISSUE THREAD

**Issue by spxrogers** [Moya/Moya#675]
hello lovlies––I'm trying to update a community library I maintain to support Swift 3 and all, however the `Moya+Alamofire.swift` file is ERROR'ing the lint :( 

here's the output of the `pod lib lint`:
```
➜  Moya-Gloss git:(master) ✗ pod lib lint

 -> Moya-Gloss (2.0.0-beta.2)
    - WARN  | [Moya-Gloss/Core, Moya-Gloss/RxSwift, Moya-Gloss/ReactiveCocoa, and more...] xcodebuild:  Moya/Source/Moya+Internal.swift:206:16: warning: value 'progress' was defined but never used; consider replacing with boolean test
    - ERROR | [Moya-Gloss/Core, Moya-Gloss/RxSwift, Moya-Gloss/ReactiveCocoa, and more...] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - ERROR | [Moya-Gloss/Core, Moya-Gloss/RxSwift, Moya-Gloss/ReactiveCocoa, and more...] xcodebuild:  Moya/Source/Moya+Alamofire.swift:9:46: error: no type named 'StreamRequest' in module 'Alamofire'
    - WARN  | [Moya-Gloss/RxSwift] xcodebuild:  Moya/Source/RxSwift/Moya+RxSwift.swift:31:20: warning: 'init' is deprecated: renamed to 'Disposables.create'
    - NOTE  | [Moya-Gloss/RxSwift] xcodebuild:  Moya/Source/RxSwift/Moya+RxSwift.swift:31:20: note: use 'Disposables.create' instead
    - WARN  | [Moya-Gloss/RxSwift] xcodebuild:  Moya/Source/RxSwift/Moya+RxSwift.swift:57:20: warning: 'init' is deprecated: renamed to 'Disposables.create'
    - NOTE  | [Moya-Gloss/RxSwift] xcodebuild:  Moya/Source/RxSwift/Moya+RxSwift.swift:57:20: note: use 'Disposables.create' instead
    - WARN  | [Moya-Gloss/RxSwift] xcodebuild:  RxCocoa/RxCocoa/Common/TextInput.swift:74:28: warning: 'RxTextInput' is deprecated: renamed to 'TextInput'
    - NOTE  | [Moya-Gloss/RxSwift] xcodebuild:  RxCocoa/RxCocoa/Common/TextInput.swift:74:28: note: use 'TextInput' instead
    - WARN  | [Moya-Gloss/RxSwift] xcodebuild:  RxCocoa/RxCocoa/Common/TextInput.swift:67:29: warning: 'RxTextInput' is deprecated: renamed to 'TextInput'
    - NOTE  | [Moya-Gloss/RxSwift] xcodebuild:  RxCocoa/RxCocoa/Common/TextInput.swift:67:29: note: use 'TextInput' instead
    - WARN  | [Moya-Gloss/ReactiveCocoa] xcodebuild:  Moya/Source/ReactiveCocoa/Moya+ReactiveCocoa.swift:5:45: warning: 'where' clause next to generic parameters is deprecated and will be removed in the future version of Swift

[!] Moya-Gloss did not pass validation, due to 2 errors and 6 warnings.
You can use the `--no-clean` option to inspect any issue.
```

relevant podspec is [here](https://github.com/spxrogers/Moya-Gloss/blob/master/Moya-Gloss.podspec). i ran with the `--verbose` tag and found the **watchOS 2.0 platform** with the **ReactiveCocoa** subspec that failed and building and removing the watchOS deployment target succeeds the lint. 

:/ hoping maybe some other contributors would have some insight, maybe @ashfurrow?

**Comment by orta** [comment]
Are you using a swift-version file? https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md#110rc2-2016-09-13

**Comment by spxrogers** [comment]
yep! @orta

**Comment by orta** [comment]
Would recommend using `--no-clean` to take a look a the resulting folder with lint, double check all the versions of alamofire/moya are what you expect them to be - as a [StreamRequest does exist](https://github.com/Alamofire/Alamofire/blob/a946285f1b1efcb7129d546f00c90ae213678185/Source/Alamofire.swift#L438) inside head Alamofire

You can also clean your pod cache for this listing stuff with `pod cache clean`

**Comment by spxrogers** [comment]
right, i found it too which why i thought it quite funky. 

i'll inspect the `--no-clean` output as well as clean the pod cache.

**Comment by petester42** [comment]
Are you using cocoapods 1.1.0.rc.2? Using it fixed all my problems related to lint fails.

**Comment by spxrogers** [comment]
@petester42 yep, i am.

so: https://github.com/Alamofire/Alamofire/blob/master/Source/Request.swift#L577-L600 
... line 577 in AF only compiles `StreamRequest` if the os is not watch, explaining why the lint fails when compiling the watchOS platform :| 

i guess this begs the question on how Moya isn't encountering this as well since [it similarly supports watchOS](https://github.com/Moya/Moya/blob/master/Moya.podspec#L18)

**Comment by ashfurrow** [comment]
Interesting, watchOS isn't being tested on CI, maybe our watch support has been broken for a while and we've just not noticed until now?

We're not even using the `StreamRequest` anywhere, we should be able to delete [this line of code](https://github.com/Moya/Moya/blob/25b8072a2cffa3baff3aea90ed94afed2c03b076/Source/Moya%2BAlamofire.swift#L9) without any problems.

**Comment by spxrogers** [comment]
@ashfurrow funny. AF didn't introduce this type until version 4 and i had no issues updating to support Moya 7, so likely not broken for so long :) 

i'll get a PR working and make sure nothing breaks, hopefully not!

**Comment by ashfurrow** [comment]
Cool, thanks!
