### ISSUE TITLE
Change Endpoint Helper Functions

### ISSUE THREAD

**Issue by nanoxd** [Moya/Moya#679]
After looking at some of the documentation, I feel that `Endpoint`s helper functions should be changed in response to Swift 3.0's new [API design guidelines](https://swift.org/documentation/api-design-guidelines/#promote-clear-usage). This would be a breaking change.

## The Problem

With the recent changes in Swift 3.0 to the standard library, the following functions are verbose without adding much clarity. 

* `endpointByAddingParameters`
* `endpointByAddingHTTPHeaderFields` 
* `endpointByAddingParameterEncoding`
* `endpointByAdding`

## Potential Solutions

Modeling after `URL`, Swift 3.0 took the very verbose `URLByAppending*` functions and removed the redundant type and dropped `by`. We were left with `appending*(pathComponent: )` functions that communicated the same intent. Two possible solutions for a Moya transition would be:

* `endpointByAddingParameters(_ parameters: [String: Any])`
  * -> `adding(parameters: [String: Any])`
  * -> `addingParameters(_ parameters: [String: Any]`
* `endpointByAddingHTTPHeaderFields(_ httpHeaderFields [String: String])` 
  * -> `adding(httpHeaders: [String: String])`
  * -> `addingHTTPHeaders(_ httpHeaders: [String: String])`
* `endpointByAddingParameterEncoding(_ newParameterEncoding: Moya.ParameterEncoding)`
  * -> `adding(parameterEncoding: Moya.ParameterEncoding)`
  * -> `addingParameterEncoding(_ newParameterEncoding: Moya.ParameterEncoding)`
* `endpointByAdding(parameters: [String: Any]? = nil, httpHeaderFields: [String: String]? = nil, parameterEncoding: Moya.ParameterEncoding? = nil)`
  * -> `adding(parameters: [String: Any]?, httpHeaderFields: [String: String]?, parameterEncoding: Moya.ParameterEncoding?)`

What are everyone's thoughts on this 💭?  I'll open up a PR, if anything comes from this 🎱.

**Comment by BasThomas** [comment]
Yes, I definitely think we should do this.

**Comment by ashfurrow** [comment]
Great idea! I like it. Let's do the first one: `adding(thing:...`. A PR would be :100:

**Comment by nanoxd** [comment]
Cool, I'll send one over shortly
