### ISSUE TITLE
Alamofire ParameterEncoding

### ISSUE THREAD

**Issue by nanoxd** [Moya/Moya#681]
It looks like Alamofire removed [ParameterEncoding enum](https://github.com/Alamofire/Alamofire/blob/d59ed4f611a447c98881be24764b130e3f7d24bd/Documentation/Alamofire%204.0%20Migration%20Guide.md#parameter-encoding-protocol) for a Protocol of the same name. 

We [typealias locally](https://github.com/Moya/Moya/blob/master/Source/Moya%2BAlamofire.swift#L13) here and use it in [Endpoint](https://github.com/Moya/Moya/blob/master/Source/Endpoint.swift#L23). 

The [docs](https://github.com/Moya/Moya/blob/master/docs/Endpoints.md#from-target-to-endpoint) should be updated to remove the enum values. 

Will the change cause issues with Moya's usage of ParameterEncoding?

**Comment by ashfurrow** [comment]
Great question, thanks for linking to relevant code :bow: We definitely need to do something here, at least in docs. I'll take a look later today and see what we can do.

**Comment by RamwiseMatt** [comment]
Any word on a fix for this? It is unclear to me at this point how to properly encode requests.

**Comment by ashfurrow** [comment]
Cool, that sounds like a good fix @RamwiseMatt. I think we just need to update our docs then, right? Anyone available for a pull request?

**Comment by bryanbartow** [comment]
Just a heads up, I'm using 8.0 Beta 2 in a framework project I'm working on and this is giving me fits. Using @RamwiseMatt solution in my endpoint closure:
``` Swift
let endpointClosure = { (target: RebatesProvider) -> Endpoint<RebatesProvider> in
  let url = target.baseURL.appendingPathComponent(target.path).absoluteString
  var encoding: Moya.ParameterEncoding = JSONEncoding()
      
  switch target.method {
    case .GET:
      encoding = URLEncoding()
    default:
      encoding = JSONEncoding()
  }
      
  let endpoint: Endpoint<RebatesProvider> = Endpoint<RebatesProvider>(URL: url, sampleResponseClosure: {.networkResponse(200, target.sampleData)}, method: target.method, parameters: target.parameters, parameterEncoding: encoding)
      
  return endpoint
}
```
gives me the following compiler errors:
```
Undefined symbols for architecture x86_64:
  "type metadata for Alamofire.URLEncoding", referenced from:
      function signature specialization <Arg[0] = Owned To Guaranteed> of OffersKit.Rebates.(init () -> OffersKit.Rebates).(closure #1) in Rebates.o
  "type metadata for Alamofire.JSONEncoding", referenced from:
      function signature specialization <Arg[0] = Owned To Guaranteed> of OffersKit.Rebates.(init () -> OffersKit.Rebates).(closure #1) in Rebates.o
  "protocol witness table for Alamofire.URLEncoding : Alamofire.ParameterEncoding in Alamofire", referenced from:
      function signature specialization <Arg[0] = Owned To Guaranteed> of OffersKit.Rebates.(init () -> OffersKit.Rebates).(closure #1) in Rebates.o
  "protocol witness table for Alamofire.JSONEncoding : Alamofire.ParameterEncoding in Alamofire", referenced from:
      function signature specialization <Arg[0] = Owned To Guaranteed> of OffersKit.Rebates.(init () -> OffersKit.Rebates).(closure #1) in Rebates.o
  "static Alamofire.URLEncoding.default.getter : Alamofire.URLEncoding", referenced from:
      function signature specialization <Arg[0] = Owned To Guaranteed> of OffersKit.Rebates.(init () -> OffersKit.Rebates).(closure #1) in Rebates.o
  "static Alamofire.JSONEncoding.default.getter : Alamofire.JSONEncoding", referenced from:
      function signature specialization <Arg[0] = Owned To Guaranteed> of OffersKit.Rebates.(init () -> OffersKit.Rebates).(closure #1) in Rebates.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Commenting out my endpoint closure and removing it from the provider initializer causes everything to work just fine.

**Comment by sunshinejr** [comment]
Hey @bryanbartow, only typo I found in your code is the `.GET` instead of `.get` enum case, otherwise it should be good to go. I've tested it in the Moya demo and was building correctly. If there are still some errors and cleaning doesn't help, let us know! 

Also I'm closing this one in favor of #709. If you guys could chime in, it would be awesome! 👊

**Comment by marcelofabri** [comment]
@bryanbartow I got the same error of yours, and in the same context (a podspec that depends on Moya). What I did was to add Alamofire directly on the podspec. However, this is weird because we didn't have this issue on previous Moya versions 🤔

**Comment by bryanbartow** [comment]
@sunshinejr Although I believe you had renamed the method cases in master by the time this came up, pod specs only allow you to point to releases and the 8.0.0 beta 2 tag/release still had uppercase cases. Either way, I don't think that's the issue.

@marcelofabri I'll give that a shot.

**Comment by sunshinejr** [comment]
Oh, I will keep this opened till we resolve the issue then :)

**Comment by bryanbartow** [comment]
@marcelofabri I forgot to report back on this. Following your suggestion of explicitly adding Alamofire to the podspec dependencies seems to have fixed this issue for me.

**Comment by BasThomas** [comment]
Closing this now, then. :)
