### ISSUE TITLE
Broken documentation link

### ISSUE THREAD

**Issue by charlag** [Moya/Moya#682]
Hi!
I noticed a broken link on the page
https://github.com/Moya/Moya/blob/9bee1ff9117d2a743cfc39d57839473dbf470fe6/docs/Providers.md
The link is [Examples](Examples.md)
I would fix it myself but I'm not sure that I will do it correctly. Thanks.

**Comment by BasThomas** [comment]
Thanks for noticing! I've fixed it now :)
