### ISSUE TITLE
Swift 3: lowercase HTTP verb enums?

### ISSUE THREAD

**Issue by BasThomas** [Moya/Moya#684]
Should we lowercase these, too?

https://github.com/Moya/Moya/blob/366a3142825957169a2807269382bb868d54f00c/Source/Target.swift#L52

**Comment by spxrogers** [comment]
AF did 🙃 
https://github.com/Alamofire/Alamofire/blob/e8bca7e40a861327366c5ccba42a688d17ec482a/Source/ParameterEncoding.swift#L30-L40

**Comment by sunshinejr** [comment]
👍

**Comment by ashfurrow** [comment]
Makes sense, does anyone have time to submit a PR?

**Comment by nanoxd** [comment]
✋ I can do it if no one else has time today
