### ISSUE TITLE
Reflect new way of encoding in docs

### ISSUE THREAD

**Issue by BasThomas** [Moya/Moya#690]
Can someone take a look at `From Target to Endpoint` here? Alamofire's encoding has changed, but I am not entirely sure how myself.

https://github.com/Moya/Moya/blob/master/docs/Endpoints.md

This also might mention some incorrect code(?)

https://github.com/Moya/Moya/blob/master/docs/Examples/ArrayAsRootContainer.md

**Comment by BasThomas** [comment]
@nanoxd, any idea?

**Comment by pschneider** [comment]
This seems to be related to #681 
Still trying to figure out how to set the encoding in Alamofire.request via Moya now.

**Comment by BasThomas** [comment]
Right, closing this in favor of #681.
