### ISSUE TITLE
Allow stubbing of NSURLResponse within sampleResponseClosure

### ISSUE THREAD

**Issue by gregkerzhner** [Moya/Moya#701]
We are using Moya to build a caching layer on top of a restful service.  The way we uniquely identify requests in our system is via their URL, which we store into our data store (using Realm).   Specifically, we are using the `response?.URL?.absoluteString` property of `Response`.  We would like to test this functionality, but the only way to stub a response seems to be with a `EndpointSampleResponse`, which always has a `response` of `nil`.  

Is there any way we can open the response property up for stubbing?  Something like
```swift
/// Used for stubbing responses.
public enum EndpointSampleResponse {

    /// Note the additional NSURLResponse field
    case NetworkResponse(Int, NSData, NSURLResponse?)

    /// The network failed to send the request, or failed to retrieve a response (eg a timeout).
    case NetworkError(NSError)
}

```

**Comment by ashfurrow** [comment]
Hmm, what an interesting idea! I think if we were to include `NSURLResponse`, we would want to remove the `Int` status code. Another solution would be to add another `case` to the enum. I think that would make a lot of sense, actually. Want to send a pull request?

**Comment by gregkerzhner** [comment]
Here is a PR: https://github.com/Moya/Moya/pull/717

One thing is that I ended up using an NSHTTPURLResponse not a plain NSURLResponse because those don't have status codes, let me know if you have thoughts on another direction here though.

Also, if we make this change we probably need to update the documentation, which I can do also do if you want.

**Comment by BasThomas** [comment]
Adding documentation for this change is definitely appreciated! 😃
