### ISSUE TITLE
Compilation error in ReactiveCocoa in xcode 8

### ISSUE THREAD

**Issue by kanishkatn** [Moya/Moya#702]
Hi,

I am getting couple of compilation errors in xcode 8. Please help me.

![screen shot 2016-10-04 at 1 07 00 pm](https://cloud.githubusercontent.com/assets/4919645/19065835/84ab32b6-8a33-11e6-83bc-d42ead54b110.png)
![screen shot 2016-10-04 at 1 06 49 pm](https://cloud.githubusercontent.com/assets/4919645/19065836/84dceb9e-8a33-11e6-9edf-cfdfba8976c7.png)

Update: Alamofire is throwing errors as well
![screen shot 2016-10-04 at 1 08 43 pm](https://cloud.githubusercontent.com/assets/4919645/19065872/c551d6ee-8a33-11e6-96d7-17b6946a8d01.png)

**Comment by BasThomas** [comment]
What is your `Podfile` like?

**Comment by kanishkatn** [comment]
> # Uncomment this line to define a global platform for your project
> # platform :ios, '9.0'
> 
> target 'BetMe' do
>   # Comment this line if you're not using Swift and don't want to use dynamic frameworks
>   use_frameworks!
> 
>   # Pods for BetMe
>   pod 'Firebase/Core'
>   pod 'Firebase/Database'
>   pod 'Firebase/Auth'
>   pod 'SideMenu'
>   pod 'TGLStackedViewController', '~> 2.0'
>   pod 'Moya/RxSwift'
>   pod 'Moya/ReactiveCocoa'
>   pod 'SwiftyJSON'
>   pod 'GMStepper'
>   pod 'YUTableView-Swift', :git=> 'https://github.com/ujell/YUTableView-Swift.git', :branch => 'Swift3'
>   pod 'SwiftDate'
>   pod 'ScrollableGraphView'
>   pod 'FoldingCell'
>   pod 'STCollapseTableView'
>   pod 'DLRadioButton', '~> 1.4'
>   pod 'PageMenu'
>   pod 'LiquidFloatingActionButton'
>   pod 'SnapKit', '~> 3.0'
>   target 'BetMeTests' do
>     inherit! :search_paths
>     # Pods for testing
>   end
> 
>   target 'BetMeUITests' do
>     inherit! :search_paths
>     # Pods for testing
>   end
> 
> end
>

**Comment by ashfurrow** [comment]
Hey there, can you double-check the installation instructions for CocoaPods [in the readme](https://github.com/Moya/Moya#cocoapods)? Then run `pod update Alamofire Moya` and that should do the trick 👍

**Comment by kanishkatn** [comment]
It did. Thanks a lot :)
