### ISSUE TITLE
Moya version for Swift X.X

### ISSUE THREAD

**Issue by sunshinejr** [Moya/Moya#706]
Hey guys! So I was wondering if we should make a note somewhere in the documentation / README, that specific version of Moya support X version of Swift. I wasn't sure if there is need for something like this so I am asking you: what do you think about it? 👊

**Comment by BasThomas** [comment]
I think that's a good idea - I don't see it doing any harm, anyway 😃

**Comment by sunshinejr** [comment]
Great! Closing this one in favor of #710 which should implement the idea.
