### ISSUE TITLE
AWS Upload - Order of parameters

### ISSUE THREAD

**Issue by batrinuvlad** [Moya/Moya#708]
Hello,

I'm trying to upload an image to AWS and I receive the following response: "Bucket POST must contain a field named 'key'.  If it is specified, please check the order of the fields. ". 

Request Body:
 {"policy":"CiAgICA...",
"signature":"RYm9...",
"ContentType":"image\/jpeg",
"key":"7c20c...jpeg",
"AWSAccessKeyId":"AKI...",
"acl":"public-read"}

``` swift
public var parameters: [String: AnyObject]? {
  switch self {
    case let .UploadFile(data: dataResponse , file: _):
                        return [
                            "key" : dataResponse.filename,
                            "AWSAccessKeyId" : dataResponse.awsKey,
                            "acl" : "public-read",
                            "signature" : dataResponse.signature,
                            "policy" : dataResponse.policy,
                            "Content-Type" : "image/jpeg"
                        ]
  }
}

    public var multipartBody : [MultipartFormData]? {
        switch self {
        case .UploadFile( _, let file):
            let formData = [MultipartFormData(provider: .Data(file), name: "file", mimeType:"image/jpeg", fileName: "file")]
            return formData
        default:
            return []
        }
    }

```

Also, in the endpoint closure I change the headers to `assigned = ["Accept": "application/json", "Accept-Language": "", "Content-Type": "image/jpeg"]`  but they get overridden when the request is logged into 
`["Accept": "application/json", "Accept-Language": "", "Content-Type": "multipart/form-data; boundary=alamofire.boundary.05a9529d0374a3b8"]`

Anyway, I guess the headers aren't the problem because the content type is indeed multipart/form-data, but the question is: How can I change the order of the fields from body request or what would be another way to upload to AWS using MOYA?

**Comment by scottrhoyt** [comment]
I think a way this can be accomplished now is to create a custom `ParameterEncoding` that searches for the `key` parameter makes sure to encode that first.

**Comment by scottrhoyt** [comment]
Since there hasn't been any activity on this thread for some time, I am going to go ahead and close it. Please re-open or create a new issue if you would like to discuss further. Thanks.

**Comment by madhavisolanki** [comment]
Changing the hierarchy of code actually solves this problem. But I am not sure if it will break something.

Class : MoyaProvider+Internal.swift
  ```
    func sendUploadMultipart(_ target: Target, request: URLRequest, queue: DispatchQueue?, multipartBody: [MultipartFormData], progress: Moya.ProgressBlock? = nil, completion: @escaping Moya.Completion) -> CancellableWrapper {
        let cancellable = CancellableWrapper()

        let multipartFormData: (RequestMultipartFormData) -> Void = { form in
            if let parameters = target.parameters {
                parameters
                    .flatMap { key, value in multipartQueryComponents(key, value) }
                    .forEach { key, value in
                        if let data = value.data(using: .utf8, allowLossyConversion: false) {
                            form.append(data, withName: key)
                        }
                }
            }
            
            for bodyPart in multipartBody {
                switch bodyPart.provider {
                case .data(let data):
                    self.append(data: data, bodyPart: bodyPart, to: form)
                case .file(let url):
                    self.append(fileURL: url, bodyPart: bodyPart, to: form)
                case .stream(let stream, let length):
                    self.append(stream: stream, length: length, bodyPart: bodyPart, to: form)
                }
            }
        }

        manager.upload(multipartFormData: multipartFormData, with: request) { result in
            switch result {
            case .success(let alamoRequest, _, _):
                if cancellable.isCancelled {
                    self.cancelCompletion(completion, target: target)
                    return
                }
                cancellable.innerCancellable = self.sendAlamofireRequest(alamoRequest, target: target, queue: queue, progress: progress, completion: completion)
            case .failure(let error):
                completion(.failure(MoyaError.underlying(error as NSError)))
            }
        }

        return cancellable
    }

```

**Comment by madhavisolanki** [comment]
With above changes you need to also change in Alamofire Parameter encoding. Since its sorted alphabetically 
` private func query(_ parameters: [String: Any]) -> String {
        var components: [(String, String)] = []

        for key in parameters.keys.sorted(by: <) {
            if key == "key" {
                let value = parameters[key]!
                components += queryComponents(fromKey: key, value: value)
                break
            }
        }
        
        for key in parameters.keys.sorted(by: <) {
            if key != "key" {
                let value = parameters[key]!
                components += queryComponents(fromKey: key, value: value)
            }
        }
        return components.map { "\($0)=\($1)" }.joined(separator: "&")
    }`
