### ISSUE TITLE
How about bot?

### ISSUE THREAD

**Issue by lolgear** [Moya/Moya#711]
How did you setup that close issues?

**Comment by BasThomas** [comment]
What do you mean? I am not sure I understand your question.

**Comment by lolgear** [comment]
@BasThomas 

@BasThomas 
For example:

https://github.com/Moya/Moya/pull/563 MoyaBot helps in checking PR.

https://github.com/MoyaBot

**Comment by BasThomas** [comment]
If you look closely at @MoyaBot's message, you can see it is generated by [Danger](http://danger.systems/). :)

**Comment by lolgear** [comment]
@BasThomas thanks!
