### ISSUE TITLE
How to add url parameters and httpbody? 

### ISSUE THREAD

**Issue by shivayogic** [Moya/Moya#714]
Hello, I am new to Moya, I would like to have a parameterised url and also httpbody as json. I followed the issue #431 using xcode 8 with swift 3. I am geting ambiguous error while compiling. Apart from that Issue #431 discusses about having custom parameterisation, but do not discuss on how do I pass url paramters and httpbody to the end point. Early help appreciated. Below is the code snippet
```swift
import Foundation
import Moya
import Alamofire

public enum CCV2Api {
    
    case addContact(urlParam:[String:Any]?)
}

typealias MyAPICallCustomEncoding = (URLRequestConvertible, [String:AnyObject]?)throws -> URLRequest


let JsonArrayEncodingClosure: (URLRequestConvertible, [String:AnyObject]?) -> (URLRequest, NSError?) = { request, data in
    var req = request.urlRequest
    
    return (req!, nil)
}

let MyAPICallCustomEncodingClosure: MyAPICallCustomEncoding = { request, data in
    let sort = URLQueryItem(name: "sort", value: "distance")
    var req = request.urlRequest
    
    guard var components = URLComponents(string: (req?.url!.absoluteString)!)
        else {
            // even though this is an error, Alamofire ignores the returned error.
            return (req!)
    }
    //Create our query string params
    components.queryItems = [sort as URLQueryItem]
    req?.url = components.url
    req?.setValue("application/json; charset=utf-8", forHTTPHeaderField: "Content-Type")
    
        let json = try JSONSerialization.data(withJSONObject: data!, options: .prettyPrinted)
        
        
        req?.setValue("application/json; charset=utf-8", forHTTPHeaderField: "Content-Type")
        req?.httpBody = json
    return req!
}

extension  CCV2Api: TargetType {
    
    public var baseURL: URL { return URL(string: "https://XYZ.com/v2")! }
    public var path: String {
        switch self {
        case .addContact(_):
            return "contacts"
        }
    }
    public var method: Moya.Method {
        switch self {
        case .addContact(_):
            return .POST
        }
    }
    public var parameters: [String: Any]? {
        switch self {
            
        case .addContact(let bodyParam):
            return bodyParam
        }
    }
    
    public var parameterEncoding: Moya.ParameterEncoding {
        switch self {
        case .addContact(let bodyParam):
            
            return ParameterEncoding.Custom(MyAPICallCustomEncodingClosure)
        }
    }
    public var sampleData: Data {
        return Data()
    }
    public var task: Task {
        return .request
    }
    
}
```
I get the below error message on ParameterEncoding.Custom
Ambiguous reference to member 'ParameterEncoding'. Am i doing something wrong?

**Comment by BasThomas** [comment]
Not sure, but shouldn't the `.Custom` be `.custom`?

**Comment by shivayogic** [comment]
@BasThomas Even after changing to .custom still I am facing the same issue

**Comment by sunshinejr** [comment]
@shivayogic if you are using Swift 3 version of Moya, there is no `enum` for `ParameterEncoding`, if you want custom one, you need to subclass `ParameterEncoding` protocol. More on the topic in our documentation [here](https://github.com/Moya/Moya/blob/master/docs/Endpoints.md#from-target-to-endpoint). Hope it helps! 👊

**Comment by shivayogic** [comment]
@sunshinejr Thank you for the information. Looking into documentation I have few questions

 Can I add httpBody in endPointCloser? If so, is it the right way of doing it rather creating custom parameterEncoding? How can I add httpBody in the EndpointCloser

**Comment by sunshinejr** [comment]
@shivayogic usually you don't need to specify custom `httpBody`, parameters do it for you. If you want to add parameters that you want in every request, then `endpointClosure` might be the best way. However if your case is a specific one, you might try to replace the httpBody of a request in `requestClosure`.

**Comment by shivayogic** [comment]
@sunshinejr Thank you. The reason for asking is I have to set url parameter as well as httpbody. The way I am looking is endpoint will have 2 arguments, one for url parameter and another is the httpbody. From #431 I can understand that Moya is supporting either httpbody or url parameter. Both cannot be accomplished.  The way I am looking is, url parameter can be set as it is by the Moya and the other parameter to the endpoint can be be added to httpBody in endpointCloser. Hope this is fine. Also I would like to know how to set the httpBody in the endpoint closer?
Thanks a lot

**Comment by shivayogic** [comment]
I am stuck,. Any help appreciated.

**Comment by shivayogic** [comment]
Resolved my self by using custom endpointCloser. For the POSt method Moya treats it as BODY. In order to send both url parameter and Body parameter to the end point, for parameter return the body to be used and for the url parameters you can add the to url in endpoint closer.

**Comment by pete183** [comment]
@shivayogic Hey, would you be able to share the code to add url parameters and httpbody please?
