### ISSUE TITLE
Which baseURL to use for a stub-only provider?

### ISSUE THREAD

**Issue by benpackard** [Moya/Moya#718]
There are occasions where a base URL isn't available and the `sampleData` is relied on for all requests. For example:
- The app is in development and the API isn't available yet. 
- The app allows the user to switch to a 'demo mode' at runtime, where the provider relies only on `sampleData`.

What is the correct `NSURL` to provide as the `baseURL` in such instances? A simple `NSURL()` will result in fatal error `url is not valid` when the url is constructed by Moya:

``` swift
// Moya.swift
guard let stringURL = target.baseURL.URLByAppendingPathComponent(target.path)?.absoluteString else {
    fatalError("\(target) url is not valid")
}
```

The URL won't be accessed so should I try just sticking `google.com` in there? Even then, I still need to account for the fact that `NSURL(string: String)` returns an optional and `baseURL` does not, so if I either have to force unwrap, or fall back to `NSURL()` eventually:

``` swift
var baseURL: NSURL {
    return appDefaults.selectedShow.apiURL ?? NSURL(string: "http://google.com") ?? NSURL()
}
```

This all feels like I'm on the wrong track - is there something I'm missing? What is the best practice here?

I'm using Moya 7.0.2 on Swift 2.3. Thanks.

**Comment by ashfurrow** [comment]
What a great question! Usually for example URLs that aren't meant to ship, I use example.com – this sounds like a good alternative?

**Comment by benpackard** [comment]
Thanks Ash - still feels slightly fishy to have to provide a URL that should never be used, plus a fallback (`NSURL()`) that returns a known fatal error. What would the ramifications be of making `baseURL` optional, I wonder? Likely a can of worms, I guess?

**Comment by ashfurrow** [comment]
It would be a can of worms, unfortunately. The trouble is that somewhere – either inside Moya or outside – someone needs to deal with the fact that a call to `NSURL(string: )` might return `nil`. We've decided it's better to give the user of the library the flexibility to fail as they like, instead of having Moya fail or work unexpectedly.

It's a balance, there are arguments for both approaches. Do you think adding documentation of this rationale might help explain it to other Moya users? Where should we put that documentation?

**Comment by benpackard** [comment]
I think that's the right call. In my own example, if I don't have a URL string I'm debating whether to throw my own fatal error, let Moya do so, or output a warning and use `example.com` and it makes sense that I get to determine that.

I guess the [Basic Usage]()https://github.com/Moya/Moya/blob/master/docs/Examples/Basic.md page is where the `!` first jumps out to me but I think that page does a nice succinct job of explaining setup and it probably wouldn't be a good idea to add it there.

**Comment by ashfurrow** [comment]
Agreed, Basic Usage is already a large document. 

We could create a new `Advanced.me` file and discuss it there. Could you send a pull request adding it?
