### ISSUE TITLE
Eidolon goes into deadlock when requesting from network whilst offline?

### ISSUE THREAD

**Issue by AndrewSB** [Moya/Moya#722]
I noticed an interesting bug with my networking code. 
All of my requests go through this observable, that I think pulled code 1:1 from https://github.com/artsy/eidolon:

``` swift
return online
            .ignore(false)  // Wait until we're online
            .take(1)        // Take 1 to make sure we only invoke the API once.
            .flatMap { _ in // Turn the online state into a network request
                return actualRequest
            }
```

The issue I'm running in to is when the app is completely offline, my request never returns. i.e. I request `logIn`, and my UI is blocked for eternity, or until I relaunch the app. Should I be running my requests with a timeout to prevent this sort of deadlock?

**Comment by ashfurrow** [comment]
What an interesting question! I hadn't thought of having the observable error after a timeout, a really neat idea. But Alamofire+NSURLConnection will already error on timeout, looks like my code here is really just interfering with that. It sounds like what you need is an observable that:

- Errors on network unavailability.
- Retries when signalled by an "I'm Online!" signal.

I actually found a really good example in the RxSwift repository of how to do this: https://github.com/ReactiveX/RxSwift/blob/4952adb27c684b47792923b00015516849061eab/RxExample/RxExample/Services/ReachabilityService.swift I think Eidolon should probably move to that approach too.

**Comment by zeew** [comment]
`swift3`

```swift

func showErrorHUD() -> Observable<Element> {
        return self.do (
            onError:{ e in
                
                if e is Moya.Error{
                    SVProgressHUD.showError(withStatus: "")
                }
                else{
                    throw e
                }
                
            }
            
        )
    }

```

**Comment by AndrewSB** [comment]
@ashfurrow yup, that sounds like the way it should be done.

I've been thinking: it would be really useful to extract Eidolen's networking stack into a sub-repo.
Two reasons:

1. Many @Moya/contributors often link to Eidolon as an implementation example, having a repo with just the networking part of eidolon would be easier for new readers to digest
2. Eidolon has a pretty great RxMoya networking stack, I used almost an exact copy of it in the app that I was previously working on. It would be awesome if the two of us (and whoever else) could share an opinionated RxMoya implementation, so we can fix things like deadlocks together.

I'm free today, I could create the repo (not sure if it makes sense to have it under artsy or Moya), and then also create a PR to eidolon that removes the code from `App/Networking/` and includes it through the new repo

Cheers

**Comment by ashfurrow** [comment]
Mmm, interesting idea. What components of the network stack are you keen to isolate? You're thinking we could add it as a library, like a new pod? If you'd like, go ahead and create the repo under your own account and we can discuss it from there?

**Comment by AndrewSB** [comment]
I was thinking everything other than `XAppToken`, `ArtsyAPI`, and `APIKeys`, but I have a feeling I'll run into some implementation issues once I get started.

I'll get started on the repo & get eidolon integrated with it

Any thoughts on a name for the repo?

**Comment by ashfurrow** [comment]
Cool cool. Let's give it some boring name and we can think of something more specific once we've got code to inspire the name?

**Comment by AndrewSB** [comment]
Yup, I did GitHub.com/AndrewSB/Networking. The library is much smaller than I thought it would be, there was a voice in my head saying that making a new repo to solve this problem may have been overkill :p 

I'll create a WIP PR for eidolon so we can figure out your integration first

**Comment by ashfurrow** [comment]
Cool, thanks Andrew! I probably won't be able to take an in-depth look until Monday, but I wanted to thank you for exploring this! Even if it turns out to be overkill, we've still learned something we can use to make documentation better, etc. Thanks again!

**Comment by AndrewSB** [comment]
Cool, no rush at all! Thanks Ash

**Comment by ashfurrow** [comment]
Cool, so @AndrewSB I took a look at the new repo, definitely see what you mean by it might be overkill, what are your current thoughts on this? Do you reckon another repo gives us enough benefits that it's worth it, or would moving a lot of this into Moya's documentation folder feel more appropriate?

**Comment by justinmakaila** [comment]
Two cents real quick: I think rather than having a full repo, we could put the relevant parts in the documentation, and break down the design decisions behind the structs and protocols and whatnot. 

I think Moya is one of the most powerful networking libraries because of it's strict types and how easy it is to transform responses/monitor outgoing requests, and I think we can make it much stronger by giving developers a little more guidance on what the patterns that Moya encourages look like in practice (simple authentication, custom error mapping, reachability, etc).

**Comment by AndrewSB** [comment]
Yeah, I noticed it was overkill as I was working on it.
There are still some things to add, but even with them I think it's too small.

1. @justinmakaila @ashfurrow: what do you think of adding the `OnlineProvider` to Moya core? In implementing the online provider I noticed that `Alamofire` includes a Reachability manager, so we'd be able to implement the `OnlineProvider` without importing a Reachability library

2. @ashfurrow: I was thinking about building a protocol to abstract away authentication tokens. For two reasons:

    1. https://github.com/AndrewSB/Networking/issues/2 talks about how my implementation of authentication was unsafe (I believe Eidolon does something very similar)
    2. To have a good solution for the problem that follows:
           - Request A comes In, it needs authentication, a request for an auth token is created and sent
           - Request B comes in while the auth token request is in flight, since B also requires auth, a second request is made
    In this case, we've made two auth token requests. Two problems arise, request A could fail if the server has a only-one-auth-token-per-device policy (the server I'm working with does), also request B is blocked until the second one comes in
Should we build an RxMoyaProvider plugin for authentication and add it to core?

I go back on what I said for documentation, we can improve the docs for Moya, so the only use for an external library would be to be able to work on complicated features together that we'd rather not add to core.
I feel as if adding the `OnlineProvider`, and building a better abstraction for authentication don't belong in core, and if the two of you agree with me, a sub-repo makes sense.

**Comment by ashfurrow** [comment]
I hadn't thought of adding `OnlineProvider` to Moya, I think we should probably open a separate issue to discuss that, separate from Rx/RAC. Can you marshal that? 

The token issue is really interesting, I hadn't thought of that. It'd be nice if we could come up with a way to hold all requests until we're auth'd, maybe through replaying a single auth request. Our servers don't do this, which is probably why it hasn't happened to me yet.

**Comment by AndrewSB** [comment]
Done!

Yup, this is what I wanted: I probably wouldn't have thought of replaying an auth request, I think I was going to store an instance bool `isRequestingAuth` or something. 
Thats why I think something like www.github.com/AndrewSB/Networking is useful, so we can work on these problems together and come up with better solutions.

So I think we should either create an add-on library to work on the common parts of our RxMoya implementations together, or add this stuff to core. I favor the former

**Comment by scottrhoyt** [comment]
Do you guys think we can close this because the relevant discussion is now in #837?

**Comment by AndrewSB** [comment]
Yup! Thanks for staying on this, @scottrhoyt
