### ISSUE TITLE
Getting error in Parameter Encoding after the update to the latest release

### ISSUE THREAD

**Issue by kanishkatn** [Moya/Moya#724]
Hi,

I am getting an error after updating to the latest release. Error message

> ParameterEncoding has no member JSON

My code

``` swift
public var parameterEncoding: Moya.ParameterEncoding {
        switch self {
        case .Search(_):
            println("parameterEncoding for .Search: JSON")
            return .JSON
        default:
            println("default parameterEncoding: URL")
            return .URL
        }
    }
```

I am using  this version of Moya 'Moya', '8.0.0-beta.2'

Please help

**Comment by sunshinejr** [comment]
Hey there @kanishkatn. There was an update for `ParameterEncoding` type in `Alamofire`, so we had to adapt as well. Everything should be clean when you read it [here](https://github.com/Moya/Moya/blob/master/docs/Endpoints.md#from-target-to-endpoint). Basically there is no `enum` anymore, just a protocol that you have to implement. There are also 3 predefined types that you can use:` URLEncoding`, `JSONEncoding`, `PropertyListEncoding`. These you can use by `.default` property, like: `JSONEncoding.default` in your case.

Hope it helps! 👊

**Comment by BasThomas** [comment]
Closing this for now, please reopen if you run into any issues with @sunshinejr's explanation.
