### ISSUE TITLE
Fix intermittent CI

### ISSUE THREAD

**Issue by ashfurrow** [Moya/Moya#725]
The intermittent CI failure fix from https://github.com/Moya/Moya/pull/723 didn't work, so I need to find out why. Also, according to [this comment](https://github.com/Moya/Moya/pull/723#issuecomment-254607549) we should be filing radars about it with details. Moya's in the distinct position of being fully open source, and we should use that to our advantage and provide lots of details for the Apple developers to fix the underlying issue.

**Comment by wongzigii** [comment]
Relevant issues are travis-ci/travis-ci#6422 and travis-ci/travis-ci#6675 and travis-ci/travis-ci#6251. Seems like this is an issue not only in Circle CI, but also Travis CI, which the output of failure is something identical.

**Comment by BasThomas** [comment]
Same failure occurred in #731, it seems.

**Comment by ashfurrow** [comment]
This should be fixed by #734.
