### ISSUE TITLE
RxSwift update to 3.0.0-rc.1

### ISSUE THREAD

**Issue by dylan** [Moya/Moya#726]
The dependency update two-step is an interesting problem, is there a good way to circumvent this? Or do we just need to not update RxSwift because Moya is still requiring an older version?

Thanks!

**Comment by ashfurrow** [comment]
You should be able to use rc 1 of RxSwift, we just haven't had a chance to update the readme yet. Let me know if it works 👍

**Comment by ashfurrow** [comment]
Yikes! I'm not too familiar with how we work with Carthage. Updating our Cartfile might fix the issue, can you send a PR?

**Comment by dylan** [comment]
Using my fork until the PR is merged, it does fix the issue.

**Comment by ashfurrow** [comment]
Should be fixed by #727. But now we need ti move to their final release (I'll do that now).
