### ISSUE TITLE
Parameter with multiple values

### ISSUE THREAD

**Issue by tuyendv2** [Moya/Moya#729]
This api `GET https://www.googleapis.com/blogger/v3/blogs/blogId/pages?status=draft&status=live&key={YOUR_API_KEY}
` from Google Blogger needs two values for status parameter. The statuses could be both `draft` and `live`. I have checked Moya documentation but seems this could not be done with parameters dictionary in the TargetType. Have any of you done the same thing like this before?

**Comment by ashfurrow** [comment]
Great question, we should improve our documentation about this because you're not the first to ask this. 

It's deceptively simple, actually: you need to provide an array of the parameter values. Something like

```swift
return [
    "status": [ "draft", "live" ]
]
```

Let me know if that works 👍

**Comment by tuyendv2** [comment]
I have applied that solution with no luck. Here is the URL in the console: ```https://www.googleapis.com/blogger/v3/blogs/2093381839762195747/comments?fields=items,nextPageToken&status[]=live&status[]=spam```. Don't know why the ```[]``` happen right after the ```status``` parameter. They should not be there.

**Comment by ashfurrow** [comment]
The `[]` is standard HTTP way to send an array of parameters, I'm surprised it's not working. I took a look through the documentation and couldn't find the endpoint you're using. Can you point to that documentation?

It's possible to do exactly as you ask, with duplicate status parameter fields, but you'll need a custom parameter encoder. You can see an example of how to use custom param encodings here: https://github.com/Moya/Moya/blob/master/docs/Examples/ArrayAsRootContainer.md

**Comment by tuyendv2** [comment]
Here is the link to documentation of Google Blogger
[https://developers.google.com/blogger/docs/3.0/reference/comments/list](url)

**Comment by ashfurrow** [comment]
I see, very interesting! A custom parameter encoding looks like your only option. Using one will be very similar to Alamofire custom parameter encoding. I looked at their issues and found a very similar question here: https://github.com/Alamofire/Alamofire/issues/965 I hope that helps, I'm sure you can do it 👍 Once you've figured it out, I'd love to see more documentation in Moya around this, so please consider either posting your solution here or sending a pull request to add it to our docs.

**Comment by BasThomas** [comment]
Hey @tuyendv2, have you ever found a solution for this? Would love to add it to our documentation. :)

**Comment by AndrewSB** [comment]
@tuyendv2 closing this for now, but we'd love to hear back from you! Please re-open this if you found a solution we can add to our docs 😄
