### ISSUE TITLE
moya 8.0 how to requestClosure

### ISSUE THREAD

**Issue by zhaoyunyi** [Moya/Moya#732]
```swift
let requestClosure: MoyaProvider<RequestAPI>.RequestClosure = { endpoint, done in
    let request = endpoint.urlRequest

    
    done(Result<NSURLRequest, Moya.Error>.Success(request))
}
```

error: Generic type Result speciallzed with too many type parameters (got 2, but expected 1)

**Comment by BasThomas** [comment]
The closure is called with a `Result`, which is one type. You are now referring to two (`endpoint` and `done`)

**Comment by garrefa** [comment]
Thanks man
