### ISSUE TITLE
How to retry all requests?

### ISSUE THREAD

**Issue by wenzhaot** [Moya/Moya#740]
In my project, I have a ip list. When I send every request, I need to check which ip can be used, if not, I will try next ip. How to do it?

**Comment by WildDylan** [comment]
Hey, sometimes, write a plug-in class for `validate` ip list and check it before request is better. But if you want do what you mind, just create an array in any `Singleton` that contain all your ips, and then, in your own `TargetType` enum extension, return the `current ip` address from `Singleton` to `baseURL`. Next step, Make a request created with `MoyaProvider `, change the `current ip` in your `Singleton` when get ` .failure(error)`. Loop this step, set a flag when get `.success(Response)`, just for break the loop.

**Comment by BasThomas** [comment]
Does @WildDylan's answer solve your problem, @wenzhaot? Let us know it doesn't :)

**Comment by ashfurrow** [comment]
This should be fixed by #767. I'm going to close, feel free to re-open if the problem persists 👍
