### ISSUE TITLE
Moya 8.0.0-beta.2 support SWIFT 3?

### ISSUE THREAD

**Issue by brijonesie** [Moya/Moya#741]
I received a ton of Swift 3 compile errors in xCode 8 with the latest Moya - 8.0.0-beta.2.  XCode thinks it's an earlier version of swift.  
![screen shot 2016-10-25 at 3 33 07 pm](https://cloud.githubusercontent.com/assets/16111607/19706865/1fac56fa-9ac9-11e6-8ff6-81a98ef47b4e.png)

Here's my podfile:
<img width="414" alt="screen shot 2016-10-25 at 3 39 22 pm" src="https://cloud.githubusercontent.com/assets/16111607/19706882/3a3b205a-9ac9-11e6-99e2-e98567b9bfdd.png">

Here's the xCode error:
![screen shot 2016-10-25 at 3 23 55 pm](https://cloud.githubusercontent.com/assets/16111607/19706889/4367bd46-9ac9-11e6-92ab-3777daa9a478.png)

**Comment by WildDylan** [comment]
support swift 3
```ruby
pod 'Moya', "~>8.0.0-beta.2" 
```
I was used it.

**Comment by marcelofabri** [comment]
What version of CocoaPods are you using? Be sure to use `1.1.0` as it contains some fixes for setting Swift version.

**Comment by brijonesie** [comment]
Thank you marcelfabri and wilddylan.   I updated CocoaPods and I used the podfile syntac that WildDylan suggested and everythings working.   Thank you!.

**Comment by BasThomas** [comment]
Hmm, I've always been using the `~>` syntax with pods, as per [the guides](https://guides.cocoapods.org/using/using-cocoapods.html). Anybody knows the difference? Should we update the README?

**Comment by ashfurrow** [comment]
The `~>` syntax assumes that all versions adhere to semantic versioning, which our betas have not done. So until we release 8.0 I'd recommend to keep the existing readme instructions.

**Comment by WildDylan** [comment]
Examples:

```ruby
pod 'Moya'
```
that means: ignore this framework's version, latest release version.

```ruby
pod 'Moya', '0.9'
```
that means: only get version `0.9` 

```ruby
pod 'Moya', '>0.1'
```
that means: any version bigger than version `0.1` which can be used.

```ruby
pod 'Moya', '>=0.1'
```
that means: any bigger version or equal version which can be used.

```ruby
pod 'Moya', '<0.1'
```
that means: any version less-than version `0.1` which can be used.

```ruby
pod 'Moya', '<=0.1'
```
that means: less-than or equal version `0.1` which can be used.

```ruby
pod 'Moya', '〜>0.1.2'
```
that means: from version `0.1.2` to `0.2`, but not contain version `0.2`, this is a `Range` of version.  >= 0.1.2 and <0.2.0.

and also, you  can use
```ruby
pod 'Moya', :head
```
will get the latest version, but it's `risky`. or get from branch
```ruby
pod 'Moya', :git => 'https://github.com/Moya/Moya.git', :branch => 'dev'
```
and you also can do this:
```ruby
pod 'Moya', :configurations => ['Release', 'App Store']
```
only for appoint `build configuration`.

You also can download `Moya` to local, and use 
```ruby
pod 'Moya', :path => '~/Documents/Moya'
```
Control source code by your self.
