### ISSUE TITLE
Pure IPv6 Support?

### ISSUE THREAD

**Issue by ioveracker** [Moya/Moya#746]
It sounds like Alamofire supports IPv6 with the caveat that reachability-type requests fail over IPv6. Does Moya work correctly over IPv6?

**Comment by ashfurrow** [comment]
We piggyback on Alamofire for networking requests, which you can [configure with a custom manager](https://github.com/Moya/Moya/blob/master/docs/Providers.md#manager), so it _should_ work. Let us know 👍

**Comment by ioveracker** [comment]
I tested using an IPv6 DNS64/NAT64 network as specified in [Apple's documentation](https://developer.apple.com/library/content/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html#//apple_ref/doc/uid/TP40010220-CH213-SW16) and everything seems to work as expected. I didn't have to configure Alamofire with a custom manager or make any other changes.

I'd say Moya is good to go for IPv6.

**Comment by ashfurrow** [comment]
Awesome, thanks! Do you think we should add any documentation about this? Maybe something to the readme?

**Comment by ioveracker** [comment]
It might be nice to know in the readme, but a quick search for IPv6 in the repo on GitHub will reveal this issue, too. 👍
