### ISSUE TITLE
How to stub/mock invalid responses?

### ISSUE THREAD

**Issue by ened** [Moya/Moya#750]
Moya saves a lot of time for me by supporting mocks like this:

```swift
    public var sampleData: Data {
        switch self {
        case .Lookup(let di):
           // return some sample data

```

Love it.

How could I now extend the testing mechanism, in Moya-fashion, to support:

- Empty responses / network timeouts / network errors
- 4xx/5xx responses, which according to the docs: "If the server responds with a 4xx or 5xx error, that will be sent as a ".success"-ful response."
- Empty 200 responses (I think already can do it)

Right now, I'm facing the problem that the App will crash when internet goes away during a long-running request and before devising a fix, I'd like to find a way to mock it.

**Comment by ashfurrow** [comment]
You can use a [custom endpoint mapping](https://github.com/Moya/Moya/blob/master/docs/Endpoints.md#from-target-to-endpoint) to return something other than `.sampleData`, one of [these three cases](https://github.com/Moya/Moya/blob/33d1c7ed5e1baaf927bfff412c9cc52d584d0b3a/Source/Endpoint.swift#L5-L15). That should let you return any data, any status code, and possible even a "network not connected" error. Let me know if that answers your question, and also let us know if we can improve our documentation around this. Thanks!

**Comment by ened** [comment]
@ashfurrow , thank you very much, that solves it for me.

Regarding the documentation, it's actually clear once read carefully. 

My nitpick would be to link the section about `sampleData` (in https://github.com/Moya/Moya/blob/master/docs/Targets.md) to https://github.com/Moya/Moya/blob/master/docs/Endpoints.md#from-target-to-endpoint, and to *highlight* the note about unit tests there for easier readability. 

Moya is super powerful. Thank you all.

**Comment by BasThomas** [comment]
Could you create a PR with the improvements you proposed? No pressure, I could look into doing that as well. 👍

**Comment by ened** [comment]
@BasThomas no time at the moment, still busy in project work. Should be able to help in 1~2 weeks.

**Comment by ashfurrow** [comment]
Not a problem, thanks for the thoughtful question!
