### ISSUE TITLE
Is it possible to define GET & POST parameters for an endpoint

### ISSUE THREAD

**Issue by loryhuz** [Moya/Moya#754]
Is it possible in Moya to have a request having both POST & GET parameters ?
For example, in my current API, GET API parameters are used for expanding the response.

POST: `{{base_url}}/user/authWithFacebook?expand=roles,facebook_friends,devices,accesses`

But I don't see how I can manage these kind of things actually, as if we define the request as POST request, all parameters will be sent as POST parameters.

**Comment by ashfurrow** [comment]
Sounds like a custom parameter encoding is what you're looking for. [Here's an example](https://github.com/Moya/Moya/blob/master/docs/Examples/ArrayAsRootContainer.md) of how you might approach that, please let us know if that approach works 👍

**Comment by ashfurrow** [comment]
@loryhuz Any luck with this?

**Comment by loryhuz** [comment]
@ashfurrow I didn't tested yet because back-end developers of this API made it possible to have expand parameter as POST parameter.

I never used Custom ParameterEncoding, but by reading your example, it's fit perfectly what I needed, I see how I could implement that.

You can close the issue, thanks for the tips !
