### ISSUE TITLE
Revert CI change once Circle is fixed

### ISSUE THREAD

**Issue by ashfurrow** [Moya/Moya#757]
Revert https://github.com/Moya/Moya/pull/753 once Circle has fixed its duplicate simulators issue.

**Comment by pedrovereza** [comment]
Issue in Circle CI: https://discuss.circleci.com/t/multiple-ios-simulators-available-for-single-os-device-configurations/7854

**Comment by pedrovereza** [comment]
It seems like both options deliver the same result, so I'm ok keeping the workaround we have now.

Also got an update from Circle CI folks on that thread:
> We are working on massive changes behind the scenes in order to prevent any of this longterm. This will take a while though so the proper solution to these issues won't be around for a while.
