### ISSUE TITLE
when I use github "Moya/Moya" , it's become  github "Moya/Moya" "3.0.0"  in the file Cartfile.resolved

### ISSUE THREAD

**Issue by Pr-Chen** [Moya/Moya#760]
when I use github "Moya/Moya" , it's become  github "Moya/Moya" "3.0.0"  in the file Cartfile.resolved.why not 8.0.0-beta.4.

**Comment by AndrewSB** [comment]
Can you show us the entire Cartfile that results in that 3.0.0 being resolved? It's possible that theres another dependency you have that depends on Moya@3.0.0

**Comment by ashfurrow** [comment]
@Pr-Chen Any update on this? Would love to figure out the issue.

**Comment by AndrewSB** [comment]
Closing this for now @Pr-Chen. Please come back if you're still running into this 😄

**Comment by BasThomas** [comment]
FYI, this has been resolved in #835 :)
