### ISSUE TITLE
Use of unresolved identifier AnonymousDisposable when installing Moya/RxSwift with CocoaPods

### ISSUE THREAD

**Issue by nikolasburk** [Moya/Moya#763]
I am trying to use Moya's extension for RxSwift, installing it through Cocoapods.

My Podfile looks as follows: 
```ruby

target 'RxMoyaExample' do
  use_frameworks!

  pod 'Moya', '8.0.0-beta.2'
  pod 'Moya/RxSwift'
  pod 'RxSwift'
  pod 'RxCocoa'

end
```

Running `pod install` works fine and fetches all required dependencies. However, once I open the workspace the project won't build anymore. I am getting 2 compiler errors in `Moya+RxSwift.swift` (lines 31 and 57):
`Use of unresolved identifier AnonymousDisposable`.

Any ideas how to fix this? I'm also happy to provide more info about my setup if needed!

**Comment by ashfurrow** [comment]
Hey, great question. Thanks for taking the time to open an issue. The instructions in the readme are outdated, please try Moya 8.0.0-beta.4 and you should be fine. Please let us know 👍

**Comment by nikolasburk** [comment]
Thanks so much for the immediate help, using `pod 'Moya', '8.0.0-beta.4'` indeed fixed the issue! 🙏

**Comment by ashfurrow** [comment]
Wonderful, glad to hear it! Would you be able to open a pull request updating the CocoaPods readme instructions? No worries if not!

**Comment by nikolasburk** [comment]
pretty sure I already did (unless I missed something?!)

<img width="1006" alt="screen shot 2016-11-09 at 22 57 41" src="https://cloud.githubusercontent.com/assets/4058327/20167389/1c991328-a6d0-11e6-8cd6-3180a1aab09b.png">

**Comment by ashfurrow** [comment]
Well well, thank you!

**Comment by crpr** [comment]
I'm having the exact same issue with beta.6

**Comment by sunshinejr** [comment]
This issue should be actually closed already by `probot`, so I'm gonna close it for them.
