### ISSUE TITLE
How to get the URLRequest object from the provider?

### ISSUE THREAD

**Issue by Dharin-shah** [Moya/Moya#765]
I need the request object build by moya for testing purposes.

**Comment by ashfurrow** [comment]
It's not straightforward, but definitely possible. Check out the [Endpoint documentation](https://github.com/Moya/Moya/blob/master/docs/Endpoints.md#request-mapping)'s request mapping section, as well as the [overview of how Moya works](https://github.com/Moya/Moya/tree/master/docs#documentation) for more detail, and let us know how it goes 👍
