### ISSUE TITLE
Moya doesn't take into account the requestRetrier configuration of a session manager

### ISSUE THREAD

**Issue by jeryRazakarison** [Moya/Moya#766]
In the case of the requestRetrier, that is because the requestRetrier delegate method is **only** called when there is an **Alamofire error** in the response. (you can see it here https://github.com/Alamofire/Alamofire/blob/master/Source/SessionDelegate.swift#L434)
When you directly use Alamofire, this error would appear if you call `validate()` on a DataRequest.

BUT when using Moya, you can't call `validate()` on a DataRequest (since it is hidden), and thus Alamofire does not consider there is an error, and the requestRetrier `should` process is not launched.

You can test that your requestRetrier would still work with Moya by calling validate() on the DataRequest here:
https://github.com/Moya/Moya/blob/master/Source/Moya%2BInternal.swift#L187
would be
`let alamoRequest = manager.request(request as URLRequestConvertible).validate()`
Using this **hot fix**, your requestAdapter and requestRetrier work as before (as when you were using Alamofire directly).

But the real improvement would be for Moya to allow us in the switch/case configuration (in the `TargetType` protocol) to pass true or false, if we want or not the Alamofire `validate()` appended.

**Comment by BasThomas** [comment]
Did you mean to make a separate issue for this? (#700)

**Comment by jeryRazakarison** [comment]
I thought it was a good idea, because the first author of issue #700 spoke about cache policy problems specifically.
The `requestRetrier` issue was introduced later by _DanteCore_, but his question and my answer (and PR) don't help the initial author.

**Comment by BasThomas** [comment]
Cool, makes sense!

**Comment by ashfurrow** [comment]
Fixed by #767.
