### ISSUE TITLE
Manual install instructions?

### ISSUE THREAD

**Issue by jaymutzafi** [Moya/Moya#780]
Any chance for instructions on how to add Moya to a project manually? I would love the fully spelled out idiot/newbie version if you don't mind? 

Thanks in advance.

**Comment by BasThomas** [comment]
Due to the dependencies not being included in this repository, I am not sure if this is possible at this moment. Do we want to support this, @ashfurrow?

**Comment by ashfurrow** [comment]
It's never really come up. It'd be pretty tricky to do, since we have a lot of source code hacks to support either CocoaPods _or_ Carthage. I'm not opposed to adding this, but I think linking to a blog post describing (in general) how to install CocoaPods or Carthage libraries without using those tools would probably be the best solution. Thoughts?

**Comment by BasThomas** [comment]
Some more in-depth CocoaPods / Carthage installation guidance would be nice, yeah.

**Comment by jaymutzafi** [comment]
I know this is not the place to complain about this but it is exactly the difficulty with installing and/or using CocoaPods/Carthage themselves that got me asking about manual install (Moya specifically is was not the problem). But it sounds like this is not viable option as it stands unfortunately.

**Comment by AndrewSB** [comment]
@jaymutzafi it is unfortunate that the current package manager landscape on iOS is that unapproachable to new developers 😕.

@ashfurrow I think we've removed most of our hacks to support Cocoapods & Carthage, so it shouldn't be *too* hard to integrate manually (famous last words 😛)
@ashfurrow is right though, a blog post describing how to do this in general would be better, and more sustainable in the long run, but I can't find one as of now. So I'll just try to help you out here 😄 

For a manual integration, all you (should) need to do is drag the source files inside https://github.com/Moya/Moya/tree/master/Source into your xcodeproj. You might want to not drag in the `RxSwift` and `ReactiveSwift` directories, unless you're using those packages in conjunction with Moya.

I haven't tested this, so I may be wrong. Let us know if you have any issues, we'll try our best to get you working with Moya 😄

**Comment by BasThomas** [comment]
I think you're missing out on all Alamofire code in that case, which would mean that doesn't work? I think you'd have to manually copy Alamofire's code as well.

**Comment by AndrewSB** [comment]
Oh yup, you're right @BasThomas. Thanks for catching that 💯

@jaymutzafi you'd also need to include Alamofire in your project, they have manual integration instructions here: https://github.com/Alamofire/Alamofire#manually

**Comment by BasThomas** [comment]
Hmm, and it seems like we need to add `Result` as well.

... and then it still doesn't work. Removed all `import Result`s, then Xcode started complaining about all `Moya.`-files, which makes sense. Seems like we're going to have a little more work to make this possible.

<img width="1512" alt="screen shot 2016-12-08 at 22 31 46" src="https://cloud.githubusercontent.com/assets/4190298/21028633/5d78c2da-bd96-11e6-9d54-490fb5feb826.png">

**Comment by BasThomas** [comment]
It seems like Alamofire's approach (git submodule) might work (?).

**Comment by BasThomas** [comment]
Woo, got it working using `git submodules`. Let me add a how-to to the readme. :)

**Comment by AndrewSB** [comment]
Thanks for rolling with this @BasThomas!
