### ISSUE TITLE
 Moya can support iOS8?

### ISSUE THREAD

**Issue by happybobo** [Moya/Moya#782]
Alamofie 4.1.0 has Updated the iOS Example app deployment target to iOS 8.0; Why Moya does not support iOS8？

**Comment by BasThomas** [comment]
Take a look at #639.

**Comment by happybobo** [comment]
https://github.com/Moya/Moya/pull/608#issuecomment-247292895 @sunshinejr had said ` Because both Alamofire and RxSwift have iOS 9.0 as a minimum deployment target.`, But now Alamofire and RxSwift Support iOS 8.0 again; iOS 8 is still 9% of the market share!

**Comment by BasThomas** [comment]
Cool! What do you think, @ashfurrow? Seems like we can lower it again.

**Comment by ashfurrow** [comment]
Let's do it, I never really liked removing iOS 8 support anyway but we had to because of Alamofire. If they're lowering it, let's do it 👍

**Comment by happybobo** [comment]
👍So cool!!!  You are so great!  Cheers!

**Comment by BasThomas** [comment]
Let's keep this open to make sure we won't forget. :)

**Comment by wangguangfeng** [comment]
COOL
