### ISSUE TITLE
Paging with the @odata.nextLink value

### ISSUE THREAD

**Issue by dianambb** [Moya/Moya#785]
There was a [similar issue](https://github.com/Moya/Moya/issues/334) on this by it does not answer my question.

OData protocol can return the 'nextLink' for multipage responses. [Here](http://www.odata.org/getting-started/basic-tutorial/) is the documentation for it.

Ideally I think it should be handled with the request. Keep sending the next request until nextLink is nil.
The solution below works but is the right thing to do?

```swift
private let provider = RxMoyaProvider<T>(endpointClosure: ApiUtility.getEndpointClosure())

    func requestPaged<E: Mappable>(_ token: T, withEntity: String) -> Observable<[E]> {
        var items:[E] = []
        
        return requestHelper(token, withEntity:withEntity, scheduler: QueueConstants.ReadQueue())
        .mapObject(PagedResponse<E>.self)
            .flatMap { pagedResponse -> Observable<[E]> in
                items += pagedResponse.items
                
                guard let nextLink = pagedResponse.nextLink else {
                    self.provider = RxMoyaProvider<T>(endpointClosure: ApiUtility.getEndpointClosure(url: nil))
                    return Observable.of(items)
                }
                
                self.provider = RxMoyaProvider<T>(endpointClosure: ApiUtility.getEndpointClosure(url: nextLink))
                return self.requestPaged(token, withEntity: withEntity)
        }
    }
```

**Comment by BasThomas** [comment]
So you want to fetch multiple "pages" at once? Most of the time, paging in an API is added to prevent sending too much information at once. I think what you would be trying to do is something that might not be the ideal solution.

That being said, I think "chaining" the requests like you are doing here should be a solution that works just fine.
