### ISSUE TITLE
Having to migrate over to swift 3. What exactly is task? 

### ISSUE THREAD

**Issue by rlam3** [Moya/Moya#788]
What exactly is this used for?
```swift
  var task: Task {
        switch self {
            case .zen, .showUser, .createUser, .showAccounts:
                return .request
        }
    }
```

**Comment by BasThomas** [comment]
The documentation on this has been updated: https://github.com/Moya/Moya/blob/master/docs/Targets.md. Does that answer you question?

**Comment by pedrovereza** [comment]
Hey @rlam3, was the documentation helpful? Do you still have questions regarding the use of `Task`?

**Comment by rlam3** [comment]
Thanks! This was helpful. But I guess most requests should by default be .request right?

**Comment by BasThomas** [comment]
Yep, most endpoints probably use `.request`.

**Comment by rlam3** [comment]
@BasThomas Thanks!
