### ISSUE TITLE
Document release process

### ISSUE THREAD

**Issue by ashfurrow** [Moya/Moya#792]
We release using a [rake task](https://github.com/Moya/Moya/blob/b0fe5de3e4cfefa20d1dd8c26ccfa8bb0ba4184e/Rakefile#L135) that's invoked using `rake release["VERSION"]`. But there are some dependencies, like having bundler installed, running a `bundle install`, and using a `netrc` file to authenticate with GitHub. 

@AvdLee Let me know what troubles you run into.

**Comment by AvdLee** [comment]
So in this case I was releasing `8.0.0-beta.5` using the `rake release` method.

Everything went fine, I only had to do a `bundle install` as noted before I could use the `rake` method. 

The podspec however didn't update automatically, so the `pod trunk push` noted a duplicate entry of `beta 4`. Furthermore, I encountered an error with the beta release of `ReactiveSwift`, so the podspec didn't validate as well.

After updating the podspec manually I was able to create a new pod release, but it would be great if the rake file does a bump here as well. Not sure if this is possible with beta versioning?

**Comment by ashfurrow** [comment]
Interesting, the Rakefile _should_ do that [here](https://github.com/Moya/Moya/blob/b0fe5de3e4cfefa20d1dd8c26ccfa8bb0ba4184e/Rakefile#L141-L145) but the regex won't work if the existing podspec is a prerelease (it looks for `"X.Y.Z"` and misses `"X.Y.Z-beta.a"`). 

I'll take a shot at a PR adding documentation steps to release, unless you beat me to it :wink:

**Comment by BasThomas** [comment]
The [Changelog](https://github.com/Moya/Moya/blob/master/Changelog.md) seems to not be completely correct right now either. I see beta 5 duplicated.

**Comment by pedrovereza** [comment]
@ashfurrow It seems that we only got a tag created, I think we should make a release out of it:
![image](https://cloud.githubusercontent.com/assets/1916041/20718051/ad265f54-b63e-11e6-95e0-70e7a2e9cc91.png)

**Comment by ashfurrow** [comment]
Sounds good 👍 That can sometimes happen when the script fails near the end. Can you take care of that?

**Comment by pedrovereza** [comment]
Sure, will do :wink:

**Comment by BasThomas** [comment]
Updated the previous releases to include the changes from `Changelog.md` as well. 👍

**Comment by pedrovereza** [comment]
I think [this](https://github.com/Moya/Moya/blob/b0fe5de3e4cfefa20d1dd8c26ccfa8bb0ba4184e/Rakefile#L174) should be adding the changelog 🤔

**Comment by ashfurrow** [comment]
Correct.

**Comment by BasThomas** [comment]
All betas from 8.0.0-beta.1 through 4 didn't include these, and I added them manually when I noticed yesterday. 🤔

**Comment by pedrovereza** [comment]
Created #811 to keep track of it.

**Comment by AvdLee** [comment]
I just did a release for beta 6, to update the podspec for ReactiveSwift beta 4. However, a new error occurred:

```
Validating podspec
 -> Moya (8.0.0-beta.5)
    - ERROR | [Moya/ReactiveSwift] file patterns: The `source_files` pattern did not match any file.

[!] The spec did not pass validation, due to 1 error.
```

Currently busy fixing this issue.

**Comment by pedrovereza** [comment]
I was able to release `8.0.1` following the docs and #941 solves the version format. 👊
