### ISSUE TITLE
Returning new Signal not working

### ISSUE THREAD

**Issue by tspecht** [Moya/Moya#793]
Hey guys!

I just recently started using Moya in conjunction with ReactiveSwift and am currently struggeling with building a small API wrapper for my service to encapsulate some more logic under the hood involving CoreData.

I'm currently using the following:
```swift
class APIProvider {
    static let provider = ReactiveCocoaMoyaProvider<MyService>()
    
    static func login(token: String) -> Signal<Response, Moya.Error> {
        return Signal { sink in
            provider.request(token: .login(token: token)).filterSuccessfulStatusCodes().start { event in
                switch event {
                case let .failed(error):
                    sink.send(error: error)
                case let .value(response):
                    // Process the response here, write to CoreData
                    sink.send(value: response)
                default:
                    //TODO: manage error here
                    break
                }
            }
        }
    }
}
```

I'm then calling this function from my view controller like this:
`_ = APIProvider.login(token: mySecretToken)`

However it seems like the request is only successfully being processed if I add an additional 
`.observe { _ in }` to the end of the call in my view controller ...

I attached the NetworkLogger as a plugin and get the following output:
```
[["Moya_Logger: [26/11/2016 14:52:54] Response: Received empty network response for login(....
```

I'm aware that I clearly didn't get something about the whole Signal and SignalProducer thing. Does someone have an idea how I could resolve this issue or what general best practices are for use with Moya?

Thanks!

**Comment by pedrovereza** [comment]
Hey @tspecht I'm not too familiar with ReactiveSwift, but this is on [our docs](https://github.com/Moya/Moya/blob/master/docs/ReactiveSwift.md):

> For ReactiveSwiftMoyaProvider, the network request is not started until the signal is subscribed to.

Also, from [ReactiveSwift docs](https://github.com/ReactiveCocoa/ReactiveSwift/blob/master/Documentation/FrameworkOverview.md#signal-producers):
> [SignalProducer] Unlike a plain signal, no work is started (and thus no events are generated) until an observer is attached

Feels like this could explain the problem you're facing. 

But I think @ashfurrow may have a better answer 😉

**Comment by justinmakaila** [comment]
@tspecht You should just return the `SignalProducer` from your provider from your `login(_:)` method, and change the signature to `login(token: String) -> SignalProducer<Response, Moya.Error>`.

What you should have is this:
```
class APIProvider {
    static let provider = ReactiveCocoaMoyaProvider<MyService>()
    
    static func login(token: String) -> Signal<Response, Moya.Error> {
        return provider.request(token: .login(token: token))
            .filterSuccessfulStatusCodes()
    }
}
```
All that does is creates a `SignalProducer`, or "unit of work" when you call `APIProvider.login("someToken")`. That unit of work still needs a subscriber before it will be invoked. In your view controller, you're going to want to do something like:

```
APIProvider.login("someToken").startWithValues { response in
    /// Update the UI with the response.
}
```
If you want the response to be transformed into some new value, you'll have to write extensions on the `SignalProducerProtocol`, i.e.:
```
extension SignalProducerProtocol where Value == Moya.Response, Error == Moya.Error {
  func mapLoginResponse() -> SignalProducer<NewValue, Error> {
    return producer
      .map { response -> NewValue in
        /// Transform response to `NewValue` and return the transformed value
      }
  }
}
```
Which will slightly modify your login producer to look like...
```
    static func login(token: String) -> Signal<NewValue, Moya.Error> {
        return provider.request(token: .login(token: token))
            .filterSuccessfulStatusCodes()
            .mapLoginResponse()
    }
```

**Comment by BasThomas** [comment]
@tspecht, have you been able to solve your issue with the answers given? Let us know if you have any more questions!

**Comment by justinmakaila** [comment]
@BasThomas I'm just going to go ahead and close this.

@tspecht, Please re-open if your issue persists.

**Comment by zhaoyunyi** [comment]
how to slove the empty network ?
