### ISSUE TITLE
Make provider to wait an endpoint to get done

### ISSUE THREAD

**Issue by mrfarukturgut** [Moya/Moya#794]
Hi, 

I am using Moya to handle HTTP operations and normally I have an `refreshToken()`. I am checking token if expired or not when a request is about happen but the problem is there can be a scenarios that more than one requests. If they are chained with nested types it is not a problem however, it is not likely all the time. 

To be more clear lets say I have `request1()` and `request2()` and assume that they execute separate operations and can be triggered anytime(for instance one is called in a `viewDidLoad()`, other one is called in another `viewDidLoad()`). when this happens and if the token is expired, my refresh request fails. (`statusCode: 400`) So, my question is, how can I make provider to wait `refresh()` operation get done?I mean by provider is other endpoints. I want them to wait `refresh()` endpoint if it is on.

I will be very appreciated if you suggest a way that will make this easier.

**Comment by AndrewSB** [comment]
Ooooh @mrfarukturgut, that's a doozie of a synchronization problem. I, personally, like to model problems with reative programming. Abstracting multiple, potentially concurrent `Request`s that require a common resource (an auth token in this case) as streams allow me to stay sane, and reason about the state of program at any point in time.

I recently had a long conversation with @rlam3 in https://github.com/Moya/Moya/issues/748 where we talked about a similar problem, why don't you give that a read, and then let us know how we can help once you're aware of the Rx/Reactive Moya solution to your problem

**Comment by mrfarukturgut** [comment]
@AndrewSB Hi, sorry for the really really late response. I just had to focus on the school, so I suspended the project. As the school is over for now, I just started work on my project. 

I examined your answer and the reference, but I am not feeling safe with the idea of using RxSwift right now. Because I do not have experience with it and it will cost me more time. I just used `GCD` in seperate function which is responsible for refreshing token so, it seems OK for now. 

But for further work about the service you are providing, I really want to see a feature that handles this kind of operations by itself. And as a user of `Moya` I want to help as much as I can. 

Thanks!

**Comment by AndrewSB** [comment]
sounds good @mrfarukturgut! Let me know if theres anything else we can help with 😄 

GCD is a perfectly fine alternative as well

**Comment by mrfarukturgut** [comment]
Just one question for now @AndrewSB . I know it is not preferred but it there a way to make all the requests made with Moya synchronous.

**Comment by AndrewSB** [comment]
you could use a dispatch group to turn the callback into something that blocks the thread. I wouldn't recommend it, but it is doable

**Comment by sandeepbol** [comment]
@mrfarukturgut I might be late to the party but you do not need to make all your request synchronous. As @AndrewSB pointed out though doable, its not recommended. You should actually make one of the refresh token calls asynchronous by making use of Dispatchqueue and DispatchGroup.wait() as suggested in this [SO answer](https://stackoverflow.com/a/43404478/7271020).
