### ISSUE TITLE
Cartfile dependence version should update.

### ISSUE THREAD

**Issue by ufosky** [Moya/Moya#795]
Update the version to support ios 8.0.

**Comment by BasThomas** [comment]
Yep, true! @AndrewSB, have you had time to take a look at this?
Otherwise, @ufosky, a PR to update the dependencies would be really appreciated!

**Comment by AndrewSB** [comment]
@BasThomas I haven't really been on my computer this weekend, I can make a PR towards the middle of the week, but Im available to look over a PR today!

**Comment by BasThomas** [comment]
I've created #797. :)
