### ISSUE TITLE
Add a Danger rule to check for (simultaneous) changes in CocoaPods / Carthage files

### ISSUE THREAD

**Issue by BasThomas** [Moya/Moya#796]
See #787 / https://github.com/Moya/Moya/pull/787#issuecomment-262627697

**Comment by pedrovereza** [comment]
Should we make the verification for `Moya.podspec` and the `Podfile` and `Podfile.lock` files inside Demo?

I feel we should only verify `Moya.podspec` but I may be missing something 😅

**Comment by BasThomas** [comment]
You are right. :)
