### ISSUE TITLE
How to use it in iOS 8

### ISSUE THREAD

**Issue by GTMYang** [Moya/Moya#798]

**Comment by BasThomas** [comment]
What is your question exactly? What doesn't work? If using CocoaPods, please post your `Podfile`. :)

**Comment by GTMYang** [comment]
I use Swift3, and need to support iOS8.0

**Comment by BasThomas** [comment]
We support iOS 8 in `beta.4` and `beta5.` :)

**Comment by GTMYang** [comment]
Thanks!
