### ISSUE TITLE
How do we handle parameter encodings now in swift 3? 

### ISSUE THREAD

**Issue by rlam3** [Moya/Moya#801]
Migrating from Swift 2 to swift 3 produced breaking changes in moya. 

How do we handle parameter encodings now in swift 3? 

It used to be a switch case sort of away to handle them... is this still present? 

Thanks!

**Comment by sunshinejr** [comment]
Hey @rlam3. We have updated our documentation around the new `ParameterEncoding` type from `Alamofire`, please check it [here](https://github.com/Moya/Moya/blob/master/docs/Endpoints.md#from-target-to-endpoint). Hope it helps! 

Also, whenever you feel like something isn't clear enough, please let us know so we can improve the docs. 👊

**Comment by rlam3** [comment]
@sunshinejr 

Is the following way not the accepted way to initialize the endpoint anymore? 

```swift
        let endpoint: Endpoint<API> = Endpoint<API>(
            URL: target.baseURL.appendingPathComponent(target.path).absoluteString,
            sampleResponseClosure: {.networkResponse(200, target.sampleData)},
            method: target.method,
            parameters: target.parameters,
            parameterEncoding: target.parameterEncoding
        )
        
```

**Comment by BasThomas** [comment]
The `URL` parameter should be `url`.

**Comment by BasThomas** [comment]
^ I've updated the documentation to reflect that in #806. Sorry!

**Comment by sunshinejr** [comment]
@rlam3 it is, it was probably the `URL` renaming to `url` as @BasThomas mentioned. Can you try if it works?

**Comment by AndrewSB** [comment]
@rlam3 it looks like @BasThomas' change should have fixed what you were seeing, please do re-open this if it didn't!

Closing for now 😄
