### ISSUE TITLE
What is the proper way to set up unit testing with quick/nimble for moya?

### ISSUE THREAD

**Issue by rlam3** [Moya/Moya#803]
What is the proper way to set up unit testing with quick/nimble for moya?

I've been looking for tutorials and documentation on this matter but have not found anything in this repository. 

Would love to see more documentation on this matter if possible. Thanks!

**Comment by sunshinejr** [comment]
Hey there @rlam3. You could look up Artsy's [eidolon](https://github.com/artsy/eidolon/tree/master/KioskTests), they are using Quick/Nimble with Moya.

**Comment by BasThomas** [comment]
And so is [Moya itself](https://github.com/Moya/Moya/tree/master/Demo/Tests). :-)

**Comment by rlam3** [comment]
@sunshinejr Thanks! I took a look at this previously. 

But I'm still a bit confused... For example... I see the XAuth.json and I see .XAuth in API enum but I only see 1 test being done in APISpec... 

I don't see it being tested for authentication.... Or maybe I'm looking at the wrong place?

**Comment by AndrewSB** [comment]
@rlam3 are you interested in testing Moya specifically for authentication?
