### ISSUE TITLE
JSON response shown in some other form when using custom transformations

### ISSUE THREAD

**Issue by Dharin-shah** [Moya/Moya#816]
Heres what i am using
```swift
open class LfArrayStringTransform : TransformType {
    public typealias Object = String
    public typealias JSON = [[String]]
    
    public init() {}
    
    open func transformFromJSON(_ value : Any?) -> String?{
    /* This Prints
Optional({
    email =     (
        "The email has already been taken."
    );
    "mobile_number" =     (
        "The mobile number has already been taken."
    );
})
*/   
 print(value)

        do{
            let jsonData = try JSONSerialization.data(withJSONObject: value, options: []) as? [AnyHashable : Any]
            print(jsonData) // this is nil
        }catch{
        }
/*Goes in there (obvious it was , silly me)*/
        if let someValue = value as? Any{
            
        }
        /* Not Going in Here */
        if let arrayValue = value as? [[String]]{
            return arrayValue.flatMap({ (value) -> String in
               return value.joined(separator: ", ")
            }).joined(separator: ", ")
        }
        return nil
    }
    
    open func transformToJSON(_ value: String?) -> [[String]]? {
        return nil
    }
}
```

I want to transform the json data that i am receiving myself. But the object that i am receiving or which is printed does not have a standard structure. 
Am I missing something here?

**Comment by Dharin-shah** [comment]
Hey @ashfurrow do you mind helping me out on this?

**Comment by BasThomas** [comment]
What do you mean with "standard structure"? That the email and mobile number might not be returned in that order?

**Comment by Dharin-shah** [comment]
Nope, That I cannot parse it since it does not seem like json to me

**Comment by Dharin-shah** [comment]
```
errors : {
  "message": "422 Unprocessable Entity",
  "errors": {
    "otp_code": [
      "The selected otp code is invalid."
    ]
  }
```

This is what i get in Postman

**Comment by BasThomas** [comment]
What is not JSON? What do you get back from the request in your app?

**Comment by Dharin-shah** [comment]
As I have commented out before that the value I get while transformation prints something like this

```
Optional({
    email =     (
        "The email has already been taken."
    );
    "mobile_number" =     (
        "The mobile number has already been taken."
    );
})
```

```

open class LfArrayStringTransform : TransformType {
    public typealias Object = String
    public typealias JSON = [[String]]
    
    public init() {}
    
    open func transformFromJSON(_ value : Any?) -> String?{
    /* This Prints
Optional({
    email =     (
        "The email has already been taken."
    );
    "mobile_number" =     (
        "The mobile number has already been taken."
    );
})
*/   
 print(value)

        do{
            let jsonData = try JSONSerialization.data(withJSONObject: value, options: []) as? [AnyHashable : Any]
            print(jsonData) // this is nil
        }catch{
        }
/*Goes in there (obvious it was , silly me)*/
        if let someValue = value as? Any{
            
        }
        /* Not Going in Here */
        if let arrayValue = value as? [[String]]{
            return arrayValue.flatMap({ (value) -> String in
               return value.joined(separator: ", ")
            }).joined(separator: ", ")
        }
        return nil
    }
    
    open func transformToJSON(_ value: String?) -> [[String]]? {
        return nil
    }
}

```

**Comment by BasThomas** [comment]
So, doing the same request, gives you the following JSON in Postman:

```json
{
  "message": "422 Unprocessable Entity",
  "errors": {
    "otp_code": [
      "The selected otp code is invalid."
    ]
}
```

and

```
{
    email =     (
        "The email has already been taken."
    );
    "mobile_number" =     (
        "The mobile number has already been taken."
    );
}
```

in Swift? Am I understanding this correctly?

**Comment by Dharin-shah** [comment]
Yup. After doing custom transformation, as i wrote down above. The value I am getting in the parameter i.e. of **Any?** type prints this. So how do i transform this value into a dictionary or json. JSONSerialization fails

**Comment by BasThomas** [comment]
Hmm, it doesn't seem like JSONSerialization is failing.

```swift
do{
    let jsonData = try JSONSerialization.data(withJSONObject: value, options: []) as? [AnyHashable : Any]
    print(jsonData) // this is nil
} catch {
}
```

If the jsonData here is `nil`, the casting fails, not the conversion from `value` to `data`. You are trying to cast `Data` to `[AnyHashable: Any]` here, which probably fails.

**Comment by BasThomas** [comment]
The way your JSON is printed might be confusing, but seems to not be the issue here.

**Comment by Dharin-shah** [comment]
```
{
  "message": "422 Unprocessable Entity",
  "errors": {
    "email": [
      "The email has already been taken."
    ],
    "mobile_number" : [
   "The mobile number has already been taken."
]
}
```
This is the actual value for the request in postman. (The same request I am doing in my app ) Just go for the semantics here.

**Comment by Dharin-shah** [comment]
True but then considering the actual json, it shouldnt fail, should it?

**Comment by BasThomas** [comment]
The casting does fail, as `Data` can't be cast to `[AnyHashable: Any]`.

I've made a gist, does that clarify? https://gist.github.com/BasThomas/0f894d610f7f24732077fa961a6fc182

**Comment by Dharin-shah** [comment]
Yeah I just tried that and it indeed failed.

**Comment by BasThomas** [comment]
So, does that solve the issue for you? :)

**Comment by Dharin-shah** [comment]
So do i have to convert the string json first into data??
Because i did that as well
```
open func transformFromJSON(_ value : Any?) -> String?{
        print(String(describing: value))
        let stringData = String(data: value as! Data, encoding: String.Encoding.utf8)
        print(stringData)
return nil
    }
```

But it gives me runtime exception

**Comment by BasThomas** [comment]
I am going to close this issue as it is not related to Moya.

The problem again is casting. You are trying to cast `Any` to `Data` here, which is not possible.
What you can do to solve this is the following:

1. Create `Data` from your `Any` response with the `JSONSerialization(withJSONObject:) function`.
2. Create a `JSONObject` / `[AnyHashable: Any]` by using `JSONSerialization(withData:)` on the data you just received.

**Comment by Dharin-shah** [comment]
Hey @BasThomas  Thanks a lot, I did all of that you said before And I realised a lot later the problem is not with Moya so I apologise for that.
BTW I solved it by casting it to a dictionary [AnyHashable : Any] directly.
Thank you so much for your time. Much Appreciated.
