### ISSUE TITLE
Discuss: Use a single target for all platforms?

### ISSUE THREAD

**Issue by AndrewSB** [Moya/Moya#818]
Hey all! I was reading https://blog.pusher.com/what-i-learned-building-the-pusherswift-framework/, and one of the first things the author goes into is how the framework they built uses only one target for all platforms. 

Currently Moya has 4 targets for each 3 of our frameworks (12 total), and then 3 for tests.
<img width="175" alt="screen shot 2016-12-01 at 2 39 57 pm" src="https://cloud.githubusercontent.com/assets/3814772/20815764/11cd4af8-b7d4-11e6-9d3c-7a1d801ddc48.png">

I'm not sure how the author was able to make a universal target, but maybe we could do something similar?

**Comment by petester42** [comment]
I know how. I've done it for other projects. It's fairly simple. There are couple things not really mentioned but this article covers mostly how to do this http://promisekit.org/news/2016/08/Multiplatform-Single-Scheme-Xcode-Projects/.

**Comment by AndrewSB** [comment]
@petester42 that looks really cool, it would be awesome to have Moya vend through one target as well.
I could take a shot in a PR, but since you've done this before it may be easier for you to do it? Let me know what you think.

**Comment by petester42** [comment]
Ya sure I could do it. I was creating a script that would automatically do this but I haven't finished it. I could do it manually, it wouldn't take too long.

**Comment by AndrewSB** [comment]
💯

A script that would do this automatically for any project?

**Comment by BasThomas** [comment]
That... that'd be awesome 😱

**Comment by aaroncrespo** [comment]
How would this work with bundleID collisions with say a watchOS extension.

**Comment by petester42** [comment]
This more for frameworks than actual applications. It's not really useful for application targets

**Comment by aaroncrespo** [comment]
frameworks still have bundleID's though.

**Comment by AndrewSB** [comment]
@aaroncrespo can you give a concrete example? 
I think the issue with bundle ID collisions disappears when you have one universal target, since there is only one target - it can't collide with something that no longer exist.

*sorry if I misunderstood your comment* 😅

**Comment by aaroncrespo** [comment]
It's more a question maybe we weren't loading/linking the framework correctly across watch/extension/app.

**Comment by petester42** [comment]
I have no idea about watchOS stuff.

**Comment by AndrewSB** [comment]
@petester42 I think we should go ahead with this, and fix watchOS issues if/when they come up. When you create a PR, can you close this issue?

Thanks 😄

**Comment by AndrewSB** [comment]
@scottrhoyt @BasThomas @pedrovereza: Along the lines of simplifying the project structure in #885, I think it would be really awesome to have this implemented too.

Especially if we can have it in before the 8.0.0 release.

**Comment by BasThomas** [comment]
Hmm, would this be a breaking change? I agree this would definitely be nice, but I am not so sure if we need it before releasing 8.0.0.

**Comment by scottrhoyt** [comment]
I don't think it would be a breaking change.

**Comment by AndrewSB** [comment]
Oh, you guys are right. It would have 0 effect on the API, it was just related to the new project structure we had

**Comment by AndrewSB** [comment]
Implemented in #967 😆
