### ISSUE TITLE
Discuss: rationale on circle ci v/ travis?

### ISSUE THREAD

**Issue by AndrewSB** [Moya/Moya#821]
I know we've been switching back and forth on Travis and CircleCI, can someone knowledgeable point me to the discussion(s) on why we were switching, and why we're currently on circle?

**Comment by BasThomas** [comment]
I have setup CI for a personal project a while back, and it turned out that CircleCI is a paid CI for iOS / macOS / etc. builds. Or at least, that is what it looked like. Switched to Travis after. Not sure about the reasoning though.

**Comment by AndrewSB** [comment]
I thought that as well, but it turns out you just need to email them (I did, they responded within half an hour) 

<img width="445" alt="screen shot 2016-12-02 at 2 01 13 pm" src="https://cloud.githubusercontent.com/assets/3814772/20851917/f1e52c00-b897-11e6-99da-2bd06b3a6337.png">

**Comment by ashfurrow** [comment]
Yup, they're pretty great. I can't remember why we switched to Circle most recently, but in general I like them better for macOS builds right now: builds start in a few seconds where Travis often has a delay of 45 minutes or more just for a container to become available. I'm not knocking Travis, they're both great providers supplying a valuable service to the OSS community, but Circle suites us better right now.

**Comment by AndrewSB** [comment]
Thanks @ashfurrow, that makes sense!
