### ISSUE TITLE
Rename functions to conform to the Swift 3 guidelines

### ISSUE THREAD

**Issue by BasThomas** [Moya/Moya#822]
Some functions haven't yet been (correctly) renamed for Swift 3, according to [this comment](https://github.com/Moya/Moya/pull/813#issue-192764406). It would be really nice if we could snug this into `8.0.0` still, to prevent future breaking changes.

@Moya/contributors, all help is appreciated!

**Comment by ashfurrow** [comment]
Sounds good, we're still in a holding pattern until the ReactiveSwift release so this seems like a good idea to get into 8.

**Comment by pedrovereza** [comment]
Opened #824 as a start 😉

**Comment by BasThomas** [comment]
Closing this as all this work has been done in #824 and #825 (and these have both been merged) 👍
