### ISSUE TITLE
How to change baseURL at runtime?

### ISSUE THREAD

**Issue by piqiu21** [Moya/Moya#836]
Hi,

I have a project where URL for a server is not known during compile time, only first server in chain is known, other servers URLs are given as a response from the first one. Also every server has its alternative URL in case of failure, so they must be switched on demand.

Here is how I tried to solve this, my provider:
```swift    
private lazy var provider: RxMoyaProvider<DataRequests> = {
        return RxMoyaProvider<DataRequests>(endpointClosure: {(target: DataRequests) -> Endpoint<DataRequests> in
            let server = URL(string: self.currentServer == .primary ? self.server.primary : self.server.secondary)!
            let url = server.appendingPathComponent(target.path).absoluteString
            return Endpoint(url: url, sampleResponseClosure: {.networkResponse(200, target.sampleData)}, method: target.method, parameters: target.parameters)
        }, manager: self.connectionManager)
    }()
```
and here is my request:
```swift
    public func dataModel() -> Observable<VeraDataModel>{
        return requestDataModel()
            .catchError{_ in
                self.currentServer = self.currentServer.changeActiveServer()    //change server and try again
                return self.requestDataModel()
        }
    }
    
    private func requestDataModel() -> Observable<VeraDataModel>{
        return self.provider
            .request(DataRequests.dataModel)
            .debug()
            .mapObject(VeraDataModel.self)
    }
``` 
So first requirement is solved by creating a new class instance (containing code I mentioned) every time I got an information about new server. 

The second one is more tricky. As far sa I understand Rx (and its async nature) since this line:
```swift
self.currentServer = self.currentServer.changeActiveServer()    //change server and try again
```
is introducing side effects it will be a problem when multiple dataModel() calls will occur (race condition)

Does anybody have simmilar problems?

**Comment by scottrhoyt** [comment]
There are a couple of things to unpack here. First of all, currently Moya's support for executing simple requests against a single `URL` is pretty light. There are some new features suggested in #861 that would make this easier, but we are still deciding whether or not they agree with Moya's philosophy. If you want to include this in your own code, I'd suggest looking at how `SingleURLTarget` is implemented and possibly include that in your code.

Without a `SingleURLTarget`, I would recommend using Alamofire instead for the dynamic `URL` requests.

The second part is writing a `TargetType` that can accept multiple `baseURL`s and cycle between them. For this I'm inclined to suggest that you create a new `TargetType` that isn't an `enum` (possibly an extended version of `SingleURLTarget`). You can even embed a separate `enum` into this structure to retain some of the `switch` semantics that Moya promotes. You will also want to subclass `MoyaProvider` to contain the state you need (e.g. the index of the `baseURL` to try). You may also want to change the behavior of it's `request` method to emit an error (from `catchError`) when the `baseURL`s have been exhausted.

Beyond that, you should just be able to string the requests together with `RxSwift` similarly to your example. Let me know if that gets you going in the right direction or if you have any other questions!

**Comment by scottrhoyt** [comment]
Since there hasn't been any activity on this thread for some time, I am going to go ahead and close it. Please re-open or create a new issue if you would like to discuss further. Thanks.
