### ISSUE TITLE
如何取消请求

### ISSUE THREAD

**Issue by lxkbest** [Moya/Moya#839]
请问如何在控制器deinit时取消 当前控制器的所有请求

**Comment by lxkbest** [comment]
发现在离开控制器之后 数据才返回，这时 self = nil 所有想问问deinit 是否有取消的方法？

**Comment by lxkbest** [comment]
How do I cancel the current controller in controller deinit all requests

**Comment by xiangyu-sun** [comment]
用了RX的话 不用管

**Comment by BasThomas** [comment]
What do you mean exactly?

**Comment by zhaoyunyi** [comment]
no problem, can close this question @BasThomas

**Comment by gongyucheng** [comment]
@xiangyu-sun  what do you mean please?Can you say more details? how to use it when i pop viewcontroller
