### ISSUE TITLE
How to handle errors after filterSuccessfulStatusCodes?

### ISSUE THREAD

**Issue by rlam3** [Moya/Moya#848]
How to handle errors after filterSuccessfulStatusCodes?

```swift

provider.request(.token(_,_))
.filterSuccessfulStatusCodes()
.mapObject(type: MyObjectMap.self)
.subscribe(onNext:{ object in

   // do something with mapped object 

})
```

what if my whole request fails? How can I handle the request and log the error? Thanks!

**Comment by leoneparise** [comment]
Use `.subscribe(onError: { error in ... })`. But it's not a good solution. Once the observable receives an error it unsubscribes.

**Comment by jonlambert** [comment]
Alternatively if you want to have the subscription remain there's `.catchError|.catchErrorJustReturn` to handle the error before it disposes. For example:

```swift
provider.request(.token(_,_))
  .filterSuccessfulStatusCodes()
  .catchError() { error -> Observable<Response> in
    // do something to return a new Observable, retry etc.

    // ...or...
    
    // pass it along if it's not recoverable
    throw error
  }
  .mapObject(type: MyObjectMap.self)
  .subscribe(onNext:{ object in

    // do something with mapped object 

})
```

**Comment by rlam3** [comment]
@leoneparise so when it unsubscribes, i handle the error out of the chain?

**Comment by scottrhoyt** [comment]
@rlam3, @jonlambert 's suggestion looks like what you are looking for then. Does this resolve the issue for you?

**Comment by scottrhoyt** [comment]
Since there hasn't been any activity on this thread for some time, I am going to go ahead and close it. Please re-open or create a new issue if you would like to discuss further. Thanks.
