### ISSUE TITLE
Consuming SOAP Api. Where can I set the httpBody?

### ISSUE THREAD

**Issue by k8mil** [Moya/Moya#849]
version : 8.0.0-beta.5
swift 3.0

In common way I used the `soapMessage` which is a `String` with XML tags, create the data from it and pass into `request.httpBody` like that: 
```swift
var request = URLRequest(url: url)
request.addValue("text/xml; charset=utf-8", forHTTPHeaderField: "Content-Type")
request.addValue(soapMessage, forHTTPHeaderField: "Content-Length")
request.httpMethod = httpMethod
request.httpBody = soapMessage.data(using: .utf8, allowLossyConversion: false)

URLSession.shared.dataTask(with: request) {
    [weak self] (data, response, error) in
    if error == nil {
        var result: String?
        if let data = data {
            result = String(data: data, encoding: .utf8)
        }
        completion(result)
    } else {
        self?.log.error(error!.localizedDescription)
        completion(nil)
    }
}.resume()
```

If I want to use the `Moya` and `TargetType` the `parameters` is a `Dictionary` type and a `sampleData` is not called after doing this:

```swift
let provider = MoyaProvider<Endpoint>()

provider.request(.authenticateManager(login: "login", password: "123123")) {
  result in
  print(result)
}
```

My `Endpoint`  class:

```swift
enum Endpoint {
    case login(login: String, password: String)
}

extension Endpoint: TargetType {

    var task: Task {
        return .request
    }
    var validate: Bool {
        return false
    }

    var baseURL: URL {
        var rl : URL;
        return URL(string: "https://someurl.com")!
    }

    var method: Moya.Method {
        return .post
    }

    var path: String {
        return "/somepath.asmx"
    }

    var parameters: [String: Any]? {
        return nil
    }

    var sampleData: Data {
        switch self {
        case .login(let login, let password):
            return SoapMessageCreator()
            .login(userName: login, password: password).data(using: .utf8)!
        }
    }
}
```

**So my question is where should I put the `Data` from my soapMessage(with XML tags) `String` ? Or where can I set the `httpBody` ?**

Thanks!

**Comment by scottrhoyt** [comment]
In this case you best bet is to modify the `httpBody` of the underlying `URLRequest`. You have two choices on where to do this. Either in the providers `requestClosure` or by creating a plugin and using the `prepare` function.

**Comment by scottrhoyt** [comment]
If you can represent all of your XML data in key/value format, another option would be to create a custom parameter encoder conforming to `ParameterEncoding` and utilize the `TargetType.parameters` property to pass the data. Then in the `endpointClosure` create the endpoint with your custom parameter encoder.

**Comment by scottrhoyt** [comment]
You can now use `TargetType.parameterEncoding` to change the parameter encoding, but you would still need to create a custom XML-based `ParameterEncoding`.

**Comment by k8mil** [comment]
Ok, thanks for that complete answer!

**Comment by scottrhoyt** [comment]
@k8mil No problem! If you wind up creating a custom XML `ParameterEncoding`, it would be awesome to submit that to Alamofire in a PR. That way we can offer it to all Moya consumers as well.
