### ISSUE TITLE
Pagination documentation/example? 

### ISSUE THREAD

**Issue by rlam3** [Moya/Moya#850]
Looking for pagination documentation. Was wondering if there was an example of how to use moya when doing some sort of feed pagination. Thanks!

**Comment by BasThomas** [comment]
You can take a look at #834 to get started, maybe?

**Comment by rlam3** [comment]
Is there a proper way to use collection view / table view with moya? 

I've been trying to map my provider.request. I'm firing my request inside viewDidLoad then mapping  and subscribing to object and setting it back into var feedObjects: [FeedObject] via self.feedObject

```swift

...viewDidLoad

provider.request(.myRequest)
.map...
.subscribe{ (event) in
switch event{
case .next(let object):
    self.feedObjects = let object.feeds
}
case .error(let error):
    print("\(error.localizedDescription...)")
default
    break // <<< It keeps breaking out
}


...numberOfItemsInSection

return self.feedObjects.count // <<< Always finds nil... even though the request works...

```

**Comment by AndrewSB** [comment]
@rlam3 since you're using Rx, I'd recommend looking at this example in the RxSwift repo: https://github.com/ReactiveX/RxSwift/tree/master/RxExample/RxExample/Examples/GitHubSearchRepositories

It doesn't use Moya, but the GitHub service it uses is similar to a Moya `provider`

**Comment by rlam3** [comment]
@AndrewSB Thanks for the pointer, but I'm confused as to why my numberOfItemsInSection is reading nil when it is mapped correctly.... Or does it mean that when I use RxSwift I'm not able to use the standard collectionview function/libraries?

**Comment by AndrewSB** [comment]
I really can't say without seeing the rest of your code @rlam3. I'd recommend putting a `didSet` propertyObserver on your `feedItems` property, and either printing out the newValue, or setting a breakpoint so you can see what is mutating the property. It doesn't look like an RxSwift problem to me, I've been able to use standard collection view functions while using Rx 😄

**Comment by AndrewSB** [comment]
@rlam3: I'm going to close this for now, but please do re-open this if you still have questions, it sounds like this is more of a Rx-y question than a Moya question.

RxSwift also has a really friendly slack where people are usually really willing to help out, especially with questions about best practice 😄
