### ISSUE TITLE
How do test without Nimble

### ISSUE THREAD

**Issue by shivayogic** [Moya/Moya#853]
Hi 

Need help in writing test cases for my project which uses `RxMoyaProvider` and Object mapper. Currently the calls to the n/w or using stub behaviour works fine in my code. However when I tried to do unit test cases test cases are failing and even there is no call to endpoint closure. This I obesrved with debug statement in endpoint closure. 
Below is the code snippet for the test case

```swift
// initialises the oauthclient which holds variable of moyaProvider and is initialized with stub behavier
 let  ccApiOAuthClient = CCApiOAuthClient(apiKey: CC_CLIENT_API_KEY, apiSecreteToken: CC_CLIENT_SECRET_TOKEN, stubCloser: MoyaProvider.immediatelyStub, response: (200, CCStubbedResponse.stubbedResponseFromJSON(filename: "authResponse")))
        

        let expect = expectation(description: "subscribeNext called")
        
        
// rx_getAuthToken is the function defined in the oAthClient which in turn send the request
        
              _ = ccApiOAuthClient.rx_getAuthToken(username: "XYZ", password: "XYZ")
            .observeOn(MainScheduler.instance)
            .do(onNext: { oAuth2ResponseObject in
                print(oAuth2ResponseObject)
                XCTAssert(true)
               // expect.fulfill()
            })
        
        waitForExpectations(timeout: 2) { error in
            if let error = error {
                XCTFail("waitForExpectationsWithTimeout errored: \(error)")
            }
        }
```
Do next is never executed. Advice me .
Thanks in Advance
Shivayogi

**Comment by shivayogic** [comment]
Can some one help me on how to test without Nimble?

**Comment by scottrhoyt** [comment]
@shivayogic, in the code you posted, it doesn't look like there are any subscriptions to `rx_getAuthToken`, so the request won't be made. The `do` operator only specifies a side-effect to be performed. Try replacing the `do` operator with `subscribe`. Then uncomment the `expect.fulfill()` and see if this test passes.

**Comment by shivayogic** [comment]
@scottrhoyt 
Thank you for the reply. I have solved the issue myself. It was a mistake on using do operator. After replacing with subscribe it is working fine.
