### ISSUE TITLE
How setup an Authorization field in HTTPHeader?

### ISSUE THREAD

**Issue by liliah** [Moya/Moya#854]
Moya: 8.0.0-beta.5
Swift: 3.0
Xcode: 8.1

Hi, everyone

I am using the endpointClosure as follows for my GET requests, but I am getting a 401 response.

```swift
let endpointClosure = { (target: MyTarget) -> Endpoint<MyTarget> in
        let defaultEndpoint = MoyaProvider<MyTarget>.defaultEndpointMapping(target)
        switch target{
        case .event:
        return defaultEndpoint.adding(newHTTPHeaderFields: ["Authorization": "Token token=\(access_token)"])
        default:
            return defaultEndpoint
        }
    }
```

When using the DHC Restless extension I add the header like this and works:
![screen shot 2016-12-21 at 9 46 46 pm](https://cloud.githubusercontent.com/assets/291768/21411397/01aa5258-c7c7-11e6-9292-76b487ab514c.png)

Can someone say what I am doing wrong or a workaround?

My Target:
```swift

enum ServiceAPI{
    case event(dateID: Int)
}

extension ServiceAPI: TargetType{
    var baseURL: URL {return URL(string: "http://myapi.com/api")!}
    
    var path: String{
        switch self{
        case .event(let dateID):
            return "/dates/\(dateID)"
        }
    }
    
     var method: Moya.Method{
        switch self{
        case .event:
                return .get
        }
    }
    
     var parameters: [String : Any]?{
        switch self{            
        case .event:
            return nil
        }
    }
    
     var task: Task {
        switch self {
        default:
            return .request
        }
    }
    
     var sampleData: Data {
        return "Hi".utf8Encoded
    }
}

private extension String {
      
    var utf8Encoded: Data {
        return self.data(using: .utf8)!
    }
}
```

Really thanks!

**Comment by liliah** [comment]
So I've found a workaround for this issue. I added an empty string after the authorization parameter and it worked!

```swift
let endpointClosure = { (target: MyTarget) -> Endpoint<MyTarget> in
        let defaultEndpoint = MoyaProvider<MyTarget>.defaultEndpointMapping(target)
        switch target{
        case .event:
        return defaultEndpoint.adding(newHTTPHeaderFields: ["authorization ": "Token token=\(access_token)"])
        default:
            return defaultEndpoint
        }
    }
```

If there is a better way to do it let me know!
Thanks.

**Comment by scottrhoyt** [comment]
Hey @liliah.

I can't say that I know specifically what is going wrong here, but if I had to guess, I would say that there could be a problem with how the authorization header is being encoded and/or how it is interpreted by your API. If you have the ability to change how authorization headers are used by the API, I think you might have fewer issues if you use the standard approach for access-token-based authentication. This is the standard format:

```
Authorization: Bearer <access_token>
```

If you have to use the current approach, I would note that the capitalization of `Authorization` also changed. That may be the source of the different behavior as well.

For debugging purposes, you can also utilize the `NetworkLoggerPlugin`. Turn on the curl output and then you can try the generated requests via CLI for another perspective on what might be going on.

**Comment by scottrhoyt** [comment]
Were you able to get this sorted out @liliah?

**Comment by liliah** [comment]
The workaround that I posted before is actually working. I contacted the API's developer and said about this issue but he told me that it's working normally on Postman and on the Android client so I don't know what exacly caused it. You can close the issue and thanks!

**Comment by scottrhoyt** [comment]
Glad to hear it is working for you! 👍

**Comment by mihailstumkins** [comment]
I've encountered this issue using AccessTokenAuthorizable, by removing it and using endpointClosure "Authorization " instead of "Authorization" it worked

**Comment by scottrhoyt** [comment]
That is interesting @mihailstumkins. Would you mind opening up an issue to track that? `AccessTokenPlugin` and `AccessTokenAuthorizable` are new additions, so there is a possibility that they contain a bug that is not being tested for.

**Comment by AmrAbedal** [comment]
> parameter

wished to work for me but it doesn't

**Comment by tudi12346** [comment]
> I've encountered this issue using AccessTokenAuthorizable, by removing it and using endpointClosure with "Authorization " string instead of "Authorization" it worked

I love you !!!!! <3
