### ISSUE TITLE
How can I use comma at url query?

### ISSUE THREAD

**Issue by lovesuper** [Moya/Moya#855]
Right now Moya url-encoding commas at %2C.

**Comment by scottrhoyt** [comment]
This is probably a result of the underlying `Alamofire.URLEncoding`. If your API can take parameters encoded as JSON in the HTTP body, I would suggest  switching to `JSONEncoding`. The easiest place to do this would be in the `endpointClosure` when initializing the `Endpoint`.

**Comment by scottrhoyt** [comment]
You can now use `TargetType.parameterEncoding` to accomplish this.
