### ISSUE TITLE
How do I reload a custom uiviewcontroller after rx request?

### ISSUE THREAD

**Issue by rlam3** [Moya/Moya#857]
I've been trying to find out how to reload my uiviewcontroller similar to how tableviewcontroller/collectionviewcontroller requires me to reload the view after the rxmoya request finishes and sets the array of object back into an optional var. 

```swift
var myArray: ArrayMappable?

func setupRx(){
// provider.request ..... 
// self.myArray = object_of_subscribed
// self.tableview.reloaddata() OR self.collectionview.reloaddata()
}

viewdidload{
setupRx()
}

```

But on a normal uiviewcontroller, what would be that similar statement? Thanks!

**Comment by scottrhoyt** [comment]
For RxSwift, the favored approach to updating your UI would be to use `bind`. You can find some good tutorials for how to do so via a search.

**Comment by scottrhoyt** [comment]
@rlam3 were you able to sort out using `bind` to accomplish what you want? If not I suggest working through [these excellent tutorials](http://www.thedroidsonroids.com/blog/ios/rxswift-by-examples-1-the-basics/) from our very own @sunshinejr.

**Comment by scottrhoyt** [comment]
Since there hasn't been any activity on this thread for some time, I am going to go ahead and close it. Please re-open or create a new issue if you would like to discuss further. Thanks.
