### ISSUE TITLE
What is sampleData for?

### ISSUE THREAD

**Issue by dannymout** [Moya/Moya#863]
I have a question. I want to make sure I understand the purpose of `sampleData`. So, is this where examples of the JSON data you'd receive from the API go? If this is the case, I'm having an issue. The documentation for the API I'm using provides examples. I'm trying to use these examples, so I copied and pasted them and put the quotes around the text, but something with the quotes somewhere is messing up making Swift think it's a comment, I need to be able to put this into a string. Here is what's happening: 

![screenshot](http://i.imgur.com/1P8cI9W.png) 
### Some of it is being picked up as a string, and some of it as a comment. All I did was put quotes around it.

**Comment by scottrhoyt** [comment]
The quotes in the JSON aren’t escaped so the compiler is not interpreting this the way that you want. For `sampleData` this complex, instead of going through and escaping all the necessary characters, I would recommend that you load this data from another file.
