### ISSUE TITLE
Suggestion for TargetType

### ISSUE THREAD

**Issue by EvilNOP** [Moya/Moya#864]
Considering that if I want to use JSONEncoding, not the default one (URLEncoding).

So I have to define an endpointClosure like the following code dose:

```swift
let endpointClosure = {
    (target: MyTarget) -> Endpoint<MyTarget> in
            
    let urlString = target.baseURL.appendingPathComponent(gistRouter.path).absoluteString
            
    let sampleResponseClosure: Endpoint.SampleResponseClosure = {
       .networkResponse(200, target.sampleData)
     }
            
    return Endpoint<MyTarget>(
      url: urlString,
      sampleResponseClosure: sampleResponseClosure,
      method: gistRouter.method,
      parameters: gistRouter.parameters,
      parameterEncoding: gistRouter.parameterEncoding
    )
}
```

That's annoying!

Here's the suggestion:

1: add the following code  to TargetType
```swift
var parameterEncoding: Moya.ParameterEncoding { get }
```

2: 
```swift
public extension TargetType {
    var parameterEncoding: Moya.ParameterEncoding {
        return URLEncoding.default
    }
}
```

3: In the Moya+Defaults.swift file
```swift
public final class func defaultEndpointMapping(for target: Target) -> Endpoint<Target> {
    let url = target.baseURL.appendingPathComponent(target.path).absoluteString
    return Endpoint(url: url, sampleResponseClosure: { .networkResponse(200, target.sampleData) }, method: target.method, parameters: target.parameters, parameterEncoding: target.parameterEncoding)
}
```

With the above code implemented, I won't have to define endpointClosure if absolutely necessary.

**Comment by BasThomas** [comment]
#859 already adds `parameterEncoding` defaulting to `JSONEncoding`. Which version of Moya are you using?

**Comment by EvilNOP** [comment]
8.0.0-beta.6

**Comment by BasThomas** [comment]
Ah right, @scottrhoyt's change has not had a new release yet. Do you think that solves your problem or would your number 3 still be something you'd really like to see?

**Comment by scottrhoyt** [comment]
@BasThomas, I think that number 3 is also being done in #859. It looks to just be the change needed to encorporate `TargetType`'s `parameterEncoding` instead of the hard-coded `URLEncoding.default`.

**Comment by BasThomas** [comment]
Alright, I am going to close this issue then. @EvilNOP, if you feel like something else should still be addressed, feel free to reopen!
