### ISSUE TITLE
Reduce CircleCI build time by downloading/caching frameworks.

### ISSUE THREAD

**Issue by scottrhoyt** [Moya/Moya#870]
I'm not very familiar with the CircleCI / Rake setup, but I think we can reduce our CI build times by downloading RxSwift instead of building it. I can't find any `--no-use-binaries` flags for carthage, so I don't know why it isn't downloading the framework in the first place. Perhaps someone with more experience with the CI setup will have more luck.

**Comment by AndrewSB** [comment]
I have no idea either... `github "ReactiveX/RxSwift" ~> 3.0` should pull down the binary... I just tested locally and it pulled down the binary

<img width="736" alt="screen shot 2016-12-29 at 3 45 35 pm" src="https://cloud.githubusercontent.com/assets/3814772/21557217/e748bfc2-cddd-11e6-9fb2-6ebf88397cf8.png">

very strange...

**Comment by scottrhoyt** [comment]
I wonder if it has anything to do with this:

<img width="467" alt="screen shot 2016-12-29 at 8 25 48 pm" src="https://cloud.githubusercontent.com/assets/4259250/21559655/13bef234-ce05-11e6-9140-82ea18d861f2.png">

I wouldn't think so, but that also looks strange to me.

**Comment by scottrhoyt** [comment]
Removing Cartfile.resolved locally doesn't seem to have an effect.

**Comment by scottrhoyt** [comment]
Thanks @AndrewSB! I wonder if it would also be possible to add the Carthage/* directories to the build cache and avoid rebuilding all together, except maybe for a tagged release or `master` builds?

**Comment by scottrhoyt** [comment]
This would also be good to figure out before #643 because we will want to test SPM builds as well and those are likely to take as long. On travis, I split builds up into 3 separate parallel jobs (macOS-Xcode, macOS-SPM, and Linux-SPM).

**Comment by AndrewSB** [comment]
@scottrhoyt: that's a good idea. I set something similar up for [AndrewSB/wrytr](github.com/AndrewSB/wrytr), a project I've been working on every now and then. I created a fastlane action to run a cached Carthage build on CI.
Here's the bootstrap action https://github.com/AndrewSB/fastlane/blob/master/carthage-bootstrap-if-needed.sh

I could set up Moya to do something similar

**Comment by scottrhoyt** [comment]
I think that's a really nice approach @AndrewSB. 👍 It might be nice to have this be the behavior on non-`master` branches and PRs, and then trigger a full bootstrap on `master` and tagged released as a sanity check. What do you think?

All in all, it would be great to get the PR build time down from the ~20 minutes right now to < 10. What do you think @Moya/contributors? Any other ideas on how we might accomplish that?

**Comment by AndrewSB** [comment]
Implemented in #885 🎉

**Comment by scottrhoyt** [comment]
<img width="610" alt="screen shot 2017-01-02 at 7 14 17 pm" src="https://cloud.githubusercontent.com/assets/4259250/21599328/caa224cc-d11f-11e6-8fd1-7e2456a00ef7.png">

Build time down over 50%. Yay!

**Comment by BasThomas** [comment]
🎉🎉🎉🎉
