### ISSUE TITLE
Make a second request to URL provided in JSON response.

### ISSUE THREAD

**Issue by dannymout** [Moya/Moya#904]
## Version
Moya 8.0.0, Swift 3

The API I'm using with Moya has URLs in most of the JSON responses. What I mean is, let's say I had `getProfile(username: String)`. The API returns the data, and the response provides more API links to get more information like the user's followers, since putting them in the same response would probably make the size of the request much larger. I don't want to add more functions for each of these URLs, but instead I want to make a Moya request using a URL. I know it's a bit confusing, should I just do this with Alamofire?

**Comment by scottrhoyt** [comment]
There are some features in #861 that would make this easier to do with Moya, but we haven't decided on whether to include them or not yet. If you are interested in including it yourself, you can take a look at how `SingleURLTarget` is implemented and can potentially use that in your own code.

**Comment by scottrhoyt** [comment]
@dannymout were you able to solve this? Or should we keep this issue open?

**Comment by dannymout** [comment]
@scottrhoyt Well, I eventually figured this out, but if you can get this feature added, it would be useful.
