### ISSUE TITLE
How to cancel a download request

### ISSUE THREAD

**Issue by GorbAnthony** [Moya/Moya#916]
I want to cancel the download request.
```swift
func download() -> Observable<ProgressResponse> {
    let req = FileDownloadProvider.requestWithProgress(.downloadFile(fromURL: fileURL, saveAs: audioID + ".mp3"))
    req.cancel()// Value of type 'Observable<ProgressResponse>' has no member 'cancel'
}
```

**Comment by scottrhoyt** [comment]
I haven't tried this before, but looking [here](https://github.com/Moya/Moya/blob/master/Sources/RxMoya/RxMoyaProvider.swift#L61) it appears the request will be cancelled if the Observable is disposed. So can you try disposing the Observable?

**Comment by leoneparise** [comment]
Yes. Cancel is done when observable is disposed.

**Comment by scottrhoyt** [comment]
Was that able to help you out @GorbAnthony? If so, can you close this issue please? Thanks.
