### ISSUE TITLE
How can I contract a url like https://api.github.com/gists/:id?

### ISSUE THREAD

**Issue by EvilNOP** [Moya/Moya#918]
The :id is a value indicating that id of the gist.

I solved this problem by creating an endpoint closure where the target's base url is `api.github.com` and the target's path is `/gists`:

```swift
let endpointClosure: MoyaProvider.EndpointClosure = {
    (target: GistRouter) -> Endpoint<GistRouter> in
            
    let url = target.baseURL.appendingPathComponent(target.path).absoluteString + "/xxx"

    let endpoint = Endpoint<GistRouter>(url: url, sampleResponseClosure: { .networkResponse(200, target.sampleData) }, method: target.method, parameters: target.parameters)
            
    return endpoint
}
```

Is there a better solution?

**Comment by bjarkehs** [comment]
Am I missing something or could the same be achieved with:

(Slightly modified example)
```swift
extension MyService: TargetType {
    ...
    var path: String {
        return "endpoint/xxx"
    }
    ...
}
```

I mean it really depends on your enum. If you have associated value with your enum, then you can grab it just like in the [Basic Example](https://github.com/Moya/Moya/blob/master/docs/Examples/Basic.md)

**Comment by EvilNOP** [comment]
@bjarkehs Oh, I forget this, thx so much.

**Comment by bjarkehs** [comment]
You're welcome.
