### ISSUE TITLE
Problems to make a valid url

### ISSUE THREAD

**Issue by edvmorango** [Moya/Moya#919]
I need use "?"  to make the url, the problem is the url created with query parameters is used to make a post request. 
```swift
path.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!
```
Doesn't work, can i construct the url through Moya?

```swift
 var baseURL: URL { return
        URL(fileURLWithPath: "https://abc.us/api/")
    }

    public var path: String {
       
        switch self {
        case .login(let person):
             return "?action=person.signIn&username="+person.login
        case .event(let event):
               return "?action=event.person.bind&eventID="+event.eventId+"&tokenID="+event.person.token!
        }
    }
    
    var method: Moya.Method {
        switch self{
        
        case  .login, .event: return .post
       
        }
    }
```

**Comment by bjarkehs** [comment]
Have a look at parameters in [Basic example](https://github.com/Moya/Moya/blob/master/docs/Examples/Basic.md), and then use URLEncoding for ParameterEncoding.

So:

```swift
var parameter: [String: Any] {
    switch self {
    case .login(let person):
        return ["action": "person.signIn", "username": person.login]
    ...
    }
}

var parameterEncoding: ParameterEncoding {
    return URLEncoding()
}
```

**Comment by bjarkehs** [comment]
Actually, sorry. Just reread the question. And you should instead have a look at #909

**Comment by edvmorango** [comment]
Ok @bjarkehs, thank you, i'll try this solution.

**Comment by bjarkehs** [comment]
@edvmorango I just realized something. #909 deals with the problem of having both body and url parameters. So if you only have data in the URL, and nothing in the body, then actually my first response was more correct.

```swift
var parameterEncoding: ParameterEncoding {
    return URLEncoding(destination: .queryString) // Puts all supplied parameters in the URL.
}
```

**Comment by edvmorango** [comment]
Thank you again, @bjarkehs, the #909 fits perfectly for my the actual problem, but i'll try this other method in other situations.
