### ISSUE TITLE
Upload pdf data

### ISSUE THREAD

**Issue by pluckq** [Moya/Moya#920]
I use latest Moya beta version, and i have a problem with uploading pdf. I've got valid pdf Data (I know coz i can open it in webview). I'm trying upload, but server didn't accepting it. While uploading images all well. 

```swift
return .upload(.multipart([MultipartFormData(provider: .data(document.file!), name: "doc", fileName: "doc.pdf", mimeType: "application/pdf")]))
```
where document.file is swift Data with pdf

**Comment by vzsg** [comment]
Does your server expect a multipart upload or a simple POST where the body is the PDF data? (Your code does the multipart version.)

 Are you getting any useful or technical messages in the server's response?

**Comment by pluckq** [comment]
Yes, server should expect multipart, as i said images uploading working fine.
I getting status code 400 with message no file here, maybe i should use some other method? 
Thank you for response

**Comment by BasThomas** [comment]
#911 might provide some insight.

**Comment by pluckq** [comment]
thank you but no, already doing same

**Comment by leoneparise** [comment]
It's strange that your server is not accepting a PDF but it's accepting images. Can you do the same test with Alamofire directly?

**Comment by pluckq** [comment]
Ok, sorry, it was my fault, wrong field name. Thank you all for response, everything work.
