### ISSUE TITLE
Can we return value inside provider.request ?

### ISSUE THREAD

**Issue by abadikaka** [Moya/Moya#927]
Hi guys i am using newest Moya version and swift 3.0
I have question, can we return some values in a function which will call a provider request ?
I need it bcs i will use that values in objective-c bridging, since i will use it for react-native .
The below code i use always return "" instead of dict that will be filled inside provider.request

```swift
public func setupRx() -> Any {
        
        provider = RxMoyaProvider<GitHub>()
        var dict : Any? = ""
        
        provider.request(.bible).subscribe { event in
            switch event {
            case let .next(response):
                //image = UIImage(data: response.data)
                do{
                    dict = try response.mapJSON()
                    try print("Dict is : ", dict)
                }catch {
                    print("Something wrong");
                }
            case let .error(error):
                print("Error : ",error)
            default:
                break
            }
        }
        return dict
}


//BRIDGING CODE in Obj-C for react-native

RCT_EXPORT_METHOD(connectToHub
                  
                  :(RCTPromiseResolveBlock)resolve
                  :(RCTPromiseRejectBlock)reject)
{
    RCTMain * helloWorld = [RCTMain newInstance];
    //call setupRx
    NSString *test = [helloWorld setupRx];
    //always nil never get the value from API that has been called inside setupRx
    NSLog(@"Test Dictionary return : %@", [helloWorld setupRx]);
    [self.bridge.eventDispatcher sendAppEventWithName:@"onHubConnected" body:nil];
}
```
Thank you..

**Comment by vzsg** [comment]
One thing is crystal clear: you cannot _synchronously_ return something that will arrive in the future, _asynchronously_. (Not to mention that using side-effects to sneak out values from RX is malpractice by itself.)

The `setupRx` function should be rewritten to take callbacks or return an Observable, and your bridging code should make use of the resolve/reject blocks you get from the framework. [This seems to be related.](https://blog.getexponent.com/react-native-meets-async-functions-3e6f81111173#.qummm3qs6)

**Comment by abadikaka** [comment]
@vzsg Thank you so much sir.. Your solution using completion block is worked. Now i could get result in my obj-c bridging..
