### ISSUE TITLE
[Discussion] Release 8.0.1

### ISSUE THREAD

**Issue by pedrovereza** [Moya/Moya#928]
Hey folks,

We already have our first fix after `8.0.0` (#905), which solves #844 and, more recently, #921.

According to [the changelog](https://github.com/Moya/Moya/blob/master/Changelog.md), it seems that this was the only change since `8.0.0` but I feel it justifies releasing `8.0.1`.

@Moya/contributors thoughts on that?

**Comment by BasThomas** [comment]
Yeah, seems like a good idea. 👍

**Comment by scottrhoyt** [comment]
I think so too!

**Comment by pedrovereza** [comment]
I naively tried to do the release myself but I don't have access to push the new pod version to cocoapods. 

@ashfurrow @AvdLee halp 🙈

**Comment by ashfurrow** [comment]
@pedrofjfmartins No problem! I've added you as an owner to the CocoaPod, want to try again? Happy to help!

**Comment by pedrovereza** [comment]
@ashfurrow it went smoothly this time, thanks!
