### ISSUE TITLE
Use Alamofire ~> 4.0.0 in pod spec dependency 

### ISSUE THREAD

**Issue by chrisjrex** [Moya/Moya#937]
Am currently using Moya 8.0.1 via cocoapods but i now have to use the cocoapods post_install hook to set `config.build_settings['SWIFT_VERSION'] = '3'` because otherwise the project can't build in the latest version of Xcode because of the syntax updates to swift and the version of Alamofire used in the podsepc is only ~> 3.0.0. which doesn't have the latest updates needed.

**Comment by bjarkehs** [comment]
According to this https://github.com/Moya/Moya/blob/master/Moya.podspec#L25 it uses `Alamofire 4.2`. Are you sure your issue is not in your Podfile or Xcode configuration?

**Comment by chrisjrex** [comment]
OK yes. i read my pod error incorrectly. This is the error I had. But if i check the install after removing my requirement for `4.3.0` then i see `4.2` is used

`[!] Unable to satisfy the following requirements:

- `Alamofire (= 4.3.0)` required by `Podfile`
- `Alamofire (~> 3.0)` required by `Moya/Core (6.1.2)`
`

But any reason why the latest version of Xcode would complain about the syntax without having `config.build_settings['SWIFT_VERSION'] = '3'` set?

I may need to move my question over to Alamofire
