### ISSUE TITLE
How to build requests for "non-standard" APIs?

### ISSUE THREAD

**Issue by miwanski** [Moya/Moya#938]
I'm in the process of building an app for a friend's website, and figured I might learn to use Moya while I'm at it. The website is using a bit non-standard way of building request links: 
```http://mobileapi.blah.info/1/?action=index&page=1```
I've followed the [basic setup](https://github.com/Moya/Moya/blob/master/docs/Examples/Basic.md) to configure the provider:
```swift
var baseURL: URL { return URL(string: "https://mobileapi.blah.info/1/?action=")! }

var path: String {
  switch self {
    case .index:
      return "index"
  }
}
// ...

var parameters: [String: Any]? {
  switch self {
    case .index(let page):
      return ["page": page]
  }
}
// ...
```

With above setup, Moya builds a request like this: 
```https://mobileapi.blah.info/1/index?action=&page=1```
and returns 404.

I've also tried passing ```https://mobileapi.blah.info/1/``` as ```baseURL```, while passing ```"?action=index"``` as ```path```, but that didn't work either. If someone could point the newb in the right direction, I'd be much obliged.

**Comment by scottrhoyt** [comment]
Since your friend's website builds page URLs using query parameters, you will probably want to use the `parameters` property to supply this information as well:

```swift
var path: String {
  return ""
}

var parameters: [String: Any]? {
  switch self {
    case .index(let page):
      return ["action": "index", "page": page]
  }
```

**Comment by bjarkehs** [comment]
I think the issue is that path is added to the URL, and since it's a path and not a parameter it wont be put in the parameters, i.e. after `?`.

This is a pretty nasty hack, but you'll have to handle everything in parameters.

And @scottrhoyt beat me to the punch.

**Comment by pedrovereza** [comment]
Expanding @scottrhoyt response:

```swift
enum MobileAPI {
    case index(page: Int)
}

extension MobileAPI : TargetType {
    public var baseURL: URL { return URL(string: "http://mobileapi.blah.info")! }

    public var path: String {
        return "/1/"
    }

    public var method: Moya.Method {
        return .get
    }
    
    public var parameters: [String : Any]? {
        switch self {
            case .index(let page): return ["action": "index", "page": page]
        }
    }
    
    public var sampleData: Data { return Data() }
    
    public var task: Task { return .request }
    
    public var validate: Bool { return true }
    
    public var parameterEncoding: Moya.ParameterEncoding { return URLEncoding.default }
}
```

Usage:

```swift
        let mobileAPIProvider = MoyaProvider<MobileAPI>()

        mobileAPIProvider.request(.index(page:1)) { result in
            switch result {
            case let .success(response):
                // do something with response
            case let .failure(error):
                print(error)
            }
        }
```

This produces the request you want:
`["Moya_Logger: Request: http://mobileapi.blah.info/1/action=index&page=1"]`

Let us know if you have more questions :wink:

**Comment by miwanski** [comment]
Worked like a charm. Many thanks, gentlemen!
