### ISSUE TITLE
Progress reporting sometimes hanging with rxMoya

### ISSUE THREAD

**Issue by migue1s** [Moya/Moya#940]
Hello all,

I'm currently trying to upload a multipart request with progress but the progress of the particular request will sometimes freeze and never complete. This will occur if I try to make many such requests (at least 2-3) in a sequence, the second or third will start reporting the percent but will randomly stop before reaching the end. The request will work appropriately as long as I don't use `requestWithProgress`. This works correctly when not using rx. 

I've tried testing using the following code and the "print" command will stop running, no errors catched, and the `filterCompleted()` never passing:

```swift
rxProvider.requestWithProgress(target)
        .do(onNext: { response in
          print(response.progress)
        })
        .filterCompleted()
        /// Do some other stuff
        .addDisposableTo(disposeBag)
```

Configuration:
Moya (8.0.1)
RxSwift (3.1.0)
COCOAPODS: 1.1.1

**Comment by migue1s** [comment]
I've continued testing it, the problem is in the current provider wrapper. `requestWithProgress` doesn't always behave reliably. 

```swift
func requestWithProgress(_ token: Target, progressHandler: @escaping (Double)->Void) -> Observable<Response> {
    let response: Observable<Response> = Observable.create { [weak self] observer in
      let cancellableToken = self?.request(target, queue: nil, progress: { (progressResponse: ProgressResponse) in
        progressHandler(progressResponse.progress)
      }, completion: { result in
        switch result {
        case let .success(response):
          observer.onNext(response)
          observer.onCompleted()
        case let .failure(error):
          observer.onError(error)
        }
      })
      return Disposables.create {
        cancellableToken.cancel()
      }
    }
    return response
  }
```

Although this is a less than ideal implementation due to the callback instead of remaining in the rx world, it will work correctly when reporting the progress and will not hang. I recommend rechecking the logic in the `scan` and `progress` block under the original implementation as I suspect the problem lies there.

**Comment by AndrewSB** [comment]
This looks pretty interesting @migue1s. Do you think it's related to #819 as well?

It would be really awesome if you'd make a Pull Request with your change, so people can discuss your solution, and we can get your bug fixed!

**Comment by vaunus** [comment]
Can confirm we are also seeing problems with this. The progress callback seems to hang as @migue1s has reported and I've also noticed that a subsequent .do(onNext after a filterCompleted in the chain is called twice sometimes.

I am using a similar fix for RxMoya for the time being based on @migue1s solution above. Thanks!

```
extension RxMoyaProvider where Target : TargetType {
    
    public func requestWithProgressFixed(_ target: Target, progressHandler: @escaping (Double)->Void) -> Observable<Response> {
        
        let response: Observable<Response> = Observable.create {
            [weak self] observer in
            
            let cancellableToken = self?.request(target, queue: nil, progress: { (progressResponse: ProgressResponse) in
                progressHandler(progressResponse.progress)
            }, completion: {
                result in
                
                switch result {
                case let .success(response):
                    observer.onNext(response)
                    observer.onCompleted()
                case let .failure(error):
                    observer.onError(error)
                }
            })
            return Disposables.create {
                cancellableToken?.cancel()
            }
        }
        return response
    }
}
```

**Comment by sunshinejr** [comment]
@migue1s, @vaunus the problem with double `onNext` event after `filterCompleted` should be resolved after #1095. We still need to find the issue with hanging in the progress. If any of you guys have time and want to help us, PR would be greatly appreciated.

**Comment by PatrickSCLin** [comment]
It's easy to reproduce with AWS S3 + ELB!
we have multiple stages of server, it's working with Nginx all the time, but hanging sometimes with AWS ELB, progress is not reliable !

**Comment by sunshinejr** [comment]
Hey @PatrickSCLin, do you still encounter double `onNext` event? What version of Moya do you use? Is it with RxSwift?

**Comment by PatrickSCLin** [comment]
it should be the latest version, i cant tell double onNext event happen or not, i have use RxSwift, however it's easy to reproduce hanging issue, onNext event freeze sometimes,  but onCompleted is work.



從我的 iPhone 傳送

**Comment by sunshinejr** [comment]
Would you be able to make a new test project where this issue happens, @PatrickSCLin?

**Comment by PatrickSCLin** [comment]
sorry, I was testing with project of company, you can try to set AWS S3 + ELB in Tokyo region, it's easy to reproduce
