### ISSUE TITLE
Can't use latest Alamofire and RxSwift with Moya 8.0.1

### ISSUE THREAD

**Issue by andreyfel** [Moya/Moya#942]
I have the following podfile:
  pod 'Alamofire', '\~> 4.3'
  pod 'RxSwift', '\~> 3.2'
  pod 'RxCocoa', '\~> 3.2'
  pod 'Moya/RxSwift', '8.0.1'

When I run pod update I get:
[!] Unable to satisfy the following requirements:
- `Alamofire (~> 4.3)` required by `Podfile`
- `Alamofire (~> 4.2.0)` required by `Moya/Core (8.0.1)`
- `RxSwift (~> 3.2)` required by `Podfile`
- `RxSwift (~> 3.2)` required by `Podfile`
- `RxSwift (~> 3.1)` required by `RxCocoa (3.2.0)`
- `RxSwift (~> 3.1.0)` required by `Moya/RxSwift (8.0.1)`

**Comment by sunshinejr** [comment]
Seems like a problem with these lines in Podspec:
```
ss.dependency "RxSwift", "~> 3.1.0"
ss.dependency "Alamofire", "~> 4.2.0"
```

change to "~> 3.0" && "~> 4.0" could fix the problem, but there might be a reason why we have it this way (I'm out of the loop lately). Because of this we should discuss the fix with @Moya/contributors first. We could just higher up the versions of pods as well.

**Comment by BasThomas** [comment]
Let's see if we can update our dependencies.

**Comment by BasThomas** [comment]
It would actually be really nice to have some sort of dependency update check somewhere to keep us up to date. What do you think, @Moya/contributors? Should I create a separate issue?

**Comment by BasThomas** [comment]
Or we should do what @sunshinejr suggested, using just `~> 3.0` and `~> 4.0` respectively. Not sure what is the best option here.

**Comment by scottrhoyt** [comment]
I would go with @sunshinejr's suggestion for the time being.

**Comment by pedrovereza** [comment]
@andreyfel Moya 8.0.2 was release and should fix your problem. Can you please update and let us know if you still have issues? :wink:

**Comment by andreyfel** [comment]
Thank you guys for the quick reaction! It resolved issue with Moya, but I still have the same issue with Moya-ObjectMapper. Opened an issue there https://github.com/ivanbruel/Moya-ObjectMapper/issues/45
