### ISSUE TITLE
Release 8.0.2

### ISSUE THREAD

**Issue by pedrovereza** [Moya/Moya#946]
Latest changes in how we pin dependency versions fixes #942 (see #944).

This change is probably useful for a lot of projects, which justifies releasing a new patch.

**Comment by pedrovereza** [comment]
And it's [done](https://github.com/Moya/Moya/releases/tag/8.0.2) 🙌

**Comment by BasThomas** [comment]
It's pretty ironic we're saying this now in the README:

> For Moya, use the following entry in your Podfile:
>
>```ruby
>pod 'Moya', '8.0.2'
>```

Instead of 

```ruby
pod 'Moya', '~> 8.0'
```

😜

**Comment by ashfurrow** [comment]
Good point @BasThomas. Technically we shouldn't be specifying anything at all and just let the `Podfile.lock` file do it's thing. Someone want to update?
