### ISSUE TITLE
TargetTypeWithCompletion for encapsulated parsing 

### ISSUE THREAD

**Issue by michaelsand** [Moya/Moya#948]
Moya is unparalleled at encapsulating the call to APIs. I've been following Moya for a while and thinking about how to make it even more end-to-end: If its completion could take a specific type, or `Result<T, MoyaError>` of a type, instead of `Result<Moya.Response, MoyaError>`. `Moya.Response` is a good object, the issue is it requires clients to immediately parse it, which is inelegant, and probably a violation of separation of concerns if done in a view controller, for example. 

Of course, Moya shouldn’t prescribe a method of parsing—that’s not where this is going. But how to parse an endpoint's response, what the expected response is, is API knowledge. API knowledge that lives with the target endpoint information, alongside its path, parameters, etc. The `TargetType`. That is where the parsers should live. 

The issue is types-- There’s not a way for a target to return a variable type—a generic T or associated would mean each instance of `TargetType` and `MoyaProvider<TagetType<T>>` could only take or return that T, which defeats the purpose.

The solution that I’ve come up with, which is _nonbreaking_, is to create protocol that inherits from `TargetType`, `TargetTypeWithCompletion`. This protocol inherits all the requirements of `TargetType`, and adds a single method, `complete(with response: Moya.Response)`. 

There is no return-- every enum case would have to have an associated type for its completion block. This is best implemented with typealiases, so `typealias StringResultClosure = (Result<String, MoyaError>) -> Void` and then `.zen(StringResultClosure)` . My research hasn’t found any way around this associated completion. There is logic to it, because what comes back varies with the specific endpoint. 

This is the entirety of the addition: 
```swift
/// Inherits from TargetType and contains its own completion method.
public protocol TargetTypeWithCompletion : TargetType {
    func complete(with response: Result<Moya.Response, MoyaError>)
}


public extension MoyaProvider where Target : TargetTypeWithCompletion {

    @discardableResult
    public func requestWithCompletion(for target: Target, queue: DispatchQueue? = nil) -> Cancellable {
        return self.request(target, queue: queue) { (response) in
            target.complete(with: response)
        }
    }
}
```
And the usage goes from:

```swift
GitHubProvider.request(.userRepositories(username)) { result in
    switch result {
    case let .success(response):
        do {
            if let json = try response.mapJSON() as? NSArray {
                // Presumably, you'd parse the JSON into a model object. This is just a demo, so we'll keep it as-is.
                self.repos = json
            } else {
                self.showAlert("GitHub Fetch", message: "Unable to fetch from GitHub")
            }
        } catch {
            self.showAlert("GitHub Fetch", message: "Unable to fetch from GitHub")
        }
        self.tableView.reloadData()
    case let .failure(error):
        guard let error = error as? CustomStringConvertible else {
            break
        }
        self.showAlert("GitHub Fetch", message: error.description)
    }
}
```
To this:

```swift
GitHubProvider.requestWithCompletion(for: .userRepositories(username, { result in
    switch result {
    case let .success(repos):
        self.repos = repos
        self.tableView.reloadData()
    case let .failure(error):
        guard let error = error as? CustomStringConvertible else {
            break
        }
        self.showAlert("GitHub Fetch", message: error.description)
    }
}))
```
The paring code has ended up in the GitHub `TargetType`, which you can see at [on this branch](https://github.com/michaelsand/Moya/blob/f_targetTypeWithCompletion/Demo/Shared/GitHubAPI.swift) The parsing does not need to be in the `TargetType`-- the target type's `complete(with response:)` should switch on self and each case can call whatever parser it wants before calling its associated completion.   

(There's also an issue that I couldn't add `TargetTypeWithCompletion` to `TargetType.swift` because the compiler kept confusing the signature's `Result` with Alamofire's `Result` and complained.)

I've been following Moya for a while but haven't messed with workings of it before, so no idea if this could cause issues-- so curious what other people think.

**Comment by scottrhoyt** [comment]
I share your desire to find a way to inject return type information into the `TargetType`s themselves, @michaelsand. This is definitely a creative approach to doing so within the constraints that Swift gives us. On the other hand, it adds considerably complexity. What I would ask is do you think this system of callbacks is better than injecting the type information in a wrapping layer? Something like this:

```swift
class GitHubClient {
  let provider = MoyaProvider<GitHubApi>()

  func getZen(completion: (Result<String, Error>) -> Void) {
    provider.request(.zen) { completion(parseString($0)) } // using your `parseString` function
  }
}
```

I understand this approach is removing the return type information from the `TargetType` by a degree, but I think the advantage is a simpler `TargetType` set up and simplicity at the call site while not expanding the API surface area.

**Comment by scottrhoyt** [comment]
The other advantage to the wrapper approach is that the pattern is compatible with `RxMoyaProvider` and `ReactiveMoyaProvider`. It is hard for me to see the direct analog for the callback solution you proposed.

**Comment by michaelsand** [comment]
How it would work with ReactiveSwift and RxSwift was a question, and while it seems like a classic case for lenses, looking more closely I wasn't able to come up with a way to implement them for this enum-associated-type-completion approach. 

I agree looking again the API is more complex than it should be. The wrapper solution of course occurred to me also, but it's unsatisfying, little more then inviting people to make wrapper layer to go the last mile. Notably, they're not connected to enum cases in any way except that they use them--definitely better than nothing, but not up to the rest of Moya standard for organization. 

However, taking another look now a better solution occurred to me: I had been resisting using `Any` -- really resisting, because I thought it would defeat the purpose. In addition, as said before, a generic function return of `T` can't return a specific type, since that would break the API contract (although if the only use of `T` is for the return type it technically should be allowed, but the compiler has enough problems with generics already I'm not complaining). 

But there's nothing to prevent a generic function from immediately casting `anAny as? T` which gets exactly the same safety, and a lot better API.

The parse function in `TargetTypeWithParser `, stripped to essentials: 
```
    //In Target : TargetTypeWithParser
    public func parse(_ response: Moya.Response) throws -> Any  {
        switch self {
        case .zen(_):
            return GitHub.parseString(from: response)
        case .userProfile(_, _):
            return GitHub.parseDictionary(from: response)
        case .userRepositories(_, _):
            return GitHub.parseNSArray(from: response)
        }
    }
```
And in `extension MoyaProvider where Target: TargetTypeWithParser`:

```
    func parseAndComplete<T>(with target: Target, from response: Moya.Response, completion: (Result<T, MoyaError>) -> Void) {
        do {
            guard let parsed = try target.parse(response) as? T else {
                throw MoyaError.stringMapping(response) //Error approximate for demonstration
            }
            completion(Result(value: parsed))
        } catch let error as MoyaError {
            completion(Result(error: error))
        } catch {
            completion(Result(error: MoyaError.underlying(error)))
        }
    }
``` 

It should be trivial to use the same parser create an equivalent method/s for a lens for a `SignalProvider<Moya.Response, MoyaError>` to `SignalProvider<T, MoyaError>`, or have a typed signal response, etc.

**Comment by michaelsand** [comment]
Actually I realize one drawback is you could call the MoyaProvider function with a completion block that took a result of any type-- the compiler wouldn't enforce the type. I don't like that it's possible to use the API incorrectly, but you would get the string mapping error above on casting, and maybe an AssertionFailure() for development there would be worthwhile. 

It's possible this could be addressed with a Swft equivalent of Objective C class object but more research is required. Regardless, this still additive change would bring better completion blocks.

**Comment by scottrhoyt** [comment]
That is an interesting idea. However, if the `parseAndComplete` `completion` isn't strongly typed, then you still need to supply the type information for the response deserialization at the call site with no compile-time guarantees. In general, that is a similar situation as we are in right now when using the Moya extensions for object deserialization. 

Also, while it is a natural extension to have a `TargetType` provide information on what return type is expected, I think it might be going too far to have `TargetType` also provide the information on how to deserialize a `Response`. Right now `TargetType` knows nothing about how requests are processed, and this proposal would suggest that it become aware of at least `Response` and the mechanisms used to deserialize it (likely a 3rd party library). This responsibility seems better placed at the `MoyaProvider` layer or above.

The proposal then comes down to:
1. Establish a way to document what return type is expected in `TargetType`
2. Provide better completion handler usability for `MoyaProvider` when both the return type and method of deserialization are known

I think 1 can be accomplished in any number of ways. I would say 2 is up to the creators of Moya extensions since I don't see any reason why they can't create a similar extension on `MoyaProvider`.

Because of the impedance mismatch between a weakly typed internet and a strongly typed Swift, it will always be incumbent on the developer to introduce the specific knowledge necessary to resolve that discrepancy. I sadly don't see a way of ever providing a generic construct for that if the tool is an `enum`.

**Comment by michaelsand** [comment]
It does appear with `enum` the only way to get the compile-time type safety is to include the completion block in the associated type, which I think is worth it but as you noted among other issues is incompatible with the reactive versions. I'll look into the best way to position it outside the core project. 

I investigated the equivalent of Objective C `class` object, which is bridged to Swift as `AnyClass.Type`, and so would be used as `Any.Type`. Unfortunately this didn't work (image to include playground output):

<img width="771" alt="screen shot 2017-02-03 at 12 44 35 pm" src="https://cloud.githubusercontent.com/assets/6426698/22602645/0d495362-ea12-11e6-960c-30cf184e4a4b.png">

Even though it has got `String.Type` by the time it's passed to the generic function, the compiler apparently can't match that to the closure parameter of `String`. (The same happened when passing a matching instance returned from `Any`.) Something maybe worth taking up within Swift itself.

So in @scottrhoyt 's formulation 1, 2,  it seems 1 is at a dead end. For 2, I actually have a lighter approach that uses generic functions that meets that goal exactly. It leaves out the `TargetType` entirely -- which you I think would consider a plus -- so I'll open a new issue for that. Cheers.
