### ISSUE TITLE
Is my way to put header to Moya correct format ?

### ISSUE THREAD

**Issue by abadikaka** [Moya/Moya#955]
Hi i am using latest moya. i want to ask how to put header field ?, i am trying like this one but always return 400. If my way is correct probably the header content is wrong.. Just want to make sure

```swift
let endpointClosure = { (target: API) -> Endpoint<API> in
            let defaultEndpoint = RxMoyaProvider.defaultEndpointMapping(target)
            return defaultEndpoint.adding(newHttpHeaderFields: ["Accept": "application/json", "Content-Type" : "application/json", "Authorization" : token!, "X-Fingi-Signature":authSign as String])
        }
        self.provider = RxMoyaProvider<API>(endpointClosure: endpointClosure)
```

**Comment by pedrovereza** [comment]
@abadikaka You can use the `NetworkLoggerPlugin` to make sure your request are being sent as expected:

```swift
self.provider = RxMoyaProvider<API>(endpointClosure: endpointClosure, 
                                    plugins: [NetworkLoggerPlugin(verbose: true)])
```

This will log details about every request :wink:

**Comment by abadikaka** [comment]
Thanks @pedrovereza  !.. Yes my body request somehow is not correct... and the parameters encoding i need use JSONEncoding but it need to be set in the endpointclosure.. Thank you it very helps me
