### ISSUE TITLE
Using data from bundle as sampleData from tutorial Basic.md

### ISSUE THREAD

**Issue by moonorblue** [Moya/Moya#958]
Hi,

I am new to Moya and Swift. Using Swift 3 and Moya  8.0.2
With the instruction in Basic.md, I tried to load some file from bundle as the the **sampleData** in TargetType
like this
```swift
var sampleData: Data {
        switch self {
            case .showAccounts:
                guard let path = Bundle.main.path(forResource: "myjson", ofType: "json"),
                    let data = Data(base64Encoded: path) else {
                        return Data()
                }
                return data
            .....
        }
```
but it always return nil data from **Data(base64Encoded: path)**
However, I change to code like follow, then it will return encoded data
```swift
var sampleData: Data {
        switch self {
            case .showAccounts:
                let path = Bundle.main.path(forResource: "myjson", ofType: "json")
                let url = URL(fileURLWithPath: path!)
                let data = try! Data(contentsOf: url)
                return data
            .....
        }
```
Am I using the **Data(base64Encoded: path)** in a wrong way?
Thank you

**Comment by scottrhoyt** [comment]
Hey @moonorblue. It would be unlikely that your data was base64 encoded unless you explicitly put it that way. I think what you most likely want is:

```swift
let string = String(data: data, encoding: .utf8)
```

Alternatively you can put a helper function in `TargetType` for that. You can check out how that was done in this PR: #881.

**Comment by moonorblue** [comment]
Thanks ! @scottrhoyt . The helper function in the PR is what I need !
However, I look at the code at https://github.com/Moya/Moya/blob/master/docs/Examples/Basic.md
that says
```
case .showAccounts:
            // Provided you have a file named accounts.json in your bundle.
            guard let path = Bundle.main.path(forResource: "accounts", ofType: "json"),
                let data = Data(base64Encoded: path) else {
                    return Data()
            }
            return data
        }
```
Will it return the **Data** of the file ?
Since it pass a path (e.g. \xxx\xxx\xxx\accounts.json) into **Data(base64Encoded: )**,
which the input should be some `Base-64 encoded String` or `Base-64, UTF-8 encoded Data`

**Comment by scottrhoyt** [comment]
Oh, yeah @moonorblue. Sorry, disregard what I said about the `String` transform. My head was stuck in my own project. You just need to return the `Data` so just use `Data(contentsOf:)`. Copy and pasting that code from the PR should work fine for you.

**Comment by moonorblue** [comment]
Many thanks @scottrhoyt  ;)
