### ISSUE TITLE
Response should have destinationURL

### ISSUE THREAD

**Issue by fjcaetano** [Moya/Moya#959]
I believe that Moya's Response should have a property called `destinationURL` much like Alamofire's response.

I'm trying to migrate a piece of code from `Alamofire.download` to the `.download` task and I've noticed that the response object does not have the destination path to where the downloaded file has been moved to.

I'm not sure if `temporaryURL` should also exist in the Response, but I believe it's a no-brainer.

**Comment by scottrhoyt** [comment]
@fjcaetano, I am having a bit of a hard time wrapping my head around the use case and implications of introducing this since I don't normally use download tasks in Moya. If the solution is pretty straightforward, what do you think about opening up a PR with the feature to further discussion?

**Comment by fjcaetano** [comment]
@scottrhoyt, typically, when downloading some data and saving it in a device, it is important to know the path in which that data was stored. That's where `destinationURL` is necessary.

I solved it trivially, but I believe the solution is something that must be discussed. For starter, Alamofire has two typical response types: `DownloadResponse` and `DataResponse`. Naturally, `destinationURL` is a property of the former. So, if we add `destinationURL` to the single response type in Moya, that property will be available even when it doesn't make sense to have it. So should it really be in the `Response` class? I think it does for simplicity of access and solution.

Secondly, how would one stub such request? Should it even be stubbed? Once again, my approach to this was to add another parameter to the response cases of `EndpointSampleResponse` representing an optional URL which is interpreted as a possible mocked destination URL:
``` swift
/// Used for stubbing responses.
public enum EndpointSampleResponse {

    /// The network returned a response, including status code, data, and destination URL of downloaded data.
    case networkResponse(Int, Data, URL?)

    /// The network returned response which can be fully customized.
    case response(HTTPURLResponse, Data, URL?)

    /// The network failed to send the request, or failed to retrieve a response (eg a timeout).
    case networkError(NSError)
}
```

I'll submit a PR right now, but I'd love to get some opinions about these.

**Comment by sunshinejr** [comment]
Closing this one in favor of #968.
