### ISSUE TITLE
Getting error "Argument labels don't match available overloads" trying to add HTTP header.

### ISSUE THREAD

**Issue by dannymout** [Moya/Moya#961]
I'm using Moya 8.0.1, Swift 3. I'm trying to add an HTTP header, and I'm using this code from the docs.

````swift
let endpointClosure = { (target: MyTarget) -> Endpoint<MyTarget> in
    let defaultEndpoint = MoyaProvider.defaultEndpointMapping(target)
    return defaultEndpoint.adding(newHttpHeaderFields: ["APP_NAME": "MY_AWESOME_APP"])
}
````

But, I'm getting this error: `Argument labels '(newHttpHeaderFields:)' do not match any available overloads`

**Comment by BasThomas** [comment]
The right signature for that function is `adding(newHTTPHeaderFields)`, wherein "HTTP" is fully capitalized. It was recently changed and it seems we forgot to update the documentation.  Could you make a PR to change the docs?

If not, don't worry - we'll get on it.

**Comment by dannymout** [comment]
@BasThomas Sure I'll update the docs.
