### ISSUE TITLE
does not conform to protocol 'TargetType in swift 3

### ISSUE THREAD

**Issue by 974929538** [Moya/Moya#964]
I think I probably don't need this method But if I deleted he appears does not conform to the protocol 'TargetType' if you don't delete I don't know how to implement the method
![Uploading 3.43.47.png…]()

**Comment by 974929538** [comment]
`extension ApiService:TargetType{
    
    /// The type of HTTP task to be performed.
    public var task: Task {
    }

    /// Provides stub data for use in testing.
    public var sampleData: Data {
        switch self {
        case .upload:
            return "".data(using: String.Encoding.utf8)!
        }
    }

    /// The method used for parameter encoding.
    public var parameterEncoding: ParameterEncoding {
        return URLEncoding.default
    }

    public var baseURL: URL { return URL(string: "https://upload.giphy.com")! }
    public var path: String {
        switch self {
        case .upload:
            return "/v1/gifs"
        }
    }
    public var method: Moya.Method {
        switch self {
        case .upload:
            return .post
        }
    }
    public var parameters: [String: Any]? {
        switch self {
        case .upload:
            return ["api_key": "dc6zaTOxFJmzC", "username": "Moya"]
        default:
            return nil
        }
    }
}`

**Comment by BasThomas** [comment]
Hey, what method is it you are talking about? It seems like your image didn't get uploaded.

**Comment by 974929538** [comment]
I said is a task of this method, I think you just need to return, the request should be ok

**Comment by BasThomas** [comment]
For `task`, you normally return `.request`: https://github.com/Moya/Moya/blob/master/docs/Examples/Basic.md#basic-usage

**Comment by bjarkehs** [comment]
@974929538 You need to say what kind of `task` your request is. In most cases you can just use:

```swift
public var task: Task {
    return .request
}
```

**Comment by 974929538** [comment]
Thank you very much A very awkward question😅

**Comment by BasThomas** [comment]
Did that resolve your issue? :)

**Comment by 974929538** [comment]
Has been resolved But I met a new problem again Forgive me, I am a little shrimp only half a year work experience My question is when I will "responsetor" into "Moya. Response" throw an error
`extension Observable{
    private func resultFormJson<T:Mapable>(jsondata:JSON,classType:T.Type) -> T?{
        return T(json:jsondata)
    }
    func mapResponseToArray<T:Mapable>(type:T.Type) -> Observable<[T]>{
        return map{ responsetor in
            
            guard let response = responsetor as? Moya.Response else{
                
                throw VendingMachineError.ConversionError
            }
            
            let json = JSON.init(data: response.data)
            
            if let code = json["resultcode"].int{
                if code == 200 {
                    var objects = [T]()
                    let arr = json["result"].array
                    if let array = arr{
                        for object in array{
                            if let obj = self.resultFormJson(jsondata: object, classType: type){
                                objects.append(obj)
                            }
                        }
                        return objects
                    }else{
                        throw VendingMachineError.ParseError
                    }
                }else{
                    throw VendingMachineError.insufficientFunds(coinsNeeded: code)
                }
            }else{
                throw VendingMachineError.ParseError
            }
        }
    }
}`

**Comment by 974929538** [comment]
```swift
import Foundation
import RxSwift
import Moya


class TestVM {
    let apiProvider = RxMoyaProvider<ApiService>()
    let backDate = Variable<[FoodTestModel]>([])
    let request = Variable<String>("")
    let disposeBag = DisposeBag()
    
    
    
    
    init(){
        
        let request = self.request.asObservable().map{ city in
            
           return self.apiProvider.request(.upload(cityname: city))
            
        }.shareReplay(1)
            
         let response = request.mapResponseToArray(type: FoodTestModel.self).shareReplay(1)
        
        
        response
            .asObservable()
            .subscribe(onNext: { result in
                
                self.backDate.value = result
                
            }, onError: {error in
                
                print(error)
                
            }).addDisposableTo(disposeBag)
    }
    
}
```

**Comment by 974929538** [comment]
```swift
class ViewController: UIViewController {
    
    var testvm:TestVM?

    override func viewWillAppear(_ animated: Bool) {
        testvm = TestVM()
        testvm?.request.value = "北京"
    }
    override func viewDidLoad() {
        super.viewDidLoad()
//        let apiProvider = RxMoyaProvider<ApiService>()
//        apiProvider
//            .request(.upload(cityname: "北京"))
//            .subscribe{event in
//                switch event{
//                case .next(let data):
////                    data.
//                    let json = JSON.init(data: data.data)
//                    print(json)
//                case .error(let error):
//                    print(error)
//                default:
//                    break
//                }
//        }.addDisposableTo(disposeBag)
        
    }
    
    func bulidVm(){
        
        self.testvm?.backDate.asObservable().subscribe(onNext: { result in
            
            print(result)
            
        }).addDisposableTo(disposeBag)
    }
```
