### ISSUE TITLE
Documentation for swift 2.2

### ISSUE THREAD

**Issue by sandeepbol** [Moya/Moya#970]
I am using Moya 7.0.0 in Xcode 7.3.1 with swift 2.2. I know very little about swift 3 and corresponding equivalent syntax of swift 3 in swift 2.2. The documentation that I found for Moya is in swift 3. It is a general problem with many excellent libraries that have migrated to swift 3 that it is hard to find documentation for swift 2.2. I have been too lazy to do the migration as I have many pending projects that I have written using swift 2.2 that have grown considerably in size. 

What is the advisable strategy here? It may come across as a very layman question but any suggestion/advice will help me forward fast. Thanks in advance.

**Comment by bjarkehs** [comment]
All documentation should still be available at corresponding tag: https://github.com/Moya/Moya/tree/7.0.4

**Comment by BasThomas** [comment]
You beat me to it, @bjarkehs. 😅

**Comment by bjarkehs** [comment]
I was not busy labelling @BasThomas 😉

**Comment by BasThomas** [comment]
🤔, `7.0.4` actually targets Swift 2.3. I think the documentation over at https://github.com/Moya/Moya/tree/7.0.1 is better for Swift 2.2.

**Comment by bjarkehs** [comment]
Yeah, I just realized this when reading your PR. And I was just about to write it, so this time you beat me to it.

**Comment by sandeepbol** [comment]
Thanks a lot guys! Long live open source and open source lovers!! :)

**Comment by sandeepbol** [comment]
Guys, which objectmapper to use for swift 2.2? I am using swiftyjson to parse my json response. Every library seem to have been updated to swift 3. Guess its time to stop being lazy and move on to swift 3 :(

Thought it might be related to this thread as didn't want open a new one.

**Comment by BasThomas** [comment]
Go ahead and update to Swift 3. You won't regret it. In the meantime, you could of course use an older version of the Object Mapper as well, such as [v1.0.5](https://github.com/AvdLee/Moya-SwiftyJSONMapper/releases/tag/1.0.5) of the SwiftyJSONMapper?
