### ISSUE TITLE
Nested Parameters

### ISSUE THREAD

**Issue by albertml** [Moya/Moya#972]
How to setup nested parameters in Moya?

This is my parameters in moya:

return ["notification": ["title": "asdfasdfasdf", "body": "jlgjkl", "badge": "3"], "to": "receiverTokenHere"]

And this will be the return body in my logs, the format is different already:

notification%5Bbody%5D=asdfasdf&notification%5Btitle%5D=Albert%20send%20you%20message&notification%5Bbadge%5D=3&to=receiverTokenHere"]

I want to be formatted like this: 

{ "notification": {
    "title": "asdfasdfasdf",
    "body": "jlgjkl",
    "badge": "3"
  },
  "to" : "receiverTokenHere"
}

Thanks...

**Comment by pedrovereza** [comment]
Hey @albertml, if I understood correctly, you want the parameters to be sent as JSON instead of having them in the URL. Is that correct?

If so, you should use `JSONEncoding.default` as your `parameterEncoding`, e.g.:

```swift
public var parameterEncoding: Moya.ParameterEncoding { return JSONEncoding.default }
```

**Comment by albertml** [comment]
hey @pedrovereza , my parameters will never be like this also?

return ["notification": ["title": "asdfasdfasdf", "body": "jlgjkl", "badge": "3"], "to": "receiverTokenHere"]

**Comment by albertml** [comment]
hey @pedrovereza, yeah you are right... I forgot to call the parameter encoding that's why it is happen... its working now. thanks
