### ISSUE TITLE
I want to abort the request and show message for user when the parameters is incorrect, How can I do?

### ISSUE THREAD

**Issue by shuijinliuxi** [Moya/Moya#974]
In my project, the all request have the same parameters（eg: key and consId）, I want to put those parameters in var parameters: [String: Any]?, but abort the request and push some alert view when the key and consId is empty.

**Comment by pedrovereza** [comment]
Hey @shuijinliuxi, can you test if the parameters are valid before making the request? Something like:

```swift
if (parameterAreValid(key, id: consId) {
  provider.request ... // Make request here
}
else {
  //show alert
}
```

**Comment by shuijinliuxi** [comment]
@pedrovereza  I am doing this at the moment, tks.
