### ISSUE TITLE
How to use Moya to ask infinite url in my JSON response with RxSwift?

### ISSUE THREAD

**Issue by YueJun1991** [Moya/Moya#980]
Moya version: 8.0.2

There is my code:
```swift
MooProvider<MooApi>(token: accessToken)
      .request(.libraryBooks)
      .filterSuccessfulStatusAndRedirectCodes()
      .mapObject(type: JSONDocumentManyObjects<LibraryItem>.self)
      .subscribe { event in
        switch event {
        case .next(let element):
          print("next: \(element.url)")
        case .error(let error):
          print("error: \(error)")
        case .completed:
          print("completed")
        }
      }
      .addDisposableTo(disposeBag)
```

In the `JSONDocumentManyObjects`, the object has the next api url. So I need to use that to request again, and with the same JSON parser, the same request, the same flow until I can't find the next url.

Should I use a `Variable` with an url value? But how can the url match my API case? 

Thanks for your help.

**Comment by scottrhoyt** [comment]
The main issue for you is to solve having a `TargetType` with a dynamic `baseURL`. Some ideas on how to do this are covered in #978. For the purposes of this example I am going to assume you have a `struct MooApi: TargetType` that takes a `URL?` to use as it's `baseURL`. If given `nil` it  has access to a default `URL`. Then it would look something like this:

```swift
struct MooApi: TargetType {
  let defaultURL = < defaultURL >
  let url: URL?

  var baseURL: URL { return url ?? defaultURL }

  /* TargetType */
}

let provider = MooProvider<MooApi>(token: accessToken)

func followTheURLs(url: URL? = nil) -> Observable<JSONDocumentManyObjects<LibraryItem>> {
  return provider.request(MooApi(url: url))
    .filterSuccessfulStatusAndRedirectCodes()
    .mapObject(type: JSONDocumentManyObjects<LibraryItem>.self)
    .flatMap { jsonDocumentManyObjects in
      if let url = jsonDocumentManyObjects.nextURL {
        return followTheURLs(url: url)
      } else {
        return Observable.just(jsonDocumentManyObjects)
      }
    }
}

followTheURLs()
      .subscribe { event in
        switch event {
        case .next(let element):
          print("next: \(element.url)")
        case .error(let error):
          print("error: \(error)")
        case .completed:
          print("completed")
        }
      }
      .addDisposableTo(disposeBag)
```

Now a couple of points:
  * If your `MooApi` has different endpoints then you'll need an additional strategy here. Look at #978 for ideas.
  * I'm not exactly sure about how this recursive flat mapping will propagate errors. You'll want to test that.
  * It might be possible to instead do this with an Observable of Observables, but I'm not sure it would be much simpler.

**Comment by YueJun1991** [comment]
Hi, @scottrhoyt thanks for your answer. Change my TargetType to a struct is much better.
I will try this method, thanks!
