### ISSUE TITLE
Statistical Metrics

### ISSUE THREAD

**Issue by roisagiv** [Moya/Moya#987]
Hi, Using Moya v8.0.2

What would be the best to collect statistics regard request and response timing?
Is there a way to get to the underline Alamofire response and access the [timeline property](https://github.com/Alamofire/Alamofire#statistical-metrics)?

Thanks!

**Comment by shannonchou** [comment]
@roisagiv  You can get URLSessionTaskMetrics like this: #2073 (comment)
