### ISSUE TITLE
When making a request, how can I see the request URL?

### ISSUE THREAD

**Issue by dannymout** [Moya/Moya#988]
I'm making a request in Moya, I'd like to see the request URL, is this possible?

**Comment by scottrhoyt** [comment]
Do you mean logging it to the console? If so, checkout `NetworkLoggingPlugin`.

**Comment by dannymout** [comment]
@scottrhoyt If you don't mind, how would I use `NetworkLoggingPlugin` to do what I need to do?

**Comment by scottrhoyt** [comment]
Sure, you just initialize a `NetworkLoggingPlugin` and pass it to the `plugins` parameter of your `MoyaProvider` initializer. (e.g. `plugins: [NetworkLoggingPlugin()]`).

**Comment by dannymout** [comment]
How would I get the request URL? @scottrhoyt

**Comment by gperdomor** [comment]
@dannymout in Xcode console log

**Comment by dannymout** [comment]
@scottrhoyt @gperdomor Perfect. Didn't know that is how it worked, thanks.
