### ISSUE TITLE
Module file's minimum deployment target is ios9.0 v9.0

### ISSUE THREAD

**Issue by coderRMS** [Moya/Moya#991]
Using Moya (8.0.0-beta.6)
class Endpoint   import Alamofire  here showing

**Comment by BasThomas** [comment]
What are you referring to exactly? Where do you get an error?

**Comment by BasThomas** [comment]
Also, which dependency manager are you using?

**Comment by AndrewSB** [comment]
This looks like an old release, hopefully everything should be fixed in our latest. Please reopen if you're still having issues @coderRMS!
